/* Прототип «источники крупнее»: три существа Замка в сетке 40–64 вместо 20–32.
   Не подключён к игре — только для листа сравнения (dev/sheet.html?files=../dev/proto/big.js). */
(function () {
  'use strict';
  H3.Sprites.defineMany({
    /* копейщик 40×48: шлем-котелок с полями и заклёпками, лицо, кольчужные рукава, туника с
       гербом, пояс с пряжкой, круглый щит за спиной, копьё с наконечником и обмоткой */
    big_pikeman: {
      hd: true, unit: 2,
      rows: [
        '.................................kk.....',
        '................................klwk....',
        '................................kllek...',
        '................................kleek...',
        '...............kkkkkkkkk........kleEk...',
        '.............kkeeeeeeeeekk......kkEEk...',
        '............keeelllleeeeeek......kek....',
        '...........keeelllleeeeeeeek.....kek....',
        '...........keeeeeeeeeeeeEEek.....kNk....',
        '..........kkeeeeeeeeeeeeEEEkk....kNk....',
        '..........kEkEkEkEkEkEkEkEkEk....kNk....',
        '..........kkkkkkkkkkkkkkkkkkk....kTk....',
        '.............kSsssssssssSk.......kTk....',
        '.............kssswkkwsssSk.......kNk....',
        '.............ksskkkkkksssk.......kNk....',
        '.............ksssssssSsssk.......kNk....',
        '.............kSsssSSSssSSk.......kNk....',
        '..............kSssSSSSsSk........kNk....',
        '...............kkSSSSSkk.........kTk....',
        '.........kkkkkkkkkEEkkkkkkkkk....kTk....',
        '.......kkbbbbbbbbkEEkbbbbbbbbkk..kNk....',
        '......kbbbBbbbbbkkkkkbbbbbBbbbk..kNk....',
        '.....kbbBbkkkbbbbbbbbbbbkkkbBbbk.kNk....',
        '....kbbBbkeEekbbbyybbbbkeEekbBbbk.kNk...',
        '....kbBbkeEeEekbbyyybbbkEeEekbBbbkkNk...',
        '....kbBbkEeEeEkbyyYyybbkeEeEkbBbbkssk...',
        '....kbBbkeEeEekbbyyybbbkEeEekbBbksSsk...',
        '....kbBbkEeEeEkbbbyybbbkeEeEkbBbkSSsk...',
        '....kbBbbkeEekbbbbbbbbbbkeEekbBbkkkkk...',
        '....kbBBbbkkkbbbbbbbbbbbbkkkbbBBk.......',
        '.....kBBbbbbbbbbbbbbbbbbbbbbbBBk........',
        '.....kkBBBbbbbbbbbbbbbbbbbbBBBkk........',
        '......kNNNNNNNNNNNNNNNNNNNNNNNk.........',
        '......kNnnnnnnnnkyykknnnnnnnnNk.........',
        '......kNNNNNNNNNkyykkNNNNNNNNNk.........',
        '......kkkkkkkkkkkkkkkkkkkkkkkkk.........',
        '.......kbbbbbbbkk...kkbbbbbbbk..........',
        '.......kbbBbbbbk.....kbbbbBbbk..........',
        '.......kbBBbbbbk.....kbbbbBBbk..........',
        '.......kbBBBbbbk.....kbbbBBBbk..........',
        '.......kBBBBBbbk.....kbbBBBBBk..........',
        '.......kkkkkkkkk.....kkkkkkkkk..........',
        '......kNnnnnnnnNk...kNnnnnnnnNk.........',
        '......kNnnNNnnnNk...kNnnnNNnnNk.........',
        '.....kkNNNNNNNNNkk.kkNNNNNNNNNkk........',
        '.....kDDDDDDDDDDDk.kDDDDDDDDDDDk........',
        '.....kkkkkkkkkkkkk.kkkkkkkkkkkkk........',
        '........................................',
      ],
    },
    /* грифон 60×56: собран композитором — крылья веером от лопаток, перья по краю, львиное тело, орлиная голова */
    big_griffin: {
      hd: true, unit: 2,
      rows: [
        '............................................................',
        '..............................kkkkkkk.......................',
        '.......................kkkkkkknnnnnnnk......................',
        '............kkkkk.....knnnnnnnnnnnnnnnk.....................',
        '........kkkkNNNNNk....knnnnnnnkkkkknnnnk....................',
        '....kkkkNNNNNNNNNNk...knnnnnnnkTTTkkknnnk...................',
        '...kNNNNNNNNNNNNNNNk.knnnnnkkkTTTTTTkkknnk............k.....',
        '...kNNNNNNNNNNNNNNNNkknnnnnkTTTTTTTTTTkknnk..k.......kwk....',
        '..kNNNNNNNNNNNNNNNNNkknnkkkTTTTTTTTTTTTkkkkkkwk......kwk....',
        '..kNNNNNNkNNNNNNNNNNNnnnkTTTTTTTTTTTTTTTTTknkwwk....kwwk....',
        '..kNNNNNNkNNNNNNNNNNNnnnkTTTTTTTTTTTTTTTTTknnkwwk...kwwk....',
        '..kNNNNNNNNNNNNNNNNNnnnnkTTTTTTTTTTTTTTTTTknnkkwwk.kwwwk....',
        '...kNNNNNNNNNNNNNNNNnnnnkkTTTTTTTTTTTTTTTknnnnkwwwkkwwwk....',
        '....kkNNNNNNNNNNNNNNnnnnkTTTTTTTTTTTTTTTTknnnnkwwwwwwwwk....',
        '.....kNNNNNNNNNNNNNNnnnnkTTTTTTTTTTTTTTTTknnnnkkwwwwwwwk....',
        '.....kNNNNNNkNNNNNNNnnnnkTTTTTTTTTTTTTTTTknnnnkwwwwwwwwwk...',
        '.....kNNNNNNNNNNNNNNNnnnkTTTTTTTTTTTTTTTTknnnkwwwwwzwwwwwk..',
        '......kNNNNNNNNNNNNNNnnnkkTTTTTTTTTTTTTTTkknnkwwwwwzzwwwwk..',
        '.......kNNNNNNkNNNNNNNnnnkTTTTTTTTTTTTTTTTknnkwwwwwwwwwwyykk',
        '.......kNNNNNNNNNNNNNNnnnkkTTTTTTTTTTTTTTTknnkwwwwwwwwwwyyyy',
        '.......kNNNNNNNNNNNNNNnnnnkTTTTTTTTTTTTTTTkkkwwwwwwwwwwwyyyy',
        '.......kNNNNNNNNNNNNNNNnnnkTTTTTTTTTTTTTTwkwwwwwwwwwwwwwyyYY',
        '........kNNNNNNNNNNNNNNnnnkkTTTTTTTTTTTTwwwwwwwwwwwwwwwwyykk',
        '.........kkNNNNNNNNNNNNNnnnkTTTTTTTTTTTwwwwwwwwwwwwwwwwkkk..',
        '....kk....kNNNNNNNNNNNNNnnnkTTTTTTTTTTTwwwwwwwwwwwwwwwk.....',
        '...kNNk...kNNNNNNNNNNNNNNnnkkTTTTTTTTTTwwwwwwwwwwwkkkk......',
        '..kNNNNk...kNNNNNNNNNNNNNnnnkTTTTTTTTkkkwwwwwwwwwwwk........',
        '.kNNNNNNk...kkNNNNNNNNNNNNnnkkTTTTTkknnkwwwwwwwwwwwk........',
        '.kNNNNNNk....kNNNNNNNNNNNNnnnkTTTkknnnnkkwwwwwwwwwwk........',
        '..kNNNNTk.....kNNNNNNNNNNNnnnkTkknnnnnnnkwwwwwwwwwwk........',
        '...kNNTTTk.....kNNNNNNkkkkkknkknnnnnnnnnkkwwwwwwwwwk........',
        '....kkTTTTk....kNNNkkktttttknnnnnnnnnnnnnkkwwwwwwwk.........',
        '......kTTTTk....kNkttttttttknnkkkkkknnnnNnkkwwwwwk..........',
        '.......kTTTTk..ktkttttttttknnnkkttknnnnNNNnkkkwkkk..........',
        '........kTTTTkkttttttttttknnnnnkkknnnnnnNNnnkkkttk..........',
        '.........kTTTTktTTTTTTTTtknnnnnnkknnnnnnNNnktttttk..........',
        '..........kTTTTTTTTTTTTTTknnNNnnkknnNNnnnnkttttttk..........',
        '...........kTTTTTTTTTTTTTknNNNnnkknNNNnnkkttttttk...........',
        '...........kTTTTTTTTTTTTTkkNNNnktkkNNNnktttttttk............',
        '...........kTTTTTTTTTTTTTTkkNNnkttkkNNnkttttttk.............',
        '...........kTTTTTTTTTTTTTTTkTTkttttkkkkttttttk..............',
        '...........kTTTTTTTTTTTTTTTTTTTTTTTTTTtttttkk...............',
        '............kTTTTTTTTTTTTTTTTTTTTTTttttTtttttkk.............',
        '.............kTTTTTTTTTTTTTTTTTTTTTttttttktttttk............',
        '.............kTTTTTTTTTTTTTTTTTTTTTttttttktttttk............',
        '.............kTTTTTTTtttttTTTTTTTTTttttttktttttk............',
        '.............kTTTTTTTtttttTTTTTTTTTttttttktttttk............',
        '.............kTTTTTTktttttkkkkkkkkkttttttktttttk............',
        '.............kTTTTTTktttttk......kttttttkktttttk............',
        '............kTTTTTTkktttttk......kttttttkktttttk............',
        '............kTTTTTTkktttttk......kttttttkktttttk............',
        '...........kyyyyyyykyyyyyyyk....kyyyyyyykyyyyyyyk...........',
        '...........kyyyyyyykyyyyyyyk....kyyyyyyykyyyyyyyk...........',
        '...........kyyyyyyykyyyyyyyk....kyyyyyyykyyyyyyyk...........',
        '............kkkkkkk.kkkkkkk......kkkkkkk.kkkkkkk............',
        '............................................................',
      ],
    },
    /* ангел 64×64: нимб, лицо с волосами, два крыла с тремя рядами перьев, золотые латы
       с наплечниками и гербом, пояс, юбка из пластин, светящийся меч, поножи */
    big_angel: {
      hd: true, unit: 2,
      rows: [
        '..........................kkkkkkkkkkk...........................',
        '........................kkyyyyyyyyyyykk.........................',
        '.......................kyyyykkkkkkkyyyyk........................',
        '.......................kyykk.......kkyyk........................',
        '.......................kkk...........kkk........................',
        '.....kk....................kkkkkkkk....................kk.......',
        '....kwwk.................kkyyyyyyyykk.................kwwk......',
        '...kwwwwk...............kyyYyyyyyyyyyk...............kwwwwk.....',
        '..kwwwwwwk.............kyYyyyyyyyyyyyyk.............kwwwwwwk....',
        '..kwwwwwwwk............kyysssssssssyyyk............kwwwwwwwk....',
        '.kwwwLwwwwwk...........kysssswkkwssssyk...........kwwwwLwwwk....',
        '.kwwwLLwwwwwk..........kysskkkkkkkkssyk..........kwwwwLLwwwk....',
        '.kwwwLLLwwwwwk.........kySsssssSsssssyk.........kwwwwLLLwwwk....',
        '.kwwwLLLLwwwwwk........kkSsssSSSsssssSk........kwwwwLLLLwwwk....',
        '.kwwwLLLLLwwwwwk........kkSSssssssSSkk........kwwwwLLLLLwwwk....',
        '.kwwwLLLLLLwwwwwk.........kkSSSSSSkk.........kwwwwLLLLLLwwwk....',
        '.kwwlLLLLLLLwwwwwk..........kkkkkk..........kwwwwLLLLLLLlwwk....',
        '.kwwlLLLLLLLLwwwwwk.....kkkkkkkkkkkkkkk....kwwwwLLLLLLLLlwwk....',
        '.kwwlLLLLLLLLLwwwwwk..kkyyyyyyyyyyyyyyykk.kwwwwLLLLLLLLLlwwk....',
        '.kwwlLLLLLLLLLLwwwwwkkyyyyyYYyyyyYYyyyyyykwwwwLLLLLLLLLLlwwk....',
        '..kwlLLLLLLLLLLLwwwwkyyyyYYYYyyyyYYYYyyyykwwwLLLLLLLLLLLlwk.....',
        '..kwlLLLlLLLLLLLLwwwkyyyYYYYYyyyyYYYYYyyykwwLLLLLLLLlLLLlwk.....',
        '..kwlLLLlLLLLLLLLLwwkyyyyYYYYyykyyYYYYyyykwLLLLLLLLLlLLLlwk.....',
        '...kwLLLlLLLLLLLLLLwkyyyyyYYyykYkyYYyyyyykLLLLLLLLLLlLLLwk......',
        '...kwLLLlLLLLLLLLLLLkYyyyyyyykYYYkyyyyyyYkLLLLLLLLLLlLLLwk......',
        '...kwLLLlLLLlLLLLLLLkYYyyyyyykYYYkyyyyyYYkLLLLLLlLLLlLLLwk......',
        '....kLLLlLLLlLLLLLLLkYYYyyyyyykYkyyyyyYYYkLLLLLLlLLLlLLLk.......',
        '....kLLLlLLLlLLLLLLLkkYYYYyyyyykyyyyYYYYkkLLLLLLlLLLlLLLk.......',
        '....kLLLlLLLlLLLLLLLkkkYYYYYYYYYYYYYYYkkkLLLLLLlLLLlLLLk........',
        '.....kLLlLLLlLLLLLLkkkkkkkkkkkkkkkkkkkkkkkLLLLLLlLLLlLLk........',
        '.....kLLlLLLlLLLLLkkeeeeekkNNNNNNNNkkeeeeekkLLLLLlLLLlLLk.......',
        '.....kLLlLLLlLLLLkkeeeEeeekNyyyyyyNkeeeEeeekkLLLLlLLLlLLk.......',
        '......kLlLLLlLLLLkeeeEEeeekNNNNNNNNkeeeEEeeekLLLLlLLLlLk........',
        '......kLlLLLlLLLkkeeeEEeeeekyyyyyykeeeEEeeeekkLLLlLLLlLk........',
        '......kLlLLLlLLkkeeeeEEeeeekyYYYYykeeeeEEeeeekkLLlLLLlLk........',
        '.......kLLLlLLkkeeeeeEEeeeekyYYYYykeeeeeEEeeeekkLlLLLLk.........',
        '.......kLLLlLkkeeeeeeEEeeeekyYYYYykeeeeeeEEeeeekkLLLLLk.........',
        '.......kLLLLkkeeeeeeeEEeeeekyYYYYykeeeeeeeEEeeeekkLLLLk.........',
        '........kLLkkEeeeeeeeEEeeeekyYYYYykeeeeeeeeEEeeeEkkLLk..........',
        '........kkkkEEeeeeeeeEEeeeekyYYYYykeeeeeeeeEEeeeEEkkkk..........',
        '...........kEEEeeeeeeEEeeeekyYYYYykeeeeeeeeEEeeEEEk.............',
        '...........kkEEEEeeeeEEeeeekyYYYYykeeeeeeeEEEEEEEkk.............',
        '............kkEEEEEEEEEEEEEkyYYYYykEEEEEEEEEEEEEkk..............',
        '.............kkkkkkkkkkkkkkkyYYYYykkkkkkkkkkkkkk................',
        '..................kyyyyyyyykyYYYYykyyyyyyyyk....................',
        '..................kyYyyyyyykyYYYYykyyyyyyYyk....................',
        '..................kYYyyyyyykyYYYYykyyyyyyYYk....................',
        '..................kYYYyyyyykyYYYYykyyyyyYYYk....................',
        '..................kYYYYyyyykyYYYYykyyyyYYYYk....................',
        '..................kkkkkkkkkkyYYYYykkkkkkkkkk....................',
        '..................kllllllkkkyyYYyykkkllllllk....................',
        '..................klllllllkkkyyyykkklllllllk....................',
        '..................kllllllk.kkkkkkkk.kllllllk....................',
        '..................kellllek..........kellllek....................',
        '..................keellleek........keellleek....................',
        '..................keeelleek........keelleeek....................',
        '..................kEeeeeeEk........kEeeeeeEk....................',
        '..................kEEeeeEEk........kEEeeeEEk....................',
        '.................kkEEEEEEEkk......kkEEEEEEEkk...................',
        '.................kyyyyyyyyyk......kyyyyyyyyyk...................',
        '.................kkkkkkkkkkk......kkkkkkkkkkk...................',
        '................................................................',
        '................................................................',
        '................................................................',
      ],
    },
  });
  // подмена в бою для проверки интеграции: настоящие id существ указывают на крупные версии
  if (new URLSearchParams(location.search).get('hdtest')) H3.Sprites.defineMany({ pikeman: { base: 'big_pikeman' }, griffin: { base: 'big_griffin' }, angel: { base: 'big_angel' } });
})();
