# -*- coding: utf-8 -*-
"""Сборка js/view/sprites_castle_hd.js: 14 существ Замка в крупной сетке (unit 2), стиль Б —
без контура, тона кладёт рисунок. Гуманоиды — строки руками, кавалерист — композитором."""
import io, os, re, sys
sys.path.insert(0, os.path.dirname(__file__))
from compose import Canvas

def rows_from(src):
    return [l for l in src.strip('\n').split('\n')]

def pad(rows, W):
    return [(r + '.' * W)[:W] for r in rows]


def stretch(rows, target, ranges):
    """Дублирует строки из указанных диапазонов (равномерно), пока высота не достигнет target."""
    rows = list(rows)
    need = target - len(rows)
    if need <= 0: return rows
    cand = [i for a, b in ranges for i in range(a, b)]
    step = max(1, len(cand) // need)
    picks = sorted(cand[::step][:need], reverse=True)
    for i in picks: rows.insert(i, rows[i])
    return rows

def block(name, rows, comment, base=None, tint=None, extra=None, unit=2):
    if base:
        parts = ["base: '%s'" % base]
        if tint: parts.append('tint: { ' + ', '.join("%s: '%s'" % kv for kv in tint.items()) + ' }')
        if extra: parts.append('extra: [' + ', '.join('[%d, %d, \'%s\']' % e for e in extra) + ']')
        return "    /* %s */\n    %s: { %s },\n" % (comment, name, ', '.join(parts))
    W = max(len(r) for r in rows); rows = pad(rows, W)
    body = '\n'.join("        '%s'," % r for r in rows)
    return "    /* %s (%d×%d) */\n    %s: {\n      hd: true, unit: %d,\n      rows: [\n%s\n      ],\n    },\n" % (comment, W, len(rows), name, unit, body)

# читаем троих готовых из прототипа
proto = io.open(os.path.join(os.path.dirname(__file__), 'big.js'), encoding='utf-8').read()
def grab(name):
    m = re.search(r"    %s: \{\n(?:.*\n)?      rows: \[\n((?:.*\n)*?)      \]" % name, proto)
    return [r.strip()[1:-2] for r in m.group(1).split('\n') if r.strip().startswith("'")]
pikeman = grab('big_pikeman'); griffin = grab('big_griffin'); angel = grab('big_angel')

# ангел: гарда и остриё меча, зубчатый нижний край крыльев
angel = [list(r) for r in angel]
for x in range(24, 35): angel[30][x] = 'Y'                       # гарда
for y in range(43, 50): angel[y][26] = 'l'; angel[y][27] = 'w'; angel[y][28] = 'w'; angel[y][29] = 'l'   # клинок уже и с бликом
for y in range(50, 53): angel[y][27] = 'w'; angel[y][28] = 'w'; angel[y][26] = '.'; angel[y][29] = '.'
angel[53][27] = 'w'; angel[53][28] = 'l'
for x in range(8, 20, 3):                                          # зубцы перьев слева
    for y in range(36, 41):
        if angel[y][x] in 'Ll' and angel[y][x + 1] in 'Ll': angel[y][x + 1] = '.' if y > 38 else angel[y][x + 1]
angel = [''.join(r) for r in angel]

archer = rows_from("""
.............GGGGGGGGGG.................
...........GGGGGGGGGGGGGG...............
..........GGGGGGGGGGGGGGGG..............
..........GGGGGGGGGGGGGGGGG.............
.........GGGGGGGGGGGGGGGGGG.............
.........GGGGGSSSSSSSSGGGGG.............
.........GGGGSssssssssSGGGG.............
.........GGGGSsssswkwsSGGGG.............
.........GGGGSssssssssSGGGG.............
.........GGGGSSssSSSssSGGGG.............
.........GGGGGSSSssssSGGGGG.............
..........GGGGGGSSSSGGGGGG..............
...........GGGGGGGGGGGGGG...............
..........HHHHHHHHHHHHHHHH..............
........HHHHhhhHHHHHHHHHHHHH............
.......HHHHhhhhHHHHHHHHHHHHHH...........
......HHHHhhhhhHHHHHHHHHHHHHHH..........
......HHHhhhhhhHHHHHHHHHHHHHHH..........
......HHHhhhhhhHHHHHHHHHHHHHHH..........
......HHHhhhhhhHHHHHHHHHHHHHHH..........
......HHHhhhhhHHHHHHHHHHHHHHHH..........
......HHHHhhhhHHHHHHHHHHHHHHHH..........
......HHHHHhhHHHHHHHHHHHHHHHHH..........
.......HHHHHHHHHHHHHHHHHHHHHH...........
........DDDDDDDDDDDDDDDDDDDD............
........DDDDDDYYYYYYDDDDDDDD............
........HHHHHHHHHHHHHHHHHHHH............
........HHHHHHHHHHHHHHHHHHHH............
........NNnnnnnnnNNNnnnnnnnNN...........
........NNnnnnnnnN.NNnnnnnnNN...........
........NNnnnnnnnN..NnnnnnnNN...........
........NNnnnnnnnN..NnnnnnnNN...........
........NNnnnnnnnN..NnnnnnnNN...........
........NNnnnnnnnN..NnnnnnnNN...........
........NNNnnnnnNN..NNnnnnNNN...........
........NNNNnnnNNN..NNNnnNNNN...........
........NNNNNNNNNN..NNNNNNNNN...........
........DDDDDDDDDD..DDDDDDDDD...........
........DDDDDDDDDD..DDDDDDDDD...........
.......DDDDDDDDDDDD.DDDDDDDDDD..........
.......DDDDDDDDDDDD.DDDDDDDDDD..........
""")
archer = [list(r) for r in archer]
# рука вперёд к луку, лук крупнее (дуга 20 строк), тетива
for y in range(17, 21):
    for x in range(27, 33): archer[y][x] = 'S' if y in (17, 20) else 's'
bow = [(33,6),(34,7),(35,8),(36,9),(36,10),(37,11),(37,12),(37,13),(37,14),(37,15),(37,16),(37,17),(37,18),(37,19),(37,20),(37,21),(37,22),(36,23),(36,24),(35,25),(34,26),(33,27)]
for x, y in bow:
    archer[y][x] = 'N'; archer[y][x - 1] = 'n'
for y in range(7, 27):
    if archer[y][32] == '.': archer[y][32] = 'w'
# колчан за спиной
for y in range(12, 24): archer[y][4] = 'N'; archer[y][5] = 'n'
for x in (4, 5): archer[11][x] = 'l'; archer[10][x] = 'l'
archer = [''.join(r) for r in archer]
archer = stretch(archer, 48, [(13, 24), (28, 37)])

swordsman = rows_from("""
..................llllllll......................
................lleeeeeeeell....................
...............leeeeeeeeeeeel...................
...............leeeeeeeeeeeel...................
...............leeeeeeeeeeeel...................
...............EEEEEEEEEEEEEE...................
...............EzzzzzzzzzzzzE...................
...............EEEEEEEEEEEEEE...................
................EEeeeeeeeeEE....................
.................EEEEEEEEEE.....................
............lllllllleeeelllllll.................
..........lleeeeeeeeeeeeeeeeeell................
.........leeeeeeeeeeeeeeeeeeeeeel...............
........leeeeeEeeeeeeeeeeeeeEeeeel..............
.......leeeeeeEeeeRRRRRRReeeEeeeeel.............
.......leeeeeeEeeeRrrwrrrReeEeeeeel.............
.......leeeeeeEeeeRrrwrrrReeEeeeeel.............
.......EeeeeeeEeeeRwwwwwrReeEeeeeeE.............
.......EeeeeeeEeeeRrrwrrrReeEeeeeeE.............
.......EEeeeeeEeeeRrrwrrrReeEeeeeEE.............
.......EEeeeeeEeeeRRRRRRReeeEeeeeEE.............
.......EEEeeeeEEeeeeeeeeeeeEEeeeEEE.............
........EEEeeeeEEeeeeeeeeeEEeeeEEE..............
.........EEEEeeeEEEEEEEEEEEeeEEEE...............
..........EEEEEEEEEEEEEEEEEEEEEE................
...........rrrrrrrrrrrrrrrrrrrrr................
...........rrrrrrrrrrrrrrrrrrrrr................
...........RRRRRRRRRRRRRRRRRRRRR................
...........leeeeeeeel..leeeeeeeel...............
...........leeeeeeeel..leeeeeeeel...............
...........lEeeeeeeEl..lEeeeeeeEl...............
...........lEeeeeeeEl..lEeeeeeeEl...............
...........lEeeeeeeEl..lEeeeeeeEl...............
...........lEEeeeeEEl..lEEeeeeEEl...............
...........lEEEEEEEEl..lEEEEEEEEl...............
...........EEEEEEEEEE..EEEEEEEEEE...............
..........EEEEEEEEEEEE.EEEEEEEEEEEE.............
..........EEEEEEEEEEEE.EEEEEEEEEEEE.............
""")
swordsman = [list(r) for r in swordsman]
# меч поднят справа: клинок 3 px с бликом, гарда, рукоять, навершие
for y in range(1, 20): swordsman[y][38] = 'e'; swordsman[y][39] = 'w'; swordsman[y][40] = 'l'; swordsman[y][41] = 'e'
swordsman[0][39] = 'l'; swordsman[0][40] = 'l'
for x in range(35, 45): swordsman[20][x] = 'Y'; swordsman[21][x] = 'y'
for y in range(22, 27): swordsman[y][38] = 'N'; swordsman[y][39] = 'n'; swordsman[y][40] = 'n'; swordsman[y][41] = 'N'
for x in range(38, 42): swordsman[27][x] = 'Y'
# рука с перчаткой к рукояти
for y in range(15, 20):
    for x in range(33, 38): swordsman[y][x] = 'e' if y not in (15, 19) else 'E'
# щит слева: каплевидный синий с жёлтым крестом
for y in range(12, 31):
    half = 5 if y < 23 else max(0, 5 - (y - 23))
    for x in range(8 - half, 8 + half + 1):
        swordsman[y][x] = 'B' if (x == 8 - half or x == 8 + half or y == 12) else 'b'
for y in range(15, 24): swordsman[y][8] = 'y'
for x in range(5, 12): swordsman[18][x] = 'y'
swordsman = [''.join(r) for r in swordsman]
swordsman = stretch(swordsman, 50, [(11, 24), (28, 36)])

monk = rows_from("""
..................NNNNNNNN..................
...............NNNNNNNNNNNNNN...............
.............NNNNNNNNNNNNNNNNN..............
............NNNNNNNNNNNNNNNNNNN.............
............NNNNNDDDDDDDDDNNNNN.............
............NNNNDDDSSSSSDDDNNNN.............
............NNNNDDSsssssSDDNNNN.............
............NNNNDDSssswkwSDNNNN.............
............NNNNDDSsssssssDNNNN.............
............NNNNDDSSssSSSSDNNNN.............
............NNNNNDDSSSSSDDNNNNN.............
............NNNNNNDDDDDDDNNNNNN.............
.............NNNNNNNNNNNNNNNNN..............
...........NNNnnnnnnnnnnnnnnnNNN............
..........NNnnnnnTTTTTTTnnnnnnnNN...........
.........NNnnnnnnTTTTTTTnnnnnnnnNN..........
.........NnnnnnnnTTTTTTTnnnnnnnnnN..........
.........NnnnnNnnTTTTTTTnnnNnnnnnN..........
.........NnnnNNnnTTTTTTTnnnNNnnnnN..........
.........NnnnNnnnTTTTTTTnnnnNnnnnN..........
.........NnnnNnnnTTTTTTTnnnnNnnnnN..........
.........NnnnNNnnTTTTTTTnnnNNnnnnN..........
.........NnnnnNyyyyyyyyyyyyNnnnnnN..........
.........NnnnnNYyYyYyYyYyYyNnnnnnN..........
.........NnnnnnnnTTTTTTTnnnnnnnnnN..........
.........NnnnnnnnTTTTTTTnnnnnnnnnN..........
.........NnnnnnnnTTTTTTTnnnnnnnnnN..........
.........NnnnnnnnTTTTTTTnnnnnnnnnN..........
.........NnnnnnnnTTTTTTTnnnnnnnnnN..........
.........NNnnnnnnTTTTTTTnnnnnnnnNN..........
.........NNnnnnnnTTTTTTTnnnnnnnnNN..........
.........NNNnnnnnTTTTTTTnnnnnnnNNN..........
.........NNNNnnnnnTTTTTnnnnnnnNNNN..........
.........NNNNNNNNNNNNNNNNNNNNNNNNN..........
..........DDDDDDDD.......DDDDDDDD...........
..........DDDDDDDD.......DDDDDDDD...........
""")
monk = [list(r) for r in monk]
# посох справа с кристаллом, рука к посоху
for y in range(6, 34): monk[y][36] = 'T'; monk[y][37] = 'n'
for y, half in ((2, 1), (3, 2), (4, 2), (5, 1)):
    for x in range(36 - half, 38 + half): monk[y][x] = 'A' if y in (3, 4) else 'a'
for y in range(17, 21):
    for x in range(31, 36): monk[y][x] = 'S' if y in (17, 20) else 's'
monk = [''.join(r) for r in monk]
monk = stretch(monk, 48, [(13, 22), (24, 33)])

# кавалерист — композитором: конь, всадник, копьё, щит
c = Canvas(64, 56)
c.ellipse(30, 36, 18, 9, 'n')                 # корпус коня
c.ellipse(46, 30, 8, 7, 'n')                  # грудь
c.ellipse(18, 38, 9, 7, 'N', rot=0.2)         # круп в тени
c.ellipse(52, 21, 6, 8, 'n', rot=-0.5)        # шея
c.ellipse(58, 15, 5, 4, 'n')                  # голова
c.ellipse(61, 16, 2.5, 2, 'N')                # морда
c.put(58, 13, 'k')                             # глаз
c.poly([(54, 9), (56, 6), (58, 11)], 'N')      # ухо
c.feathers([(48, 14), (54, 10)], 'D', 2.4, (-0.2, -0.8))   # грива
for x0 in (14, 22, 36, 44):                    # ноги
    c.poly([(x0, 42), (x0 - 1, 54), (x0 + 4, 54), (x0 + 5, 42)], 'n' if x0 > 30 else 'N')
    c.poly([(x0 - 2, 52), (x0 - 2, 55), (x0 + 5, 55), (x0 + 5, 52)], 'D')
c.line(12, 33, 4, 46, 'D', th=3)               # хвост
c.ellipse(30, 30, 9, 4, 'r'); c.ellipse(30, 31, 8, 3, 'R')   # седло/попона
# всадник
c.ellipse(31, 18, 6, 8, 'e')                  # корпус
c.ellipse(31, 19, 4, 5, 'E')                  # тень корпуса
c.ellipse(31, 9, 4.5, 4.5, 'e')               # шлем
c.poly([(28, 9), (34, 9), (34, 11), (28, 11)], 'z')   # щель забрала
c.feathers([(29, 3), (33, 2)], 'r', 2.0, (0, -0.6))    # плюмаж
c.poly([(24, 20), (18, 40), (23, 41), (28, 24)], 'e')   # нога всадника
c.ellipse(20, 41, 3, 2, 'E')                   # стремя/сапог
c.line(26, 20, 63, 8, 'T', th=2)               # копьё
c.poly([(60, 7), (64, 8), (60, 11)], 'l')      # наконечник
c.line(34, 16, 40, 18, 'e', th=2)              # рука
c.outline(between=set())
cav = c.rows()
# композитор рисует внешний 'k' — в стиле Б контур не нужен: снимаем
cav = [r.replace('k', '.') for r in cav]
# но глаз коня оставляем тёмным
cav = [list(r) for r in cav]; cav[13][58] = 'k'; cav = [''.join(r) for r in cav]

out = "/* ============================================================================\n"
out += "   view/sprites_castle_hd.js — существа Замка в крупной сетке (unit 2 = вдвое крупнее\n"
out += "   номинала), стиль Б: без контурной линии, тона кладёт рисунок, лёгкий свет по силуэту\n"
out += "   даёт конвейер «краска». Собирается скриптом dev/proto/castle_hd.py.\n"
out += "   ========================================================================== */\n(function () {\n  'use strict';\n  H3.Sprites.defineMany({\n"
out += block('pikeman', pikeman, 'копейщик: шлем-котелок, кольчужные рукава, туника с гербом, копьё')
out += block('halberdier', None, 'алебардщик: красная туника, лезвие алебарды', base='pikeman', tint={'b': 'r', 'B': 'R'}, extra=[(32,3,'l'),(31,4,'l'),(30,5,'e'),(31,5,'l'),(32,6,'l'),(31,6,'l')])
out += block('archer', archer, 'лучник: зелёный капюшон, туника, лук с тетивой, колчан')
out += block('marksman', None, 'стрелок: капюшон в тёмный дуб, серебряный наконечник, вторая стрела', base='archer', tint={'G': 'R', 'h': 'H', 'H': 'u', 'D': 'z'}, extra=[(33,5,'l'),(33,4,'l'),(34,4,'l')])
out += block('griffin', griffin, 'грифон: крылья веером, львиное тело, орлиная голова (композитор)')
out += block('royal_griffin', None, 'королевский грифон: золотой окрас крыльев, алый гребень', base='griffin', tint={'n': 'y', 'N': 'Y', 'T': 'o'}, extra=[(50,12,'r'),(51,11,'r'),(52,12,'r')])
out += block('swordsman', swordsman, 'мечник: полные латы, забрало, табард с крестом, меч, каплевидный щит')
out += block('crusader', None, 'крестоносец: золочёные латы, белый табард с красным крестом', base='swordsman', tint={'e': 'y', 'E': 'Y', 'l': 'w', 'r': 'w', 'R': 'l'}, extra=[(22,15,'r'),(22,16,'r'),(22,17,'r'),(22,18,'r'),(22,19,'r'),(20,17,'r'),(21,17,'r'),(23,17,'r'),(24,17,'r')])
out += block('monk', monk, 'монах: ряса с капюшоном, верёвочный пояс, посох с кристаллом')
out += block('zealot', None, 'фанатик: белая ряса, золотой пояс, посох ярче', base='monk', tint={'n': 'i', 'N': 'I', 'D': 'T'}, extra=[(35,1,'A'),(36,1,'A')])
out += block('cavalier', cav, 'кавалерист: конь в галопе, всадник в латах, копьё, плюмаж (композитор)')
out += block('champion', None, 'чемпион: белый конь, серебряные латы, синяя попона', base='cavalier', tint={'n': 'l', 'N': 'e', 'D': 'E', 'r': 'b', 'R': 'B', 'e': 'w', 'E': 'l'})
out += block('angel', angel, 'ангел: нимб, крылья с рядами перьев, золотые латы, светящийся меч')
out += block('archangel', None, 'архангел: белое золото лат, голубое свечение меча, лазурные перья', base='angel', tint={'y': 'w', 'Y': 'y', 'L': 'c', 'l': 'c', 'e': 'l', 'E': 'e'})
out += "  });\n})();\n"
p = os.path.join(os.path.dirname(__file__), '..', '..', 'js', 'view', 'sprites_castle_hd.js')
io.open(p, 'w', encoding='utf-8').write(out)
print('записан', os.path.relpath(p))
