# -*- coding: utf-8 -*-
"""Сборка js/view/sprites_cove_hd.js: 14 существ Бухты в крупной сетке (unit 2), стиль Б.
Нимфа, матрос, пират, морская ведьма, никс — строками; штормовая птица и морской змей — композитором."""
import io, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from compose import Canvas
from castle_hd import rows_from, pad, block, stretch   # общие помощники (castle_hd при импорте пересобирает свой файл — это безвредно)

# ---------- нимфа 40×46: морская дева, мятная кожа, бирюзовые волосы, вместо ног — гребень волны с пеной ----------
nymph = rows_from("""
...............CCCCCCCCC................
.............CCCCCCCCCCCCC..............
............CCCCCCCCCCCCCCC.............
............CCCvvvvvvvvvCCC.............
............CCvvvvvvvvvvvCC.............
............CCvvwkvvvwkvvCC.............
............CCvvwkvvvwkvvCC.............
............CCvvvvvvvvvvvCC.............
............CCCvvvvvvvvvCCC.............
.............CCCvvvvvvvCCCC.............
.............CCCCvvvvvCCCCC.............
..............CCCCvvvCCCCCC.............
...............CCCvvvCCCCCC.............
..........vvvvvvvvvvvvvvvCCCC...........
.........vvvvvvvvvvvvvvvvvCCC...........
........vvvvvvvCCCCCCCvvvvvvvCC.........
.......vvvv.vvvCCCCCCCvvv.vvvvCC........
.......vvvv.vvvCCCCCCCvvv.vvvvCC........
.......vvvv.vvvvCCCCCvvvv.vvvv..........
.......vvvv.vvvvvvvvvvvvv.vvvv..........
.......vvvv.vvvvvvvvvvvvv.vvvv..........
.......vvvv..vvvvvvvvvvv..vvvv..........
........vv...vvvvvvvvvvv...vv...........
.............vvvvvvvvvvv................
............CCCvvvvvvvCCC...............
...........CCCCCvvvvvCCCCC..............
..........CCCCCCCCCCCCCCCCC.............
.........CCCCCCCCCCCCCCCCCCC............
........CCCCCCCCCCCCCCCCCCCCC...........
.......CCCCCCCCCCCCCCCCCCCCCCC..........
......CCCCCCCCCCCCCCCCCCCCCCCCC.........
....LLCCCCCCCCCCCCCCCCCCCCCCCCLL........
...LLLLCCCCCCCCCCCCCCCCCCCCCCLLLL.......
..LLLLLLCCCCCCCCCCCCCCCCCCCCLLLLLL......
..LLLLLLLLCCCCCCCCCCCCCCCCLLLLLLLL......
...LLLLLLLLLLLLLLLLLLLLLLLLLLLLLL.......
....LLLLLLLLLLLLLLLLLLLLLLLLLLLL........
......LLLLLLLLLLLLLLLLLLLLLLLL..........
""")
nymph = [list(r) for r in nymph]
for y, xs in ((27, (10, 11, 12)), (28, (9, 10, 11, 12)), (29, (9, 10, 11))):   # брызги пены на гребне
    for x in xs: nymph[y][x] = 'L'
for y, xs in ((28, (24, 25, 26)), (29, (24, 25, 26, 27)), (30, (25, 26, 27))):
    for x in xs: nymph[y][x] = 'L'
nymph = [''.join(r) for r in nymph]
nymph = stretch(nymph, 46, [(13, 23), (26, 34)])

# ---------- матрос 40×46: красная бандана, тельняшка в широкую полосу, синие штаны, сабля ----------
crew_mate = rows_from("""
..............rrrrrrrrr.................
............rrrrrrrrrrrrr...............
...........rrrrrrrrrrrrrrr..............
...........rrrrrrrrrrrrrrrrr............
...........rrsssssssssssrrrr............
...........rssssssssssssrr..............
...........rsssswkssswkssr..............
...........rsssswkssswkssr..............
............ssssssssssssss..............
............ssssssssssssss..............
.............sssssssssssS...............
..............ssssssssss................
................ssssss..................
...........llllllssssllllll.............
.........llllllllllllllllllll...........
........bbbbbbbbbbbbbbbbbbbbbb..........
.......bbbbbbbbbbbbbbbbbbbbbbbb.........
......llll.llllllllllllllllll.llll......
......llll.llllllllllllllllll.llll......
......bbbb.bbbbbbbbbbbbbbbbbb.bbbb......
......bbbb.bbbbbbbbbbbbbbbbbb.bbbb......
......ssss.llllllllllllllllll.ssss......
......ssss.llllllllllllllllll.ssss......
......ssss.bbbbbbbbbbbbbbbbbb.ssss......
......ssss.bbbbbbbbbbbbbbbbbb.ssss......
......SSSS.llllllllllllllllll.SSSSS.....
......SSSS.llllllllllllllllll.SSSSS.....
......SSSS.DDDDDDDDDDDDDDDDDD.SSSSS.....
...........DDDDDDDyyDDDDDDDD............
...........BBBBBBBBBBBBBBBBBB...........
...........BBBBBBBBBBBBBBBBBB...........
...........BBBBBBBB..BBBBBBBB...........
...........BBBBBBBB..BBBBBBBB...........
...........BBBBBBBB..BBBBBBBB...........
...........BBBBBBBB..BBBBBBBB...........
...........BBBBBBBB..BBBBBBBB...........
..........nnnnnnnnn..nnnnnnnnn..........
..........nnnnnnnnn..nnnnnnnnn..........
..........NNNNNNNNN..NNNNNNNNN..........
""")
crew_mate = [list(r) for r in crew_mate]
for y in range(25, 28): crew_mate[y][35] = 'N'; crew_mate[y][36] = 'N'                  # рукоять сабли в кулаке
for x in range(34, 39): crew_mate[24][x] = 'y'                                           # гарда
for y in range(6, 24): crew_mate[y][35] = 'l'; crew_mate[y][36] = 'w'; crew_mate[y][37] = 'l'   # клинок с бликом
for y, xs in ((5, (36, 37, 38)), (4, (37, 38, 39)), (3, (38, 39))):                       # изгиб острия
    for x in xs: crew_mate[y][x] = 'w' if x == xs[1] else 'l'
crew_mate = [''.join(r) for r in crew_mate]
crew_mate = stretch(crew_mate, 46, [(14, 27), (29, 36)])

# ---------- пират 48×52: треуголка, повязка на глазу, борода, красный камзол, пистолет вперёд, сабля к земле ----------
pirate = rows_from("""
..............DDDDDDDDDD........................
............DDDDDDDDDDDDDD......................
...........DDDDDDDDDDDDDDDD.....................
..........DDDDDDDDDDDDDDDDDD....................
.........DDDDDDDDDDDDDDDDDDDD...................
......EEEEEEEEEEEEEEEEEEEEEEEEE.................
.....EEEEEEEEEEEEEEEEEEEEEEEEEEE................
..............ssssssssssss......................
.............sszzzssssssss......................
.............sszzzsssswkss......................
.............sszzzsssswkss......................
.............ssssssssssssss.....................
.............ssssssssssssss.....................
..............DDDDDDDDDDDD......................
...............DDDDDDDDDD.......................
.................ssssss.........................
............rrrrrrssssrrrrrrr...................
..........rrrrrrrrrrrrrrrrrrrrrr................
.........rrrrrrrrrrrrrrrrrrrrrrrr...............
........rrrrrrrrrrrrrrrrrrrrrrrrrrrrr...........
.......rrrrr.rrrrrrrrrrrrrrrrrrrrrrrrssss.......
.......rrrrr.rrrrrrrrrrrrrrrrrrrrrrrrsssseeeeeee
.......rrrrr.rrrrrrrrrrrrrrrrrrrrrrrrssssEEEEEEE
.......rrrrr.rrrrrrrrrrrrrrrrrrr.....ssssnnn....
.......rrrrr.rrrrrrrrrrrrrrrrrrr.........nn.....
.......rrrrr.rrrrrrrrrrrrrrrrrrr................
.......rrrrr.rrrrrrrrrrrrrrrrrrr................
.......ssss..yyyyyyyyyyyyyyyyyyy................
.......ssss..YYYYYYYYYYYYYYYYYYY................
.............rrrrrrrrrrrrrrrrrrr................
.............rrrrrrrrrrrrrrrrrrr................
.............tttttttt..ttttttttt................
.............tttttttt..ttttttttt................
.............tttttttt..ttttttttt................
.............tttttttt..ttttttttt................
.............DDDDDDDD..DDDDDDDDD................
.............DDDDDDDD..DDDDDDDDD................
.............DDDDDDDD..DDDDDDDDD................
.............DDDDDDDD..DDDDDDDDD................
............DDDDDDDDD..DDDDDDDDDD...............
............DDDDDDDDD..DDDDDDDDDD...............
""")
pirate = [list(r) for r in pirate]
for x in range(5, 12): pirate[29][x] = 'y'                                              # гарда сабли
for y in range(30, 41): pirate[y][7] = 'l'; pirate[y][8] = 'w'; pirate[y][9] = 'l'      # клинок остриём вниз
for x in range(12, 16): pirate[8][x] = 'z'; pirate[8][x] = 'z'                           # ремешок повязки
pirate = [''.join(r) for r in pirate]
pirate = stretch(pirate, 52, [(17, 30), (31, 38)])

# ---------- морская ведьма 56×58: тёмно-бирюзовые волосы, фиолетовая мантия с волной, посох с жемчужиной ----------
sea_witch = rows_from("""
...................QQQQQQQQQQ...........................
.................QQQQQQQQQQQQQQ.........................
................QQQQQQQQQQQQQQQQ........................
................QQQQssssssssQQQQ........................
...............QQQsssssssssssQQQ........................
...............QQQsssssssssssQQQ........................
...............QQQsswkssswkssQQQ........................
...............QQQsswkssswkssQQQ........................
...............QQQsssssssssssQQQ........................
...............QQQsssssssssssQQQ........................
...............QQQQsssssssssQQQQ........................
...............QQQQQsssssssQQQQQ........................
...............QQQQQQsssssQQQQQQ........................
...............QQQQQ.sssss.QQQQQ........................
..............QQQQQ.ppppppp.QQQQQ.......................
.............QQQQQpppppppppppQQQQQ......................
............QQQQpppppppppppppppQQQQ.....................
...........QQQQppppppppppppppppppQQQQ...................
...........QQQpppppppppppppppppppppQQQ..................
...........QQppppppppppppppppppppppppQQ.................
..........ppppppppppppppppppppppppppppp.................
..........pppp.pppppppppppppppppppppppppp...............
..........pppp.ppppppppppppppppppppppppppppssss.........
..........pppp.ppppppppppppppppppppppppppppssss.........
..........pppp.ppppppppppppppppppppppppppppssss.........
..........pppp.pppppppppppppppppppppppp....ssss.........
..........pppp.pppppppppppppppppppppppp.................
..........pppp.pppppppppppppppppppppppp.................
..........ssss.yyyyyyyyyyyyyyyyyyyyyyyy.................
..........ssss.YYYYYYYYYYYYYYYYYYYYYYYY.................
...............pppppppppppppppppppppppp.................
..............pppppppppppppppppppppppppp................
..............pppppppppppppppppppppppppp................
.............pppppppppppppppppppppppppppp...............
.............pppppppppppppppppppppppppppp...............
............pppppppppppppppppppppppppppppp..............
............pppppppppppppppppppppppppppppp..............
...........pppppppppppppppppppppppppppppppp.............
...........pppppppppppppppppppppppppppppppp.............
..........pppppppppppppppppppppppppppppppppp............
..........pppppppppppppppppppppppppppppppppp............
.........PPpppppppppppppppppppppppppppppppPP............
.........PPPPpppppppppppppppppppppppppppPPPP............
.........PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP............
.........PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP............
.........PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP............
""")
sea_witch = [list(r) for r in sea_witch]
for y in range(9, 46): sea_witch[y][49] = 'N'; sea_witch[y][50] = 'N'                     # посох
for y in range(1, 10):                                                                    # сияние жемчужины
    for x in range(44, 56):
        if (x - 49.5) ** 2 / 25 + (y - 5) ** 2 / 16 <= 1: sea_witch[y][x] = 'c'
for y in (4, 5, 6):
    for x in (48, 49, 50, 51): sea_witch[y][x] = 'w'                                      # сама жемчужина
for x in range(14, 40): sea_witch[37][x] = 'c'                                            # волна по подолу
for x in range(14, 40, 4): sea_witch[36][x] = 'c'; sea_witch[36][x + 1] = 'c'
for x in range(16, 40, 4): sea_witch[38][x] = 'c'; sea_witch[38][x + 1] = 'c'
sea_witch = [''.join(r) for r in sea_witch]
sea_witch = stretch(sea_witch, 58, [(20, 28), (30, 44)])

# ---------- никс 56×60: тритон-воин, мятная кожа, гребень-плавник, чешуйчатые латы, трезубец и щит-раковина ----------
nix = rows_from("""
.......................CCC..............................
.....................CCCCCCC............................
....................CCCCCCCCC...........................
...................CCCCCCCCCCC..........................
..................CCvvvvvvvvvCC.........................
..................CvvvvvvvvvvvC.........................
..................vvvvvvvvvvvvv.........................
..................vvwkvvvvvwkvv.........................
..................vvwkvvvvvwkvv.........................
..................vCCvvvvvvvCCv.........................
..................vCCvvvvvvvCCv.........................
...................vvvvvvvvvvv..........................
....................vvvvvvvvv...........................
......................vvvvv.............................
..............qqqqqqqqqvvvvqqqqqqqqq....................
............qqqqqqqqqqqqqqqqqqqqqqqqq...................
...........qqqqqqqqqqqqqqqqqqqqqqqqqqq..................
..........qqqqqqqqqqqqqqqqqqqqqqqqqqqqq.................
..........qqqqq.qQQqqQQqqQQqqQQq.qqqqq..................
..........qqqqq.QqqQQqqQQqqQQqqQ.qqqqq..................
..........qqqqq.qQQqqQQqqQQqqQQq.qqqqq..................
..........qqqqq.QqqQQqqQQqqQQqqQ.qqqqq..................
..........qqqqq.qQQqqQQqqQQqqQQq.qqqqq..................
..........qqqqq.QqqQQqqQQqqQQqqQ.qqqqq..................
..........vvvvv.qQQqqQQqqQQqqQQq.vvvvv..................
..........vvvvv.QqqQQqqQQqqQQqqQ.vvvvv..................
..........vvvvv.qQQqqQQqqQQqqQQq.vvvvv..................
..........vvvvv.QqqQQqqQQqqQQqqQ.vvvvv..................
..........vvvvv.qqqqqqqqqqqqqqqq.vvvvv..................
................QQQQQQQQQQQQQQQQ........................
................qqqqqqqqqqqqqqqq........................
................qqqqqqqqqqqqqqqq........................
................qqqqqqq..qqqqqqq........................
................qqqqqqq..qqqqqqq........................
................qqqqqqq..qqqqqqq........................
................qqqqqqq..qqqqqqq........................
................qqqqqqq..qqqqqqq........................
................qqqqqqq..qqqqqqq........................
................qqqqqqq..qqqqqqq........................
................qqqqqqq..qqqqqqq........................
...............vvvvvvvv..vvvvvvvv.......................
..............vvvvvvvvv..vvvvvvvvv......................
.............CCCCCCCCCC..CCCCCCCCCC.....................
""")
nix = [list(r) for r in nix]
for y in range(24, 28):
    for x in range(38, 41): nix[y][x] = 'v'                                               # кисть на древке
for y in range(6, 43): nix[y][41] = 'e'; nix[y][42] = 'e'                                 # древко трезубца
for x in range(37, 47): nix[5][x] = 'l'                                                   # перекладина
for y in range(1, 5): nix[y][37] = 'l'; nix[y][38] = 'l'; nix[y][45] = 'l'; nix[y][46] = 'l'   # боковые зубья
for y in range(0, 5): nix[y][41] = 'l'; nix[y][42] = 'l'                                  # средний зуб
for y in range(17, 33):                                                                   # щит-раковина слева
    for x in range(2, 15):
        d = (x - 8) ** 2 / 36.0 + (y - 25) ** 2 / 64.0
        if d <= 1: nix[y][x] = 'I' if d > 0.62 else 'i'
for y in (24, 25, 26):
    for x in (7, 8, 9): nix[y][x] = 'C'                                                   # завиток раковины
nix = [''.join(r) for r in nix]
nix = stretch(nix, 60, [(15, 29), (31, 40)])

# ---------- штормовая птица (композитор) 52×52: чайка-буревестник, крылья размахом во всю ширину, тёмные концы, оранжевый клюв, вилка хвоста ----------
c = Canvas(52, 52)
c.poly([(25, 22), (10, 8), (0, 10), (0, 20), (8, 25), (25, 37)], 'e')      # левое крыло — широкая полоса к краю
c.poly([(27, 22), (42, 8), (52, 10), (52, 20), (44, 25), (27, 37)], 'e')   # правое крыло
c.poly([(10, 8), (0, 10), (0, 20), (8, 25), (13, 19), (14, 11)], 'E')      # тёмные концы крыльев
c.poly([(42, 8), (52, 10), (52, 20), (44, 25), (39, 19), (38, 11)], 'E')
c.feathers([(9, 26), (24, 38)], 'E', 2.2, (0.2, 0.6))                       # зубчатый нижний край
c.feathers([(43, 26), (28, 38)], 'E', 2.2, (-0.2, 0.6))
c.ellipse(26, 34, 7, 9, 'l')                                        # тело
c.ellipse(28, 29, 5, 5, 'l'); c.ellipse(31, 24, 5.5, 5, 'l')        # шея и голова
c.poly([(36, 22), (45, 25), (36, 27)], 'o')                         # клюв
c.poly([(22, 42), (30, 42), (34, 50), (18, 50)], 'e')               # хвост
c.poly([(24, 47), (28, 47), (26, 51)], '.')                         # вилка хвоста
c.line(30, 42, 33, 46, 'o', th=2); c.line(33, 46, 36, 47, 'o', th=1); c.line(33, 46, 34, 49, 'o', th=1)   # лапа
c.outline(between=set())
stormbird = [r.replace('k', '.') for r in c.rows()]
stormbird = [list(r) for r in stormbird]
for x, y in ((32, 22), (33, 22), (32, 23), (33, 23)): stormbird[y][x] = 'k'   # глаз
stormbird = [''.join(r) for r in stormbird]

# ---------- морской змей (композитор) 64×60: длинное тело кольцами, тёмная задняя петля, голова с гребнем и пастью ----------
c = Canvas(64, 60)
back = [(44, 52), (57, 44), (50, 34), (30, 34)]                     # задняя петля (в тени)
for (x0, y0), (x1, y1) in zip(back, back[1:]): c.line(x0, y0, x1, y1, 'Q', th=8)
front = [(2, 56), (14, 52), (30, 55), (44, 52)]                     # нижнее кольцо
for (x0, y0), (x1, y1) in zip(front, front[1:]): c.line(x0, y0, x1, y1, 'q', th=9)
for (x0, y0), (x1, y1) in zip(front, front[1:]): c.line(x0, y0 - 3, x1, y1 - 3, 'v', th=2)   # блик по спине
neck = [(30, 34), (24, 26), (30, 16), (44, 10)]                     # шея
for (x0, y0), (x1, y1) in zip(neck, neck[1:]): c.line(x0, y0, x1, y1, 'q', th=8)
for (x0, y0), (x1, y1) in zip(neck, neck[1:]): c.line(x0 - 2, y0 - 2, x1 - 2, y1 - 2, 'v', th=2)
c.ellipse(50, 10, 9, 6, 'q')                                        # голова
c.poly([(50, 13), (63, 15), (52, 18)], 'Q')                         # нижняя челюсть, пасть открыта
c.poly([(53, 12), (62, 13), (53, 14)], 'R')                         # зев
for x in (54, 57, 60): c.put(x, 12, 'w'); c.put(x, 14, 'w')         # зубы
c.put(52, 7, 'y'); c.put(53, 7, 'y'); c.put(52, 8, 'y'); c.put(53, 8, 'k')   # глаз
c.feathers([(42, 5), (52, 3)], 'o', 2.2, (0, -0.7))                 # гребень на голове
c.feathers([(27, 12), (36, 8)], 'o', 2.0, (-0.6, -0.6))             # плавник по шее
c.outline(between=set())
sea_serpent = [r.replace('k', '.') for r in c.rows()]
sea_serpent = [list(r) for r in sea_serpent]
sea_serpent[8][53] = 'k'
sea_serpent = [''.join(r) for r in sea_serpent]
# шипы хаспида: по верхнему краю нижнего кольца, над бликом
haspid_spikes = []
for x0 in range(8, 44, 6):
    top = next(y for y in range(60) if sea_serpent[y][x0] in 'qv' and y > 40)
    haspid_spikes += [(x0 - 1, top - 1, 'h'), (x0, top - 1, 'h'), (x0 + 1, top - 1, 'h'), (x0, top - 2, 'h'), (x0, top - 3, 'h')]

out = "/* ============================================================================\n"
out += "   view/sprites_cove_hd.js — существа Бухты в крупной сетке (unit 2), стиль Б:\n"
out += "   без контурной линии, тона кладёт рисунок. Собирается скриптом dev/proto/cove_hd.py.\n"
out += "   ========================================================================== */\n(function () {\n  'use strict';\n  H3.Sprites.defineMany({\n"
out += block('nymph', nymph, 'нимфа: морская дева, мятная кожа, бирюзовые волосы, вместо ног гребень волны с пеной')
out += block('oceanid', None, 'океанида: кожа в голубизну, волосы в глубокую бирюзу, жемчуг в волосах', base='nymph', tint={'v': 'c', 'C': 'Q'},
             extra=[(x, y, 'w') for x, y in ((14, 1), (15, 1), (14, 2), (18, 0), (19, 0), (19, 1), (24, 2), (25, 2), (25, 3))])
out += block('crew_mate', crew_mate, 'матрос: красная бандана, тельняшка, синие штаны, сабля')
out += block('seaman', None, 'морской волк: бандана синяя, тельняшка в серую полосу, борода, серьга', base='crew_mate', tint={'r': 'B', 'b': 'C'},
             extra=[(x, y, 'e') for y in (9, 10, 11) for x in range(13, 25)] + [(x, 12, 'e') for x in range(15, 23)] + [(11, 7, 'y'), (11, 8, 'y'), (10, 8, 'y')])
out += block('pirate', pirate, 'пират: треуголка, повязка на глазу, борода, красный камзол, пистолет вперёд, сабля к земле')
out += block('corsair', None, 'корсар: камзол в малиновый, штаны серые, красное перо на треуголке', base='pirate', tint={'r': 'M', 't': 'e'},
             extra=[(x, y, 'r') for y, (a, b) in ((0, (25, 32)), (1, (24, 31)), (2, (23, 28)), (3, (23, 25))) for x in range(a, b)])
out += block('stormbird', stormbird, 'штормовая птица: чайка-буревестник, крылья вверх, тёмные концы крыльев, вилка хвоста (композитор)')
out += block('ayssid', None, 'айссид: оперение штормовое сине-серое, клюв и лапы огненные, искры на крыльях', base='stormbird', tint={'l': 'C', 'e': 'B', 'E': 'z', 'o': 'f'},
             extra=[(x, y, 'y') for x, y in ((5, 13), (6, 14), (5, 15), (6, 16), (7, 17), (6, 18), (47, 13), (46, 14), (47, 15), (46, 16), (45, 17), (46, 18))])
out += block('sea_witch', sea_witch, 'морская ведьма: тёмно-бирюзовые волосы, фиолетовая мантия с волной по подолу, посох с жемчужиной')
out += block('sorceress', None, 'колдунья: мантия в синь, волосы чёрные, жемчужина в сиреневом свете, золотая диадема', base='sea_witch', tint={'p': 'b', 'P': 'B', 'c': 'A', 'Q': 'z'},
             extra=[(x, 2, 'y') for x in range(19, 29)] + [(x, 1, 'y') for x in (20, 23, 24, 27)])
out += block('nix', nix, 'никс: тритон-воин, мятная кожа, гребень-плавник, чешуйчатые латы, трезубец и щит-раковина')
out += block('nix_warrior', None, 'никс-воин: латы чернеют, гребень и плавники оранжевые, трезубец золотой', base='nix', tint={'q': 'u', 'Q': 'z', 'e': 'Y', 'l': 'y', 'C': 'o'})
out += block('sea_serpent', sea_serpent, 'морской змей: тело кольцами, тёмная задняя петля, голова с гребнем и раскрытой пастью (композитор)')
out += block('haspid', None, 'хаспид: чешуя в малахит, петля чёрная, гребень розовый, ядовитые шипы по спине', base='sea_serpent', tint={'q': 'G', 'Q': 'z', 'v': 'H', 'o': 'm'},
             extra=haspid_spikes)
out += "  });\n})();\n"
p = os.path.join(os.path.dirname(__file__), '..', '..', 'js', 'view', 'sprites_cove_hd.js')
io.open(p, 'w', encoding='utf-8').write(out)
print('записан', os.path.relpath(p))
