# -*- coding: utf-8 -*-
"""Сборка js/view/sprites_dungeon_hd.js: 14 существ Темницы в крупной сетке (unit 2), стиль Б.
Троглодит, минотавр — строками; гарпия, бехолдер, медуза, мантикора, дракон — композитором."""
import io, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from compose import Canvas
from castle_hd import rows_from, pad, block, stretch   # общие помощники (castle_hd при импорте пересобирает свой файл — это безвредно)

# ---------- троглодит 40×46: сгорбленный безглазый ящер, светлое брюхо, гребень на спине, дубина ----------
troglodyte = rows_from("""
..............................TTTTT.....
.............................TTTTTTT....
.............................TTTnnTT....
.............................TTTTTTT....
..............................TTTTT.....
...............................nNn......
......ppppp....................nNn......
....pppppppppp.................nNn......
..pppppppppppppp...............nNn......
.ppppppppppppppppp.............nNn......
kkppppppppppppppppp............nNn......
kkppppppppppppppppp............nNn......
PPPPPPppppppppppppp............nNn......
PiiPiiPPPPpppppppppp...........nNn......
.PiiPiiPPPPPppppppppp..........nNn......
....PPPPPPPPPPppppppPP.........nNn......
..........PPPPpppppppPPP.......nNn......
..........pppppppppppppPPP.....nNn......
.........ppppppppppppppppPPP...nNn......
.........pppppppppppppppppppp..nNn......
.........ppppAAAAAppppppppppppppNn......
.........pppAAAAAAAppppppppppPPPPP......
.........pppAAAAAAAAppppppppPPPPPP......
.........pppAAAAAAAAppppppppPP..........
.........pppAAAAAAAAppppppppP...........
........ppppAAAAAAAApppppppp............
........ppppAAAAAAAAppppppp.............
.......pppppAAAAAAAppppppp..............
......ppppppAAAAAAppppppp...............
.....PPPpppppAAAAppppppp................
....PPPPpppppppppppppppp................
...PPPP.pppppppppppppppp................
..PPPP..PPPPPPPPPPPPPPPP................
.PPPP...pppppp..pppppp..................
.PPP....pppppp..pppppp..................
.PP.....pppppp..pppppp..................
........PPpppp..PPpppp..................
........PPpppp..PPpppp..................
.......ppppppp..ppppppp.................
.......PPPPPPP..PPPPPPP.................
""")
troglodyte = [list(r) for r in troglodyte]
for x0 in (16, 21, 26):                                                                   # шипы гребня над спиной
    for y, half in ((17, 0), (16, 0), (15, 1), (14, 1)):
        for x in range(x0 - half, x0 + half + 1):
            if 0 <= y < len(troglodyte): troglodyte[y][x] = 'P'
troglodyte = [''.join(r) for r in troglodyte]
troglodyte = stretch(troglodyte, 46, [(17, 30), (33, 38)])

# ---------- минотавр 52×60: бык-человек, тёмная бычья голова с рогами, загорелый торс, красная повязка, секира ----------
minotaur = rows_from("""
......ii................ii..........................
.....iii................iii.........................
.....iii................iii.........................
......iii..............iii..........................
......iiii............iiii..........................
.......iiiNNNNNNNNNNNNiii...........................
........iNNNNNNNNNNNNNNi............................
.........NNNNNNNNNNNNNNN............................
.........NNNwwNNNNNNwwNN............................
.........NNNkwNNNNNNwkNN............................
.........NNNNNNNNNNNNNNN............................
..........NNNnnnnnnnnnN.............................
..........NNnnnnnnnnnnnN............................
..........NnnnnnnnnnnnnnN...........................
..........NnnnkknnnnkknnN...........................
...........NnnnnnnnnnnnN............................
............NnnnnnnnnnN.............................
.............NNNNNNNNN..............................
........SSSSSSSSSSSSSSSSSSS.........................
......SSSSSSSSSSSSSSSSSSSSSSS.......................
.....SSSSSSSSSSSSSSSSSSSSSSSSS......................
....SSSSSSSSnnnnnnnnnnSSSSSSSSS.....................
....SSSSSSSnnnnnnnnnnnnSSSSSSSSS....................
....SSSSS.SSnnnnnnnnnnSSSSSSSSSSS...................
....SSSSS.SSSSnnnnnnSSSSSSSSSSSSSSSSSS..............
....SSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSS..............
....SSSSS.SSSSnnnnnnSSSSSSSSSSSSSSSSSS..............
....SSSSS.SSSnnnnnnnnSSSSSSSSSSSSSSSSS..............
....SSSSS.SSSSnnnnnnSSSSSSSSSSSSS...................
....SSSSS.SSSSSSSSSSSSSSSSSSSSSS....................
....nnnnn.SSSSSSSSSSSSSSSSSSSSS.....................
....nnnnn.yyyyyyyyyyyyyyyyyyyyy.....................
.....nnn..rrrrrrrrrrrrrrrrrrrrr.....................
..........rrrrrrrrrrrrrrrrrrrrr.....................
..........RRRRRRRRRRRRRRRRRRRRR.....................
..........RRRRRRRRRRRRRRRRRRRRR.....................
..........SSSSSSSSS...SSSSSSSSS.....................
..........SSSSSSSSS...SSSSSSSSS.....................
..........SSSSSSSSS...SSSSSSSSS.....................
..........SSSSSSSSS...SSSSSSSSS.....................
..........NNNNNNNNN...NNNNNNNNN.....................
..........NNNNNNNNN...NNNNNNNNN.....................
..........NNNNNNNNN...NNNNNNNNN.....................
..........NNNNNNNNN...NNNNNNNNN.....................
.........DDDDDDDDDD...DDDDDDDDDD....................
.........DDDDDDDDDD...DDDDDDDDDD....................
""")
minotaur = [list(r) for r in minotaur]
for y in range(2, 36): minotaur[y][37] = 'n'; minotaur[y][38] = 'N'; minotaur[y][39] = 'n'      # рукоять секиры
for y, half in ((2, 2), (3, 3), (4, 4), (5, 5), (6, 5), (7, 5), (8, 5), (9, 4), (10, 3), (11, 2)):   # двустороннее лезвие
    for x in range(36 - half - 1, 36):   minotaur[y][x] = 'l' if x == 36 - half - 1 else 'e'
    for x in range(40, 40 + half + 2):   minotaur[y][x] = 'l' if x == 40 + half + 1 else 'e'
for y in range(24, 28):                                                                          # кисть на рукояти
    for x in range(35, 41): minotaur[y][x] = 'n' if y in (24, 27) else 'S'
minotaur = [''.join(r) for r in minotaur]
minotaur = stretch(minotaur, 60, [(18, 30), (36, 44)])

# ---------- гарпия (композитор) 44×48: крылатая женщина, тёмные волосы-грива, золотые крылья вверх, птичьи лапы с когтями ----------
c = Canvas(44, 48)
c.poly([(19, 20), (2, 2), (12, 0), (22, 14)], 'Y')             # левое крыло
c.poly([(25, 20), (42, 2), (32, 0), (22, 14)], 'Y')            # правое крыло
c.feathers([(3, 4), (17, 21)], 'y', 2.2, (0, 0.7))             # светлые перья по нижней кромке
c.feathers([(41, 4), (27, 21)], 'y', 2.2, (0, 0.7))
c.line(19, 20, 4, 3, 'y', th=1); c.line(25, 20, 40, 3, 'y', th=1)   # маховые кости
c.ellipse(22, 9, 5.5, 5.5, 'R')                                 # волосы
c.poly([(16, 9), (13, 22), (18, 19)], 'R'); c.poly([(28, 9), (31, 22), (26, 19)], 'R')   # пряди вниз
c.ellipse(22, 10, 3.8, 4.2, 's')                                # лицо
c.poly([(18, 15), (26, 15), (27, 31), (17, 31)], 's')           # туловище
c.ellipse(22, 20, 4.5, 3, 'N')                                  # кожаный нагрудник
c.poly([(17, 16), (7, 27), (10, 29), (19, 20)], 's'); c.ellipse(8, 28, 2.2, 2.2, 'S')    # руки в стороны
c.poly([(27, 16), (37, 27), (34, 29), (25, 20)], 's'); c.ellipse(36, 28, 2.2, 2.2, 'S')
c.poly([(18, 30), (26, 30), (27, 34), (17, 34)], 'N')           # тёмные бёдра (одним тоном с лапами)
c.line(19, 33, 16, 42, 'N', th=2); c.line(25, 33, 28, 42, 'N', th=2)   # птичьи ноги
for x0 in (16, 28):
    c.ellipse(x0, 42, 2.5, 1.5, 'y')
    for dx in (-3, 0, 3): c.line(x0, 42, x0 + dx, 46, 'y', th=2)          # когти
c.outline(between=set())
harpy = [r.replace('k', '.') for r in c.rows()]
harpy = [list(r) for r in harpy]; harpy[10][20] = 'k'; harpy[10][24] = 'k'; harpy = [''.join(r) for r in harpy]

# ---------- бехолдер (композитор) 48×48: парящий шар с огромным глазом, стебли с глазками сверху, зубастая пасть ----------
c = Canvas(48, 48)
stalks = ((5, 5), (13, 2), (24, 0), (35, 2), (43, 5))
for x1, y1 in stalks: c.line(24, 20, x1, y1 + 2, 'p', th=2)     # стебли
c.ellipse(24, 29, 15, 15, 'p')                                  # шар
c.ellipse(24, 36, 11, 7, 'P')                                   # тень снизу
c.ellipse(15, 21, 4, 3, 'A')                                    # блик
for x1, y1 in stalks:                                           # глазки на стеблях
    c.ellipse(x1, y1 + 1, 2.2, 2.2, 'w'); c.put(x1, y1 + 1, 'k')
c.ellipse(24, 27, 10, 6.5, 'w')                                 # белок
c.ellipse(25, 27, 4.5, 4.5, 'b'); c.ellipse(25, 27, 1.8, 1.8, 'k')   # радужка, зрачок
c.poly([(13, 20), (35, 20), (34, 23), (14, 23)], 'P')           # нависшее веко
c.poly([(13, 37), (35, 37), (32, 41), (16, 41)], 'P')           # пасть
for x in range(15, 33, 4): c.poly([(x, 37), (x + 2, 41), (x + 4, 37)], 'i')   # зубы
c.outline(between=set())
beholder = [r.replace('k', '.') for r in c.rows()]
beholder = [list(r) for r in beholder]
for x1, y1 in stalks: beholder[y1 + 1][x1] = 'k'
for y in (26, 27): beholder[y][24] = 'k'; beholder[y][25] = 'k'
beholder = [''.join(r) for r in beholder]
# два лишних стебля для злого глаза — считаем композитором, отдаём как extra
c2 = Canvas(48, 48)
c2.line(12, 24, 1, 14, 'r', th=2); c2.line(36, 24, 47, 14, 'r', th=2)
c2.ellipse(1, 13, 2.2, 2.2, 'w'); c2.ellipse(47, 13, 2.2, 2.2, 'w'); c2.put(1, 13, 'k'); c2.put(47, 13, 'k')
evil_extra = [(x, y, ch) for y, row in enumerate(c2.rows()) for x, ch in enumerate(row) if ch != '.' and beholder[y][x] == '.']

# ---------- медуза (композитор) 48×52: змеиный хвост кольцом, женский торс в тёмном платье, волосы-змеи, лук ----------
c = Canvas(48, 52)
c.line(9, 8, 5, 20, 'N', th=2); c.line(5, 20, 9, 32, 'N', th=2)   # лук
c.line(9, 8, 9, 32, 'w', th=1)                                  # тетива
coil = ((24, 37), (12, 40), (6, 46), (16, 50), (34, 50), (44, 44), (46, 34), (44, 26))   # змеиный хвост S-петлёй
for i, ((x0, y0), (x1, y1)) in enumerate(zip(coil, coil[1:])): c.line(x0, y0, x1, y1, 'G', th=(8, 8, 8, 8, 7, 6, 4)[i])
for i, ((x0, y0), (x1, y1)) in enumerate(zip(coil, coil[1:])): c.line(x0, y0 - 1.5, x1, y1 - 1.5, 'g', th=(5, 5, 5, 5, 4, 3, 2)[i])   # свет по верху
c.line(12, 46, 34, 46, 'h', th=1); c.line(40, 42, 44, 36, 'h', th=1)   # полоса чешуи
c.poly([(19, 16), (29, 16), (28, 38), (20, 38)], 's')           # торс
c.poly([(18, 23), (30, 23), (29, 38), (19, 38)], 'P')           # платье
c.poly([(18, 23), (30, 23), (30, 25), (18, 25)], 'y')           # золотой пояс
c.poly([(19, 19), (6, 17), (6, 21), (19, 23)], 's'); c.ellipse(6, 19, 2, 2.5, 'S')     # рука к луку
c.poly([(29, 18), (13, 17), (13, 20), (29, 22)], 's')           # рука к тетиве
c.line(8, 19, 32, 19, 'N', th=1); c.poly([(5, 17), (9, 19), (5, 21)], 'l')   # стрела
c.ellipse(24, 7, 5.5, 4, 'G')                                   # шапка волос-змей
for x1, y1 in ((13, 2), (17, 0), (24, 0), (31, 0), (35, 2), (11, 9), (37, 9)):
    c.line(24, 7, x1, y1, 'G', th=2); c.ellipse(x1, y1, 1.6, 1.6, 'g')    # змеи с головками
c.ellipse(24, 10, 4.2, 4.8, 's')                                # лицо
c.outline(between=set())
medusa = [r.replace('k', '.') for r in c.rows()]
medusa = [list(r) for r in medusa]; medusa[10][22] = 'k'; medusa[10][26] = 'k'; medusa = [''.join(r) for r in medusa]

# ---------- мантикора (композитор) 60×58: лев с тёмной гривой, перепончатые крылья, хвост скорпиона с жалом ----------
c = Canvas(60, 58)
c.poly([(26, 30), (2, 8), (12, 0), (32, 6), (30, 20)], 'P')     # перепонка крыла
c.ellipse(12, 21, 5, 4, '.'); c.ellipse(33, 15, 3, 3, '.')      # вырезы между пальцами
for x1, y1 in ((2, 8), (12, 0), (32, 6)): c.line(26, 30, x1, y1, 'p', th=2)   # пальцы крыла
c.ellipse(32, 40, 20, 9, 'o')                                   # туловище
c.ellipse(32, 45, 15, 3.5, 'O')                                 # брюхо
c.ellipse(47, 27, 11, 10, 'N')                                  # грива
c.feathers([(38, 19), (56, 23)], 'N', 2.4, (0, -0.8))          # взъерошенная грива
c.ellipse(49, 27, 7, 6, 'o'); c.ellipse(54, 30, 5, 3.5, 'O')    # голова, морда
c.poly([(52, 31), (59, 31), (57, 34), (52, 33)], 'R')           # пасть
c.put(53, 31, 'w'); c.put(54, 31, 'w'); c.put(56, 31, 'w'); c.put(57, 31, 'w')   # клыки
for x, y in ((47, 24), (48, 24), (47, 25)): c.put(x, y, 'y')   # глаз
c.put(48, 25, 'k')
for x0, mat in ((12, 'O'), (20, 'o'), (38, 'O'), (46, 'o')):    # лапы
    c.poly([(x0, 46), (x0 - 1, 55), (x0 + 5, 55), (x0 + 6, 46)], mat)
    c.ellipse(x0 + 2, 55, 4, 2, 'O')
    for dx in (-2, 1, 4): c.poly([(x0 + dx, 55), (x0 + dx + 1, 58), (x0 + dx + 2, 55)], 'i')   # когти
tail = ((13, 37), (11, 34), (6, 29), (4, 23), (5, 17), (9, 12), (15, 9))
for (x0, y0), (x1, y1) in zip(tail, tail[1:]): c.line(x0, y0, x1, y1, 'R', th=3)   # стержень хвоста
for x, y in tail[1:]: c.ellipse(x, y, 2.8, 2.8, 'R')   # сегменты хвоста
c.poly([(15, 9), (22, 3), (19, 11)], 'R'); c.poly([(21, 5), (25, 1), (23, 7)], 'l')   # жало
c.outline(between=set())
manticore = [r.replace('k', '.') for r in c.rows()]
manticore = [list(r) for r in manticore]; manticore[25][48] = 'k'; manticore = [''.join(r) for r in manticore]

# ---------- красный дракон (композитор) 64×60: два перепончатых крыла, красная чешуя, золотое брюхо, рога, огонь в пасти ----------
c = Canvas(64, 60)
c.poly([(28, 30), (2, 4), (14, 0), (30, 4), (32, 22)], 'R')     # левое крыло
c.ellipse(13, 17, 5, 4, '.'); c.ellipse(32, 12, 3, 3, '.')
for x1, y1 in ((2, 4), (14, 0), (30, 4)): c.line(28, 30, x1, y1, 'r', th=2)
c.poly([(36, 30), (44, 2), (54, 0), (62, 8), (40, 24)], 'R')    # правое крыло
c.ellipse(44, 14, 4, 3, '.'); c.ellipse(54, 10, 3, 3, '.')
for x1, y1 in ((44, 2), (54, 0), (62, 8)): c.line(36, 30, x1, y1, 'r', th=2)
c.ellipse(30, 40, 18, 9, 'r')                                   # туловище
for y in range(42, 49): c.line(15 + (y - 42) // 2, y, 45 - (y - 42) // 2, y, 'y' if y % 2 == 0 else 'Y', th=1)   # пластины брюха
c.line(42, 36, 52, 18, 'r', th=6)                               # шея
c.ellipse(54, 14, 8, 6.5, 'r')                                  # голова
c.poly([(56, 16), (64, 19), (57, 20)], 'R')                     # нижняя челюсть
c.poly([(58, 15), (64, 17), (60, 17)], 'f')                     # огонь в пасти
c.put(53, 12, 'f'); c.put(54, 12, 'f'); c.put(53, 13, 'f'); c.put(54, 13, 'k')   # глаз
c.poly([(49, 10), (46, 2), (53, 8)], 'i'); c.poly([(55, 9), (57, 1), (59, 8)], 'i')   # рога
for x in range(16, 44, 6): c.poly([(x, 32), (x + 2, 27), (x + 4, 32)], 'R')   # шипы вдоль спины
for x0, mat in ((18, 'R'), (36, 'r')):                          # лапы
    c.poly([(x0, 46), (x0 - 2, 57), (x0 + 4, 57), (x0 + 5, 46)], mat)
    c.ellipse(x0 + 1, 57, 5, 2, 'R')
    for dx in (-3, 0, 3): c.poly([(x0 + dx, 57), (x0 + dx + 1, 60), (x0 + dx + 2, 57)], 'i')
c.line(14, 42, 3, 52, 'r', th=4); c.line(3, 52, 1, 58, 'r', th=2)   # хвост
c.poly([(0, 56), (4, 58), (0, 60)], 'R')                        # лопасть на хвосте
c.outline(between=set())
red_dragon = [r.replace('k', '.') for r in c.rows()]
red_dragon = [list(r) for r in red_dragon]; red_dragon[13][54] = 'k'; red_dragon = [''.join(r) for r in red_dragon]

out = "/* ============================================================================\n"
out += "   view/sprites_dungeon_hd.js — существа Темницы в крупной сетке (unit 2), стиль Б:\n"
out += "   без контурной линии, тона кладёт рисунок. Собирается скриптом dev/proto/dungeon_hd.py.\n"
out += "   ========================================================================== */\n(function () {\n  'use strict';\n  H3.Sprites.defineMany({\n"
out += block('troglodyte', troglodyte, 'троглодит: сгорбленный безглазый ящер, светлое брюхо, гребень на спине, дубина')
out += block('infernal_troglodyte', None, 'адский троглодит: красная кожа, огненное брюхо, тлеющая дубина', base='troglodyte', tint={'p': 'r', 'P': 'R', 'A': 'f', 'T': 'F', 'n': 'O', 'N': 'R'})
out += block('harpy', harpy, 'гарпия: крылатая женщина, тёмные волосы, золотые крылья вверх, птичьи лапы с когтями (композитор)')
out += block('harpy_hag', None, 'гарпия-ведьма: зелёная кожа, пурпурные крылья, чёрные волосы, красные глаза', base='harpy', tint={'s': 'g', 'S': 'G', 'y': 'p', 'Y': 'P', 'R': 'z', 'k': 'r'})
out += block('beholder', beholder, 'бехолдер: парящий шар с огромным глазом, стебли с глазками сверху, зубастая пасть (композитор)')
out += block('evil_eye', None, 'злой глаз: красный, жёлтая радужка, два лишних стебля по бокам', base='beholder', tint={'p': 'r', 'P': 'R', 'b': 'y', 'A': 'o'}, extra=evil_extra)
out += block('medusa', medusa, 'медуза: змеиный хвост кольцом, торс в тёмном платье, волосы-змеи, лук со стрелой (композитор)')
out += block('medusa_queen', None, 'королева медуз: синее платье, золотая полоса чешуи, золотая тиара', base='medusa', tint={'P': 'B', 'h': 'y'},
             extra=[(x, y, 'y') for y in (5, 6) for x in range(20, 29)] + [(x, 4, 'y') for x in (20, 21, 23, 24, 25, 27, 28)] + [(x, 7, 'Y') for x in range(20, 29)])
out += block('minotaur', minotaur, 'минотавр: тёмная бычья голова с рогами, загорелый торс, красная повязка, двусторонняя секира')
out += block('minotaur_king', None, 'король минотавров: золотая корона, золотая секира, пурпурная повязка', base='minotaur', tint={'e': 'y', 'l': 'i', 'r': 'M', 'R': 'x'},
             extra=[(x, y, 'y') for y in (5, 6) for x in range(11, 24)] + [(x, 4, 'y') for x in (11, 12, 16, 17, 21, 22)] + [(x, 7, 'Y') for x in range(11, 24)])
out += block('manticore', manticore, 'мантикора: лев с тёмной гривой, перепончатые крылья, хвост скорпиона с жалом (композитор)')
out += block('scorpicore', None, 'скорпикора: тёмно-красная шерсть, серые крылья, чёрный хвост, светящийся глаз и жало', base='manticore', tint={'o': 'r', 'O': 'R', 'N': 'D', 'P': 'e', 'p': 'E', 'R': 'z', 'y': 'h', 'l': 'f'})
out += block('red_dragon', red_dragon, 'красный дракон: два перепончатых крыла, красная чешуя, золотое брюхо, рога, огонь в пасти (композитор)')
out += block('black_dragon', None, 'чёрный дракон: чёрная чешуя, серое брюхо, светлые рога, оранжевые глаза', base='red_dragon', tint={'r': 'u', 'R': 'z', 'y': 'e', 'Y': 'E', 'i': 'l', 'f': 'o'})
out += "  });\n})();\n"
p = os.path.join(os.path.dirname(__file__), '..', '..', 'js', 'view', 'sprites_dungeon_hd.js')
io.open(p, 'w', encoding='utf-8').write(out)
print('записан', os.path.relpath(p))
