# -*- coding: utf-8 -*-
"""Сборка js/view/sprites_factory_hd.js: 14 существ Фабрики в крупной сетке (unit 2), стиль Б.
Полурослик, механик, автоматон, стрелок — строками; броненосец, песчаный червь, коатль — композитором."""
import io, os, sys, math
sys.path.insert(0, os.path.dirname(__file__))
from compose import Canvas
from castle_hd import rows_from, pad, block, stretch   # общие помощники (castle_hd при импорте пересобирает свой файл — это безвредно)

def check(name, rows):
    """служебная проверка: все строки одной ширины (ошибка счёта при ручном наборе)"""
    w = len(rows[0]); bad = [(i, len(r)) for i, r in enumerate(rows) if len(r) != w]
    if bad: print('ШИРИНА %s: ожидалось %d — %s' % (name, w, bad))

def find_row(rows, needle, start=0):
    """первая строка (с индекса start), содержащая подстроку — чтобы задавать extra по итоговой сетке после stretch"""
    for i in range(start, len(rows)):
        if needle in rows[i]: return i
    raise ValueError(needle)

# ---------- полурослик 36×44: маленький, круглая голова, шляпа с полями, зелёная куртка и жилет, рогатка в вытянутой руке, босые ноги ----------
halfling = rows_from("""
..........HHHHHHHHHH................
.........HHHHHHHHHHHH...............
.........HHHHHHHHHHHH...............
.........HHHHHHHHHHHH...............
.........HHHHHHHHHHHH...............
.....HHHHHHHHHHHHHHHHHHHH...........
....HHHHHHHHHHHHHHHHHHHHHH..........
.........ssssssssssss...............
........ssssssssssssss..............
........ssssswkwsswkws..............
........ssssswkwsswkws..............
........ssssssssssssss..............
........ssssssSSSSssss..............
.........ssssssssssss...............
..........ssssssssss................
........GGGGGGGGGGGGGGGGGGG.........
......GGGGGGGGGGGGGGGGGGGGG.........
.....GGGGGGGGIIIIIIIGGGGGGG.........
.....GGGGGGGGIIIIIIIGGGGGGG.........
.....GGGGGGGGIIIIIIIGGGGGGG.........
.....GGGGGGGGIIIIIIIGGGGGGG.........
.....GGGGGGGGIIIIIIIGGGGGG..........
.....GGGGGGGGIIIIIIIGGGGGG..........
.....GGGGGGGGIIIIIIIGGGGGG..........
.....GGGG.GGGIIIIIIIGGGGG...........
.....GGGG.GGGIIIIIIIGGGGG...........
.....ssss.DDDDDyyyDDDDD.............
.....ssss.DDDDDyyyDDDDD.............
..........TTTTTTTTTTTTT.............
..........TTTTTTTTTTTTT.............
..........TTTTTT.TTTTTT.............
..........TTTTTT.TTTTTT.............
..........TTTTTT.TTTTTT.............
..........TTTTTT.TTTTTT.............
..........TTTTTT.TTTTTT.............
.........nnnnnnn.nnnnnnn............
.........nnnnnnn.nnnnnnn............
........nnnnnnnn.nnnnnnnn...........
""")
check('halfling', halfling)
halfling = [list(r) for r in halfling]
for y in range(16, 20):                                            # правая рука вытянута вперёд: рукав и кисть
    for x in range(26, 30): halfling[y][x] = 'G'
    for x in range(30, 34): halfling[y][x] = 's'
for y in range(11, 16):                                            # рукоять рогатки над кистью
    for x in (31, 32, 33): halfling[y][x] = 'n'
for y in range(5, 11):                                             # две рожки расходятся вверх
    t = (11 - y) / 6.0
    xl = int(round(31 - 3 * t)); xr = int(round(33 + 2 * t))
    halfling[y][xl] = 'n'; halfling[y][xl + 1] = 'n'; halfling[y][xr - 1] = 'n'; halfling[y][xr] = 'n'
for y in (3, 4):                                                   # тёмная резина между рожками
    for x in range(28, 36): halfling[y][x] = 'D'
for y in (1, 2):                                                   # кожаный кармашек с камнем
    for x in range(30, 34): halfling[y][x] = 'D'
halfling[2][31] = 'e'; halfling[2][32] = 'e'; halfling[3][31] = 'e'; halfling[3][32] = 'e'
halfling = [''.join(r) for r in halfling]
halfling = stretch(halfling, 44, [(17, 25), (29, 34)])
# гренадёр: пояс с гранатами и бомба в кармашке рогатки — координаты по итоговой сетке
_belt = find_row(halfling, 'DDDDDyyyDDDDD')
grenadier_extra = [(x, y, 'e') for y in (_belt, _belt + 1) for x in (11, 12, 20, 21)] + [(31, 0, 'f'), (32, 0, 'f'), (31, 1, 'f'), (32, 1, 'f')]

# ---------- механик 40×48: тёмные волосы, очки на лбу, синяя рубаха, кожаный фартук с карманом, большой гаечный ключ в поднятой руке ----------
mechanic = rows_from("""
...............NNNNNNNN........eee..eee.
..............NNNNNNNNNN.......eee..eee.
.............NecccecccccN......eee..eee.
.............NecccecccceN......eeeeeeee.
.............NNeeeeeeeeNN......eeeeeeee.
.............NNNNNNNNNNNN.......eeeeee..
.............Nsssssssssss.........ele...
.............Nsssssssssss.........ele...
.............Nssswkwsswkw.........ele...
.............Nssswkwsswkw.........ele...
..............sssssssssss.........ele...
..............sssssSSSsss.........ele...
...............sssssssss..........ele...
................sssssss...........ele...
............bbbbbbbbbbbbbbbb......ele...
..........bbbbbbbbbbbbbbbbbbbb....ele...
.........bbbbbDDDDDDDDbbbbbbbbbb..ele...
.........bbbbbDDDDDDDDbbbbbbbbbbbsssss..
.........bbbbbDDDDDDDDbbbbbbbbbbbsssss..
.........bbbbbDDDDDDDDbbbbbb.....sssss..
.........bbbb.DDDDDDDDDDDDDbbb..........
.........bbbb.DDDDDDDDDDDDDbbb..........
.........bbbb.DDDnnnnnnnDDDbbb..........
.........bbbb.DDDnnnnnnnDDDbbb..........
.........bbbb.DDDnnnnnnnDDDbbb..........
.........ssss.DDDDDDDDDDDDDbbb..........
.........ssss.DDDDDDDDDDDDDbbb..........
..............DDDDDDDDDDDDDbbb..........
..............DDDDDDDDDDDDDbbb..........
..............DDDDDDDDDDDDD.............
..............DDDDDDDDDDDDD.............
..............eeeeee.eeeeee.............
..............eeeeee.eeeeee.............
..............eeeeee.eeeeee.............
..............eeeeee.eeeeee.............
..............eeeeee.eeeeee.............
.............DDDDDDD.DDDDDDD............
.............DDDDDDD.DDDDDDD............
............DDDDDDDD.DDDDDDDD...........
""")
check('mechanic', mechanic)
mechanic = [list(r) for r in mechanic]
mechanic[2][18] = 'e'; mechanic[3][18] = 'e'; mechanic[2][23] = 'e'; mechanic[3][23] = 'e'   # оправа очков: две линзы c в рамке e
mechanic[2][14] = 'e'; mechanic[3][14] = 'e'
mechanic = [''.join(r) for r in mechanic]
mechanic = stretch(mechanic, 48, [(20, 30), (31, 36)])
_bib = find_row(mechanic, 'bbbbbDDDDDDDDbbbb')
engineer_extra = [(x, y, 'y') for y in (_bib + 1, _bib + 2) for x in range(16, 20)] + [(17, _bib, 'y'), (18, _bib, 'y'), (17, _bib + 3, 'y'), (18, _bib + 3, 'y')]   # медная шестерня на нагруднике

# ---------- автоматон 48×54: паровой робот из латуни и меди, круглая голова с трубой и паром, топка на груди, заклёпки, поршневые руки ----------
automaton = rows_from("""
.........................lllll..................
........................lllllll.................
.........................lllll..................
..........................uuu...................
..........................uuu...................
..............YYYYYYYYYYYYYYYYYY................
.............YYYYYYYYYYYYYYYYYYYY...............
.............YYyyyyyyyyyyyyyyyyYY...............
.............YYyyyDDDDyyyDDDDyyYY...............
.............YYyyyDccDyyyDccDyyYY...............
.............YYyyyDccDyyyDccDyyYY...............
.............YYyyyDDDDyyyDDDDyyYY...............
.............YYyyyyyyyyyyyyyyyyYY...............
.............YYyyyyEEEEEEEEyyyyYY...............
.............YYyyyyyyyyyyyyyyyyYY...............
..............YYYYYYYYYYYYYYYYYY................
...................uuuuuu.......................
...................uuuuuu.......................
........YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY..........
......YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY........
.....uuuuuYYyyyyyyyyyyyyyyyyyyyyYYuuuuu.........
.....uuuuuYYyyyyyyyyyyyyyyyyyyyyYYuuuuu.........
.....uuuuuYYyyNNyyyyyyyyyyyyNNyyYYuuuuu.........
.....uuuuuYYyyNNyyyyyyyyyyyyNNyyYYuuuuu.........
.....uuuuuYYyyyyyyyOOOOOOyyyyyyyYYuuuuu.........
.....uuuuuYYyyyyyyOOffffOOyyyyyyYYuuuuu.........
.....uuuuuYYyyyyyyOffFFffOyyyyyyYYuuuuu.........
.....uuuuuYYyyyyyyOffFFffOyyyyyyYYuuuuu.........
.....uuuuuYYyyyyyyOOffffOOyyyyyyYYuuuuu.........
.....uuuuuYYyyyyyyyOOOOOOyyyyyyyYYuuuuu.........
.....uuuuuYYyyNNyyyyyyyyyyyyNNyyYYuuuuu.........
.....uuuuuYYyyNNyyyyyyyyyyyyNNyyYYuuuuu.........
...YYYYYY.YYyyyyyyyyyyyyyyyyyyyyYY.YYYYYY.......
...YYYYYY.YYyyyyyyyyyyyyyyyyyyyyYY.YYYYYY.......
...YYYYYY.YYyyyyyyyyyyyyyyyyyyyyYY.YYYYYY.......
...YYYYYY.YYYYYYYYYYYYYYYYYYYYYYYY.YYYYYY.......
..........YYYYYYYYYYYYYYYYYYYYYYYY..............
.............uuuuuuuu....uuuuuuuu...............
.............uuuuuuuu....uuuuuuuu...............
.............YYYYYYYY....YYYYYYYY...............
.............YYYYYYYY....YYYYYYYY...............
.............uuuuuuuu....uuuuuuuu...............
.............uuuuuuuu....uuuuuuuu...............
.............uuuuuuuu....uuuuuuuu...............
...........YYYYYYYYYY..YYYYYYYYYY...............
...........YYYYYYYYYY..YYYYYYYYYY...............
...........YYYYYYYYYY..YYYYYYYYYY...............
""")
check('automaton', automaton)
automaton = stretch(automaton, 54, [(20, 32), (41, 44)])

# ---------- стрелок 56×58: широкополая шляпа с лентой, усы, красный платок, светлый плащ-пыльник до колен, длинное ружьё с латунной казённой частью ----------
gunslinger = rows_from("""
..................DDDDDDDDDD............................
.................DDDDDDDDDDDD...........................
.................DDDDDDDDDDDD...........................
.................DDDDDDDDDDDD...........................
.................DDYYYYYYYYDD...........................
..........DDDDDDDDDDDDDDDDDDDDDDDDDD....................
.........DDDDDDDDDDDDDDDDDDDDDDDDDDDD...................
..................ssssssssssss..........................
.................ssssssssssssss.........................
.................ssssswkwsswkws.........................
.................ssssswkwsswkws.........................
.................ssssssssssssss.........................
.................ssssssNNNNNsss.........................
..................ssssssssssss..........................
...................ssssssssss...........................
..................rrrrrrrrrrrr..........................
..............TTTTrrrrrrrrrrrrTTTT......................
............TTTTTTTTTTTTTTTTTTTTTTTT....................
...........TTTTTTTTTTTTTTTTTTTTTTTTTT...................
..........TTTTTTTTTTTTTTTTTTTTTTTTTTTT..................
..........TTTTTTTTTTTTTTTTTTTTTTTTTTTT..................
..........TTTTTTTTTTTTTTTTTTTTTTTTTTTT..................
..........TTTTTTTTTTTTNNNNNNNNNNlllllEEEEEEEEEEEEEEEEEEE
..........TTTTTTTTTTTTNNNNNNNNNNllllllllllllllllllllllll
..........TTTTTTTTTTTTNNNNNNNNNNlllllEEEEEEEEEEEEEEEEEEE
..........TTTTTTTTTTTTNNNNNNNNNNlllllTTTTsssss..........
..........TTTTTTTTTTTTNNNNNNNNTTTTTTTTTTTsssss..........
..........TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTsssss..........
..........TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTsssss..........
..........TTTTTTTTTTTTTTTTTTTTTTTTTTTT..................
..........TTTTTTTTTTTTTTTTTTTTTTTTTTTT..................
..........TTTTNNNNNNNNNyyNNNNNNNNNTTTT..................
..........TTTTNNNNNNNNNyyNNNNNNNNNTTTT..................
..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................
..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................
..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................
..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................
..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................
..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................
..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................
..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................
..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................
............uuuuuuuuuuuu..uuuuuuuuuuuu..................
............uuuuuuuuuuuu..uuuuuuuuuuuu..................
............uuuuuuuuuuuu..uuuuuuuuuuuu..................
............uuuuuuuuuuuu..uuuuuuuuuuuu..................
............nnnnnnnnnnnn..nnnnnnnnnnnn..................
............nnnnnnnnnnnn..nnnnnnnnnnnn..................
...........nnnnnnnnnnnnn..nnnnnnnnnnnnn.................
...........NNNNNNNNNNNNN..NNNNNNNNNNNNN.................
""")
check('gunslinger', gunslinger)
gunslinger = [list(r) for r in gunslinger]
for y in range(22, 26):                                             # задняя рука на прикладе
    for x in range(26, 31): gunslinger[y][x] = 's'
gunslinger = [''.join(r) for r in gunslinger]
gunslinger = stretch(gunslinger, 58, [(17, 21), (33, 41), (42, 46)])
_barrel = find_row(gunslinger, 'EEEEEEEEEE')
_bandolier = [(x, y, 'y') for x, y in ((14 + k, _barrel - 6 + k // 2) for k in range(0, 14, 1))]
bounty_extra = [(x, _barrel - 1, 'E') for x in range(40, 47)] + [(x, _barrel - 2, 'c') for x in range(40, 47)] + [(x, _barrel - 3, 'E') for x in range(40, 47)]   # оптический прицел на стволе
bounty_extra += [(x, y, 'y') for y in range(_barrel - 5, _barrel) for x in (12 + (y - (_barrel - 5)) * 2, 13 + (y - (_barrel - 5)) * 2)]   # патронташ наискось по груди

# ---------- броненосец (композитор) 52×48: песочный панцирь пластинами с тёмными швами, бурая голова с вытянутой мордой, четыре лапы, хвост ----------
c = Canvas(52, 48)
c.ellipse(24, 30, 20, 16, 't')                          # купол панциря
for x0 in (10, 18, 26, 34):                             # швы между пластинами (только по панцирю)
    for y in range(10, 48):
        for x in (x0, x0 + 1):
            if c.get(x, y) == 't': c.put(x, y, 'N')
c.ellipse(24, 42, 15, 5.5, 'd')                          # брюхо
c.ellipse(24, 40, 19, 3, 'T')                            # нижняя кромка панциря
c.ellipse(42, 32, 8, 6.5, 'd')                           # голова
c.poly([(46, 28), (52, 33), (46, 37)], 'd')              # вытянутая морда
c.poly([(38, 22), (41, 29), (44, 27)], 'd'); c.poly([(43, 22), (44, 28), (47, 26)], 'd')   # уши
c.put(44, 30, 'y'); c.put(45, 30, 'y'); c.put(44, 31, 'y'); c.put(45, 31, 'k')   # глаз
c.put(50, 32, 'k'); c.put(50, 33, 'k')                   # ноздря
c.poly([(8, 34), (0, 44), (3, 47), (11, 39)], 'd')       # хвост
for x0 in (11, 19, 30, 38):                              # четыре лапы
    c.poly([(x0, 40), (x0 - 1, 47), (x0 + 5, 47), (x0 + 6, 40)], 'd')
    for dx in (-1, 2): c.poly([(x0 + dx, 45), (x0 + dx + 1, 48), (x0 + dx + 2, 45)], 'i')   # когти
c.outline(between=set())
armadillo = [r.replace('k', '.') for r in c.rows()]
armadillo = [list(r) for r in armadillo]; armadillo[31][45] = 'k'; armadillo[32][50] = 'k'; armadillo[33][50] = 'k'; armadillo = [''.join(r) for r in armadillo]
bellwether_extra = [(x, y, 'i') for x0 in (14, 22, 30) for x, y in ((x0, 15), (x0 + 1, 15), (x0, 14), (x0 + 1, 14), (x0, 13), (x0 + 1, 13), (x0 + 1, 12))]   # шипы на хребте

# ---------- песчаный червь (композитор) 60×60: кольчатое тело поднимается из песка, раскрытая пасть-воронка кверху с рядами зубов ----------
c = Canvas(60, 60)
c.ellipse(20, 57, 20, 4, 'T')                            # песчаный холм
path = [(6, 55, 4), (12, 54, 5), (18, 52, 6), (24, 49, 7), (29, 44, 8), (33, 38, 9), (36, 31, 9.5), (38, 24, 10), (40, 17, 10.5)]
for x, y, r in path:                                    # сегменты: тёмный обод + светлая середина, каждый следующий накрывает предыдущий
    c.ellipse(x, y, r, r * 0.85, 'd')
    c.ellipse(x, y, r - 2, r * 0.85 - 2, 't')
c.ellipse(41, 12, 12, 8, 'd'); c.ellipse(41, 12, 10, 6, 't')   # голова
c.poly([(28, 1), (54, 1), (48, 13), (34, 13)], 'M')             # раскрытая пасть-воронка кверху
c.poly([(30, 1), (52, 1), (47, 4), (35, 4)], 'R')               # глубина глотки
for x in range(30, 52, 4):                                      # ряд зубов по краю пасти
    c.poly([(x, 1), (x + 2, 5), (x + 4, 1)], 'i')
for x in range(33, 49, 4):                                      # второй ряд зубов внутри
    c.poly([(x, 8), (x + 2, 11), (x + 4, 8)], 'i')
c.outline(between=set())
sandworm = [r.replace('k', '.') for r in c.rows()]

# ---------- коатль (композитор) 64×60: пернатый змей, золотые крылья с тёмными опахалами, зелёное тело со светлым брюхом, гребень, раскрытая пасть ----------
c = Canvas(64, 60)
c.poly([(34, 32), (6, 8), (2, 16), (12, 30), (30, 40)], 'y')              # дальнее крыло вверх-влево
c.poly([(38, 32), (63, 20), (62, 28), (52, 38), (40, 42)], 'y')           # ближнее крыло вправо, ниже головы
c.feathers([(2, 16), (12, 30)], 'y', 2.4, (-0.5, 0.6))                    # зубчатые кромки
c.feathers([(62, 28), (52, 38)], 'y', 2.4, (0.4, 0.7))
for x1, y1 in ((6, 8), (3, 14), (10, 24)): c.line(34, 32, x1, y1, 'Y', th=1)   # маховые перья
for x1, y1 in ((63, 20), (62, 26), (56, 34)): c.line(38, 32, x1, y1, 'Y', th=1)
c.poly([(34, 32), (6, 8), (10, 14), (30, 36)], 'Y')                        # тёмное опахало у корня
c.poly([(38, 32), (63, 20), (58, 26), (40, 36)], 'Y')
spine = [(4, 58), (12, 57), (22, 54), (32, 48), (38, 40), (40, 32), (36, 24), (38, 16), (42, 10)]
for i in range(len(spine) - 1):                                           # тело: толстая зелёная линия
    (x0, y0), (x1, y1) = spine[i], spine[i + 1]
    c.line(x0, y0, x1, y1, 'g', th=8 if i > 0 else 5)
for i in range(1, len(spine) - 2):                                        # светлое брюхо по нижней стороне
    (x0, y0), (x1, y1) = spine[i], spine[i + 1]
    c.line(x0 + 1, y0 + 2, x1 + 1, y1 + 2, 'h', th=3)
c.ellipse(46, 8, 9, 6, 'g')                                               # голова
c.poly([(50, 8), (61, 6), (61, 9), (50, 11)], 'g')                        # верхняя челюсть
c.poly([(50, 10), (60, 16), (52, 16)], 'g')                               # нижняя челюсть
c.poly([(51, 9), (59, 9), (57, 14), (52, 12)], 'R')                       # раскрытая пасть
c.poly([(52, 9), (53, 12), (54, 9)], 'w'); c.poly([(56, 9), (57, 12), (58, 9)], 'w')   # клыки
c.feathers([(38, 5), (46, 1)], 'y', 2.2, (0, -0.6))                       # золотой гребень
c.put(48, 6, 'w'); c.put(49, 6, 'w'); c.put(48, 7, 'w'); c.put(49, 7, 'k')   # глаз
c.outline(between=set())
couatl = [r.replace('k', '.') for r in c.rows()]
couatl = [list(r) for r in couatl]; couatl[7][49] = 'k'; couatl = [''.join(r) for r in couatl]

out = "/* ============================================================================\n"
out += "   view/sprites_factory_hd.js — существа Фабрики в крупной сетке (unit 2), стиль Б:\n"
out += "   без контурной линии, тона кладёт рисунок. Собирается скриптом dev/proto/factory_hd.py.\n"
out += "   ========================================================================== */\n(function () {\n  'use strict';\n  H3.Sprites.defineMany({\n"
out += block('halfling', halfling, 'полурослик: маленький, шляпа с полями, зелёная куртка и жилет, рогатка с камнем в вытянутой руке, босые ноги')
out += block('halfling_grenadier', None, 'гренадёр: куртка в хаки, шляпа бурая, в рогатке бомба с искрящимся фитилём, гранаты на поясе', base='halfling', tint={'G': 'H', 'H': 'd', 'e': 'E'}, extra=grenadier_extra)
out += block('mechanic', mechanic, 'механик: очки на лбу, синяя рубаха, кожаный фартук с карманом, большой гаечный ключ')
out += block('engineer', None, 'инженер: рубаха в рыжий, ключ и очки из латуни, шестерня на нагруднике', base='mechanic', tint={'b': 'o', 'n': 'y', 'e': 'Y'}, extra=engineer_extra)
out += block('armadillo', armadillo, 'броненосец: песочный панцирь пластинами, бурая голова с вытянутой мордой, четыре лапы, хвост (композитор)')
out += block('bellwether_armadillo', None, 'вожак броненосцев: панцирь в бронзу со светлыми швами, тело темнее, костяные шипы на хребте', base='armadillo', tint={'t': 'O', 'N': 'i', 'd': 'D'}, extra=bellwether_extra)
out += block('automaton', automaton, 'автоматон: паровой робот из латуни, труба с паром, топка на груди, заклёпки, поршневые руки')
out += block('sentinel_automaton', None, 'автоматон-страж: сталь темнеет, глаза и топка горят алым', base='automaton', tint={'Y': 'E', 'y': 'e', 'u': 'z', 'O': 'D', 'f': 'r', 'F': 'f', 'c': 'r'})
out += block('sandworm', sandworm, 'песчаный червь: кольчатое тело поднимается из песка, пасть-воронка кверху с рядами зубов (композитор)')
out += block('olgoi_khorkhoi', None, 'олгой-хорхой: тело рыжеет, кольца в тёмно-красный, пасть алая', base='sandworm', tint={'t': 'o', 'd': 'R', 'M': 'r', 'R': 'D', 'T': 'O'})
out += block('gunslinger', gunslinger, 'стрелок: широкополая шляпа, усы, красный платок, светлый плащ-пыльник, длинное ружьё')
out += block('bounty_hunter', None, 'охотник за головами: плащ бордовый, платок золотой, оптика на стволе, патронташ через грудь', base='gunslinger', tint={'T': 'R', 'r': 'Y', 'N': 'n', 'u': 'e'}, extra=bounty_extra)
out += block('couatl', couatl, 'коатль: пернатый змей, золотые крылья, зелёное тело со светлым брюхом, гребень, раскрытая пасть (композитор)')
out += block('crimson_couatl', None, 'багровый коатль: тело в багрянец, брюхо розовое, крылья огненные', base='couatl', tint={'g': 'M', 'h': 'm', 'y': 'f', 'Y': 'O', 'R': 'z'})
out += "  });\n})();\n"
p = os.path.join(os.path.dirname(__file__), '..', '..', 'js', 'view', 'sprites_factory_hd.js')
io.open(p, 'w', encoding='utf-8').write(out)
print('записан', os.path.relpath(p))
