# -*- coding: utf-8 -*-
"""Сборка js/view/sprites_fortress_hd.js: 14 существ Крепости в крупной сетке (unit 2), стиль Б.
Гнолл и ящер — строками; змеемуха, василиск, горгона, виверна, гидра — композитором."""
import io, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from compose import Canvas
from castle_hd import rows_from, pad, block, stretch   # общие помощники (castle_hd при импорте пересобирает свой файл — это безвредно)

# ---------- гнолл 40×48: гиеноголовый, тёмные уши и грива, светлая морда с клыками, кожаный жилет, алебарда ----------
gnoll = rows_from("""
........DD...........DD...........l.....
.......DDDD.........DDDD.........lll....
.......DDDDD.......DDDDD.........lll....
.......DDDDDDDDDDDDDDDDD......llllll....
.......DDDDDDDDDDDDDDDDD....llllllll....
.......nnnnnnDDDDDnnnnnn...llllllll.....
.......nnnnnnnnnnnnnnnnn..llllllllD.....
.......nnnnnnnnnnnnnnnnn..lllllllDDD....
.......nnyyynnnnnnnyyynn..lllllllDDD....
.......nnykynnnnnnnykynn...llllllDDD....
.......nnyyynnnnnnnyyynn....lllllDDD....
.......nnnnnnnnnnnnnnnnn......lllDDD....
........nnnnntttttttnnnn.........DDD....
........nnnttttttttttnnn.........DDD....
.........nntkkttttkktnn..........DDD....
.........nntkkttttkktnn..........DDD....
..........nttttttttttn...........DDD....
...........twwttttwwt............DDD....
...........www.nnn.www...........DDD....
.............nnnnnnn.............DDD....
.........NNNNNNNNNNNNNNNNN.......DDD....
.......NNNNNNNNNNNNNNNNNNNNN.....DDD....
....nnnnNNNNNNNNNNNNNNNNNNNnnnn..DDD....
....nnnnNNNNNNNNNNNNNNNNNNNnnnn..DDD....
....nnnnNNNNNNNNNNNNNNNNNNNnnnnnnDDDnn..
....nnnnNNNNNNNNNNNNNNNNNNNnnnnnnDDDnn..
....nnnnNNNNNNNNNNNNNNNNNNNnnnnnnDDDnn..
....nnnnNNNNNNNNNNNNNNNNNNNnnnnnnnnnnn..
....nnnnNNNNNNNNNNNNNNNNNNN......DDD....
....nnnn.NNNNNNNNNNNNNNNNN.......DDD....
....nnnn.NNNNNNNNNNNNNNNNN.......DDD....
....nnnn.yyyyyyyyyyyyyyyyy.......DDD....
....nnnn.yyyyyyyyyyyyyyyyy.......DDD....
.....nn..TTTTTTTTTTTTTTTTT.......DDD....
.........TTTTTTTTTTTTTTTTT.......DDD....
.........TTTTTTTTTTTTTTTTT.......DDD....
.........TTTTTTTTTTTTTTTTT.......DDD....
.........nnnnnn...nnnnnn.........DDD....
.........nnnnnn...nnnnnn.........DDD....
.........nnnnnn...nnnnnn.........DDD....
.........nnnnnn...nnnnnn.........DDD....
........DDDDDDD...DDDDDDD........DDD....
........DDDDDDD...DDDDDDD........DDD....
""")
gnoll = [list(r) for r in gnoll]
for y in (24, 25): gnoll[y][5] = 'D'; gnoll[y][6] = 'D'                       # пятна гиены на руках и ногах
for y in (38, 39): gnoll[y][10] = 'D'; gnoll[y][11] = 'D'; gnoll[y][21] = 'D'; gnoll[y][22] = 'D'
gnoll = [''.join(r) for r in gnoll]
gnoll = stretch(gnoll, 48, [(20, 30), (36, 40)])

# ---------- ящер 40×48: зелёный ящер с тёмным гребнем, светлое брюхо и челюсть, набедренная повязка, лук, хвост ----------
lizardman = rows_from("""
...........GG...GG...GG.................
..........GGGGGGGGGGGGGG................
.........GGGGGGGGGGGGGGG................
........gggggggggggggggg................
........gggggggggggggggg................
........ggyyygggggggyyyg.........N......
........ggykygggggggykyg........Nn......
........ggyyygggggggyyyg.......Nn.......
........gggggggggggggggg......Nn........
........gggggggggggggggg.....Nn.........
.........ghhhhhhhhhhhhg......Nn.........
..........hhhhhhhhhhhh.......Nn.........
..........hhhhhhhhhhhh.......Nn.........
..........hGGGGGGGGGGh.......Nn.........
...........hhhhhhhhhh........Nn.........
.............gggggg..........Nn.........
.............gggggg..........Nn.........
......gggggggggggggggggggg...Nn.........
....gggggggggggggggggggggggg.Nn.........
...ggggggggghhhhhhhhggggggggggn.........
...gggggggghhhhhhhhhhgggggggggn.........
...gggggggghhhhhhhhhhgggggggggn.........
...gggggggghhhhhhhhhhggggggggggg........
...gggggggghhhhhhhhhhggggggggggg........
...gggggggghhhhhhhhhhggggggggggg........
...gggg.ggghhhhhhhhhhggg.....Nn.........
...gggg.ggghhhhhhhhhhggg.....Nn.........
...gggg.ggghhhhhhhhhhggg.....Nn.........
...gggg.gggghhhhhhhhgggg.....Nn.........
....gg..gggggggggggggggg.....Nn.........
........dddddddddddddddd......Nn........
........dddddddddddddddd.......Nn.......
........dddddddddddddddd........Nn......
........dddddddddddddddd.........N......
........dddddddddddddddd................
.........gggggg...gggggg................
.....GGGGgggggg...gggggg................
...GGGGGGgggggg...gggggg................
.GGGGGG..gggggg...gggggg................
GGGGG...GGGGGGG...GGGGGGG...............
GGG.....GGGGGGG...GGGGGGG...............
""")
lizardman = [list(r) for r in lizardman]
for y in range(6, 34):                                                     # тетива
    if lizardman[y][30] == '.': lizardman[y][30] = 'w'
for y in range(5, 34):                                                     # дуга лука толще: вторая полоса «n» левее «N»
    for x in range(29, 34):
        if lizardman[y][x] == 'N' and lizardman[y][x - 1] == 'n': lizardman[y][x + 1] = 'N'
for y in range(11, 20): lizardman[y][1] = 'N'; lizardman[y][2] = 'N'; lizardman[y][3] = 'n'; lizardman[y][4] = 'n'   # колчан за левым плечом
for x in (1, 2, 3, 4): lizardman[10][x] = 'l'; lizardman[9][x] = 'l'; lizardman[8][x] = 'I'
lizardman = [''.join(r) for r in lizardman]
lizardman = stretch(lizardman, 48, [(19, 29), (35, 39)])

# ---------- змеемуха (композитор) 44×48: змеиное тело с тёмной спиной, четыре голубых крыла с прожилками, большие глаза ----------
c = Canvas(44, 48)
c.ellipse(15, 15, 12, 4.5, 'c', rot=0.7)                   # верхнее левое крыло
c.ellipse(35, 17, 11, 4, 'c', rot=-0.6)                    # верхнее правое
c.ellipse(13, 29, 12, 4, 'c', rot=-0.35)                   # нижнее левое
c.ellipse(35, 29, 10, 3.5, 'c', rot=0.55)                  # нижнее правое
c.line(26, 24, 6, 8, 'C', th=1); c.line(26, 24, 43, 10, 'C', th=1)     # прожилки
c.line(26, 26, 3, 32, 'C', th=1); c.line(26, 26, 43, 35, 'C', th=1)
c.line(26, 26, 15, 34, 'C', th=1); c.line(26, 26, 33, 24, 'C', th=1)
c.line(26, 27, 21, 36, 'g', th=5); c.line(21, 36, 14, 43, 'g', th=4); c.line(14, 43, 6, 46, 'g', th=3)   # хвост вниз
c.ellipse(26, 25, 6, 7, 'g')                               # грудь
c.line(27, 20, 27, 12, 'g', th=5)                          # шея
c.ellipse(27, 9, 6.5, 5.5, 'g')                            # голова
c.ellipse(32, 11, 3.5, 2.5, 'h')                           # светлая морда
c.line(24, 30, 19, 37, 'G', th=2); c.line(19, 37, 12, 44, 'G', th=1)   # тёмная спинка хвоста
c.ellipse(24, 25, 2.5, 4.5, 'h')                           # светлое брюшко
c.ellipse(23.5, 8, 2.8, 2.5, 'y'); c.ellipse(30.5, 7, 2.8, 2.5, 'y')   # большие глаза
c.outline(between=set())
serpent_fly = [r.replace('k', '.') for r in c.rows()]
serpent_fly = [list(r) for r in serpent_fly]
serpent_fly[8][23] = 'k'; serpent_fly[7][30] = 'k'
serpent_fly = [''.join(r) for r in serpent_fly]

# ---------- василиск (композитор) 52×48: шестиногий оливковый ящер, ржавый гребень, светлое брюхо, красный глаз ----------
c = Canvas(52, 48)
c.line(10, 30, 3, 24, 'H', th=4); c.line(3, 24, 4, 14, 'H', th=3); c.line(4, 14, 8, 9, 'H', th=2)   # хвост вверх
c.ellipse(26, 31, 17, 8.5, 'H')                            # туловище
c.ellipse(26, 35, 13, 4, 'h')                              # брюхо
c.feathers([(12, 24), (38, 23)], 'O', 2.2, (0, -0.5))      # зубчатый ржавый гребень по спине
c.ellipse(43, 26, 7.5, 5.5, 'H')                           # голова
c.ellipse(48, 28, 4.5, 3, 'h')                             # светлая челюсть
c.poly([(46, 27), (52, 26), (52, 29), (46, 29)], 'G')      # пасть
c.ellipse(44, 24, 2, 1.8, 'r')                             # глаз
for k, x0 in enumerate((10, 18, 26, 34)):                  # дальние лапы (тёмные)
    c.poly([(x0, 36), (x0 - 2, 46), (x0 + 3, 46), (x0 + 5, 36)], 'G')
    c.ellipse(x0 + 1, 46, 3.5, 1.5, 'G')
for x0 in (14, 22, 30):                                    # ближние лапы (светлее)
    c.poly([(x0, 37), (x0 - 1, 46), (x0 + 5, 46), (x0 + 5, 37)], 'H')
    for dx in (-2, 1, 4): c.poly([(x0 + dx, 46), (x0 + dx, 48), (x0 + dx + 2, 48), (x0 + dx + 2, 46)], 'i')   # когти
c.outline(between=set())
basilisk = [r.replace('k', '.') for r in c.rows()]
basilisk = [list(r) for r in basilisk]; basilisk[24][44] = 'k'; basilisk = [''.join(r) for r in basilisk]

# ---------- горгона (композитор) 60×56: бронзовый бык в чешуе, горб, рога, тёмные ноги с копытами ----------
c = Canvas(60, 56)
c.line(9, 30, 3, 42, 'N', th=2); c.ellipse(3, 44, 2.5, 3, 'N')          # хвост с кистью
c.ellipse(27, 33, 20, 11, 'Y')                                          # туловище
c.ellipse(20, 25, 11, 6, 'Y')                                           # горб
for y in range(26, 42, 4):                                              # чешуя — шахматка светлых пластинок
    for x in range(10 + (y // 4 % 2) * 2, 46, 4):
        if c.get(x, y) == 'Y' and c.get(x + 1, y + 1) == 'Y': c.put(x, y, 'y'); c.put(x + 1, y, 'y'); c.put(x, y + 1, 'y'); c.put(x + 1, y + 1, 'y')
c.ellipse(47, 30, 9, 7, 'Y')                                            # голова, опущена
c.ellipse(54, 36, 5, 4.5, 'N')                                          # тёмная морда
c.put(56, 36, 'k'); c.put(56, 37, 'k')                                  # ноздря
c.poly([(44, 25), (40, 14), (45, 16), (48, 24)], 'i'); c.poly([(50, 24), (54, 13), (57, 16), (54, 25)], 'i')   # рога
c.ellipse(49, 28, 2, 1.8, 'r')                                          # глаз
for x0, mat in ((12, 'N'), (20, 'N'), (36, 'N'), (44, 'N')):            # ноги
    c.poly([(x0, 40), (x0 - 1, 53), (x0 + 5, 53), (x0 + 6, 40)], mat)
    c.poly([(x0 - 2, 53), (x0 + 6, 53), (x0 + 6, 56), (x0 - 2, 56)], 'D')
c.outline(between=set())
gorgon = [r.replace('k', '.') for r in c.rows()]
gorgon = [list(r) for r in gorgon]; gorgon[36][56] = 'k'; gorgon[37][56] = 'k'; gorgon[28][49] = 'k'; gorgon = [''.join(r) for r in gorgon]

# ---------- виверна (композитор) 60×60: двуногий дракон, тёмные перепончатые крылья, хвост с жалом, открытая пасть ----------
c = Canvas(60, 60)
c.poly([(28, 30), (2, 6), (12, 2), (24, 4), (30, 22)], 'N')             # левое крыло
c.poly([(34, 30), (38, 4), (50, 2), (58, 8), (40, 26)], 'N')            # правое крыло
for x1, y1 in ((2, 6), (12, 2), (24, 4)): c.line(28, 30, x1, y1, 'n', th=1)   # спицы
for x1, y1 in ((38, 4), (50, 2), (58, 8)): c.line(34, 30, x1, y1, 'n', th=1)
c.line(18, 38, 8, 46, 'H', th=4); c.line(8, 46, 4, 38, 'H', th=3)       # хвост влево и вверх
c.poly([(2, 38), (0, 30), (7, 33), (7, 38)], 'i')                       # жало — косой шип назад
c.ellipse(30, 37, 12, 7, 'H')                                           # туловище
c.ellipse(30, 40, 9, 3.5, 'h')                                          # брюхо
c.line(38, 32, 47, 20, 'H', th=5)                                       # шея
c.ellipse(49, 17, 7, 5.5, 'H')                                          # голова
c.poly([(50, 18), (58, 15), (58, 21), (50, 21)], 'R')                   # раскрытая пасть
c.poly([(50, 21), (59, 22), (56, 25)], 'h')                             # нижняя челюсть
c.poly([(44, 14), (42, 6), (47, 12)], 'O'); c.poly([(49, 13), (50, 5), (53, 12)], 'O')   # рога
c.ellipse(47, 15, 2, 1.8, 'r')                                          # глаз
for x0 in (22, 36):                                                     # две лапы
    c.poly([(x0, 42), (x0 - 2, 57), (x0 + 4, 57), (x0 + 5, 42)], 'G')
    c.ellipse(x0 + 1, 57, 5, 2, 'G')
    for dx in (-3, 0, 3): c.poly([(x0 + dx, 57), (x0 + dx + 1, 60), (x0 + dx + 2, 57)], 'i')
c.outline(between=set())
wyvern = [r.replace('k', '.') for r in c.rows()]
wyvern = [list(r) for r in wyvern]; wyvern[15][47] = 'k'; wyvern = [''.join(r) for r in wyvern]

# ---------- гидра (композитор) 64×60: бурое тело, пять голов на длинных шеях веером, светлое брюхо, тёмные лапы ----------
c = Canvas(64, 60)
c.line(12, 46, 2, 52, 'd', th=3)                                        # хвост
heads = ((6, 16), (18, 8), (32, 4), (46, 8), (58, 16))
for k, (hx, hy) in enumerate(heads):                                    # шеи веером, через одну светлые
    mat = 'T' if k % 2 else 'd'
    c.line(32 - (2 - k) * 4, 40, hx, hy + 4, mat, th=5)
c.ellipse(32, 45, 20, 8, 'd')                                           # туловище поверх оснований шей
for k, (hx, hy) in enumerate(heads):                                    # головы
    side = -1 if hx < 32 else 1
    c.ellipse(hx, hy, 5.5, 4.5, 'd')
    c.ellipse(hx + side * 3, hy + 2, 4, 2.5, 'T')                       # челюсть
    c.line(hx + side * 1, hy + 2, hx + side * 6, hy + 2, 'N', th=1)     # линия пасти
    c.ellipse(hx - side * 1, hy - 1, 1.8, 1.6, 'y')                     # глаз
c.ellipse(32, 48, 15, 4, 'T')                                           # брюхо
for x0 in (14, 24, 36, 46):                                             # лапы
    c.poly([(x0, 50), (x0 - 2, 58), (x0 + 4, 58), (x0 + 5, 50)], 'D')
    c.ellipse(x0 + 1, 58, 5, 1.8, 'D')
    for dx in (-3, 0, 3): c.poly([(x0 + dx, 58), (x0 + dx + 1, 60), (x0 + dx + 2, 58)], 'i')
c.outline(between=set())
hydra = [r.replace('k', '.') for r in c.rows()]
hydra = [list(r) for r in hydra]
for hx, hy in heads:
    side = -1 if hx < 32 else 1
    hydra[hy - 1][hx - side * 1] = 'k'
hydra = [''.join(r) for r in hydra]

out = "/* ============================================================================\n"
out += "   view/sprites_fortress_hd.js — существа Крепости в крупной сетке (unit 2), стиль Б:\n"
out += "   без контурной линии, тона кладёт рисунок. Собирается скриптом dev/proto/fortress_hd.py.\n"
out += "   ========================================================================== */\n(function () {\n  'use strict';\n  H3.Sprites.defineMany({\n"
out += block('gnoll', gnoll, 'гнолл: гиеноголовый, тёмные уши и грива, светлая морда с клыками, кожаный жилет, алебарда')
out += block('gnoll_marauder', None, 'гнолл-мародёр: жилет в тёмно-красный, повязка чёрная, красный гребень на гриве', base='gnoll', tint={'N': 'R', 'T': 'z'},
             extra=[(x, y, 'r') for y, (a, b) in ((0, (14, 17)), (1, (13, 18)), (2, (13, 18)), (3, (12, 19)), (4, (12, 19))) for x in range(a, b)])
out += block('lizardman', lizardman, 'ящер: зелёный, тёмный гребень, светлое брюхо и челюсть, повязка, лук со стрелами, хвост')
out += block('lizard_warrior', None, 'ящер-воин: бирюзовая чешуя, повязка в тёмно-красный, стальные наплечники', base='lizardman', tint={'g': 'C', 'G': 'Q', 'h': 'v', 'd': 'R'},
             extra=[(x, y, 'l') for y in (17, 18, 19) for x in list(range(4, 10)) + list(range(22, 28))])
out += block('serpent_fly', serpent_fly, 'змеемуха: змеиное тело с тёмной спиной, четыре голубых крыла с прожилками, большие глаза (композитор)')
out += block('dragon_fly', None, 'стрекоза: крылья в алый, тело оливковое, глаза огненные', base='serpent_fly', tint={'c': 'r', 'C': 'R', 'g': 'H', 'h': 't', 'y': 'f'})
out += block('basilisk', basilisk, 'василиск: шестиногий оливковый ящер, ржавый гребень, светлое брюхо, красный глаз (композитор)')
out += block('greater_basilisk', None, 'великий василиск: чешуя в бирюзу, гребень оранжевый, глаз огненный', base='basilisk', tint={'H': 'q', 'G': 'Q', 'h': 'v', 'j': 'Q', 'O': 'o', 'r': 'f'})
out += block('gorgon', gorgon, 'горгона: бронзовый бык в чешуе, горб, костяные рога, тёмные ноги с копытами (композитор)')
out += block('mighty_gorgon', None, 'могучая горгона: чешуя чёрно-бирюзовая, ноги в чёрно-синий, копыта стальные, рога светлые, глаз горит', base='gorgon', tint={'Y': 'Q', 'y': 'q', 'N': 'z', 'D': 'e', 'i': 'l', 'r': 'h'})
out += block('wyvern', wyvern, 'виверна: двуногий дракон, тёмные перепончатые крылья, хвост с жалом, раскрытая пасть (композитор)')
out += block('wyvern_monarch', None, 'монарх виверн: крылья пурпурные со светлыми спицами, тело ярко-зелёное, золотая корона', base='wyvern', tint={'N': 'P', 'n': 'A', 'H': 'g', 'h': 'y'},
             extra=[(x, y, 'y') for y in (10, 11) for x in range(45, 53)] + [(x, 9, 'y') for x in (45, 46, 48, 49, 51, 52)])
out += block('hydra', hydra, 'гидра: бурое тело, пять голов на длинных шеях веером, светлое брюхо, тёмные лапы (композитор)')
out += block('chaos_hydra', None, 'гидра хаоса: синяя чешуя, светло-синие шеи и брюхо, чёрные лапы, красные глаза', base='hydra', tint={'d': 'B', 'T': 'b', 'D': 'z', 'N': 'R', 'y': 'r'})
out += "  });\n})();\n"
p = os.path.join(os.path.dirname(__file__), '..', '..', 'js', 'view', 'sprites_fortress_hd.js')
io.open(p, 'w', encoding='utf-8').write(out)
print('записан', os.path.relpath(p))
