# -*- coding: utf-8 -*-
"""Сборка js/view/sprites_inferno_hd.js: 14 существ Инферно в крупной сетке (unit 2), стиль Б.
Бес, гог, демон, порождение ада, ифрит, дьявол — строками (крылья/хвост/оружие дорисованы композитором
под строки); адская гончая и цербер — целиком композитором."""
import io, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from compose import Canvas
from castle_hd import rows_from, pad, block, stretch   # общие помощники (castle_hd при импорте пересобирает свой файл — это безвредно)


def under(rows, cv):
    """Кладёт строки поверх холста: где в строках прозрачно — берём пиксель холста (крылья/хвост за телом)."""
    cvr = cv.rows(); W = cv.w
    rows = pad(rows, W) + ['.' * W] * (cv.h - len(rows))
    return [''.join(a if a != '.' else b for a, b in zip(r, c)) for r, c in zip(rows[:cv.h], cvr)]


def pupils(rows, pts):
    rows = [list(r) for r in rows]
    for x, y in pts: rows[y][x] = 'k'
    return [''.join(r) for r in rows]


def nok(c):
    """Композитор без контура: убираем 'k', которым compose обводит силуэт."""
    c.outline(between=set())
    return [r.replace('k', '.') for r in c.rows()]


# ---------- бес 40×46: маленький красный чертёнок, рожки, острые уши, светлое брюшко, кожаные крылья, хвост ----------
imp = rows_from("""
.............ii.........ii..............
............iii.........iii.............
............iii.........iii.............
............iiirrrrrrrrriii.............
.............rrrrrrrrrrrrr..............
...........rrrrrrrrrrrrrrrrr............
.........rrrrrrrrrrrrrrrrrrrrr..........
........rrrrrrryyyrrrryyyrrrrrr.........
.......rrrrrrryykrrrrkyyrrrrrrr.........
........rrrrrrryyyrrrryyyrrrrrr.........
.........rrrrrrrrrrrrrrrrrrrrr..........
..........rrrrrRRRRRRRRRrrrr............
...........rrrrRwRwRwRwRrrr.............
............rrrRRRRRRRRRrr..............
..............rrrrrrrrrr................
................rrrrrr..................
..........rr..rrrrrrrrrr..rr............
.........rrr.rrrrooooorrr.rrr...........
.........rrr.rrrooooooorrr.rrr..........
.........rrr.rrrooooooorrr.rrr..........
.........rrr.rrrooooooorrr.rrr..........
.........rrr.rrrooooooorrr.rrr..........
.........rrr.rrrrooooorrrr.rrr..........
.........rrr.rrrrrrrrrrrrr.rrr..........
.........iii.rrDDDDDDDDDDr.iii..........
.........iii.rrDDDDDDDDDDr.iii..........
...............DDDDDDDDDD...............
...............DDDDDDDDDD...............
...............rrrr..rrrr...............
...............rrrr..rrrr...............
...............rrrr..rrrr...............
...............rrrr..rrrr...............
...............rrrr..rrrr...............
..............rrrr....rrrr..............
..............DDDD....DDDD..............
..............DDDD....DDDD..............
""")
c = Canvas(40, len(imp))
c.poly([(14, 17), (2, 5), (1, 11), (4, 14), (2, 21), (7, 20), (5, 26), (13, 24)], 'R')      # левое крыло
c.poly([(26, 17), (38, 5), (39, 11), (36, 14), (38, 21), (33, 20), (35, 26), (27, 24)], 'R')   # правое крыло
c.line(25, 27, 31, 26, 'r', th=2); c.line(31, 26, 34, 20, 'r', th=2)                       # хвост
c.poly([(31, 20), (34, 15), (37, 20)], 'R')                                                  # наконечник хвоста
imp = under(imp, c)
imp = stretch(imp, 46, [(16, 26), (28, 34)])

# ---------- гог 44×46: ржаво-коричневый бес, светлое лицо, рожки, огненный шар в поднятой руке ----------
gog = rows_from("""
..........iii.........iii...................
..........iii.........iii...................
..........iiiooooooooiii....................
...........ioooooooooooi....................
..........oooooooooooooo....................
.........oooooooooooooooo...................
.........ooooyyyoooyyyooo...................
.........ooooykyoooykyooo...................
.........ooooyyyoooyyyooo...................
.........oooooooooooooooo...................
..........ooooRRRRRRRoooo...................
..........oooRwRwRwRwRooo...................
...........oooRRRRRRRooo....................
............oooooooooooo....................
..............OOOOOO........................
..........OOOOOOOOOOOOOOOO..................
.........OOOOOOOOOOOOOOOOOO.................
........OOO.OOOOOOOOOOOO.OOO................
........OOO.OOOOOOOOOOOO.OOO................
........OOO.OOOOOOOOOOOO.OOO................
........OOO.OOOOOOOOOOOO....................
........OOO.OOOOOOOOOOOO....................
........OOO.OOOOOOOOOOOO....................
........OOO.OOOOOOOOOOOO....................
........iii.OOOOOOOOOOOO....................
........iii.DDDDDDDDDDDD....................
............DDDDDDDDDDDD....................
............DDDDDDDDDDDD....................
............OOOO....OOOO....................
............OOOO....OOOO....................
............OOOO....OOOO....................
............OOOO....OOOO....................
............OOOO....OOOO....................
...........OOOO......OOOO...................
...........DDDD......DDDD...................
...........DDDD......DDDD...................
""")
c = Canvas(44, len(gog))
c.line(25, 18, 32, 11, 'O', th=3)                          # поднятая правая рука
c.ellipse(33, 10, 3, 3, 'O')                               # кулак
c.ellipse(36, 5, 5, 5, 'F'); c.ellipse(36, 5, 3.5, 3.5, 'f')   # огненный шар
for x, y in ((35, 4), (36, 4), (35, 5), (36, 5)): c.put(x, y, 'w')
gog = under(gog, c)
gog = stretch(gog, 46, [(15, 26), (28, 34)])
magog_ball = [(x, y, 'F') for y in range(0, 13) for x in range(28, 44)
              if 26 < (x - 36) ** 2 + (y - 5) ** 2 <= 52 and not (y >= 9 and x < 36)]
magog_ball += [(x, y, 'w') for y in (3, 4, 5, 6) for x in (34, 35, 36, 37)]

# ---------- адская гончая (композитор) 52×48: чёрно-графитовый пёс, огненная грива и хвост, светящаяся пасть ----------
c = Canvas(52, 48)
c.feathers([(10, 22), (30, 17), (40, 15)], 'f', 2.6, (0, -0.8), tip_c='F')   # огненная грива вдоль хребта
c.line(9, 26, 3, 16, 'u', th=2)                                             # хвост
c.ellipse(3, 13, 2.8, 3.6, 'f'); c.ellipse(3, 10, 1.8, 2.4, 'F')              # огонь на хвосте
c.ellipse(24, 30, 17, 8, 'u')                                               # туловище
c.ellipse(36, 28, 9, 8, 'u')                                                # грудь
c.ellipse(24, 34, 12, 3.5, 'z')                                             # брюхо
c.poly([(34, 10), (37, 19), (41, 15)], 'u'); c.poly([(41, 10), (42, 18), (46, 14)], 'u')   # уши торчком
c.ellipse(40, 19, 7, 6.5, 'u'); c.ellipse(46, 21, 6, 3.5, 'u')               # голова и верхняя челюсть
c.poly([(42, 24), (52, 23), (51, 29), (42, 27)], 'F')                       # раскрытая пасть светится
c.poly([(42, 27), (51, 29), (48, 31), (41, 29)], 'u')                       # нижняя челюсть
for x in range(44, 51, 3): c.put(x, 24, 'w'); c.put(x + 1, 28, 'w')          # клыки
c.poly([(38, 17), (43, 17), (43, 20), (38, 20)], 'y')                       # глаз
for x0, mat in ((13, 'z'), (19, 'u'), (33, 'z'), (39, 'u')):                # лапы: ближние графит, дальние чёрные
    dx = 3 if mat == 'u' else -3
    c.poly([(x0, 36), (x0 + dx, 47), (x0 + dx + 5, 47), (x0 + 5, 36)], mat)
    c.ellipse(x0 + dx + 2.5, 46.5, 3.5, 1.5, 'z')
hell_hound = pupils(nok(c), [(40, 18), (41, 18), (40, 19), (41, 19)])

# ---------- цербер (композитор) 56×50: трёхголовый пёс, серо-графитовая шерсть, три огненные пасти, шипастый ошейник ----------
c = Canvas(56, 50)
c.feathers([(10, 26), (26, 20), (32, 17)], 'f', 2.6, (0, -0.8), tip_c='F')   # грива
c.line(9, 30, 3, 20, 'E', th=2); c.ellipse(3, 17, 2.8, 3.6, 'f'); c.ellipse(3, 14, 1.8, 2.4, 'F')   # хвост с огнём
c.ellipse(22, 34, 16, 8, 'E')                                               # туловище
c.ellipse(33, 31, 8, 8, 'E')                                                # грудь
c.ellipse(22, 38, 11, 3.5, 'z')                                             # брюхо
c.line(35, 28, 40, 12, 'E', th=5); c.line(37, 29, 44, 22, 'E', th=5); c.line(35, 32, 41, 32, 'E', th=5)   # три шеи
for hx, hy in ((40, 11), (44, 21), (41, 31)):                              # три головы веером
    c.poly([(hx - 5, hy - 8), (hx - 3, hy - 1), (hx, hy - 5)], 'E')          # ухо
    c.ellipse(hx, hy, 6, 5.5, 'E'); c.ellipse(hx + 6, hy + 2, 5, 3.2, 'E')   # голова и верхняя челюсть
    c.poly([(hx + 2, hy + 4), (hx + 12, hy + 3), (hx + 11, hy + 8), (hx + 2, hy + 7)], 'F')   # пасть светится
    c.poly([(hx + 2, hy + 7), (hx + 11, hy + 8), (hx + 8, hy + 10), (hx + 1, hy + 9)], 'E')   # нижняя челюсть
    for x in range(hx + 4, hx + 11, 3): c.put(x, hy + 4, 'w'); c.put(x + 1, hy + 7, 'w')
    c.poly([(hx - 2, hy - 2), (hx + 3, hy - 2), (hx + 3, hy + 1), (hx - 2, hy + 1)], 'y')   # глаз
for x0, mat in ((13, 'z'), (19, 'E'), (31, 'z'), (37, 'E')):
    dx = 3 if mat == 'E' else -3
    c.poly([(x0, 40), (x0 + dx, 49), (x0 + dx + 5, 49), (x0 + 5, 40)], mat)
    c.ellipse(x0 + dx + 2.5, 48.5, 3.5, 1.5, 'z')
cerberus = pupils(nok(c), [(x, y) for hx, hy in ((40, 11), (44, 21), (41, 31)) for x in (hx, hx + 1) for y in (hy - 1, hy)])

# ---------- демон 48×52: мускулистый красный демон, короткие рога, светлая грудь, когти, тёмная повязка ----------
demon = rows_from("""
................................................
................................................
.............III..........III...................
.............III..........III...................
.............IIIrrrrrrrrrrIII...................
..............IrrrrrrrrrrrrI....................
.............rrrrrrrrrrrrrrrr...................
............rrrrrrrrrrrrrrrrrr..................
............rrrryyyrrrrryyyrrr..................
............rrrrykyrrrrrykyrrr..................
............rrrryyyrrrrryyyrrr..................
............rrrrrrrrrrrrrrrrrr..................
.............rrrrRRRRRRRRrrrr...................
.............rrrRwRwRwRwRRrrr...................
..............rrrRRRRRRRRrrr....................
...............rrrrrrrrrrrr.....................
.................rrrrrrrr.......................
..........rrrrrrrrrrrrrrrrrrrrrrrr..............
........rrrrrrrrrrrrrrrrrrrrrrrrrrrr............
.......rrrrr.rrrrrooooooorrrrr.rrrrr............
.......rrrrr.rrrroooooooooorrr.rrrrr............
.......rrrrr.rrrooooRRooooorrr.rrrrr............
.......rrrrr.rrrooooRRooooorrr.rrrrr............
.......rrrrr.rrrroooooooooorrr.rrrrr............
.......rrrrr.rrrrrooooooorrrrr.rrrrr............
.......rrrrr.rrrrrrrrrrrrrrrrr.rrrrr............
.......rrrrr.rrrrroRRRRRorrrrr.rrrrr............
.......rrrrr.rrrrrroRRRorrrrrr.rrrrr............
.......iiiii.rrrrrrrrrrrrrrrrr.iiiii............
.......iiiii.rDDDDDDDDDDDDDDDr.iiiii............
.............rDDDDDDDDDDDDDDDr..................
..............DDDDDDDDDDDDDDD...................
..............DDDDDDDDDDDDDDD...................
..............rrrrrr...rrrrrr...................
..............rrrrrr...rrrrrr...................
..............rrrrrr...rrrrrr...................
..............rrrrrr...rrrrrr...................
..............rrrrrr...rrrrrr...................
..............rrrrrr...rrrrrr...................
.............rrrrrr.....rrrrrr..................
.............DDDDDD.....DDDDDD..................
.............DDDDDD.....DDDDDD..................
""")
demon = stretch(demon, 52, [(17, 30), (33, 39)])
horns = []
for y, (a, b) in enumerate(((8, 11), (8, 12), (9, 13), (10, 14), (11, 15), (12, 16))):     # большие костяные рога
    horns += [(x, y, 'i') for x in range(a, b)] + [(42 - x, y, 'i') for x in range(a, b)]

# ---------- порождение ада 56×58: крупный красный демон, рога, стальные оплечья и наручи, кожаные крылья, кнут ----------
pit_fiend = rows_from("""
..............III..............III......................
...............III............III.......................
................III..........III........................
.................III........III.........................
.................IIIrrrrrrrrIII.........................
..................IrrrrrrrrrrI..........................
.................rrrrrrrrrrrrrr.........................
................rrrrrrrrrrrrrrrr........................
...............rrrrrrrrrrrrrrrrrr.......................
...............rrrryyyrrrrryyyrrr.......................
...............rrrrykyrrrrrykyrrr.......................
...............rrrryyyrrrrryyyrrr.......................
...............rrrrrrrrrrrrrrrrrr.......................
................rrrrRRRRRRRRRrrr........................
................rrrRwRwRwRwRwRrr........................
.................rrrRRRRRRRRRrr.........................
..................rrrrrrrrrrrr..........................
....................rrrrrrrr............................
..........llllllllllllllllllllllllllllllll..............
........llllllrrrrrrrrrrrrrrrrrrrrrrllllll..............
.......rrrrrrr.rrrrrrooooooorrrrrr.rrrrrrr..............
.......rrrrrrr.rrrrroooooooooorrrr.rrrrrrr..............
.......rrrrrrr.rrrroooooRRooooorrr.rrrrrrr..............
.......rrrrrrr.rrrroooooRRooooorrr.rrrrrrr..............
.......rrrrrrr.rrrroooooooooooorrr.rrrrrrr..............
.......rrrrrrr.rrrrrooooooooorrrrr.rrrrrrr..............
.......lllllll.rrrrrrrrrrrrrrrrrrr.lllllll..............
.......lllllll.rrrrrrroRRRRorrrrrr.lllllll..............
.......lllllll.rrrrrrrroRRRorrrrrr.lllllll..............
.......rrrrrrr.rrrrrrrrrrrrrrrrrrr.rrrrrrr..............
.......rrrrrrr.rrrrrrrrrrrrrrrrrrr.rrrrrrr..............
.......iiiiiii.lllllllllllllllllll.rrrrrrr..............
.......iiiiiii.DDDDDDDDDDDDDDDDDDD.rrrrrrr..............
...............DDDDDDDDDDDDDDDDDDD......................
...............DDDDDDDDDDDDDDDDDDD......................
...............DDDDDDDDDDDDDDDDDDD......................
...............rrrrrrr.....rrrrrrr......................
...............rrrrrrr.....rrrrrrr......................
...............rrrrrrr.....rrrrrrr......................
...............rrrrrrr.....rrrrrrr......................
...............rrrrrrr.....rrrrrrr......................
...............rrrrrrr.....rrrrrrr......................
..............rrrrrrr.......rrrrrrr.....................
..............DDDDDDD.......DDDDDDD.....................
..............DDDDDDD.......DDDDDDD.....................
""")
c = Canvas(56, len(pit_fiend))
c.poly([(16, 21), (3, 4), (0, 16), (3, 27), (8, 25), (5, 35), (12, 33), (15, 36)], 'D')       # левое крыло
c.poly([(32, 21), (45, 4), (48, 16), (45, 27), (40, 25), (43, 35), (36, 33), (33, 36)], 'D')   # правое крыло
for x1, y1 in ((3, 4), (3, 27), (5, 35)): c.line(16, 21, x1, y1, 'N', th=1)                  # кости крыльев
for x1, y1 in ((45, 4), (45, 27), (43, 35)): c.line(32, 21, x1, y1, 'N', th=1)
c.poly([(42, 29), (46, 29), (46, 33), (42, 33)], 'Y')                                        # рукоять кнута
c.line(46, 31, 53, 36, 'n', th=3); c.line(53, 36, 54, 42, 'n', th=3)                          # кнут
c.line(54, 42, 48, 44, 'n', th=3)
pit_fiend = under(pit_fiend, c)
pit_fiend = stretch(pit_fiend, 58, [(20, 31), (36, 42)])
hand_y = max(y for y, r in enumerate(pit_fiend) if 'Y' in r)                                 # где кулак (после stretch)
trident = [(x, y, 'y') for y in range(6, hand_y + 4) for x in (41, 42)]                      # древко трезубца
trident += [(x, y, 'y') for y in range(0, 6) for x in (41, 42)] + [(x, y, 'y') for y in range(2, 8) for x in (37, 38, 45, 46)]
trident += [(x, 7, 'y') for x in range(37, 47)] + [(x, 8, 'y') for x in range(37, 47)]

# ---------- ифрит 56×58: красный дух огня, пламя вместо волос и ног, золотые браслеты и пояс, ятаган ----------
efreet = rows_from("""
......................FF....FF..........................
.....................FFF...FFF....FF....................
....................FFff...ffFF..FFF....................
...................FFfff.ffffFFFFFF.....................
...................FffffffffffffFF......................
..................FFfffffffffffffF......................
..................Ffffffffffffffff......................
..................ffffffffffffffff......................
..................fffrrrrrrrrrrfff......................
..................ffrrrrrrrrrrrrff......................
..................frrrrrrrrrrrrrrf......................
..................rrrrrrrrrrrrrrrr......................
..................rrryyyrrrrryyyrr......................
..................rrrykyrrrrrykyrr......................
..................rrryyyrrrrryyyrr......................
..................rrrrrrrrrrrrrrrr......................
...................rrrrRRRRRRRrrr.......................
...................rrrRwRwRwRwRrr.......................
....................rrrRRRRRRRrr........................
.....................rrrrrrrrrr.........................
.......................rrrrrr...........................
..............rrrrrrrrrrrrrrrrrrrrrrrr..................
............rrrrrrrrrrrrrrrrrrrrrrrrrrrr................
...........rrrrrr.rrrrrooooooorrrrr.....................
...........rrrrrr.rrrroooooooooorrr.....................
...........rrrrrr.rrroooooRRoooorrr.....................
...........rrrrrr.rrroooooRRoooorrr.....................
...........rrrrrr.rrrroooooooooorrr.....................
...........yyyyyy.rrrrrooooooorrrrr.....................
...........yyyyyy.rrrrrrrrrrrrrrrrr.....................
...........rrrrrr.rrrrrrroRRRorrrrr.....................
...........rrrrrr.rrrrrrrrrrrrrrrrr.....................
...........rrrrrr.yyyyyyyyyyyyyyyyy.....................
...........rrrrrr.yyYyYyYyYyYyYyYyy.....................
..................yyyyyyyyyyyyyyyyy.....................
""")
c = Canvas(56, 58)
c.line(38, 24, 44, 14, 'r', th=4); c.ellipse(45, 13, 3, 3, 'r')                              # поднятая рука с кулаком
c.poly([(43, 8), (44, 4), (47, 1), (51, 0), (55, 1), (51, 2), (48, 4), (46, 8), (46, 11)], 'l')   # изогнутый клинок
c.line(44, 8, 50, 2, 'e', th=1)                                                              # тёмная грань
c.poly([(42, 15), (48, 15), (48, 17), (42, 17)], 'y')                                        # золотая гарда
c.poly([(18, 35), (34, 35), (33, 44), (31, 52), (28, 57), (24, 57), (21, 52), (19, 44)], 'f')      # столб пламени
c.poly([(15, 36), (19, 34), (20, 44), (16, 47), (17, 41)], 'F')                              # языки по краям
c.poly([(37, 36), (33, 34), (32, 44), (36, 47), (35, 41)], 'F')
c.poly([(19, 46), (22, 46), (23, 52), (20, 54), (16, 52)], 'F')
c.poly([(30, 46), (33, 46), (36, 52), (32, 54), (29, 52)], 'F')
c.poly([(23, 52), (29, 52), (31, 57), (28, 58), (26, 55), (24, 58), (21, 57)], 'F')
c.ellipse(26, 41, 2.5, 3.5, 'w')                                                                 # белое ядро огня
efreet = under(efreet, c)
crown = [(x, y, 'Y') for y in (7, 8) for x in range(19, 33)] + [(x, y, 'Y') for y in (5, 6) for x in (19, 20, 25, 26, 31, 32)]

# ---------- дьявол 64×60: высокий красный рогатый, широкие кожаные крылья, золотой трезубец, хвост, копыта ----------
devil = rows_from("""
....................iii..................iii....................
....................iiii................iiii....................
.....................iiii..............iiii.....................
......................iiii............iiii......................
.......................iiiirrrrrrrrrriiii.......................
........................iiirrrrrrrrrriii........................
.........................rrrrrrrrrrrrrr.........................
........................rrrrrrrrrrrrrrrr........................
.......................rrrrrrrrrrrrrrrrrr.......................
.......................rrrryyyrrrrrryyyrr.......................
.......................rrrrykyrrrrrrykyrr.......................
.......................rrrryyyrrrrrryyyrr.......................
.......................rrrrrrrrrrrrrrrrrr.......................
........................rrrRRRRRRRRRRrrr........................
........................rrRwRwRwRwRwRrrr........................
.........................rrRRRRRRRRRRrr.........................
..........................rrrrrrrrrrrr..........................
............................rrrrrrrr............................
.......................rrrrrrrrrrrrrrrrrr.......................
....................rrrrrrrrrrrrrrrrrrrrrrrr....................
..................rrrrrr.rrrrrrrrrrrrrr.rrrrrr..................
..................rrrrrr.rrrrrooooorrrr.rrrrrr..................
..................rrrrrr.rrrroooooooorr.rrrrrr..................
..................rrrrrr.rrrooooRRoooor.rrrrrr..................
..................rrrrrr.rrrooooRRoooor.rrrrrr..................
..................rrrrrr.rrrroooooooorr.rrrrrr..................
..................rrrrrr.rrrrrooooorrrr.rrrrrr..................
..................rrrrrr.rrrrrrrrrrrrrr.rrrrrr..................
..................rrrrrr.rrrrroRRRRorrr.rrrrrr..................
..................rrrrrr.rrrrrroRRRorrr.rrrrrr..................
..................rrrrrr.rrrrrrrrrrrrrr.rrrrrrrrr...............
..................rrrrrr.rrrrrrrrrrrrrr.rrrrrrrrr...............
..................iiiiii.rrrrrrrrrrrrrr.rrrrrrrrr...............
..................iiiiii.DDDDDDDDDDDDDD.rrrrrrrrr...............
.........................DDDDDDDDDDDDDD.........................
.........................DDDDDDDDDDDDDD.........................
.........................DDDDDDDDDDDDDD.........................
.........................rrrrrr..rrrrrr.........................
.........................rrrrrr..rrrrrr.........................
.........................rrrrrr..rrrrrr.........................
.........................rrrrrr..rrrrrr.........................
.........................rrrrrr..rrrrrr.........................
.........................rrrrrr..rrrrrr.........................
.........................rrrrrr..rrrrrr.........................
.........................rrrrrr..rrrrrr.........................
.........................rrrrrr..rrrrrr.........................
........................rrrrrr....rrrrrr........................
........................DDDDDD....DDDDDD........................
........................DDDDDD....DDDDDD........................
""")
c = Canvas(64, len(devil))
c.poly([(24, 21), (3, 2), (0, 15), (3, 26), (9, 24), (6, 36), (13, 33), (12, 40), (23, 35)], 'D')      # левое крыло
c.poly([(39, 21), (60, 2), (63, 15), (60, 26), (54, 24), (57, 36), (50, 33), (51, 40), (40, 35)], 'D')   # правое крыло
for x1, y1 in ((3, 2), (3, 26), (6, 36)): c.line(24, 21, x1, y1, 'N', th=1)                          # кости крыльев
for x1, y1 in ((60, 2), (60, 26), (57, 36)): c.line(39, 21, x1, y1, 'N', th=1)
c.line(47, 44, 47, 8, 'y', th=2)                                                                     # древко трезубца
c.poly([(43, 0), (45, 0), (45, 6), (49, 6), (49, 0), (51, 0), (51, 8), (43, 8)], 'y')               # боковые зубцы
c.poly([(46, 0), (48, 0), (48, 8), (46, 8)], 'y')                                                    # средний зубец
c.line(24, 38, 16, 44, 'r', th=2); c.line(16, 44, 12, 38, 'r', th=2)                                  # хвост
c.poly([(9, 39), (12, 33), (15, 39)], 'R')                                                           # наконечник хвоста
devil = under(devil, c)
devil = stretch(devil, 60, [(20, 33), (37, 45)])
aura = []
for cx in (16, 46):
    aura += [(x, y, 'F') for y in range(52, 60) for x in range(cx - 5, cx + 6) if ((x - cx) / 4.5) ** 2 + ((y - 57) / 5.5) ** 2 <= 1]
    aura += [(x, y, 'f') for y in range(55, 60) for x in range(cx - 2, cx + 3) if ((x - cx) / 2.2) ** 2 + ((y - 58) / 3.2) ** 2 <= 1]

out = "/* ============================================================================\n"
out += "   view/sprites_inferno_hd.js — существа Инферно в крупной сетке (unit 2), стиль Б:\n"
out += "   без контурной линии, тона кладёт рисунок. Собирается скриптом dev/proto/inferno_hd.py.\n"
out += "   ========================================================================== */\n(function () {\n  'use strict';\n  H3.Sprites.defineMany({\n"
out += block('imp', imp, 'бес: маленький красный чертёнок, рожки, светлое брюшко, кожаные крылья, хвост')
out += block('familiar', None, 'фамильяр: фиолетовый бес, сиреневое брюшко, золотой трезубец', base='imp', tint={'r': 'p', 'R': 'P', 'o': 'A'},
             extra=[(x, y, 'y') for y in range(0, 31) for x in (30, 31)] + [(x, y, 'y') for y in range(0, 5) for x in (27, 28, 33, 34)] + [(x, y, 'y') for y in (4, 5) for x in range(27, 35)])
out += block('gog', gog, 'гог: ржаво-коричневый бес, светлое лицо, рожки, огненный шар в поднятой руке')
out += block('magog', None, 'магог: золотые рога, шар больше и ярче с белым ядром', base='gog', tint={'i': 'y'}, extra=magog_ball)
out += block('hell_hound', hell_hound, 'адская гончая: графитовый пёс, огненная грива и хвост, светящаяся пасть (композитор)')
out += block('cerberus', cerberus, 'цербер: три головы, серая шерсть, три огненные пасти, шипастый ошейник (композитор)')
out += block('demon', demon, 'демон: мускулистый красный, короткие рога, светлая грудь, когти, тёмная повязка')
out += block('horned_demon', None, 'рогатый демон: большие костяные рога, кожа темнее, глаза горят', base='demon', tint={'o': 'r', 'R': 'D', 'I': 'i', 'y': 'f'}, extra=horns)
out += block('pit_fiend', pit_fiend, 'порождение ада: крупный красный демон, рога, стальные оплечья и наручи, кожаные крылья, кнут')
out += block('pit_lord', None, 'владыка бездны: сталь в золото, вместо кнута золотой трезубец', base='pit_fiend', tint={'l': 'y', 'n': '.', 'Y': '.'}, extra=trident)
out += block('efreet', efreet, 'ифрит: красный дух огня, пламя вместо волос и ног, золотые браслеты и пояс, ятаган')
out += block('efreet_sultan', None, 'султан ифритов: синее пламя, золотая корона', base='efreet', tint={'F': 'b', 'f': 'c'}, extra=crown)
out += block('devil', devil, 'дьявол: высокий красный рогатый, широкие кожаные крылья, золотой трезубец, хвост, копыта')
out += block('arch_devil', None, 'архидьявол: пурпурно-чёрный с золотом, огненная аура у копыт', base='devil', tint={'r': 'x', 'R': 'z', 'o': 'p', 'D': 'z', 'N': 'E', 'y': 'y'}, extra=aura)
out += "  });\n})();\n"
p = os.path.join(os.path.dirname(__file__), '..', '..', 'js', 'view', 'sprites_inferno_hd.js')
io.open(p, 'w', encoding='utf-8').write(out)
print('записан', os.path.relpath(p))
