# -*- coding: utf-8 -*-
"""Сборка js/view/sprites_necropolis_hd.js: 14 существ Некрополиса в крупной сетке (unit 2), стиль Б.
Скелет, мертвец, вампир, лич — строками; привидение, чёрный рыцарь, костяной дракон — композитором."""
import io, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from compose import Canvas
from castle_hd import rows_from, pad, block, stretch   # общие помощники (castle_hd при импорте пересобирает свой файл — это безвредно)

# ---------- скелет 40×48: череп с глазницами, рёбра, ржавый меч, круглый щит ----------
skeleton = rows_from("""
..............iiiiiiiii.................
............iiiiiiiiiiiii...............
...........iiiiiiiiiiiiiii..............
...........iiIIIIIIIIIIIii..............
...........iiIzzzIIIzzzIii..............
...........iiIzzzIIIzzzIii..............
...........iiIIIIIIIIIIIii..............
............iIIIIzzIIIIIi...............
............iiIIIIIIIIIii...............
.............IiIiIiIiIiI................
..............IIIIIIIII.................
................III.....................
.........iii....III....iii..............
........iIIi..iiIIIii..iIIi.............
........iIIi.iiiiiiiii.iIIi.............
........iIIi.iIzzzzzIi.iIIi.............
........iIIi.iiiiiiiii.iIIi.............
........iIIi.iIzzzzzIi.iIIi.............
........iIIi.iiiiiiiii.iIIi.............
........iIIi.iIzzzzzIi.iIIi.............
........iIIi.iiiiiiiii.iIIi.............
........iIIi..iIzzzIi..iIIi.............
........iIIi...iiiii...iIIi.............
........iIIi....III....iIIi.............
.........ii...iiIIIii...ii..............
..............iIIIIIi...................
..............iiiiiii...................
..............III.III...................
..............III.III...................
..............iIi.iIi...................
..............iIi.iIi...................
..............iIi.iIi...................
..............III.III...................
..............III.III...................
..............iIi.iIi...................
..............iIi.iIi...................
.............iiii.iiii..................
.............IIII.IIII..................
""")
skeleton = [list(r) for r in skeleton]
for y in range(4, 24): skeleton[y][31] = 'O'; skeleton[y][32] = 'N'; skeleton[y][33] = 'O'   # ржавый клинок
skeleton[3][32] = 'O'; skeleton[2][32] = 'O'
for x in range(28, 37): skeleton[24][x] = 'D'
for y in range(25, 30): skeleton[y][31] = 'N'; skeleton[y][32] = 'N'; skeleton[y][33] = 'N'
for y in range(13, 24):                                            # круглый щит слева
    half = 4 if 15 <= y <= 21 else 3 if y in (14, 22) else 2
    for x in range(5 - half, 5 + half + 1): skeleton[y][x] = 'D' if y in (13, 23) or x in (5 - half, 5 + half) else 'N'
skeleton[18][5] = 'e'; skeleton[17][5] = 'e'; skeleton[19][5] = 'e'; skeleton[18][4] = 'e'; skeleton[18][6] = 'e'
skeleton = [''.join(r) for r in skeleton]
skeleton = stretch(skeleton, 48, [(12, 24), (27, 36)])

# ---------- ходячий мертвец 40×48: сгорбленный, руки вперёд, рваная одежда, оголённая кость ----------
walking_dead = rows_from("""
..............GGGGGGGGG.................
............GGhhhhhhhhhGG...............
...........GhhhhhhhhhhhhhG..............
...........GhhhGGhhhhGGhhG..............
...........GhhhGzhhhhGzhhG..............
...........GhhhhhhhhhhhhhG..............
...........GhhhhGGGGGhhhhG..............
............GhhhhhhhhhhhG...............
.............GGGhhhhhGGG................
................GhhhG...................
............HHHHHhhhHHHHH...............
..........HHHHHHHhhhHHHHHHH.............
.........HHHHDDHHHHHHHHDDHHH............
........HHHHDDDHHHHHHHHDDDHHHHhhhhhh....
........HHHHDDHHHHHHHHHHDDHHHhhhhhhhh...
........HHHHHHHHHHDDDHHHHHHHHhhhGhhhh...
........HHHHHHHHHDDDDDHHHHHHHHhhhhhhh...
........HHHHHHHHHDDDDDHHHHHHHHhhhGGGh...
........HHHHHHHHHHDDDHHHHHHHHHGGG.......
........HHHHHHHHHHHHHHHHHHHHHH..........
........HHHHDDHHHHHHHHHHHDDHHH..........
........HHHHDDDHHHHHHHHHDDDHHH..........
.........HHHDDHHHHHHHHHHDDHHH...........
..........HHHHHHHHHHHHHHHHHH............
...........NNNNNNNNNNNNNNNN.............
...........NNNNNNNNNNNNNNNN.............
...........NnnnnnnnNNnnnnnN.............
...........NnnnnnnnN.NnnnnN.............
...........NnnDDnnnN.NnnnnN.............
...........NnnDDDnnN.NnDDnN.............
...........NnnnDDnnN.NnDDnN.............
...........NnnnnnnnN.NnnnnN.............
...........NnnnnnnnN.NnnnnN.............
...........NNnnnnnNN.NNnnNN.............
...........NNNNNNNNN.NNNNNN.............
..........DDDDDDDDDD.DDDDDDD............
..........DDDDDDDDDD.DDDDDDD............
""")
walking_dead = stretch(walking_dead, 48, [(10, 23), (26, 34)])
walking_dead = [list(r) for r in walking_dead]
for y in range(14, 19): walking_dead[y][9] = 'i'; walking_dead[y][10] = 'I'    # кость наружу на левом плече
walking_dead = [''.join(r) for r in walking_dead]

# ---------- вампир 40×48: чёрный плащ с алой подкладкой, бледное лицо, высокий воротник ----------
vampire = rows_from("""
..............zzzzzzzzz.................
............zzzzzzzzzzzzz...............
...........zzzzzzzzzzzzzzz..............
...........zzzLLLLLLLLLzzz..............
...........zzLLLLLLLLLLLzz..............
...........zzLLLkLLLkLLLzz..............
...........zzLLLLLLLLLLLzz..............
...........zzlLLLLLLLLLlzz..............
............zlLLrrrrrLLlz...............
............zllLLLLLLLllz...............
.............zllllllllllz...............
........RRR...zzlllllzz...RRR...........
.......RRRRR.zzzzzzzzzzz.RRRRR..........
.......RRRRRzzzzzzzzzzzzzRRRRR..........
.......RRRRzzzzzzzzzzzzzzzRRRR..........
.......RRRzzzzzzzzzzzzzzzzzRRR..........
......RRRRzzzzzzzzzzzzzzzzzRRRR.........
......RRRRzzzzzzzzzzzzzzzzzRRRR.........
......RRRRzzzzzzzzzzzzzzzzzRRRR.........
......RRRRzzzzzzzzzzzzzzzzzRRRR.........
......RRRRzzzzzzzzzzzzzzzzzRRRR.........
......RRRRzzzzzzzzzzzzzzzzzRRRR.........
......RRRRzzzzzzzzzzzzzzzzzRRRR.........
......RRRRzzzzzzzzzzzzzzzzzRRRR.........
......rRRRzzzzzzzzzzzzzzzzzRRRr.........
......rRRRzzzzzzzzzzzzzzzzzRRRr.........
......rRRRRzzzzzzzzzzzzzzzRRRRr.........
......rrRRRRzzzzzzzzzzzzzRRRRrr.........
......rrrRRRRRzzzzzzzzzRRRRRrrr.........
.......rrrrRRRRRzzzzzRRRRRrrrr..........
........rrrrrrRRRzzzRRRrrrrrr...........
..........rrrrrrrzzzrrrrrrr.............
..............zzzzzzzzz.................
..............zzz...zzz.................
..............zzz...zzz.................
..............zzz...zzz.................
..............zzz...zzz.................
..............zzz...zzz.................
..............zzz...zzz.................
.............zzzz...zzzz................
.............zzzz...zzzz................
""")
vampire = [list(r) for r in vampire]
for y in range(13, 22): vampire[y][31] = 'L'; vampire[y][32] = 'L'; vampire[y][33] = 'l'   # поднятая бледная рука
for x in range(30, 36): vampire[12][x] = 'L'
for x in (32, 33, 34): vampire[11][x] = 'L'
vampire[10][33] = 'L'; vampire[9][33] = 'l'
vampire = [''.join(r) for r in vampire]
vampire = stretch(vampire, 48, [(12, 30), (33, 39)])

# ---------- лич 44×48: череп в тёмном капюшоне, пурпурная мантия, посох с черепом и зелёным светом ----------
lich = rows_from("""
.................PPPPPPPPP..................
...............PPPPPPPPPPPPP................
..............PPPPPPPPPPPPPPP...............
..............PPPPxxxxxxxPPPP...............
..............PPPxiiiiiiixPPP...............
..............PPPxiiiiiiixPPP...............
..............PPPxihhiihhixPP...............
..............PPPxiiiiiiixPPP...............
..............PPPxIiIiIiIxPPP...............
..............PPPPxIIIIIxPPPP...............
...............PPPPxxxxxPPPP................
................PPPPPPPPPPP.................
.............PPPPPxxxxxxxPPPPP..............
............PPPxxxxxxxxxxxxxPPP.............
...........PPxxxxxxxxxxxxxxxxxPP............
...........PxxxxxxxxxxxxxxxxxxxP............
...........PxxxPxxxxxxxxxxxPxxxP............
...........PxxxPxxxxaaaxxxxPxxxP............
...........PxxxPxxxaAAAaxxxPxxxP............
...........PxxxPxxxxaaaxxxxPxxxP............
...........PxxxPxxxxxxxxxxxPxxxP............
...........PxxxPPxxxxxxxxxPPxxxP............
...........PxxxxPPPPPPPPPPPxxxxP............
...........PxxxxxxxxxxxxxxxxxxxP............
...........PxxxxxxxxxxxxxxxxxxxP............
...........PxxxxxxxxxxxxxxxxxxxP............
...........PxxxxxxxxxxxxxxxxxxxP............
...........PxxxxxxxxxxxxxxxxxxxP............
...........PxxxxxxxxxxxxxxxxxxxP............
...........PxxxxxxxxxxxxxxxxxxxP............
...........PPxxxxxxxxxxxxxxxxxPP............
...........PPPxxxxxxxxxxxxxxxPPP............
...........PPPPPPPPPPPPPPPPPPPPP............
""")
lich = [list(r) for r in lich]
for y in range(8, 33): lich[y][36] = 'D'; lich[y][37] = 'N'; lich[y][38] = 'D'            # посох
for y, half in ((2, 1), (3, 2), (4, 3), (5, 3), (6, 2), (7, 1)):                        # череп на посохе
    for x in range(37 - half, 38 + half): lich[y][x] = 'i'
lich[5][36] = 'z'; lich[5][38] = 'z'
for y, half in ((0, 1), (1, 2)):                                                         # зелёный свет
    for x in range(37 - half, 38 + half): lich[y][x] = 'h'
for y in range(17, 21):                                                                  # рука к посоху
    for x in range(30, 36): lich[y][x] = 'i' if y in (18, 19) else 'I'
lich = [''.join(r) for r in lich]
lich = stretch(lich, 48, [(12, 22), (23, 32)])

# ---------- привидение (композитор) 44×48: саван с рваным низом, парит, светящиеся глаза ----------
c = Canvas(44, 48)
c.ellipse(22, 14, 9, 10, 'l')                     # голова-капюшон
c.ellipse(22, 16, 6, 6, 'z')                      # тьма внутри капюшона
c.put(19, 15, 'A'); c.put(20, 15, 'A'); c.put(25, 15, 'A'); c.put(26, 15, 'A')   # глаза
c.poly([(12, 22), (32, 22), (36, 40), (8, 40)], 'l')   # саван
c.ellipse(22, 31, 7, 8, 'L')  # свет пятном по центру
for x0 in range(9, 36, 6):                         # рваный низ
    c.poly([(x0, 40), (x0 + 3, 46), (x0 + 6, 40)], 'l')
c.poly([(4, 26), (12, 24), (12, 30), (2, 33)], 'l')   # рукав-обрывок влево
c.poly([(32, 24), (42, 22), (40, 30), (32, 31)], 'l') # рукав вправо
c.ellipse(41, 21, 2.5, 2, 'L')                    # кисть
c.outline(between=set())
wight = [r.replace('k', '.') for r in c.rows()]

# ---------- чёрный рыцарь (композитор) 64×56: чёрный конь с алыми глазами, всадник в чёрных латах, меч ----------
c = Canvas(64, 56)
c.ellipse(30, 36, 18, 9, 'z'); c.ellipse(46, 30, 8, 7.5, 'z'); c.ellipse(18, 38, 9, 7, 'D', rot=0.2)
c.ellipse(52, 21, 6, 8, 'z', rot=-0.5); c.ellipse(58, 15, 5, 4, 'z'); c.ellipse(61, 16, 2.5, 2, 'D')
c.ellipse(30, 34, 12, 4, 'u')   # блик на спине коня
c.put(58, 13, 'r'); c.poly([(54, 9), (56, 6), (58, 11)], 'z')
c.feathers([(48, 14), (54, 10)], 'z', 2.4, (-0.2, -0.8))
for x0 in (14, 22, 36, 44):
    c.poly([(x0, 42), (x0 - 1, 54), (x0 + 4, 54), (x0 + 5, 42)], 'z' if x0 > 30 else 'D')
    c.poly([(x0 - 2, 52), (x0 - 2, 55), (x0 + 5, 55), (x0 + 5, 52)], 'u')
c.line(12, 33, 4, 46, 'D', th=3)
c.ellipse(30, 30, 9, 4, 'R'); c.ellipse(30, 31, 8, 3, 'x')
c.ellipse(31, 18, 6, 8, 'E'); c.ellipse(29, 17, 3, 6, 'e'); c.ellipse(32, 20, 3, 4, 'u')
c.ellipse(31, 9, 4.5, 4.5, 'E'); c.ellipse(30, 8, 2, 2, 'e'); c.poly([(28, 9), (34, 9), (34, 11), (28, 11)], 'r')   # алая щель
c.feathers([(29, 3), (33, 2)], 'R', 2.0, (0, -0.6))
c.poly([(24, 20), (18, 40), (23, 41), (28, 24)], 'E'); c.ellipse(20, 41, 3, 2, 'u')
c.line(36, 17, 46, 3, 'e', th=2); c.line(37, 17, 46, 4, 'l', th=1)   # меч поднят
c.poly([(33, 16), (40, 16), (40, 18), (33, 18)], 'Y')
c.poly([(6, 22), (14, 20), (16, 30), (8, 34)], 'z'); c.ellipse(11, 26, 2, 2.5, 'i')   # щит с черепом
c.outline(between=set())
black_knight = [r.replace('k', '.') for r in c.rows()]
black_knight = [list(r) for r in black_knight]; black_knight[13][58] = 'r'; black_knight = [''.join(r) for r in black_knight]

# ---------- костяной дракон (композитор) 64×62: череп с рогами, костяные крылья с обрывками перепонки, рёбра, хвост ----------
c = Canvas(64, 62)
# крылья: костяные спицы + тёмно-пурпурные обрывки перепонки
for (x0, y0), (x1, y1) in (((26, 30), (6, 4)), ((26, 30), (16, 2)), ((26, 30), (28, 1))):
    c.line(x0, y0, x1, y1, 'I', th=2)
c.poly([(26, 30), (6, 4), (16, 2), (28, 1), (24, 22)], 'P')
c.poly([(26, 30), (8, 6), (14, 4), (22, 26)], 'x')
for (x0, y0), (x1, y1) in (((26, 30), (6, 4)), ((26, 30), (16, 2)), ((26, 30), (28, 1))):
    c.line(x0, y0, x1, y1, 'i', th=1)
# тело: позвоночник и рёбра
c.ellipse(30, 38, 14, 8, 'I')
c.ellipse(30, 38, 12, 6, 'z')
for x in range(20, 42, 4): c.line(x, 32, x - 1, 44, 'i', th=1)
c.line(16, 36, 44, 36, 'i', th=2)
# шея и череп
c.line(42, 34, 52, 18, 'I', th=4); c.line(42, 34, 52, 18, 'i', th=2)
c.ellipse(55, 14, 7, 6, 'i'); c.poly([(58, 15), (64, 17), (58, 20)], 'I')   # челюсть
c.put(54, 12, 'h'); c.put(55, 12, 'h'); c.put(54, 13, 'h')                   # глаз
c.poly([(50, 9), (46, 2), (53, 8)], 'I'); c.poly([(56, 8), (58, 1), (60, 8)], 'I')   # рога
# лапы и хвост
for x0 in (20, 36):
    c.poly([(x0, 44), (x0 - 2, 56), (x0 + 3, 56), (x0 + 4, 44)], 'I')
    c.poly([(x0 - 4, 55), (x0 + 6, 55), (x0 + 6, 58), (x0 - 4, 58)], 'i')
c.line(16, 40, 4, 52, 'I', th=3); c.line(4, 52, 2, 58, 'I', th=2)
c.outline(between=set())
bone_dragon = [r.replace('k', '.') for r in c.rows()]

out = "/* ============================================================================\n"
out += "   view/sprites_necropolis_hd.js — существа Некрополиса в крупной сетке (unit 2), стиль Б:\n"
out += "   без контурной линии, тона кладёт рисунок. Собирается скриптом dev/proto/necro_hd.py.\n"
out += "   ========================================================================== */\n(function () {\n  'use strict';\n  H3.Sprites.defineMany({\n"
out += block('skeleton', skeleton, 'скелет: череп с глазницами, рёбра, ржавый меч, круглый щит')
out += block('skeleton_warrior', None, 'скелет-воин: шлем и клинок из стали, красный щит', base='skeleton', tint={'O': 'l', 'N': 'R'}, extra=[(19,0,'e'),(20,0,'e'),(18,1,'e'),(21,1,'e'),(17,2,'e'),(22,2,'e')])
out += block('walking_dead', walking_dead, 'ходячий мертвец: сгорбленный, руки вперёд, рваная одежда, кость наружу')
out += block('zombie', None, 'зомби: кожа сереет, одежда в бурый, больше кости', base='walking_dead', tint={'h': 'v', 'G': 'q', 'z': 'D', 'u': 'N'}, extra=[(9,15,'i'),(9,16,'i'),(9,17,'i')])
out += block('wight', wight, 'привидение: саван с рваным низом, тьма под капюшоном, светящиеся глаза (композитор)')
out += block('wraith', None, 'призрак: саван темнеет, глаза в ядовитый свет', base='wight', tint={'l': 'u', 'L': 'l', 'A': 'h'})
out += block('vampire', vampire, 'вампир: чёрный плащ с алой подкладкой, бледное лицо, поднятая рука')
out += block('vampire_lord', None, 'лорд вампиров: подкладка в пурпур, седые виски, золотая застёжка', base='vampire', tint={'r': 'p', 'R': 'P'}, extra=[(13,4,'l'),(13,5,'l'),(24,4,'l'),(24,5,'l'),(19,12,'y'),(20,12,'y')])
out += block('lich', lich, 'лич: череп в капюшоне, пурпурная мантия с магическим знаком, посох с черепом')
out += block('power_lich', None, 'могучий лич: мантия чернеет, знак и свет посоха ярче', base='lich', tint={'x': 'P', 'P': 'z', 'a': 'A', 'h': 'A'})
out += block('black_knight', black_knight, 'чёрный рыцарь: чёрный конь с алыми глазами, чёрные латы, меч, щит с черепом (композитор)')
out += block('dread_knight', None, 'рыцарь смерти: латы в пурпур, попона алая, плюмаж пурпурный', base='black_knight', tint={'E': 'P', 'e': 'p', 'R': 'r', 'x': 'R'})
out += block('bone_dragon', bone_dragon, 'костяной дракон: череп с рогами, крылья-спицы с обрывками перепонки, рёбра, хвост (композитор)')
out += block('ghost_dragon', None, 'призрачный дракон: кость в мятный свет, перепонка в бирюзу', base='bone_dragon', tint={'i': 'v', 'I': 'q', 'P': 'Q', 'x': 'q', 'h': 'A'})
out += "  });\n})();\n"
p = os.path.join(os.path.dirname(__file__), '..', '..', 'js', 'view', 'sprites_necropolis_hd.js')
io.open(p, 'w', encoding='utf-8').write(out)
print('записан', os.path.relpath(p))
