# -*- coding: utf-8 -*-
"""Сборка js/view/sprites_stronghold_hd.js: 14 существ Цитадели в крупной сетке (unit 2), стиль Б.
Гоблин, орк, огр, циклоп — строками; наездник на волке, рух, чудище — композитором."""
import io, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from compose import Canvas
from castle_hd import rows_from, pad, block, stretch   # общие помощники (castle_hd при импорте пересобирает свой файл — это безвредно)

# ---------- гоблин 36×44: маленький, зелёный, большие уши, дубинка, красная повязка ----------
goblin = rows_from("""
..............gggggggg..........NN..
.....gg......gggggggggg........NNNN.
....gggg....gggggggggggg......NNNNN.
...ggggg...ggggggggggggg......NNNNN.
...ggggggggggGGGGggGGGgg......NNNNN.
...gggggggggGGwwGGGGwwGG.......NNN..
....ggggggggGGkwGGGGwkGG.......NNN..
.....gggggggggGGGgggGGGg.......NNN..
.......ggggggggggggggggg.......NNN..
.........ggggggGGGGGgg.........NNN..
.........ggggGGRRRGGgg.........NNN..
..........gggGGGGGGGgg.........NNN..
...........gggggggggg..........NNN..
............GGGGGGGG...........NNN..
...........GGGGGGGGGG..........nnn..
..........GGGGGGGGGGGG.........nnn..
.........GGGGGGGGGGGGGG........nnn..
........GGGGGGGGGGGGGGGG.......nnn..
.......gggGGGGGGGGGGGGgggg.....nnn..
......ggggGGGGGGGGGGGGggggg...nnnn..
......ggggGGGGGGGGGGGGggggggnnnnnn..
......ggggGGGGGGGGGGGGgggggggnnnn...
......gggg.GGGGGGGGGGG.gggggggg.....
......gggg.rrrrrrrrrrr..gggggg......
.......gg..rRrRrRrRrRr..............
...........RRRRRRRRRRR..............
...........RRRRRRRRRRR..............
...........rrrrrrrrrrr..............
...........gggggg.gggggg............
...........gggggg.gggggg............
...........GGGGGG.GGGGGG............
...........GGGGGG.GGGGGG............
...........gggggg.gggggg............
...........gggggg.gggggg............
..........nnnnnnn.nnnnnnn...........
..........NNNNNNN.NNNNNNN...........
""")
goblin = [list(r) for r in goblin]
for y, xs in ((1, (25, 26)), (2, (24, 25, 26, 27)), (3, (24, 25, 26, 27, 28)), (4, (24, 25, 26, 27))):   # правое ухо
    for x in xs: goblin[y][x] = 'g'
goblin = [''.join(r) for r in goblin]
goblin = stretch(goblin, 44, [(14, 22), (28, 33)])

# ---------- орк 44×52: зеленокожий здоровяк, клыки, кожаная броня, метательный топор ----------
orc = rows_from("""
..............GGGGGGGGGGGG..................
............GGGGGGGGGGGGGGGG................
...........GGGGGGGGGGGGGGGGGG...............
...........GGGggggggggggggGGG...............
...........GGggggggggggggggGG...............
...........GGgggGGGggggGGGggG...............
...........GGgggGwwGggggGwwGG...............
...........GGgggGwkGggggGkwGG...............
...........GGggggggggggggggGG...............
...........GGggggggGGGGggggGG...............
............GgggggGGGGGGggG.................
............GgggggggggggggG.................
............GggiiGGGGGGiigG.................
.............GgiiggggggiigG.................
..............GGgggggggggG..................
...............GGGGGGGGGG...................
...........nnnnnnnnnnnnnnnnnn...............
.........nnnnnnnnnnnnnnnnnnnnnn.............
........nnnnNNNnnnnnnnnnnNNNnnnn............
.......ggggnNNNNnnnnnnnnNNNNnggggg..........
......gggggnnNNNnnnnnnnnnNNNnnggggg.........
......gggggnnnnnnnnnnnnnnnnnnnggggg.........
......gggggnnnnnNNNNNNNNnnnnnnggggg.........
......gggggnnnnNNNNNNNNNNnnnnnggggg.........
......gggggnnnnNNNNNNNNNNnnnnnggggg.........
......GGGGGnnnnnNNNNNNNNnnnnnnGGGGG.........
......GGGGGnnnnnnnnnnnnnnnnnnnGGGGG.........
......GGGGG.nnnnnnnnnnnnnnnnn.GGGGG.........
......ggggg.nnnnnnnnnnnnnnnnn.ggggg.........
......ggggg.NNNNNNNNNNNNNNNNN.ggggg.........
......ggggg.NNNNNNNNNNNNNNNNN.ggggg.........
.......ggg..nnnnnnnnnnnnnnnnn..ggg..........
............NNNNNNNNNNNNNNNNN...............
............NNNNNNNNNNNNNNNNN...............
............nnnnnnnnnnnnnnnnn...............
............ggggggggg.gggggggg..............
............ggggggggg.gggggggg..............
............GGGGGGGGG.GGGGGGGG..............
............GGGGGGGGG.GGGGGGGG..............
............ggggggggg.gggggggg..............
............ggggggggg.gggggggg..............
...........NNNNNNNNNN.NNNNNNNNNN............
...........DDDDDDDDDD.DDDDDDDDDD............
""")
orc = [list(r + '....') for r in orc]   # запас справа под лезвие
for y in range(6, 28): orc[y][37] = 'N'; orc[y][38] = 'n'; orc[y][39] = 'N'           # рукоять топора
for y, half in ((3, 2), (4, 4), (5, 5), (6, 5), (7, 5), (8, 4), (9, 3), (10, 2)):     # лезвие
    for x in range(38 - half - 2, 38 - 1): orc[y][x] = 'l' if half > 3 else 'e'
    for x in range(39 + 1, 39 + half + 2): orc[y][x] = 'e'
for y in range(19, 24):
    for x in range(33, 37): orc[y][x] = 'g' if y != 21 else 'G'                       # кисть на рукояти
orc = [''.join(r) for r in orc]
orc = stretch(orc, 52, [(16, 30), (35, 42)])

# ---------- огр 52×56: толстый жёлто-коричневый великан, живот, набедренная повязка из шкуры, дубина ----------
ogre = rows_from("""
..............NNNNNNNNNNNN..........................
............NNNNNNNNNNNNNNNN..................DDDDD.
...........NNNNNNNNNNNNNNNNNN................DDDNNDD
...........NNNtttttttttttNNNN...............DDNNNNND
...........NNttttttttttttttNN...............DNNnnNND
...........NNtttTTTttttTTTtNN...............DNNnnNND
...........NNtttTwwTttttTwwTN...............DNNnnNND
...........NNtttTwkTttttTkwTN...............DDNNNNDD
...........NNttttttttttttttNN................DDNNNDD
...........NNtttttttTTTttttNN.................DNNND.
............NtttttttTTTTtttN..................DNNND.
............NttttTTTTTTTTttN..................DNNND.
............NtttiTTTTTTTTitN..................DNNND.
.............NttiitttttiitN...................DNNND.
..............NNttttttttNN....................DNNND.
................NNNNNNNN......................DNNND.
............tttttttttttttttt..................DNNND.
..........tttttttttttttttttttt................DNNND.
.........ttttttttttttttttttttttt..............DNNND.
........tttttttttttttttttttttttttt............DNNND.
.......tttttttttttttttttttttttttttt...........DNNND.
......ttttttTTTTTTTTTTTTTTTTttttttttt.........DNNND.
......tttttTTTTTTTTTTTTTTTTTTtttttttt.........DNNND.
......tttttTTTTTTTTTTTTTTTTTTttttttttt........DNNND.
......tttttTTTTTTTTTTTTTTTTTTtttttttttt.......DNNND.
......tttttTTTTTTTTTTTTTTTTTTttttttttttt......NNNNN.
......tttttTTTTTTTTTTTTTTTTTTtttttttttttt.....nnnnn.
......TTTTTTTTTTTTTTTTTTTTTTTTtttttttttttttt.nnnnn..
......TTTTTTTTTTTTTTTTTTTTTTTTtttttttttttttttnnnn...
......TTTTT.TTTTTTTTTTTTTTTTTTttttttttttttttnnnn....
......TTTTT.TTTTTTTTTTTTTTTTTTtttttttttttttnnnn.....
......ttttt.TTTTTTTTTTTTTTTTTT..tttttttttt.nnnn.....
......ttttt.TTTTTTTTTTTTTTTTTT....tttttt...nnn......
.......ttt..nnNnnNnnNnnNnnNnnN......................
............nNnnNnnNnnNnnNnnNn......................
............NnnNnnNnnNnnNnnNnn......................
............nNnnNnnNnnNnnNnnNn......................
............NNNNNNNNNNNNNNNNNN......................
............ttttttttt..tttttttt.....................
............ttttttttt..tttttttt.....................
............TTTTTTTTT..TTTTTTTT.....................
............TTTTTTTTT..TTTTTTTT.....................
............ttttttttt..tttttttt.....................
............ttttttttt..tttttttt.....................
...........NNNNNNNNNN..NNNNNNNNNN...................
...........DDDDDDDDDD..DDDDDDDDDD...................
""")
ogre = stretch(ogre, 56, [(16, 32), (37, 44)])

# ---------- циклоп 56×60: одноглазый великан, красная повязка, камень в поднятой руке ----------
cyclops = rows_from("""
.............................................IIIIIIII...
...........................................IIIIiiiiIII..
..........................................IIiiiiiiiiIII.
..........................................IiiiiiiiiiIII.
..........................................IiiiiiiiiIIII.
..........................................IIiiiiiIIIII..
...........................................IIIIIIIIII...
..............NNNNNNNNNNNN...................ssssss.....
............NNNNNNNNNNNNNNNN................ssssss......
...........NNNNNNNNNNNNNNNNNN..............ssssss.......
...........NNsssssssssssssNNN.............ssssss........
...........NssssssssssssssssN............ssssss.........
...........NssssssssssssssssN...........ssssss..........
...........NsssssssSSSssssssN..........ssssss...........
...........NssssssSbbbSsssssN.........ssssss............
...........NssssssSbkbSsssssN........SSSSSS.............
...........NsssssssSSSssssssN.......SSSSSS..............
...........NssssssssssssssssN......SSSSSS...............
...........NsssssSSSSSSSsssSN.....SSSSSS................
............NssssiSiSiSissSN.....SSSSSS.................
............NssssSSSSSSSssSN....SSSSSS..................
.............NsssssssssssSN....SSSSSS...................
..............NNsssssssSNN....SSSSSS....................
................NNNNNNNN.....SSSSSS.....................
.............sssssssssssssssssssss......................
..........sssssssssssssssssssssssss.....................
.........sssssssssssssssssssssssssss....................
........ssssssssssssssssssssssssssss....................
.......ssssssSSSSSSSSSSSSSSSssssssss....................
......sssssssSSSSSSSSSSSSSSSssssssss....................
......ssssss.SSSSSSSSSSSSSSSsssssss.....................
......ssssss.SSSSSSSSSSSSSSSsssssss.....................
......ssssss.SSSSSSSSSSSSSSSsssssss.....................
......ssssss.SSSSSSSSSSSSSSSsssssss.....................
......ssssss.SSSSSSSSSSSSSSSsssssss.....................
......SSSSSS.SSSSSSSSSSSSSSSSSSSSSS.....................
......SSSSSS.SSSSSSSSSSSSSSSSSSSSSS.....................
......ssssss.SSSSSSSSSSSSSSSSSSSSSS.....................
......ssssss.rrrrrrrrrrrrrrrrrrrrr......................
.......ssss..rRrRrRrRrRrRrRrRrRrRr......................
.............RRRRRRRRRRRRRRRRRRRRR......................
.............rrrrrrrrrrrrrrrrrrrrr......................
.............RRRRRRRRRRRRRRRRRRRRR......................
.............sssssssss...sssssssss......................
.............sssssssss...sssssssss......................
.............SSSSSSSSS...SSSSSSSSS......................
.............SSSSSSSSS...SSSSSSSSS......................
.............sssssssss...sssssssss......................
.............sssssssss...sssssssss......................
............NNNNNNNNNNN.NNNNNNNNNNN.....................
............DDDDDDDDDDD.DDDDDDDDDDD.....................
""")
cyclops = [list(r) for r in cyclops]
for x in range(19, 24): cyclops[12][x] = 'S'; cyclops[16][x] = 'S'                      # бровь и низ глазницы
for y in (13, 14, 15):                                                                  # большой глаз с белком
    cyclops[y][18] = 'S'; cyclops[y][24] = 'S'; cyclops[y][19] = 'w'; cyclops[y][23] = 'w'
    for x in (20, 21, 22): cyclops[y][x] = 'b'
cyclops[14][21] = 'k'
cyclops = [''.join(r) for r in cyclops]
cyclops = stretch(cyclops, 60, [(24, 38), (43, 49)])

# ---------- наездник на волке (композитор) 56×48: серый волк в прыжке, гоблин с копьём ----------
c = Canvas(56, 48)
c.ellipse(28, 32, 17, 7, 'e')                       # тело волка
c.ellipse(24, 30, 10, 4, 'l')                       # светлая спина
c.ellipse(28, 35, 13, 3.5, 'E')                     # тёмное брюхо
c.ellipse(44, 28, 7, 5.5, 'e'); c.ellipse(50, 30, 5, 3.5, 'e')   # голова и морда
c.ellipse(52, 31, 3.5, 2, 'E'); c.put(53, 30, 'k')  # нос
c.put(46, 26, 'y'); c.put(47, 26, 'y'); c.put(46, 27, 'k')     # глаз
c.poly([(40, 22), (43, 26), (45, 24)], 'e'); c.poly([(46, 22), (48, 26), (50, 24)], 'e')   # уши
c.poly([(41, 23), (43, 25), (44, 24)], 'E'); c.poly([(47, 23), (48, 25), (49, 24)], 'E')
for x in range(46, 54, 3): c.put(x, 33, 'w'); c.put(x + 1, 33, 'w')   # клыки
c.poly([(12, 30), (2, 22), (0, 25), (10, 34)], 'e'); c.ellipse(2, 23, 2.5, 2.5, 'l')   # хвост
for x0, mat in ((14, 'E'), (20, 'e'), (34, 'E'), (40, 'e')):   # лапы в беге
    dx = 4 if mat == 'e' else -3
    c.poly([(x0, 36), (x0 + dx, 47), (x0 + dx + 5, 47), (x0 + 5, 36)], mat)
    c.ellipse(x0 + dx + 2.5, 46.5, 3.5, 1.5, 'E')
# гоблин верхом
c.poly([(22, 22), (30, 22), (32, 31), (20, 31)], 'G')               # туловище в тёмно-зелёной куртке
c.ellipse(26, 27, 4, 3, 'r')                                        # красный нагрудник
c.ellipse(26, 15, 6, 6, 'g'); c.ellipse(25, 14, 3, 3, 'h')           # голова со светлым лбом
c.poly([(18, 13), (22, 15), (21, 18)], 'g'); c.poly([(34, 13), (30, 15), (31, 18)], 'g')   # уши
c.put(24, 16, 'k'); c.put(28, 16, 'k'); c.put(23, 16, 'w'); c.put(29, 16, 'w')   # глаза
c.poly([(23, 30), (29, 30), (30, 36), (22, 36)], 'N')                 # набедренная повязка
c.line(31, 20, 44, 6, 'N', th=2)                                      # копьё
c.poly([(43, 8), (46, 2), (48, 7)], 'l')                              # наконечник
c.poly([(30, 24), (36, 18), (37, 21), (32, 27)], 'g')                 # рука с копьём
c.poly([(19, 24), (14, 30), (17, 31), (21, 27)], 'g')                 # рука с поводом
c.line(16, 30, 44, 29, 'D', th=1)                                     # повод
c.outline(between=set())
wolf_rider = [r.replace('k', '.') for r in c.rows()]
wolf_rider = [list(r) for r in wolf_rider]
wolf_rider[16][24] = 'k'; wolf_rider[16][28] = 'k'; wolf_rider[27][46] = 'k'; wolf_rider[30][53] = 'k'
wolf_rider = [''.join(r) for r in wolf_rider]

# ---------- рух (композитор) 64×60: огромная бурая птица, распахнутые крылья, жёлтый клюв, лапы вперёд ----------
c = Canvas(64, 60)
# крылья веером
for k, (x1, y1) in enumerate(((2, 4), (8, 1), (16, 0), (24, 2))):
    c.poly([(30, 26), (x1, y1), (x1 + 8, y1 + 1), (32, 30)], 'n' if k % 2 else 'N')
for k, (x1, y1) in enumerate(((62, 4), (56, 1), (48, 0), (40, 2))):
    c.poly([(34, 26), (x1, y1), (x1 - 8, y1 + 1), (32, 30)], 'n' if k % 2 else 'N')
c.poly([(2, 4), (10, 2), (18, 1), (32, 12), (32, 30), (14, 16)], 'n')   # плоскость левого крыла
c.poly([(62, 4), (54, 2), (46, 1), (32, 12), (32, 30), (50, 16)], 'n')
for x1, y1 in ((2, 4), (10, 2), (18, 1)): c.line(32, 14, x1, y1, 'N', th=1)      # перья-линии
for x1, y1 in ((62, 4), (54, 2), (46, 1)): c.line(32, 14, x1, y1, 'N', th=1)
c.feathers([(4, 5), (30, 20)], 'N', 2.2, (0, 0.7))                    # зубчатый низ крыльев
c.feathers([(60, 5), (34, 20)], 'N', 2.2, (0, 0.7))
# тело
c.ellipse(32, 30, 8, 12, 'n'); c.ellipse(32, 32, 5, 8, 't')             # грудь светлее
c.ellipse(32, 15, 6, 5.5, 'n'); c.ellipse(31, 13, 3, 2.5, 't')          # голова
c.poly([(28, 16), (36, 16), (32, 24)], 'y'); c.poly([(29, 17), (35, 17), (32, 21)], 'Y')   # клюв
c.put(29, 13, 'k'); c.put(35, 13, 'k')
# хвост и лапы
c.poly([(28, 40), (36, 40), (40, 56), (24, 56)], 'N')
c.poly([(29, 42), (35, 42), (36, 54), (28, 54)], 'n')
for x0 in (22, 38):
    c.line(x0 + 2, 42, x0, 50, 'y', th=2)
    for dx in (-3, 0, 3): c.line(x0, 50, x0 + dx, 55, 'Y', th=1)
c.outline(between=set())
roc = [r.replace('k', '.') for r in c.rows()]
roc = [list(r) for r in roc]; roc[13][29] = 'k'; roc[13][35] = 'k'; roc = [''.join(r) for r in roc]

# ---------- чудище (композитор) 64×56: огромный бурый зверь на четырёх лапах, горб, когти, пасть ----------
c = Canvas(64, 56)
c.ellipse(30, 30, 22, 13, 'n')                     # туловище
c.ellipse(26, 22, 14, 7, 'd')                      # горб тёмный
c.ellipse(30, 36, 18, 6, 'N')                      # брюхо
c.ellipse(50, 22, 10, 8, 'n'); c.ellipse(56, 26, 7, 5, 'd')          # голова и морда
c.poly([(52, 28), (63, 27), (60, 33), (52, 32)], 'N')                # раскрытая пасть
for x in range(53, 62, 3): c.put(x, 28, 'w'); c.put(x + 1, 32, 'w')  # клыки
c.put(50, 19, 'y'); c.put(51, 19, 'y'); c.put(50, 20, 'k')           # глаз
c.poly([(44, 14), (46, 18), (49, 16)], 'd'); c.poly([(52, 13), (52, 17), (55, 15)], 'd')   # уши
c.feathers([(10, 20), (40, 14)], 'd', 2.4, (0, -0.6))                # взъерошенная холка
for x0, mat in ((10, 'd'), (18, 'n'), (38, 'd'), (46, 'n')):         # четыре лапы
    c.poly([(x0, 38), (x0 - 2, 52), (x0 + 6, 52), (x0 + 7, 38)], mat)
    c.ellipse(x0 + 2, 51, 5, 2.5, 'd')
    for dx in (-2, 1, 4): c.poly([(x0 + dx, 52), (x0 + dx + 1, 56), (x0 + dx + 2, 52)], 'i')   # когти
c.poly([(8, 26), (0, 32), (2, 36), (10, 32)], 'n')                    # хвост
c.outline(between=set())
behemoth = [r.replace('k', '.') for r in c.rows()]
behemoth = [list(r) for r in behemoth]; behemoth[20][50] = 'k'; behemoth = [''.join(r) for r in behemoth]

out = "/* ============================================================================\n"
out += "   view/sprites_stronghold_hd.js — существа Цитадели в крупной сетке (unit 2), стиль Б:\n"
out += "   без контурной линии, тона кладёт рисунок. Собирается скриптом dev/proto/stronghold_hd.py.\n"
out += "   ========================================================================== */\n(function () {\n  'use strict';\n  H3.Sprites.defineMany({\n"
out += block('goblin', goblin, 'гоблин: маленький зелёный, большие уши, дубинка, красная повязка')
out += block('hobgoblin', None, 'хобгоблин: повязка в кожу, красный шлем с гребнем', base='goblin', tint={'r': 'n', 'R': 'N'},
             extra=[(x, y, 'r') for y in (0, 1, 2) for x in range(13 + (2 - y) * 2, 23 - (2 - y) * 2)] + [(x, 3, 'R') for x in range(11, 25)] + [(17, 0, 'R'), (18, 0, 'R')])
out += block('wolf_rider', wolf_rider, 'наездник на волке: серый волк в прыжке, гоблин с копьём (композитор)')
out += block('wolf_raider', None, 'волчий налётчик: чёрный волк, гоблин в красной броне, острие темнее', base='wolf_rider', tint={'e': 'u', 'E': 'z', 'l': 'e', 'G': 'R', 'r': 'y'})
out += block('orc', orc, 'орк: зеленокожий, клыки, кожаная броня, метательный топор')
out += block('orc_chieftain', None, 'вождь орков: броня в красное, рогатый шлем', base='orc', tint={'n': 'r', 'N': 'R'},
             extra=[(x, y, 'e') for y, (a, b) in ((0, (14, 26)), (1, (12, 28)), (2, (11, 29))) for x in range(a, b)] + [(10, 0, 'i'), (11, 0, 'i'), (10, 1, 'I'), (11, 1, 'I'), (11, 2, 'I'), (28, 0, 'i'), (29, 0, 'i'), (28, 1, 'I'), (29, 1, 'I'), (28, 2, 'I')])
out += block('ogre', ogre, 'огр: толстый жёлто-коричневый великан, живот, повязка из шкуры, дубина')
out += block('ogre_mage', None, 'огр-маг: синяя кожа, повязка в пурпур, посох со светящимся шаром вместо дубины', base='ogre', tint={'t': 'b', 'T': 'B', 'n': 'p', 'N': 'P'},
             extra=[(x, y, 'c') for y in range(1, 8) for x in range(44, 52) if (x - 47.5) ** 2 + (y - 4) ** 2 <= 12] + [(47, 3, 'w'), (48, 3, 'w'), (47, 4, 'w')])
out += block('roc', roc, 'рух: огромная бурая птица, распахнутые крылья, жёлтый клюв, лапы вперёд (композитор)')
out += block('thunderbird', None, 'птица грома: синее оперение, светлая грудь, молнии из крыльев', base='roc', tint={'n': 'b', 'N': 'B', 't': 'c'},
             extra=[(x, y, 'y') for x, y in ((10, 10), (11, 11), (10, 12), (11, 13), (12, 14), (53, 10), (52, 11), (53, 12), (52, 13), (51, 14), (18, 6), (19, 7), (18, 8), (45, 6), (44, 7), (45, 8))])
out += block('cyclops', cyclops, 'циклоп: одноглазый великан, красная повязка, камень в поднятой руке')
out += block('cyclops_king', None, 'король циклопов: кожа темнее, повязка в золото, золотая корона', base='cyclops', tint={'s': 'S', 'S': 'n', 'r': 'y', 'R': 'Y'},
             extra=[(x, y, 'y') for y in (5, 6) for x in range(13, 27)] + [(x, 4, 'y') for x in (13, 14, 17, 18, 21, 22, 25, 26)] + [(x, 7, 'Y') for x in range(13, 27)])
out += block('behemoth', behemoth, 'чудище: огромный бурый зверь на четырёх лапах, горб, когти, раскрытая пасть (композитор)')
out += block('ancient_behemoth', None, 'древнее чудище: чёрно-серая шерсть, когти светлее и длиннее, глаз алый', base='behemoth', tint={'n': 'u', 'N': 'z', 'd': 'E', 'i': 'L', 'y': 'r'})
out += "  });\n})();\n"
p = os.path.join(os.path.dirname(__file__), '..', '..', 'js', 'view', 'sprites_stronghold_hd.js')
io.open(p, 'w', encoding='utf-8').write(out)
print('записан', os.path.relpath(p))
