# -*- coding: utf-8 -*-
"""Сборка js/view/sprites_tower_hd.js: 14 существ Башни в крупной сетке (unit 2), стиль Б.
Гремлин, голем, маг, гигант — строками; гаргулья, джинн, нага — композитором."""
import io, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from compose import Canvas
from castle_hd import rows_from, pad, block, stretch   # общие помощники (castle_hd при импорте пересобирает свой файл — это безвредно)

# ---------- гремлин 36×44: зелёный ушастый коротышка, бурая роба, цепь с чугунным ядром ----------
gremlin = rows_from("""
............ggggggggg...............
..........ggggggggggggg.............
.........ggggggggggggggg............
..gg....gggggggggggggggg....gg......
.gggg...gggggGGGggggGGGgg..gggg.....
.ggggggggggggGwwwggGwwwGgggggggg....
.ggggggggggggGwkwggGwkwGgggggggg....
..ggggggggggggGGGggggGGGgggggggg....
...ggg..gggggggggggggggggg..ggg.....
.........ggggggGGGGGGgggg...........
.........gggggGRRRRRRGgg............
..........ggggGGGGGGGGgg............
...........gggggggggggg.............
............NNNNNNNNN...............
..........NNnnnnnnnnnNN.............
.........NNnnnnnnnnnnnNN............
........NNnnnnnnnnnnnnnNN...........
.......gggNnnnnnnnnnnnNggg..........
......ggggNnnnnnnnnnnnNgggg.........
......ggggNnnnnnnnnnnnNgggg.........
......ggggNnnnnnnnnnnnNggggg........
......GGGGNnnnnnnnnnnnNGGGGG........
......gggg.NnnnnnnnnnN.gggg.........
......gggg.NnnnnnnnnnN..ggg.........
.......gg..DDDDDDDDDDD..............
...........NnnnnnnnnnN..............
...........NnnnnnnnnnN..............
...........NnnnnnnnnnN..............
...........NnnnnnnnnnN..............
...........NnnnnnnnnnN..............
...........NnnnnnnnnnN..............
..........NNnnnnnnnnnNN.............
..........NNNNNNNNNNNNN.............
...........ggggg.ggggg..............
...........ggggg.ggggg..............
...........GGGGG.GGGGG..............
..........NNNNNN.NNNNNN.............
..........DDDDDD.DDDDDD.............
""")
gremlin = [list(r) for r in gremlin]
for i in range(9):                                           # цепь от правой руки вниз-вправо к ядру
    x, y = 25 + i // 2, 22 + i
    for dx, ch in ((0, 'e'), (1, 'E'), (2, 'e')): gremlin[y][x + dx] = ch if i % 2 == 0 else ('E' if ch == 'e' else 'e')
for y in range(30, 38):                                      # ядро на земле справа
    half = (2, 3, 4, 4, 4, 4, 3, 2)[y - 30]
    for x in range(30 - half, 30 + half + 1): gremlin[y][x] = 'u'
for y, xs in ((31, (28, 29)), (32, (27, 28, 29)), (33, (27, 28))):
    for x in xs: gremlin[y][x] = 'E'                          # блик на ядре
gremlin = [''.join(r) for r in gremlin]
gremlin = stretch(gremlin, 44, [(13, 24), (33, 36)])

# ---------- каменный голем 44×52: приземистый истукан из песчаника, трещины, узкие щели глаз ----------
stone_golem = rows_from("""
................IIIIIIIIIIII................
...............IITTTTTTTTTTdd...............
...............ITTTTTTTTTTTTd...............
...............ITTkkkTTTkkkTd...............
...............ITTkkkTTTkkkTd...............
...............ITTTTTTTTTTTTd...............
...............ITTTdddddddTTd...............
...............IdTTTTTTTTTTdd...............
................dddddddddddd................
........IIIIIIIIIIIIIIIIIIIIIIIIIIIIII......
.....IIITTTTTTTTTTTTTTTTTTTTTTTTTTTTTTddd...
....ITTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTd..
...ITTTTTTdITTTTTTTTTTTTTTTTTTTTTTdTTTTTTTd.
..ITTTTTTTdITTTTTTTTTTTdTTTTTTTTTTdTTTTTTTTd
..ITTTTTTTdITTTTTTTTTTddTTTTTTTTTTdTTTTTTTTd
..ITTTTTTTdITTTTTTTTTddTTTTTTTTTTTdTTTTTTTTd
..ITTTTTTTdITTTTTTTTTdTTTTTTTTTTTTdTTTTTTTTd
..ITTTTTTTdITTTTTTTTddTTTTTdddTTTTdTTTTTTTTd
..ITTTTTTTdITTTTTTTTdTTTTTTTTdddTTdTTTTTTTTd
..ITTTTTTTdITTTTTTTTdTTTTTTTTTTddTdTTTTTTTTd
..ITTTTTTTdITTTTTTTddTTTTTTTTTTTTTdTTTTTTTTd
..ITTTTTTTdITTTTTTTdTTTTTTTTTTTTTTdTTTTTTTTd
..ITTTTTTTdITTTTTTddTTTTTTTTTTTTTTdTTTTTTTTd
..ITTTTTTTdITTTTTTdTTTTTTTTTTTTTTTdTTTTTTTTd
..ITTTTTTTdITTTTTTdTTTTTTTTTTTTTTTdTTTTTTTTd
..IIIIIIIIdITTTTTTdTTTTTTTTTTTTTTTdIIIIIIIId
..ITTTTTTTdITTTTTdTTTTTTTTTTTTTTTTdTTTTTTTTd
..ITTTTTTTdITTTTTdTTTTTTTTTTTTTTTTdTTTTTTTTd
..ITTTTTTTdITTTTTdTTTTTTTTTTTTTTTTdTTTTTTTTd
..IdddddddddTTTTTdTTTTTTTTTTTTTTTTddddddddd.
...........dddddddddddddddddddddddd.........
..........ITTTTTTTTTTd..ITTTTTTTTTTd........
..........ITTTTTTTTTTd..ITTTTTTTTTTd........
..........ITTTTTTTTTTd..ITTTTTTTTTTd........
..........ITTTTdTTTTTd..ITTTTTTTTTTd........
..........ITTTTdTTTTTd..ITTTTTTdTTTd........
..........ITTTTTdTTTTd..ITTTTTTdTTTd........
..........ITTTTTTTTTTd..ITTTTTTTTTTd........
..........ITTTTTTTTTTd..ITTTTTTTTTTd........
.........IITTTTTTTTTTdd.IITTTTTTTTTdd.......
.........IIIIIIIIIIIIdd.IIIIIIIIIIIIdd......
.........dddddddddddddd.ddddddddddddd.......
""")
stone_golem = [list(r) for r in stone_golem]
for y in range(12, 30):                                                           # шов рука/торс в две тени
    stone_golem[y][10] = 'd'; stone_golem[y][11] = 'd'; stone_golem[y][12] = 'I'
    stone_golem[y][33] = 'd'; stone_golem[y][34] = 'd'; stone_golem[y][35] = 'I'
for x in range(4, 9):  stone_golem[16][x] = 'd'; stone_golem[17][x] = 'd'          # трещины на плечах
for x in range(35, 40): stone_golem[21][x] = 'd'; stone_golem[22][x] = 'd'
stone_golem = [''.join(r) for r in stone_golem]
stone_golem = stretch(stone_golem, 52, [(11, 28), (31, 39)])

# ---------- маг 44×52: синяя мантия, остроконечная шляпа со звездой, седая борода, посох с шаром ----------
mage = rows_from("""
..............bb............................
..............bbb...........................
.............bbbb...........................
.............bbbbb..........................
............bbbbbb..........................
............bbbbbbb.........................
...........bbbbbbbb.........................
...........bbbbbbbbb........................
..........bbbybbbbbb........................
..........bbyyybbbbbb.......................
.........bbbbybbbbbbb.......................
.........bbbbbbbbbbbbb......................
........bbbbbbbbbbbbbb......................
....BBBBBBBBBBBBBBBBBBBBBB..................
....BBBBBBBBBBBBBBBBBBBBBB..................
.........sssssssssss........................
........sssssssssssss.......................
........ssswwsssssswws......................
........ssskwsssssskws......................
........sssssssssssss.......................
.........wwwsssssswww.......................
........wwwwwwsswwwwww......................
........wwwwwwwwwwwwww......................
.......wwwwwwwwwwwwwww......................
.....BBwwwwwwwwwwwwwwBB.....................
....BBbbwwwwwwwwwwwwbbBB....................
...BBbbbbwwwwwwwwwwbbbbBB...................
...BbbbbbbwwwwwwwwbbbbbbB...................
...BbbbbbbbwwwwwwbbbbbbbB...................
...BbbbbbbbbwwwwbbbbbbbbB...................
...BbbbbbbbbbwwbbbbbbbbbB...................
...BbbbbbbbbbbbbbbbbbbbbB...................
...BbbbbbbbbbbbbbbbbbbbbB...................
...BbbbbbbbbbbbbbbbbbbbbB...................
...BbbbyyyyyyyyyyyyyyybbB...................
...BbbbbbbbbbbbbbbbbbbbbB...................
...BbbbbbbbbbbbbbbbbbbbbB...................
...BbbbbbbbbbbbbbbbbbbbbB...................
...BbbbbbbbbbbbbbbbbbbbbB...................
...BbbbbbbbbbbbbbbbbbbbbB...................
...BbbbbbbbbbbbbbbbbbbbbB...................
...BbbbbbbbbbbbbbbbbbbbbB...................
..BBbbbbbbbbbbbbbbbbbbbbBB..................
..BBbbbbbbbbbbbbbbbbbbbbBB..................
..BBBBBBBBBBBBBBBBBBBBBBBB..................
""")
mage = [list(r) for r in mage]
for y in range(10, 44): mage[y][35] = 'N'; mage[y][36] = 'n'; mage[y][37] = 'n'; mage[y][38] = 'N'   # посох
for y in range(1, 10):                                                                    # шар на посохе
    half = (1, 3, 4, 4, 5, 4, 4, 3, 1)[y - 1]
    for x in range(37 - half, 37 + half + 1): mage[y][x] = 'a'
for y, half in ((3, 1), (4, 2), (5, 2), (6, 2), (7, 1)):
    for x in range(36 - half, 36 + half + 1): mage[y][x] = 'A'
for y in range(26, 32):                                                                   # рукав к посоху
    for x in range(24, 34): mage[y][x] = 'b' if y not in (26, 31) else 'B'
for y in range(28, 32):                                                                   # кисть на посохе
    for x in range(31, 36): mage[y][x] = 's' if mage[y][x] in 'bB' else mage[y][x]
mage = [''.join(r) for r in mage]
mage = stretch(mage, 52, [(24, 34), (35, 42)])

# ---------- гигант 64×60: исполин в белой тоге через плечо, тёмные волосы, молния в поднятой руке ----------
giant = rows_from("""
..........................DDDDDDDD..............................
........................DDDDDDDDDDDD............................
.......................DDDDDDDDDDDDDD...........................
.......................DDDDDDDDDDDDDD...........................
.......................DDSSSSSSSSSSDD...........................
.......................DSSSSSSSSSSSSD...........................
.......................DSSSSSSSSSSSSD...........................
.......................DSSSwwwSSwwwSD...........................
.......................DSSSwkwSSwkwSD...........................
.......................DSSSSSSSSSSSSD...........................
........................SSSSSSnnSSSS............................
........................SSSSSSSSSSSS............................
........................SSSSnnnnnSSS............................
.........................SSSSSSSSSS.............................
..........................SSSSSSSS..............................
...........................SSSSSS...............................
...........................SSSSSS...............................
..................LLLLLLLLLLLLLLLLSSSSSSSSSSSS..................
................LLLLLLLLLLLLLLLLLLSSSSSSSSSSSSSS................
...............LLLLLLLLLLLLLLLLLLLSSSSSSSSSSSSSSS...............
..............LLLLLLLLLLLLLLLLLLLLSSSSSSSSSSSSSSSS..............
..............LLLLLLLLLLLLLLLLLLLLSSSSSSSSSSSSSSSS..............
..............LLLLLLLLLLLLLLLLLLLLLSSSSSSSSSSSSSSS..............
..............LLLLLLLLLLLLLLLLLLLLLLSSSSSSSSSSSSSS..............
..............LLLLLL.LLLLLLLLLLLLLLLLSSSSSSSS.SSSS..............
..............LLLLLL.LLLLLLLLLLLLLLLLLSSSSSSS.SSSS..............
..............LLLLLL.LLLLLLLLLLLLLLLLLLSSSSSS.SSSS..............
..............SSSSSS.LLLLLLLLLLLLLLLLLLLSSSSS.SSSS..............
..............SSSSSS.LLLLLLLLLLLLLLLLLLLLSSSS.SSSS..............
..............SSSSSS.LLLLLLLLLLLLLLLLLLLLLSSS.SSSS..............
..............SSSSSS.LLLLLLLLLLLLLLLLLLLLLLSS.SSSS..............
..............SSSSSS.LLLLLLLLLLLLLLLLLLLLLLLS.SSSS..............
..............SSSSSS.LLLLLLLLLLLLLLLLLLLLLLLL.SSSS..............
..............SSSSSS.LLLLLLLLLLLLLLLLLLLLLLLL.SSSS..............
...............SSSS..YYYYYYYYYYYYYYYYYYYYYYYY.SSSS..............
.....................LLLLLLLLLLLLLLLLLLLLLLLL...................
.....................LLLLLLLLLLLLLLLLLLLLLLLL...................
.....................LLLLLLLLLLLLLLLLLLLLLLLL...................
.....................LLLLLLLLLLLLLLLLLLLLLLLL...................
.....................LLLLLLLLLLLLLLLLLLLLLLLL...................
.....................LLLLLLLLLLLLLLLLLLLLLLLL...................
.....................LLLLLLLLLLLLLLLLLLLLLLLL...................
.....................llllllllllllllllllllllll...................
.....................SSSSSSSSSS...SSSSSSSSSS....................
.....................SSSSSSSSSS...SSSSSSSSSS....................
.....................SSSSSSSSSS...SSSSSSSSSS....................
.....................SSSSSSSSSS...SSSSSSSSSS....................
.....................SSSSSSSSSS...SSSSSSSSSS....................
.....................SSSSSSSSSS...SSSSSSSSSS....................
.....................SSSSSSSSSS...SSSSSSSSSS....................
.....................SSSSSSSSSS...SSSSSSSSSS....................
....................NNNNNNNNNNN...NNNNNNNNNNN...................
....................NNNNNNNNNNN...NNNNNNNNNNN...................
....................DDDDDDDDDDD...DDDDDDDDDDD...................
""")
giant = [list(r) for r in giant]
# правая рука поднята вверх-вправо, кулак сжимает молнию
for y in range(17, 22):
    for x in range(46, 52): giant[y][x] = 'S'
for i in range(12):                                            # плечо → предплечье вверх
    y = 20 - i
    for x in range(48 + i // 2, 54 + i // 2): giant[y][x] = 'S'
zig = (2, 1, 0, 1, 2, 3, 4, 3, 2, 1, 0, 1, 2, 3, 4, 3)                        # зигзаг молнии, 4 px шириной
for y in range(16):
    x0 = 56 + zig[y]
    for dx in range(4): giant[y][x0 + dx] = 'f'
    giant[y][x0 + 1] = 'w'; giant[y][x0 + 2] = 'w'
for y in range(7, 11):                                                         # кулак поверх молнии
    for x in range(53, 59): giant[y][x] = 'S'
for y in range(8, 10): giant[y][55] = 'n'; giant[y][56] = 'n'
giant = [''.join(r) for r in giant]
giant = stretch(giant, 60, [(17, 33), (43, 51)])

# ---------- каменная гаргулья (композитор) 44×48: серая крылатая статуя-демон, рога, клыки, когти; парит ----------
c = Canvas(44, 48)
# крылья: сплошные тёмные перепонки со светлыми спицами
c.poly([(17, 24), (1, 2), (10, 0), (20, 6), (22, 12)], 'E'); c.poly([(27, 24), (43, 2), (34, 0), (24, 6), (22, 12)], 'E')
c.poly([(17, 24), (2, 6), (1, 20), (12, 28)], 'E'); c.poly([(27, 24), (42, 6), (43, 20), (32, 28)], 'E')
for (x1, y1) in ((2, 3), (10, 1), (2, 18)): c.line(17, 24, x1, y1, 'l', th=1)
for (x1, y1) in ((42, 3), (34, 1), (42, 18)): c.line(27, 24, x1, y1, 'l', th=1)
# тело, сгорбленное
c.ellipse(22, 26, 9, 9, 'e'); c.ellipse(22, 30, 8, 6, 'E')
c.ellipse(22, 14, 8.5, 7.5, 'e'); c.ellipse(22, 11, 6, 3, 'l')                  # голова, светлый лоб
c.poly([(14, 12), (9, 1), (19, 8)], 'l'); c.poly([(30, 12), (35, 1), (25, 8)], 'l')   # рога
for x, y in ((17, 14), (18, 14), (19, 14), (25, 14), (26, 14), (27, 14), (17, 15), (18, 15), (19, 15), (25, 15), (26, 15), (27, 15)): c.put(x, y, 'w')
c.poly([(16, 18), (28, 18), (26, 22), (18, 22)], 'E')                             # пасть
for x, y in ((17, 18), (18, 18), (26, 18), (27, 18), (17, 19), (18, 19), (26, 19), (27, 19)): c.put(x, y, 'w')   # клыки
# руки с когтями вперёд-вниз
c.poly([(14, 24), (6, 34), (10, 36), (18, 28)], 'e'); c.poly([(30, 24), (38, 34), (34, 36), (26, 28)], 'e')
for x0 in (5, 8, 11): c.poly([(x0, 35), (x0 - 1, 40), (x0 + 2, 36)], 'l')
for x0 in (33, 36, 39): c.poly([(x0, 35), (x0 + 1, 40), (x0 - 2, 36)], 'l')
# согнутые ноги, лапы до низа (просвет 3 строки)
c.poly([(16, 32), (10, 40), (14, 44), (20, 36)], 'E'); c.poly([(28, 32), (34, 40), (30, 44), (24, 36)], 'E')
c.ellipse(13, 43, 4, 2, 'e'); c.ellipse(31, 43, 4, 2, 'e')
for x0 in (10, 13, 16): c.poly([(x0, 43), (x0 + 1, 45), (x0 + 2, 43)], 'l')
for x0 in (28, 31, 34): c.poly([(x0, 43), (x0 + 1, 45), (x0 + 2, 43)], 'l')
c.line(20, 34, 12, 46, 'E', th=2)                                                 # хвост
c.outline(between=set())
stone_gargoyle = [r.replace('k', '.') for r in c.rows()]
stone_gargoyle = [list(r) for r in stone_gargoyle]
for x, y in ((18, 15), (26, 15)): stone_gargoyle[y][x] = 'k'
stone_gargoyle = [''.join(r) for r in stone_gargoyle]

# ---------- джинн (композитор) 52×56: синий дух без ног, руки скрещены на груди, дымный хвост, серьга ----------
c = Canvas(52, 56)
# дымный хвост: от пояса вниз влево и завиток к низу
c.poly([(20, 32), (34, 32), (26, 44), (12, 50), (8, 55), (2, 55), (6, 48), (14, 40)], 'c')
c.ellipse(6, 51, 5, 4, 'c'); c.ellipse(4, 54, 3, 2, 'w')
c.ellipse(24, 37, 4, 5, 'C'); c.ellipse(14, 46, 3, 4, 'C')                      # тени в дыме
# торс, пояс
c.ellipse(27, 24, 12, 10, 'b'); c.ellipse(27, 22, 12, 8, 'b')
c.poly([(15, 14), (39, 14), (37, 32), (17, 32)], 'b')
c.poly([(16, 30), (38, 30), (37, 34), (17, 34)], 'y')                            # пояс
c.ellipse(21, 20, 4, 6, 'B'); c.ellipse(33, 20, 4, 6, 'B')                        # тени грудных мышц
# руки: плечи вниз, предплечья крест-накрест толстым X, кулаки по краям
c.poly([(15, 14), (21, 14), (16, 26), (10, 25)], 'b'); c.poly([(33, 14), (39, 14), (44, 25), (38, 26)], 'b')
c.line(42, 27, 16, 17, 'b', th=7); c.line(43, 30, 20, 21, 'B', th=2)              # нижнее предплечье (справа-налево) и тень
c.line(12, 27, 38, 17, 'b', th=7); c.line(11, 30, 34, 21, 'B', th=2)              # верхнее предплечье и тень
c.ellipse(42, 27, 4, 3.5, 'c'); c.ellipse(12, 27, 4, 3.5, 'c')                     # кулаки
# голова: лысая, чёрный хохолок с хвостиком, серьга
c.ellipse(27, 8, 7, 7, 'b')
c.poly([(23, 4), (28, 1), (33, 2), (32, 5), (24, 6)], 'z'); c.line(32, 3, 40, 7, 'z', th=2)
c.put(24, 7, 'w'); c.put(25, 7, 'w'); c.put(29, 7, 'w'); c.put(30, 7, 'w')
c.put(24, 8, 'w'); c.put(25, 8, 'w'); c.put(29, 8, 'w'); c.put(30, 8, 'w')
c.poly([(25, 11), (30, 11), (30, 12), (25, 12)], 'B')                               # рот
c.ellipse(35, 11, 1.8, 2.5, 'y')                                                    # серьга
c.outline(between=set())
genie = [r.replace('k', '.') for r in c.rows()]
genie = [list(r) for r in genie]
for x, y in ((25, 8), (29, 8)): genie[y][x] = 'k'
genie = [''.join(r) for r in genie]

# ---------- нага (композитор) 56×60: женщина-змея, шесть рук с саблями, кольца бирюзового хвоста ----------
c = Canvas(56, 60)
# кольца хвоста
c.ellipse(28, 50, 26, 9, 'q'); c.ellipse(28, 52, 22, 5, 'Q')
c.ellipse(20, 42, 16, 6, 'q'); c.ellipse(20, 44, 12, 2.5, 'Q')
c.ellipse(28, 36, 8, 5, 'q')
c.line(6, 42, 50, 46, 'C', th=2); c.line(4, 50, 52, 50, 'C', th=2)               # блики по гребню колец
c.poly([(50, 44), (55, 34), (52, 30), (46, 42)], 'q'); c.ellipse(53, 31, 2.5, 2.5, 'C')   # кончик хвоста
# торс
c.poly([(21, 16), (35, 16), (36, 36), (20, 36)], 's')
c.poly([(20, 18), (36, 18), (36, 24), (20, 24)], 'M')                              # топ
c.ellipse(28, 30, 6, 3, 'S')                                                       # тень живота
# шесть рук: три пары от плеч, с саблями
arms = [((21, 18), (6, 8)), ((21, 22), (4, 22)), ((22, 26), (8, 36)),
        ((35, 18), (50, 8)), ((35, 22), (52, 22)), ((34, 26), (48, 36))]
for (x0, y0), (x1, y1) in arms: c.line(x0, y0, x1, y1, 's', th=3)
for (x0, y0), (x1, y1) in arms: c.ellipse(x1, y1, 2.5, 2.5, 'S')
for (x1, y1), (bx, by) in (((6, 8), (2, 0)), ((4, 22), (0, 10)), ((8, 36), (0, 28)),
                             ((50, 8), (54, 0)), ((52, 22), (55, 10)), ((48, 36), (55, 28))):
    c.line(x1, y1, bx, by, 'l', th=2)
# голова, чёрные волосы
c.ellipse(28, 9, 6, 7, 'z'); c.ellipse(28, 10, 4.5, 5, 's'); c.poly([(22, 8), (34, 8), (33, 4), (23, 4)], 'z')
c.poly([(22, 10), (20, 18), (24, 18)], 'z'); c.poly([(34, 10), (36, 18), (32, 18)], 'z')   # пряди
c.put(26, 10, 'w'); c.put(27, 10, 'w'); c.put(29, 10, 'w'); c.put(30, 10, 'w')
c.put(26, 11, 'w'); c.put(27, 11, 'w'); c.put(29, 11, 'w'); c.put(30, 11, 'w')
c.outline(between=set())
naga = [r.replace('k', '.') for r in c.rows()]
naga = [list(r) for r in naga]
for x, y in ((27, 11), (29, 11)): naga[y][x] = 'k'
naga = [''.join(r) for r in naga]

out = "/* ============================================================================\n"
out += "   view/sprites_tower_hd.js — существа Башни в крупной сетке (unit 2), стиль Б:\n"
out += "   без контурной линии, тона кладёт рисунок. Собирается скриптом dev/proto/tower_hd.py.\n"
out += "   ========================================================================== */\n(function () {\n  'use strict';\n  H3.Sprites.defineMany({\n"
out += block('gremlin', gremlin, 'гремлин: зелёный ушастый коротышка, бурая роба, цепь с чугунным ядром')
out += block('master_gremlin', None, 'мастер-гремлин: фиолетовая роба, красный колпак', base='gremlin', tint={'n': 'p', 'N': 'P'},
             extra=[(x, y, 'r') for y, (a, b) in ((0, (12, 21)), (1, (10, 23)), (2, (9, 24))) for x in range(a, b)] + [(x, 3, 'R') for x in range(8, 24)])
out += block('stone_gargoyle', stone_gargoyle, 'каменная гаргулья: серая крылатая статуя-демон, рога, клыки, когти, парит (композитор)')
out += block('obsidian_gargoyle', None, 'обсидиановая гаргулья: чёрный камень с фиолетовым отливом, светящиеся глаза', base='stone_gargoyle', tint={'e': 'u', 'E': 'z', 'l': 'p', 'w': 'A'})
out += block('stone_golem', stone_golem, 'каменный голем: приземистый истукан из песчаника, трещины, щели глаз')
out += block('iron_golem', None, 'железный голем: стальной корпус, заклёпки, огненные глаза', base='stone_golem', tint={'I': 'l', 'T': 'e', 'd': 'E'},
             extra=[(x, y, 'f') for y in (3, 4) for x in (18, 19, 20, 24, 25, 26)] + [(x, y, 'y') for y in (12, 13) for x in (5, 6, 39, 40)] + [(x, y, 'y') for y in (33, 34) for x in (12, 13, 31, 32)])
out += block('mage', mage, 'маг: синяя мантия, остроконечная шляпа со звездой, седая борода, посох с шаром')
out += block('arch_mage', None, 'архимаг: пурпурная мантия с золотой оторочкой, золотой посох, шар голубой', base='mage', tint={'b': 'p', 'B': 'P', 'n': 'y', 'N': 'Y', 'a': 'C', 'A': 'c'},
             extra=[(x, 14, 'y') for x in range(4, 26)] + [(x, y, 'y') for y in (50, 51) for x in range(2, 26)] + [(16, 3, 'y'), (17, 3, 'y'), (16, 4, 'y'), (17, 4, 'y')])
out += block('genie', genie, 'джинн: синий дух без ног, руки скрещены на груди, дымный хвост, серьга (композитор)')
out += block('master_genie', None, 'мастер-джинн: голубая кожа, белая дымка, золотой обруч на голове', base='genie', tint={'b': 'c', 'B': 'b', 'c': 'w', 'C': 'l', 'y': 'Y'},
             extra=[(x, y, 'Y') for y in (3, 4) for x in range(22, 33)])
out += block('naga', naga, 'нага: женщина-змея, шесть рук с саблями, кольца бирюзового хвоста (композитор)')
out += block('naga_queen', None, 'королева наг: пурпурная чешуя, красные клинки, золотая корона', base='naga', tint={'q': 'x', 'Q': 'P', 'C': 'p', 'l': 'r'},
             extra=[(x, y, 'y') for y in (3, 4) for x in range(23, 34)] + [(x, 2, 'y') for x in (23, 24, 27, 28, 32, 33)])
out += block('giant', giant, 'гигант: исполин в белой тоге через плечо, тёмные волосы, молния в поднятой руке')
out += block('titan', None, 'титан: синяя кожа, золотая тога-доспех и шлем, молния', base='giant', tint={'S': 'b', 'n': 'B', 'L': 'y', 'l': 'Y', 'D': 'y', 'N': 'Y'},
             extra=[(x, y, 'r') for y in (0, 1, 2) for x in range(28, 34)])
out += "  });\n})();\n"
p = os.path.join(os.path.dirname(__file__), '..', '..', 'js', 'view', 'sprites_tower_hd.js')
io.open(p, 'w', encoding='utf-8').write(out)
print('записан', os.path.relpath(p))
