/* ============================================================================
   view/sprites_castle_hd.js — существа Замка в крупной сетке (unit 2 = вдвое крупнее
   номинала), стиль Б: без контурной линии, тона кладёт рисунок, лёгкий свет по силуэту
   даёт конвейер «краска». Собирается скриптом dev/proto/castle_hd.py.
   ========================================================================== */
(function () {
  'use strict';
  H3.Sprites.defineMany({
    /* копейщик: шлем-котелок, кольчужные рукава, туника с гербом, копьё (40×48) */
    pikeman: {
      hd: true, unit: 2,
      rows: [
        '.................................kk.....',
        '................................klwk....',
        '................................kllek...',
        '................................kleek...',
        '...............kkkkkkkkk........kleEk...',
        '.............kkeeeeeeeeekk......kkEEk...',
        '............keeelllleeeeeek......kek....',
        '...........keeelllleeeeeeeek.....kek....',
        '...........keeeeeeeeeeeeEEek.....kNk....',
        '..........kkeeeeeeeeeeeeEEEkk....kNk....',
        '..........kEkEkEkEkEkEkEkEkEk....kNk....',
        '..........kkkkkkkkkkkkkkkkkkk....kTk....',
        '.............kSsssssssssSk.......kTk....',
        '.............kssswkkwsssSk.......kNk....',
        '.............ksskkkkkksssk.......kNk....',
        '.............ksssssssSsssk.......kNk....',
        '.............kSsssSSSssSSk.......kNk....',
        '..............kSssSSSSsSk........kNk....',
        '...............kkSSSSSkk.........kTk....',
        '.........kkkkkkkkkEEkkkkkkkkk....kTk....',
        '.......kkbbbbbbbbkEEkbbbbbbbbkk..kNk....',
        '......kbbbBbbbbbkkkkkbbbbbBbbbk..kNk....',
        '.....kbbBbkkkbbbbbbbbbbbkkkbBbbk.kNk....',
        '....kbbBbkeEekbbbyybbbbkeEekbBbbk.kNk...',
        '....kbBbkeEeEekbbyyybbbkEeEekbBbbkkNk...',
        '....kbBbkEeEeEkbyyYyybbkeEeEkbBbbkssk...',
        '....kbBbkeEeEekbbyyybbbkEeEekbBbksSsk...',
        '....kbBbkEeEeEkbbbyybbbkeEeEkbBbkSSsk...',
        '....kbBbbkeEekbbbbbbbbbbkeEekbBbkkkkk...',
        '....kbBBbbkkkbbbbbbbbbbbbkkkbbBBk.......',
        '.....kBBbbbbbbbbbbbbbbbbbbbbbBBk........',
        '.....kkBBBbbbbbbbbbbbbbbbbbBBBkk........',
        '......kNNNNNNNNNNNNNNNNNNNNNNNk.........',
        '......kNnnnnnnnnkyykknnnnnnnnNk.........',
        '......kNNNNNNNNNkyykkNNNNNNNNNk.........',
        '......kkkkkkkkkkkkkkkkkkkkkkkkk.........',
        '.......kbbbbbbbkk...kkbbbbbbbk..........',
        '.......kbbBbbbbk.....kbbbbBbbk..........',
        '.......kbBBbbbbk.....kbbbbBBbk..........',
        '.......kbBBBbbbk.....kbbbBBBbk..........',
        '.......kBBBBBbbk.....kbbBBBBBk..........',
        '.......kkkkkkkkk.....kkkkkkkkk..........',
        '......kNnnnnnnnNk...kNnnnnnnnNk.........',
        '......kNnnNNnnnNk...kNnnnNNnnNk.........',
        '.....kkNNNNNNNNNkk.kkNNNNNNNNNkk........',
        '.....kDDDDDDDDDDDk.kDDDDDDDDDDDk........',
        '.....kkkkkkkkkkkkk.kkkkkkkkkkkkk........',
        '........................................',
      ],
    },
    /* алебардщик: красная туника, лезвие алебарды */
    halberdier: { base: 'pikeman', tint: { b: 'r', B: 'R' }, extra: [[32, 3, 'l'], [31, 4, 'l'], [30, 5, 'e'], [31, 5, 'l'], [32, 6, 'l'], [31, 6, 'l']] },
    /* лучник: зелёный капюшон, туника, лук с тетивой, колчан (40×48) */
    archer: {
      hd: true, unit: 2,
      rows: [
        '.............GGGGGGGGGG.................',
        '...........GGGGGGGGGGGGGG...............',
        '..........GGGGGGGGGGGGGGGG..............',
        '..........GGGGGGGGGGGGGGGGG.............',
        '.........GGGGGGGGGGGGGGGGGG.............',
        '.........GGGGGSSSSSSSSGGGGG.............',
        '.........GGGGSssssssssSGGGG.....nN......',
        '.........GGGGSsssswkwsSGGGG.....wnN.....',
        '.........GGGGSssssssssSGGGG.....w.nN....',
        '.........GGGGSSssSSSssSGGGG.....w..nN...',
        '....ll...GGGGGSSSssssSGGGGG.....w..nN...',
        '....ll....GGGGGGSSSSGGGGGG......w...nN..',
        '....Nn.....GGGGGGGGGGGGGG.......w...nN..',
        '....Nn....HHHHHHHHHHHHHHHH......w...nN..',
        '....Nn....HHHHHHHHHHHHHHHH......w...nN..',
        '....Nn..HHHHhhhHHHHHHHHHHHHH....w...nN..',
        '....Nn.HHHHhhhhHHHHHHHHHHHHHH...w...nN..',
        '....Nn.HHHHhhhhHHHHHHHHHHHHHH...w...nN..',
        '....NnHHHHhhhhhHHHHHHHHHHHHHHH..w...nN..',
        '....NnHHHhhhhhhHHHHHHHHHHHHSSSSSS...nN..',
        '....NnHHHhhhhhhHHHHHHHHHHHHSSSSSS...nN..',
        '....NnHHHhhhhhhHHHHHHHHHHHHssssss...nN..',
        '....NnHHHhhhhhhHHHHHHHHHHHHssssss...nN..',
        '....NnHHHhhhhhhHHHHHHHHHHHHssssss...nN..',
        '....NnHHHhhhhhHHHHHHHHHHHHHSSSSSS...nN..',
        '....NnHHHHhhhhHHHHHHHHHHHHHHHH..w...nN..',
        '....NnHHHHhhhhHHHHHHHHHHHHHHHH..w...nN..',
        '....NnHHHHHhhHHHHHHHHHHHHHHHHH..w...nN..',
        '....Nn.HHHHHHHHHHHHHHHHHHHHHH...w..nN...',
        '....Nn.HHHHHHHHHHHHHHHHHHHHHH...w..nN...',
        '........DDDDDDDDDDDDDDDDDDDD....w..nN...',
        '........DDDDDDYYYYYYDDDDDDDD....w.nN....',
        '........HHHHHHHHHHHHHHHHHHHH....wnN.....',
        '........HHHHHHHHHHHHHHHHHHHH....nN......',
        '........NNnnnnnnnNNNnnnnnnnNN...........',
        '........NNnnnnnnnN.NNnnnnnnNN...........',
        '........NNnnnnnnnN.NNnnnnnnNN...........',
        '........NNnnnnnnnN..NnnnnnnNN...........',
        '........NNnnnnnnnN..NnnnnnnNN...........',
        '........NNnnnnnnnN..NnnnnnnNN...........',
        '........NNnnnnnnnN..NnnnnnnNN...........',
        '........NNNnnnnnNN..NNnnnnNNN...........',
        '........NNNNnnnNNN..NNNnnNNNN...........',
        '........NNNNNNNNNN..NNNNNNNNN...........',
        '........DDDDDDDDDD..DDDDDDDDD...........',
        '........DDDDDDDDDD..DDDDDDDDD...........',
        '.......DDDDDDDDDDDD.DDDDDDDDDD..........',
        '.......DDDDDDDDDDDD.DDDDDDDDDD..........',
      ],
    },
    /* стрелок: капюшон в тёмный дуб, серебряный наконечник, вторая стрела */
    marksman: { base: 'archer', tint: { G: 'R', h: 'H', H: 'u', D: 'z' }, extra: [[33, 5, 'l'], [33, 4, 'l'], [34, 4, 'l']] },
    /* грифон: крылья веером, львиное тело, орлиная голова (композитор) (60×56) */
    griffin: {
      hd: true, unit: 2,
      rows: [
        '............................................................',
        '..............................kkkkkkk.......................',
        '.......................kkkkkkknnnnnnnk......................',
        '............kkkkk.....knnnnnnnnnnnnnnnk.....................',
        '........kkkkNNNNNk....knnnnnnnkkkkknnnnk....................',
        '....kkkkNNNNNNNNNNk...knnnnnnnkTTTkkknnnk...................',
        '...kNNNNNNNNNNNNNNNk.knnnnnkkkTTTTTTkkknnk............k.....',
        '...kNNNNNNNNNNNNNNNNkknnnnnkTTTTTTTTTTkknnk..k.......kwk....',
        '..kNNNNNNNNNNNNNNNNNkknnkkkTTTTTTTTTTTTkkkkkkwk......kwk....',
        '..kNNNNNNkNNNNNNNNNNNnnnkTTTTTTTTTTTTTTTTTknkwwk....kwwk....',
        '..kNNNNNNkNNNNNNNNNNNnnnkTTTTTTTTTTTTTTTTTknnkwwk...kwwk....',
        '..kNNNNNNNNNNNNNNNNNnnnnkTTTTTTTTTTTTTTTTTknnkkwwk.kwwwk....',
        '...kNNNNNNNNNNNNNNNNnnnnkkTTTTTTTTTTTTTTTknnnnkwwwkkwwwk....',
        '....kkNNNNNNNNNNNNNNnnnnkTTTTTTTTTTTTTTTTknnnnkwwwwwwwwk....',
        '.....kNNNNNNNNNNNNNNnnnnkTTTTTTTTTTTTTTTTknnnnkkwwwwwwwk....',
        '.....kNNNNNNkNNNNNNNnnnnkTTTTTTTTTTTTTTTTknnnnkwwwwwwwwwk...',
        '.....kNNNNNNNNNNNNNNNnnnkTTTTTTTTTTTTTTTTknnnkwwwwwzwwwwwk..',
        '......kNNNNNNNNNNNNNNnnnkkTTTTTTTTTTTTTTTkknnkwwwwwzzwwwwk..',
        '.......kNNNNNNkNNNNNNNnnnkTTTTTTTTTTTTTTTTknnkwwwwwwwwwwyykk',
        '.......kNNNNNNNNNNNNNNnnnkkTTTTTTTTTTTTTTTknnkwwwwwwwwwwyyyy',
        '.......kNNNNNNNNNNNNNNnnnnkTTTTTTTTTTTTTTTkkkwwwwwwwwwwwyyyy',
        '.......kNNNNNNNNNNNNNNNnnnkTTTTTTTTTTTTTTwkwwwwwwwwwwwwwyyYY',
        '........kNNNNNNNNNNNNNNnnnkkTTTTTTTTTTTTwwwwwwwwwwwwwwwwyykk',
        '.........kkNNNNNNNNNNNNNnnnkTTTTTTTTTTTwwwwwwwwwwwwwwwwkkk..',
        '....kk....kNNNNNNNNNNNNNnnnkTTTTTTTTTTTwwwwwwwwwwwwwwwk.....',
        '...kNNk...kNNNNNNNNNNNNNNnnkkTTTTTTTTTTwwwwwwwwwwwkkkk......',
        '..kNNNNk...kNNNNNNNNNNNNNnnnkTTTTTTTTkkkwwwwwwwwwwwk........',
        '.kNNNNNNk...kkNNNNNNNNNNNNnnkkTTTTTkknnkwwwwwwwwwwwk........',
        '.kNNNNNNk....kNNNNNNNNNNNNnnnkTTTkknnnnkkwwwwwwwwwwk........',
        '..kNNNNTk.....kNNNNNNNNNNNnnnkTkknnnnnnnkwwwwwwwwwwk........',
        '...kNNTTTk.....kNNNNNNkkkkkknkknnnnnnnnnkkwwwwwwwwwk........',
        '....kkTTTTk....kNNNkkktttttknnnnnnnnnnnnnkkwwwwwwwk.........',
        '......kTTTTk....kNkttttttttknnkkkkkknnnnNnkkwwwwwk..........',
        '.......kTTTTk..ktkttttttttknnnkkttknnnnNNNnkkkwkkk..........',
        '........kTTTTkkttttttttttknnnnnkkknnnnnnNNnnkkkttk..........',
        '.........kTTTTktTTTTTTTTtknnnnnnkknnnnnnNNnktttttk..........',
        '..........kTTTTTTTTTTTTTTknnNNnnkknnNNnnnnkttttttk..........',
        '...........kTTTTTTTTTTTTTknNNNnnkknNNNnnkkttttttk...........',
        '...........kTTTTTTTTTTTTTkkNNNnktkkNNNnktttttttk............',
        '...........kTTTTTTTTTTTTTTkkNNnkttkkNNnkttttttk.............',
        '...........kTTTTTTTTTTTTTTTkTTkttttkkkkttttttk..............',
        '...........kTTTTTTTTTTTTTTTTTTTTTTTTTTtttttkk...............',
        '............kTTTTTTTTTTTTTTTTTTTTTTttttTtttttkk.............',
        '.............kTTTTTTTTTTTTTTTTTTTTTttttttktttttk............',
        '.............kTTTTTTTTTTTTTTTTTTTTTttttttktttttk............',
        '.............kTTTTTTTtttttTTTTTTTTTttttttktttttk............',
        '.............kTTTTTTTtttttTTTTTTTTTttttttktttttk............',
        '.............kTTTTTTktttttkkkkkkkkkttttttktttttk............',
        '.............kTTTTTTktttttk......kttttttkktttttk............',
        '............kTTTTTTkktttttk......kttttttkktttttk............',
        '............kTTTTTTkktttttk......kttttttkktttttk............',
        '...........kyyyyyyykyyyyyyyk....kyyyyyyykyyyyyyyk...........',
        '...........kyyyyyyykyyyyyyyk....kyyyyyyykyyyyyyyk...........',
        '...........kyyyyyyykyyyyyyyk....kyyyyyyykyyyyyyyk...........',
        '............kkkkkkk.kkkkkkk......kkkkkkk.kkkkkkk............',
        '............................................................',
      ],
    },
    /* королевский грифон: золотой окрас крыльев, алый гребень */
    royal_griffin: { base: 'griffin', tint: { n: 'y', N: 'Y', T: 'o' }, extra: [[50, 12, 'r'], [51, 11, 'r'], [52, 12, 'r']] },
    /* мечник: полные латы, забрало, табард с крестом, меч, каплевидный щит (48×50) */
    swordsman: {
      hd: true, unit: 2,
      rows: [
        '..................llllllll.............ll.......',
        '................lleeeeeeeell..........ewle......',
        '...............leeeeeeeeeeeel.........ewle......',
        '...............leeeeeeeeeeeel.........ewle......',
        '...............leeeeeeeeeeeel.........ewle......',
        '...............EEEEEEEEEEEEEE.........ewle......',
        '...............EzzzzzzzzzzzzE.........ewle......',
        '...............EEEEEEEEEEEEEE.........ewle......',
        '................EEeeeeeeeeEE..........ewle......',
        '.................EEEEEEEEEE...........ewle......',
        '............lllllllleeeelllllll.......ewle......',
        '..........lleeeeeeeeeeeeeeeeeell......ewle......',
        '..........lleeeeeeeeeeeeeeeeeell......ewle......',
        '...BBBBBBBBBBBeeeeeeeeeeeeeeeeeel.....ewle......',
        '...BBBBBBBBBBBeeeeeeeeeeeeeeeeeel.....ewle......',
        '...BbbbbbbbbbBEeeeeeeeeeeeeeEeeeel....ewle......',
        '...BbbbbbbbbbBEeeeeeeeeeeeeeEeeeel....ewle......',
        '...BbbbbbbbbbBEeeeRRRRRRReeeEeeeeel...ewle......',
        '...BbbbbbbbbbBEeeeRRRRRRReeeEeeeeel...ewle......',
        '...BbbbbybbbbBEeeeRrrwrrrReeEeeeeEEEEEewle......',
        '...BbbbbybbbbBEeeeRrrwrrrReeEeeeeEEEEEewle......',
        '...BbbbbybbbbBEeeeRrrwrrrReeEeeeeeeeeeewle......',
        '...BbbbbybbbbBEeeeRrrwrrrReeEeeeeeeeeeewle......',
        '...BbbbbybbbbBEeeeRwwwwwrReeEeeeeeeeeeewle......',
        '...BbbbbybbbbBEeeeRwwwwwrReeEeeeeeeeeeewle......',
        '...BbyyyyyyybBEeeeRrrwrrrReeEeeeeeeeeeewle......',
        '...BbyyyyyyybBEeeeRrrwrrrReeEeeeeeeeeeewle......',
        '...BbbbbybbbbBEeeeRrrwrrrReeEeeeeEEEEEewle......',
        '...BbbbbybbbbBEeeeRrrwrrrReeEeeeeEEEEEewle......',
        '...BbbbbybbbbBEeeeRRRRRRReeeEeeeeEEYYYYYYYYYY...',
        '...BbbbbybbbbBEeeeRRRRRRReeeEeeeeEEYYYYYYYYYY...',
        '...BbbbbybbbbBEEeeeeeeeeeeeEEeeeEEEyyyyyyyyyy...',
        '...BbbbbybbbbBEEeeeeeeeeeeeEEeeeEEEyyyyyyyyyy...',
        '...BbbbbybbbbBeEEeeeeeeeeeEEeeeEEE....NnnN......',
        '...BbbbbybbbbBeEEeeeeeeeeeEEeeeEEE....NnnN......',
        '...BbbbbybbbbBeeEEEEEEEEEEEeeEEEE.....NnnN......',
        '....BbbbbbbbBEEEEEEEEEEEEEEEEEEE......NnnN......',
        '.....BbbbbbBrrrrrrrrrrrrrrrrrrrr......NnnN......',
        '......BbbbBrrrrrrrrrrrrrrrrrrrrr......NnnN......',
        '.......BbB.RRRRRRRRRRRRRRRRRRRRR......YYYY......',
        '........B..leeeeeeeel..leeeeeeeel...............',
        '........B..leeeeeeeel..leeeeeeeel...............',
        '........B..lEeeeeeeEl..lEeeeeeeEl...............',
        '...........lEeeeeeeEl..lEeeeeeeEl...............',
        '...........lEeeeeeeEl..lEeeeeeeEl...............',
        '...........lEEeeeeEEl..lEEeeeeEEl...............',
        '...........lEEEEEEEEl..lEEEEEEEEl...............',
        '...........EEEEEEEEEE..EEEEEEEEEE...............',
        '..........EEEEEEEEEEEE.EEEEEEEEEEEE.............',
        '..........EEEEEEEEEEEE.EEEEEEEEEEEE.............',
      ],
    },
    /* крестоносец: золочёные латы, белый табард с красным крестом */
    crusader: { base: 'swordsman', tint: { e: 'y', E: 'Y', l: 'w', r: 'w', R: 'l' }, extra: [[22, 15, 'r'], [22, 16, 'r'], [22, 17, 'r'], [22, 18, 'r'], [22, 19, 'r'], [20, 17, 'r'], [21, 17, 'r'], [23, 17, 'r'], [24, 17, 'r']] },
    /* монах: ряса с капюшоном, верёвочный пояс, посох с кристаллом (44×48) */
    monk: {
      hd: true, unit: 2,
      rows: [
        '..................NNNNNNNN..................',
        '...............NNNNNNNNNNNNNN...............',
        '.............NNNNNNNNNNNNNNNNN.....aaaa.....',
        '............NNNNNNNNNNNNNNNNNNN...AAAAAA....',
        '............NNNNNDDDDDDDDDNNNNN...AAAAAA....',
        '............NNNNDDDSSSSSDDDNNNN....aaaa.....',
        '............NNNNDDSsssssSDDNNNN.....Tn......',
        '............NNNNDDSssswkwSDNNNN.....Tn......',
        '............NNNNDDSsssssssDNNNN.....Tn......',
        '............NNNNDDSSssSSSSDNNNN.....Tn......',
        '............NNNNNDDSSSSSDDNNNNN.....Tn......',
        '............NNNNNNDDDDDDDNNNNNN.....Tn......',
        '.............NNNNNNNNNNNNNNNNN......Tn......',
        '...........NNNnnnnnnnnnnnnnnnNNN....Tn......',
        '...........NNNnnnnnnnnnnnnnnnNNN....Tn......',
        '..........NNnnnnnTTTTTTTnnnnnnnNN...Tn......',
        '..........NNnnnnnTTTTTTTnnnnnnnNN...Tn......',
        '.........NNnnnnnnTTTTTTTnnnnnnnnNN..Tn......',
        '.........NNnnnnnnTTTTTTTnnnnnnnnNN..Tn......',
        '.........NnnnnnnnTTTTTTTnnnnnnnnnN..Tn......',
        '.........NnnnnnnnTTTTTTTnnnnnnnnnN..Tn......',
        '.........NnnnnNnnTTTTTTTnnnNnnnSSSSSTn......',
        '.........NnnnnNnnTTTTTTTnnnNnnnSSSSSTn......',
        '.........NnnnNNnnTTTTTTTnnnNNnnsssssTn......',
        '.........NnnnNNnnTTTTTTTnnnNNnnsssssTn......',
        '.........NnnnNnnnTTTTTTTnnnnNnnsssssTn......',
        '.........NnnnNnnnTTTTTTTnnnnNnnsssssTn......',
        '.........NnnnNnnnTTTTTTTnnnnNnnSSSSSTn......',
        '.........NnnnNnnnTTTTTTTnnnnNnnSSSSSTn......',
        '.........NnnnNNnnTTTTTTTnnnNNnnnnN..Tn......',
        '.........NnnnNNnnTTTTTTTnnnNNnnnnN..Tn......',
        '.........NnnnnNyyyyyyyyyyyyNnnnnnN..Tn......',
        '.........NnnnnNYyYyYyYyYyYyNnnnnnN..Tn......',
        '.........NnnnnnnnTTTTTTTnnnnnnnnnN..Tn......',
        '.........NnnnnnnnTTTTTTTnnnnnnnnnN..Tn......',
        '.........NnnnnnnnTTTTTTTnnnnnnnnnN..Tn......',
        '.........NnnnnnnnTTTTTTTnnnnnnnnnN..Tn......',
        '.........NnnnnnnnTTTTTTTnnnnnnnnnN..Tn......',
        '.........NnnnnnnnTTTTTTTnnnnnnnnnN..Tn......',
        '.........NnnnnnnnTTTTTTTnnnnnnnnnN..Tn......',
        '.........NnnnnnnnTTTTTTTnnnnnnnnnN..Tn......',
        '.........NNnnnnnnTTTTTTTnnnnnnnnNN..Tn......',
        '.........NNnnnnnnTTTTTTTnnnnnnnnNN..Tn......',
        '.........NNNnnnnnTTTTTTTnnnnnnnNNN..Tn......',
        '.........NNNNnnnnnTTTTTnnnnnnnNNNN..Tn......',
        '.........NNNNNNNNNNNNNNNNNNNNNNNNN..Tn......',
        '..........DDDDDDDD.......DDDDDDDD...........',
        '..........DDDDDDDD.......DDDDDDDD...........',
      ],
    },
    /* фанатик: белая ряса, золотой пояс, посох ярче */
    zealot: { base: 'monk', tint: { n: 'i', N: 'I', D: 'T' }, extra: [[35, 1, 'A'], [36, 1, 'A']] },
    /* кавалерист: конь в галопе, всадник в латах, копьё, плюмаж (композитор) (64×56) */
    cavalier: {
      hd: true, unit: 2,
      rows: [
        '...........................rrrrrrrr.............................',
        '...........................rrrrrrrr.............................',
        '...........................rrrr.rr..............................',
        '............................rr..................................',
        '................................................................',
        '............................eeeeee..................DDD.........',
        '...........................eeeeeeee................DDDDDN.......',
        '...........................eeeeeeee..............DDDDDDDN...llTT',
        '...........................eeeeeeee.............DDDDDDDDNTTTllll',
        '...........................ezzzzzze...........DDDDDDDDTTTTTTllT.',
        '...........................ezzzzzze..........DDDDDDTTTTTTTTTl...',
        '...........................eeeeeeee..........DDDTTTTTTTTTnnn....',
        '...........................eeeeeeee.........TTTTTTTTTTnnnnnnnn..',
        '..........................eeeeeeeeee.....TTTTTTTTTT..nnnnnknnnn.',
        '..........................eeeEEEEeee..TTTTTTTTTTDnnnnnnnnnnNNNN.',
        '.........................eeeEEEEEeeeeTTTTTTTT..nnnnnnnnnnnnNNNN.',
        '.........................eeeEEEETeeeeeeeT.....nnnnnnnnnnnnnNNNN.',
        '.........................eeEETTTTTeeeeeee.....nnnnnnnnnnnnnNNNN.',
        '.........................eTTTTTTTTTeeeeee.....nnnnnnnnnnnnnn....',
        '.........................TTTTTTTEEEee........nnnnnnnnnnnnn......',
        '.......................eeTTTTEEEEEEee.........nnnnnnnnnnnn......',
        '.......................eeeeeEEEEEEee..........nnnnnnnnnnnn......',
        '.......................eeeeeEEEEEEee..........nnnnnnnnnnnnn.....',
        '......................eeeeeeeEEEEee........nnnnnnnnnnnnnnn......',
        '......................eeeeeeeeeeee.......nnnnnnnnnnnnnnnnn......',
        '......................eeeeee.eeee.......nnnnnnnnnnnnnnnnnn......',
        '......................eeeeeerrrrrr.....nnnnnnnnnnnnnnnnnn.......',
        '.....................eeeeeerrrrrrrrrr..nnnnnnnnnnnnnnnnnn.......',
        '....................neeeeeeRRRRRRRrrrrnnnnnnnnnnnnnnnn..........',
        '..................nnneeeeeeRRRRRRRRRRrrnnnnnnnnnnnnnnn..........',
        '................nnnneeeeeeeRRRRRRRRRRRrnnnnnnnnnnnnnnn..........',
        '...........DD.NNNNNNeeeeeeRRRRRRRRRRRRnnnnnnnnnnnnnnnn..........',
        '..........DDDDNNNNNNeeeeeeRRRRRRRRRRRnnnnnnnnnnnnnnnn...........',
        '.........DDDDDNNNNNeeeeeeeRRRRRRRRnnnnnnnnnnnnnnnnnnn...........',
        '.........DDDDNNNNNNeeeeeennnnnnnnnnnnnnnnnnnnnnnnnnn............',
        '........DDDDDNNNNNNeeeeeeNnnnnnnnnnnnnnnnnnnnnnnnnn.............',
        '........DDDDNNNNNNNeeeeeeNnnnnnnnnnnnnnnnnnnnnnnn...............',
        '.......DDDDDNNNNNNeeeeeeeNNnnnnnnnnnnnnnnnnnnnnn................',
        '......DDDDDNNNNNNNeeeeeeNNNnnnnnnnnnnnnnnnnnnnn.................',
        '......DDDDNNNNNNNNEEEEeeNNNnnnnnnnnnnnnnnnnnnnn.................',
        '.....DDDDDNNNNNNNEEEEEEeNNNnnnnnnnnnnnnnnnnnnn..................',
        '....DDDDD..NNNNNNEEEEEENNNnnnnnnnnnnnnnnnnnn....................',
        '....DDDD....NNNNNNEEEENNNNNnnnnnnnnnnnnnnn.nnnnnn...............',
        '...DDDDD.....NNNNNNNNNNNNNNnnnnnnnnnnnnnn..nnnnnn...............',
        '...DDDD......NNNNNNNNNNNNNNnnnnnnnnnnnnnn..nnnnnn...............',
        '..DDDDD......NNNNNN..NNNNNN........nnnnnn..nnnnnn...............',
        '..DDDD.......NNNNNN..NNNNNN........nnnnnn..nnnnnn...............',
        '...DD........NNNNNN..NNNNNN........nnnnnn..nnnnnn...............',
        '.............NNNNNN..NNNNNN........nnnnnn..nnnnnn...............',
        '.............NNNNNN..NNNNNN........nnnnnn..nnnnnn...............',
        '.............NNNNNN..NNNNNN........nnnnnn..nnnnnn...............',
        '.............NNNNNN..NNNNNN........nnnnnn..nnnnnn...............',
        '............DDDDDDD.DDDDDDD.......DDDDDDD.DDDDDDD...............',
        '............DDDDDDD.DDDDDDD.......DDDDDDD.DDDDDDD...............',
        '............DDDDDDD.DDDDDDD.......DDDDDDD.DDDDDDD...............',
        '................................................................',
      ],
    },
    /* чемпион: белый конь, серебряные латы, синяя попона */
    champion: { base: 'cavalier', tint: { n: 'l', N: 'e', D: 'E', r: 'b', R: 'B', e: 'w', E: 'l' } },
    /* ангел: нимб, крылья с рядами перьев, золотые латы, светящийся меч (64×64) */
    angel: {
      hd: true, unit: 2,
      rows: [
        '..........................kkkkkkkkkkk...........................',
        '........................kkyyyyyyyyyyykk.........................',
        '.......................kyyyykkkkkkkyyyyk........................',
        '.......................kyykk.......kkyyk........................',
        '.......................kkk...........kkk........................',
        '.....kk....................kkkkkkkk....................kk.......',
        '....kwwk.................kkyyyyyyyykk.................kwwk......',
        '...kwwwwk...............kyyYyyyyyyyyyk...............kwwwwk.....',
        '..kwwwwwwk.............kyYyyyyyyyyyyyyk.............kwwwwwwk....',
        '..kwwwwwwwk............kyysssssssssyyyk............kwwwwwwwk....',
        '.kwwwLwwwwwk...........kysssswkkwssssyk...........kwwwwLwwwk....',
        '.kwwwLLwwwwwk..........kysskkkkkkkkssyk..........kwwwwLLwwwk....',
        '.kwwwLLLwwwwwk.........kySsssssSsssssyk.........kwwwwLLLwwwk....',
        '.kwwwLLLLwwwwwk........kkSsssSSSsssssSk........kwwwwLLLLwwwk....',
        '.kwwwLLLLLwwwwwk........kkSSssssssSSkk........kwwwwLLLLLwwwk....',
        '.kwwwLLLLLLwwwwwk.........kkSSSSSSkk.........kwwwwLLLLLLwwwk....',
        '.kwwlLLLLLLLwwwwwk..........kkkkkk..........kwwwwLLLLLLLlwwk....',
        '.kwwlLLLLLLLLwwwwwk.....kkkkkkkkkkkkkkk....kwwwwLLLLLLLLlwwk....',
        '.kwwlLLLLLLLLLwwwwwk..kkyyyyyyyyyyyyyyykk.kwwwwLLLLLLLLLlwwk....',
        '.kwwlLLLLLLLLLLwwwwwkkyyyyyYYyyyyYYyyyyyykwwwwLLLLLLLLLLlwwk....',
        '..kwlLLLLLLLLLLLwwwwkyyyyYYYYyyyyYYYYyyyykwwwLLLLLLLLLLLlwk.....',
        '..kwlLLLlLLLLLLLLwwwkyyyYYYYYyyyyYYYYYyyykwwLLLLLLLLlLLLlwk.....',
        '..kwlLLLlLLLLLLLLLwwkyyyyYYYYyykyyYYYYyyykwLLLLLLLLLlLLLlwk.....',
        '...kwLLLlLLLLLLLLLLwkyyyyyYYyykYkyYYyyyyykLLLLLLLLLLlLLLwk......',
        '...kwLLLlLLLLLLLLLLLkYyyyyyyykYYYkyyyyyyYkLLLLLLLLLLlLLLwk......',
        '...kwLLLlLLLlLLLLLLLkYYyyyyyykYYYkyyyyyYYkLLLLLLlLLLlLLLwk......',
        '....kLLLlLLLlLLLLLLLkYYYyyyyyykYkyyyyyYYYkLLLLLLlLLLlLLLk.......',
        '....kLLLlLLLlLLLLLLLkkYYYYyyyyykyyyyYYYYkkLLLLLLlLLLlLLLk.......',
        '....kLLLlLLLlLLLLLLLkkkYYYYYYYYYYYYYYYkkkLLLLLLlLLLlLLLk........',
        '.....kLLlLLLlLLLLLLkkkkkkkkkkkkkkkkkkkkkkkLLLLLLlLLLlLLk........',
        '.....kLLlLLLlLLLLLkkeeeeYYYYYYYYYYYkkeeeeekkLLLLLlLLLlLLk.......',
        '.....kLLlLLLlLLLLkkeeeEeeekNyyyyyyNkeeeEeeekkLLLLlLLLlLLk.......',
        '......kLlLLLlLLLLkeeeEEeeekNNNNNNNNkeeeEEeeekLLLLlLLLlLk........',
        '......kLlLLLlLLLkkeeeEEeeeekyyyyyykeeeEEeeeekkLLLlLLLlLk........',
        '......kLlLLLlLLkkeeeeEEeeeekyYYYYykeeeeEEeeeekkLLlLLLlLk........',
        '.......kLLLlLLkkeeeeeEEeeeekyYYYYykeeeeeEEeeeekkLlLLLLk.........',
        '.......kLLLlLkkeeeeeeEEeeeekyYYYYykeeeeeeEEeeeekkLLLLLk.........',
        '.......kLLLLkkeeeeeeeEEeeeekyYYYYykeeeeeeeEEeeeekkLLLLk.........',
        '........kLLkkEeeeeeeeEEeeeekyYYYYykeeeeeeeeEEeeeEkkLLk..........',
        '........kkkkEEeeeeeeeEEeeeekyYYYYykeeeeeeeeEEeeeEEkkkk..........',
        '...........kEEEeeeeeeEEeeeekyYYYYykeeeeeeeeEEeeEEEk.............',
        '...........kkEEEEeeeeEEeeeekyYYYYykeeeeeeeEEEEEEEkk.............',
        '............kkEEEEEEEEEEEEEkyYYYYykEEEEEEEEEEEEEkk..............',
        '.............kkkkkkkkkkkkklwwlYYYykkkkkkkkkkkkkk................',
        '..................kyyyyyyylwwlYYYykyyyyyyyyk....................',
        '..................kyYyyyyylwwlYYYykyyyyyyYyk....................',
        '..................kYYyyyyylwwlYYYykyyyyyyYYk....................',
        '..................kYYYyyyylwwlYYYykyyyyyYYYk....................',
        '..................kYYYYyyylwwlYYYykyyyyYYYYk....................',
        '..................kkkkkkkklwwlYYYykkkkkkkkkk....................',
        '..................kllllllk.ww.YYyykkkllllllk....................',
        '..................klllllll.ww.yyykkklllllllk....................',
        '..................kllllllk.ww.kkkkk.kllllllk....................',
        '..................kellllek.wl.......kellllek....................',
        '..................keellleek........keellleek....................',
        '..................keeelleek........keelleeek....................',
        '..................kEeeeeeEk........kEeeeeeEk....................',
        '..................kEEeeeEEk........kEEeeeEEk....................',
        '.................kkEEEEEEEkk......kkEEEEEEEkk...................',
        '.................kyyyyyyyyyk......kyyyyyyyyyk...................',
        '.................kkkkkkkkkkk......kkkkkkkkkkk...................',
        '................................................................',
        '................................................................',
        '................................................................',
      ],
    },
    /* архангел: белое золото лат, голубое свечение меча, лазурные перья */
    archangel: { base: 'angel', tint: { y: 'w', Y: 'y', L: 'c', l: 'c', e: 'l', E: 'e' } },
  });
})();
