/* ============================================================================
   view/sprites_castle.js — спрайты существ фракции Castle (Замок).
   14 существ: pikeman, halberdier, archer, marksman, griffin, royal_griffin,
   swordsman, crusader, monk, zealot, cavalier, champion, angel, archangel.
   Формат и палитра — docs/sprite-guide.md. Все смотрят вправо, якорь низ-центр.
   Подключать после js/view/sprites.js.
   ========================================================================== */
(function () {
  'use strict';

  H3.Sprites.defineMany({

    /* ---------- уровень 1: копейщик 20×24 — синяя туника, кольчуга, копьё ---------- */
    pikeman: {
      rows: [
        '................kk..',
        '.......kkkkk...kllk.',
        '......kleeeEk..kllk.',
        '.....kleeeeeEk.kllk.',
        '.....kEEEEEEEk..kek.',
        '......kssssSk...kn..',
        '......kssksSk...kn..',
        '......kSsssSk...kn..',
        '.......kkkkk....kn..',
        '......kbbbbBk...kn..',
        '....kkebbbbBekk.kn..',
        '...kekbbbbBkeesskn..',
        '...kskbbbbBkkkkkkn..',
        '...kkkbbbbBk....kn..',
        '.....kBbbbBk....kn..',
        '.....kBBBBBk....kn..',
        '.....kleeeEk....kn..',
        '.....keeeEEk....kn..',
        '....kkkkkkkkk...kn..',
        '....knNk.knNk...kn..',
        '....knNk.knNk...kn..',
        '....knNk.knNk...kn..',
        '...kkNNk.kNNkk..kn..',
        '...kkkkk.kkkkk..kk..',
      ],
    },
    /* алебардщик: красная туника + лезвие топора на древке */
    halberdier: {
      base: 'pikeman',
      tint: { b: 'r', B: 'R' },
      extra: [
        [14, 1, 'k'],
        [13, 2, 'k'], [14, 2, 'e'], [15, 2, 'e'],
        [12, 3, 'k'], [13, 3, 'e'], [14, 3, 'e'], [15, 3, 'e'],
        [13, 4, 'k'], [14, 4, 'e'], [15, 4, 'k'],
        [14, 5, 'k'], [15, 5, 'k'],
      ],
    },

    /* ---------- уровень 2: лучник 22×22 — зелёный капюшон, оливковый плащ, лук ---------- */
    archer: {
      rows: [
        '.......kkkkk..........',
        '......kggggGk.........',
        '.....kgggggGGk........',
        '.....kggGsssGk....k...',
        '.....kggGskSGk...knk..',
        '.....kgGGsssGk...lknk.',
        '......kGGkkkk....l.knk',
        '.....kkHHHHHkk...l.knk',
        '....kHHHHHHHHjk..l.kNk',
        '...kHHkknnnkkjk..l.kNk',
        '...kHkknnnnkkjknnnsssk',
        '...kHk.knnnnkkkkkkkkkk',
        '...kkk.kNnnnnk...l.kNk',
        '.......kNnnnNk...l.knk',
        '.......kNNNNNk...lknk.',
        '.......kkkkkkk...knk..',
        '.......kdk.kdk...kk...',
        '.......kdk.kdk........',
        '.......kdk.kdk........',
        '......kkNk.kNkk.......',
        '......kkkk.kkkk.......',
        '......................',
      ],
    },
    /* стрелок: красный плащ + ложе арбалета */
    marksman: {
      base: 'archer',
      tint: { H: 'r', j: 'R' },
      extra: [
        [12, 9, 'k'], [13, 9, 'k'], [14, 9, 'k'], [15, 9, 'k'], [16, 9, 'k'], [17, 9, 'k'],
        [13, 10, 'N'], [14, 10, 'N'], [15, 10, 'N'], [16, 10, 'N'], [17, 10, 'N'],
        [15, 8, 'k'], [16, 8, 'k'], [17, 8, 'k'],
      ],
    },

    /* ---------- уровень 3: грифон 24×24 — орлиная голова, крылья, львиное тело ---------- */
    griffin: {
      rows: [
        '.....kk...kk............',
        '....kTnk.kTnk...........',
        '...kTnnnkkTnnk..........',
        '...knnnnnnnnnnk.........',
        '..kTnnnnnnnnnnk.........',
        '..knnnnnnNnnnnk.........',
        '..kNnnnnnnNnnnk.kkk.....',
        '..kNNnnnnnnNnnkkwwlk....',
        '...kNNnnnnnnNnkwwwwlk...',
        '....kNNnnnnnNkwwlkwlkk..',
        '.....kNNnnnnkwwwwwlkyk..',
        '......kkkkkkkwwwwlkYYk..',
        '.......kttttttwwlkkkk...',
        '......ktttttttttlk......',
        '.....kSttttttttttk......',
        '...kkkSSttttttttSk......',
        '..kSSkkSttttttttSk......',
        '..kSk.kSSttttSSStk......',
        '..kk..kSStkkkkkSttk.....',
        '......kSSk...kSttSk.....',
        '......ktSk...kkSSSk.....',
        '.....kkkkk....kkkkk.....',
        '........................',
        '........................',
      ],
    },
    /* королевский грифон: золотые крылья */
    royal_griffin: {
      base: 'griffin',
      tint: { n: 'y', N: 'Y', T: 'f' },
      extra: [[17, 6, 'y'], [16, 5, 'y'], [18, 5, 'y']],
    },

    /* ---------- уровень 4: мечник 22×24 — стальной доспех, щит с крестом, меч ---------- */
    swordsman: {
      rows: [
        '...............kk.....',
        '.......kkkkk...klk....',
        '......kleeeEk..klk....',
        '.....kleeeeeEk.klk....',
        '.....kEeeeeeEk.klk....',
        '.....kEekkkkEk.klk....',
        '.....kEeeeeeEk.klk....',
        '......kEEEEEk..klk....',
        '.......kkkkk..kklkk...',
        '....kkleeeeEkkkyyyyk..',
        '...kleekeeeEkeesskyk..',
        '..klrlkeeeeEkkkkkkNk..',
        '..klrlkeeeeEk....kNk..',
        '..krrrkEeeeEk....kkk..',
        '..klrlkEEEEEk.........',
        '..klrlkEeeeEk.........',
        '...kkkkEeeeEk.........',
        '......kEEEEEk.........',
        '......kkkkkkk.........',
        '......kekk.kek........',
        '......kekk.kek........',
        '......kEkk.kEk........',
        '.....kkEkk.kEkk.......',
        '.....kkkkk.kkkkk......',
      ],
    },
    /* крестоносец: белая накидка с красным крестом, два меча */
    crusader: {
      rows: [
        '...............kk.....',
        '.......kkkkk...klk....',
        '......kleeeEk..klk....',
        '.....kleeeeeEk.klk....',
        '.....kEeeeeeEk.klk....',
        '.....kEekkkkEk.klk....',
        '.....kEeeeeeEk.klk....',
        '......kEEEEEk..klk....',
        '.......kkkkk..kklkk...',
        '....kkwwwrwwkkkyyyyk..',
        '...keekwwrwwlkeesskyk.',
        '..keekkrrrrrlkkkkkkNk.',
        '..kskkkwwrwwlk....kNk.',
        '..kkkkkwwrwwlk....kkk.',
        '.kkyyk.wwwwwlk........',
        '.kNk...kwwwwlk........',
        '.kNk...kllllLk........',
        'kklk...kkkkkkk........',
        'klk....kekk.kek.......',
        'klk....kekk.kek.......',
        'kk.....kEkk.kEk.......',
        '......kkEkk.kEkk......',
        '......kkkkk.kkkkk.....',
        '......................',
      ],
    },

    /* ---------- уровень 5: монах 24×26 — коричневая ряса, посох с шаром ---------- */
    monk: {
      rows: [
        '.................kAk....',
        '................kAAAk...',
        '................kAaAk...',
        '.................kAk....',
        '........kkkkkk...kTk....',
        '.......ktnnnnNk..kTk....',
        '......ktnnnnnnNk.kTk....',
        '......knnNsssNNk.kTk....',
        '......knnNskSNNk.kTk....',
        '......knnNsssNNk.kTk....',
        '......kNnNSSSNNk.kTk....',
        '.......kNNkkkNk..kTk....',
        '......kktnnnnnkk.kTk....',
        '.....ktnnnnnnnNk.kTk....',
        '....ktnnknnnnnNknnsskk..',
        '....ktnknnnnnnNkkkkkkk..',
        '....kskknnnnnnNk.kTk....',
        '....kkkknnnnnnNk.kTk....',
        '......ktnnnnnnNk.kTk....',
        '......ktnnnnnnNk.kTk....',
        '......ktnnnnnnNNk.kTk...',
        '.....ktnnnnnnnNNk.kTk...',
        '.....ktnnnnnnnNNk.kTk...',
        '.....kNnnnnnnnNNk.kTk...',
        '.....kNNNNNNNNNNk.kTk...',
        '.....kkkkkkkkkkkk.kkk...',
      ],
    },
    /* фанатик: белая ряса, золотой посох, ледяной шар */
    zealot: {
      base: 'monk',
      tint: { n: 'l', N: 'e', t: 'w', T: 'y', a: 'c', A: 'w' },
      extra: [[8, 4, 'y'], [9, 4, 'y'], [10, 4, 'y'], [11, 4, 'y'], [12, 4, 'y']],
    },

    /* ---------- уровень 6: кавалерист 28×28 — всадник на коне с копьём ---------- */
    cavalier: {
      rows: [
        '..........................kk',
        '........kkkkk............klk',
        '.......kleeeEk..........klk.',
        '......kleeeeeEk........klk..',
        '......kEeeeeeEk.......kek...',
        '......kEekkkkEk......kn.....',
        '......kEeeeeeEk.....kn......',
        '.......kEEEEEk.....kn.......',
        '.....kkkkkkkkk....kn.kk.kk..',
        '....kleeeeeeEkk..knktnknnk..',
        '...kleekeeeeEkeeknkttnnnnnnk',
        '...kekkkeeeeEkssk.knnnnknnnk',
        '...kskkkEeeeeEkkkknnnnnnnNNk',
        '...kkkkbbbbbbbbk.knnnnNkkNNk',
        '..kktnkbbBbbbbbknnnnnNk.kkk.',
        '.kNnnnkbbBkekbbknnnnnnk.....',
        '.kNkkknnnnkekknnnnnnnnnk....',
        '.kNk.knnnnkekknnnnnnnnnNk...',
        '.kk..knnnnkEkknnnnnnnnnNk...',
        '.....knnnnkkkknnnnnnnnnNk...',
        '.....kNnnnnnnnnnnnnnnnnNk...',
        '......kNnnkkkkkkkknnnNNk....',
        '......kNnkkNk..kNkkNnnk.....',
        '......kNnk.kNk.kNk.kNnk.....',
        '......kNnk.kNk.kNk.kNnk.....',
        '.....kkNnk.kNk.kNkkNnk......',
        '.....kNNkk.kkk.kkkkNNkk.....',
        '.....kkkk.........kkkk......',
      ],
    },
    /* чемпион: золотая броня и плюмаж */
    champion: {
      base: 'cavalier',
      tint: { e: 'y', E: 'Y', l: 'i' },
      extra: [
        [9, 0, 'k'], [10, 0, 'k'], [11, 0, 'k'],
        [8, 1, 'r'], [9, 1, 'r'], [10, 1, 'r'], [11, 1, 'r'], [12, 1, 'k'],
        [7, 2, 'k'], [8, 2, 'R'], [9, 2, 'r'],
        [6, 3, 'k'], [7, 3, 'R'],
      ],
    },

    /* ---------- уровень 7: ангел 32×32 — белые крылья, золотые доспехи, меч ---------- */
    angel: {
      rows: [
        '.........kk.............kk......',
        '........kwwk...........kwwk.....',
        '.......kwwwwk.........kwwwwk....',
        '......kwwwwwlk.......kwwwwwlk...',
        '.....kwwwwwwlk.......kwwwwwwlk..',
        '....kwwwwwwwlk.kkkkk.kwwwwwwlk..',
        '....kwwwwwwwlkkttttkkkwwwwwwlk..',
        '...kwwwwwwwwlktttttttkwwwwwwlk..',
        '...kwwwwwwwwlktttssstkwwwwwwlkk.',
        '...kwwwwwwwlkktssksStkwwwwwwlkek',
        '...kwwwwwwwlk.ksSsssSkkwwwwwlkek',
        '...kwwwwwwlk..kkkkkkkkkkwwwwlkek',
        '....kwwwwlk..kyyyyyyYkkkkwwwlkek',
        '....kwwwlk..kiyyyyyyyYkkkkkklkek',
        '.....kwlk..kiykyyyyyyYkkyyyyykek',
        '.....kwlk..kykkyyyyyyYkkyyyykssk',
        '......kk...kkkkyyyyyyyYkkkkkkkkk',
        '...........kskkyyyyyyYk...kkk...',
        '...........kkkkYYYYYYYk...kek...',
        '.............kiiiiiiIk....kkk...',
        '.............kiiiiiiIk..........',
        '.............kiiiiiiIk..........',
        '.............kiiiiiiIIk.........',
        '............kiiiiiiiIIk.........',
        '............kIIIIIIIIIk.........',
        '............kkkkkkkkkkk.........',
        '.............kyyk.kyyk..........',
        '.............kyYk.kyYk..........',
        '.............kyYk.kyYk..........',
        '............kkYYk.kYYkk.........',
        '............kkkkk.kkkkk.........',
        '................................',
      ],
    },
    /* архангел: золотые крылья, платиновые доспехи, светящийся меч, нимб */
    archangel: {
      base: 'angel',
      tint: { w: 'y', l: 'Y', y: 'L', Y: 'e', e: 'c', E: 'C' },
      extra: [
        [15, 3, 'y'], [16, 3, 'y'], [17, 3, 'y'], [18, 3, 'y'],
        [14, 4, 'y'], [19, 4, 'y'],
      ],
    },
  });
})();
