/* ============================================================================
   view/sprites_rampart_hd.js — существа Оплота в крупной сетке (unit 2), стиль Б:
   без контурной линии, тона кладёт рисунок. Собирается скриптом dev/proto/rampart_hd.py.
   ========================================================================== */
(function () {
  'use strict';
  H3.Sprites.defineMany({
    /* кентавр: гнедое конское тело, торс в зелёной тунике, копьё (композитор) (44×48) */
    centaur: {
      hd: true, unit: 2,
      rows: [
        '.......................................ll...',
        '.......................................llN..',
        '......................................llllN.',
        '...........................NNNNNNNN...lllll.',
        '..........................NNNNNNNNNN.llllll.',
        '..........................NNNNNNNNNN.lllllll',
        '..........................sNNNNNNNNs...NNNN.',
        '..........................ssssssssss...NNNN.',
        '..........................ssssssskws...NNNN.',
        '..........................ssssssssss...NNNN.',
        '...........................ssssssss....NNNN.',
        '...........................ssssssss....NNNN.',
        '.............................ssss......NNNN.',
        '.............................ssss.....sssNN.',
        '............................gssssg...sssssN.',
        '...........................gggggggg.ssssssN.',
        '..........................gggggggggssssssNN.',
        '.........................ssggggggggsss.NNNN.',
        '........................sssggggggggss..NNNN.',
        '........................sssggggggggg...NNNN.',
        '.......................sssgggggggggg..NNNNN.',
        '......................ssssgggggggggg..NNNN..',
        '......................sss.gggggggggg..NNNN..',
        '.....................sss..gggggggggg..NNNN..',
        '.....................sss..gggggggggg..NNNN..',
        '.....................ss...gggggggggg..NNNN..',
        '...........................gggggggg...NNNN..',
        '.........................yyyyyyyyyyyy.NNNN..',
        '.............NNNNNNNNNN..yyyyyyyyyyyy.NNNN..',
        '......nnnnnNNNNNNNNNNNNNNNNNNNNNNNN...NNNN..',
        '....nnnnnnnnnNNNNNNNNNNNNNNNNNNNNNNN..NNNN..',
        '....nDDnnnnnnnNNNNNNNNNNNNNNNNNNNNNN..NNNN..',
        '...nDDDDnnnnnnnNNNNNNNNNNNNNNNNNNNNN..NNNN..',
        '...nDDDDnnnnnnnNNNNNNNNNNNNNNNNNNNNN..NNNN..',
        '...DDDDDnnnnnnnNNNNNNNNNNNNNNNNNNNN...NNNN..',
        '...DDDDnnnnnnnnNNNNNNNNNNNNNNNNNNNN...NNNN..',
        '...DDDDnnnnnnnNNNNNNNNNNNNNNNNNNNN....NNNN..',
        '..DDDDnnnnnnnnNNNNNNNNNNNNNNNNNN......NNNN..',
        '..DDDD.nnnnnNNNNNNNNNNNNNNNNN.........NNNN..',
        '.DDDDDNNNNNNNnnnnnNNNNNNNNNN..nnnnn....NN...',
        '.DDDD.NNNNNNNnnnnnNNNNNNNNNN..nnnnn.........',
        '.DDDD.NNNNN..nnnnnNNNNNNNNNN..nnnnn.........',
        'DDDD..NNNNN..nnnnn.....NNNNN..nnnnn.........',
        'DDDD..NNNNN..nnnnn.....NNNNN..nnnnn.........',
        'DDDD..NNNNN..nnnnn.....NNNNN..nnnnn.........',
        'DDD..DDDDDD.DDDDDD....DDDDDD.DDDDDD.........',
        'DDD..DDDDDD.DDDDDD....DDDDDD.DDDDDD.........',
        'DD...DDDDDD.DDDDDD....DDDDDD.DDDDDD.........',
      ],
    },
    /* капитан кентавров: стальной панцирь и шлем, красный плюмаж, алый плащ */
    centaur_captain: { base: 'centaur', tint: { g: 'e', G: 'E' }, extra: [[28, 0, 'r'], [29, 0, 'r'], [30, 0, 'r'], [31, 0, 'r'], [32, 0, 'r'], [33, 0, 'r'], [28, 1, 'r'], [29, 1, 'r'], [30, 1, 'r'], [31, 1, 'r'], [32, 1, 'r'], [33, 1, 'r'], [28, 2, 'r'], [29, 2, 'r'], [30, 2, 'r'], [31, 2, 'r'], [32, 2, 'r'], [33, 2, 'r'], [27, 3, 'e'], [28, 3, 'e'], [29, 3, 'e'], [30, 3, 'e'], [31, 3, 'e'], [32, 3, 'e'], [33, 3, 'e'], [34, 3, 'e'], [26, 4, 'e'], [27, 4, 'e'], [28, 4, 'e'], [29, 4, 'e'], [30, 4, 'e'], [31, 4, 'e'], [32, 4, 'e'], [33, 4, 'e'], [34, 4, 'e'], [35, 4, 'e'], [26, 5, 'e'], [27, 5, 'e'], [28, 5, 'e'], [29, 5, 'e'], [30, 5, 'e'], [31, 5, 'e'], [32, 5, 'e'], [33, 5, 'e'], [34, 5, 'e'], [35, 5, 'e'], [27, 6, 'e'], [28, 6, 'e'], [29, 6, 'e'], [30, 6, 'e'], [31, 6, 'e'], [32, 6, 'e'], [33, 6, 'e'], [34, 6, 'e'], [23, 15, 'r'], [24, 15, 'r'], [25, 15, 'r'], [20, 16, 'r'], [21, 16, 'r'], [22, 16, 'r'], [23, 16, 'r'], [24, 16, 'r'], [25, 16, 'r'], [20, 17, 'r'], [21, 17, 'r'], [22, 17, 'r'], [23, 17, 'r'], [24, 17, 'r'], [25, 17, 'r'], [20, 18, 'r'], [21, 18, 'r'], [22, 18, 'r'], [23, 18, 'r'], [24, 18, 'r'], [25, 18, 'r'], [20, 19, 'r'], [21, 19, 'r'], [22, 19, 'r'], [23, 19, 'r'], [24, 19, 'r'], [25, 19, 'r'], [20, 20, 'r'], [21, 20, 'r'], [22, 20, 'r'], [23, 20, 'r'], [24, 20, 'r'], [25, 20, 'r'], [20, 21, 'r'], [21, 21, 'r'], [22, 21, 'r'], [23, 21, 'r'], [24, 21, 'r'], [25, 21, 'r'], [20, 22, 'r'], [21, 22, 'r'], [22, 22, 'r'], [23, 22, 'r'], [24, 22, 'r'], [25, 22, 'r'], [19, 23, 'r'], [20, 23, 'r'], [21, 23, 'r'], [22, 23, 'r'], [23, 23, 'r'], [24, 23, 'r'], [25, 23, 'r'], [19, 24, 'r'], [20, 24, 'r'], [21, 24, 'r'], [22, 24, 'r'], [23, 24, 'r'], [24, 24, 'r'], [25, 24, 'r'], [19, 25, 'r'], [20, 25, 'r'], [21, 25, 'r'], [22, 25, 'r'], [23, 25, 'r'], [24, 25, 'r'], [25, 25, 'r'], [19, 26, 'r'], [20, 26, 'r'], [21, 26, 'r'], [22, 26, 'r'], [23, 26, 'r'], [24, 26, 'r'], [25, 26, 'r'], [19, 27, 'r'], [20, 27, 'r'], [21, 27, 'r'], [22, 27, 'r'], [23, 27, 'r'], [24, 27, 'r'], [25, 27, 'r'], [19, 28, 'r'], [20, 28, 'r'], [21, 28, 'r'], [22, 28, 'r'], [23, 28, 'r'], [19, 29, 'r'], [20, 29, 'r']] },
    /* гном: коренастый, рыжая борода до пояса, кольчуга, тяжёлый топор (37×44) */
    dwarf: {
      hd: true, unit: 2,
      rows: [
        '...........nnnnnnnnnn................',
        '.........nnnnnnnnnnnnnn..............',
        '........nnnnnnnnnnnnnnnn.......dd....',
        '........nnNNNNNNNNNNNNnn.......ddle..',
        '........nnssssssssssssnn.......ddlle.',
        '........nnssssssssssssnn.......ddllle',
        '........nnssSwwsswwSssnn.......ddllle',
        '........nnssSwksskwSssnn.......ddllle',
        '........nnsssssSSsssssnn.......ddllle',
        '........nnssOOOOOOOOssnn.......ddlle.',
        '..........OOOOooooOOOO.........ddle..',
        '...eeeeeOOOOOOooooOOOOOOeeeee..dd....',
        '...eeeeeOOOOOOooooOOOOOOeeeee..dd....',
        '..EeeeeEeOOOOOooooOOOOOeEeeeeE.dd....',
        '..EeeeeEeOOOOOooooOOOOOeEeeeeE.dd....',
        '..EeeeeEeOOOOOooooOOOOOeEeeeeE.dd....',
        '..EeeeeEeOOOOOooooOOOOOeEeeeeE.dd....',
        '..EeeeeEeOOOOOoooOOOOOeeEeeeeE.dd....',
        '..EeeeeEeOOOOOoooOOOOOeeEeeeeE.dd....',
        '..EeeeeEeeOOOOoooOOOOeeeEeeeeE.dd....',
        '..EeeeeEeeOOOOoooOOOOeeeEeeeeE.dd....',
        '..EeeeeEeeeOOOoooOOOeeeeEeeeeE.dd....',
        '..EeeeeEeeeOOOoooOOOeeeeEeeeeE.dd....',
        '..EeeeeEeeeeOOoooOOeeeeeEeeeessdd....',
        '..EeeeeEeeeeOOoooOOeeeeeEeeeessdd....',
        '..EeeeeEeeeeeOOoOOeeeeeeEeeeessdd....',
        '..EeeeeEeeeeeOOoOOeeeeeeEeeeessdd....',
        '..EeeeeEeeeeeeeeeeeeeeeeEeeeessdd....',
        '..EeeeeEeeeeeeeeeeeeeeeeEeeeessdd....',
        '..EeeeeEeeeeeeeeeeeeeeeeEeeeessdd....',
        '..EeeeeEeeeeeeeeeeeeeeeeEeeeessdd....',
        '..EssssEeeeeeeeeeeeeeeeeEeeeeE.dd....',
        '..EssssEeeeeeeeeeeeeeeeeEeeeeE.dd....',
        '...eeeeeeeeeeeeeeeeeeeeeeeee...dd....',
        '.......NNNNNNNNNNNNNNNNN.......dd....',
        '.......dddddddd.ddddddd........dd....',
        '.......dddddddd.ddddddd........dd....',
        '.......dddddddd.ddddddd........dd....',
        '.......dddddddd.ddddddd..............',
        '.......dddddddd.ddddddd..............',
        '.......dddddddd.ddddddd..............',
        '.......dddddddd.ddddddd..............',
        '......DDDDDDDDD.DDDDDDDD.............',
        '......DDDDDDDDD.DDDDDDDD.............',
      ],
    },
    /* боевой гном: синий шлем, стальная броня, двусторонний топор */
    battle_dwarf: { base: 'dwarf', tint: { e: 'C', E: 'B' }, extra: [[11, 0, 'b'], [12, 0, 'b'], [13, 0, 'b'], [14, 0, 'b'], [15, 0, 'b'], [16, 0, 'b'], [17, 0, 'b'], [18, 0, 'b'], [19, 0, 'b'], [20, 0, 'b'], [9, 1, 'b'], [10, 1, 'b'], [11, 1, 'b'], [12, 1, 'b'], [13, 1, 'b'], [14, 1, 'b'], [15, 1, 'b'], [16, 1, 'b'], [17, 1, 'b'], [18, 1, 'b'], [19, 1, 'b'], [20, 1, 'b'], [21, 1, 'b'], [22, 1, 'b'], [8, 2, 'b'], [9, 2, 'b'], [10, 2, 'b'], [11, 2, 'b'], [12, 2, 'b'], [13, 2, 'b'], [14, 2, 'b'], [15, 2, 'b'], [16, 2, 'b'], [17, 2, 'b'], [18, 2, 'b'], [19, 2, 'b'], [20, 2, 'b'], [21, 2, 'b'], [22, 2, 'b'], [23, 2, 'b'], [8, 3, 'B'], [9, 3, 'B'], [10, 3, 'B'], [11, 3, 'B'], [12, 3, 'B'], [13, 3, 'B'], [14, 3, 'B'], [15, 3, 'B'], [16, 3, 'B'], [17, 3, 'B'], [18, 3, 'B'], [19, 3, 'B'], [20, 3, 'B'], [21, 3, 'B'], [22, 3, 'B'], [23, 3, 'B'], [29, 3, 'l'], [30, 3, 'l'], [28, 4, 'l'], [29, 4, 'l'], [30, 4, 'l'], [27, 5, 'l'], [28, 5, 'l'], [29, 5, 'l'], [30, 5, 'l'], [27, 6, 'l'], [28, 6, 'l'], [29, 6, 'l'], [30, 6, 'l'], [27, 7, 'l'], [28, 7, 'l'], [29, 7, 'l'], [30, 7, 'l'], [27, 8, 'l'], [28, 8, 'l'], [29, 8, 'l'], [30, 8, 'l'], [28, 9, 'l'], [29, 9, 'l'], [30, 9, 'l'], [29, 10, 'l'], [30, 10, 'l']] },
    /* лесной эльф: каштановые волосы, острые уши, зелёная туника и плащ, длинный лук, колчан (40×48) */
    wood_elf: {
      hd: true, unit: 2,
      rows: [
        '..............nnnnnnnn..................',
        '............nnnnnnnnnnnn................',
        '............nnnnnnnnnnnn................',
        '............nnssssssssnn................',
        '............nnssssssssnn......TN........',
        '............nnsSwwswwSnn.......TN.......',
        '.........sssnnsSwkskwSnnsss....lTN......',
        '..........ssnnssssssssnnss.....l.TN.....',
        '.....ll.....nnsssSSsssnn.......l..TN....',
        '.....ll.....nnssssssssnn.......l..TN....',
        '.....NT.....nnnssssssnnn.......l...TN...',
        '.....NT......nnnssssnnn........l...TN...',
        '.....NT........GssssG..........l....TN..',
        '.....NT....ggggGGssGGgggg......l....TN..',
        '.....NT....ggggGGssGGgggg......l....TN..',
        '.....NT...gggggggGGgggggggg....l....TN..',
        '.....NT..GgggggGggggggggggg....l....TN..',
        '.....NT..GgggggGggggggggggg....l....TN..',
        '.....NT.GGgggggGggggggggggg....l....NN..',
        '.....NT.GGGggggGgggggggggggSSSSSSSSSNN..',
        '.....NT.GGGggggGgggggggggggSSSSSSSSSNN..',
        '.....NT.GGGggggGgggggggggggsssssssssNN..',
        '.....NT.GGGggggGgggggggggggsssssssssNN..',
        '.....NT.GGGggggGgggggggggggsssssssssNN..',
        '.....NT.GGGggggGgggggggggggSSSSSSSSSNN..',
        '.....NT.GGGggggGggggggggggg....l....NN..',
        '.....NT.GGGggggGggggggggggg....l....NN..',
        '........GGGggggGggggggggggg....l....TN..',
        '........GGGgNNNNNNNNNNNNNNN....l...TN...',
        '........GGGgNNNNNNNNNNNNNNN....l...TN...',
        '........GGGgggggggggggggggg....l...TN...',
        '........GGGgggggggggggggggg....l..TN....',
        '........GGGgggggggggggggggg....l..TN....',
        '........GGGgggggggggggggggg....l..TN....',
        '............NNNNNNN.NNNNNNN....l.TN.....',
        '............NNNNNNN.NNNNNNN....lTN......',
        '............NNNNNNN.NNNNNNN....lTN......',
        '............NNNNNNN.NNNNNNN....TN.......',
        '............NNNNNNN.NNNNNNN...TN........',
        '............NNNNNNN.NNNNNNN...TN........',
        '............NNNNNNN.NNNNNNN.............',
        '............NNNNNNN.NNNNNNN.............',
        '............NNNNNNN.NNNNNNN.............',
        '............NNNNNNN.NNNNNNN.............',
        '............NNNNNNN.NNNNNNN.............',
        '............NNNNNNN.NNNNNNN.............',
        '...........DDDDDDDD.DDDDDDDD............',
        '...........DDDDDDDD.DDDDDDDD............',
      ],
    },
    /* великий эльф: золотые волосы, светлая одежда, синий плащ, смуглая кожа, самоцвет в волосах */
    grand_elf: { base: 'wood_elf', tint: { n: 'y', g: 'i', G: 'b', s: 'S' }, extra: [[17, 1, 'w'], [18, 1, 'w'], [17, 2, 'w'], [18, 2, 'w']] },
    /* пегас: белая крылатая лошадь в полёте, тёмно-золотая грива и хвост (композитор) (52×52) */
    pegasus: {
      hd: true, unit: 2,
      rows: [
        '................llll................................',
        '................lllllllleeee........................',
        '................lllllllleeeeeee.....................',
        '........eeee....lllllllleeeeeee.....................',
        '........eeeeeeee.llllllleeeeeee.....................',
        '.........eeeeeee.llllllleeeeeee.....................',
        '..........eeeeeeellllllleeeeeee.....................',
        '..........eeeeeee.lllllleeeeeee.....................',
        '..llll.....eeeeeeelllllleeeeeee........YY..LL.......',
        '...lllllll.eeeeeeelllllleeeeeee........YYY.LL.......',
        '....lllllll.eeeeeelllllleeeeeee.......YYYY.LL.......',
        '.....lllllll.eeeeeellllleeeeeee......YYYYYLLLL......',
        '......llllllleeeeeellllleeeeee.......YYYY.LLLLLLL...',
        '.......llllll.eeeeellllleeeeee......YYYY..LLLLLLLL..',
        '........lllllleeeeellllleeeeee.....YYYYY.LLLLLLLLLL.',
        '.........lllllleeeeelllleeeeee....YYYYY.LLLLLLLkLLLL',
        '..........lllllleeeelllleeeeee....YYYY..LLLLLLLLLlll',
        '...........llllleeeelllleeeeee...YYYY...LLLLLLLLllll',
        '............llllleeelllleeeeee....YYYLLLLLLLLLLlllll',
        '.............lllleeeellleeeeee....YYLLLLLLLLLLLLllll',
        '..............lllleeellleeeeee.....LLLLLLLLLLLLLLlll',
        '...............llleeellleeeee......LLLLLLLLLLLLLL...',
        '................llleeelleeeee......LLLLLLLLLL.......',
        '.................llleelleeeee......LLLLLLLLLLL......',
        '..................lleelleeeee......LLLLLLLLLLL......',
        '...................llelleeeee.......LLLLLLLLLLL.....',
        '....................leeleeeee.......LLLLLLLLLLL.....',
        '.....................leleeeee........LLLLLLLLLL.....',
        '......................lleeeee......LLLLLLLLLLLL.....',
        '.......................leeeee....LLLLLLLLLLLLLL.....',
        '.....................LLLLLLLLLL.LLLLLLLLLLLLLL......',
        '.................LLLLLLLLLLLLLLLLLLLLLLLLLLLLL......',
        '...........YYLLLLLLLLLLLLLLLLLLLLLLLLLLLLL..........',
        '..........YYYYLLLLLLLLLLLLLLLLLLLLLLLLLLLL..........',
        '.........YYYYYLLLLLLLLLLLLLLLLLLLLLLLLLLLL..........',
        '.........YYYYLLLLLLLLLLLLLLLLLLLLLLLLLLLLL..........',
        '........YYYYYLLLLLLLllllllllllllLLLLLLLLL...........',
        '.......YYYYYLLLLLllllllllllllllllllLLLL.............',
        '......YYYYYLLLLLllllllllllllllllllllLL..............',
        '......YYYYYLLLLLllllllllllllllllllllL...............',
        '.....YYYYYLLLlllllllLLLLLllllllllll.LLLLL...........',
        '....YYYYY...Llllll..LLLLLlllllllll..LLLLL...........',
        '....YYYYY....lllll..LLLLL....lllll..LLLLL...........',
        '...YYYYY.....lllll..LLLLL....lllll..LLLLL...........',
        '..YYYYY......lllll..LLLLL....lllll..LLLLL...........',
        '..YYYY.......lllll..LLLLL....lllll..LLLLL...........',
        '.YYYYY.......lllll..LLLLL....lllll..LLLLL...........',
        '.YYYY........lllll..LLLLL....lllll..LLLLL...........',
        '..YY........eeeeee.eeeeee...eeeeee.eeeeee...........',
        '............eeeeee.eeeeee...eeeeee.eeeeee...........',
        '............eeeeee.eeeeee...eeeeee.eeeeee...........',
        '....................................................',
      ],
    },
    /* серебряный пегас: серебристое тело, серые крылья, морская грива, синий нагрудный ремень */
    silver_pegasus: { base: 'pegasus', tint: { L: 'l', l: 'e', e: 'E', Y: 'C' }, extra: [[35, 30, 'b'], [36, 30, 'b'], [37, 30, 'b'], [38, 30, 'b'], [39, 30, 'b'], [40, 30, 'b'], [35, 31, 'b'], [36, 31, 'b'], [37, 31, 'b'], [38, 31, 'b'], [39, 31, 'b'], [40, 31, 'b'], [35, 32, 'b'], [36, 32, 'b'], [37, 32, 'b'], [38, 32, 'b'], [39, 32, 'b'], [40, 32, 'b']] },
    /* дендроид-страж: дерево-великан, крона листвы, кора с бороздами, ветки-руки, корни-ноги (56×60) */
    dendroid_guard: {
      hd: true, unit: 2,
      rows: [
        '.....................ggggggggggggggg....................',
        '.................ghhhhhhggggggggghhhhhhg................',
        '...............gghhhhhhhhggggggghhhhhhhhgg..............',
        '.............gggghhhhhhhggGGGGGgghhhhhhhgggg............',
        '............gggggghhhhhggGGGGGGGgghhhhhgggggg...........',
        '...........ggggggggggggggGGGGGGGgggggggggggggg..........',
        '...........gggggggggggggggGGGGGggggggggggggggg..........',
        '............ggggggggggggggggggggggggggggggggg...........',
        '.............ggggggggggggggggggggggggggggggg............',
        '...............ggggggNNNNNNNNNNNNNNNgggggg..............',
        '..NN..............gggNNNNNNNNNNNNNNNggg............NNN..',
        '..NNN................NDDDDDNNNDDDDDN..............NNNN..',
        '...NNN...............NNyyyNNNNNyyyNN.............NNN....',
        '....NN...............NNykyNNNNNykyNN.............NN.....',
        '....NNN.nn...........NNyyyNNNNNyyyNN.........nnnNNN.....',
        '.....NNNnnnn.........NNNNNNTTTNNNNNN.......nnnnNNNN.....',
        '.NNNNNNNNnnnnn.......NNNNNNTTTNNNNNN.....nnnnnNNNNNNNNN.',
        '.NNNNNNNNNNnnnn......NNNNNNTTTNNNNNN....nnnnNNNNNNNNNNN.',
        '.....NNNNNNNNnnnn....NNNNNNTTTNNNNNN..nnnnNNNNNNNNN.....',
        '.....NNNNNNNNNnnnnn..NNNDDDDDDDDDNNNnnnnnNNNNNNNNNN.....',
        '....NNNNNNNNNNNNnnnnnNNNDDDDDDDDDNnnnnnNNNNNNNNNNNN.....',
        '....NN...NNNNNNNNNnnnnNNnnNNDNNnnnnnnNNNNNNNNNN..NNN....',
        '....NN.....NNNNNNNNNnnnNnnNNDNNnNnnNNNNNNNNNN.....NN....',
        '.............NNNNNNNNnnNNnNNDNNnNnnNNNNNNNN.............',
        '...............NNNNNNNNNNnNNDNNnNNNNNNNNN...............',
        '.................NNNNNNNNnNNDNNnNNNNNNN.................',
        '...................NNNNNNnNNDNNnNNNNN...................',
        '....................NNNNNnNNDNNnNNNNN...................',
        '....................NNNNnnNNDNNnnNNNN...................',
        '....................NNNNnnNNDNNnnNNNN...................',
        '....................NNNNnnNNDNNnnNNNN...................',
        '....................NNNNnnNNDNNnnNNNN...................',
        '....................NNNNnnNNDNNnnNNNN...................',
        '...................NNNNNnnNNDNNnnNNNNN..................',
        '...................NNNNNnnNNDNNnnNNNNN..................',
        '...................NNNNNnnNNDNNnnNNNNN..................',
        '...................NNNNNnnNNDNNnnNNNNN..................',
        '...................NNNNNnnNNDNNnnNNNNN..................',
        '..................NNNNNNnnNNDNNnnNNNNNN.................',
        '..................NNNNNNnnNNDNNnnNNNNNN.................',
        '..................NNNNNNnnNNDNNnnNNNNNN.................',
        '..................NNNNNNnnNNDNNnnNNNNNN.................',
        '..................NNNNNNnnNNDNNnnNNNNNN.................',
        '.................NNNNNNNnnNNDNNnnNNNNNNN................',
        '.................NNnNNNN.NNnNNNN.NNnNNNN................',
        '................NNnNNNN..NNnNNNN.NNnNNNN................',
        '...............NNnNNNN...NNnNNNN..NNnNNNN...............',
        '..............NNnNNNN....NNnNNNN...NNnNNNN..............',
        '..............NNnNNNN....NNnNNNN...NNnNNNN..............',
        '.............NNnNNNN.....NNnNNNN....NNnNNNN.............',
        '............NNnNNNN......NNnNNNN.....NNnNNNN............',
        '...........NNnNNNN.......NNnNNNN......NNnNNNN...........',
        '...........NNnNNNN.......NNnNNNN......NNnNNNN...........',
        '..........NNnNNNN........NNnNNNN.......NNnNNNN..........',
        '.........NNnNNNN.........NNnNNNN........NNnNNNN.........',
        '........NNnNNNN..........NNnNNNN.........NNnNNNN........',
        '........NNnNNNN..........NNnNNNN.........NNnNNNN........',
        '.......NNnNNNN...........NNnNNNN..........NNnNNNN.......',
        '......zzzzzzz............zzzzzzz...........zzzzzzz......',
        '......zzzzzzz............zzzzzzz............zzzzzzz.....',
      ],
    },
    /* дендроид-солдат: тёмная кора с тлеющими трещинами, оливковая крона, листва на сучьях */
    dendroid_soldier: { base: 'dendroid_guard', tint: { N: 'D', n: 'd', D: 'O', g: 'H', G: 'j' }, extra: [[2, 9, 'g'], [3, 9, 'g'], [4, 9, 'g'], [1, 10, 'g'], [2, 10, 'g'], [3, 10, 'g'], [4, 10, 'g'], [5, 10, 'g'], [1, 11, 'g'], [2, 11, 'g'], [3, 11, 'g'], [4, 11, 'g'], [5, 11, 'g'], [1, 12, 'g'], [2, 12, 'g'], [3, 12, 'g'], [4, 12, 'g'], [5, 12, 'g'], [2, 13, 'g'], [3, 13, 'g'], [4, 13, 'g'], [52, 9, 'g'], [53, 9, 'g'], [54, 9, 'g'], [51, 10, 'g'], [52, 10, 'g'], [53, 10, 'g'], [54, 10, 'g'], [55, 10, 'g'], [51, 11, 'g'], [52, 11, 'g'], [53, 11, 'g'], [54, 11, 'g'], [55, 11, 'g'], [51, 12, 'g'], [52, 12, 'g'], [53, 12, 'g'], [54, 12, 'g'], [55, 12, 'g'], [52, 13, 'g'], [53, 13, 'g'], [54, 13, 'g'], [1, 15, 'g'], [2, 15, 'g'], [3, 15, 'g'], [0, 16, 'g'], [1, 16, 'g'], [2, 16, 'g'], [3, 16, 'g'], [4, 16, 'g'], [0, 17, 'g'], [1, 17, 'g'], [2, 17, 'g'], [3, 17, 'g'], [4, 17, 'g'], [0, 18, 'g'], [1, 18, 'g'], [2, 18, 'g'], [3, 18, 'g'], [4, 18, 'g'], [1, 19, 'g'], [2, 19, 'g'], [3, 19, 'g'], [53, 15, 'g'], [54, 15, 'g'], [55, 15, 'g'], [52, 16, 'g'], [53, 16, 'g'], [54, 16, 'g'], [55, 16, 'g'], [52, 17, 'g'], [53, 17, 'g'], [54, 17, 'g'], [55, 17, 'g'], [52, 18, 'g'], [53, 18, 'g'], [54, 18, 'g'], [55, 18, 'g'], [53, 19, 'g'], [54, 19, 'g'], [55, 19, 'g']] },
    /* единорог: белая лошадь, мятная грива и хвост, золотой рог (композитор) (60×58) */
    unicorn: {
      hd: true, unit: 2,
      rows: [
        '.........................................................YY.',
        '........................................................YYY.',
        '........................................................YYY.',
        '.......................................................YYYY.',
        '.......................................................YYY..',
        '.......................................................YYY..',
        '...............................................vvv....YYY...',
        '..............................................vvvvLL..YYY...',
        '..............................................vvvvvL.YYYY...',
        '............................................vvvvvvvL.YYY....',
        '...........................................vvvvvvvLLLYYY....',
        '..........................................vvvvvvvvLLLYYL....',
        '........................................vvvvvvvvLLLLLLLLL...',
        '........................................vvvvvvvLLLLLkLLLLL..',
        '......................................vvvvvvvvLLLLLLLLLlll..',
        '.....................................vvvvvvvv.LLLLLLLLlllll.',
        '.....................................vvvvvvv..LLLLLLLlllllll',
        '.....................................vvvvvLLLLLLLLLLLLlllll.',
        '.....................................vvvvLLLLLLLLLLLLLLlll..',
        '......................................vvvLLLLLLLL...........',
        '........................................LLLLLLLLLL..........',
        '........................................LLLLLLLLLL..........',
        '........................................LLLLLLLLLLL.........',
        '........................................LLLLLLLLLLL.........',
        '........................................LLLLLLLLLLLL........',
        '........................................LLLLLLLLLLLL........',
        '.........................................LLLLLLLLLLL........',
        '.........................................LLLLLLLLLLL........',
        '....................LLLLLLLLLLLL.....LLLLLLLLLLLLLLL........',
        '................LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL........',
        '........LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL........',
        '.......vvLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL........',
        '......vvvvLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL.........',
        '.....LvvvvLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL..............',
        '....LvvvvvLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL..............',
        '....LvvvvLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL..............',
        '....vvvvvLLLLLLLLLLLllllllllllllLLLLLLLLLLLLLL..............',
        '...vvvvvvLLLLLLLlllllllllllllllllllLLLLLLLLLL...............',
        '...vvvvvLLLLLLllllllllllllllllllllllLLLLLLLL................',
        '...vvvvvLLLLLllllllllllllllllllllllllLLLLLL.................',
        '..vvvvvLLLLLLllllllllllllllllllllllllllL....................',
        '..vvvvvLLLLLLLllllllllllllllllllllllll......................',
        '..vvvvvllllllLL.LLLLLLlllllllllllllll...LLLLLL..............',
        '..vvvv.llllllL..LLLLLLlllllllllllllll...LLLLLL..............',
        '.vvvvv.llllll...LLLLLL.........llllll...LLLLLL..............',
        '.vvvvv.llllll...LLLLLL.........llllll...LLLLLL..............',
        'vvvvv..llllll...LLLLLL.........llllll...LLLLLL..............',
        'vvvvv..llllll...LLLLLL.........llllll...LLLLLL..............',
        'vvvvv..llllll...LLLLLL.........llllll...LLLLLL..............',
        'vvvv...llllll...LLLLLL.........llllll...LLLLLL..............',
        'vvvv...llllll...LLLLLL.........llllll...LLLLLL..............',
        'vvv....llllll...LLLLLL.........llllll...LLLLLL..............',
        'v......llllll...LLLLLL.........llllll...LLLLLL..............',
        '.......llllll...LLLLLL.........llllll...LLLLLL..............',
        '......eeeeeee..eeeeeee........eeeeeee..eeeeeee..............',
        '......eeeeeee..eeeeeee........eeeeeee..eeeeeee..............',
        '......eeeeeee..eeeeeee........eeeeeee..eeeeeee..............',
        '......eeeeeee..eeeeeee........eeeeeee..eeeeeee..............',
      ],
    },
    /* боевой единорог: голубое тело, белая грива, искры у острия рога */
    war_unicorn: { base: 'unicorn', tint: { L: 'c', l: 'C', v: 'L', e: 'E' }, extra: [[55, 0, 'w'], [56, 0, 'w'], [57, 0, 'w'], [58, 0, 'w'], [59, 0, 'w'], [55, 1, 'w'], [56, 1, 'w'], [57, 1, 'w'], [58, 1, 'w'], [59, 1, 'w'], [57, 2, 'w']] },
    /* зелёный дракон: тёмно-зелёный, светлое брюхо, перепончатые крылья, раскрытая пасть, рога (композитор) (64×60) */
    green_dragon: {
      hd: true, unit: 2,
      rows: [
        '...................GGG....................GGG...................',
        '........GG.........GGG....................GGG.........GG........',
        '........GGG........GGG....................GGG........GGG........',
        '........GGGG.......GGG....................GGG.......GGGG........',
        '.........GGGgg.....gGGG..................gGGG.....ggGGG.........',
        '..........GGGgg....gGGG..................GGGg....ggGGGG.........',
        '..........GGGGggg..gGGGg................gGGGg..ggggGGG..........',
        '..........gGGGggggggGGGG................gGGGggggggGGGg.II.......',
        '..........ggGGGggggggGGGg..............ggGGGIggggGGGGg.II.......',
        '...........gGGGGgggggGGGg..............ggGGGgIIggGGGg..II.......',
        '...........ggGGGGggggGGGgg............ggGGGggIIIGGGGg..II.......',
        'GGG........gggGGGgggggGGGg............ggGGGgggIIIIGgg.IIII...GGG',
        'GGGGggggggggggGGGGggggGGGgg..........gggGGGggggIIIIIggIIIIggGGGG',
        '.GGGGGgggggggggGGGGgggGGGgg..........gggGGGgggGIIIIIggIIIIGGGGG.',
        '..GGGGGgggggggggGGGgggGGGgg..........gggGGGgggGGIIGGGGGGGGGGGG..',
        '....GGGGGgggggggGGGGgggGGGgg.........ggGGGgggGGGGGGGGGGGGGGGG...',
        '.....GGGGGgggggggGGGGggGGGgg........gggGGGggGGGGGGGGGyyGGGGGGGG.',
        '.......GGGGGggggggGGGggGGGggg.......gggGGGggGGGGGGGGGykGGGGGGGG.',
        '........GGGGGgggggGGGGgGGGggg.......gggGGGgGGGGGGGGGGGGGGGGGGGG.',
        '..........GGGGGggggGGGGgGGGgg.......gggGGGgGGGGGGGGGGGGGGGGGGGG.',
        '...........GGGGGggggGGGgGGGggg.....gggGGGgGGGgGGGGGGGGGGGGGG....',
        '.............GGGGGggGGGGGGGggg.....gggGGGGGGGggGGGGGGGDDiDDiDDi.',
        '..............GGGGGggGGGGGGGgg.....gggGGGGGGGgGGGGGGGGDDDDDDDDD.',
        '................GGGGGgGGGGGGggg....gggGGGGGGGGGGGGGGtttDDDDDDD..',
        '.................GGGGGgGGGGGggg...ggggGGGGGGGGGG....tttittitDi..',
        '...................GGGGGGGGGgggg..gggGGGGtttGGGGG...tttttttttt..',
        '....................GGGGGGGGGggg..gggGGGtttttGGGGG..tttttttt....',
        '......................GGGGGGGggg..gggGGGttttttGGGGG....tttt.....',
        '.......................GGGGGGgg....ggGGGGttttttGGGG.............',
        '.........................GGGGGGGGGG..GGGGtttttttGGG.............',
        '.....................GGGGGGGGGGGGGGGGGGGGtttttttGGGG............',
        '...................GGGGGGGGGGGGGGGGGGGGGGGtttttttGGG............',
        '.................GGGGGGGGGGGGGGGGGGGGGGGGGtttttttGGG............',
        '................GGGGGGGGGGGGGGGGGGGGGGGGGGGttttttGGG............',
        '...............GGGGGGGGGGGGGGGGGGGGGGGGGGGGGttttttGG............',
        '...............GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGtttttGG............',
        '..............GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGtttGG.............',
        '..............GGGGGGGGGGGGttttttttttGGGGGGGGGGGGGG..............',
        '..............GGGGGGGGttttttttttttttttttGGGGGG..................',
        '.............GGGGGGGGttttttttttttttttttttGGGGG..................',
        '............GGGGGGGGttttttttttttttttttttttGGG...................',
        '...........GGGGGGGGttttttttttttttttttttttttGG...................',
        '..........GGGGGGGGGttttttttttttttttttttttttG....................',
        '.........GGGGGGG.GGGttttttttttttttttttttttG.....................',
        '........GGGGGGG..GGGGGGGtttttttttGGGGGGGt.......................',
        '.......GGGGGGG...GGGGGGGtttttttttGGGGGGG........................',
        '......GGGGGGG....GGGGGGG.GtttttttGGGGGGG........................',
        '.....GGGGGGG.....GGGGGGG.........GGGGGGG........................',
        '....GGGGGGG......GGGGGGG.........GGGGGGG........................',
        '...GGGGGGG.......GGGGGGG.........GGGGGGG........................',
        '..GhhGGGG........GGGGGGG.........GGGGGGG........................',
        '.hhhhGGG........GGGGGGGG........GGGGGGGG........................',
        'hhhhhGG.........GGGGGGGG........GGGGGGGG........................',
        'hhhhhh..........GGGGGGGG........GGGGGGGG........................',
        'hhhhhh..........GGGGGGGG........GGGGGGGG........................',
        'Ghhhhh..........GGGGGGGG........GGGGGGGG........................',
        '.hhhh.........GGGGGGGGGG......GGGGGGGGGG........................',
        '.hh...........GGGGGGGGGG......GGGGGGGGGG........................',
        '..............GiiGiiGiiG......GiiGiiGiiG........................',
        '...............ii.ii.ii........ii.ii.ii.........................',
      ],
    },
    /* золотой дракон: золотая чешуя, светлое брюхо, красный глаз, пламя из пасти */
    gold_dragon: { base: 'green_dragon', tint: { g: 'y', G: 'Y', t: 'i', h: 'f', I: 'w' }, extra: [[53, 16, 'r'], [54, 16, 'r'], [53, 17, 'r'], [63, 20, 'f'], [62, 21, 'f'], [63, 21, 'f'], [61, 22, 'f'], [62, 22, 'f'], [63, 22, 'f'], [61, 23, 'f'], [62, 23, 'f'], [63, 23, 'f'], [60, 24, 'f'], [61, 24, 'f'], [62, 24, 'f'], [63, 24, 'f'], [60, 25, 'f'], [61, 25, 'f'], [62, 25, 'f'], [63, 25, 'f'], [62, 26, 'f'], [63, 26, 'f']] },
  });
})();
