/* ============================================================================
   view/sprites_inferno_hd.js — существа Инферно в крупной сетке (unit 2), стиль Б:
   без контурной линии, тона кладёт рисунок. Собирается скриптом dev/proto/inferno_hd.py.
   ========================================================================== */
(function () {
  'use strict';
  H3.Sprites.defineMany({
    /* бес: маленький красный чертёнок, рожки, светлое брюшко, кожаные крылья, хвост (40×46) */
    imp: {
      hd: true, unit: 2,
      rows: [
        '.............ii.........ii..............',
        '............iii.........iii.............',
        '............iii.........iii.............',
        '............iiirrrrrrrrriii.............',
        '.............rrrrrrrrrrrrr..............',
        '.RR........rrrrrrrrrrrrrrrrr.........RR.',
        '.RRR.....rrrrrrrrrrrrrrrrrrrrr......RRR.',
        '.RRRR...rrrrrrryyyrrrryyyrrrrrr....RRRR.',
        '.RRRRR.rrrrrrryykrrrrkyyrrrrrrr...RRRRR.',
        '.RRRRRR.rrrrrrryyyrrrryyyrrrrrr..RRRRRR.',
        '.RRRRRRR.rrrrrrrrrrrrrrrrrrrrr..RRRRRRR.',
        '.RRRRRRRR.rrrrrRRRRRRRRRrrrr...RRRRRRRR.',
        '..RRRRRRRR.rrrrRwRwRwRwRrrr...RRRRRRRR..',
        '...RRRRRRRR.rrrRRRRRRRRRrr...RRRRRRRR...',
        '...RRRRRRRRR..rrrrrrrrrr....RRRRRRRRR...',
        '...RRRRRRRRRR...rrrrrr.....RRRRRRRRRR...',
        '...RRRRRRRrrRRrrrrrrrrrr..rrRRRRRRRRR...',
        '...RRRRRRRrrRRrrrrrrrrrr..rrRRRRRRRRR...',
        '...RRRRRRrrrRrrrrooooorrr.rrrRRRRRRRR...',
        '...RRRRRRrrrRrrrrooooorrr.rrrRRRRRRRR...',
        '..RRRRRRRrrrRrrrooooooorrrRrrrRRRRRRRR..',
        '..RRRRRRRrrrRrrrooooooorrrRrrrRRRRRRRR..',
        '..RRRRRRRrrrRrrrooooooorrrRrrrRRRRRRRR..',
        '..RRRRRRRrrrRrrrooooooorrrRrrrRRRRRRRR..',
        '..RRR.RRRrrrRrrrooooooorrrRrrrRRrrrRRR..',
        '..RRR.RRRrrrRrrrooooooorrrRrrrRRrrrRRR..',
        '......RRRrrrRrrrooooooorrrRrrrRRrrr.....',
        '......RRRrrrRrrrooooooorrrRrrrRRrrr.....',
        '......RRRrrrRrrrrooooorrrrRrrrRrrr......',
        '......RRRrrrRrrrrooooorrrrRrrrRrrr......',
        '.....RRRRrrrRrrrrrrrrrrrrrRrrrRrrrR.....',
        '.....RRRRrrrRrrrrrrrrrrrrrRrrrRrrrR.....',
        '.....RRRRiii.rrDDDDDDDDDDr.iiirrrRR.....',
        '.....RRRRiii.rrDDDDDDDDDDr.iiirrrRR.....',
        '.....RR..iii.rrDDDDDDDDDDrriiirrrRR.....',
        '.....RR..iii.rrDDDDDDDDDDrriiirrrRR.....',
        '...............DDDDDDDDDDrrrrrrr........',
        '...............DDDDDDDDDDrrrrrr.........',
        '...............rrrr..rrrr...............',
        '...............rrrr..rrrr...............',
        '...............rrrr..rrrr...............',
        '...............rrrr..rrrr...............',
        '...............rrrr..rrrr...............',
        '..............rrrr....rrrr..............',
        '..............DDDD....DDDD..............',
        '..............DDDD....DDDD..............',
      ],
    },
    /* фамильяр: фиолетовый бес, сиреневое брюшко, золотой трезубец */
    familiar: { base: 'imp', tint: { r: 'p', R: 'P', o: 'A' }, extra: [[30, 0, 'y'], [31, 0, 'y'], [30, 1, 'y'], [31, 1, 'y'], [30, 2, 'y'], [31, 2, 'y'], [30, 3, 'y'], [31, 3, 'y'], [30, 4, 'y'], [31, 4, 'y'], [30, 5, 'y'], [31, 5, 'y'], [30, 6, 'y'], [31, 6, 'y'], [30, 7, 'y'], [31, 7, 'y'], [30, 8, 'y'], [31, 8, 'y'], [30, 9, 'y'], [31, 9, 'y'], [30, 10, 'y'], [31, 10, 'y'], [30, 11, 'y'], [31, 11, 'y'], [30, 12, 'y'], [31, 12, 'y'], [30, 13, 'y'], [31, 13, 'y'], [30, 14, 'y'], [31, 14, 'y'], [30, 15, 'y'], [31, 15, 'y'], [30, 16, 'y'], [31, 16, 'y'], [30, 17, 'y'], [31, 17, 'y'], [30, 18, 'y'], [31, 18, 'y'], [30, 19, 'y'], [31, 19, 'y'], [30, 20, 'y'], [31, 20, 'y'], [30, 21, 'y'], [31, 21, 'y'], [30, 22, 'y'], [31, 22, 'y'], [30, 23, 'y'], [31, 23, 'y'], [30, 24, 'y'], [31, 24, 'y'], [30, 25, 'y'], [31, 25, 'y'], [30, 26, 'y'], [31, 26, 'y'], [30, 27, 'y'], [31, 27, 'y'], [30, 28, 'y'], [31, 28, 'y'], [30, 29, 'y'], [31, 29, 'y'], [30, 30, 'y'], [31, 30, 'y'], [27, 0, 'y'], [28, 0, 'y'], [33, 0, 'y'], [34, 0, 'y'], [27, 1, 'y'], [28, 1, 'y'], [33, 1, 'y'], [34, 1, 'y'], [27, 2, 'y'], [28, 2, 'y'], [33, 2, 'y'], [34, 2, 'y'], [27, 3, 'y'], [28, 3, 'y'], [33, 3, 'y'], [34, 3, 'y'], [27, 4, 'y'], [28, 4, 'y'], [33, 4, 'y'], [34, 4, 'y'], [27, 4, 'y'], [28, 4, 'y'], [29, 4, 'y'], [30, 4, 'y'], [31, 4, 'y'], [32, 4, 'y'], [33, 4, 'y'], [34, 4, 'y'], [27, 5, 'y'], [28, 5, 'y'], [29, 5, 'y'], [30, 5, 'y'], [31, 5, 'y'], [32, 5, 'y'], [33, 5, 'y'], [34, 5, 'y']] },
    /* гог: ржаво-коричневый бес, светлое лицо, рожки, огненный шар в поднятой руке (44×46) */
    gog: {
      hd: true, unit: 2,
      rows: [
        '..........iii.........iii.........FFFF......',
        '..........iii.........iii.......FFFFFFFF....',
        '..........iiiooooooooiii........FFffffFF....',
        '...........ioooooooooooi.......FFffffffFF...',
        '..........oooooooooooooo.......FFffwwffFF...',
        '.........oooooooooooooooo......FFffwwffFF...',
        '.........ooooyyyoooyyyooo......FFffffffFF...',
        '.........ooooykyoooykyooo......OFFffffFF....',
        '.........ooooyyyoooyyyooo.....OOFFFFFFFF....',
        '.........oooooooooooooooo.....OOOOFFFF......',
        '..........ooooRRRRRRRoooo.....OOOOOO........',
        '..........oooRwRwRwRwRooo....OOOOOOO........',
        '...........oooRRRRRRRooo....OOOOOOO.........',
        '............oooooooooooo...OOOOO............',
        '..............OOOOOO......OOOOO.............',
        '..........OOOOOOOOOOOOOOOOOOOO..............',
        '..........OOOOOOOOOOOOOOOOOOOO..............',
        '.........OOOOOOOOOOOOOOOOOOOO...............',
        '.........OOOOOOOOOOOOOOOOOOOO...............',
        '........OOO.OOOOOOOOOOOOOOOO................',
        '........OOO.OOOOOOOOOOOOOOOO................',
        '........OOO.OOOOOOOOOOOOOOOO................',
        '........OOO.OOOOOOOOOOOOOOOO................',
        '........OOO.OOOOOOOOOOOOOOOO................',
        '........OOO.OOOOOOOOOOOOOOOO................',
        '........OOO.OOOOOOOOOOOO....................',
        '........OOO.OOOOOOOOOOOO....................',
        '........OOO.OOOOOOOOOOOO....................',
        '........OOO.OOOOOOOOOOOO....................',
        '........OOO.OOOOOOOOOOOO....................',
        '........OOO.OOOOOOOOOOOO....................',
        '........OOO.OOOOOOOOOOOO....................',
        '........OOO.OOOOOOOOOOOO....................',
        '........iii.OOOOOOOOOOOO....................',
        '........iii.OOOOOOOOOOOO....................',
        '........iii.DDDDDDDDDDDD....................',
        '............DDDDDDDDDDDD....................',
        '............DDDDDDDDDDDD....................',
        '............OOOO....OOOO....................',
        '............OOOO....OOOO....................',
        '............OOOO....OOOO....................',
        '............OOOO....OOOO....................',
        '............OOOO....OOOO....................',
        '...........OOOO......OOOO...................',
        '...........DDDD......DDDD...................',
        '...........DDDD......DDDD...................',
      ],
    },
    /* магог: золотые рога, шар больше и ярче с белым ядром */
    magog: { base: 'gog', tint: { i: 'y' }, extra: [[31, 0, 'F'], [32, 0, 'F'], [33, 0, 'F'], [34, 0, 'F'], [38, 0, 'F'], [39, 0, 'F'], [40, 0, 'F'], [41, 0, 'F'], [30, 1, 'F'], [31, 1, 'F'], [32, 1, 'F'], [40, 1, 'F'], [41, 1, 'F'], [42, 1, 'F'], [30, 2, 'F'], [31, 2, 'F'], [41, 2, 'F'], [42, 2, 'F'], [30, 3, 'F'], [31, 3, 'F'], [41, 3, 'F'], [42, 3, 'F'], [29, 4, 'F'], [30, 4, 'F'], [42, 4, 'F'], [43, 4, 'F'], [29, 5, 'F'], [30, 5, 'F'], [42, 5, 'F'], [43, 5, 'F'], [29, 6, 'F'], [30, 6, 'F'], [42, 6, 'F'], [43, 6, 'F'], [30, 7, 'F'], [31, 7, 'F'], [41, 7, 'F'], [42, 7, 'F'], [30, 8, 'F'], [31, 8, 'F'], [41, 8, 'F'], [42, 8, 'F'], [40, 9, 'F'], [41, 9, 'F'], [42, 9, 'F'], [38, 10, 'F'], [39, 10, 'F'], [40, 10, 'F'], [41, 10, 'F'], [36, 11, 'F'], [37, 11, 'F'], [38, 11, 'F'], [39, 11, 'F'], [40, 11, 'F'], [36, 12, 'F'], [37, 12, 'F'], [34, 3, 'w'], [35, 3, 'w'], [36, 3, 'w'], [37, 3, 'w'], [34, 4, 'w'], [35, 4, 'w'], [36, 4, 'w'], [37, 4, 'w'], [34, 5, 'w'], [35, 5, 'w'], [36, 5, 'w'], [37, 5, 'w'], [34, 6, 'w'], [35, 6, 'w'], [36, 6, 'w'], [37, 6, 'w']] },
    /* адская гончая: графитовый пёс, огненная грива и хвост, светящаяся пасть (композитор) (52×48) */
    hell_hound: {
      hd: true, unit: 2,
      rows: [
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '..FF................................................',
        '.FFFF...............................................',
        '.FFFF.............................u.f.fFFu..........',
        'ffFFff..........................fFuuuFfFFuu.........',
        'ffffff......................fFFfFFuuuufFFuuuu.......',
        'ffffff.................f.fFFfFFfFFfuuuuuuuuuuu......',
        'ffffff.............fffFFfFFffFFffFfuuuuuuuuuuu......',
        '.ffff..........fFffFFfFFffFfffffffuuuuuuuuuuuu......',
        '..ffu.......fFffFFfFFffFffffffffffuuuuuuuuuuuu......',
        '..uuuu..fFFfFFffFffFFfffffffffff.uuuuuyyyyyuuuu.....',
        '...uuu..fFFfFFffFfffffffffff.....uuuuuyykkyuuuuuuu..',
        '...uuuuffFFfffffffffffff.........uuuuuyykkyuuuuuuuu.',
        '....uuuffffffffffffff............uuuuuuuuuuuuuuuuuuu',
        '.....uuufffffff................uuuuuuuuuuuuuuuuuuuuu',
        '.....uuuufff......uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu.',
        '......uuu.....uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuFFFFF',
        '......uuuu..uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuFFwFFwFFwF',
        '.......uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuFFFFFFFFFF',
        '........uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuFFFFFFFFFF',
        '........uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuFFFFFFF',
        '.......uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuwuuwFFw',
        '.......uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu.',
        '.......uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu.uuu...',
        '.......uuuuuuuuuzzzzzzzzzzzzzzzzuuuuuuuuuuuu........',
        '........uuuuuzzzzzzzzzzzzzzzzzzzzzzuuuuuuuu.........',
        '.........uuuzzzzzzzzzzzzzzzzzzzzzzzzuuuuuuu.........',
        '..........uuzzzzzzzzzzzzzzzzzzzzzzzzuuuuu...........',
        '............uzzzzzzzzzzzzzzzzzzzzzzuuuu.............',
        '............zzzzzzzuuuuuuzzzzzzzzzzzzz.uuuuuu.......',
        '............zzzzzzuuuuuuuuuuuu..zzzzzz.uuuuuu.......',
        '............zzzzzz.uuuuuu.......zzzzzz.uuuuuu.......',
        '............zzzzzz.uuuuuu.......zzzzzz.uuuuuu.......',
        '...........zzzzzz...uuuuuu.....zzzzzz...uuuuuu......',
        '...........zzzzzz...uuuuuu.....zzzzzz...uuuuuu......',
        '...........zzzzzz...uuuuuu.....zzzzzz...uuuuuu......',
        '..........zzzzzz.....uuuuuu...zzzzzz.....uuuuuu.....',
        '..........zzzzzz.....uuuuuu...zzzzzz.....uuuuuu.....',
        '..........zzzzzz.....uzzzzz...zzzzzz.....uzzzzz.....',
        '.........zzzzzzz.....zzzzzzz.zzzzzzz.....zzzzzzz....',
        '..........zzzzz.......zzzzz...zzzzz.......zzzzz.....',
      ],
    },
    /* цербер: три головы, серая шерсть, три огненные пасти, шипастый ошейник (композитор) (56×50) */
    cerberus: {
      hd: true, unit: 2,
      rows: [
        '........................................................',
        '........................................................',
        '........................................................',
        '...................................E....................',
        '...................................EEE..................',
        '...................................EEEEE................',
        '....................................EEEEEEE.............',
        '...................................EEEEEEEEEE...........',
        '...................................EEEEEEEEEE...........',
        '..................................EEEEyyyyyEEE..........',
        '..................................EEEEyykkyEEEEEE.......',
        '..................................EEEEyykkyEEEEEEE......',
        '..FF..........................fFFfEEEEEEEEEEEEEEEEE.....',
        '.FFFF.........................fFFf.EEEEEEEEEEEEEEEE.....',
        '.FFFF........................ffFFffEEEEEEEEEEEEFFFFF....',
        'ffFFff..................fFFf.ffffff.EEEEEEEEwFFwFFwF....',
        'ffffff...............fFffFFf..ffff.EEEEEEEEEEEEFFFFF....',
        'ffffff............ffffFffFFff.ffff.EEEEEEEEEEEEEEFFF....',
        'ffffff.........ffffFffFffffff......EEEEEEEEEEEEEEFFw....',
        '.ffff........ffFFfFFffffffff.......EEEEEEEyyyyyEEEE.....',
        '..ffE......fFFfFFffFffffffff......EEEEEEEEyykkyEEEEEE...',
        '..EEEE..fFFfFFffFffffffff.........EEEEEEEEyykkyEEEEEEE..',
        '...EEE..fFFfFFffffffff............EEEEEEEEEEEEEEEEEEEEE.',
        '...EEEEffFFfffffff.f..........EEEEEEEEEEEEEEEEEEEEEEEEE.',
        '....EEEffffffffff...........EEEEEEEEEEEEEEEEEEEEEEEFFFFF',
        '.....EEEfffffff............EEEEEEEEEEEEEEEEEEEFFwFFwFFwF',
        '.....EEEEfff....EEEEEEEEEEEEEEEEEEEEEEEEEEEE..FFFFFFFFFF',
        '......EEE....EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFFFFFFFFFF',
        '......EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEwEFwFFw',
        '.......EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEyyyyyEEEEEEEEEEE.',
        '........EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEyykkyEEEEEEEEE...',
        '.......EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEyykkyEEEEEEE.....',
        '......EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE....',
        '......EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE....',
        '......EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFFFFF...',
        '......EEEEEEEEzzzzzzzzzzzzzzzzEEEEEEEEEEEEEFFwFFwFFwF...',
        '.......EEEEEzzzzzzzzzzzzzzzzzzzzEEEEEEE....FFFFFFFFFF...',
        '........EEEzzzzzzzzzzzzzzzzzzzzzzEEEEE.....FFFFFFFFFF...',
        '.........EEzzzzzzzzzzzzzzzzzzzzzzEEE......EEEEwEFwFFw...',
        '..........EEzzzzzzzzzzzzzzzzzzzzEE........EEEEEEEEEE....',
        '............zzzzzzzEEEEEEzzzzzzzzzzz.EEEEEE..EEEEE......',
        '............zzzzzzEEEEEEEEEE..zzzzzz.EEEEEE.............',
        '............zzzzzz.EEEEEE.....zzzzzz.EEEEEE.............',
        '...........zzzzzz...EEEEEE...zzzzzz...EEEEEE............',
        '...........zzzzzz...EEEEEE...zzzzzz...EEEEEE............',
        '...........zzzzzz...EEEEEE...zzzzzz...EEEEEE............',
        '..........zzzzzz.....EEEEEE.zzzzzz.....EEEEEE...........',
        '..........zzzzzz.....Ezzzzz.zzzzzz.....Ezzzzz...........',
        '.........zzzzzzz.....zzzzzzzzzzzzz.....zzzzzzz..........',
        '..........zzzzz.......zzzzz.zzzzz.......zzzzz...........',
      ],
    },
    /* демон: мускулистый красный, короткие рога, светлая грудь, когти, тёмная повязка (48×52) */
    demon: {
      hd: true, unit: 2,
      rows: [
        '................................................',
        '................................................',
        '.............III..........III...................',
        '.............III..........III...................',
        '.............IIIrrrrrrrrrrIII...................',
        '..............IrrrrrrrrrrrrI....................',
        '.............rrrrrrrrrrrrrrrr...................',
        '............rrrrrrrrrrrrrrrrrr..................',
        '............rrrryyyrrrrryyyrrr..................',
        '............rrrrykyrrrrrykyrrr..................',
        '............rrrryyyrrrrryyyrrr..................',
        '............rrrrrrrrrrrrrrrrrr..................',
        '.............rrrrRRRRRRRRrrrr...................',
        '.............rrrRwRwRwRwRRrrr...................',
        '..............rrrRRRRRRRRrrr....................',
        '...............rrrrrrrrrrrr.....................',
        '.................rrrrrrrr.......................',
        '..........rrrrrrrrrrrrrrrrrrrrrrrr..............',
        '..........rrrrrrrrrrrrrrrrrrrrrrrr..............',
        '........rrrrrrrrrrrrrrrrrrrrrrrrrrrr............',
        '........rrrrrrrrrrrrrrrrrrrrrrrrrrrr............',
        '.......rrrrr.rrrrrooooooorrrrr.rrrrr............',
        '.......rrrrr.rrrrrooooooorrrrr.rrrrr............',
        '.......rrrrr.rrrroooooooooorrr.rrrrr............',
        '.......rrrrr.rrrroooooooooorrr.rrrrr............',
        '.......rrrrr.rrrooooRRooooorrr.rrrrr............',
        '.......rrrrr.rrrooooRRooooorrr.rrrrr............',
        '.......rrrrr.rrrooooRRooooorrr.rrrrr............',
        '.......rrrrr.rrrooooRRooooorrr.rrrrr............',
        '.......rrrrr.rrrroooooooooorrr.rrrrr............',
        '.......rrrrr.rrrroooooooooorrr.rrrrr............',
        '.......rrrrr.rrrrrooooooorrrrr.rrrrr............',
        '.......rrrrr.rrrrrooooooorrrrr.rrrrr............',
        '.......rrrrr.rrrrrrrrrrrrrrrrr.rrrrr............',
        '.......rrrrr.rrrrrrrrrrrrrrrrr.rrrrr............',
        '.......rrrrr.rrrrroRRRRRorrrrr.rrrrr............',
        '.......rrrrr.rrrrroRRRRRorrrrr.rrrrr............',
        '.......rrrrr.rrrrrroRRRorrrrrr.rrrrr............',
        '.......iiiii.rrrrrrrrrrrrrrrrr.iiiii............',
        '.......iiiii.rDDDDDDDDDDDDDDDr.iiiii............',
        '.............rDDDDDDDDDDDDDDDr..................',
        '..............DDDDDDDDDDDDDDD...................',
        '..............DDDDDDDDDDDDDDD...................',
        '..............rrrrrr...rrrrrr...................',
        '..............rrrrrr...rrrrrr...................',
        '..............rrrrrr...rrrrrr...................',
        '..............rrrrrr...rrrrrr...................',
        '..............rrrrrr...rrrrrr...................',
        '..............rrrrrr...rrrrrr...................',
        '.............rrrrrr.....rrrrrr..................',
        '.............DDDDDD.....DDDDDD..................',
        '.............DDDDDD.....DDDDDD..................',
      ],
    },
    /* рогатый демон: большие костяные рога, кожа темнее, глаза горят */
    horned_demon: { base: 'demon', tint: { o: 'r', R: 'D', I: 'i', y: 'f' }, extra: [[8, 0, 'i'], [9, 0, 'i'], [10, 0, 'i'], [34, 0, 'i'], [33, 0, 'i'], [32, 0, 'i'], [8, 1, 'i'], [9, 1, 'i'], [10, 1, 'i'], [11, 1, 'i'], [34, 1, 'i'], [33, 1, 'i'], [32, 1, 'i'], [31, 1, 'i'], [9, 2, 'i'], [10, 2, 'i'], [11, 2, 'i'], [12, 2, 'i'], [33, 2, 'i'], [32, 2, 'i'], [31, 2, 'i'], [30, 2, 'i'], [10, 3, 'i'], [11, 3, 'i'], [12, 3, 'i'], [13, 3, 'i'], [32, 3, 'i'], [31, 3, 'i'], [30, 3, 'i'], [29, 3, 'i'], [11, 4, 'i'], [12, 4, 'i'], [13, 4, 'i'], [14, 4, 'i'], [31, 4, 'i'], [30, 4, 'i'], [29, 4, 'i'], [28, 4, 'i'], [12, 5, 'i'], [13, 5, 'i'], [14, 5, 'i'], [15, 5, 'i'], [30, 5, 'i'], [29, 5, 'i'], [28, 5, 'i'], [27, 5, 'i']] },
    /* порождение ада: крупный красный демон, рога, стальные оплечья и наручи, кожаные крылья, кнут (56×58) */
    pit_fiend: {
      hd: true, unit: 2,
      rows: [
        '..............III..............III......................',
        '...............III............III.......................',
        '................III..........III........................',
        '.................III........III.........................',
        '..DN.............IIIrrrrrrrrIII.............NN..........',
        '..DDN.............IrrrrrrrrrrI.............NDD..........',
        '..DDDN...........rrrrrrrrrrrrrr...........NDDD..........',
        '..DDDN..........rrrrrrrrrrrrrrrr..........NDDD..........',
        '.DDDDDN........rrrrrrrrrrrrrrrrrr........NDDDDD.........',
        '.DDDDDDN.......rrrryyyrrrrryyyrrr.......NDDDDDD.........',
        '.DDDDDDDN......rrrrykyrrrrrykyrrr......NDDDDDDD.........',
        '.DDDDDDDN......rrrryyyrrrrryyyrrr......NDDDDDDD.........',
        'DDDDDDDDDN.....rrrrrrrrrrrrrrrrrr.....NDDDDDDDDD........',
        'DDDDDDDDDDN.....rrrrRRRRRRRRRrrr.....NDDDDDDDDDD........',
        'DDDDDDDDDDND....rrrRwRwRwRwRwRrr....DNDDDDDDDDDD........',
        'DDDDDDDDDDDN.....rrrRRRRRRRRRrr.....NDDDDDDDDDDD........',
        'DDDDDDDDDDDDN.....rrrrrrrrrrrr.....NDDDDDDDDDDDD........',
        'DDDDDDDDDDDDDN......rrrrrrrr......NDDDDDDDDDDDDD........',
        'DDDDDDDDDDllllllllllllllllllllllllllllllllDDDDDD........',
        'DDDDDDDDllllllrrrrrrrrrrrrrrrrrrrrrrllllllDDDDDD........',
        '.DDDDDDrrrrrrrDrrrrrrooooooorrrrrrDrrrrrrrDDDDD.........',
        '.DDDDDDrrrrrrrDrrrrrrooooooorrrrrrDrrrrrrrDDDDD.........',
        '.DDDDDDrrrrrrrNrrrrroooooooooorrrrDrrrrrrrDDDDD.........',
        '.DDDDDDrrrrrrrNrrrrroooooooooorrrrDrrrrrrrDDDDD.........',
        '.DDDDDDrrrrrrrNrrrroooooRRooooorrrNrrrrrrrDDDDD.........',
        '.DDDDDDrrrrrrrNrrrroooooRRooooorrrNrrrrrrrDDDDD.........',
        '..DDDDDrrrrrrrDrrrroooooRRooooorrrNrrrrrrrDDDD..........',
        '..DDDDDrrrrrrrDrrrroooooRRooooorrrNrrrrrrrDDDD..........',
        '..DDDDDrrrrrrrDrrrroooooooooooorrrNrrrrrrrDDDD..........',
        '..DDDDDrrrrrrrDrrrroooooooooooorrrNrrrrrrrDDDD..........',
        '..DDDNNrrrrrrrDrrrrrooooooooorrrrrDrrrrrrrNDDD..........',
        '..DDDNNrrrrrrrDrrrrrooooooooorrrrrDrrrrrrrNDDD..........',
        '..DNN..lllllllDrrrrrrrrrrrrrrrrrrrDlllllll.NND..........',
        '..DNN..lllllllDrrrrrrrrrrrrrrrrrrrDlllllll.NND..........',
        '...N...lllllllDrrrrrrroRRRRorrrrrrDlllllll...N..........',
        '...N...lllllllDrrrrrrroRRRRorrrrrrDlllllll...N..........',
        '......DlllllllDrrrrrrrroRRRorrrrrrDlllllll..............',
        '......DlllllllDrrrrrrrroRRRorrrrrrDlllllll..............',
        '......DrrrrrrrDrrrrrrrrrrrrrrrrrrrDrrrrrrrYYYnn.........',
        '......DrrrrrrrDrrrrrrrrrrrrrrrrrrrDrrrrrrrYYYnn.........',
        '......DrrrrrrrDrrrrrrrrrrrrrrrrrrrDrrrrrrrYYnnnnn.......',
        '......DrrrrrrrDrrrrrrrrrrrrrrrrrrrDrrrrrrrYYnnnnn.......',
        '......DiiiiiiiDlllllllllllllllllllDrrrrrrrYYnnnnnn......',
        '.....DDiiiiiiiDDDDDDDDDDDDDDDDDDDDDrrrrrrrYYYnnnnnnn....',
        '.....DNDDDD.DDDDDDDDDDDDDDDDDDDDDDDD.DDDDND...nnnnnnn...',
        '.....ND......DDDDDDDDDDDDDDDDDDDDDD......DN....nnnnnnn..',
        '.....N........DDDDDDDDDDDDDDDDDDDD.........N.....nnnnnn.',
        '...............rrrrrrr.....rrrrrrr................nnnnn.',
        '...............rrrrrrr.....rrrrrrr................nnnnn.',
        '...............rrrrrrr.....rrrrrrr.................nnnn.',
        '...............rrrrrrr.....rrrrrrr.................nnnn.',
        '...............rrrrrrr.....rrrrrrr.................nnnn.',
        '...............rrrrrrr.....rrrrrrr..................nnnn',
        '...............rrrrrrr.....rrrrrrr..................nnnn',
        '...............rrrrrrr.....rrrrrrr...............nnnnnnn',
        '..............rrrrrrr.......rrrrrrr............nnnnnnnnn',
        '..............DDDDDDD.......DDDDDDD...........nnnnnnnnn.',
        '..............DDDDDDD.......DDDDDDD...........nnnnnnn...',
      ],
    },
    /* владыка бездны: сталь в золото, вместо кнута золотой трезубец */
    pit_lord: { base: 'pit_fiend', tint: { l: 'y', n: '.', Y: '.' }, extra: [[41, 6, 'y'], [42, 6, 'y'], [41, 7, 'y'], [42, 7, 'y'], [41, 8, 'y'], [42, 8, 'y'], [41, 9, 'y'], [42, 9, 'y'], [41, 10, 'y'], [42, 10, 'y'], [41, 11, 'y'], [42, 11, 'y'], [41, 12, 'y'], [42, 12, 'y'], [41, 13, 'y'], [42, 13, 'y'], [41, 14, 'y'], [42, 14, 'y'], [41, 15, 'y'], [42, 15, 'y'], [41, 16, 'y'], [42, 16, 'y'], [41, 17, 'y'], [42, 17, 'y'], [41, 18, 'y'], [42, 18, 'y'], [41, 19, 'y'], [42, 19, 'y'], [41, 20, 'y'], [42, 20, 'y'], [41, 21, 'y'], [42, 21, 'y'], [41, 22, 'y'], [42, 22, 'y'], [41, 23, 'y'], [42, 23, 'y'], [41, 24, 'y'], [42, 24, 'y'], [41, 25, 'y'], [42, 25, 'y'], [41, 26, 'y'], [42, 26, 'y'], [41, 27, 'y'], [42, 27, 'y'], [41, 28, 'y'], [42, 28, 'y'], [41, 29, 'y'], [42, 29, 'y'], [41, 30, 'y'], [42, 30, 'y'], [41, 31, 'y'], [42, 31, 'y'], [41, 32, 'y'], [42, 32, 'y'], [41, 33, 'y'], [42, 33, 'y'], [41, 34, 'y'], [42, 34, 'y'], [41, 35, 'y'], [42, 35, 'y'], [41, 36, 'y'], [42, 36, 'y'], [41, 37, 'y'], [42, 37, 'y'], [41, 38, 'y'], [42, 38, 'y'], [41, 39, 'y'], [42, 39, 'y'], [41, 40, 'y'], [42, 40, 'y'], [41, 41, 'y'], [42, 41, 'y'], [41, 42, 'y'], [42, 42, 'y'], [41, 43, 'y'], [42, 43, 'y'], [41, 44, 'y'], [42, 44, 'y'], [41, 45, 'y'], [42, 45, 'y'], [41, 46, 'y'], [42, 46, 'y'], [41, 0, 'y'], [42, 0, 'y'], [41, 1, 'y'], [42, 1, 'y'], [41, 2, 'y'], [42, 2, 'y'], [41, 3, 'y'], [42, 3, 'y'], [41, 4, 'y'], [42, 4, 'y'], [41, 5, 'y'], [42, 5, 'y'], [37, 2, 'y'], [38, 2, 'y'], [45, 2, 'y'], [46, 2, 'y'], [37, 3, 'y'], [38, 3, 'y'], [45, 3, 'y'], [46, 3, 'y'], [37, 4, 'y'], [38, 4, 'y'], [45, 4, 'y'], [46, 4, 'y'], [37, 5, 'y'], [38, 5, 'y'], [45, 5, 'y'], [46, 5, 'y'], [37, 6, 'y'], [38, 6, 'y'], [45, 6, 'y'], [46, 6, 'y'], [37, 7, 'y'], [38, 7, 'y'], [45, 7, 'y'], [46, 7, 'y'], [37, 7, 'y'], [38, 7, 'y'], [39, 7, 'y'], [40, 7, 'y'], [41, 7, 'y'], [42, 7, 'y'], [43, 7, 'y'], [44, 7, 'y'], [45, 7, 'y'], [46, 7, 'y'], [37, 8, 'y'], [38, 8, 'y'], [39, 8, 'y'], [40, 8, 'y'], [41, 8, 'y'], [42, 8, 'y'], [43, 8, 'y'], [44, 8, 'y'], [45, 8, 'y'], [46, 8, 'y']] },
    /* ифрит: красный дух огня, пламя вместо волос и ног, золотые браслеты и пояс, ятаган (56×58) */
    efreet: {
      hd: true, unit: 2,
      rows: [
        '......................FF....FF...................llll...',
        '.....................FFF...FFF....FF..........lllllll...',
        '....................FFff...ffFF..FFF.........llllee.....',
        '...................FFfff.ffffFFFFFF.........lllle.......',
        '...................FffffffffffffFF.........lllle........',
        '..................FFfffffffffffffF.........lllel........',
        '..................Ffffffffffffffff.........llel.........',
        '..................ffffffffffffffff.........lell.........',
        '..................fffrrrrrrrrrrfff.........lel..........',
        '..................ffrrrrrrrrrrrrff..........ll..........',
        '..................frrrrrrrrrrrrrrf.........rrlr.........',
        '..................rrrrrrrrrrrrrrrr........rrrrrr........',
        '..................rrryyyrrrrryyyrr........rrrrrr........',
        '..................rrrykyrrrrrykyrr.......rrrrrrr........',
        '..................rrryyyrrrrryyyrr.......rrrrrrr........',
        '..................rrrrrrrrrrrrrrrr......rryyyyyy........',
        '...................rrrrRRRRRRRrrr.......rryyyyyy........',
        '...................rrrRwRwRwRwRrr......rrrrrr...........',
        '....................rrrRRRRRRRrr......rrrrrr............',
        '.....................rrrrrrrrrr.......rrrrrr............',
        '.......................rrrrrr........rrrrrr.............',
        '..............rrrrrrrrrrrrrrrrrrrrrrrrrrrr..............',
        '............rrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..............',
        '...........rrrrrr.rrrrrooooooorrrrr.rrrrr...............',
        '...........rrrrrr.rrrroooooooooorrr.rrrrr...............',
        '...........rrrrrr.rrroooooRRoooorrr.rrrr................',
        '...........rrrrrr.rrroooooRRoooorrr.....................',
        '...........rrrrrr.rrrroooooooooorrr.....................',
        '...........yyyyyy.rrrrrooooooorrrrr.....................',
        '...........yyyyyy.rrrrrrrrrrrrrrrrr.....................',
        '...........rrrrrr.rrrrrrroRRRorrrrr.....................',
        '...........rrrrrr.rrrrrrrrrrrrrrrrr.....................',
        '...........rrrrrr.yyyyyyyyyyyyyyyyy.....................',
        '...........rrrrrr.yyYyYyYyYyYyYyYyy.....................',
        '..................yyyyyyyyyyyyyyyyy.....................',
        '................FFFFffffffffffffFFFF....................',
        '...............FFFFFffffffffffffFFFFF...................',
        '...............FFFFFffffffffffffFFFFF...................',
        '................FFFFffffwwwwffffFFFF....................',
        '................FFFFffffwwwwffffFFFF....................',
        '................FFFFffffwwwwffffFFFF....................',
        '................FFFFffffwwwwffffFFFF....................',
        '................FFFFffffwwwwffffFFFF....................',
        '................FFFFffffwwwwffffFFFF....................',
        '................FFFFffffffffffffFFFF....................',
        '................FF.ffffffffffffff.FF....................',
        '................F.FFFFFffffffFFFFF.F....................',
        '..................FFFFFffffffFFFFF......................',
        '.................FFFFFFffffffFFFFFF.....................',
        '.................FFFFFFffffffFFFFFF.....................',
        '................FFFFFFFffffffFFFFFFF....................',
        '................FFFFFFFffffffFFFFFFF....................',
        '.................FFFFFFFFFFFFFFFFFF.....................',
        '...................FFfFFFFFFFFfFF.......................',
        '......................FFFFFFFF..........................',
        '.....................FFFFFFFFFF.........................',
        '.....................FFFFffFFFF.........................',
        '......................FFF..FFF..........................',
      ],
    },
    /* султан ифритов: синее пламя, золотая корона */
    efreet_sultan: { base: 'efreet', tint: { F: 'b', f: 'c' }, extra: [[19, 7, 'Y'], [20, 7, 'Y'], [21, 7, 'Y'], [22, 7, 'Y'], [23, 7, 'Y'], [24, 7, 'Y'], [25, 7, 'Y'], [26, 7, 'Y'], [27, 7, 'Y'], [28, 7, 'Y'], [29, 7, 'Y'], [30, 7, 'Y'], [31, 7, 'Y'], [32, 7, 'Y'], [19, 8, 'Y'], [20, 8, 'Y'], [21, 8, 'Y'], [22, 8, 'Y'], [23, 8, 'Y'], [24, 8, 'Y'], [25, 8, 'Y'], [26, 8, 'Y'], [27, 8, 'Y'], [28, 8, 'Y'], [29, 8, 'Y'], [30, 8, 'Y'], [31, 8, 'Y'], [32, 8, 'Y'], [19, 5, 'Y'], [20, 5, 'Y'], [25, 5, 'Y'], [26, 5, 'Y'], [31, 5, 'Y'], [32, 5, 'Y'], [19, 6, 'Y'], [20, 6, 'Y'], [25, 6, 'Y'], [26, 6, 'Y'], [31, 6, 'Y'], [32, 6, 'Y']] },
    /* дьявол: высокий красный рогатый, широкие кожаные крылья, золотой трезубец, хвост, копыта (64×60) */
    devil: {
      hd: true, unit: 2,
      rows: [
        '....................iii..................iiiy.yy.yy.............',
        '....................iiii................iiiiy.yy.yy.............',
        '..DN.................iiii..............iiiiyy.yy.yy........NN...',
        '..DDN.................iiii............iiii.yy.yy.yy.......NDD...',
        '..DDDN.................iiiirrrrrrrrrriiii..yy.yy.yy......NDDD...',
        '..DDDDN.................iiirrrrrrrrrriii...yy.yy.yy.....NDDDD...',
        '.DDDDDDN.................rrrrrrrrrrrrrr....yyyyyyyy....NDDDDDD..',
        '.DDDDDDDND..............rrrrrrrrrrrrrrrr...yyyyyyyy..DNDDDDDDD..',
        '.DDDDDDDDNN............rrrrrrrrrrrrrrrrrr.....yy....NNDDDDDDDD..',
        '.DDDDDDDDDDN...........rrrryyyrrrrrryyyrr.....yy...NDDDDDDDDDD..',
        '.DDDDDDDDDDDN..........rrrrykyrrrrrrykyrr.....yy..NDDDDDDDDDDD..',
        'DDDDDDDDDDDDDN.........rrrryyyrrrrrryyyrr.....yy.NDDDDDDDDDDDDD.',
        'DDDDDDDDDDDDDDN........rrrrrrrrrrrrrrrrrr.....yyNDDDDDDDDDDDDDD.',
        'DDDDDDDDDDDDDDDN........rrrRRRRRRRRRRrrr......yyDDDDDDDDDDDDDDD.',
        'DDDDDDDDDDDDDDDDNN......rrRwRwRwRwRwRrrr.....NyyDDDDDDDDDDDDDDD.',
        'DDDDDDDDDDDDDDDDDDN......rrRRRRRRRRRRrr.....NDyyDDDDDDDDDDDDDDD.',
        'DDDDDDDDDDDDDDDDDDDN......rrrrrrrrrrrr.....NDDyyDDDDDDDDDDDDDDD.',
        'DDDDDDDDDDDDDDDDDDDDN.......rrrrrrrr......NDDDyyDDDDDDDDDDDDDDD.',
        'DDDDDDDDDDDDDDDDDDDDDN.rrrrrrrrrrrrrrrrrrNDDDDyyDDDDDDDDDDDDDDD.',
        '.DDDDDDDDDDDDDDDDDDDrrrrrrrrrrrrrrrrrrrrrrrrDDyyDDDDDDDDDDDDDD..',
        '.DDDDDDDDDDDDDDDDDrrrrrr.rrrrrrrrrrrrrrNrrrrrryyDDDDDDDDDDDDDD..',
        '.DDDDDDDDDDDDDDDDDrrrrrr.rrrrrrrrrrrrrrNrrrrrryyDDDDDDDDDDDDDD..',
        '.DDDDDDDDDDDDDDDDDrrrrrrNrrrrrooooorrrrNrrrrrryyDDDDDDDDDDDDDD..',
        '.DDDDDDDDDDDDDDDDDrrrrrrNrrrrrooooorrrrNrrrrrryyDDDDDDDDDDDDDD..',
        '..DDDDDDDDDDDDDDNNrrrrrr.rrrroooooooorrDrrrrrryyDDDDDDDDDDDDD...',
        '..DDDDDDDDDDDDDDNNrrrrrr.rrrroooooooorrDrrrrrryyDDDDDDDDDDDDD...',
        '..DDDDDDDDDNNNNNDDrrrrrr.rrrooooRRoooorDrrrrrryyNNNNDDDDDDDDD...',
        '..DDDDDDDDDNNNNNDDrrrrrr.rrrooooRRoooorDrrrrrryyNNNNDDDDDDDDD...',
        '..DDDDDNNNNDDDDDDDrrrrrr.rrrooooRRoooorDrrrrrryyDDDDNNNNDDDDD...',
        '..DDDDDNNNNDDDDDDDrrrrrr.rrrooooRRoooorDrrrrrryyDDDDNNNNDDDDD...',
        '..DNNNN.DDDDDDDDDDrrrrrr.rrrroooooooorrDrrrrrryyDDDDDDD.NNNND...',
        '..DNNNN.DDDDDDDDDDrrrrrr.rrrroooooooorrDrrrrrryyDDDDDDD.NNNND...',
        '...N....DDDDDDDDDNrrrrrr.rrrrrooooorrrrDrrrrrryyDDDDDDD.....N...',
        '...N....DDDDDDDDDNrrrrrr.rrrrrooooorrrrDrrrrrryyDDDDDDD.....N...',
        '........DDDDDDDDNDrrrrrr.rrrrrrrrrrrrrrDrrrrrryyDDDDDDD.........',
        '........DDDDDDDDNDrrrrrr.rrrrrrrrrrrrrrDrrrrrryyDDDDDDD.........',
        '.......DDDDDDDNNDDrrrrrr.rrrrroRRRRorrrDrrrrrryyNDDDDDDD........',
        '.......DDDDDDDNNDDrrrrrr.rrrrroRRRRorrrDrrrrrryyNDDDDDDD........',
        '.......DDDDDDNDDDDrrrrrr.rrrrrroRRRorrrDrrrrrryyDNDDDDDD........',
        '.......DDDDDDNDDDDrrrrrr.rrrrrroRRRorrrDrrrrrryyDNDDDDDD........',
        '.......DDDDDNDDDDDrrrrrr.rrrrrrrrrrrrrrDrrrrrrrrrDNDDDDD........',
        '.......DDDDDNDDDDDrrrrrr.rrrrrrrrrrrrrrDrrrrrrrrrDNDDDDD........',
        '.......DDDDNDDDDDDrrrrrr.rrrrrrrrrrrrrrDrrrrrrrrrDDNDDDD........',
        '......DDDNNDDDDDDDiiiiii.rrrrrrrrrrrrrrDrrrrrrrrrDDDNNDDD.......',
        '......DDNDDRRDDDDDiiiiii.DDDDDDDDDDDDDDDrrrrrrrrrDDDDDNDD.......',
        '......DNDD.RRDDDDDDDDDDD.DDDDDDDDDDDDDDDDDDDDDyyDDD..DDND.......',
        '......ND..RRRRDDDDDDDD...DDDDDDDDDDDDDD..DDDDDyyDDD....DN.......',
        '......N...RRRRDDDDDD.....DDDDDDDDDDDDDD....DDDyyDDD......N......',
        '.........RRRRRRDDD....rrrrrrrrr..rrrrrr......DyyDDD.............',
        '.........RRRRRRD.....rrrrrrrrrr..rrrrrr.......yyDDD.............',
        '...........rrrr.....rrrr.rrrrrr..rrrrrr.......yy.DD.............',
        '............rrr...rrrrr..rrrrrr..rrrrrr.......yy................',
        '.............rrr.rrrrr...rrrrrr..rrrrrr.......yy................',
        '.............rrrrrrr.....rrrrrr..rrrrrr.......yy................',
        '..............rrrrr......rrrrrr..rrrrrr.......yy................',
        '...............rrr.......rrrrrr..rrrrrr.......yy................',
        '.........................rrrrrr..rrrrrr.........................',
        '........................rrrrrr....rrrrrr........................',
        '........................DDDDDD....DDDDDD........................',
        '........................DDDDDD....DDDDDD........................',
      ],
    },
    /* архидьявол: пурпурно-чёрный с золотом, огненная аура у копыт */
    arch_devil: { base: 'devil', tint: { r: 'x', R: 'z', o: 'p', D: 'z', N: 'E', y: 'y' }, extra: [[15, 52, 'F'], [16, 52, 'F'], [17, 52, 'F'], [13, 53, 'F'], [14, 53, 'F'], [15, 53, 'F'], [16, 53, 'F'], [17, 53, 'F'], [18, 53, 'F'], [19, 53, 'F'], [13, 54, 'F'], [14, 54, 'F'], [15, 54, 'F'], [16, 54, 'F'], [17, 54, 'F'], [18, 54, 'F'], [19, 54, 'F'], [12, 55, 'F'], [13, 55, 'F'], [14, 55, 'F'], [15, 55, 'F'], [16, 55, 'F'], [17, 55, 'F'], [18, 55, 'F'], [19, 55, 'F'], [20, 55, 'F'], [12, 56, 'F'], [13, 56, 'F'], [14, 56, 'F'], [15, 56, 'F'], [16, 56, 'F'], [17, 56, 'F'], [18, 56, 'F'], [19, 56, 'F'], [20, 56, 'F'], [12, 57, 'F'], [13, 57, 'F'], [14, 57, 'F'], [15, 57, 'F'], [16, 57, 'F'], [17, 57, 'F'], [18, 57, 'F'], [19, 57, 'F'], [20, 57, 'F'], [12, 58, 'F'], [13, 58, 'F'], [14, 58, 'F'], [15, 58, 'F'], [16, 58, 'F'], [17, 58, 'F'], [18, 58, 'F'], [19, 58, 'F'], [20, 58, 'F'], [12, 59, 'F'], [13, 59, 'F'], [14, 59, 'F'], [15, 59, 'F'], [16, 59, 'F'], [17, 59, 'F'], [18, 59, 'F'], [19, 59, 'F'], [20, 59, 'F'], [16, 55, 'f'], [15, 56, 'f'], [16, 56, 'f'], [17, 56, 'f'], [14, 57, 'f'], [15, 57, 'f'], [16, 57, 'f'], [17, 57, 'f'], [18, 57, 'f'], [14, 58, 'f'], [15, 58, 'f'], [16, 58, 'f'], [17, 58, 'f'], [18, 58, 'f'], [14, 59, 'f'], [15, 59, 'f'], [16, 59, 'f'], [17, 59, 'f'], [18, 59, 'f'], [45, 52, 'F'], [46, 52, 'F'], [47, 52, 'F'], [43, 53, 'F'], [44, 53, 'F'], [45, 53, 'F'], [46, 53, 'F'], [47, 53, 'F'], [48, 53, 'F'], [49, 53, 'F'], [43, 54, 'F'], [44, 54, 'F'], [45, 54, 'F'], [46, 54, 'F'], [47, 54, 'F'], [48, 54, 'F'], [49, 54, 'F'], [42, 55, 'F'], [43, 55, 'F'], [44, 55, 'F'], [45, 55, 'F'], [46, 55, 'F'], [47, 55, 'F'], [48, 55, 'F'], [49, 55, 'F'], [50, 55, 'F'], [42, 56, 'F'], [43, 56, 'F'], [44, 56, 'F'], [45, 56, 'F'], [46, 56, 'F'], [47, 56, 'F'], [48, 56, 'F'], [49, 56, 'F'], [50, 56, 'F'], [42, 57, 'F'], [43, 57, 'F'], [44, 57, 'F'], [45, 57, 'F'], [46, 57, 'F'], [47, 57, 'F'], [48, 57, 'F'], [49, 57, 'F'], [50, 57, 'F'], [42, 58, 'F'], [43, 58, 'F'], [44, 58, 'F'], [45, 58, 'F'], [46, 58, 'F'], [47, 58, 'F'], [48, 58, 'F'], [49, 58, 'F'], [50, 58, 'F'], [42, 59, 'F'], [43, 59, 'F'], [44, 59, 'F'], [45, 59, 'F'], [46, 59, 'F'], [47, 59, 'F'], [48, 59, 'F'], [49, 59, 'F'], [50, 59, 'F'], [46, 55, 'f'], [45, 56, 'f'], [46, 56, 'f'], [47, 56, 'f'], [44, 57, 'f'], [45, 57, 'f'], [46, 57, 'f'], [47, 57, 'f'], [48, 57, 'f'], [44, 58, 'f'], [45, 58, 'f'], [46, 58, 'f'], [47, 58, 'f'], [48, 58, 'f'], [44, 59, 'f'], [45, 59, 'f'], [46, 59, 'f'], [47, 59, 'f'], [48, 59, 'f']] },
  });
})();
