/* ============================================================================
   view/sprites_objects.js — спрайты объектов карты приключений и боя:
   шахты, кучи ресурсов, сундук/костёр/артефакт, жилища существ, бонусные
   объекты, банки существ, препятствия карты и боя, осадные стены.
   Якорь везде — низ по центру; здания стоят на нижней строке.
   Флаг владельца не рисуем (его рисует движок) — у шахт/жилищ верхний правый
   угол оставлен свободным под флажок.
   Подключать после js/view/sprites.js. Формат — см. docs/sprite-guide.md.
   ========================================================================== */
(function () {
  'use strict';
  H3.Sprites.defineMany({

    /* ------------------------------------------------------------------
       ШАХТЫ 32×28
       ------------------------------------------------------------------ */
    mine_gold: { rows: [
      '................................',
      '...........kk...................',
      '..........kllk..................',
      '.........klleek.................',
      '........kllyeeek................',
      '.......klleeyeeek...............',
      '......kllleeeyeeek..............',
      '.....klleeyeeeeEEk..............',
      '....kllleeeeyeeeEEk.............',
      '...klleeyeeeeeeeEEEk............',
      '..klleeeeeeyeeeeEEEEk...........',
      '.klleeyeeeeeeeeeeEEEEk..........',
      'klleeeeeeekkkkkeeeEEEEk.........',
      'kleeyeeeekNNNNNkeeyEEEEk........',
      'kleeeeeekNnnnnnNkeeeEEEEk.......',
      'keeeeeeekNnkkkkNkeeeeEEEEk......',
      'keeyeeeekNkzzzkNkeeeeeEEEEk.....',
      'keeeeeeekNkzzzkNkeeyeeEEEEEk....',
      'kEeeeeeekNkzzzkNkeeeeeeEEEEEk...',
      'kEeeyeeekNkzzzkNkeeeeeeeEEEEEk..',
      'kEEeeeeekNkzzzkNkeeeeeeeeEEEEEk.',
      'kEEeeeeekNkzzzkNkeeekkkkkkeEEEEk',
      'kEEEeeeekNkzzzkNkeekyyYyyykEEEEk',
      'kEEEEeeekNkzzzkNkeekNnnnnnkEEEEk',
      'kkkkkkkkkkkzzzkkkkkkkNnnnnnkkkkk',
      '.........ttzzztt.....kkkkkkk....',
      '........tttttttt.....kEkkkEk....',
      '........kkkkkkkk......kk.kk.....',
    ] },

    mine_wood: { rows: [
      '................................',
      '................................',
      '................kk..............',
      '...............kRRk.............',
      '..............kRrrRk............',
      '.............kRrrrrRk...........',
      '............kRrrrrrrRk..........',
      '...........kRrrrrrrrrRk.........',
      '..........kRrrrrrrrrrrRk........',
      '.........kRrrrrrrrrrrrrRk.......',
      '........kRrrrrrrrrrrrrrrRk......',
      '.......kRRRRRRRRRRRRRRRRRRk.....',
      '.......kkkkkkkkkkkkkkkkkkkk.....',
      '........kTnnnnnnnnnnnnnnNk......',
      '........kTnnnnnnnnnnnnnnNk......',
      '........kTnnkkkknnnnnnnnNk......',
      '........kTnkleelknnnnnnnNk......',
      '........kTkleeeelknkkkknNk......',
      '........kTkleekeelkNzzNkNk......',
      '........kTkleeeeelkNzzNkNk......',
      '.....kkkkTkkleeelkkNzzNkNk......',
      '....kTTnkTnnkkkknnkNzzNkNk......',
      '...kTnnnNknnnnnnnnkNzzNkNk......',
      '.kkkNnnnNkkknnnnnnkNzzNkNk......',
      'kTnNkkkkkTnknnnnnnkNzzNkNk......',
      'kTnnNkTTnnNknnnnnnkNzzNkNk......',
      'kNnnNkTnnnNknnnnnnkNzzNkNk......',
      'kkkkkkkkkkkkkkkkkkkkkkkkkk......',
    ] },

    mine_ore: { rows: [
      '................................',
      '................................',
      '................................',
      '..........kkkk..................',
      '........kkleeekk................',
      '......kkleeeeeeEkk..............',
      '....kkleeeeleeeeeEkk............',
      '...kleeeleeeeeeeeeEEk...........',
      '..kleeeeeeeeeleeeeeEEk..........',
      '.kleeeeeeeeeeeeeeeeeEEk.........',
      'kleeeleeeeeeeeeeeeleeEEk........',
      'kleeeeeeeeeeeeeeeeeeeEEEk.......',
      'keeeeeeeekkkkkkkeeeeeeEEEk......',
      'keeeeeeekNnnnnnNkeeeleeEEEk.....',
      'keeeeeeekNkkkkkNkeeeeeeEEEEk....',
      'keeleeeekNkzzzkNkeeeeeeeEEEEk...',
      'kEeeeeeekNkzzzkNkeeeeeeeeEEEEk..',
      'kEeeeeeekNkzzzkNkEeeleeeeeEEEEk.',
      'kEEeeeeekNkzzzkNkEeeeeeeeeeEEEEk',
      'kEEeeeeekNkzzzkNkEEeeeeeeeeeEEEk',
      'kEEEeeeekNkzzzkNkEEeeeeeeeeeEEEk',
      'kEEEeeeekNkzzzkNkEEEeeeeeeeeEEEk',
      'kkkkkkkkkNkzzzkNkkkkkkkkkkkkkkkk',
      '.....kkk.kkzzzkk..kkk.....kkk...',
      '....kleek.tzzzt..kleek...klek...',
      '...kleeEek.ttt..kleeEek.kleEk...',
      '...kEEEEEk.....kEEEEEEk.kEEEk...',
      '...kkkkkkk.....kkkkkkkk.kkkkk...',
    ] },

    mine_mercury: { rows: [
      '............kk..................',
      '...........kppk.................',
      '..........kpApPk................',
      '.........kpAppPPk...............',
      '........kpApppPPPk..............',
      '.......kpApppppPPPk.............',
      '......kppppppppPPPPk............',
      '.....kPPPPPPPPPPPPPPk...........',
      '.....kkkkkkkkkkkkkkkk...........',
      '.....kllleeeeeeeeeeEk...........',
      '.....kleeeeeeeeeeeeEk...........',
      '.....kleeekkkkeeeeeEk....kkkk...',
      '.....kleeekcwckeeeeEk....kcwck..',
      '.....kleeekcwckeeeeEk....kcwck..',
      '.....kleeekcwckeeeeEk....kcwck..',
      '.....kleeekkkkkeeeeEk...kkcwckk.',
      '.....kleeeeeeeeeeeeEk..kccccccck',
      '.....kleeeeeeeeeeeeEk.kcwcccccck',
      '.....kleeeeekkkkkeeEk.kcwcccccck',
      '.....kleeeekNnnnNkeEk.kcwcccccck',
      '.....kleeeekNkkkNkeEkkcclllllcck',
      '.....kleeeekNkzzNkeEkkclwlllllck',
      '.....kleeeekNkzzNkeEkkclllllelck',
      '.....kEeeeekNkzzNkEEkkclllllelck',
      '.....kEeeeekNkzzNkEEk.kclllllelk',
      '.....kEEeeekNkzzNkEEk.kkcllllekk',
      '.....kEEEeekNkzzNkEEk..kkkkkkkk.',
      '.....kkkkkkkkkzzkkkkk...........',
    ] },

    mine_sulfur: { rows: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '..............kkkk..............',
      '...........kkkyyyykkk...........',
      '.........kkyyyyyyyyyykk.........',
      '.......kkyyyyyyyyyyyyyYkk.......',
      '.....kkyyyyyyyyyyyyyyyyYYkk.....',
      '....kyyyyyyyykkkkkkyyyyyYYYk....',
      '...kyyyyyyyykNNNNNNkyyyyyYYYk...',
      '..kyyyyyyyykNkkkkkkNkyyyyYYYYk..',
      '.kyyyyyyyykNkzzzzzzkNkyyyyYYYYk.',
      'kyyyyyyyykNkzzzzzzzzkNkyyyYYYYYk',
      'kyyyyyyyykNkzzzzzzzzkNkyyYYYYYYk',
      'kYyyyyyyykNkzzzzzzzzkNkyYYYYYYYk',
      'kYyyyyyyyykNkzzzzzzkNkyyYYYYYYYk',
      'kYYyyyyyyyykNNkkkkNNkyyyYYYYYYYk',
      'kYYyyyyyyyyykkkkkkkkyyyYYYYYYYYk',
      'kYYYyyyyyyyyyyyyyyyyyyYYYYYYYYYk',
      'kYYYYyyyyyyyyyyyyyyyYYYYYYYYYYYk',
      'kkkkYYYYyyyyyyyyyyYYYYYYYYYYYYYk',
      '...kkkkkYYYYYYYYYYYYYYYYYYYkkkkk',
      '........kkkkkkkkkkkkkkkkkkk.....',
    ] },

    mine_crystal: { rows: [
      '................................',
      '................................',
      '................................',
      '........kk......................',
      '.......kwmk.....................',
      '.......kmmmk...kk...............',
      '......kwmmmk..kwck..............',
      '......kmmmmmk.kcck..............',
      '.....kwmmmmmkkkcckk.............',
      '.....kmmmmmmkwcccck.............',
      '....kwmmmmmMkcccccck............',
      '....kmmmmMMMkcccccck............',
      '...kkmmmMMMkkccccCCkk...........',
      '..kEkmMMMMkeeecCCCCkEk..........',
      '.kEEkkkkkkkeeekkkkkkEEk.........',
      '.kEeeeeeeeeeeeeeeeeeeEEk........',
      'kEeeeeeeekkkkkkkkkeeeeEEk.......',
      'kEeeeeeekzzzzzzzzzkeeeeEEk......',
      'kEeeeeekzzzzzzzzzzzkeeeeEEk.....',
      'kEeeeekzzzzmzzzzzzzzkeeeeEEk....',
      'kEeeeekzzzmwmzzzczzzkeeeeeEEk...',
      'kEeeeekzzmmmmzzcwczzkeeekkeEEk..',
      'kEEeeekzzmmMmzzcccczkeekwmkeEEk.',
      'kEEeeekzzmmMmzcccCczkeekmmmkeEEk',
      'kEEEeekzmMMMmzccCCczkeekmMMkEEEk',
      'kEEEeekzmMMMMzccCCCzkeekMMMkEEEk',
      'kEEEEekkkkkkkkkkkkkkkEEkkkkkEEEk',
      'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    ] },

    mine_gems: { rows: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '..........kk....................',
      '.........khgk.......kk..........',
      '.........kgGk......khgk.........',
      '........kkggkk.....kgGk.........',
      '.......kddkkddk...kkggkk........',
      '.....kkdddddddkk.kddkkddkk......',
      '...kkdddddddddddkkddddddddkk....',
      '..kdddddkkkkkkkkkkkkkkkkkddddk..',
      '.kddddkkccccccccccccccccckkdddk.',
      'kdddkkcccbbbbbbbbbbbbbbbccckkddk',
      'kddkcccbbbbbbbbbbbbbbbbbbbccckdk',
      'kdkccbbbbbbbbkkkbbbbbbbbbbbcckdk',
      'kdkcbbbbbbbbkhgGkbbbbbbbbbbbckdk',
      'kdkcbbbbbbbbkgGGkbbbbkkkbbbbckdk',
      'kdkccbbbbbbbbkkkbbbbkhgGkbbcckdk',
      'kddkccbbbbbbbbbbbbbbkgGGkbcckddk',
      'kddkkcccbbbbbbbbbbbbbkkkccckkddk',
      'kdddkkccccbbbbbbbbbbccccckkdddk.',
      'kkddddkkkccccccccccccckkkddddkk.',
      '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
    ] },

    /* ------------------------------------------------------------------
       КУЧИ РЕСУРСОВ 14×12
       ------------------------------------------------------------------ */
    res_gold: { rows: [
      '..............',
      '.....kkk......',
      '....kyYyk.....',
      '....kNNNk.....',
      '...kyyyyyk....',
      '..kyyyyyyyk...',
      '.kyyyyyyyyYk..',
      '.kyyyyyyyYYk..',
      '.kyyyyyyYYYkk.',
      '.kYyyyyYYYkyyk',
      '..kYYYYYYYkYyk',
      '...kkkkkkkkkkk',
    ] },
    res_wood: { rows: [
      '..............',
      '..............',
      '...kkkkkkkk...',
      '..kTTTTTTTNk..',
      '..kTnnnnnnNk..',
      '..kNnnnnnnNk..',
      '.kkkkkkkkkkkk.',
      'kTTTTTTkTTTTNk',
      'kTnnnnnkTnnnNk',
      'kNnnnnnkNnnnNk',
      'kNNNNNNkNNNNNk',
      'kkkkkkkkkkkkkk',
    ] },
    res_ore: { rows: [
      '..............',
      '..............',
      '..............',
      '.....kkk......',
      '....klleEk....',
      '...kleeeEEk...',
      '..kkleeeeEEkk.',
      '.klekeeeEEkeEk',
      'kleeEkEEEkeeEk',
      'kleeEEkkkeeEEk',
      'kEEEEEEkEEEEEk',
      'kkkkkkkkkkkkkk',
    ] },
    res_mercury: { rows: [
      '.....kkkk.....',
      '.....kcwk.....',
      '.....kcwk.....',
      '.....kcwk.....',
      '....kkcwkk....',
      '...kccccccck..',
      '..kccccccccck.',
      '..kclwlllllck.',
      '..kcllllllelk.',
      '..kclllllelck.',
      '...kklllleck..',
      '....kkkkkkk...',
    ] },
    res_sulfur: { rows: [
      '..............',
      '..............',
      '..............',
      '..............',
      '......kk......',
      '....kkyyk.....',
      '...kyyyyYk....',
      '..kyyyyyyYk...',
      '.kyyyyyyyYYk..',
      'kyyyyyyyYYYYk.',
      'kYyyyyyYYYYYYk',
      'kkkkkkkkkkkkkk',
    ] },
    res_crystal: { rows: [
      '......kk......',
      '.....kwmk.....',
      '.....kmmk.....',
      '..kk.kmmMk....',
      '.kwmkkmmMk.kk.',
      '.kmmkmmmMkkwmk',
      '.kmMkmmmMkmmMk',
      'kmmMkmmMMkmmMk',
      'kmmMkmMMMkmMMk',
      'kmMMkmMMMkMMMk',
      'kMMMkMMMMkMMMk',
      'kkkkkkkkkkkkkk',
    ] },
    res_gems: { rows: [
      '..............',
      '..............',
      '..............',
      '......kk......',
      '.....khgk.....',
      '..kk.kggGk.kk.',
      '.khgkgggGkhgk.',
      'khggkgggGkgGGk',
      'kgggGkggGkgGGk',
      'kgGGGkkkkkGGGk',
      'kGGGGkgGGkGGGk',
      'kkkkkkkkkkkkkk',
    ] },

    /* ------------------------------------------------------------------
       СУНДУК 16×14, КОСТЁР 18×18, АРТЕФАКТ 14×14
       ------------------------------------------------------------------ */
    chest: { rows: [
      '................',
      '.....kkkkkk.....',
      '...kkTTTTTTkk...',
      '..kyTnnnnnnTyk..',
      '.kyynnnnnnnnyyk.',
      '.kYkkkkkkkkkkYk.',
      '.kyNnnnkykNnnyk.',
      '.kynnnnkykNnnyk.',
      '.kynnnnkkkNnnyk.',
      '.kynnnnnnnNnnyk.',
      '.kynnnnnnnNNnyk.',
      '.kYyNNNNNNNNYYk.',
      '.kYkkkkkkkkkkYk.',
      '.kkk........kkk.',
    ] },
    campfire: { rows: [
      '........kk........',
      '.......kfk........',
      '.......kffk.......',
      '......kfyfk.......',
      '.....kFfyffk......',
      '....kFffyyfFk.....',
      '....kFfyyyfFk.....',
      '...kFFfyyyffFk....',
      '...kFfyyyyyfFk....',
      '..kFFfyyyyyffFk...',
      '..kFFffyyyffFFk...',
      '..kkFFffffffFFkk..',
      '.kNNkFFfffffFkNNk.',
      'kTnnNkkFFFFFkkNnTk',
      'kTnnnNNkkkkkNNnnTk',
      'kNnnnnnNNNNNnnnnNk',
      '.kNNNNNNNNNNNNNNk.',
      '..kkkkkkkkkkkkkk..',
    ] },
    artifact: { rows: [
      '......A.......',
      '....A.kk.A....',
      '.....kywk.....',
      '..A.kyyyyk.A..',
      '....kyYyyk....',
      '.A...kyYk...A.',
      '..A..kkkk..A..',
      '....kkeekk....',
      '...kleeeeEk...',
      '....kkeekk....',
      '.....keek.....',
      '....kkeekk....',
      '...kleeeeEk...',
      '...kkkkkkkk...',
    ] },

    /* ------------------------------------------------------------------
       ЖИЛИЩА СУЩЕСТВ 32×30 (1 — хижина … 7 — врата с сиянием)
       ------------------------------------------------------------------ */
    dwelling_1: { rows: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '..............kk................',
      '.............kTTk...............',
      '...........kkTTnnkk.............',
      '.........kkTTnnnnnnkk...........',
      '.......kkTTnnnnnnnnnnkk.........',
      '.....kkTTnnnnnnnnnnnnNNkk.......',
      '...kkTTnnnnnnnnnnnnnnNNNNkk.....',
      '..kTTnnnnnnnnnnnnnnnnnNNNNNk....',
      '..kNNNNNNNNNNNNNNNNNNNNNNNNk....',
      '..kkkkkkkkkkkkkkkkkkkkkkkkkk....',
      '....kttttttttttttttttttStk......',
      '....ktttttkkkkttttttttttSk......',
      '....kttttkNnnNktttkkkkttSk......',
      '....kttttkNkkNktttkzzkttSk......',
      '....kttttkNkzNktttkzzkttSk......',
      '....kttttkNkzNktttkkkkttSk......',
      '....kttttkNkzNkttttttttSSk......',
      '....kttttkNkzNkttttttttSSk......',
      '....kSttttkzzkttttttttSSSk......',
      '....kSSSSSkkkkSSSSSSSSSSSk......',
      '....kkkkkkkkkkkkkkkkkkkkkk......',
    ] },

    dwelling_2: { rows: [
      '................................',
      '................................',
      '..........kkkkkkkkkk............',
      '.........kNNNNNNNNNNk...........',
      '........kNnnnnnnnnnnNk..........',
      '.......kNnnnnnnnnnnnnNk.........',
      '......kNNNNNNNNNNNNNNNNk........',
      '......kkkkkkkkkkkkkkkkkk........',
      '.......kTknkkkkkkkknkNk.........',
      '.......kTknkzzzzzzknkNk.........',
      '.......kTknkzzzzzzknkNk.........',
      '.......kTknkzzzzzzknkNk.........',
      '.......kTknkkkkkkkknkNk.........',
      '.......kTnnnnnnnnnnnnNk.........',
      '......kkkkkkkkkkkkkkkkkk........',
      '......kTTTTTTTTTTTTTTNNk........',
      '......kkkkkkkkkkkkkkkkkk........',
      '.......kNnkkNnnnnnNkkNk.........',
      '.......kNnk.kNkkkkNk.kNk........',
      '.......kNnk.kNnnnnNk.kNk........',
      '.......kNnk.kNkkkkNk.kNk........',
      '.......kNnk.kNnnnnNk.kNk........',
      '.......kNnk.kNkkkkNk.kNk........',
      '.......kNnk.kNnnnnNk.kNk........',
      '.......kNnk.kNkkkkNk.kNk........',
      '.......kNnk.kNnnnnNk.kNk........',
      '.......kNnk.kNkkkkNk.kNk........',
      '......kkNnkkkNnnnnNkkkNkk.......',
      '.....kNNnnNNkNNNNNNkNNNNNk......',
      '.....kkkkkkkkkkkkkkkkkkkkk......',
    ] },

    dwelling_3: { rows: [
      '................................',
      '................................',
      '................................',
      '................................',
      '..........kk....................',
      '.........kRRk...................',
      '........kRrrRk..................',
      '.......kRrrrrRk.................',
      '......kRrrrrrrRk................',
      '.....kRrrrrrrrrRk...............',
      '....kRrrrrrrrrrrRk..............',
      '...kRrrrrrrrrrrrrRk.............',
      '..kRRRRRRRRRRRRRRRRk............',
      '..kkkkkkkkkkkkkkkkkk............',
      '...kTtttttttttttttSk............',
      '...kTttkkkkttkkkkttSk...........',
      '...kTttkzzkttkNnNkttSk..........',
      '.k.kTttkzzkttkNkNkttSk.k........',
      'kTkkTttkkkkttkNkNkttSkkTk...k...',
      'kTkTkkkkkkkkkkNkNkkkkkTkTk.kTk..',
      'kTkTkTkTkTkTkTkTkTkTkTkTkTkTkTkk',
      'kTkTkTkTkTkTkTkTkTkTkTkTkTkTkTNk',
      'kTkTkTkTkTkTkTkTkTkTkTkTkTkTkTNk',
      'kTkTkTkTkTkTkTkTkTkTkTkTkTkTkTNk',
      'kNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNk',
      'kTkTkTkTkTkTkTkTkTkTkTkTkTkTkTNk',
      'kTkTkTkTkTkTkTkTkTkTkTkTkTkTkTNk',
      'kTkTkTkTkTkTkTkTkTkTkTkTkTkTkTNk',
      'kNkNkNkNkNkNkNkNkNkNkNkNkNkNkNNk',
      'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    ] },

    dwelling_4: { rows: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '.kkkkkkkk..............kkkkkkkk.',
      '.klkklkkl..............lkklkklk.',
      '.klleeeel..............leeeeElk.',
      '.klleeeelkkkkkkkkkkkkkkleeeeElk.',
      '.klleeeelkllkkllkkllkkleeeeeElk.',
      '.klleeeelklleeeeeeeeeeleeeeeElk.',
      '.kleeeeelkleeeeeeeeeeeeeeeeeElk.',
      '.kleekkelkleeeeeeeeeeeeeeekkElk.',
      '.kleekzkelkleeeeekkkkkeeeeekzkElk',
      '.kleekkelkleeeeekNnnNkeeeeekkElk.',
      '.kleeeeelkleeeeekNkkNkeeeeeeElk.',
      '.kleeeeelkleeeeekNkzNkeeeeeeElk.',
      '.kleeeeelkleeeeekNkzNkeeeeeeElk.',
      '.kEeeeeelkleeeeekNkzNkeeeeeeElk.',
      '.kEeeeeelkleeeeekNkzNkeeeeeeElk.',
      '.kEeeeeelkEeeeeekNkzNkeeeeeEElk.',
      '.kEEeeeelkEeeeeekNkzNkeeeeeEElk.',
      '.kEEeeeeEkEEeeeekNkzNkeeeeEEElk.',
      '.kEEEeeeEkEEEeeekNkzNkeeeEEEElk.',
      '.kEEEEeeEkEEEEEEkNkzNkEEEEEEElk.',
      '.kkkkkkkkkkkkkkkkkkzzkkkkkkkkkkk',
      '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
    ] },

    dwelling_5: { rows: [
      '................................',
      '................................',
      '................................',
      '..............kk................',
      '.............kwwk...............',
      '............kwwlik..............',
      '...........kwwllyik.............',
      '..........kwwlllyyik............',
      '.........kwwllllyyiik...........',
      '........kwwlllllyyiiik..........',
      '.......kwwllllllyyiiiik.........',
      '......kwwlllllllyyiiiiik........',
      '.....kwwllllllllyyiiiiiik.......',
      '....kwwlllllllllyyiiiiiiik......',
      '...kwwwwwwwwwwwwwwwwwwwwwwk.....',
      '...kkkkkkkkkkkkkkkkkkkkkkkk.....',
      '....kwlkkwlkkwlkkwlkkwlkkwlk....',
      '....kwlkkwlkkwlkkwlkkwlkkwlk....',
      '....kwlk.kwlkkwlkkwlk.kwlkwlk...',
      '....kwlk.kwlk.kwlk.kwlk.kwlk....',
      '....kwlk.kwlk.kwlk.kwlk.kwlk....',
      '....kwlk.kwlkkzzzkkkwlk.kwlk....',
      '....kwlk.kwlk.kzzk.kwlk.kwlk....',
      '....kwlk.kwlk.kzzk.kwlk.kwlk....',
      '....kwlk.kwlk.kzzk.kwlk.kwlk....',
      '....kwlkkkwlkkkzzkkkwlkkkwlk....',
      '...kwwwwwwwwwwwzzwwwwwwwwwwwk...',
      '..kwwwwwwwwwwwwzzwwwwwwwwwwwwk..',
      '.klllllllllllllzzllllllllllllllk',
      'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    ] },

    dwelling_6: { rows: [
      '..............kk................',
      '.............kbBk...............',
      '............kbbBBk..............',
      '...........kbbbBBBk.............',
      '..........kbbbbBBBBk............',
      '.........kbbbbbBBBBBk...........',
      '........kbbbbbbBBBBBBk..........',
      '.......kBBBBBBBBBBBBBBk.........',
      '......kkkkkkkkkkkkkkkkkk........',
      '......klkklkklkklkklkkEk........',
      '......klleeeeeeeeeeeeeEk........',
      '......klleeeeeeeeeeeeeEk........',
      '......kkkkkkkkkkkkkkkkkk........',
      '.......kleeeekkkkeeeeEk.........',
      '.......kleeeekzzkeeeeEk.........',
      '.......kleeeekzzkeeeeEk.........',
      '.......kleeeeekkeeeeeEk.........',
      '.......kleeeeeeeeeeeeEk.........',
      '.......kleeeeeeeeeeeeEk.........',
      '.......kleeeekkkkeeeeEk.........',
      '.......kleeeekzzkeeeeEk.........',
      '.......kleeeekzzkeeeeEk.........',
      '.......kleeeeekkeeeeeEk.........',
      '.......kleeeeeeeeeeeeEk.........',
      '.......kleeeekkkkkeeeEk.........',
      '.......kleeekNnnnNkeeEk.........',
      '.......kleeekNkkkNkeeEk.........',
      '.......kleeekNkzzNkeeEk.........',
      '......kkleeekNkzzNkeeEkk........',
      '.....kkkkkkkkkkzzkkkkkkkk.......',
    ] },

    dwelling_7: { rows: [
      '................................',
      '................................',
      '................................',
      '...........kkkkkkkk.............',
      '.........kkEeeeeeeEkk...........',
      '.......kkEeeeeeeeeeeEkk.........',
      '.....kkEeeeekkkkkkeeeeEkk.......',
      '....kEeeeekkAAAAAAkkeeeeEk......',
      '...kEeeeekAAAaaaaAAAkeeeeEk.....',
      '..kEeeeekAaaaaaaaaaaAkeeeeEk....',
      '.kEeeeekAaaaaaaaaaaaaAkeeeeEk...',
      'kEeeeekAaaaaaaaaaaaaaaAkeeeeEEk.',
      'kEeeeekAaaaaawwaaaaaaaAkeeeeEEk.',
      'kEeeeekAaaaawwwwaaaaaaAkeeeeEEEk',
      'kEeeeekAaaaawwwwaaaaaaAkeeeeEEEk',
      'kEeeeekAaaaaawwaaaaaaaAkeeeeEEEk',
      'kEeeeekAaaaaaaaaaaaaaaAkeeeeEEEk',
      'kEeeeekAaaaaaaaaaaaaaaAkeeeeEEEk',
      'kEeeeekAaaaaaaaaaaaaaaAkeeeeEEEk',
      'kEeeeekAaaaaaaaaaaaaaaAkeeeeEEEk',
      'kEeeeekAaaaaaaaaaaaaaaAkeeeeEEEk',
      'kEeeeekAaaaaaaaaaaaaaaAkeeeeEEEk',
      'kEeeeekAaaaaaaaaaaaaaaAkeeeeEEEk',
      'kEeeeekAaaaaaaaaaaaaaaAkeeeeEEEk',
      'kEeeeekAaaaaaaaaaaaaaaAkeeeeEEEk',
      'kEeeeekAaaaaaaaaaaaaaaAkeeeeEEEk',
      'kEeeeekAaaaaaaaaaaaaaaAkeeeeEEEk',
      'kEeeeekAAAAAAAAAAAAAAAAkeeeeEEEk',
      'kEEeeekkkkkkkkkkkkkkkkkkeeeEEEEk',
      'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    ] },

    /* ------------------------------------------------------------------
       БОНУСНЫЕ ОБЪЕКТЫ (24×24, если не сказано иное)
       ------------------------------------------------------------------ */
    learning_stone: { rows: [
      '.........kkkk...........',
      '........kleeEk..........',
      '.......kleeeeEk.........',
      '.......kleAeeEk.........',
      '.......kleAAeEk.........',
      '.......kleeAeEk.........',
      '.......kleeeeEk.........',
      '.......kleAAAEk.........',
      '.......kleeAeEk.........',
      '.......kleeAeEk.........',
      '.......kleeeeEk.........',
      '.......kleAeAEk.........',
      '.......kleeAeEk.........',
      '.......kleAeAEk.........',
      '.......kleeeeEk.........',
      '.......kleeeeEk.........',
      '.......kleeeeEk.........',
      '......kkleeeeEkk........',
      '.....kleeeeeeeeEk.......',
      '....kkkkkkkkkkkkkk......',
      '...kEeeeeeeeeeeeEEk.....',
      '..kEEeeeeeeeeeeEEEEk....',
      '.kEEEEEEEEEEEEEEEEEEk...',
      '.kkkkkkkkkkkkkkkkkkkk...',
    ] },

    tree_knowledge: { rows: [
      '............kkkk............',
      '..........kkyyyykk..........',
      '.........kyywwyyyyk.........',
      '........kyywyyyyyyYk........',
      '.......kyyyyyyyyyyYYk.......',
      '......kyywyyyyyyyyyYYk......',
      '.....kyyyyyyyyyyyyyYYYk.....',
      '....kyyywyyyyyyyyyyYYYYk....',
      '....kyyyyyyyyyyyyyyyYYYk....',
      '...kyyyyyyyyyyyyyyyyYYYYk...',
      '...kyyywyyyyyyyyyyyyYYYYk...',
      '...kyyyyyyyyyyyyyyyyyYYYk...',
      '...kYyyyyyyyyyyyyyyyYYYYk...',
      '....kYyyyyyyyyyyyyyYYYYk....',
      '....kYYyyyyyyyyyyyYYYYYk....',
      '.....kYYyyyyyyyyyYYYYYk.....',
      '......kYYYyyyyyyYYYYYk......',
      '.......kkYYYkkkkYYYkk.......',
      '.........kkkNnnNkkk.........',
      '...........kNnnnNk..........',
      '...........kNnnnNk..........',
      '...........kNnnnNk..........',
      '...........kNnnnNk..........',
      '...........kNnnnNk..........',
      '...........kNnnnNk..........',
      '...........kNnnnNk..........',
      '..........kkNnnnNkk.........',
      '.........kNNNnnnNNNk........',
      '........kNNNNnnnNNNNk.......',
      '.......kkkkkkkkkkkkkkk......',
      '......kjjjjjjjjjjjjjjjk.....',
      '......kkkkkkkkkkkkkkkkk.....',
    ] },

    shrine_1: { rows: [
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........kkkkkkk.........',
      '.......kiiiiiiik........',
      '.......kiIkkkIik........',
      '.......kiIIIIIik........',
      '......kkkkkkkkkkk.......',
      '.....klllllllllllk......',
      '.....kkkkkkkkkkkkk......',
      '......kleeeeeeeEk.......',
      '......kleeeeeeeEk.......',
      '......kleeeeeeeEk.......',
      '......kleeeeeeeEk.......',
      '......kleeeeeeeEk.......',
      '....kklleeeeeeeEEkk.....',
      '...kllleeeeeeeeeEEEk....',
      '...kkkkkkkkkkkkkkkkk....',
    ] },

    shrine_2: { rows: [
      '...........kk...........',
      '..........kyyk..........',
      '..........kkkk..........',
      '..........kbBk..........',
      '.........kbbBBk.........',
      '........kbbbBBBk........',
      '.......kbbbbBBBBk.......',
      '......kbbbbbBBBBBk......',
      '.....kbbbbbbBBBBBBk.....',
      '....kbbbbbbbBBBBBBBk....',
      '...kBBBBBBBBBBBBBBBBk...',
      '...kkkkkkkkkkkkkkkkkk...',
      '....kllllllllllllllk....',
      '....kllkkkkllllllllk....',
      '....kllkiiikllkkklek....',
      '....kllkiIiklkiiiklek...',
      '....kllkiiikllkiiklek...',
      '....kllkkkkklkkkkklek...',
      '....klllllllllllllelk...',
      '....kllllkkkkkllllelk...',
      '....kllllkNnNkllllelk...',
      '....kllllkNzNkllllelk...',
      '..kkllllllkNzNkllllelkk.',
      '.kkkkkkkkkkkkkkkkkkkkkkk',
    ] },

    shrine_3: { rows: [
      '...........kk...........',
      '..........kyyk..........',
      '...........kk...........',
      '..........kyyk..........',
      '.........kyyyYk.........',
      '........kyyyyYYk........',
      '.......kyyyyyYYYk.......',
      '......kyyyyyyYYYYk......',
      '.....kYYYYYYYYYYYYk.....',
      '....kkkkkkkkkkkkkkkk....',
      '...kwwwwwwwwwwwwwwwwk...',
      '...kkkkkkkkkkkkkkkkkk...',
      '..kwlkwlkwiiiwkwlkwlk...',
      '..kwlkwlkiIIIikwlkwlk...',
      '..kwlkwlkiiiiikwlkwlk...',
      '..kwlkwlkwiiiwkwlkwlk...',
      '..kwlkwlkwwwwwkwlkwlk...',
      '..kwlkwlkwwzzwkwlkwlk...',
      '..kwlkwlkwwzzwkwlkwlk...',
      '..kwlkwlkwwzzwkwlkwlk...',
      '..kwlkwlkwwzzwkwlkwlk...',
      '.kwwwwwwwwwwzzwwwwwwwwk.',
      'klllllllllllzzlllllllllk',
      'kkkkkkkkkkkkkkkkkkkkkkkk',
    ] },

    magic_well: { rows: [
      '........................',
      '.........kkkkkk.........',
      '.......kkNNNNNNkk.......',
      '.....kkNnnnnnnnnNkk.....',
      '...kkNnnnnnnnnnnnnNkk...',
      '..kNNNNNNNNNNNNNNNNNNk..',
      '..kkkkkkkkkkkkkkkkkkkk..',
      '....kNk....c.....kNk....',
      '....kNk..c.....c.kNk....',
      '....kNk....ccc...kNk....',
      '....kNk.c.cwcc.c.kNk....',
      '....kNk...ccwc...kNk....',
      '....kNk..c.ccc...kNk....',
      '....kNkkkkkkkkkkkkNk....',
      '..kkkkleeeeeeeeeeeEkkk..',
      '.klleekkkkkkkkkkkkkeeEk.',
      'kleeekcccccccccccckeeEk.',
      'kleeekcccwwwcccccckeeEEk',
      'kleeekccccwccccccckeeEEk',
      'kEeeeekcccccccccckeeeEEk',
      'kEeeeeekkkkkkkkkkeeeeEEk',
      'kEEeeeeeeeeeeeeeeeeeEEEk',
      'kEEEeeeeeeeeeeeeeeeEEEEk',
      'kkkkkkkkkkkkkkkkkkkkkkkk',
    ] },

    fountain_fortune: { rows: [
      '...........kk...........',
      '..........kggk..........',
      '.........kgGkgGk........',
      '.........kgggGGk........',
      '..........kkGkk.........',
      '...........kkk..........',
      '..........kcwck.........',
      '.........kkcccck........',
      '........klleeeeEk.......',
      '........kkkkkkkkk.......',
      '.......c.kleeeEk.c......',
      '......cc.kleeeEk.cc.....',
      '.....c.c.kleeeEk.c.c....',
      '....kkkkkkkkkkkkkkkkk...',
      '...kleeeeeeeeeeeeeeEEk..',
      '..kkkkkkkkkkkkkkkkkkkkk.',
      '.kleekccccccccccccckeEEk',
      'kleeekcbbbbbbbbbbbckeeEk',
      'kleeekcbbbbbbbbbbbckeeEk',
      'kEeeeekkkkkkkkkkkkkeeEEk',
      'kEeeeeeeeeeeeeeeeeeeeEEk',
      'kEEeeeeeeeeeeeeeeeeeEEEk',
      'kEEEEeeeeeeeeeeeeeEEEEEk',
      'kkkkkkkkkkkkkkkkkkkkkkkk',
    ] },

    temple: { rows: [
      '...........kk...........',
      '..........kyyk..........',
      '........kkkyykkk........',
      '........kyyyyyyk........',
      '........kkkyykkk........',
      '..........kyyk..........',
      '..........kkkk..........',
      '.........kwwwwk.........',
      '........kwwwwwlk........',
      '.......kwwwwwwllk.......',
      '......kwwwwwwwlllk......',
      '.....kwwwwwwwwllllk.....',
      '....kwwwwwwwwwlllllk....',
      '...kwwwwwwwwwwllllllk...',
      '..kkkkkkkkkkkkkkkkkkkk..',
      '..kwwwwwwwwwwwwwwwwwLk..',
      '..kwwkkkwwwwwwwwwkkkLk..',
      '..kwwkbbkwwkkkkwwkbbLk..',
      '..kwwkbBkwkNnnNkwkbBLk..',
      '..kwwkkkkwkNkkNkwkkkLk..',
      '..kwwwwwwwkNkzNkwwwwLk..',
      '..kwwwwwwwkNkzNkwwwwLk..',
      '..kLLwwwwwkNkzNkwwwLLk..',
      '..kkkkkkkkkkkkkkkkkkkk..',
    ] },

    rally_flag: { rows: [
      '.........kk.............',
      '........klek............',
      '........kkkk............',
      '........kNkkkkkkkkkkkk..',
      '........kNkrrrrrrrrrrwk.',
      '........kNkrrwwwwwwwrwk.',
      '........kNkrrwrrrrrrrwk.',
      '........kNkrrwwwwwwwrwk.',
      '........kNkrrwrrrrrrRwk.',
      '........kNkrrwwwwwwwRwk.',
      '........kNkRRRRRRRRRRRk.',
      '........kNkkkkkkkkkkkk..',
      '........kNk.............',
      '........kNk.............',
      '........kNk.............',
      '........kNk.............',
      '........kNk.............',
      '........kNk.............',
      '........kNk.............',
      '........kNk.............',
      '.......kkNkk............',
      '......kleeeEk...........',
      '.....kleeeeEEk..........',
      '.....kkkkkkkkk..........',
    ] },

    oasis: { rows: [
      '........kk..............',
      '......kkggkkk...........',
      '....kkgggggggkk.........',
      '...kggkkggGkkggk........',
      '..kgGk.kgGk..kGk........',
      '.kgGk..kNGk...kk........',
      '.kGk..kkNnkk............',
      '.kk..kgGkNkGgk..........',
      '....kgGk.kNkGgk.........',
      '...kGk...kNk.kGk........',
      '...kk....kNk..kk........',
      '.........kNk............',
      '........kNnk............',
      '........kNnk............',
      '........kNnk............',
      '........kNnk............',
      '.......kNnnk............',
      '.......kNnnk...kkkkkk...',
      '......kkNnnkkkkccccccck.',
      '.....kttkkkktkccbbbbbbck',
      '....kttttttttkcbbbbbbbck',
      '...ktttttttttkccbbbbbcck',
      '..ktttttttttttkkcccccckk',
      '.kkkkkkkkkkkkkkkkkkkkkk.',
    ] },

    windmill: { rows: [
      'kk.......kkkk...........',
      'kTk......kNNk...........',
      'kTTk.....kNNk...........',
      '.kTTk....kNNk...........',
      '..kTTk...kNNk...........',
      '...kTTk..kNNk...........',
      '....kTTk.kNNk...........',
      '.....kTTkkNNk...........',
      '......kTkkNkk...........',
      '.......kkkkk.k..........',
      '.......kNkkk..k.........',
      '......kkNkkkk..k........',
      '.....kNNkkkkk...k.......',
      '....kNNk.klleEk..k......',
      '...kNNk..klleEk...k.....',
      '..kNNk..kleeeEEk...k....',
      '.kNNk...kleeeEEk....k...',
      'kNNk...kleeekkeEk....k..',
      'kkk....kleeekzkEk.....kk',
      '.......kleeekkeEEk......',
      '......kleeeeeeeEEk......',
      '......kleeeeeeeEEk......',
      '......kleeeeeeeEEEk.....',
      '.....kleeeeeeeeEEEk.....',
      '.....kleeekkkkeEEEk.....',
      '.....kleeekNnNkEEEk.....',
      '....kleeeekNkNkeEEEk....',
      '....kleeeekNkzkeEEEk....',
      '....kleeeekNkzkeEEEk....',
      '....kEeeeekNkzkeEEEk....',
      '...kkEEEEEkkzzkEEEEEk...',
      '...kkkkkkkkkkkkkkkkkk...',
    ] },

    water_wheel: { rows: [
      '........................kkk.',
      '.......kkkkkkkkk.......kNNNk',
      '......kNnnnnnnnNk......kNTNk',
      '.....kNnnnnnnnnnNk.....kNTNk',
      '....kNnnnnnnnnnnnNk....kNTNk',
      '...kNNNNNNNNNNNNNNNk...kNTNk',
      '...kkkkkkkkkkkkkkkkk...kNTNk',
      '....kTtttttttttttSk....kNTNk',
      '....kTtttkkkkttttSk..kkkNTNkk',
      '....kTtttkzzkttttSkkkTTkNTNkTk',
      '....kTtttkzzkttttSkTTkkkNNNkkTk',
      '....kTtttkkkkttttSkTkTTTkTkTTkTk',
      '....kTtttttttttttSkkTkkkkkkkkTkk',
      '....kTttttttttttSSkTkTkNNNkTkTk.',
      '....kTtkkkkkttttSSkTkTkNTNkTkTk.',
      '....kTtkNnNkttttSSkTkTkNTNkTkTk.',
      '....kTtkNkNkttttSSkTkkTkkkTkkTk.',
      '....kTtkNkzkttttSSkkTkkTTTkkTkk.',
      '....kTtkNkzkttttSSSkkTTkTkTTkk..',
      '....kTtkNkzkttttSSSkkkkkNkkkk...',
      '....kSSkNkzkSSSSSSSkkkkkkkkkkk..',
      '.kkkkkkkkzzkkkkkkkkkcccccccccck.',
      'kccccccccccccccccccccbbbbbbbbbck',
      'kcbbbbbbbbbbbbbbbbbbbbbbbbbbbbck',
      'kcbbbbbbbbbbbbbbbbbbbbbbbbbbbbck',
      'kcbbbbbbbbbbbbbbbbbbbbbbbbbbbbck',
      'kccbbbbbbbbbbbbbbbbbbbbbbbbbbcck',
      'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    ] },

    witch_hut: { rows: [
      '.........kk.............',
      '........kNNk............',
      '.......kNnnNk...........',
      '......kNnnnnNk..........',
      '.....kNnnnnnnNk.........',
      '....kNnnnnnnnnNk........',
      '...kNnnnnnnnnnnNk.......',
      '..kNnnnnnnnnnnnnNk......',
      '.kNNNNNNNNNNNNNNNNk.....',
      '.kkkkkkkkkkkkkkkkkk.....',
      '..kdddkkkdddkkkdddk.....',
      '..kdddkiikdddkzzkdk.....',
      '..kdddkkkkdddkzzkdk.....',
      '..kdddkiIikddkkkkdk.....',
      '..kdddkkkkkdddddddk.....',
      '..kddddkkkddddddddk.....',
      '..kddddkNkkkkdddddk.....',
      '..kddddkNkzzkdddddk.....',
      '..kddddkNkzzkdddddk.....',
      '..kkkkkkkkkkkkkkkkk.....',
      '....kykk......kkyk......',
      '....kykk......kkyk......',
      '...kyyyk......kyyyk.....',
      '...kkkkk......kkkkk.....',
    ] },

    arena: { rows: [
      '................................',
      '................................',
      '................................',
      '................................',
      '..........kkkkkkkkkkkk..........',
      '.......kkkllllllllllllkkk.......',
      '.....kklllllkklkklkklllllkk.....',
      '...kkllllkklkkkkkkkkkllkkllkk...',
      '..kllllkkleeeeeeeeeeeeekkllllk..',
      '.kllllkleeeeeeeeeeeeeeeeekllllk.',
      'kllkkkleeeeeeeeeeeeeeeeeeekkkllk',
      'kllkkleeeetttttttttttteeeeekkllk',
      'kllkkleeetttttttttttttteeeeekllk',
      'kleekleeettttttttttttttteeeekeek',
      'kleekleeettttttttttttttteeeekeek',
      'kleekleeeettttttttttttteeeeekeek',
      'kleeekleeeetttttttttttteeeekeeEk',
      'kEeeeekleeeeeeeeeeeeeeeeeekeeeEk',
      'kEeeeeekkleeeeeeeeeeeeeekkeeeEEk',
      'kEEeeeeeekkkkkkkzzkkkkkkeeeeEEEk',
      '.kEEeeeeeeeeeeekzzkeeeeeeeeEEEk.',
      '..kEEeeeeeeeeeekzzkeeeeeeeEEEk..',
      '...kkEEEEEEEEEkkzzkkEEEEEEEkk...',
      '.....kkkkkkkkkkkzzkkkkkkkkkk....',
    ] },

    mercenary_camp: { rows: [
      '.........kk.............',
      '.........kyk............',
      '.........kkk............',
      '.........kek............',
      '.........kek............',
      '........kklkk...........',
      '.......kyyyyyk..........',
      '.......kkkNkkk..........',
      '.........kNk............',
      '.........kNk............',
      '.........kk......kk.....',
      '........kttk....kttk....',
      '.......kttttk..kttttk...',
      '......kttttttk.kttttSk..',
      '.....kttttttttkttttttSk.',
      '....kttttkkktttkttttttSk',
      '...kttttkzzzkttkttkkkttk',
      '..kttttkzzzzzkttktkzzkSk',
      '.kttttkzzzzzzzktkttkzzkk',
      '.kSSSSkzzzzzzzkkSSSSSSSk',
      '.kkkkkkkkkkkkkkkkkkkkkkk',
      '.kjjjjjjjjjjjjjjjjjjjjjk',
      '.kGjjjjjjjjjjjjjjjjjjjGk',
      '.kkkkkkkkkkkkkkkkkkkkkkk',
    ] },

    marletto_tower: { rows: [
      '.........kk.........',
      '........kPPk........',
      '........kppk........',
      '.......kppPPk.......',
      '.......kppPPk.......',
      '......kpppPPPk......',
      '......kpppPPPk......',
      '.....kppppPPPPk.....',
      '.....kppppPPPPk.....',
      '....kPPPPPPPPPPk....',
      '....kkkkkkkkkkkk....',
      '....klkklkklkkEk....',
      '....kleeeeeeeeEk....',
      '....kkkkkkkkkkkk....',
      '.....kleekkkeeEk....',
      '.....kleekzkeeEk....',
      '.....kleekkkeeEk....',
      '.....kleeeeeeeEk....',
      '.....kleeeeeeeEk....',
      '.....kleekkkeeEk....',
      '.....kleekzkeeEk....',
      '.....kleekkkeeEk....',
      '.....kleeeeeeeEk....',
      '.....kleeeeeeeEk....',
      '.....kleekkkeeEk....',
      '.....kleekzkeeEk....',
      '.....kleekkkeeEk....',
      '.....kleeeeeeeEk....',
      '.....kleekkkkeEk....',
      '.....kleekNzNkEk....',
      '....kkleekNzNkEkk...',
      '....kkkkkkkkkkkkk...',
    ] },

    star_axis: { rows: [
      '.......kkkkkkk..........',
      '.....kkbbcccbbkk........',
      '....kbbccwwcccbbk.......',
      '...kbbccwwccccbbBk......',
      '..kbbcccwccccbbbBBk.....',
      '..kbbccccccccbbbBBk.....',
      '.kbbccccccccbbbbBBBk....',
      '.kyyyyyyyyyyyyyyyyyyk...',
      '.kYYYYYYYYYYYYYYYYYYk...',
      '.kbbbbbbbbbbbbbbBBBBk...',
      '..kbbbbbbbbbbbbBBBBk....',
      '..kbbbbbbbbbbbbBBBBk....',
      '...kbbbbbbbbbbBBBBk.....',
      '....kBbbbbbbbBBBBk......',
      '.....kkBBBBBBBBkk.......',
      '.......kkkkkkkk.........',
      '.........kyYk...........',
      '.........kyYk...........',
      '.........kyYk...........',
      '........kkyYkk..........',
      '.......kleeeeEk.........',
      '......kleeeeeeEk........',
      '.....kEEEEEEEEEEk.......',
      '.....kkkkkkkkkkkk.......',
    ] },

    garden_revelation: { rows: [
      '........................',
      '........................',
      '...........A............',
      '.........A.A.A..........',
      '..........AAA...........',
      '.......AAAAwAAAA........',
      '..........AAA...........',
      '..kk.....A.A.A.....kk...',
      '.kmmk......A......kyyk..',
      '.kmmk.kk...k..kk..kyyk..',
      '..kk.kyykkkGkkrrk..kk...',
      '.kGk.kyykGkGkGrrk..kGk..',
      '..kGkkkkkGkGkGkkk.kGk...',
      '...kGkGGkGkGkGkGkkGk....',
      '...kkGkGkGkGkGkGkGkk....',
      '....kGkGkGkGkGkGkGk.....',
      '..kkkkkkkkkkkkkkkkkkkk..',
      '.kjjjjjjjjjjjjjjjjjjjjk.',
      'kjjjjjjjjjjjjjjjjjjjjjjk',
      'kjjjjjjjjjjjjjjjjjjjjjjk',
      'kHjjjjjjjjjjjjjjjjjjjjHk',
      'kHHjjjjjjjjjjjjjjjjjjHHk',
      'kHHHHHHHHHHHHHHHHHHHHHHk',
      'kkkkkkkkkkkkkkkkkkkkkkkk',
    ] },

    observatory: { rows: [
      '...................kk...',
      '..................kEk...',
      '.................kEEk...',
      '................keEk....',
      '...............kekk.....',
      '..............kekk......',
      '.........kkkkkkekk......',
      '.......kkbbbbbekBkk.....',
      '......kbbbbbbkkbBBk.....',
      '.....kbbbbbbbbbbBBBk....',
      '.....kbbbbbbbbbbBBBk....',
      '....kBBBBBBBBBBBBBBBk...',
      '....kkkkkkkkkkkkkkkkk...',
      '.....klkklkklkklkkEk....',
      '.....klleeeeeeeeeeEk....',
      '.....kkkkkkkkkkkkkkk....',
      '......kleeekkkkeeEk.....',
      '......kleeekzzkeeEk.....',
      '......kleeekzzkeeEk.....',
      '......kleeeekkeeeEk.....',
      '......kleeeeeeeeeEk.....',
      '......kleeeeeeeeeEk.....',
      '......kleeekkkkeeEk.....',
      '......kleeekzzkeeEk.....',
      '......kleeekzzkeeEk.....',
      '......kleeeekkeeeEk.....',
      '......kleeeeeeeeeEk.....',
      '......kleeekkkkeeEk.....',
      '......kleeekNnNkeEk.....',
      '......kleeekNkzkeEk.....',
      '.....kkleeekNkzkeEkk....',
      '.....kkkkkkkkkkkkkkk....',
    ] },

    trading_post: { rows: [
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '..kkkkkkkkkkkkkkkkkkkk..',
      '.kwwrrwwrrwwrrwwrrwwrrk.',
      '.kkkkkkkkkkkkkkkkkkkkkk.',
      '.kNk................kNk.',
      '.kNk................kNk.',
      '.kNk................kNk.',
      '.kNk................kNk.',
      '.kNk.....kkk........kNk.',
      '.kNk..kk.kgk..kk....kNk.',
      '.kNk.kbbkkgk.kyyk...kNk.',
      '.kNk.kbBkkGkkkyYk...kNk.',
      '.kNkkkkkkkkkkkkkkkkkkNk.',
      '.kNkTTTTTTTTTTTTTTTTkNk.',
      '.kNkkkkkkkkkkkkkkkkkkNk.',
      '.kNkNnnnnnnnnnnnnnnNkNk.',
      '.kNkNnkkkkkkkkkkkkkNkNk.',
      '.kNkNnnnnnnnnnnnnnnNkNk.',
      '.kNkNNNNNNNNNNNNNNNNkNk.',
      '.kkkkkkkkkkkkkkkkkkkkkk.',
    ] },

    hill_fort: { rows: [
      '.....kkkk......kkkk.............',
      '.....klklkkkkkkklklk............',
      '.....kleelkllklleeEk............',
      '.....kleelleeelleeEk............',
      '.....kleeeeeeeeeeeEk............',
      '.....kleeekkkkeeeeEk............',
      '.....kleekNnnNkeeeEk............',
      '.....kleekNkkNkeeeEk............',
      '.....kleekNkzNkeeeEk............',
      '.....kEeekNkzNkeeEEk............',
      '...kkkkkkkkkzzkkkkkkkk..........',
      '..kgggjjjjjkzzkjjjjjjjk.........',
      '.kgggjjjjjjkzzkjjjjjjjjk........',
      'kgggjjjjjjjkzzkjjjjjjjjjk.......',
      'kggjjjjjjjkzzkjjjjjjjjjjjk......',
      'kgjjjjjjjjkzzkjjjjjjjjjjjjk.....',
      'kgjjjjjjjkzzkjjjjjjjjjjjjjjk....',
      'kjjjjjjjjkzzkjjjjjjjjjjjjjjjk...',
      'kjjjjjjjjkzzkjjjjjjjjjjjjjjjjk..',
      'kjjjjjjjkzzkjjjjjjjjjjjjjjjjjjk.',
      'kjjjjjjjkzzkjjjjjjjjjjjjjjjjjjHk',
      'kjjjjjjkzzkjjjjjjjjjjjjjjjjjjHHk',
      'kHjjjjjkzzkjjjjjjjjjjjjjjjjjHHHk',
      'kHjjjjkzzkjjjjjjjjjjjjjjjjjjHHHk',
      'kHHjjjkzzkjjjjjjjjjjjjjjjjjHHHHk',
      'kHHjjjkttkjjjjjjjjjjjjjjjjHHHHHk',
      'kHHHjjkttkjjjjjjjjjjjjjjjHHHHHHk',
      'kkkkkkkttkkkkkkkkkkkkkkkkkkkkkkk',
    ] },

    tavern: { rows: [
      '............kk..............',
      '...........kNNk.............',
      '..........kNnnNk............',
      '.........kNnnnnNk...........',
      '........kNnnnnnnNk..........',
      '.......kNnnnnnnnnNk.........',
      '......kNnnnnnnnnnnNk........',
      '.....kNnnnnnnnnnnnnNk.......',
      '....kNnnnnnnnnnnnnnnNk......',
      '...kNNNNNNNNNNNNNNNNNNk.....',
      '...kkkkkkkkkkkkkkkkkkkk.....',
      '....kTttttttttttttttSk......',
      '....kTtkkkktttkkkkttSk.kkk..',
      '....kTtkyykttTkyykttSkkNNNk.',
      '....kTtkyykttTkyykttSkNTnNNk',
      '....kTtkkkkttTkkkkttSkNTnnNk',
      '....kTtttttttTttttttSkNTnnNk',
      '....kTtttttttTtttttttkkNNNNk',
      '....kTttkkkkkTttttttSk.kkkk.',
      '....kTtkNnnNkTttttttSk......',
      '....kTtkNkkNkTttttttSk......',
      '....kTtkNkzNkTttttttSk......',
      '....kTtkNkzNkTttttttSk......',
      '....kTtkNkzNkTttttttSk......',
      '....kTtkNkzNkTttttttSk......',
      '...kkStkNkzNkTttttttSSk.....',
      '..kSSSSSkzzkSSSSSSSSSSSk....',
      '..kkkkkkkkkkkkkkkkkkkkkk....',
    ] },
  });
})();
