/* ============================================================================
   view/sprites_objects_1_hd.js — шахты, кучи ресурсов, сундук, костёр и артефакт карты приключений
   в крупной сетке (unit 2), стиль Б: без контурной линии, форму держат тона. Якорь низ-центр.
   У шахт правый верхний угол (исходные x 54–66, строки 0–28) свободен под флажок владельца.
   Собирается скриптом dev/proto/objects_1_hd.py.
   ========================================================================== */
(function () {
  'use strict';
  H3.Sprites.defineMany({
    /* золотая шахта: серая скала с золотыми жилами, крепь входа, вагонетка с золотом на рельсах (64×56) */
    mine_gold: {
      hd: true, unit: 2,
      rows: [
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '......................EEEEEEEE..................................',
        '...................EEeeeEEEEEEEEE...............................',
        '................eeeeeeeeeeeeEEEEEEEE............................',
        '...............eeeeeeeeeeeeeeeEEEEEEE...........................',
        '.............eeeeeeeeeeeeeeeeeeEEEEEEEE.........................',
        '............eeeeeeeeeeeeeeeeeeeeEEEEEEEE........................',
        '...........eeeeeeeeeeeeeeeeeeeeeeeEEEEEEE.......................',
        '..........eeellllleeeeeeeeeeeeeeeeeEEEEEEE......................',
        '.........eeellllllleeeeeeeeeyyyyeeeEEEEEEEE.....................',
        '........EeellllllllleeeeeeeyyyyyyeeeEEEEEEEE....................',
        '.......EeellllllllllleeeeeeyyYYYYeeeeEEEEEEEE...................',
        '.......eeellllllllllleeeeeeeyyyyeeeeeeEEEEEEE...................',
        '......eeellllllllllllleeeeeeeeeeeeeeeeEEEEEEEE..................',
        '.....eeeellllllllllllleeeeeeeeeeeeeeeeeEEEEEEEE.................',
        '.....eeellllllllllllllleeeeeeeeeeeeeeeeEEEEEEEE.................',
        '....EeeellllllllllllllleeeeeeeeeeeeeeeeeEEEEEEEE................',
        '...EeeellllllllllllllllleeeeeeeeeeeeeeeeeEEEEEEEE...............',
        '...EeeellllllllllllllllleeeeeeeeeeeeeeeeeEEEEEEEE...............',
        '..EeeeellllyyyyyyllllllleeeeeeeeeeeeeeeeeEEEEEEEEE..............',
        '..EeeellllyyyyyyyyllllllleeeeeeeeeeeeeeeeeEEEEEEEE..............',
        '.EEeeellllyyyYYYYyllllllleeeeeeeeeeeeeeeeeEEEEEEEEE.............',
        '.EeeeelllllyyyyyylllllllleeeeeeeeeeeeeeeeeeEEEEEEEE.............',
        '.EeeeellllllllllllllllllleeeeeeeeeeeeeeeeeeEEEEEEEE.............',
        'EeeeellllllllllllllllllllleeeeeeeeeeeeeeeeeEEEEEEEEE............',
        'EeeeellllllllllllllllllllyyeeeeeeeeyyyyyyeeeEEEEffffyyy.........',
        'EeeeellllllllllllllllllyyyyyyeeeeeyyyyyyyyeeEEEffffffyyyy.......',
        'EeeeellllllllllllllllllyyYYYYeeeeeyyyYYYYyeeEEyffffffyyyyy......',
        'eeeeellllllllllllllllllllyyeeeeeeeeyyyyyyeeeEEyyffffyYYYYy......',
        'eeeellllllllllllllNNNNNNNNNNNNNNNNeeeeeeeeeeeEEyyyyyyYYYY.......',
        'eeeellllllllllllllNNNNNNNNNNNNNNNNeeeeeeeeeeeTTTnyyyyyynNNN.....',
        'eeeellllllllllllllNNNNNNNNNNNNNNNNeeeeeeeeeeeTTTnnnnnnnnNNN.....',
        'eeeellllllllllllllnnnzzzzzzzzzznnneeeeeeeeeeeTTTnnnnnnnnNNN.....',
        'eeeellllllllllllllnnnzzzzzzzzzznnneeeeeeeeeeeTTTnnnnnnnnNNN.....',
        'eeeelllllllllllllynnnzzzzzzzzzznnneeeeeeeeeeeTTTnnnnnnnnNNN.....',
        'eeeelllllllllllllynnnzzzzzzzzzznnneeeeeeeeeeeTTTnnnnnnnnNNN.....',
        'eeelllllllllllllllnnnzzzzzzzzzznnneeeeeeeeeeeTTTnnnnnnnnNNN.....',
        'eeelllllllllllllllnnnzzzzzzzzzznnneeeeeeeeyyyTTTnnnnnnnnNNN.....',
        'eeelllllllllllllllnnnzzzzzzzzzznnneeeeeeeyyyyTTTnnnnnnnnNNN.....',
        'eeelllllyyyyllllllnnnzzzzzzzzzznnneeeeeeeyyYYTTEEEnnnnEEENN.....',
        'eeellllyyyyyylllllnnnzzzzzzzzzznnneeeeeeeeyyyyEEEEEEEEEEEE......',
        'eeellllyyYYYYlllllnnnzzzzzzzzzznnneeeeeeeeeeeEElllEEEElllEE.....',
        'eeelllllyyyyllllllnnnzzzzzzzzzznnneeeeeeeeeeeEElllEEEElllEE.....',
        'eeelllllllllllllllnnnzzzzzzzzzznnneeeeeeeeeeeEElllEEEElllEE.....',
        'eeelllllllllllllllnnnzzzzzzzzzznnneeeeeeeeeeeeEEEEEEEEEEEE......',
        'eeelllllllllllllllnnnzzzzzzzzzznnneeeeeeeeeeeeeEEEeeeeEEEeeeee..',
        'eeelllllllllllllllnnnzzzzzzzzzznnneeeeeeeeeeeeeeeeeeeeeeeeeeee..',
        'eeelllllllllllllllnnnzzzzzzzzzznnneeeeeeEEEEEEEEEEEEEEEEEEEEEE..',
        'eeelllllllllllllllnnnzzzzzzzzzznnneeeeeeEEEEEEEEEEEEEEEEEEEEEE..',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
      ],
    },
    /* лесопилка: сруб с красной крышей и трубой, тёплое окно, штабель брёвен и колода справа (64×56) */
    mine_wood: {
      hd: true, unit: 2,
      rows: [
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '..........................rR.........llllllll...................',
        '.........................rrRR........llllllll...................',
        '........................rrrrRR.......llllllll...................',
        '.......................rrrrrRRR.......eeeeEE....................',
        '......................rrrrrrRRRR......eeeeEE....................',
        '.....................rrrrrrrrRRRR.....eeeeEE....................',
        '....................rrrrrrrrrRRRRR....eeeeEE....................',
        '...................rrrrrrrrrrrRRRRR...eeeeEE....................',
        '..................rrrrrrrrrrrrRRRRRR..eeeeEE....................',
        '.................rrrrrrrrrrrrrRRRRRRR.eeeeEE....................',
        '................rrrrrrrrrrrrrrrRRRRRRReeeeEE....................',
        '..............rrrrrrrrrrrrrrrrrRRRRRRReeeeEE....................',
        '.............rrrrrrrrrrrrrrrrrrrRRRRRReeeeEE....................',
        '............rrrrrrrrrrrrrrrrrrrrRRRRRReeeeEE....................',
        '...........rrrrrrrrrrrrrrrrrrrrrRRRRRRRRRRR.....................',
        '..........rrrrrrrrrrrrrrrrrrrrrrrRRRRRRRRRRR....................',
        '.........rrrrrrrrrrrrrrrrrrrrrrrrRRRRRRRRRRRR...................',
        '........rrrrrrrrrrrrrrrrrrrrrrrrrrRRRRRRRRRRRR..................',
        '.......rrrrrrrrrrrrrrrrrrrrrrrrrrrRRRRRRRRRRRRR...NN............',
        '......rrrrrrrrrrrrrrrrrrrrrrrrrrrrRRRRRRRRRRRRRR..NN............',
        '.....rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrRRRRRRRRRRRRRR.NN............',
        '..RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRNN............',
        '..RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRNNlllee.......',
        '..RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRNNlllee.......',
        '........NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTTTTNNlllee.......',
        '........NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTTTTNNlllee.......',
        '........TTTTnnnnyyyNNyyynnnnnnnnnnnnnnnnNNNNNNTTTTTTlllee.......',
        '........TTTTnnnnyyyNNyyynnnnnnnnnnnnnnnnNNNNNNnnnnnn............',
        '........TTTTnnnnyyyNNyyynnnnnnnnnnnnnnnnNNNNNNnnnnnn............',
        '........TTTTnnnnNNNNNNNNnnnnnnnnnnnnnnnnNNNNNNnnnnnn............',
        '........NNNNNNNNNNNNNNNNNNNNNNDDDDDDDNNNNNNNNN.....NNNN.........',
        '........NNNNNNNNyyyNNyyyNNNNNNDDDDDDDNNNNNNNNN....NnnnnN........',
        '........TTTTnnnnyyyNNyyynnnnNNDDDDDDDnnnNNNNNN...NnnTTnnN.......',
        '........TTTTnnnnyyyNNyyynnnnNNDDDDDDDnnnNNNNNN...NnTTTTnN.......',
        '........TTTTnnnnnnnnnnnnnnnnNNDDDDDDDnnnNNNNNN...NnTTTTnN.......',
        '........TTTTnnnnnnnnnnnnnnnnNNDDDDDDDnnnNNNNNN...NnnTTnnN.......',
        '........NNNNNNNNNNNNNNNNNNNNNNDDDDDDDNNNNNNNNN....NnnnnN........',
        '........NNNNNNNNNNNNNNNNNNNNNNDDDDDDDNNNNNNNNN.NNNNNNNNNNNN.....',
        '........TTTTnnnnnnnnnnnnnnnnNNDDDDDDDnnnNNNNNNNnnnnN..NnnnnN....',
        '........TTTTnnnnnnnnnnnnnnnnNNDDDDDDDnnnNNNNNNnnTTnnNNnnTTnnN...',
        '........TTTTnnnnnnnnnnnnnnnnNNDDDDDDDnnnNNNNNNnTTTTnNNnTTTTnN...',
        '........TTTTnnnnnnnnnnnnnnnnNNDDDDDDDnnnNNNNNNnTTTTnNNnTTTTnN...',
        '........NNNNNNNNNNNNNNNNNNNNNNDDDDDDDNNNNNNNNNnnTTnnNNnnTTnnN...',
        '........NNNNNNNNNNNNNNNNNNNNNNDDDDDDDNNNNNNNNNNnnnnN..NnnnnN....',
        '........TTTTnnnnnnnnnnnnnnnnNNDDDDDDDnnnNNNNNN.NNNN....NNNN.....',
        '........TTTTnnnnnnnnnnnnnnnnNNDDDDDDDnnnNNNNNN..................',
        '..jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj..',
        '..jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj..',
        '..jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj..',
        '....DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD....',
      ],
    },
    /* рудник: тёмная скала с рыжими пятнами руды, крепь входа, отвал камней справа (64×56) */
    mine_ore: {
      hd: true, unit: 2,
      rows: [
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '......................uuuuuuuu..................................',
        '..................uuuEEEuuuuuuuuuu..............................',
        '................EEEEEEEEEEEEuuuuuuuu............................',
        '...............EEEEEEEEEEEEEEEuuuuuuu...........................',
        '.............EEEEEEEEEEEEEEEEEEuuuuuuuu.........................',
        '............EEEEEEEEEEEEEEEEEEEEEuuuuuuu........................',
        '...........EEEEeEEEEEEEEEEEEEEEEEEuuuuuuu.......................',
        '..........EEEeeeeeEEEEEEEEEEEEEEEEEuuuuuuu......................',
        '.........EEeeeeeeeeeEEEEEEEEOOOOEEEEuuuuuuu.....................',
        '........EEEeeeeeeeeeEEEEEEEooooOOEEEEuuuuuuu....................',
        '.......EEEeeeeeeeeeeeEEEEEEOOOOOOEEEEuuuuuuuu...................',
        '......uEEeeeeeeeeeeeeeEEEEEEOOOOEEEEEEuuuuuuuu..................',
        '.....uEEEeeeeeeeeeeeeeEEEEEEEEEEEEEEEEEuuuuuuuu.................',
        '.....uEEeeeeeeeeeeeeeeeEEEEEEEEEEEEEEEEuuuuuuuu.................',
        '....uEEEeeeeeeeeeeeeeeeEEEEEEEEEEEEEEEEEuuuuuuuu................',
        '....EEEeeeeeeeeeeeeeeeeeEEEEEEEEEEEEEEEEuuuuuuuu................',
        '...uEEEeeeeeeeeeeeeeeeeeEEEEEEEEOOOOEEEEEuuuuuuuu...............',
        '..uEEEEeeeeeeeeeeeeeeeeeEEEEEEEooooOOEEEEuuuuuuuuu..............',
        '..uEEEeeeeeeeeeeeeeeeeeeeEEEEEEOOOOOOEEEEEuuuuuuuu..............',
        '.uuEEEeeeeeeeeeeeeeeeeeeeEEEEEEEOOOOEEEEEEuuuuuuuuu.............',
        '.uEEEEeeeeeeeeeeeeeeeeeeeEEEEEEEEEEEEEEEEEEuuuuuuuu.............',
        '.uEEEEeeeeeeeeeeeeeeeeeeeEEEEEEEEEEEEEEEEEEuuuuuuuu.............',
        'uEEEEeeeeOooOOOeeeeeeeeeeeEEEEEEEEEEEEEEEEEuuuuuuuuu............',
        'uEEEEeeeOooooOOOeeeeeeeeeeEEEEEEEEEEEEEEEEEEuuuuuuuu............',
        'uEEEEeeeOOooOOOOeeeeeeeeeeEEEEEEEEEEEEEEEEEEuuuuuuuuu...........',
        'uEEEEeeeeOOOOOOeeeeeeeeeeeEEEEEEEEEEEEEEEEEEuuuuuuuuu...........',
        'EEEEEeeeeeeeeeeeeeNNNnnnnnnnnnnnNNEEEOooOOOEEuuuuuuuu...........',
        'EEEEeeeeeeeeeeeeeeNNNnnnnnnnnnnnNNEEOooooOOOEuuuuuuuu...........',
        'EEEEeeeeeeeeeeeeeeNNNNNNNNNNNNNNNNEEOOooOOOOEuuuuuuuuu..........',
        'EEEEeeeeeeeeeeeeeennnzzzzzzzzzznnnEEEOOOOOOEEuuuuuuuuu..........',
        'EEEEeeeeeeeeeeeeeennnzzzzzzzzzznnnEEEEEEEEEEEuuuuuuuuu..........',
        'EEEEeeeeeeeeeeeeeennnzzzzzzzzzznnnEEEEEEEEEEEEullleEEu..........',
        'EEEEeeeeeeeeeeeeeennnzzzzzzzzzznnnEEEEEEEEEEEEullleeEEE.........',
        'EEEEeeeeeeeeeeeeeennnzzzzzzzzzznnnEEEEEEEEEEEEueeeeeEEE.........',
        'EEEeeeeeeeeeeeeeeennnzzzzzzzzzznnnEEEEEEEEEEEEuEeeeEEEE.........',
        'EEEeeeeeeeeeeeeeeennnzzzzzzzzzznnnEEEEEEEEEEEEuEEEEEEEE.........',
        'EEEeeeeeeeeeeeeeeennnzzzzzzzzzznnnEEEEEEEEEEeEEEEEEEEuu.........',
        'EEEeeeeeeeeeeeeeeennnzzzzzzzzzznnnEEEEEEEEllleeEEEuuuuuEE.......',
        'EEEeeeeeeeeeeeeeeennnzzzzzzzzzznnnEEEEEEEEllleeEEEEullleeEE.....',
        'EEEeeeeeeeeeeeeeeennnzzzzzzzzzznnnEEEEEEEEeeeeeEEEEullleeEEE....',
        'EEEeeeeeeeeeeeeeeennnzzzzzzzzzznnnEEEEEEEEeeeeeEEEEueeeeeEEE....',
        'EEEeeeeeeeeeeeeeeennnzzzzzzzzzznnnEEEEEEEEEEeEEEEEEueeeeeEEE....',
        'EEEeeeeeeeeeeeeeeennnzzzzzzzzzznnnEEEEEEEEEEEEEEEEuuEEEEEEEE....',
        'EEEeeeeeeeeeeeeeeennnzzzzzzzzzznnnEEEEEEEEEEEEEEuuuuuEEEEEE.....',
        'EEEeeeeeeeeeeeeeeennnzzzzzzzzzznnnEEEEEEEEEEEEEuuuuuuuuEE.......',
        'EEEeeeeeeeeeeeeeeennnzzzzzzzzzznnnEEEEEEEEEEEEEuuuuuuuuu........',
        '..........................................EEEEEEEEEEEEEEEEEEEE..',
        '................................................................',
        '................................................................',
        '................................................................',
      ],
    },
    /* ртутная лаборатория: каменная башня с лиловым конусом, голубые окна, реторта с ртутью справа (64×56) */
    mine_mercury: {
      hd: true, unit: 2,
      rows: [
        '................................................................',
        '......................ApPp......................................',
        '.....................AApPPp.....................................',
        '....................AApppPPp....................................',
        '...................AAppppPPPp...................................',
        '..................AAApppppPPPp..................................',
        '.................AAAppppppPPPPp.................................',
        '................AAAppppppppPPPPp................................',
        '...............AAAAppppppppPPPPPp...............................',
        '..............AAAAppppppppppPPPPPp..............................',
        '.............AAAAppppppppppppPPPPPP.............................',
        '............AAAAAppppppppppppPPPPPPP............................',
        '...........AAAAAppppppppppppppPPPPPPP...........................',
        '..........AAAAApppppppppppppppPPPPPPPP..........................',
        '.........AAAAAAppppppppppppppppPPPPPPPP.........................',
        '........AAAAAApppppppppppppppppPPPPPPPPP........................',
        '.......AAAAAApppppppppppppppppppPPPPPPPPP.......................',
        '......AAAAAAApppppppppppppppppppPPPPPPPPPP......................',
        '........llllllllllllllllllllllllllllllll........................',
        '..........lllleeeeeeeeeeeeeeeeeeEEEEEE..........................',
        '..........lllleeeeeeeeeeeeeeeeeeEEEEEE..........................',
        '..........lllleeeeeeeeeeeeeeeeeeEEEEEE..........................',
        '..........lllleeeeeeeeeeeeeeeeeeEEEEEE..........................',
        '..........lllleeeeeeeeeeeeeeeeeeEEEEEE..........................',
        '..........lllleeeeeeeeeeeeeeeeeeEEEEEE..........................',
        '..........lllleeeeeeeeeeeeeeeeeeEEEEEE..........................',
        '..........lllleeewwwwwweeeewwwwwwEEEEE..........................',
        '..........lllleeewwwwwweeeewwwwwwEEEEE..........................',
        '..........lllleeecccccceeeeccccccEEEEE..........................',
        '..........lllleeecccccceeeeccccccEEEEE..........................',
        '..........lllleeecccccceeeeccccccEEEEE.............cwwccc.......',
        '..........lllleeecccccceeeeccccccEEEEE.............cwwccc.......',
        '..........lllleeecccccceeeeccccccEEEEE.............cwwccc.......',
        '..........lllleeecccccceeeeccccccEEEEE.............cwwccc.......',
        '..........lllleeeeeeeeeeeeeeeeeeEEEEEE.............cwwccc.......',
        '..........lllleeeeeeeeeeeeeeeeeeEEEEEE.............cwwccc.......',
        '..........lllleeeeeeeeeeeeeeeeeeEEEEEE.............cwwccc.......',
        '..........lllleeeeeeeeeeeeeeeeeeEEEEEE.............cwwccc.......',
        '..........lllleeeeeeeeeeeeeeeeeeEEEEEE.............cwwccc.......',
        '..........lllleeeeeeeeeeeeeeeeeeEEEEEE.............cccccc.......',
        '..........lllleeeeeeNNNzzzzNNNeeEEEEEE..........wwcccccccccc....',
        '..........lllleeeeeeNNzzzzzzNNeeEEEEEE.........cwwccccccccccc...',
        '..........lllleeeeeeNNzzzzzzNNeeEEEEEE........ccwwcccccccccccc..',
        '..........lllleeeeeeNNzzzzzzNNeeEEEEEE........ccwwcccccccccccc..',
        '..........lllleeeeeeNNzzzzzzNNeeEEEEEE.......cccwwlllllllllcccc.',
        '..........lllleeeeeeNNzzzzzzNNeeEEEEEE.......cccwwwwwwwlllllccc.',
        '..........lllleeeeeeNNzzzzzzNNeeEEEEEE.......cclwwwwwwwwlllllcc.',
        '..........lllleeeeeeNNzzzzzzNNeeEEEEEE.......cclwwwwwwwwlllllcc.',
        '..........lllleeeeeeNNzzzzzzNNeeEEEEEE........cllwwwwweeeeeelc..',
        '..........lllleeeeeeNNzzzzzzNNeeEEEEEE........cllllllleeeeeelc..',
        '..........lllleeeeeeNNzzzzzzNNeeEEEEEE.........cllllllllllllc...',
        '..........lllleeeeeeNNzzzzzzNNeeEEEEEE..........cEEEEEEEEEEc....',
        '..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeEEEEEEEEEEeee..',
        '..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..',
        '..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..',
        '....EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE....',
      ],
    },
    /* серная шахта: жёлтый холм с рыжими наростами, дымящие отдушины, крепь входа (64×56) */
    mine_sulfur: {
      hd: true, unit: 2,
      rows: [
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '...........llll.................................................',
        '..........llllll................................................',
        '..........llllll................................................',
        '...........llll.................................................',
        '.............llll...............................................',
        '............llllll..............................................',
        '............llllll.......YYYYYYYYYY.............................',
        '............llllll...YYyyyyyyyYYYYYYYYY.........................',
        '............llllll.yyyyyyyyyyyyyyYYYYYYYY.......................',
        '.............lllleeyyyyyyyyyyyyyyyyYYllllYY.....................',
        '..............eeeeeeyyyyyyyyyyyyyyyyllllllYYY...................',
        '..............eeeeeettyyyyyyyyyyyoOOllllllYYYY..................',
        '.............yeeeeeetttyyyyyyyyyyoooollllYYYYYY.................',
        '............yyeeeeeettttyyyyyyyyyyyooyyeeeeYYYYY................',
        '...........yyeeeeeettooooooyyyyyyyyyyyeeeeeeYYYYY...............',
        '..........yyeeeeeettooOOOOooyyyyyyyyyyeeeeeeYYYYYY..............',
        '.........YyyeeeeeettooooooooyyyyyyyyyyeeeeeeYYYYYYY.............',
        '........YyyyeeeeeetttooooooyyyyyyyyyyyeeeeeeYYYYYYYY............',
        '.......YyyyyeeeeeettttttttttyyyyyyyyyyyeeeeyyYYYYYYYY...........',
        '.......YyyyEEeeeetttttttttttyyyyyyyyyyyEEEEEEYYYYYYYY...........',
        '......YyyytEEEEEEttttttttttttyyyyyyyyyyEEEEEEyYYYYYYYY..........',
        '.....YyyyytEEEEEEttttttttttttyyyyyyyyyyEEEEEEyYYYYYYYYY.........',
        '.....YyyyytEEEEEEttttttttttttyyyyyyyyyyEEEEEEyyYYYYYYYY.........',
        '....YYyyytttttttttttttttttttttyyyyyyyyyyyyyyyyyYYYYYYYYY........',
        '....YyyyyttttttttttttNNNNNNNNNNNNNNNNNNyyyyyyyyyYYYYYYYY........',
        '...YYyyyyttttttttttttNNNNNNNNNNNNNNNNNNyyyyyyyyyYYYYYYYYY.......',
        '...YyyyyyttttttttttttNNNNNNNNNNNNNNNNNNyyyyyyyyyYYYYYYYYY.......',
        '...YyyyytttttttttttttnnnzzzzzzzzzzzznnnyyyyyyyyyyYYYYYYYY.......',
        '..YYyyyytooOOoottttttnnnzzzzzzzzzzzznnnyyooooooyyYYYYYYYYY......',
        '..YyyyyyooOOOOootttttnnnzzzzzzzzzzzznnnyooOOOOooyYYYYYYYYY......',
        '..YyyyyyoooOOoootttttnnnzzzzzzzzzzzznnnyooooooooyyYYYYYYYY......',
        '.YYyyyyytoooooottttttnnnzzzzzzzzzzzznnnyyooooooyyyYYYYYYYYY.....',
        '.YYyyyyytttttttttttttnnnzzzzzzzzzzzznnnyyyyyyyyyyyYYYYYYYYY.....',
        '.YYyyyyttttttttttttttnnnzzzzzzzzzzzznnnyyyyyyyyyyyYYYYYYYYY.....',
        '.YyyyyyttttttttttttttnnnzzzzzzzzzzzznnnyyyyyyyyyyyYYYYYYYYY.....',
        'YYyyyyyttttttttttttttnnnzzzzzzzzzzzznnnyyyyyyyyyyyyyyyyYYYYY....',
        'YYyyyyyttttttttttttttnnnzzzzzzzzzzzznnnyyyyyyyyyyYyyyyyyYYYY....',
        'YYyyyyyttttttttttttttnnnzzzzzzzzzzzznnnyyyyyyyyyyYyyyyyyYYYY....',
        'YYyyyyyttttttttttttttnnnzzzzzzzzzzzznnnyyyyyyyyyyYYyyyyYYYYY....',
        'YYyyyyyttttttttttttttnnnzzzzzzzzzzzznnnyyyyyyyyyyYYYYYYYYYYY....',
        'YYyyyyyttttttttttttttnnnzzzzzzzzzzzznnnyyyyyyyyyyyyYYYYYYYYY....',
        'YYyyyyyttttttttttttttnnnzzzzzzzzzzzznnnyyyyyyyyyyyyYYYYYYYYY....',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
      ],
    },
    /* кристальная пещера: серая скала, розовая друза слева, голубая по центру, мелкие кристаллы справа (64×56) */
    mine_crystal: {
      hd: true, unit: 2,
      rows: [
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '..........wmmM..................................................',
        '..........wmmM..................................................',
        '..........wmmM..................................................',
        '..........wmmM..................................................',
        '..........wmmM........................wccC......................',
        '..........wmmM........................wccC......................',
        '.........wwmmMM.......................wccC......................',
        '.........wwmmMM.......................wccC......................',
        '.........wwmmMM.....wmMM..............wccC......................',
        '.........wwmmMM.....wmMM.............wwccCC.....................',
        '.........wwmmMM.....wmMM.............wwccCC.....................',
        '.........wwmmMM.....wmMM.............wwccCC.....................',
        '.........wwmmMM.....wmMM.............wwccCC.....................',
        '........wwwmmMMM...wwmMM.............wwccCC.....................',
        '..wwmM..wwwmmMMM...wwmMM............wwwccCCC..wcCC..............',
        '..wwmM..wwwmmMMM...wwmMM............wwwccCCC..wcCC..............',
        '..wwmM..wwwmmMMM...wwmMM............wwwccCCC..wcCC..............',
        '..wwmM..wwwmmMMM...wwmMMM...........wwwccCCC..wcCC..............',
        '..wwmMM.wwwmmMMM..wwwmMMM...........wwwccCCC.wwcCC..............',
        '..wwmMMwwwwmmMMMM.wwwmMMM...........wwwccCCC.wwcCC..............',
        '..wwmMMwwwwmmMMMM.wwwmMMM..........wwwwccCCCCwwcCC..............',
        '..wwmMMwwwwmmMMMM.wwwmMMM..........wwwwccCCCwwwcCC..............',
        '..wwmMMwwwwmmMMMM.wwwmMMMEEEEEEEEEEwwwwccCCCwwwcCC..............',
        '..wwmMMMwwwmmMMMM.wwwmMMMeeeeeeeEEEwwwwccCCCwwccCC..............',
        '..wwmmMMwwwmmMMMMwwwwmMMMeeeeeeeeeewwwwccCCCwwcCCC..............',
        '..wwwmMMwwwmmMMMMwwwwmMMMMeeeeeeeewwwwwccCCwwwcCCC..............',
        '..wwwmMMwwwmmMMMMwwwwmMMMMeeeeeeeewwwwwccCCwwwcCCC..............',
        '..wwwmMMMwwmmMMMMwwwwmMMMMeeeeeeeewwwwwccCCwwwcCCC..............',
        '..wwwmMMMwwmmMMMMwwwwmMMMMeeeeeeeewwwwwccCwwwwcCCCE.............',
        '..wwwmMMMwwmmMMMwwwwmmMMMMeeeeeeeewwwwwccCwwwwcCCCEE............',
        '..wwwmMMMwwmmMMMwwwwmmMMMMEEEEEEEEEEEEeeeewwwwcCCCEEwmmM........',
        '..wwwmMMMwwmmMMMwwwwmmMMMMEEEEEEEEEEEEeeeewwwwcCCCEEwmmM........',
        '..wwwmMMMMllllllwwwwmmMMMMEEEEEEEEEEEEeeeeeeeeeEEEEEwmmM........',
        '..wwwmMMMMllllllwwwwmmMMMMzzzzzzzzzeeeeeeeeeeeeeEEEEwmmME.......',
        '..wwwmmMMMlllllllllllleeezzzmmmmzzzeeeeeeeeeeeeeEEEEwmmME.......',
        '..wwwmmMMMlllllllllllleeezzmmmmmmzzeeeeeeeeeeeeeeEEEwmmMEE......',
        '.EEeeeelllllEEEEEEEElleeezzmmmmmmzzeeeeeeeeeeeeeeeEwwmmMMEwmMM..',
        '.EeeeeelllllEEEEEEEElleeezzzwwwwzzzeeeeeeeeeeeeeeeEwwmmMMEwmMM..',
        'EEeeeeellllllllllllllleeezzzwwwwzzzeeeeeeeeeeeeeeeEwwmmMMEwmMM..',
        'EeeeeelllllllllllllllleeezzzzzzzzzzeeeeeeeeeeeeeeeewwmmMMEwmMM..',
        'EeeeeelllllllllllllllleeezzzzzzzzzzeeeeeEEEEEEEEEEewwmmMMwwmMM..',
        'EeeeeelllllllllllllllleeezzzzzzzzzzeeeeeEEEEEEEEEEewwmmMMwwmMM..',
        'EeeeeelllllllllllllllleeezzzzzzzzzzeeeeeeeeeeeeeeewwwmmMMwwmMM..',
        'eeeeeelllllllllllllllleeezzzzzzzzzzeeeeeeeeeeeeeeewwwmmMMwwmMM..',
        'eeeeeelllllllllllllllleeezzzzzzzzzzeeeeeeeeeeeeeeewwwmmMwwwmMM..',
        'eeeeellllllllllllllllleeezzzzzzzzzzeeeeeeeeeeeeeeewwwmmMwwwmMM..',
        'eeeeellllllllllllllllleeezzzzzzzzzzeeeeeeeeeeeeeeewwwmmMwwwmMM..',
        'eeeeellllllllllllllllleeezzzzzzzzzzeeeeeeeeeeeeeeewwwmmMwwwMMM..',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
      ],
    },
    /* самоцветная жила: бурый холм, голубое озерцо, зелёные самоцветы (64×56) */
    mine_gems: {
      hd: true, unit: 2,
      rows: [
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '..........hhgG..................................................',
        '..........hhgG..................................................',
        '..........hhgG..................................................',
        '..........hhgG..................................................',
        '..........hhgGG.................................................',
        '..........hhgGG.................................................',
        '..........hhgGG.................................................',
        '.........hhhgGG.................................................',
        '.........hhhgGGG..hgGG..DDDDDDDDDDDD............................',
        '.........hhhgGGG..hgGGdddddddddDDDDDDDDD........................',
        '.........hhhgGGG.hhgGGdddddddddddddDDDDDDDD.....................',
        '.........hhhgGGGhhhgGGdddddddddddddddDDDDDDDD...................',
        '.........hhhgGGGhhhgGGdddddddddddddddddDDDDDDDD.................',
        '........hhhhggGGhhggGGndddddddddddddddddDDDDDDDD................',
        '........hhhhggGhhhgGGGnnddddddddddddddddddDDDDDDDD..............',
        '........hhhhggGhhhgGGGnnnddddddddddddddddddDDDDDDDD.............',
        '........hhhhgghhhhgGGGnnnnddddddddddddddddddDDDDDDDD............',
        '.......DhhhhgghhhhgGGGnnnnnddddddddddddddddddDDDDDDDD...........',
        '......DdhhhhggGGGGnnnnnnnnnnddddddddddddddddddDDDDDDDD..........',
        '.....DddhhhhggGGGGnnnnnnnnnnddddddddddddddddddDDDDDDDDD.........',
        '....DddddnnnnnnnnnnnnnnnnnnnnddddddddddhgGGddddDDDDDDDDD........',
        '...DDdddnnnnnnnnnnnnnnnnnnnnnddddddddddhgGGdddddDDDDDDDDD.......',
        '...DddddnnnnnnnnnnnnnnnnnhhgGndddddddddhgGGdddddDDDDDDDDD.......',
        '..DdddddnnnnnnnnnnnnnnnnnhhgGBBBBBBBBBBhgGGddddddDDDDDDDDD......',
        '.DDddddnnnnnnnnnnnnnBBBBBhhgGBBBBBBBBBhhgGGBdddddDhhgGDDDDD.....',
        '.DdddddnnnnnnnnnnBBBBbbbbhhgGGbbbbbbbbhhgGGBBBBdddhhgGDDDDD.....',
        'DDdddddnnnnnnnnBBBbbbbbbbhhgGGbbbbbbbbhhgGGbBBBBBdhhgGDDDDDD....',
        'DDdddddnnnnnnBBBbbbbccccchhgGGccbbbbbhhhgGGGbbBBBBhhgGGDDDDD....',
        'DdddddnnnnnnBBBbbbbccccchhhgGGGccbbbbhhhgGGGhgGGBBhhgGGDDDDD....',
        'DdddddnnnnnnBBbbbbbccccchhhgGGGccbbbbhhhgGGGhgGGBhhhgGGDDDDDD...',
        'DdddddnnnnnnBBbbbbbbcccchhhgGGGcbbbbbhhhgGGhhgGGBhhhgGGGDDDDD...',
        'DdddddnnnnnnBBBbbbbbbbbbhhhgGGGGbbbbhhhhgGGhhgGGBhhhgGGGDDDDD...',
        'ddddddnnnnnnnBBBbbbbbbbbhhhggGGGbbbbhhhhgGhhhgGGBhhhgGGGGDDDD...',
        'ddddddnnnnnnnnnBBBbbbbbbhhhggGGGbbbbhhhhgGhhggGGhhhhggGGGDDDDD..',
        'dddddnnnnnnnnnnnnBBBBbbbbbbbbbbbbbbbbbbbbhhhgGGGhhhhggGGGDDDDD..',
        'dddddnnnnnnnnnnnnnnnBBBBBBBBBBBBBBBBBBBBBhhhgGGGhhhhggGGGGDDDD..',
        'dddddnnnnnnnnnnnnnnnnnnnnBBBBBBBBBBBBBBdhhhhgGGGhhhhggGGGGDDDD..',
        'dddddnnnnnnnnnnnnnnnnnnnnnnnnnnnddddddddhhhhgGGGhhhhggGGGGDDDD..',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
      ],
    },
    /* куча золота: горка монет (28×24) */
    res_gold: {
      hd: true, unit: 2,
      rows: [
        '............................',
        '............................',
        '............................',
        '............................',
        '............................',
        '............................',
        '............................',
        '..........yyyY..............',
        '.........yyyyyY.............',
        '.........YyyyYY.............',
        '....yyyY..YYYY..............',
        '...yyyyyY......yyyY.........',
        '...YyyyYY.....yyyyyY........',
        '....YYYY......YyyyYY........',
        '........yyyYYYYYYYY.........',
        '.......yyyyyYYYYYYY.........',
        '.....YYYyyyYYyyyyYYYY.......',
        '....YYyyYYYYyyyyyyYYYY......',
        '...YyyyyyyyyyYyyyYYyYYY.....',
        '...YyyffffffyyYYYYyyyyyyyy..',
        '.yyyyffffffffyyyyyyyyyyyyyy.',
        'yyyyyyfffffffyyyyyyyyyYYYYy.',
        'yyyyyyffffffyyyyyyyyyyYYYY..',
        '..YYYYYYYYYYYYYYYYYYYYYYYY..',
      ],
    },
    /* куча дерева: штабель брёвен торцами (28×24) */
    res_wood: {
      hd: true, unit: 2,
      rows: [
        '.............NN.............',
        '...........NNnnNN...........',
        '..........NnnnnnnN..........',
        '..........NnTTTTnN..........',
        '.........NnnTTTTnnN.........',
        '.........NnnTTTTnnN.........',
        '..........NnTTTTnN..........',
        '.........NNnnnnnnNN.........',
        '.......NNnNNNnnNNNnNN.......',
        '......NnnnnnNNNNnnnnnN......',
        '.....NnnTTTnnNNnnTTTnnN.....',
        '.....NnTTTTTnNNnTTTTTnN.....',
        '.....NnTTTTTnNNnTTTTTnN.....',
        '.....NnnTTTnnNNnnTTTnnN.....',
        '....NNNnnnnnNNNNnnnnnNNN....',
        '..NNnnNNNnNNNnnNNNnNNNnnNN..',
        '.NnnnnnnNNNnnnnnnNNNnnnnnnN.',
        '.NnTTTTnN.NnTTTTnN.NnTTTTnN.',
        'NnnTTTTnnNnnTTTTnnNnnTTTTnnN',
        'NnnTTTTnnNnnTTTTnnNnnTTTTnnN',
        '.NnTTTTnN.NnTTTTnN.NnTTTTnN.',
        '.NnnnnnnN.NnnnnnnN.NnnnnnnN.',
        '..NNnnNN...NNnnNN...NNnnNN..',
        '....NN.......NN.......NN....',
      ],
    },
    /* куча руды: серые глыбы (28×24) */
    res_ore: {
      hd: true, unit: 2,
      rows: [
        '............................',
        '............................',
        '............................',
        '............................',
        '...........eEE..............',
        '.........llleeEEE...........',
        '........ellleeeEEE..........',
        '........ellleeeEEE..........',
        '........eeeeeeeEEE..........',
        '........EeeeeeEEEE..........',
        '........EEEeEEEEEE..........',
        '........EEEEEEEEEE..........',
        '.........EEEEEEEE..EE.......',
        '....eeeEEE..EE..eeeeeEEE....',
        '..ellleeeEE....ellleeeEEE...',
        '..ellleeeEEE..eellleeeeEEE..',
        '.EellleeeEEEE.eellleeeeEEE..',
        '.EeeeeeeeEEEE.eeeeeeeeeEEE..',
        '.EeeeeeeeEEEE.EeeeeeeeEEEE..',
        '.EEEeeeEEEEEE.EEeeeeeEEEEE..',
        '..EEEEEEEEEE..EEEEEEEEEEEE..',
        '...EEEEEEEE....EEEEEEEEEE...',
        '....EEEEEE......EEEEEEEE....',
        '..EEEEEEEEEEEEEEEEEEEEEEEE..',
      ],
    },
    /* ртуть: колба с серебристой жидкостью (28×24) */
    res_mercury: {
      hd: true, unit: 2,
      rows: [
        '..........llllllll..........',
        '..........llllllll..........',
        '..........llllllll..........',
        '...........cwwccc...........',
        '...........cwwccc...........',
        '...........cwwccc...........',
        '...........cwwccc...........',
        '...........cwwccc...........',
        '...........cwwccc...........',
        '...........cccccc...........',
        '.......wwccccccccccc........',
        '.......wwcccccccccccc.......',
        '......cwwccccccccccccc......',
        '......cwwccccccccccccc......',
        '.....ccwwllllllllllcccc.....',
        '.....ccwwwwwwwwlllllccc.....',
        '.....cclwwwwwwwwlllllcc.....',
        '.....cclwwwwwwwwlllllcc.....',
        '......cllwwwwweeeeeelc......',
        '......cllllllleeeeeelc......',
        '.......cllllllllllllc.......',
        '........cllllllllllc........',
        '........EEEEEEEEEEEE........',
        '........EEEEEEEEEEEE........',
      ],
    },
    /* сера: жёлтая горка с рыжими крапинами (28×24) */
    res_sulfur: {
      hd: true, unit: 2,
      rows: [
        '............................',
        '............................',
        '............................',
        '............................',
        '............................',
        '............................',
        '............................',
        '............................',
        '............................',
        '............................',
        '............................',
        '..........YYYYYYYY..........',
        '........YYYYYYYYYYYY........',
        '......YYYyyyyyooooYYYY......',
        '.....YyyyyyyyooooooYYYY.....',
        '....YyyyyyyyyooooooYYYYY....',
        '...YyyyyyyyyyyooooyyYYYYY...',
        '..YyyoooottyyyyyyyyyyYYYYY..',
        '..YyyoooottttyyyyyyyyYYYYY..',
        '..yyyttttttttyyyyyyyyyYYYY..',
        '.YyyttttttttttyyyyyyyyYYYYY.',
        '.YyyttttttttttyyyyyyyyYYYYY.',
        '.YyyttttttttttyyyyyyyyYYYYY.',
        '..OOOOOOOOOOOOOOOOOOOOOOOO..',
      ],
    },
    /* кристаллы: розовая друза (28×24) */
    res_crystal: {
      hd: true, unit: 2,
      rows: [
        '............................',
        '.............wmMM...........',
        '.............wmMM...........',
        '.............wmMM...........',
        '.............wmMM...........',
        '............wwmMM...........',
        '............wwmMM...........',
        '............wwmMM....wmMM...',
        '...wwmM.....wwmMMM...wmMM...',
        '...wwmM.....wwmMMM...wmMM...',
        '...wwmM....wwwmMMM..wwmMM...',
        '...wwmMM...wwwmMMM..wwmMM...',
        '...wwmMM...wwwmMMM..wwmMMM..',
        '..wwwmMM...wwwmMMM.wwwmMMM..',
        '..wwwmMMM.wwwwmMMM.wwwmMMM..',
        '..wwwmMMM.wwwwmMMM.wwwmMMM..',
        '..wwwmMMM.wwwwmMMMMwwwmMMM..',
        '..wwwmMMMMwwwwmMMMwwwwmMMM..',
        '.wwwwmmMMMwwwwmMMMwwwwmMMMM.',
        '.wwwwmmMMMwwwmmMMMwwwwmMMMM.',
        '.wwwwmmMMMMwwmmMMwwwwmmMMMM.',
        '.wwwwmmMMMMwwmmMMwwwwmmMMMM.',
        '.wMMMMMMMMMMMMMMMMMMMMMMMMM.',
        '..MMMMMMMMMMMMMMMMMMMMMMMM..',
      ],
    },
    /* самоцветы: зелёные огранённые камни (28×24) */
    res_gems: {
      hd: true, unit: 2,
      rows: [
        '............................',
        '............................',
        '............................',
        '............hggG............',
        '............hggG............',
        '............hggG............',
        '............hggG............',
        '...........hhggGG...........',
        '...........hhggGG...........',
        '...........hhggGG....hggG...',
        '..hhgG.....hhggGG....hggG...',
        '..hhgG....hhhggGGG...hggG...',
        '..hhgG....hhhggGGG...hggG...',
        '..hhgGG...hhhggGGG..hhggGG..',
        '.hhhgGG...hhhggGGG..hhggGG..',
        '.hhhgGGG.hhhhggGGGG.hhggGG..',
        '.hhhgGGG.hhhhggGGGGhhhggGGG.',
        '.hhhgGGG.hhhhggGGGGhhhggGGG.',
        '.hhhgGGGGhhhhggGGGGhhhggGGG.',
        'hhhhggGGGhhhhggGGGGhhhggGGG.',
        'hhhhggGGGGhhhggGGGhhhhggGGGG',
        'hhhhggGGGGhhhggGGGhhhhggGGGG',
        'hhGGGGGGGGGGGGGGGGGGGGGGGGGG',
        '..GGGGGGGGGGGGGGGGGGGGGGGG..',
      ],
    },
    /* сундук: коричневый ларец с золотыми обручами и замком (32×28) */
    chest: {
      hd: true, unit: 2,
      rows: [
        '................................',
        '................................',
        '................................',
        '................................',
        '.....yyYY..nnnnnnnnnn..yyYY.....',
        '.....yyYYnnnnnnnnnnnnnnyyYY.....',
        '.....yyYYnnnnnnnnnnnnnnyyYY.....',
        '....nyyYYnTTTTTTTTTTTTnyyYYn....',
        '...nnyyYYTTTTTTTTTTTTTTyyYYnn...',
        '...nnyyYYTTTTTTTTTTTTTTyyYYnn...',
        '..nnnyyYYTTTTTTTTTTTTTTyyYYnnn..',
        '..nnnyyYYTTTTyyyyYYTTTTyyYYnnn..',
        '..nnnyyYYTTTTyyyyYYTTTTyyYYnnn..',
        'NNNNNyyYYNNNNyyyyYYNNNNyyYYNNNNN',
        '..TnnyyYYTTTTyyDDYYTTTTyyYYnnN..',
        '..TnnyyYYTTTTyyDDYYTTTTyyYYnnN..',
        '..TTnyyYYnTTTyyDDYYTTTnyyYYnNN..',
        '..TTTyyYYnnnnyyyyYYnnnnyyYYNNN..',
        '..TTTyyYYnnnnyyyyYYnnnnyyYYNNN..',
        '..TTTyyYYnnnnnnnnnnnnnnyyYYNNN..',
        '..TTTyyYYnnnnnnnnnnnnnnyyYYNNN..',
        '..TTTyyYYnnnnnnnnnnnnnnyyYYNNN..',
        '..TTTyyYYnnnnnnnnnnnnnnyyYYNNN..',
        '..TTTyyYYnnnnnnnnnnnnnnyyYYNNN..',
        '..YYYYYYYYYYYYYYYYYYYYYYYYYYYY..',
        '..YYYYYYYYYYYYYYYYYYYYYYYYYYYY..',
        '..DDDDDDDDDDDDDDDDDDDDDDDDDDDD..',
        '..DDDDDDDDDDDDDDDDDDDDDDDDDDDD..',
      ],
    },
    /* костёр: языки пламени над поленьями, кольцо камней (36×36) */
    campfire: {
      hd: true, unit: 2,
      rows: [
        '....................................',
        '................FFFF................',
        '................FFFF................',
        '................FFFF................',
        '................FFFF................',
        '................FFFF................',
        '................FFFF................',
        '................FFFF................',
        '................FFFF................',
        '...............FFFFFF...............',
        '...............FooooF...............',
        '...............FooooF...............',
        '...............FooooF...............',
        '...............FooooF...............',
        '..........FFFF.FooooF...............',
        '..........FFFFFFooooFF..............',
        '..........FFFFFFooooFFFFFF..........',
        '..........FFFFFFooooFFFFFF..........',
        '..........FFFFFFooooFFFFFF..........',
        '..........FooFFooooooFFFFF..........',
        '..........FooFFoffffoFFooF..........',
        '..........FoFFFoffffoFFFoF..........',
        '.........FFoFFFoffffoFFFoF..........',
        '.........FooFFooffffooFFoFF.........',
        '.........FffFFooyyyyooFFooF.........',
        '........FFfFFFoyyyyyyoFFFfFF........',
        '........FofFFFyyyyyyyyFFFfFF........',
        '.......FFofFFoyyyyyyyyoFFfoF........',
        '.....TTFFoFFFooyyyyyyooFFFoFFTT.....',
        '...eeTTFFoFFFoofyyyyfooFFFoFFTTEE...',
        '..eeTTTTTTFFFooffffffooFFFTTTTTTEE..',
        '..eeTTTTTTTNNNNNNNNNNNNNNTTTTTTTEE..',
        '..EennnnnNNNNNNNNNNNNNNNNNNNNNEEEE..',
        '..EEEEEE.NNNNNNNNNNNNNNNNNN.EEEEEE..',
        '...EDDDDDDDNNNNNNDDnnnnnnDDDDDDDE...',
        '....DDDDDDDDDDDDDDDDDDDDDDDDDDDD....',
      ],
    },
    /* артефакт: золотой кубок с самоцветом на каменном постаменте, искры (28×28) */
    artifact: {
      hd: true, unit: 2,
      rows: [
        '............................',
        '............................',
        '...A........................',
        '...A.....ffffffffff.........',
        '.AAAAA.ffffffffffffff....A..',
        '...A...ffffffffffffff....A..',
        '...A...yyffffffffffYYY.AAAAA',
        '......yyyyyyyyyyyyYYYY...A..',
        '......yyyyyyyyyyyyYYYY...A..',
        '......yyyyyymmrryyYYYY......',
        '......yyyyyymmrryyYYYY......',
        '......yyyyyyrrrryyYYYY......',
        '........yyyyrrrryyYYYY......',
        '.....A...yyyyyyyyyYYYY......',
        '.....A....yyyyyyyyYYYY......',
        '...AAAAA...YYYYYY.......A...',
        '.....A.....YYYYYY.......A...',
        '.....A.....YYYYYY.....AAAAA.',
        '.........yyyyyyyyyy.....A...',
        '.........yyyyyyyyyy.....A...',
        '....lllllyyyyyyyyyylllll....',
        '....llllllllllllllllllll....',
        '....llllllllllllllllllll....',
        '......llleeeeeeeeeEEEE......',
        '......llleeeeeeeeeEEEE......',
        '......llleeeeeeeeeEEEE......',
        '......llleeeeeeeeeEEEE......',
        '......llleeeeeeeeeEEEE......',
      ],
    },
  });
})();
