/* ============================================================================
   view/sprites_fortress.js — спрайты существ фракции Fortress (Крепость).
   Формат — см. docs/sprite-guide.md. Имя спрайта = id из js/data/creatures.js.
   Улучшенные версии с тем же силуэтом — через base/tint/extra.
   ========================================================================== */
(function () {
  H3.Sprites.defineMany({
    gnoll: {
      rows: [
        '......kk.kk...kkk...',
        '.....kNnknnk.kleek..',
        '.....kNtnnnk.kleeek.',
        '....kNnnnnnkkkeeeek.',
        '....knnnnnnnnk.kkkk.',
        '....knnnyknttk..kTk.',
        '....kNnnnnnttk..kTk.',
        '.....kNnnnkkkk..kTk.',
        '......kNnk......kTk.',
        '....kkkNnkkk....kTk.',
        '...knnkNnnnkkk..kTk.',
        '..kNnkNntnnNnnkkkTk.',
        '..kNnkNnnnnNknnnnnk.',
        '..kkkkNnnnnNkkkkkTk.',
        '....kNNdddNNk...kTk.',
        '....kNddddddk...kkk.',
        '.....kNdddNk........',
        '.....kNkkkNk........',
        '....kNNk.kNNk.......',
        '....kNnk.knNk.......',
        '....kNnk.knNk.......',
        '...kkkkk.kkkkk......',
      ],
    },
    gnoll_marauder: { base: 'gnoll', tint: { n: 'd', t: 'n', d: 'R' }, extra: [[5, 3, 'r'], [6, 3, 'r'], [7, 3, 'r'], [8, 3, 'r'], [9, 3, 'r'], [10, 3, 'r'], [3, 3, 'R'], [2, 4, 'R'], [2, 5, 'R']] },
    lizardman: {
      rows: [
        '......kkk...........',
        '.....kGggk..........',
        '....kGgggkk.........',
        '....kgggykggk..k....',
        '....kgggggghhk.lTk..',
        '....kGgghhhhk..l.Tk.',
        '.....kGgkkkk...l.Tk.',
        '......kgk......l..Tk',
        '....kkkgkkk....l..Tk',
        '...kggkgggkk...l..Tk',
        '..kGgkGgghhkggggk.Tk',
        '..kGgkGgghhkgggggggk',
        '..kkkkGgghhkkkkl..Tk',
        '....kGGgghhk...l..Tk',
        '....kGgggghk...l.Tk.',
        '..kkkGggghhk...lTk..',
        '.kGGkkGgkkggk..k....',
        'kGGk.kGgk.kggk......',
        'kGk..kGGk.kGgk......',
        'kGk..kGgk.kGgk......',
        'kGGkkkGgk.kGgk......',
        '.kkkkkkkk.kkkkk.....',
      ],
    },
    lizard_warrior: {
      rows: [
        '.....kokkk..........',
        '....kokqCCk.........',
        '....kokqCCCkk.......',
        '....kCCCykCCk..k....',
        '....kCCCCCCvvk.lTk..',
        '....kqCCvvvvk..l.Tk.',
        '.....kqCkkkk...l.Tk.',
        '......kCk......l..Tk',
        '.kkkkkkCkkk....l..Tk',
        'kEeeekCCCkk....l..Tk',
        'kEeyekqCCvvkCCCCk.Tk',
        'kEeeekqCCvvkCCCCCCCk',
        '.kEeekqCCvvkkkkl..Tk',
        '..kkkqqCCvvk...l..Tk',
        '....kqCCCCvk...l.Tk.',
        '..kkkqCCCvvk...lTk..',
        '.kqqkkqCkkCCk..k....',
        'kqqk.kqCk.kCCk......',
        'kqk..kqqk.kqCk......',
        'kqk..kqCk.kqCk......',
        'kqqkkkqCk.kqCk......',
        '.kkkkkkkk.kkkkk.....',
      ],
    },
    serpent_fly: {
      rows: [
        '....kkkk......kkkk....',
        '..kkccccck..kccccckk..',
        '.kccccccccckcccccccck.',
        '.kclcccccccGcccccclck.',
        '..kcccccccGgGccccccck.',
        '...kkccccGgggGcccckk..',
        '.....kkkkGgggGkkkkkk..',
        '.........kGgggkGgggk..',
        '.........kGgggkgykggk.',
        '........kGgghhkggkkkk.',
        '.......kGgghhkkGhhhk..',
        '......kGgghhk.kkkkk...',
        '.....kGgghhk..........',
        '....kGgghhk...........',
        '...kGgghhk............',
        '..kGgghhk.............',
        '.kGgghhk..............',
        '.kGghhk...............',
        '..kkkk................',
        '......................',
      ],
    },
    dragon_fly: {
      rows: [
        '....kkkkk.......kkkkk...',
        '..kkrrrrrrk...kkrrrrrkk.',
        '.krrrrrrrrrk.krrrrrrrrrk',
        '.krfrrrrrrrrkrrrrrrrfrrk',
        '.krrrrrrrrrrGrrrrrrrrrk.',
        '..krrrrrrrrGgGrrrrrrrrk.',
        '...kkrrrrrGgggGrrrrrkk..',
        '.....kkkkGgggggGkkkkkkk.',
        '.........kGggggkGggggk..',
        '.........kGggggkgyykggk.',
        '.........kGgghhkggkkkkk.',
        '........kGgghhkkGhhhhk..',
        '.......kGgghhhk.kkkkkk..',
        '......kGgghhhk..........',
        '.....kGgghhhk...........',
        '....kGgghhhk............',
        '...kGgghhhk.............',
        '..kGgghhhk..............',
        '.kGgghhhk...............',
        '.kGghhhk................',
        '..kkkkk.................',
        '........................',
      ],
    },
    basilisk: {
      rows: [
        '........kk..............',
        '.......kjHk.............',
        '......kjHHhk............',
        '......kjHHhk............',
        '......kjHHhk......kkkkk.',
        '.......kjHhk.....kHHHHHk',
        '.......kjHHk....kHhhHrHk',
        '........kjHkkkkkkHhhhkkk',
        '........kjHHHHHHHHHhhhhk',
        '.......kjHHhhhhhhhHHkkkk',
        '......kjHHhhhhhhhhhHHHHk',
        '.....kjHHHHhhhhhhhhHkkk.',
        '.....kjHHHHHHHHHHHHHjk..',
        '.....kjjHHHHHHHHHHHjjk..',
        '.....kkjjjjjjjjjjjjjjk..',
        '...kjkkHkkjkkHkkjkkHk...',
        '...kjkkHkkjkkHkkjkkHk...',
        '...kjkkHkkjkkHkkjkkHk...',
        '...kjkkHkkjkkHkkjkkHk...',
        '...kjkkHkkjkkHkkjkkHk...',
        '...kkkkHkkkkkHkkkkkHk...',
        '......kkk...kkk...kkk...',
      ],
    },
    greater_basilisk: { base: 'basilisk', tint: { H: 'G', j: 'Q', h: 'H', r: 'f' }, extra: [[11, 6, 'o'], [12, 5, 'o'], [12, 6, 'o'], [13, 6, 'o'], [14, 5, 'o'], [14, 6, 'o'], [15, 6, 'o'], [8, 0, 'o'], [9, 0, 'o']] },
    gorgon: {
      rows: [
        '............................',
        '............................',
        '............................',
        '............................',
        '............................',
        '.........kkkkkkkk...........',
        '.......kkYyyyYYYYkk.........',
        '......kYyyyYYYYYYYYk....kk..',
        '.....kYyyYYYYYYYYYYYk..kiik.',
        '....kYyYYYYYYYYYYYYYYkkiiik.',
        '...kYYYYYYYYYYYYYYYYYYkiik..',
        '..kkYYYYYYYYYYYYYYYYYYYkkkk.',
        '.kNkYYYYYYYYYYYYYYYYYYYYYYk.',
        'kNNkYYYYYYYYYYYYYYYYYYyYYYYk',
        'kNkkYYYYYYYYYYYYYYYYYYyYrYYk',
        'kNk.kYYYYYYYYYYYYYYYNYYYYYYk',
        '.kk.kNYYYYYYYYYYYYYNkNYYYYYk',
        '....kNNYYYYYYYYYYYNNk.kNYYYk',
        '.....kNNNYYYYYYYNNNk..kNNNNk',
        '.....kkYYkNNNNNkYYkk..kkkkk.',
        '..kNNkkYYk.kNNkkYYk.........',
        '..kNNkkYYk.kNNkkYYk.........',
        '..kNNkkYYk.kNNkkYYk.........',
        '..kNNkkYYk.kNNkkYYk.........',
        '..kNNkkYYk.kNNkkYYk.........',
        '..kNNkkYYk.kNNkkYYk.........',
        '..kkkkkYYk.kkkkkYYk.........',
        '......kkkk.....kkkk.........',
      ],
    },
    mighty_gorgon: { base: 'gorgon', tint: { Y: 'Q', y: 'q', N: 'z', r: 'h', i: 'l' }, extra: [[23, 14, 'h'], [25, 14, 'h'], [24, 13, 'h'], [24, 15, 'h']] },
    wyvern: {
      rows: [
        '.......kk...................',
        '......kNNk..................',
        '.....kNnnNk.................',
        '....kNnnnnNk................',
        '...kNnnnnnnNk...............',
        '..kNnnnNnnnnNk.......kkkkk..',
        '..kNnnnNnnnnnNk.....kjHHjjk.',
        '.kNnnnNnnnnnnnNk...kjHjrjjjk',
        '.kNnnnNnnnnnnnnNk..kjjjjkkkk',
        '.kNnnNnnnnnnnnnnNk.kGjjkHHk.',
        '.kkNNnnnnnnnnnnnnNkkGjkkkk..',
        '..kkkNNnnnnnnnnnnNkkGjjk....',
        '....kkkNNnnnnnnnnNkkGjjk....',
        '......kkkNNnnnnnkkGjjjk.....',
        '........kkkkkkkGjjjjjjk.....',
        '.......kGjjjjjjjjjjjjjHk....',
        '......kGjjjjjjjjjjjjjjHhk...',
        '.....kGjjjjjjjjjjjjjjjHhk...',
        '....kGjkGjjjjjjjjjjjjjjhk...',
        '...kGjk.kGGjjjjjjjjjjjjk....',
        '..kGjk...kkGGGjjjjjjGGk.....',
        '..kGk.....kkGjkkkkkGjkk.....',
        '..kGGk.....kGjk...kGjk......',
        '...khhk....kGjk...kGjk......',
        '....khk....kkkkk..kkkkk.....',
        '.....k......................',
        '............................',
        '............................',
      ],
    },
    wyvern_monarch: { base: 'wyvern', tint: { j: 'p', G: 'P', H: 'A', n: 'g', N: 'G' }, extra: [[21, 4, 'y'], [23, 4, 'y'], [25, 4, 'y'], [22, 5, 'y'], [24, 5, 'y']] },
    hydra: {
      rows: [
        '..............kkkkk.............',
        '.............kttddddk...........',
        '.............kdtdyddk...........',
        '......kkkkk..kddkkkkk.kkkkk.....',
        '.....kttddddk.kkNNNk.kttddddk...',
        '.....kdtdyddk.ktdNk..kdtdyddk...',
        '.....kddkkkkk.ktdNk..kddkkkkk...',
        '......kkNNNk..ktdNk...kkNNNk....',
        '.......ktdNk..ktdNk..ktdNk......',
        '.kkkkk..ktdNk.ktdNk.ktdN.kkkkk..',
        'kttddddkktdNk.ktdNk.ktdNkttddddk',
        'kdtdyddkktdNk.ktdNk.ktdNkdtdyddk',
        'kddkkkkkktdNk.ktdNk.ktdNkddkkkkk',
        '.kkNNNk..ktdNkktdNkktdNk.kkNNNk.',
        '...ktdNk.ktdNkktdNkktdNkktdNk...',
        '....ktdNkktdNkktdNkktdNkktdNk...',
        '....ktdNkktdNkktdNkktdNktdNk....',
        '.....ktdNkktdNktdNktdNkktdNk....',
        '......ktdNktdNktdNktdNktdNk.....',
        '.........kkkkktttttkkkkk........',
        '.......kkdddddddddddddddkk......',
        '......kdddddddddddddddddddk.....',
        '.....kdddddddddddddddddddddk....',
        '.....kdddddddddddddddddddddk....',
        '......kNNkddkddkddkNNkddkddk....',
        '......kNNkNNkddkNNkNNkNNkddk....',
        '......kNNkkkkddkNNkNNkkkkddk....',
        '......kNNk..kddkkkkNNk..kddk....',
        '......kNNk..kddk..kNNk..kddk....',
        '......kNNk..kddk..kNNk..kddk....',
        '......kNNk..kddk..kNNk..kddk....',
        '......kkkk..kkkk..kkkk..kkkk....',
      ],
    },
    chaos_hydra: { base: 'hydra', tint: { d: 'B', t: 'b', N: 'z', y: 'r' }, extra: [[16, 17, 'r'], [12, 16, 'r'], [20, 16, 'r']] },
  });
})();
