/* ============================================================================
   view/sprites_quest.js — объекты квестов и ключей (v2.5): хижина провидца,
   страж-квестор, шатёр ключника, пограничная застава, Ящик Пандоры.
   Символ 'r' у шатра и заставы — цвет ключа; движок подменяет его через tint.
   Якорь — низ по центру. Подключать после js/view/sprites.js.
   ========================================================================== */
(function () {
  'use strict';
  H3.Sprites.defineMany({
    seer_hut: { rows: [
      '...........kk...........',
      '..........kAAk..........',
      '.........kAaaAk.........',
      '........kPpppPk.........',
      '.......kPppppppPk.......',
      '......kPpppppppppPk.....',
      '.....kPpppppppppppPk....',
      '....kPpppppPPpppppppPk..',
      '...kPppppppPPppppppppPk.',
      '..kPPPPPPPPPPPPPPPPPPPPk',
      '..kkkkkkkkkkkkkkkkkkkkkk',
      '...kttttttkkkkkttttttk..',
      '...ktttttkAaaAkttttttk..',
      '...kttttkAaccaAktttttk..',
      '...kttttkAaccaAktttttk..',
      '...ktttttkAaaAkttttttk..',
      '...ktttttkkkkkkttttttk..',
      '...ktttttkdddkkttttttk..',
      '...kTTTTTkdddkkTTTTTTk..',
      '...kTTTTTkdddkkTTTTTTk..',
      '...kkkkkkkkkkkkkkkkkkk..',
      '..kGGgGGGGGGGGGGGGGgGGk.',
      '..kkkkkkkkkkkkkkkkkkkkk.',
    ] },

    quest_guard: { rows: [
      '.........kkkkkkk.........',
      '........kEEEEEEEk........',
      '.......kElllllllEk.......',
      '......kEllkkkkkllEk......',
      '.....kEllkeeeeekllEk.....',
      '.....kElkeeyyyeeklEk.....',
      '.....kElkeeyyyeeklEk.....',
      '.....kElkeeeeeeeklEk.....',
      '.....kEllkkkkkkkllEk.....',
      '.....kEllsssssssllEk.....',
      '.....kElksskkkkssklEk....',
      '.....kEkllkeeekllkEk.....',
      '.....kEklkeeeeeklkEk.....',
      '.....kEklkeeeeeklkEk.....',
      '.....kEkkkeeeeekkkEk.....',
      '.....kEEkkeeeeekkEEk.....',
      '.....kEEllkeeekllEEk.....',
      '.....kEElllkkklllEEk.....',
      '.....kEElllllllllEEk.....',
      '.....kEElllllllllEEk.....',
      '....kEEEEEEEEEEEEEEEk....',
      '...kEEEEEEEEEEEEEEEEEk...',
      '...kkkkkkkkkkkkkkkkkkk...',
    ] },

    keymaster: { rows: [
      '.............kk.............',
      '.............krrrrk.........',
      '.............krrrrrk........',
      '.............krrrk..........',
      '.............kk.............',
      '............kiik............',
      '...........kiiiik...........',
      '..........kiirriik..........',
      '.........kiirrrriik.........',
      '........kiiirrrriiik........',
      '.......kiiirrrrrriiik.......',
      '......kiiiirrrrrriiiik......',
      '.....kiiiirrrrrrrriiiik.....',
      '....kiiiiirrrrrrrriiiiik....',
      '...kiiiiiirrrrrrrriiiiiik...',
      '..kiiiiiiirrrkkkrriiiiiiik..',
      '..kiiiiiiirrkzzzkriiiiiiik..',
      '..kIIIIIIIrrkzzzkrIIIIIIIk..',
      '..kIIIIIIIrrkzzzkrIIIIIIIk..',
      '..kkkkkkkkkkkkkkkkkkkkkkkk..',
      '.kGGGGGGGGGGGGGGGGGGGGGGGGk.',
      '.kkkkkkkkkkkkkkkkkkkkkkkkkk.',
    ] },

    border_guard: { rows: [
      '..kkkk................kkkk..',
      '..kllk.kkkkkkkkkkkkkk.kllk..',
      '..kllkkkrrrrrrrrrrrrkkkllk..',
      '.kllllkkrrrrrrrrrrrrkkllllk.',
      '.kleelk.krrrrrrrrrrk.kleelk.',
      '.kleelk..krrrrrrrrk..kleelk.',
      '.kleelk...krrrrrrk...kleelk.',
      '.kleelk....kkkkkk....kleelk.',
      '.kleelkkkkkkkkkkkkkkkkleelk.',
      '.kleeleeeeeeeeeeeeeeeeleelk.',
      '.kleelellllkkkkkkllllleleelk',
      '.kleelellkkzzzzzzkkllleleelk',
      '.kleelelkzzkzkzkzzkleleleelk',
      '.kleelelkzkzzzzzkzkleleleelk',
      '.kleelelkzzkzkzkzzkleleleelk',
      '.kleelelkzkzzzzzkzkleleleelk',
      '.kleelelkzzkzkzkzzkleleleelk',
      '.kleelelkzkzzzzzkzkleleleelk',
      '.kleelelkzzkzkzkzzkleleleelk',
      '.kleelelkzkzzzzzkzkleleleelk',
      '.kEEEEEEkzzkzkzkzzkEEEEEEEk.',
      '.kEEEEEEkzkzzzzzkzkEEEEEEEk.',
      '.kkkkkkkkkkkkkkkkkkkkkkkkkk.',
      'kuuuuuuuuuuuuuuuuuuuuuuuuuuk',
      'kkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    ] },

    pandora_box: { rows: [
      '....kkkkkkkkkkkk....',
      '...kPPPPPPPPPPPPk...',
      '..kPpppppppppppppPk.',
      '..kPpyyppppppppyppPk',
      '.kPppyyypppppppyyppPk',
      '.kPppppppppppppppppPk',
      '.kkkkkkkkkkkkkkkkkkkk',
      '.kPpppppkyyykpppppPk.',
      '.kPpppppkyYykpppppPk.',
      '.kPpppppkyyykpppppPk.',
      '.kPppppppkkkppppppPk.',
      '.kPppppppppppppppppk.',
      '.kPPPPPPPPPPPPPPPPPk.',
      '.kkkkkkkkkkkkkkkkkkk.',
      '..kyyk..........kyyk.',
      '..kkkk..........kkkk.',
    ] },
  });
})();
