/* ============================================================================
   view/sprites_tower_hd.js — существа Башни в крупной сетке (unit 2), стиль Б:
   без контурной линии, тона кладёт рисунок. Собирается скриптом dev/proto/tower_hd.py.
   ========================================================================== */
(function () {
  'use strict';
  H3.Sprites.defineMany({
    /* гремлин: зелёный ушастый коротышка, бурая роба, цепь с чугунным ядром (36×44) */
    gremlin: {
      hd: true, unit: 2,
      rows: [
        '............ggggggggg...............',
        '..........ggggggggggggg.............',
        '.........ggggggggggggggg............',
        '..gg....gggggggggggggggg....gg......',
        '.gggg...gggggGGGggggGGGgg..gggg.....',
        '.ggggggggggggGwwwggGwwwGgggggggg....',
        '.ggggggggggggGwkwggGwkwGgggggggg....',
        '..ggggggggggggGGGggggGGGgggggggg....',
        '...ggg..gggggggggggggggggg..ggg.....',
        '.........ggggggGGGGGGgggg...........',
        '.........gggggGRRRRRRGgg............',
        '..........ggggGGGGGGGGgg............',
        '...........gggggggggggg.............',
        '............NNNNNNNNN...............',
        '............NNNNNNNNN...............',
        '..........NNnnnnnnnnnNN.............',
        '.........NNnnnnnnnnnnnNN............',
        '.........NNnnnnnnnnnnnNN............',
        '........NNnnnnnnnnnnnnnNN...........',
        '.......gggNnnnnnnnnnnnNggg..........',
        '.......gggNnnnnnnnnnnnNggg..........',
        '......ggggNnnnnnnnnnnnNgggg.........',
        '......ggggNnnnnnnnnnnnNgggg.........',
        '......ggggNnnnnnnnnnnnNgggg.........',
        '......ggggNnnnnnnnnnnnNggggg........',
        '......GGGGNnnnnnnnnnnnNGGGGG........',
        '......GGGGNnnnnnnnnnnnNGGGGG........',
        '......gggg.NnnnnnnnnnN.ggeEe........',
        '......gggg.NnnnnnnnnnN..gEeE........',
        '......gggg.NnnnnnnnnnN..gEeE........',
        '.......gg..DDDDDDDDDDD....eEe.......',
        '...........NnnnnnnnnnN....EeE.......',
        '...........NnnnnnnnnnN.....eEe......',
        '...........NnnnnnnnnnN.....EeE......',
        '...........NnnnnnnnnnN......eEe.....',
        '...........NnnnnnnnnnN......EeE.....',
        '...........NnnnnnnnnnN......uuuuu...',
        '..........NNnnnnnnnnnNN....uEEuuuu..',
        '..........NNNNNNNNNNNNN...uEEEuuuuu.',
        '...........ggggg.ggggg....uEEuuuuuu.',
        '...........ggggg.ggggg....uuuuuuuuu.',
        '...........GGGGG.GGGGG....uuuuuuuuu.',
        '..........NNNNNN.NNNNNN....uuuuuuu..',
        '..........DDDDDD.DDDDDD.....uuuuu...',
      ],
    },
    /* мастер-гремлин: фиолетовая роба, красный колпак */
    master_gremlin: { base: 'gremlin', tint: { n: 'p', N: 'P' }, extra: [[12, 0, 'r'], [13, 0, 'r'], [14, 0, 'r'], [15, 0, 'r'], [16, 0, 'r'], [17, 0, 'r'], [18, 0, 'r'], [19, 0, 'r'], [20, 0, 'r'], [10, 1, 'r'], [11, 1, 'r'], [12, 1, 'r'], [13, 1, 'r'], [14, 1, 'r'], [15, 1, 'r'], [16, 1, 'r'], [17, 1, 'r'], [18, 1, 'r'], [19, 1, 'r'], [20, 1, 'r'], [21, 1, 'r'], [22, 1, 'r'], [9, 2, 'r'], [10, 2, 'r'], [11, 2, 'r'], [12, 2, 'r'], [13, 2, 'r'], [14, 2, 'r'], [15, 2, 'r'], [16, 2, 'r'], [17, 2, 'r'], [18, 2, 'r'], [19, 2, 'r'], [20, 2, 'r'], [21, 2, 'r'], [22, 2, 'r'], [23, 2, 'r'], [8, 3, 'R'], [9, 3, 'R'], [10, 3, 'R'], [11, 3, 'R'], [12, 3, 'R'], [13, 3, 'R'], [14, 3, 'R'], [15, 3, 'R'], [16, 3, 'R'], [17, 3, 'R'], [18, 3, 'R'], [19, 3, 'R'], [20, 3, 'R'], [21, 3, 'R'], [22, 3, 'R'], [23, 3, 'R']] },
    /* каменная гаргулья: серая крылатая статуя-демон, рога, клыки, когти, парит (композитор) (44×48) */
    stone_gargoyle: {
      hd: true, unit: 2,
      rows: [
        '.......EEEE......................EEEE.......',
        '...EEEEEEllEE..................EEllEEEEEE...',
        '.EEEEEEEElllEEE..............EEElllEEEEEEEE.',
        '..lEEEEEEElllEEE............EEElllEEEEEEEll.',
        '..ElEEEEEEllllEEEE........EEEEllllEEEEEElE..',
        '...ElEEEEEElllllEEEE....EEEElllllEEEEEElE...',
        '.EE.lEEEEEEllllllEEEE..EEEEllllllEEEEEEl.EE.',
        '.EEE.lEEEEElllllllleeeeeellllllllEEEEEl.EEE.',
        '.EEEEElEEEEEllllllllllllllllllllEEEEElEEEEE.',
        '.EEEE.lEEEEEllllllllllllllllllllEEEEEl.EEEE.',
        '.EEEEE.lEEEEllllllllllllllllllllEEEEl.EEEEE.',
        '.EEEEEEElEEEEllellllllllllllellEEEElEEEEEEE.',
        '.EEEEEEElEEEEleeelllllllllleeelEEEElEEEEEEE.',
        '.EEEEEEEElEEEleeeeelllllleeeeelEEElEEEEEEEE.',
        '.EEEEEEEEElEEEeeewwweeeeewwweeEEElEEEEEEEEE.',
        '.EEEEEEEEElEEEeeewkweeeeewkweeEEElEEEEEEEEE.',
        '.EEEEEEEEEElEEeeeeeeeeeeeeeeeeEElEEEEEEEEEE.',
        '.EEEEEEEEEEElEeeeeeeeeeeeeeeeeElEEEEEEEEEEE.',
        '.EllEEEEEEEElEEeEwwEEEEEEEwweEElEEEEEEEElll.',
        '.EEElllEEEEEElElEwwEEEEEEEwwlElEEEEEElllEEE.',
        '.EEEEEEllEEEEEleeEEEEEEEEEEeelEEEEEllEEEEEE.',
        '...EEEEEElllEEeeeEEEEEEEEEEeeeEElllEEEEEE...',
        '....EEEEEEEElleeeeeeeeeeeeeeeellEEEEEEEE....',
        '.....EEEEEEEEeeeeeeeeeeeeeeeeeeEEEEEEEE.....',
        '.......EEEEEEeeeeeeEEEEEEeeeeeeEEEEEE.......',
        '........EEEEeeeeeEEEEEEEEEEeeeeeEEEE........',
        '.........EEEeeeeeEEEEEEEEEEeeeeeEEE.........',
        '...........eeeeeeeEEEEEEEEeeeeeee...........',
        '..........eeeeeeeeEEEEEEEEeeeeeeee..........',
        '.........eeeeeeeeEEEEEEEEEEeeeeeeee.........',
        '........eeeeeeeeEEEEEEEEEEEEeeeeeeee........',
        '........eeeeeeeEEEEEEEEEEEEEEeeeeeee........',
        '.......eeeeeee.EEEEEEEEEEEEEE.eeeeeee.......',
        '......eeeeeee.EEEEEEEEEEEEEEEE.eeeeeee......',
        '.......eeeee..EEEEEEEEEEEEEEEE..eeeee.......',
        '....ll.llell.EEEEEEEEEEEEEEEEEE.llell.ll....',
        '....llllllllEEEEEEEE....EEEEEEEEllllllll....',
        '....ll.ll.lEEEEEEEE......EEEEEEEEl.ll.ll....',
        '....ll.ll.lEEEEEEEE......EEEEEEEEl.ll.ll....',
        '....l..l..EEEEEEEE........EEEEEEEE..l..l....',
        '..........EEEEEEE..........EEEEEEE..........',
        '..........eeeEEEE...........eeeeee..........',
        '.........eeeeEEEe..........eeeeeeee.........',
        '.........ellEEEell.........ellellell........',
        '..........lEEEEell..........llellell........',
        '...........EEE..............................',
        '...........EE...............................',
        '............................................',
      ],
    },
    /* обсидиановая гаргулья: чёрный камень с фиолетовым отливом, светящиеся глаза */
    obsidian_gargoyle: { base: 'stone_gargoyle', tint: { e: 'u', E: 'z', l: 'p', w: 'A' } },
    /* каменный голем: приземистый истукан из песчаника, трещины, щели глаз (44×52) */
    stone_golem: {
      hd: true, unit: 2,
      rows: [
        '................IIIIIIIIIIII................',
        '...............IITTTTTTTTTTdd...............',
        '...............ITTTTTTTTTTTTd...............',
        '...............ITTkkkTTTkkkTd...............',
        '...............ITTkkkTTTkkkTd...............',
        '...............ITTTTTTTTTTTTd...............',
        '...............ITTTdddddddTTd...............',
        '...............IdTTTTTTTTTTdd...............',
        '................dddddddddddd................',
        '........IIIIIIIIIIIIIIIIIIIIIIIIIIIIII......',
        '.....IIITTTTTTTTTTTTTTTTTTTTTTTTTTTTTTddd...',
        '....ITTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTd..',
        '....ITTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTd..',
        '...ITTTTTTddITTTTTTTTTTTTTTTTTTTTddITTTTTTd.',
        '..ITTTTTTTddITTTTTTTTTTdTTTTTTTTTddITTTTTTTd',
        '..ITTTTTTTddITTTTTTTTTTdTTTTTTTTTddITTTTTTTd',
        '..ITTTTTTTddITTTTTTTTTddTTTTTTTTTddITTTTTTTd',
        '..ITTTTTTTddITTTTTTTTddTTTTTTTTTTddITTTTTTTd',
        '..ITTTTTTTddITTTTTTTTddTTTTTTTTTTddITTTTTTTd',
        '..ITdddddTddITTTTTTTTdTTTTTTTTTTTddITTTTTTTd',
        '..ITdddddTddITTTTTTTddTTTTTdddTTTddITTTTTTTd',
        '..ITdddddTddITTTTTTTddTTTTTdddTTTddITTTTTTTd',
        '..ITTTTTTTddITTTTTTTdTTTTTTTTdddTddITTTTTTTd',
        '..ITTTTTTTddITTTTTTTdTTTTTTTTTTddddITTTTTTTd',
        '..ITTTTTTTddITTTTTTTdTTTTTTTTTTddddITTTTTTTd',
        '..ITTTTTTTddITTTTTTddTTTTTTTTTTTTddITTTTTTTd',
        '..ITTTTTTTddITTTTTTdTTTTTTTTTTTTTdddddddTTTd',
        '..ITTTTTTTddITTTTTTdTTTTTTTTTTTTTdddddddTTTd',
        '..ITTTTTTTddITTTTTddTTTTTTTTTTTTTdddddddTTTd',
        '..ITTTTTTTddITTTTTdTTTTTTTTTTTTTTddITTTTTTTd',
        '..ITTTTTTTddITTTTTdTTTTTTTTTTTTTTddITTTTTTTd',
        '..ITTTTTTTddITTTTTdTTTTTTTTTTTTTTddITTTTTTTd',
        '..IIIIIIIIddITTTTTdTTTTTTTTTTTTTTddIIIIIIIId',
        '..IIIIIIIIddITTTTTdTTTTTTTTTTTTTTddIIIIIIIId',
        '..ITTTTTTTddITTTTdTTTTTTTTTTTTTTTddITTTTTTTd',
        '..ITTTTTTTddITTTTdTTTTTTTTTTTTTTTddITTTTTTTd',
        '..ITTTTTTTddITTTTdTTTTTTTTTTTTTTTddITTTTTTTd',
        '..ITTTTTTTddITTTTdTTTTTTTTTTTTTTTddITTTTTTTd',
        '..IdddddddddITTTTdTTTTTTTTTTTTTTTddIddddddd.',
        '...........dddddddddddddddddddddddd.........',
        '..........ITTTTTTTTTTd..ITTTTTTTTTTd........',
        '..........ITTTTTTTTTTd..ITTTTTTTTTTd........',
        '..........ITTTTTTTTTTd..ITTTTTTTTTTd........',
        '..........ITTTTTTTTTTd..ITTTTTTTTTTd........',
        '..........ITTTTdTTTTTd..ITTTTTTTTTTd........',
        '..........ITTTTdTTTTTd..ITTTTTTdTTTd........',
        '..........ITTTTTdTTTTd..ITTTTTTdTTTd........',
        '..........ITTTTTTTTTTd..ITTTTTTTTTTd........',
        '..........ITTTTTTTTTTd..ITTTTTTTTTTd........',
        '.........IITTTTTTTTTTdd.IITTTTTTTTTdd.......',
        '.........IIIIIIIIIIIIdd.IIIIIIIIIIIIdd......',
        '.........dddddddddddddd.ddddddddddddd.......',
      ],
    },
    /* железный голем: стальной корпус, заклёпки, огненные глаза */
    iron_golem: { base: 'stone_golem', tint: { I: 'l', T: 'e', d: 'E' }, extra: [[18, 3, 'f'], [19, 3, 'f'], [20, 3, 'f'], [24, 3, 'f'], [25, 3, 'f'], [26, 3, 'f'], [18, 4, 'f'], [19, 4, 'f'], [20, 4, 'f'], [24, 4, 'f'], [25, 4, 'f'], [26, 4, 'f'], [5, 12, 'y'], [6, 12, 'y'], [39, 12, 'y'], [40, 12, 'y'], [5, 13, 'y'], [6, 13, 'y'], [39, 13, 'y'], [40, 13, 'y'], [12, 33, 'y'], [13, 33, 'y'], [31, 33, 'y'], [32, 33, 'y'], [12, 34, 'y'], [13, 34, 'y'], [31, 34, 'y'], [32, 34, 'y']] },
    /* маг: синяя мантия, остроконечная шляпа со звездой, седая борода, посох с шаром (44×52) */
    mage: {
      hd: true, unit: 2,
      rows: [
        '..............bb............................',
        '..............bbb...................aaa.....',
        '.............bbbb.................aaaaaaa...',
        '.............bbbbb...............aaAAAaaaa..',
        '............bbbbbb...............aAAAAAaaa..',
        '............bbbbbbb.............aaAAAAAaaaa.',
        '...........bbbbbbbb..............aAAAAAaaa..',
        '...........bbbbbbbbb.............aaAAAaaaa..',
        '..........bbbybbbbbb..............aaaaaaa...',
        '..........bbyyybbbbbb...............aaa.....',
        '.........bbbbybbbbbbb..............NnnN.....',
        '.........bbbbbbbbbbbbb.............NnnN.....',
        '........bbbbbbbbbbbbbb.............NnnN.....',
        '....BBBBBBBBBBBBBBBBBBBBBB.........NnnN.....',
        '....BBBBBBBBBBBBBBBBBBBBBB.........NnnN.....',
        '.........sssssssssss...............NnnN.....',
        '........sssssssssssss..............NnnN.....',
        '........ssswwsssssswws.............NnnN.....',
        '........ssskwsssssskws.............NnnN.....',
        '........sssssssssssss..............NnnN.....',
        '.........wwwsssssswww..............NnnN.....',
        '........wwwwwwsswwwwww.............NnnN.....',
        '........wwwwwwwwwwwwww.............NnnN.....',
        '.......wwwwwwwwwwwwwww.............NnnN.....',
        '.....BBwwwwwwwwwwwwwwBB............NnnN.....',
        '.....BBwwwwwwwwwwwwwwBB............NnnN.....',
        '....BBbbwwwwwwwwwwwwbbBB...........NnnN.....',
        '...BBbbbbwwwwwwwwwwbbbbBBBBBBBBBBB.NnnN.....',
        '...BBbbbbwwwwwwwwwwbbbbBBBBBBBBBBB.NnnN.....',
        '...Bbbbbbbwwwwwwwwbbbbbbbbbbbbbbbb.NnnN.....',
        '...Bbbbbbbbwwwwwwbbbbbbbbbbbbbbsss.NnnN.....',
        '...Bbbbbbbbwwwwwwbbbbbbbbbbbbbbsss.NnnN.....',
        '...Bbbbbbbbbwwwwbbbbbbbbbbbbbbbsss.NnnN.....',
        '...Bbbbbbbbbbwwbbbbbbbbbbbbbbbbsss.NnnN.....',
        '...Bbbbbbbbbbwwbbbbbbbbbbbbbbbbsss.NnnN.....',
        '...BbbbbbbbbbbbbbbbbbbbbBBBBBBBsss.NnnN.....',
        '...BbbbbbbbbbbbbbbbbbbbbB..........NnnN.....',
        '...BbbbbbbbbbbbbbbbbbbbbB..........NnnN.....',
        '...BbbbbbbbbbbbbbbbbbbbbB..........NnnN.....',
        '...BbbbyyyyyyyyyyyyyyybbB..........NnnN.....',
        '...BbbbbbbbbbbbbbbbbbbbbB..........NnnN.....',
        '...BbbbbbbbbbbbbbbbbbbbbB..........NnnN.....',
        '...BbbbbbbbbbbbbbbbbbbbbB..........NnnN.....',
        '...BbbbbbbbbbbbbbbbbbbbbB..........NnnN.....',
        '...BbbbbbbbbbbbbbbbbbbbbB..........NnnN.....',
        '...BbbbbbbbbbbbbbbbbbbbbB..........NnnN.....',
        '...BbbbbbbbbbbbbbbbbbbbbB..........NnnN.....',
        '...BbbbbbbbbbbbbbbbbbbbbB..........NnnN.....',
        '...BbbbbbbbbbbbbbbbbbbbbB..........NnnN.....',
        '..BBbbbbbbbbbbbbbbbbbbbbBB.........NnnN.....',
        '..BBbbbbbbbbbbbbbbbbbbbbBB.........NnnN.....',
        '..BBBBBBBBBBBBBBBBBBBBBBBB..................',
      ],
    },
    /* архимаг: пурпурная мантия с золотой оторочкой, золотой посох, шар голубой */
    arch_mage: { base: 'mage', tint: { b: 'p', B: 'P', n: 'y', N: 'Y', a: 'C', A: 'c' }, extra: [[4, 14, 'y'], [5, 14, 'y'], [6, 14, 'y'], [7, 14, 'y'], [8, 14, 'y'], [9, 14, 'y'], [10, 14, 'y'], [11, 14, 'y'], [12, 14, 'y'], [13, 14, 'y'], [14, 14, 'y'], [15, 14, 'y'], [16, 14, 'y'], [17, 14, 'y'], [18, 14, 'y'], [19, 14, 'y'], [20, 14, 'y'], [21, 14, 'y'], [22, 14, 'y'], [23, 14, 'y'], [24, 14, 'y'], [25, 14, 'y'], [2, 50, 'y'], [3, 50, 'y'], [4, 50, 'y'], [5, 50, 'y'], [6, 50, 'y'], [7, 50, 'y'], [8, 50, 'y'], [9, 50, 'y'], [10, 50, 'y'], [11, 50, 'y'], [12, 50, 'y'], [13, 50, 'y'], [14, 50, 'y'], [15, 50, 'y'], [16, 50, 'y'], [17, 50, 'y'], [18, 50, 'y'], [19, 50, 'y'], [20, 50, 'y'], [21, 50, 'y'], [22, 50, 'y'], [23, 50, 'y'], [24, 50, 'y'], [25, 50, 'y'], [2, 51, 'y'], [3, 51, 'y'], [4, 51, 'y'], [5, 51, 'y'], [6, 51, 'y'], [7, 51, 'y'], [8, 51, 'y'], [9, 51, 'y'], [10, 51, 'y'], [11, 51, 'y'], [12, 51, 'y'], [13, 51, 'y'], [14, 51, 'y'], [15, 51, 'y'], [16, 51, 'y'], [17, 51, 'y'], [18, 51, 'y'], [19, 51, 'y'], [20, 51, 'y'], [21, 51, 'y'], [22, 51, 'y'], [23, 51, 'y'], [24, 51, 'y'], [25, 51, 'y'], [16, 3, 'y'], [17, 3, 'y'], [16, 4, 'y'], [17, 4, 'y']] },
    /* джинн: синий дух без ног, руки скрещены на груди, дымный хвост, серьга (композитор) (52×56) */
    genie: {
      hd: true, unit: 2,
      rows: [
        '....................................................',
        '........................bbbzzzz.....................',
        '.......................bbzzzzzzzzz..................',
        '......................bzzzzzzzzzzzzz................',
        '.....................bbzzzzzzzzzzzzzzz..............',
        '....................bbbzzzzzbbbbbbzzzzzz............',
        '....................bbbbbbbbbbbbbb..zzzzz...........',
        '....................bbbbwwbbbwwbbb....zzz...........',
        '....................bbbbwkbbbkwbbb..................',
        '....................bbbbbbbbbbbbbbyy................',
        '....................bbbbbbbbbbbbbyyyy...............',
        '.....................bbbbBBBBBbbbyyyy...............',
        '......................bbbbbbbbbb..yy................',
        '..............bbbb.....bbbbbbbb.....bbbb............',
        '.............bbbbbbbbBBbbbbbbbbBBbbbbbbbb...........',
        '............bbbbbbbbbbbBbbbbbbBbbbbbbbbbbb..........',
        '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..........',
        '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..........',
        '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..........',
        '............bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..........',
        '............bbbbbbbbbbbbbbbbbbbBBBBbbbbbbb..........',
        '...........bbbbbbbbbbbbbbbbbbBBBBBBbbbbbbbb.........',
        '...........bbbbbbbbbbbbbbbBBBBBBBBbbbbbbbbb.........',
        '..........bbbbbbbbbbbbbbBBBBBBBBbbbbbbbbbbbb........',
        '.........ccccccbbbbbbBBBBBBBBbBBBbbbbbbcccccc.......',
        '........ccccccccbbbBBBBBBBbbBBBBBBBbbbcccccccc......',
        '........ccccccccBBBBBBBBbbbbbbBBBBBBBBcccccccc......',
        '........ccccccccBBBBBbbbbbbbbbbbbBBBBBcccccccc......',
        '........ccccccccBBBbbbbbbbbbbbbbbbbBBBcccccccc......',
        '.........ccccccBbbbbbbbbbbbbbbbbbbbbbbBcccccc.......',
        '..........BBBB..yyyyyyyyyyyyyyyyyyyyyy..BBBB........',
        '................yyyyyyyyyyyyyyyyyyyyyy..............',
        '................yyyyyyyyyyyyyyyyyyyyyy..............',
        '................yyyyyyyyyyyyyyyyyyyyyy..............',
        '..................cccCCCCCCcccccc...................',
        '.................cccCCCCCCCCcccc....................',
        '................ccccCCCCCCCCccc.....................',
        '...............cccccCCCCCCCCccc.....................',
        '...............cccccCCCCCCCCcc......................',
        '..............cccccccCCCCCCcc.......................',
        '.............ccccccccCCCCCCcc.......................',
        '............ccccccccccCCCCcc........................',
        '...........ccCCcccccccccccc.........................',
        '..........ccCCCCccccccccccc.........................',
        '.........ccCCCCCCcccccccc...........................',
        '........cccCCCCCCcccccc.............................',
        '.......ccccCCCCCCcccc...............................',
        '....cccccccCCCCCCc..................................',
        '..ccccccccccCCCC....................................',
        '.ccccccccccccCC.....................................',
        '.ccccccccccc........................................',
        '.cccccccccc.........................................',
        '.cwwwwccccc.........................................',
        '.wwwwwwccc..........................................',
        '.wwwwwwcc...........................................',
        '..wwww..............................................',
      ],
    },
    /* мастер-джинн: голубая кожа, белая дымка, золотой обруч на голове */
    master_genie: { base: 'genie', tint: { b: 'c', B: 'b', c: 'w', C: 'l', y: 'Y' }, extra: [[22, 3, 'Y'], [23, 3, 'Y'], [24, 3, 'Y'], [25, 3, 'Y'], [26, 3, 'Y'], [27, 3, 'Y'], [28, 3, 'Y'], [29, 3, 'Y'], [30, 3, 'Y'], [31, 3, 'Y'], [32, 3, 'Y'], [22, 4, 'Y'], [23, 4, 'Y'], [24, 4, 'Y'], [25, 4, 'Y'], [26, 4, 'Y'], [27, 4, 'Y'], [28, 4, 'Y'], [29, 4, 'Y'], [30, 4, 'Y'], [31, 4, 'Y'], [32, 4, 'Y']] },
    /* нага: женщина-змея, шесть рук с саблями, кольца бирюзового хвоста (композитор) (56×60) */
    naga: {
      hd: true, unit: 2,
      rows: [
        '.lll................................................lll.',
        '.lll................................................lll.',
        '..lll.....................zzzz.....................lll..',
        '..lll...................zzzzzzzz...................lll..',
        '...lll................zzzzzzzzzzzz................lll...',
        '...lll................zzzzzzzzzzzz................lll...',
        '....lllS..............zzzzzzzzzzzz..............Slll....',
        '....lllSs.............zzzzzzzzzzzz.............sSlll....',
        '....SllSss............zzsssssssszz............ssSllS....',
        'l...SSSSssss..........zzsssssssszz..........ssssSSSS..ll',
        'll....sssssss........zzzsswwswwszzz........sssssss...lll',
        'll......sssssss......zzzsswkskwszzz......sssssss.....lll',
        'll.......sssssss.....zzzsssssssszzz.....sssssss......lll',
        'lll........sssssss...zzzzsssssszzzz...sssssss........lll',
        'lll.........sssssss.zzzzzzsssszzzzzz.sssssss........lll.',
        'lll...........sssssszzzz..zzzz..zzzzssssss..........lll.',
        '.lll...........ssssszzzzsssssssszzzzsssss...........lll.',
        '.lll.............ssszzzzsssssssszzzzsss.............lll.',
        '.lll..............sssssMMMMMMMMMMsssss.............lll..',
        '..lll...............ssMMMMMMMMMMMMss...............lll..',
        '..lllSssssssssssssssssMMMMMMMMMMMMssssssssssssssssSlll..',
        '..lllSsssssssssssssssssMMMMMMMMMMsssssssssssssssssSlll..',
        '..SllSsssssssssssssssssMMMMMMMMMMsssssssssssssssssSllS..',
        '..SSSSssssssssssssssssMMMMMMMMMMMMssssssssssssssssSSSS..',
        '....................ssssssssssssssss....................',
        '...................ssssssssssssssssss...................',
        '..................ssssssssssssssssssss..................',
        'l................ssssssssSSSSSSssssssss...............ll',
        'lll............ssssssssSSSSSSSSSSssssssss............lll',
        'llll..........ssssssssSSSSSSSSSSSSssssssss.........Cllll',
        'lllll.......sssssss.ssSSSSSSSSSSSSss.sssssss.......llll.',
        '.lllll.....sssssss..sssSSSSSSSSSSsss..sssssss.....llllC.',
        '..lllll..sssssss....sssssSSSSSSsssss....sssssss..llllCC.',
        '...lllllsssssss.....ssssssssssssssss.....sssssssllllqqq.',
        '....llllSSsss.......ssssssssssssssss.......sssSllllqqqq.',
        '.....llllSss........ssssssssssssssss........ssSlllqqqqq.',
        '......SllSs...qqqqqqqqqqqqqqqqqqqqqq.........sSllSqqqq..',
        '......SSSSqqqqqqqqqqqqqqqqqqqqqqqqqq..........SSSSqqqq..',
        '.......qqqqqqqqqqqqqqqqqqqqqqqqqqqq............qqqqqq...',
        '.....qqqqqqqqqqqqqqqqqqqqqqqqqqqqqq............qqqqqq...',
        '.....qqqqqqqqqqqqqqqqqqqqqqqqqqqqqq...........qqqqqq....',
        '....qCCCCCCCCCCCCqqqqqqqqqqqqqqqqqqqq.........qqqqqq....',
        '....qCCCCCCCCCCCCCCCCCCCCCCCQQqqqqqqqqqqqq.....qqqq.....',
        '.....qCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCqqqqqqq...qq.....',
        '.....qqqQQQQQQQQQCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC......',
        '.....qqqqqQQQQQQQQQQQQQQQQQQCCCCCCCCCCCCCCCCCCCCCCC.....',
        '....qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqCCCCCCCCCCCCq....',
        '...qqqqqqqqqqqqqqqqqqqqqqqQQQQQQQQQQQQqqqqqqqqqqqqqqq...',
        '..qqqqqqqqqqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQqqqqqqqqqq..',
        '..qCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCq..',
        '..qCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCq..',
        '..qqqqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQqqqq..',
        '...qqqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQqqq...',
        '....qqqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQqqq....',
        '.....qqqqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQqqqq.....',
        '.......qqqqqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQqqqqq.......',
        '..........qqqqqqqqQQQQQQQQQQQQQQQQQQQQqqqqqqqq..........',
        '..............qqqqqqqqqqqqqqqqqqqqqqqqqqqq..............',
        '...................qqqqqqqqqqqqqqqqqq...................',
        '........................................................',
      ],
    },
    /* королева наг: пурпурная чешуя, красные клинки, золотая корона */
    naga_queen: { base: 'naga', tint: { q: 'x', Q: 'P', C: 'p', l: 'r' }, extra: [[23, 3, 'y'], [24, 3, 'y'], [25, 3, 'y'], [26, 3, 'y'], [27, 3, 'y'], [28, 3, 'y'], [29, 3, 'y'], [30, 3, 'y'], [31, 3, 'y'], [32, 3, 'y'], [33, 3, 'y'], [23, 4, 'y'], [24, 4, 'y'], [25, 4, 'y'], [26, 4, 'y'], [27, 4, 'y'], [28, 4, 'y'], [29, 4, 'y'], [30, 4, 'y'], [31, 4, 'y'], [32, 4, 'y'], [33, 4, 'y'], [23, 2, 'y'], [24, 2, 'y'], [27, 2, 'y'], [28, 2, 'y'], [32, 2, 'y'], [33, 2, 'y']] },
    /* гигант: исполин в белой тоге через плечо, тёмные волосы, молния в поднятой руке (64×60) */
    giant: {
      hd: true, unit: 2,
      rows: [
        '..........................DDDDDDDD........................fwwf..',
        '........................DDDDDDDDDDDD.....................fwwf...',
        '.......................DDDDDDDDDDDDDD...................fwwf....',
        '.......................DDDDDDDDDDDDDD....................fwwf...',
        '.......................DDSSSSSSSSSSDD.....................fwwf..',
        '.......................DSSSSSSSSSSSSD......................fwwf.',
        '.......................DSSSSSSSSSSSSD.......................fwwf',
        '.......................DSSSwwwSSwwwSD................SSSSSSfwwf.',
        '.......................DSSSwkwSSwkwSD................SSnnSSwwf..',
        '.......................DSSSSSSSSSSSSD................SSnnSSwf...',
        '........................SSSSSSnnSSSS.................SSSSSSf....',
        '........................SSSSSSSSSSSS................SSSSSfwwf...',
        '........................SSSSnnnnnSSS................SSSSSSfwwf..',
        '.........................SSSSSSSSSS................SSSSSS..fwwf.',
        '..........................SSSSSSSS.................SSSSSS...fwwf',
        '...........................SSSSSS.................SSSSSS...fwwf.',
        '...........................SSSSSS.................SSSSSS........',
        '..................LLLLLLLLLLLLLLLLSSSSSSSSSSSSSSSSSSSSS.........',
        '..................LLLLLLLLLLLLLLLLSSSSSSSSSSSSSSSSSSSSS.........',
        '................LLLLLLLLLLLLLLLLLLSSSSSSSSSSSSSSSSSSSSS.........',
        '...............LLLLLLLLLLLLLLLLLLLSSSSSSSSSSSSSSSSSSSS..........',
        '..............LLLLLLLLLLLLLLLLLLLLSSSSSSSSSSSSSSSSSSSS..........',
        '..............LLLLLLLLLLLLLLLLLLLLSSSSSSSSSSSSSSSSSS............',
        '..............LLLLLLLLLLLLLLLLLLLLSSSSSSSSSSSSSSSSSS............',
        '..............LLLLLLLLLLLLLLLLLLLLLSSSSSSSSSSSSSSS..............',
        '..............LLLLLLLLLLLLLLLLLLLLLLSSSSSSSSSSSSSS..............',
        '..............LLLLLL.LLLLLLLLLLLLLLLLSSSSSSSS.SSSS..............',
        '..............LLLLLL.LLLLLLLLLLLLLLLLLSSSSSSS.SSSS..............',
        '..............LLLLLL.LLLLLLLLLLLLLLLLLSSSSSSS.SSSS..............',
        '..............LLLLLL.LLLLLLLLLLLLLLLLLLSSSSSS.SSSS..............',
        '..............SSSSSS.LLLLLLLLLLLLLLLLLLLSSSSS.SSSS..............',
        '..............SSSSSS.LLLLLLLLLLLLLLLLLLLLSSSS.SSSS..............',
        '..............SSSSSS.LLLLLLLLLLLLLLLLLLLLLSSS.SSSS..............',
        '..............SSSSSS.LLLLLLLLLLLLLLLLLLLLLSSS.SSSS..............',
        '..............SSSSSS.LLLLLLLLLLLLLLLLLLLLLLSS.SSSS..............',
        '..............SSSSSS.LLLLLLLLLLLLLLLLLLLLLLLS.SSSS..............',
        '..............SSSSSS.LLLLLLLLLLLLLLLLLLLLLLLL.SSSS..............',
        '..............SSSSSS.LLLLLLLLLLLLLLLLLLLLLLLL.SSSS..............',
        '...............SSSS..YYYYYYYYYYYYYYYYYYYYYYYY.SSSS..............',
        '.....................LLLLLLLLLLLLLLLLLLLLLLLL...................',
        '.....................LLLLLLLLLLLLLLLLLLLLLLLL...................',
        '.....................LLLLLLLLLLLLLLLLLLLLLLLL...................',
        '.....................LLLLLLLLLLLLLLLLLLLLLLLL...................',
        '.....................LLLLLLLLLLLLLLLLLLLLLLLL...................',
        '.....................LLLLLLLLLLLLLLLLLLLLLLLL...................',
        '.....................LLLLLLLLLLLLLLLLLLLLLLLL...................',
        '.....................llllllllllllllllllllllll...................',
        '.....................SSSSSSSSSS...SSSSSSSSSS....................',
        '.....................SSSSSSSSSS...SSSSSSSSSS....................',
        '.....................SSSSSSSSSS...SSSSSSSSSS....................',
        '.....................SSSSSSSSSS...SSSSSSSSSS....................',
        '.....................SSSSSSSSSS...SSSSSSSSSS....................',
        '.....................SSSSSSSSSS...SSSSSSSSSS....................',
        '.....................SSSSSSSSSS...SSSSSSSSSS....................',
        '.....................SSSSSSSSSS...SSSSSSSSSS....................',
        '.....................SSSSSSSSSS...SSSSSSSSSS....................',
        '.....................SSSSSSSSSS...SSSSSSSSSS....................',
        '....................NNNNNNNNNNN...NNNNNNNNNNN...................',
        '....................NNNNNNNNNNN...NNNNNNNNNNN...................',
        '....................DDDDDDDDDDD...DDDDDDDDDDD...................',
      ],
    },
    /* титан: синяя кожа, золотая тога-доспех и шлем, молния */
    titan: { base: 'giant', tint: { S: 'b', n: 'B', L: 'y', l: 'Y', D: 'y', N: 'Y' }, extra: [[28, 0, 'r'], [29, 0, 'r'], [30, 0, 'r'], [31, 0, 'r'], [32, 0, 'r'], [33, 0, 'r'], [28, 1, 'r'], [29, 1, 'r'], [30, 1, 'r'], [31, 1, 'r'], [32, 1, 'r'], [33, 1, 'r'], [28, 2, 'r'], [29, 2, 'r'], [30, 2, 'r'], [31, 2, 'r'], [32, 2, 'r'], [33, 2, 'r']] },
  });
})();
