/* ============================================================================
   view/sprites_fortress_hd.js — существа Крепости в крупной сетке (unit 2), стиль Б:
   без контурной линии, тона кладёт рисунок. Собирается скриптом dev/proto/fortress_hd.py.
   ========================================================================== */
(function () {
  'use strict';
  H3.Sprites.defineMany({
    /* гнолл: гиеноголовый, тёмные уши и грива, светлая морда с клыками, кожаный жилет, алебарда (40×48) */
    gnoll: {
      hd: true, unit: 2,
      rows: [
        '........DD...........DD...........l.....',
        '.......DDDD.........DDDD.........lll....',
        '.......DDDDD.......DDDDD.........lll....',
        '.......DDDDDDDDDDDDDDDDD......llllll....',
        '.......DDDDDDDDDDDDDDDDD....llllllll....',
        '.......nnnnnnDDDDDnnnnnn...llllllll.....',
        '.......nnnnnnnnnnnnnnnnn..llllllllD.....',
        '.......nnnnnnnnnnnnnnnnn..lllllllDDD....',
        '.......nnyyynnnnnnnyyynn..lllllllDDD....',
        '.......nnykynnnnnnnykynn...llllllDDD....',
        '.......nnyyynnnnnnnyyynn....lllllDDD....',
        '.......nnnnnnnnnnnnnnnnn......lllDDD....',
        '........nnnnntttttttnnnn.........DDD....',
        '........nnnttttttttttnnn.........DDD....',
        '.........nntkkttttkktnn..........DDD....',
        '.........nntkkttttkktnn..........DDD....',
        '..........nttttttttttn...........DDD....',
        '...........twwttttwwt............DDD....',
        '...........www.nnn.www...........DDD....',
        '.............nnnnnnn.............DDD....',
        '.........NNNNNNNNNNNNNNNNN.......DDD....',
        '.........NNNNNNNNNNNNNNNNN.......DDD....',
        '.......NNNNNNNNNNNNNNNNNNNNN.....DDD....',
        '....nnnnNNNNNNNNNNNNNNNNNNNnnnn..DDD....',
        '....nnnnNNNNNNNNNNNNNNNNNNNnnnn..DDD....',
        '....nnnnNNNNNNNNNNNNNNNNNNNnnnn..DDD....',
        '....nDDnNNNNNNNNNNNNNNNNNNNnnnnnnDDDnn..',
        '....nDDnNNNNNNNNNNNNNNNNNNNnnnnnnDDDnn..',
        '....nDDnNNNNNNNNNNNNNNNNNNNnnnnnnDDDnn..',
        '....nnnnNNNNNNNNNNNNNNNNNNNnnnnnnDDDnn..',
        '....nnnnNNNNNNNNNNNNNNNNNNNnnnnnnDDDnn..',
        '....nnnnNNNNNNNNNNNNNNNNNNNnnnnnnnnnnn..',
        '....nnnnNNNNNNNNNNNNNNNNNNN......DDD....',
        '....nnnnNNNNNNNNNNNNNNNNNNN......DDD....',
        '....nnnn.NNNNNNNNNNNNNNNNN.......DDD....',
        '....nnnn.NNNNNNNNNNNNNNNNN.......DDD....',
        '....nnnn.yyyyyyyyyyyyyyyyy.......DDD....',
        '....nnnn.yyyyyyyyyyyyyyyyy.......DDD....',
        '.....nn..TTTTTTTTTTTTTTTTT.......DDD....',
        '.........TTTTTTTTTTTTTTTTT.......DDD....',
        '.........TTTTTTTTTTTTTTTTT.......DDD....',
        '.........TTTTTTTTTTTTTTTTT.......DDD....',
        '.........nnnnnn...nnnnnn.........DDD....',
        '.........nDDnnn...nnnDDn.........DDD....',
        '.........nDDnnn...nnnDDn.........DDD....',
        '.........nnnnnn...nnnnnn.........DDD....',
        '........DDDDDDD...DDDDDDD........DDD....',
        '........DDDDDDD...DDDDDDD........DDD....',
      ],
    },
    /* гнолл-мародёр: жилет в тёмно-красный, повязка чёрная, красный гребень на гриве */
    gnoll_marauder: { base: 'gnoll', tint: { N: 'R', T: 'z' }, extra: [[14, 0, 'r'], [15, 0, 'r'], [16, 0, 'r'], [13, 1, 'r'], [14, 1, 'r'], [15, 1, 'r'], [16, 1, 'r'], [17, 1, 'r'], [13, 2, 'r'], [14, 2, 'r'], [15, 2, 'r'], [16, 2, 'r'], [17, 2, 'r'], [12, 3, 'r'], [13, 3, 'r'], [14, 3, 'r'], [15, 3, 'r'], [16, 3, 'r'], [17, 3, 'r'], [18, 3, 'r'], [12, 4, 'r'], [13, 4, 'r'], [14, 4, 'r'], [15, 4, 'r'], [16, 4, 'r'], [17, 4, 'r'], [18, 4, 'r']] },
    /* ящер: зелёный, тёмный гребень, светлое брюхо и челюсть, повязка, лук со стрелами, хвост (40×48) */
    lizardman: {
      hd: true, unit: 2,
      rows: [
        '...........GG...GG...GG.................',
        '..........GGGGGGGGGGGGGG................',
        '.........GGGGGGGGGGGGGGG................',
        '........gggggggggggggggg................',
        '........gggggggggggggggg................',
        '........ggyyygggggggyyyg.........N......',
        '........ggykygggggggykyg......w.Nn......',
        '........ggyyygggggggyyyg......wNn.......',
        '.IIII...gggggggggggggggg......Nn........',
        '.llll...gggggggggggggggg.....Nn.........',
        '.llll....ghhhhhhhhhhhhg......Nn.........',
        '.NNnn.....hhhhhhhhhhhh.......Nn.........',
        '.NNnn.....hhhhhhhhhhhh.......Nn.........',
        '.NNnn.....hGGGGGGGGGGh.......Nn.........',
        '.NNnn......hhhhhhhhhh........Nn.........',
        '.NNnn........gggggg..........Nn.........',
        '.NNnn........gggggg..........Nn.........',
        '.NNnn.gggggggggggggggggggg...Nn.........',
        '.NNnnggggggggggggggggggggggg.Nn.........',
        '.NNnnggggggghhhhhhhhggggggggggn.........',
        '.NNnnggggggghhhhhhhhggggggggggn.........',
        '...gggggggghhhhhhhhhhgggggggggn.........',
        '...gggggggghhhhhhhhhhgggggggggn.........',
        '...gggggggghhhhhhhhhhgggggggggn.........',
        '...gggggggghhhhhhhhhhggggggggggg........',
        '...gggggggghhhhhhhhhhggggggggggg........',
        '...gggggggghhhhhhhhhhggggggggggg........',
        '...gggggggghhhhhhhhhhggggggggggg........',
        '...gggg.ggghhhhhhhhhhggg.....Nn.........',
        '...gggg.ggghhhhhhhhhhggg.....Nn.........',
        '...gggg.ggghhhhhhhhhhggg.....Nn.........',
        '...gggg.ggghhhhhhhhhhggg.....Nn.........',
        '...gggg.ggghhhhhhhhhhggg.....Nn.........',
        '...gggg.gggghhhhhhhhgggg.....Nn.........',
        '....gg..gggggggggggggggg.....Nn.........',
        '........dddddddddddddddd......Nn........',
        '........dddddddddddddddd......wNn.......',
        '........dddddddddddddddd......w.Nn......',
        '........dddddddddddddddd......w..N......',
        '........dddddddddddddddd................',
        '.........gggggg...gggggg................',
        '.........gggggg...gggggg................',
        '.....GGGGgggggg...gggggg................',
        '...GGGGGGgggggg...gggggg................',
        '...GGGGGGgggggg...gggggg................',
        '.GGGGGG..gggggg...gggggg................',
        'GGGGG...GGGGGGG...GGGGGGG...............',
        'GGG.....GGGGGGG...GGGGGGG...............',
      ],
    },
    /* ящер-воин: бирюзовая чешуя, повязка в тёмно-красный, стальные наплечники */
    lizard_warrior: { base: 'lizardman', tint: { g: 'C', G: 'Q', h: 'v', d: 'R' }, extra: [[4, 17, 'l'], [5, 17, 'l'], [6, 17, 'l'], [7, 17, 'l'], [8, 17, 'l'], [9, 17, 'l'], [22, 17, 'l'], [23, 17, 'l'], [24, 17, 'l'], [25, 17, 'l'], [26, 17, 'l'], [27, 17, 'l'], [4, 18, 'l'], [5, 18, 'l'], [6, 18, 'l'], [7, 18, 'l'], [8, 18, 'l'], [9, 18, 'l'], [22, 18, 'l'], [23, 18, 'l'], [24, 18, 'l'], [25, 18, 'l'], [26, 18, 'l'], [27, 18, 'l'], [4, 19, 'l'], [5, 19, 'l'], [6, 19, 'l'], [7, 19, 'l'], [8, 19, 'l'], [9, 19, 'l'], [22, 19, 'l'], [23, 19, 'l'], [24, 19, 'l'], [25, 19, 'l'], [26, 19, 'l'], [27, 19, 'l']] },
    /* змеемуха: змеиное тело с тёмной спиной, четыре голубых крыла с прожилками, большие глаза (композитор) (44×48) */
    serpent_fly: {
      hd: true, unit: 2,
      rows: [
        '............................................',
        '............................................',
        '............................................',
        '............................................',
        '.......................gggggggy.............',
        '......................gyggggyyyyy...........',
        '.....................yyyyyggyyyyy...........',
        '......cccccc.........yyyyyggyykyy...........',
        '.....cCccccccc.......yykyyggyyyyy...........',
        '.....ccCccccccc......yyyyyggghyhhhh.........',
        '......ccCcccccccc....ggyggggghhhhhh....cccCC',
        '......cccCCccccccc...gggggggghhhhhh..ccccCcc',
        '.......ccccCccccccc...ggggggghhhhhhcccccCccc',
        '.......cccccCccccccc...gggggggg..cccccCCcccc',
        '........cccccCCcccccc...gggggg..cccccCccccc.',
        '.........ccccccCcccccc..ggggggccccccCcccccc.',
        '..........ccccccCcccccc.ggggggcccccCcccccc..',
        '...........ccccccCCcccc.ggggggcccCCcccccc...',
        '............cccccccCccccggggggccCccccccc....',
        '.............cccccccCcggggggggcCcccccc......',
        '...............ccccccggggggggggcccccc.......',
        '................cccccghhhhgggggcccc.........',
        '..................ccgghhhhggggggc...........',
        '...................cgghhhhgggggg............',
        '..............ccccccgghhhhggggggCC..........',
        '...........cccccccccgghhhhggggggcccc........',
        '.........cccccccccccgghhhhggggggcccccc......',
        '.......ccccccccccccCgghhhhggggggccccccc.....',
        '.....ccccccccccCCCCccghhhhgggggccccccccc....',
        '....cccccccCCCCccccccggGGggggggCCcccccccc...',
        '...ccccCCCCccccccccCCgGGGggggg.ccCCccccccc..',
        '..cCCCCcccccccccc.C.gGGGGggg....cccCCcccccc.',
        '..cCccccccccccc.CC..GGGGgg........cccCCccccc',
        '..cccccccccc...C...gGGGggg..........cccCCccc',
        '....ccc........C..gGGGGgg..............ccCC.',
        '..................GGGGggg..................C',
        '.................gGGGggg....................',
        '................ggGGgggg....................',
        '...............ggGggggg.....................',
        '..............ggGgggg.......................',
        '.............ggGgggg........................',
        '............ggGgggg.........................',
        '..........gggGgggg..........................',
        '.......gggggGgggg...........................',
        '.....gggggggGggg............................',
        '....ggggggggg...............................',
        '....gggggg..................................',
        '.....ggg....................................',
      ],
    },
    /* стрекоза: крылья в алый, тело оливковое, глаза огненные */
    dragon_fly: { base: 'serpent_fly', tint: { c: 'r', C: 'R', g: 'H', h: 't', y: 'f' } },
    /* василиск: шестиногий оливковый ящер, ржавый гребень, светлое брюхо, красный глаз (композитор) (52×48) */
    basilisk: {
      hd: true, unit: 2,
      rows: [
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '.......HH...........................................',
        '......HHH...........................................',
        '.....HHHH...........................................',
        '....HHHH............................................',
        '...HHHH.............................................',
        '..HHHH..............................................',
        '..HHHH..............................................',
        '..HHHH..............................................',
        '..HHHH..............................................',
        '..HHHH..............................................',
        '..HHHH..............................................',
        '.HHHH........................O..O.OO.OO.............',
        '.HHHH......OO.OOOOOOOOOOOOOOOOOOOOOOOOOO............',
        '.HHHH.....OOOOOOOOOOOOOOOOOOOOOOOOOOOOOHHHHHHHH.....',
        '.HHHH.....OOOOOOOOOOOOOOOOOOOOOOOOOOOHHHHHHrrHHHH...',
        '.HHHHH....OOOOOOOOOOOOOOOOOOOOOOOOOOHHHHHHrrrrHHHH..',
        '.HHHHHH...OOOOOOOOOOOOOOOOOOOOOOOHOOHHHHHHrrkrHHHH..',
        '.HHHHHHHH..OOHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHrrHhhhh..',
        '..HHHHHHHH..HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhhhhhGGG',
        '...HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhhGGGGGG',
        '....HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhhGGGGGG',
        '......HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhhhhhhhh',
        '.......HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhhhh..',
        '........HHHHHHHHHHHHhhhhhhhhhhhhHHHHHHHHHHH.........',
        '.........HHHHHHHhhhhhhhhhhhhhhhhhhhhHHHHHHH.........',
        '..........HHHHhhhhhhhhhhhhhhhhhhhhhhhhHHHH..........',
        '...........HHhhhhhhhhhhhhhhhhhhhhhhhhhhHH...........',
        '............HhhhhhhhhhhhhhhhhhhhhhhhhhhH............',
        '.........GGGGGGhhGGGGGGhhGGGGGGhhGGGGGG.............',
        '.........GGGGHHHHHHGGHHHHHHGGHHHHHHGGGG.............',
        '.........GGGGHHHHHHGGHHHHHHGGHHHHHHGGGG.............',
        '.........GGGGHHHHHHGGHHHHHHGGHHHHHHGGGG.............',
        '.........GGGGHHHHHHGGHHHHHHGGHHHHHHGGGG.............',
        '........GGGGGHHHHHHGGHHHHHHGGHHHHHHGGG..............',
        '........GGGGGHHHHHHGGHHHHHHGGHHHHHHGGG..............',
        '........GGGGGHHHHHHGGHHHHHHGGHHHHHHGGG..............',
        '........GGGGGHHHHHHGGHHHHHHGGHHHHHHGGG..............',
        '........GGGGGHHHHHHGGHHHHHHGGHHHHHHGGG..............',
        '........GGGGii.iiGiiii.iiGiiii.iiGiiGG..............',
        '............ii.ii.iiii.ii.iiii.ii.ii................',
      ],
    },
    /* великий василиск: чешуя в бирюзу, гребень оранжевый, глаз огненный */
    greater_basilisk: { base: 'basilisk', tint: { H: 'q', G: 'Q', h: 'v', j: 'Q', O: 'o', r: 'f' } },
    /* горгона: бронзовый бык в чешуе, горб, костяные рога, тёмные ноги с копытами (композитор) (60×56) */
    gorgon: {
      hd: true, unit: 2,
      rows: [
        '............................................................',
        '............................................................',
        '............................................................',
        '............................................................',
        '............................................................',
        '............................................................',
        '............................................................',
        '............................................................',
        '............................................................',
        '............................................................',
        '............................................................',
        '............................................................',
        '............................................................',
        '.....................................................ii.....',
        '........................................ii...........iii....',
        '........................................iiii.........iiii...',
        '........................................iiiiii......iiiii...',
        '.........................................iiiii......iiiii...',
        '.........................................iiiii......iiiii...',
        '................YYYYYYYY..................iiiii....iiiii....',
        '.............YYYYYYYYYYYYYY...............iiiii....iiiii....',
        '...........YYYYYYYYYYYYYYYYYY.............iiiiii..iiiiii....',
        '..........YYYYYYYYYYYYYYYYYYYYYYY..........iiiii..iiiii.....',
        '.........YYYYYYYYYYYYYYYYYYYYYYYYYYYY......iiiiiYYiiiii.....',
        '.........YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.YYiiiYYYYYYiii.....',
        '.........YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY......',
        '.........YyyYYyyYYyyYYyyYYyyYYyyYYyyYYyYYYYYYYYYrrYYYYY.....',
        '..........yyYYyyYYyyYYyyYYyyYYyyYYyyYYyYYYYYYYYrrrrYYYY.....',
        '.........YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYrrkrYYYYY....',
        '........YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYrrYYYYYY....',
        '.......NYYYYyyYYyyYYyyYYyyYYyyYYyyYYyyYYYYYYYYYYYYYYYYYY....',
        '.......YYYYYyyYYyyYYyyYYyyYYyyYYyyYYyyYYYYYYYYYYYYYYYYYY....',
        '......NYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNNNNNN...',
        '......NYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNNNNNNNN..',
        '.....NNYYYyyYYyyYYyyYYyyYYyyYYyyYYyyYYyyYYYYYYYYYNNNNNNNNNN.',
        '.....NNNYYyyYYyyYYyyYYyyYYyyYYyyYYyyYYyyYYYYYYYYYNNNNNNNNNN.',
        '....NNN.YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNNNNNNNkNN.',
        '....NNN..YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY....NNNNNNNkNN.',
        '...NNN....YYyyYYyyYYyyYYyyYYyyYYyyYYyyYYyyYY......NNNNNNNN..',
        '...NNN.....YyyYYyyYYyyYYyyYYyyYYyyYYyyYYyyY........NNNNNN...',
        '..NNN......NNNNNNNYNNNNNNNYYYYYYYYYNNNNNNN.NNNNNNN..........',
        '..NNN......NNNNNNNYNNNNNNNYYYYYYYYYNNNNNNN.NNNNNNN..........',
        '.NNNN......NNNNNNNYNNNNNNNYYYYYYYYYNNNNNNN.NNNNNNN..........',
        '.NNNN......NNNNNNN.NNNNNNNYYYYYYY..NNNNNNN.NNNNNNN..........',
        '.NNNN......NNNNNNN.NNNNNNN.........NNNNNNN.NNNNNNN..........',
        '.NNNN......NNNNNNN.NNNNNNN.........NNNNNNN.NNNNNNN..........',
        '..NN.......NNNNNNN.NNNNNNN.........NNNNNNN.NNNNNNN..........',
        '...........NNNNNNN.NNNNNNN.........NNNNNNN.NNNNNNN..........',
        '...........NNNNNNN.NNNNNNN.........NNNNNNN.NNNNNNN..........',
        '...........NNNNNNN.NNNNNNN.........NNNNNNN.NNNNNNN..........',
        '...........NNNNNNN.NNNNNNN.........NNNNNNN.NNNNNNN..........',
        '...........NNNNNNN.NNNNNNN.........NNNNNNN.NNNNNNN..........',
        '...........NNNNNNN.NNNNNNN.........NNNNNNN.NNNNNNN..........',
        '..........DDDDDDDDDDDDDDDD........DDDDDDDDDDDDDDDD..........',
        '..........DDDDDDDDDDDDDDDD........DDDDDDDDDDDDDDDD..........',
        '..........DDDDDDDDDDDDDDDD........DDDDDDDDDDDDDDDD..........',
      ],
    },
    /* могучая горгона: чешуя чёрно-бирюзовая, ноги в чёрно-синий, копыта стальные, рога светлые, глаз горит */
    mighty_gorgon: { base: 'gorgon', tint: { Y: 'Q', y: 'q', N: 'z', D: 'e', i: 'l', r: 'h' } },
    /* виверна: двуногий дракон, тёмные перепончатые крылья, хвост с жалом, раскрытая пасть (композитор) (60×60) */
    wyvern: {
      hd: true, unit: 2,
      rows: [
        '............................................................',
        '............................................................',
        '..........NNnNN................................NNnn.........',
        '........NNNNNnNNNNNNN....................NNNNNNNnNNN........',
        '.....NNNNNNNNnNNNNNNNNNNn............nnNNNNNNNNNnNNNNN......',
        '...NNNNNNNNNNNnNNNNNNNNNn............nNNNNNNNNNnNOONNNN.....',
        '..nNNNNNNNNNNNnNNNNNNNNNn............nNNNNONNNNnNOONNNNN....',
        '...nNNNNNNNNNNNnNNNNNNNNnN...........nNNNNOONNnNNOOONNNNNN..',
        '....nNNNNNNNNNNnNNNNNNNNnN...........nNNNNOOONnNNOOONNNNNnn.',
        '.....nNNNNNNNNNNnNNNNNNNnN...........nNNNNOOOnNNNOOONNNNn...',
        '......nNNNNNNNNNnNNNNNNNNnN.........nNNNNNNOOONNNOOOONNn....',
        '.......nNNNNNNNNNnNNNNNNNnN.........nNNNNNNOOOONNOOOONn.....',
        '........nNNNNNNNNNnNNNNNNnN.........nNNNNNNOOOOHHOOHHn......',
        '.........nNNNNNNNNnNNNNNNnNN........nNNNNNNOOHrrHHHHHH......',
        '..........nnNNNNNNNnNNNNNnNN........nNNNNNnHHrrrrHHHHHH.....',
        '............nNNNNNNnNNNNNnNN........nNNNNNHHHrrkrHHHHHHHRR..',
        '.............nNNNNNNnNNNNnNNN.......nNNNNnHHHHrrHHHHHHRRRR..',
        '..............nNNNNNnNNNNNnNN......nNNNNNnHHHHHHHHHRRRRRRR..',
        '...............nNNNNNnNNNNnNN......nNNNNnNHHHHHHHHRRRRRRRR..',
        '................nNNNNnNNNNnNNN.....nNNNNnNNHHHHHHHRRRRRRRR..',
        '.................nNNNNnNNNnNNN.....nNNNnNNNHHHHHHHRRRRRRRR..',
        '..................nNNNNnNNnNNN.....nNNnNNNHHHHHHHHhhhhh.....',
        '...................nnNNnNNnNNN.....nNNnNNHHHHHHHH...hhhhhhh.',
        '....................NnNNnNnNNN.....nNnNNnHHHHHHH.....hhhhh..',
        '......................nNnNNnNN....nNNnNnHHHHHHH........hh...',
        '.......................nNnNnNN....nNnNnHHHHHHHH.............',
        '........................nnNnN.....nNnnHHHHHHHH..............',
        '.........................nnnN.....nnnNHHHHHHH...............',
        '..........................nnN.....nnNHHHHHHH................',
        '...........................nN.....n.HHHHHHHH................',
        'ii........................HHHHHHHHnHHHHHHHH.................',
        'iiii...................HHHHHHHHHHHHHHHHHHH..................',
        'iiiiii...............HHHHHHHHHHHHHHHHHHHH...................',
        'iiiiiii.............HHHHHHHHHHHHHHHHHHHHH...................',
        '.iiiiii............HHHHHHHHHHHHHHHHHHHHHH...................',
        '.iiiiii...........HHHHHHHHHHHHHHHHHHHHHHHH..................',
        '.iiiiii.........HHHHHHHHHHHHHHHHHHHHHHHHHH..................',
        '.iiiiii........HHHHHHHHHhhhhhhhhhhhhHHHHHH..................',
        '..HHHH.......HHHHHHHHHhhhhhhhhhhhhhhhhHHHH..................',
        '...HHHH.....HHHHHHHHHhhhhhhhhhhhhhhhhhhHH...................',
        '...HHHH....HHHHHHHH.HhhhhhhhhhhhhhhhhhhH....................',
        '....HHHH..HHHHHHHH...HhhhhhhhhhhhhhhhhH.....................',
        '....HHHHHHHHHHHH.....GGGGGGhhhhhhhhGGGGGG...................',
        '.....HHHHHHHHHH......GGGGGGHHHHHHH.GGGGGG...................',
        '.....HHHHHHHHH.......GGGGGG........GGGGGG...................',
        '......HHHHHHH........GGGGGG........GGGGGG...................',
        '......HHHHH..........GGGGGG........GGGGGG...................',
        '......HHHH...........GGGGGG........GGGGGG...................',
        '.....................GGGGGG........GGGGGG...................',
        '.....................GGGGGG........GGGGGG...................',
        '....................GGGGGGG.......GGGGGGG...................',
        '....................GGGGGGG.......GGGGGGG...................',
        '....................GGGGGGG.......GGGGGGG...................',
        '....................GGGGGGG.......GGGGGGG...................',
        '....................GGGGGGG.......GGGGGGG...................',
        '....................GGGGGGG.......GGGGGGG...................',
        '..................GGGGGGGGGG....GGGGGGGGGG..................',
        '..................GiiGiiGiiG....GiiGiiGiiG..................',
        '...................iiGiiGii......iiGiiGii...................',
        '...................ii.ii.ii......ii.ii.ii...................',
      ],
    },
    /* монарх виверн: крылья пурпурные со светлыми спицами, тело ярко-зелёное, золотая корона */
    wyvern_monarch: { base: 'wyvern', tint: { N: 'P', n: 'A', H: 'g', h: 'y' }, extra: [[45, 10, 'y'], [46, 10, 'y'], [47, 10, 'y'], [48, 10, 'y'], [49, 10, 'y'], [50, 10, 'y'], [51, 10, 'y'], [52, 10, 'y'], [45, 11, 'y'], [46, 11, 'y'], [47, 11, 'y'], [48, 11, 'y'], [49, 11, 'y'], [50, 11, 'y'], [51, 11, 'y'], [52, 11, 'y'], [45, 9, 'y'], [46, 9, 'y'], [48, 9, 'y'], [49, 9, 'y'], [51, 9, 'y'], [52, 9, 'y']] },
    /* гидра: бурое тело, пять голов на длинных шеях веером, светлое брюхо, тёмные лапы (композитор) (64×60) */
    hydra: {
      hd: true, unit: 2,
      rows: [
        '.............................dddddd.............................',
        '...........................dddyyddddd...........................',
        '...........................ddyyyydddd...........................',
        '...........................ddyykydddd...........................',
        '...............dddddd......dddyyTTTTTT.....dddddd...............',
        '.............dddddyyddd....ddddTTTTTTTT..dddyyddddd.............',
        '.............ddddyyyydd....ddddTTNNNNNN..ddyyyydddd.............',
        '.............ddddyykydd......dddTTTTTT...ddyykydddd.............',
        '............TTTTTTyyddd......dddddd......dddyyTTTTTT............',
        '...........TTTTTTTTdddd......dddddd......ddddTTTTTTTT...........',
        '...........TNNNNNNTdddd......dddddd......ddddTTNNNNNN...........',
        '............TTTTTTddd........dddddd........dddTTTTTT............',
        '...dddddd......TTTTTT........dddddd........TTTTTT......dddddd...',
        '.dddddyyddd....TTTTTTT.......dddddd.......TTTTTTT....dddyyddddd.',
        '.ddddyyyydd.....TTTTTT.......dddddd.......TTTTTT.....ddyyyydddd.',
        '.ddddyykydd.....TTTTTT.......dddddd.......TTTTTT.....ddyykydddd.',
        'TTTTTTyyddd.....TTTTTTT......dddddd......TTTTTTT.....dddyyTTTTTT',
        'TTTTTTTdddd......TTTTTT......dddddd......TTTTTT......ddddTTTTTTT',
        'NNNNNNTdddd......TTTTTT......dddddd......TTTTTT......ddddTTNNNNN',
        'TTTTTTdddd........TTTTTT.....dddddd.....TTTTTT........ddddTTTTTT',
        '...ddddddd........TTTTTT.....dddddd.....TTTTTT........ddddddd...',
        '...dddddddd.......TTTTTTT....dddddd....TTTTTTT.......dddddddd...',
        '....dddddddd.......TTTTTT....dddddd....TTTTTT.......dddddddd....',
        '.....dddddddd......TTTTTT....dddddd....TTTTTT......dddddddd.....',
        '......dddddddd.....TTTTTTT...dddddd...TTTTTTT.....dddddddd......',
        '.......dddddddd.....TTTTTT...dddddd...TTTTTT.....dddddddd.......',
        '........dddddddd....TTTTTT...dddddd...TTTTTT....dddddddd........',
        '.........dddddddd...TTTTTTT..dddddd..TTTTTTT...dddddddd.........',
        '..........dddddddd...TTTTTT..dddddd..TTTTTT...dddddddd..........',
        '...........dddddddd..TTTTTT..dddddd..TTTTTT..dddddddd...........',
        '...........dddddddd..TTTTTTT.dddddd.TTTTTTT..dddddddd...........',
        '............dddddddd..TTTTTT.dddddd.TTTTTT..dddddddd............',
        '.............dddddddd.TTTTTT.dddddd.TTTTTT.dddddddd.............',
        '..............dddddddd.TTTTTTddddddTTTTTT.dddddddd..............',
        '...............ddddddddTTTTTTddddddTTTTTTdddddddd...............',
        '................dddddddTTTTTTdddddTTTTTTdddddddd................',
        '.................dddddddTTTTTdddddTTTTTdddddddd.................',
        '..................ddddddTddddddddddddddddddddd..................',
        '...................dddddddddddddddddddddddddd...................',
        '.................dddddddddddddddddddddddddddddd.................',
        '...............dddddddddddddddddddddddddddddddddd...............',
        '..............dddddddddddddddddddddddddddddddddddd..............',
        '.............dddddddddddddddddddddddddddddddddddddd.............',
        '............dddddddddddddddddddddddddddddddddddddddd............',
        '...........ddddddddddddddTTTTTTTTTTTTTTddddddddddddd............',
        '.........dddddddddddTTTTTTTTTTTTTTTTTTTTTTTTdddddddd............',
        '.......dddddddddddTTTTTTTTTTTTTTTTTTTTTTTTTTTTdddddd............',
        '......dddddddddddTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTdddd.............',
        '....dddddddd..dddTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTddd..............',
        '..dddddddd.....dddTTTTTTTTTTTTTTTTTTTTTTTTTTTTddd...............',
        '.ddddddd.....DDDDDDdTTTDDDDDDTTTTTTDDDDDDTTTdDDDDDD.............',
        'ddddddd......DDDDDD.dddDDDDDDTTTTTTDDDDDDddd.DDDDDD.............',
        'ddddd........DDDDDD....DDDDDDddddddDDDDDD....DDDDDD.............',
        '.dd..........DDDDDD....DDDDDD......DDDDDD....DDDDDD.............',
        '............DDDDDDD...DDDDDDD.....DDDDDDD...DDDDDDD.............',
        '............DDDDDDD...DDDDDDD.....DDDDDDD...DDDDDDD.............',
        '............DDDDDDD...DDDDDDD.....DDDDDDD...DDDDDDD.............',
        '..........DDDDDDDDDDDDDDDDDDDD..DDDDDDDDDDDDDDDDDDDD............',
        '..........DiiDiiDiiDDiiDiiDiiD..DiiDiiDiiDDiiDiiDiiD............',
        '...........iiDiiDii..iiDiiDii....iiDiiDii..iiDiiDii.............',
      ],
    },
    /* гидра хаоса: синяя чешуя, светло-синие шеи и брюхо, чёрные лапы, красные глаза */
    chaos_hydra: { base: 'hydra', tint: { d: 'B', T: 'b', D: 'z', N: 'R', y: 'r' } },
  });
})();
