/* ============================================================================
   view/sprites_conflux_hd.js — существа Сопряжения в крупной сетке (unit 2), стиль Б:
   без контурной линии, тона кладёт рисунок. Собирается скриптом dev/proto/conflux_hd.py.
   ========================================================================== */
(function () {
  'use strict';
  H3.Sprites.defineMany({
    /* пикси: маленькая фея, рыжие волосы, зелёное платье, крылья стрекозы (40×46) */
    pixie: {
      hd: true, unit: 2,
      rows: [
        '................oooooo..................',
        '.AAAA.........oooooooooo..........AAAA..',
        '.AaAAA.......oooooooooooo........AAAaa..',
        '.AAaAAA......oooossssssoo.......AAAaAA..',
        '.AAAaAAAA....ooossssssssoo....AAAAaAAA..',
        '..AAAaAAAA...oosssswwsswws...AAAAaAAA...',
        '..AAAAaAAA...oosssskwsskws...AAAaAAAA...',
        '...AAAAaAAA...ossssssssss...AAAAaAAA....',
        '....AAAaAAAA..osssssssMMs..AAAAaAAA.....',
        '....AAAAaAAA...sssssssssss.AAAaAAAA.....',
        '.....AAAAaAAA...ssssssss..AAAaAAAA......',
        '.......AAAaAA....sssss....AAaAAA........',
        '........AAAaA..GGGgggGGG..AaAAA.........',
        '.........AAAa.GGgggggggGG.AaAA..........',
        '.............GGGgggggggGGG..............',
        '.............GGGgggggggGGG..............',
        '..........AAAGG.GgggggG.GGAAA...........',
        '........AAAaaGG.GgggggG.GGAaAAA.........',
        '.......AAAaAAGG.GgggggG.GGAAaAAA........',
        '......AAAaAAAGG.GGgggGG.GGAAAaAAA.......',
        '.....AAAaAAA.GG.GggggggG.GGAAAaAAA......',
        '....AAAAaAAA.GG.GggggggG.GGAAAaAAAA.....',
        '...AAAAaAAA...ssGgggggggGss.AAAaAAAA....',
        '..AAAAaAAAA...ssGgggggggGss.AAAAaAAAA...',
        '..AAAaAAAA....ssGgggggggGss..AAAAaAAA...',
        '.AAAaAAAA......GgggggggggG....AAAAaAAA..',
        '.AAAaAAA.......GgggggggggG.....AAAaAAA..',
        'AAAaAAA........GgggggggggG......AAAaAAA.',
        'AAaAAA........GgggggggggggG......AAAaAA.',
        'AaAAA.........GgggggggggggG.......AAAaA.',
        'AaA...........GgggggggggggG.........AAa.',
        '.............GgggggggggggggG............',
        '.............GgggggggggggggG............',
        '.............GgggggggggggggG............',
        '............GgggggggggggggggG...........',
        '............GgggggggggggggggG...........',
        '............GGGGGGGGGGGGGGGGG...........',
        '..............sss......sss..............',
        '..............sss......sss..............',
        '..............sss......sss..............',
        '..............sss......sss..............',
        '..............sss......sss..............',
        '..............sss......sss..............',
        '..............sss......sss..............',
        '.............GGGG.....GGGGG.............',
        '.............GGGG.....GGGGG.............',
      ],
    },
    /* спрайт: крылья в белую магию, платье синее, волосы сиреневые, искры */
    sprite: { base: 'pixie', tint: { A: 'L', a: 'e', g: 'b', G: 'B', o: 'a' }, extra: [[4, 38, 'w'], [3, 38, 'w'], [5, 38, 'w'], [4, 37, 'w'], [4, 39, 'w'], [36, 38, 'w'], [35, 38, 'w'], [37, 38, 'w'], [36, 37, 'w'], [36, 39, 'w'], [2, 14, 'w'], [1, 14, 'w'], [3, 14, 'w'], [2, 13, 'w'], [2, 15, 'w'], [38, 14, 'w'], [37, 14, 'w'], [39, 14, 'w'], [38, 13, 'w'], [38, 15, 'w']] },
    /* воздушный элементаль: вихрь, серо-голубые формы, руки вверх, книзу воронка (композитор) (44×48) */
    air_elemental: {
      hd: true, unit: 2,
      rows: [
        '...................llllll...................',
        '..................llllllll..................',
        '................llllllllllll................',
        '...............llllllllllllll...............',
        '..............llllllllllllllll..............',
        '.eeeeee......llllllllllllllllll......eeeeee.',
        'eeeeeeee.....llllllllllllllllll.....eeeeeeee',
        'eeeeeeeel....llllllllllllllllll....leeeeeeee',
        'eeeeeeeell...llllllllllllllllll...lleeeeeeee',
        'eeeeeeeelll...llllBBBlllBBBlll...llleeeeeeee',
        '.eeeeeelllll...lllBBBlllBBBll...llllleeeeee.',
        '...llllllllll..lllBBBlllBBBll..llllllllll...',
        '....lllllllll..llllllllllllll..lllllllll....',
        '....llllllllll..llllllllllll..llllllllll....',
        '.....llllllllll.llllllllllll.llllllllll.....',
        '......llllllllll.llllllllll.llllllllll......',
        '.......llllllllll..llllll..llllllllll.......',
        '........lllllllllleeeeeeeellllllllll........',
        '.........llllllllleeeeeeeelllllllll.........',
        '.........llllllleeelllllleeelllllll.........',
        '..........lllllellllllllllllelllll..........',
        '...........lleelllleeeeeelllleell...........',
        '...........eeellleeecccceeellleee...........',
        '...........eeelleeecccccceeelleee...........',
        '...........eeelleeecccccceeelleee...........',
        '...........eeellleeecccceeellleee...........',
        '............eeelllleeeeeelllleee............',
        '............eeeelllllllllllleeeelll.........',
        '.............leeeeelllllleeeeelllll.........',
        '..............leeeeeeeeeeeeeellllll.........',
        '.............eeeeeeeeeeeeellllleee..........',
        '............eecccceeeeeeeeeeeeee............',
        '...........leeeeeeeeeeeeeeeeee..............',
        '...........llllleeeeeeeeeell................',
        '...........lllllllllllllllll................',
        '.............llllllllllllllle...............',
        '...............lllllllllleeeee..............',
        '.................eeeeeeeeeeeeee.............',
        '..................eeeeeeeeeeeee.............',
        '.................lllleeeeeeell..............',
        '................llllllllllll................',
        '...............ellllllllll..................',
        '...............eeellllll....................',
        '................eeeeeeee....................',
        '.................eeeeeeel...................',
        '...................eeellll..................',
        '.....................lllll..................',
        '......................llll..................',
      ],
    },
    /* штормовой элементаль: вихрь синеет, в руке молния */
    storm_elemental: { base: 'air_elemental', tint: { l: 'c', e: 'C', c: 'l' }, extra: [[42, 0, 'y'], [43, 0, 'y'], [41, 1, 'y'], [42, 1, 'y'], [40, 2, 'y'], [41, 2, 'y'], [41, 3, 'y'], [42, 3, 'y'], [42, 4, 'y'], [43, 4, 'y'], [41, 5, 'y'], [42, 5, 'y'], [40, 6, 'y'], [41, 6, 'y'], [1, 0, 'y'], [2, 0, 'y'], [2, 1, 'y'], [3, 1, 'y'], [3, 2, 'y'], [4, 2, 'y'], [2, 3, 'y'], [3, 3, 'y'], [1, 4, 'y'], [2, 4, 'y'], [2, 5, 'y'], [3, 5, 'y'], [3, 6, 'y'], [4, 6, 'y']] },
    /* водяной элементаль: фигура-волна, тёмное тело, голубая голова и руки, гребень с пеной (композитор) (48×52) */
    water_elemental: {
      hd: true, unit: 2,
      rows: [
        '................................................',
        '................................................',
        '................................................',
        '................................................',
        '................................................',
        '........................cccc....................',
        '......................cccccccc..............wwww',
        '.....................cccccccccc.............wwww',
        '...wwww.............cccccccccccc...........cwwww',
        '...wwwwc............cccccccccccc..........ccwwww',
        '..cwwwwccc..........cccccccccccc..........cccccc',
        '..cwwwwccc..........ccBBBcccBBBc..........cccccc',
        '..cccccccc..........ccBBBcccBBBc..........cccccc',
        '..cccccccc..........ccBBBcccBBBc..........ccccc.',
        '..cccccccc..........cccccccccccc.........ccccc..',
        '..cccccccc..........cccccccccccc........ccccccc.',
        '....ccccccc..........cccccccccc........cccccccc.',
        '....cccccccc..........cccccccc........cccccccc..',
        '....ccccccccc......BBBBBccccBBBBB.....ccccccc...',
        '.....cccccccccc....BBBBBBBBBBBBBB....ccccccc....',
        '......cccccccccc...BBBBBBBBBBBBBB...cccccccc....',
        '.......cccccccccc..BBBBBBBBBBBBBB..cccccccc.....',
        '........cccccccccc.BBBBBBbbBBBBBB.cccccccc......',
        '.........ccccccccccBBBBBbbbbBBBBBcccccccc.......',
        '........wwwccccccccBBBBBbbbbBBBBBccccccc........',
        '..wwwwwwwwwwcccccccBBBBbbbbbbBBBBcccccc.........',
        '..wwwwwwwwww.ccccccBBBBbbbbbbBBBBccccc..........',
        '..wwwwwwwwwwc.cccc.BBBBbbbbbbBBBB.cccc..........',
        '..wwwwwwcccccc.ccc.BBBBbbbbbbBBBB.ccc...........',
        '.cccccccccccccc.ccBBBBBbbbbbbBBBBBcc............',
        '.cccccccccccccc...BBBBBbbbbbbBBBBB..............',
        'cccccccccccccccc..BBBBBBbbbbBBBBBB..............',
        'ccccccbbbbbbcccc..BBBBBBbbbbBBBBBB..............',
        'cccccbbbbbbbbccc..BBBBBBBbbBBBBBBB..............',
        'cccccbbbbbbbbccc..BBBBBBBBBBBBBBBB...bbbb.......',
        '.ccccbbbbbbbbcc...BBBBBBBBBBBBBBBBbbbbbbbb......',
        '.ccccbbbbbbbbccbb.BBBBBBBBBBBBBBBBbbbbbbbbbb....',
        '..ccccbbbbbbccbbbbBBBBBBBBBBBBBBBBbbbbbbbbbbb...',
        '...ccccccccccbbbbbBBBBBBBBBBBBBBBBbbbbbbbbbbbb..',
        '....bccccccbbbbbbbBBBBBBBBBBBBBBBBbbbbbbbbbbbbbb',
        '..bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
        'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
        'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
        'bbbbbbcccccccccccbbbbbbbbbbbbbbbbbbbcccccccccccb',
        'bbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbb',
        'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
        'bbbbbbbbbbbbBBBBBBBBBBBBBBBBBBBBBBBBbbbbbbbbbbbb',
        'bbbbbBBBBBBBcccccccccBBBBBBBBBBBBBBBBBBBBBBbbbbb',
        'bbBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbb',
        'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..',
      ],
    },
    /* ледяной элементаль: вода становится льдом, голова и руки белеют, сосульки */
    ice_elemental: { base: 'water_elemental', tint: { b: 'C', c: 'L', w: 'b' }, extra: [[6, 20, 'b'], [6, 21, 'b'], [6, 22, 'b'], [6, 23, 'b'], [7, 20, 'b'], [7, 21, 'b'], [7, 22, 'b'], [42, 22, 'b'], [42, 23, 'b'], [42, 24, 'b'], [42, 25, 'b'], [43, 22, 'b'], [43, 23, 'b'], [43, 24, 'b']] },
    /* огненный элементаль: фигура из пламени, языки вверх, лицо светлее, угли внизу (композитор) (48×54) */
    fire_elemental: {
      hd: true, unit: 2,
      rows: [
        '................F.......FF......................',
        '................FF......FF....F.................',
        '................FFF....FFF...FF.................',
        '........ff.......FFF...FFFF..FF.......ff........',
        '........ff.......FFFF.FFFFF.FF........ff........',
        '........ff........FFFFFFFFFFFF........ff........',
        '.f.....fff........FFFFFFFFFFFF........fff.....f.',
        '.ff....fff........FFFFFFFFFFFF........fff....ff.',
        '.fff...fff.........FFFFFFFFFF.........fff...fff.',
        '.fffffffff........FFFffffffFFF........fffffffff.',
        '.fffffffff........FFffffffffFF........fffffffff.',
        '..ffffffff........FFffffffffFF........ffffffff..',
        '..ffffffff........FFzzzfffzzzF........ffffffff..',
        '..ffffffF.........FFzzzfffzzzF.........Fffffff..',
        '..fffFFFFF........FFzzzfffzzzF........FFFFFfff..',
        '..ffFFFFFFF........FffffffffF........FFFFFFFff..',
        '..FFFFFFFFFF.......FFffffffFF.......FFFFFFFFFF..',
        '...FFFFFFFFFF........FFFFFFF.......FFFFFFFFFF...',
        '...FFFFFFFFFF........FFFFFFF.......FFFFFFFFFF...',
        '....FFFFFFFFFF.FF....FFFFFFF...FF.FFFFFFFFFF....',
        '.....FFFFFFFFFFFFF.ffFFFFFF...FFFFFFFFFFFFF.....',
        '.....FFFFFFFFFFFFFFffFFFFFFFffFFFFFFFFFFFFF.....',
        '.....FFFFFFFFFFFFFFffFFFFFFFffFFFFFFFFFFFFF.....',
        '......FFFFFFFFFFFFFffFFFFFFFffFFFFFFFFFFFF......',
        '......FFFFFFFFFFFFFffFFFFFFFffFFFFFFFFFFFF......',
        '......FFFFFFFFFFFFFfffFFFFFfffFFFFFFFFFFFF......',
        '.......FFFFFFFFFFFFfffFFFFFfffFFFFFFFFFFF.......',
        '.......FFFFFFFFFFFFfffFffFFfffFFFFFFFFFFF.......',
        '.......FFFFFFFFFFFffffffffFfffFFFFFFFFFFF.......',
        '.......FFFFFFFFFFFfffffffffffffFFFFFFFFFF.......',
        '........FFFFFFFFFFfffffffffffffFFFFFFFFF........',
        '........FFFFFFFFFFfffffffffffffFFFFFFFFF........',
        '........FFFFFFFFFFfffffffffffffFFFFFFFFF........',
        '.........FFFFFFFFFfffffffffffffFFFFFFFF.........',
        '.........FFFFFFFFffffffffffffffFFFFFFFF.........',
        '.........FFFFFFFFffffffffffffffFFFFFFFF.........',
        '........FFFFFFFFffffffffffffffffFFFFFFFF........',
        '........FFFFFFFFffffffffffffffffFFFFFFFF........',
        '........FFFFFFFFffffffffffffffffFFFFFFFF........',
        '........FFFFFFFFffffffffffffffffFFFFFFFF........',
        '.........FFFFFFFffffffffffffffffFFFFFFF.........',
        '..........FFFFFFffffffffffffffffFFFFFF..........',
        '..........FFFFFFffffffffffffffffFFFFFF..........',
        '...........FFFFFffffffffffffffffFFFFF...........',
        '...........FFFFFffffffffffffffffFFFFF...........',
        '...........FFFFFffffffffffffffffFFFFF...........',
        '...........FFFFFFFFFFFFFFFFFFFFFFFFFF...........',
        '...............RRRRRRRRRRRRRRRRRR...............',
        '..........RRRRRRRRRRRRRRRRRRRRRRRRRRRR..........',
        '........RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR........',
        '.......RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.......',
        '........RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR........',
        '..........RRRRRRRRRRRRRRRRRRRRRRRRRRRR..........',
        '...............RRRRRRRRRRRRRRRRRR...............',
      ],
    },
    /* энергетический элементаль: пламя выцветает в белый жар, глаза синие, искры */
    energy_elemental: { base: 'fire_elemental', tint: { F: 'y', f: 'w', R: 'F', z: 'b' }, extra: [[13, 4, 'c'], [12, 4, 'c'], [14, 4, 'c'], [13, 3, 'c'], [13, 5, 'c'], [35, 4, 'c'], [34, 4, 'c'], [36, 4, 'c'], [35, 3, 'c'], [35, 5, 'c'], [2, 2, 'c'], [1, 2, 'c'], [3, 2, 'c'], [2, 1, 'c'], [2, 3, 'c'], [46, 2, 'c'], [45, 2, 'c'], [47, 2, 'c'], [46, 1, 'c'], [46, 3, 'c']] },
    /* земляной элементаль: каменный великан, трещины, глыба в поднятой руке, светящиеся глаза (композитор) (56×58) */
    earth_elemental: {
      hd: true, unit: 2,
      rows: [
        '........................................................',
        '.............................................TTTTTT.....',
        '...........................................TTTTTTTTTT...',
        '..........................................TTTTTTTTTTTT..',
        '.........................................TTTTTTTTTTTTTT.',
        '.........................................TTTTTTTTTTTTTT.',
        '..........................TTTTTTTT.......TTTTTTTTTTTTTT.',
        '........................TTTTTTTTTTTT.....TTTTTTTTTTTTTT.',
        '.......................TTTTTTTTTTTTTT....TTTTTTTTTTTTTT.',
        '......................TTTTTTTTTTTTTTTT...TTTTTTTTTTTTTT.',
        '......................TTTTTTTTTTTTTTTT....TTTTTTTTTTTT..',
        '.....................TTTTTTTTTTTTTTTTTT....TTTTTTTTTT...',
        '.....................TTTTyyyTTTTTyyyTTT.....NTTTTTT.....',
        '.....................TTTTyyyTTTTTyyyTTT....NNNNNNNNN....',
        '.....................TTTTyyyTTTTTyyyTTT....NNNNNNNNN....',
        '......................TTTTTTTTTTTTTTTT....NNNNNNNNNN....',
        '......................TTTTTTTTTTTTTTTT...NNNNNNNNNN.....',
        '.......................TTTTTTTTTTTTTT....NNNNNNNNNN.....',
        '.....................nnnTTTTTTTTTTTT.....NNNNNNNNN......',
        '...................nnnnnnnTTTTTTTTnnn...NNNNNNNNNN......',
        '.................nnnnnnnnnnnnnnnnnnnnnn.NNNNNNNNN.......',
        '................nnnnnnnnnnnnnnnnnnnnnnnnNNNNNNNNN.......',
        '.............NNnnnnnnnnnnnnnnnnnnnDnnnnnNNNNNNNN........',
        '.............NNnnnnnnnnnnnnnnnnnnnDnnnnnnnNNNNNN........',
        '............NNNNnnDnnnnnnnnnnnnnnnDnnnnnnn.NNNN.........',
        '...........NNNNNNnnDnnnnnnnnnnnnnnDnnnnnnnn..NN.........',
        '...........NNNNNNnnDnnnnnnnnnnnnnnDnnnnnnnn.............',
        '..........NNNNNNNNnnDnnnnnnnnnnnnnnDnnnnnnnn............',
        '.........NNNNNNNNNnnDnnnnnnnnnnnnnnDnnnnnnnn............',
        '.........NNNNNNNNNnnnDnnnnnnnnnnnnnDnnnnnnnn............',
        '........NNNNNNNNNnnnnDnnnnnnnnnnnnnDnnnnnnnn............',
        '.......NNNNNNNNNNnnnnnDnnnnnnnnnnnnDnnnnnnnn............',
        '.......NNNNNNNNNnnnnnnDnnnnnnnnnnnnDDnnnnnnn............',
        '......NNNNNNNNNNnnnnnnnDnnnnnnnnnnDnnnnnnnn.............',
        '.....NNNNNNNNNNnnnnnnnnDDnnnnnnnnnDnnnnnnnn.............',
        '.....NNNNNNNNNNnnnnnnnnDnnnnnnnnnDnnnnnnnn..............',
        '.....NNNNNNNNNnnnnnnnnnDnnnnnnnnnDnnnnnnnn..............',
        '.....NNNNNNNNN.nnnnnnnDnnnnnnnnnDnnnnnnnn...............',
        '.....NNNNNNNNN..nnnnnnDnnnnnnnnnDnnnnnnn................',
        '.....NNNNNNNNN...nnnnnDnnnnnnnnnnnnnnnn.................',
        '....NNNNNNNNNNNNNNnnnnDnnnnnnnnnnnnnnnNNNNN.............',
        '....NNNNNNNNNNNNNNnnnnnnnnnnnnnnnnnnnnNNNNN.............',
        '....NNnnnnNNNNNNNNNnnnnnnnnnnnnnnnnnnNNNNNN.............',
        '....nnnnnnnnNNNNNNNNNnnnnnnnnnnnnnnNNNNNNNN.............',
        '...nnnnnnnnnnNNNNNNNNNNNnnnnnnnnNNNNNNNNNNN.............',
        '...nnnnnnnnnnNNNNNNNNNNNN......NNNNNNNNNNNN.............',
        '...nnnnnnnnnnNNNNNNNNNNNN......NNNNNNNNNNNN.............',
        '...nnnnnnnnnnNNNNNNNNNNNN......NNNNNNNNNNNN.............',
        '....nnnnnnnn.NNNNNNNNNNNN......NNNNNNNNNNNN.............',
        '......nnnn...NNNNNNNNNNNN......NNNNNNNNNNNN.............',
        '.............NNNNNNNNNNNN......NNNNNNNNNNNN.............',
        '.............NNNNNNNNNNNN......NNNNNNNNNNNN.............',
        '.............NNNNNNNNNNNN......NNNNNNNNNNNN.............',
        '.............NNnnnnnnnnNN......NNnnnnnnnnNN.............',
        '.............nnnnnnnnnnnn......nnnnnnnnnnnn.............',
        '............nnnnnnnnnnnnnn....nnnnnnnnnnnnnn............',
        '.............nnnnnnnnnnnn......nnnnnnnnnnnn.............',
        '...............nnnnnnnn..........nnnnnnnn...............',
      ],
    },
    /* магмовый элементаль: камень чернеет, в трещинах лава, глаза огненные */
    magma_elemental: { base: 'earth_elemental', tint: { n: 'E', N: 'z', T: 'e', D: 'F', y: 'f' }, extra: [[16, 44, 'F'], [17, 45, 'F'], [18, 46, 'F'], [17, 47, 'F'], [16, 48, 'F'], [37, 44, 'F'], [38, 45, 'F'], [39, 46, 'F'], [38, 47, 'F'], [37, 48, 'F']] },
    /* псионический элементаль: сиреневая фигура с ореолом, сферы в руках, хвост-дымка (композитор) (56×60) */
    psychic_elemental: {
      hd: true, unit: 2,
      rows: [
        '........................................................',
        '.........................pppppp.........................',
        '......................pppppppppppp......................',
        '.....................pppppppppppppp.....................',
        '....................ppppp......ppppp....................',
        '...................pppp..........pppp...................',
        '..................pppp...AAAAAA...pppp..................',
        '.................pppp...AAAAAAAA...pppp.................',
        '.................ppp...AAAAAAAAAA...ppp.................',
        '.................ppp..AAAAAAAAAAAA..ppp.................',
        '...AAAAAA.......ppp...AAAAAAAAAAAA...ppp.......AAAAAA...',
        '..AAAAAAAA......ppp...AAAAAAAAAAAA...ppp......AAAAAAAA..',
        '..AAAAAAAA......ppp...AAxxxAAAxxxA...ppp......AAAAAAAA..',
        '..AAAwwwAA......ppp...AAxxxAAAxxxA...ppp......AAAwwwAA..',
        '..AAAwwwAA......ppp...AAxxxAAAxxxA...ppp......AAAwwwAA..',
        '..AAAwwwAAPP....ppp...AAAAAAAAAAAA...ppp....PPAAAwwwAA..',
        '..AAAAAAAAPPP....ppp..AAAAAAAAAAAA..ppp....PPPAAAAAAAA..',
        '...AAAAAAPPPPP...ppp...AAAAAAAAAA...ppp...PPPPPAAAAAA...',
        '....PPPPPPPPPPPP.pppp...AAAAAAAA...pppp.PPPPPPPPPPPP....',
        '......PPPPPPPPPPP.pppp...AAAAAA...pppp.PPPPPPPPPPP......',
        '.......PPPPPPPPPPP.pppp..........pppp.PPPPPPPPPPP.......',
        '.........PPPPPPPPPPPppppp......pppppPPPPPPPPPPP.........',
        '..........PPPPPPPPPPPppppppppppppppPPPPPPPPPPP..........',
        '...........PPPPPPPPPP.pppppppppppp.PPPPPPPPPP...........',
        '.............PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.............',
        '..............PPPPPPPPPPPPPPPPPPPPPPPPPPPP..............',
        '................PPPPPPPPPPPPPPPPPPPPPPPP................',
        '................PPPPPPPPPPppppPPPPPPPPPP................',
        '................PPPPPPPPPppppppPPPPPPPPP................',
        '................PPPPPPPPppppppppPPPPPPPP................',
        '................PPPPPPPPppppppppPPPPPPPP................',
        '.................PPPPPPPpppAAAppPPPPPPP.................',
        '.................PPPPPPPpppAAAppPPPPPPP.................',
        '.................PPPPPPPpppAAAppPPPPPPP.................',
        '.................PPPPPPPpppAAAppPPPPPPP.................',
        '.................PPPPPPPppppppppPPPPPPP.................',
        '.................PPPPPPPppppppppPPPPPPP.................',
        '..................PPPPPPPppppppPPPPPPP..................',
        '..................PPPPPPPPppppPPPPPPPP..................',
        '..................PPPPPPPPPPPPPPPPPPPP..................',
        '..................PPPPPPPPPPPPPPPPPPPP..................',
        '..................PPPPPPPPPPPPPPPPPPPP..................',
        '..................PPPPPPPPPPPPPPPPPPPP..................',
        '..................PPPPPPPPPPPPPPPPPPPP..................',
        '...................PPPPPPPPPPPPPPPPPP...................',
        '...................PPPPPPPPPPPPPPPPPP...................',
        '....................PPPPPPPPPPPPPPPP....................',
        '.....................PPPPPPPPPPPPPP.....................',
        '.....................PPPPPPPPPPPPPP.....................',
        '......................PPPPPPPPPPPP......................',
        '.......................PPPPPPPPPP.......................',
        '.......................PPPPPPPPPP.......................',
        '........................PPPPPPPP........................',
        '........................PPPPPPPP........................',
        '........................PPPPPPPP........................',
        '.........................PPPPPP.........................',
        '.........................PPPPPP.........................',
        '.........................PPPPPP.........................',
        '.........................PPPPPP.........................',
        '........................................................',
      ],
    },
    /* магический элементаль: тело светлеет, голова и сферы белеют, золотые искры */
    magic_elemental: { base: 'psychic_elemental', tint: { P: 'a', p: 'A', A: 'w', x: 'B' }, extra: [[6, 6, 'y'], [5, 6, 'y'], [7, 6, 'y'], [6, 5, 'y'], [6, 7, 'y'], [50, 6, 'y'], [49, 6, 'y'], [51, 6, 'y'], [50, 5, 'y'], [50, 7, 'y'], [15, 3, 'y'], [14, 3, 'y'], [16, 3, 'y'], [15, 2, 'y'], [15, 4, 'y'], [41, 3, 'y'], [40, 3, 'y'], [42, 3, 'y'], [41, 2, 'y'], [41, 4, 'y']] },
    /* жар-птица: птица в пламени, крылья вверх, гребень, длинный хвост до земли (композитор) (64×60) */
    firebird: {
      hd: true, unit: 2,
      rows: [
        '.........rrrrr....................................rrrrr.........',
        '....rrrrrrrrrrrr................................rrrrrrrrrrrr....',
        '..rrrrrrrrfrrrrrrr..............ff.ffffff.fff.rrrrrrrffrrrrrrr..',
        '..ffrrrrrrrfrrrrrrfrr..........ffffffffffffffrrrrrrrfrrrrrrrff..',
        '.ffffrrrrrrrfrrrrrrfrrr........ffffffffffffffrrrrrrfrrrrrrrffff.',
        '.ffffffrrrrrrfrrrrrfrrrrr......ffffffffffffffrrrrrfrrrrrrrfffff.',
        '.fffffffrrrrrrfrrrrrfrrrrrr....ffffffffffffffrrrrfrrrrrrrffffff.',
        '..fffffffrrrrrrfrrrrfrrrrrr.....ffFffffffFffrrrrfrrrrrrfffffff..',
        '...fffffffrrrrrrfrrrrfrrrrr......FFFFFFFFFFrrrrfrrrrrrfffffff...',
        '....fffffffrrrrrrfrrrrfrrrr.....FFFFFFFFFFFFrrrrrrrrrfffffff....',
        '......fffffffrrrrfrrrrfrrrrr....FFFFFFFFFFFFrrrrrrrrrffffff.....',
        '.......fffffffrrrrfrrrrfrrrr...FFFFFFFFFFFFFFrrrrrrrrfffff......',
        '........fffffffrrrrfrrrfrrrr...FFFFFFwwFFFFyyrrrrrrrrffff.......',
        '..........fffffffrrrfrrrfrrrr..FFFFFFwkFFFFyyyyrrr.rrff.........',
        '...........fffffffrrrfrrrfrrr..FFFFFFFFFFFFyyyyyy...rf..........',
        '............fffffffrrrfrrfrrr...FFFFFFFFFFFyyyyyy...............',
        '..............fffffffrrfrrfrr...FFFFFFFFFFFyyrr.................',
        '..............ffffffffrrfrfrrr...FFFFFFFFFFrrr..................',
        '................fffffffrfrrfrr..FFFFFFFFFFrrr...................',
        '.................fffffffffrfrr..FFFFFFFffrrr....................',
        '..................fffffffffrfr.FFFFFFFfrrrr.....................',
        '....................ffffffffrffFFFFFFFrrr.......................',
        '.....................fffffffffFFFFFFFrrr........................',
        '......................ffffffffFFFFFFFrr.........................',
        '........................ffffffFFFFFFff..........................',
        '.........................fffffFFFFFFfff.........................',
        '.........................ffffffFFFFffff.........................',
        '........................ffffffffffffffff........................',
        '........................ffffffffffffffff........................',
        '........................ffffffffffffffff........................',
        '........................ffffffFFFFffffff........................',
        '........................fffffFFFFFFfffff........................',
        '........................fffffFFFFFFfffff........................',
        '........................ffffFFFFFFFFffff........................',
        '........................ffffFFFFFFFFffff........................',
        '........................ffffFFFFFFFFffff........................',
        '........................ffffFFFFFFFFffff........................',
        '.........................fffFFFFFFFFfff.........................',
        '.........................fffFFFFFFFFfff.........................',
        '..........................fffFFFFFFfff..........................',
        '...........................ffFFFFFFff...........................',
        '............................fNNFFFfNN...........................',
        '.......................FFFFFNNNffffNNN..........................',
        '.....................FFFFFFFNNNFFFFNNN..........................',
        '...................FFFFFFFFFNNNFFFFNNN..........................',
        '.................FFFFFFFFFFNNNFFFFFFNNN.........................',
        '...............FFFFFFFFFFFFNNNFFFFFFNNN.........................',
        '.............FFFFFFFFFFFFyyNNNyyyyF.NNN.........................',
        '...........FFFFFFFFFFFFyyFyNNNyFFF..NNN.........................',
        '.........FFFFFFFFFFFyyyyyyNNNFFFF....NNN........................',
        '.......FFFFFFFFFFFyyFyyFFyNNNFFF.....NNN........................',
        '.....FFFFFFFFFFyyyFyyFFyyFNNNFF......NNN........................',
        '...FFFFFFFFFFyyFyyyFyyyFFFNNFF........NN........................',
        '.FFFFFFFFFyyyFyyFFyyFFFFFFFFF...................................',
        'FFFFFFFFyyFyyyFFyyFFFFFFFFFF....................................',
        'FFFFFyyyFyyFFFyyFFFFFFFFFFFF....................................',
        'FFFyyFFyyFFFyyFFFFFFFFFFFFF.....................................',
        'FFFyFFFyFFFFyFFFFFFFFFFFFF......................................',
        'FFFFFFFFFFFFFFFFFFFFFFFFF.......................................',
        '.FFFFFFFFFFFFFFFFFFFFFFF........................................',
      ],
    },
    /* феникс: перья добела, крылья огненные, хвост золотистый, искры над головой */
    phoenix: { base: 'firebird', tint: { r: 'F', f: 'w', F: 'f', y: 'O', N: 'D' }, extra: [[33, 3, 'c'], [32, 3, 'c'], [34, 3, 'c'], [33, 2, 'c'], [33, 4, 'c'], [43, 3, 'c'], [42, 3, 'c'], [44, 3, 'c'], [43, 2, 'c'], [43, 4, 'c']] },
  });
})();
