/* ============================================================================
   view/sprites_rampart.js — спрайты существ фракции Rampart (Оплот).
   Формат: см. docs/sprite-guide.md. Имя спрайта = id из js/data/creatures.js.
   Все существа смотрят вправо, якорь — низ по центру, контур 'k'.
   Подключать после js/view/sprites.js.
   ========================================================================== */
(function () {
  'use strict';
  H3.Sprites.defineMany({

    /* ---------------- 1. Кентавр (24×24): человек-конь с копьём ---------- */
    centaur: {
      rows: [
        '..............kkk.......',
        '.............kNNNk..kk..',
        '............kNsssSk.kyk.',
        '............kNsskSk.kyk.',
        '.............kssSk..kTk.',
        '..............kSk...kTk.',
        '............kkgggk..kTk.',
        '...........ksgggggkkkTk.',
        '..........kskggggggsSTk.',
        '..........kk.kGGGGkkkTk.',
        '.............kGGGk..kTk.',
        '......kkkkk..knnnnk.kTk.',
        '....kknTTTTkkknTTnnk.kk.',
        '..kkknnnnnnnnnnnnnnnnnk.',
        '.kNknNnnnnnnnnnnnnnnnnk.',
        '.kNkNnnnnnnnnnnnnnnnnnk.',
        '.kNkNNnnnnnnnnnnnnnNNnk.',
        '..kkknkNkkkkkkknkNkkkk..',
        '....knkNk.....knkNk.....',
        '....knkNk.....knkNk.....',
        '....knkNk.....knkNk.....',
        '....knkNk.....knkNk.....',
        '....kDkDk.....kDkDk.....',
        '....kkkkk.....kkkkk.....',
      ],
    },
    /* Капитан кентавров: стальной панцирь, шлем с красным плюмажем, красный плащ */
    centaur_captain: {
      base: 'centaur',
      tint: { g: 'e', G: 'E' },
      extra: [
        [14, 0, 'r'], [15, 0, 'r'],
        [14, 1, 'e'], [15, 1, 'l'], [16, 1, 'e'], [13, 2, 'E'], [13, 3, 'E'],
        [12, 7, 'r'], [11, 8, 'r'], [12, 8, 'r'], [11, 9, 'R'], [12, 9, 'k'],
      ],
    },

    /* ---------------- 2. Гном (22×20): борода, кольчуга, топор ------------ */
    dwarf: {
      rows: [
        '......kkkkk...........',
        '.....kTTnnnk..........',
        '....kTnnnnnnk.........',
        '....kNNNNNNNk...kdk...',
        '....kssssksk....kdkk..',
        '....kssssssk....kdlek.',
        '.....kooooook...kdllek',
        '....kooOooooook.kdllek',
        '...kooOOooooook.kdlek.',
        '...kOOOOOOkeeekkkdkk..',
        '..kEeeeeeeekeeeekdk...',
        '..keeeeeeeeeeeesSdk...',
        '..keeeeeeeeeekkkkdk...',
        '..kEeeeeeeeeEk..kk....',
        '...kEEEEEEEEk.........',
        '...kdddkkdddk.........',
        '...kddk..kddk.........',
        '...kddk..kddk.........',
        '..kDDDk.kDDDk.........',
        '..kkkkk.kkkkk.........',
      ],
    },
    /* Боевой гном (24×20): синий шлем, двусторонний топор над плечом — редрав */
    battle_dwarf: {
      rows: [
        '......kkkkk.............',
        '.....kccbbbk....kkkdkkk.',
        '....kcbbbbbbk..kllkdkllk',
        '....kBBBBBBBk..kleedeelk',
        '....kssssksk...kllkdkllk',
        '....kssssssk....kkkdkkk.',
        '.....kooooook.....kdk...',
        '....kooOooooook...kdk...',
        '...kooOOooooook...kdk...',
        '...kOOOOOOkeeekkkkkdk...',
        '..kEeeeeeeekeeeeeekdk...',
        '..keeeeeeeeeeeeeesSdk...',
        '..keeeeeeeeeekkkkkkdk...',
        '..kEeeeeeeeeEk....kk....',
        '...kEEEEEEEEk...........',
        '...kdddkkdddk...........',
        '...kddk..kddk...........',
        '...kddk..kddk...........',
        '..kDDDk.kDDDk...........',
        '..kkkkk.kkkkk...........',
      ],
    },

    /* ---------------- 3. Лесной эльф (22×24): зелёный, лук, острые уши ---- */
    wood_elf: {
      rows: [
        '.......kkkk...........',
        '......knnnnk..........',
        '.....knnnnnnk.........',
        '...kkkNsssssk.....kk..',
        '..ksskNsskssk....kTk..',
        '...kkkNssssk.....l.Tk.',
        '......kSssk......l.Tk.',
        '.......kSk.......l.Tk.',
        '.....kkgggkk.....l..Tk',
        '....kGkgggkskkkkklkkTk',
        '....kGkggggksssssssSTk',
        '....kGkgggggkkkkklkkTk',
        '....kGkgggggk....l..Tk',
        '....kGkGgggGk....l.Tk.',
        '....kGkGGGGGk....l.Tk.',
        '....kkkNNNNNk....l.Tk.',
        '......kNkkNk.....kTk..',
        '......kNk.kNk.....kk..',
        '......kNk.kNk.........',
        '......kNk.kNk.........',
        '......kNk.kNk.........',
        '......kNk.kNk.........',
        '.....kDDk.kDDk........',
        '.....kkkk.kkkk........',
      ],
    },
    /* Великий эльф: золотые волосы, светлая одежда, голубой плащ, золотые концы лука */
    grand_elf: {
      base: 'wood_elf',
      tint: { n: 'y', g: 'i', G: 'c' },
      extra: [[8, 1, 'w'], [18, 4, 'y'], [18, 16, 'y'], [6, 3, 'Y'], [6, 4, 'Y'], [6, 5, 'Y']],
    },

    /* ---------------- 4. Пегас (24×24): белая крылатая лошадь, парит ------ */
    pegasus: {
      rows: [
        '.......kkk..............',
        '.....kkwwwk.............',
        '....kwwLLLLk............',
        '...kwwlLLLLLk...........',
        '...kLwwlLLLLLk..........',
        '..kllLwwlLLLLLk...kkk...',
        '..kllLLwwlLLLLLk.kwLLkk.',
        '...kklLLLwlLLLLkkyLkLLLk',
        '....kkllLLwlLLLLkyLLLLek',
        '......kkllLwlLLLkyLLkkkk',
        '........kkllLLLLkkLLLk..',
        '....kkkkkkkkkLLLLLLLLk..',
        '...kwwwwwwwwwwwwwwLLLk..',
        '..kLLLLLLLLLLLLLLLLLk...',
        '.kIkLLLLLLLLLLLLLLLLk...',
        '.kIklLLLLLLLLLLLLLLlk...',
        '..kkllLLLLLLLLLLLLllk...',
        '....kklklkkkkkkklklkk...',
        '.....kLkLk.....kLkLk....',
        '.....kLkLk.....kLkLk....',
        '.....klklk.....klklk....',
        '.....kkkkk.....kkkkk....',
        '........................',
        '........................',
      ],
    },
    /* Серебряный пегас: серебристое тело, голубая грива и хвост */
    silver_pegasus: {
      base: 'pegasus',
      tint: { L: 'l', l: 'e', y: 'c', I: 'c' },
      extra: [[18, 6, 'c'], [17, 10, 'c']],
    },

    /* ---------------- 5. Дендроид-страж (26×28): дерево-человек ---------- */
    dendroid_guard: {
      rows: [
        '.......kkk......kkk.......',
        '......kgggk....kgggk......',
        '.....kgggggkkkkkgggggk....',
        '....kgGgggggggggggggGk....',
        '....kGgggggGGGgggggGk.....',
        '.....kkGGgggggggGGkk......',
        '.......kkNnnnnnnNkk.......',
        '.........kTnnnnnnk........',
        '..kk.....kTnknnknk....kk..',
        '.kNnk....kTnnnnnnk...knNk.',
        '.kNnnk...kTnnkknnk..knnNk.',
        '..kNnnk..kTnnnnnnkkknnNk..',
        '...kNnnkkkTnnnnnnnnnnNk...',
        '....kNnnnnTnnnnnnnnnNk....',
        '.....kNnnnTnnnnnnnnNk.....',
        '......kkkkTnnnnnnnNk......',
        '.........kTnnnnnnnNk......',
        '.........kTnnnnnnnNk......',
        '.........kTnnNnnnnNk......',
        '.........kTnnNnnnnNk......',
        '........kkTnnnNnnnNkk.....',
        '.......kNnTnnnnNnnnNNk....',
        '......kNnnkTnnnnkNnnNNk...',
        '.....kNnnk.kTnnnk.kNnNNk..',
        '....kNnnk..kTnnk...kNNNk..',
        '...kNnnk...kNNk.....kNNk..',
        '..kDDDk....kDDk.....kDDDk.',
        '..kkkkk....kkkk.....kkkkk.',
      ],
    },
    /* Дендроид-солдат: темнее кора, листья на ветках-руках */
    dendroid_soldier: {
      base: 'dendroid_guard',
      tint: { n: 'N', N: 'D', T: 'n' },
      extra: [
        [2, 9, 'g'], [3, 9, 'h'], [2, 10, 'g'], [3, 10, 'g'], [4, 10, 'h'],
        [22, 9, 'h'], [23, 9, 'g'], [21, 10, 'g'], [22, 10, 'h'], [23, 10, 'g'],
        [9, 3, 'h'], [16, 3, 'h'],
      ],
    },

    /* ---------------- 6. Единорог (28×28): белая лошадь с рогом ----------- */
    unicorn: {
      rows: [
        '......................kkk...',
        '.....................kiik...',
        '....................kiik....',
        '.................kkkkiik....',
        '................kIILLLkk....',
        '...............kIILLLLLLk...',
        '..............kIILLkLLLLk...',
        '..............kILLLLLLLLek..',
        '.............kIILLLLkkkkkk..',
        '.............kILLLLLk.......',
        '.............kILLLLk........',
        '............kILLLLLk........',
        '.....kkkkkkkkILLLLLk........',
        '....kwwwwwwwwwLLLLLLk.......',
        '..kkLLLLLLLLLLLLLLLLLk......',
        '.kIkLLLLLLLLLLLLLLLLLLk.....',
        '.kIkLLLLLLLLLLLLLLLLLLk.....',
        '.kIkLLLLLLLLLLLLLLLLLLk.....',
        '.kIIklLLLLLLLLLLLLLLLlk.....',
        '..kIkllLLLLLLLLLLLLLllk.....',
        '..kkkkklklkkkkkkkkklklk.....',
        '......kLkLk.......kLkLk.....',
        '......kLkLk.......kLkLk.....',
        '......kLkLk.......kLkLk.....',
        '......kLkLk.......kLkLk.....',
        '......klklk.......klklk.....',
        '......klklk.......klklk.....',
        '......kkkkk.......kkkkk.....',
      ],
    },
    /* Боевой единорог: голубая грива и хвост, золотой рог */
    war_unicorn: {
      base: 'unicorn',
      tint: { I: 'c', i: 'y' },
      extra: [[15, 6, 'b'], [14, 8, 'b'], [13, 11, 'b'], [2, 17, 'b'], [3, 18, 'b'], [22, 0, 'Y'], [21, 1, 'Y']],
    },

    /* ---------------- 7. Зелёный дракон (32×32): крылья, хвост, пасть ----- */
    green_dragon: {
      rows: [
        '......kk........................',
        '.....kGGk.......................',
        '....kGGGGk......................',
        '....kGGgGGk.............kk.kk...',
        '...kGGGgGGGk...........kgkkgkk..',
        '...kGGGGgGGGk..........kgggggggk',
        '..kGGGGGgGGGGk........kgggykgggk',
        '..kGGGGGGgGGGGk.......kgggggggkk',
        '..kGGgGGGGgGGGGk......kgGggggkkk',
        '...kGGgGGGGgGGGGk.....kgGggkkiik',
        '...kGGGgGGGGgGGGkk....kgGggkkkk.',
        '....kGGGgGGGGgGGGGk...kgGgggk...',
        '.kk..kGGGgGGGGgGGGGk..kgGggk....',
        '.kGk..kkGGGgGGGGgGGGk.kgGggk....',
        '.kGGk...kkGGGgGGGGGGkkkgGggk....',
        '.kGGk.....kkkGGGGGGGggggGgggk...',
        '.kGGk...kkkkkkkkkkkgggggGggggk..',
        '.kGGk..kggggggggggggggggGgggggk.',
        '.kGGkkkggggggggggggggggggggggggk',
        '.kGGGGGgggggggggggggggggggggggk.',
        '.kGGGGgggggttttttttttttttggggk..',
        '..kGGGggggttttttttttttttttgggk..',
        '...kGGggggkttttttttttttttkgggk..',
        '....kkGGggkkkkkkkkkkkkkkkkggggk.',
        '......kkGGGk..........kGGgggkk..',
        '........kGGk..........kGGggk....',
        '........kGGk..........kGGgk.....',
        '........kGGk..........kGGk......',
        '........kGGk..........kGGk......',
        '.......kGGGk.........kGGGk......',
        '......kGGGGk........kGGGGk......',
        '......kkkkkk........kkkkkk......',
      ],
    },
    /* Золотой дракон: золотая чешуя, красный глаз, светлое брюхо */
    gold_dragon: {
      base: 'green_dragon',
      tint: { g: 'y', G: 'Y', t: 'i' },
      extra: [[26, 6, 'r'], [25, 6, 'f'], [8, 6, 'f'], [10, 8, 'f'], [12, 10, 'f']],
    },
  });
})();
