/* ============================================================================
   view/sprites_dungeon_hd.js — существа Темницы в крупной сетке (unit 2), стиль Б:
   без контурной линии, тона кладёт рисунок. Собирается скриптом dev/proto/dungeon_hd.py.
   ========================================================================== */
(function () {
  'use strict';
  H3.Sprites.defineMany({
    /* троглодит: сгорбленный безглазый ящер, светлое брюхо, гребень на спине, дубина (40×46) */
    troglodyte: {
      hd: true, unit: 2,
      rows: [
        '..............................TTTTT.....',
        '.............................TTTTTTT....',
        '.............................TTTnnTT....',
        '.............................TTTTTTT....',
        '..............................TTTTT.....',
        '...............................nNn......',
        '......ppppp....................nNn......',
        '....pppppppppp.................nNn......',
        '..pppppppppppppp...............nNn......',
        '.ppppppppppppppppp.............nNn......',
        'kkppppppppppppppppp............nNn......',
        'kkppppppppppppppppp............nNn......',
        'PPPPPPppppppppppppp............nNn......',
        'PiiPiiPPPPpppppppppp...........nNn......',
        '.PiiPiiPPPPPpppPPPppPPP..PPP...nNn......',
        '....PPPPPPPPPPpPPPppPPP..PPP...nNn......',
        '..........PPPPppPppppPPP..P....nNn......',
        '..........ppppppPppppPpPPPP....nNn......',
        '..........ppppppPppppPpPPPP....nNn......',
        '.........ppppppppppppppppPPP...nNn......',
        '.........pppppppppppppppppppp..nNn......',
        '.........ppppAAAAAppppppppppppppNn......',
        '.........ppppAAAAAppppppppppppppNn......',
        '.........pppAAAAAAAppppppppppPPPPP......',
        '.........pppAAAAAAAAppppppppPPPPPP......',
        '.........pppAAAAAAAAppppppppPP..........',
        '.........pppAAAAAAAAppppppppPP..........',
        '.........pppAAAAAAAAppppppppP...........',
        '........ppppAAAAAAAApppppppp............',
        '........ppppAAAAAAAAppppppp.............',
        '........ppppAAAAAAAAppppppp.............',
        '.......pppppAAAAAAAppppppp..............',
        '......ppppppAAAAAAppppppp...............',
        '.....PPPpppppAAAAppppppp................',
        '.....PPPpppppAAAAppppppp................',
        '....PPPPpppppppppppppppp................',
        '...PPPP.pppppppppppppppp................',
        '..PPPP..PPPPPPPPPPPPPPPP................',
        '.PPPP...pppppp..pppppp..................',
        '.PPP....pppppp..pppppp..................',
        '.PP.....pppppp..pppppp..................',
        '.PP.....pppppp..pppppp..................',
        '........PPpppp..PPpppp..................',
        '........PPpppp..PPpppp..................',
        '.......ppppppp..ppppppp.................',
        '.......PPPPPPP..PPPPPPP.................',
      ],
    },
    /* адский троглодит: красная кожа, огненное брюхо, тлеющая дубина */
    infernal_troglodyte: { base: 'troglodyte', tint: { p: 'r', P: 'R', A: 'f', T: 'F', n: 'O', N: 'R' } },
    /* гарпия: крылатая женщина, тёмные волосы, золотые крылья вверх, птичьи лапы с когтями (композитор) (44×48) */
    harpy: {
      hd: true, unit: 2,
      rows: [
        '.........YYYY..................YYYY.........',
        '....YYYYYYYYYY................YYYYYYYYYY....',
        '..YYYYYYYYYYYY................YYYYYYYYYYYY..',
        '..yyyYYYYYYYYYY..............YYYYYYYYYYyyy..',
        '.yyyyyYYYYYYYYYY...RRRRRR...YYYYYYYYYYyyyyy.',
        '.yyyyyyYYYYYYYYY..RRRRRRRR..YYYYYYYYYyyyyyy.',
        '.yyyyyyyYYYYYYYYYRRRssssRRRYYYYYYYYYyyyyyyy.',
        '.yyyyyyYyYYYYYYYYRRssssssRRYYYYYYYYyYyyyyyy.',
        '...yyyyyyyYYYYYYYRssssssssRYYYYYYYYyyyyyy...',
        '...yyyyyyyYYYYYRRRssssssssRRRYYYYYyyyyyyy...',
        '....yyyyyyyYYYYRRRssksssksRRRYYYYyyyyyyy....',
        '.....yyyyyyyYYYRRRssssssssRRRYYYyyyyyyy.....',
        '......yyyyyYyYYRRYRssssssRYRRYYyYyyyyy......',
        '.......yyyyyyyRRRYYRssssRYYRRRyyyyyyy.......',
        '.......yyyyyyYRRRRYYYYYYYYRRRRyyyyyyy.......',
        '........yyyyyyRRRssssssssssRRRyyyyyy........',
        '.........yyyyyRRssssssssssssRRyyyyy.........',
        '..........yyyyRsssssNNNNsssssRyyyy..........',
        '...........yyRsssssNNNNNNsssssRyy...........',
        '...........yyssssssNNNNNNssssssyy...........',
        '............sssssssNNNNNNsssssss............',
        '............ssssssNNNNNNNNssssss............',
        '...........sssssssssNNNNsssssssss...........',
        '..........ssssssyssssssssssyssssss..........',
        '.........ssssssyyssssssssssyyssssss.........',
        '........ssssss...ssssssssss...ssssss........',
        '......SSSSsss....ssssssssss....sssSSSS......',
        '......SSSSss.....ssssssssss.....ssSSSS......',
        '......SSSSs......ssssssssss......sSSSS......',
        '......SSSS.......ssssssssss.......SSSS......',
        '.................NNNNNNNNNN.................',
        '.................NNNNNNNNNN.................',
        '.................NNNNNNNNNN.................',
        '.................NNNNNNNNNN.................',
        '.................NNN....NNN.................',
        '.................NNN....NNN.................',
        '................NNN......NNN................',
        '................NNN......NNN................',
        '................NNN......NNN................',
        '...............NNN........NNN...............',
        '...............NNN........NNN...............',
        '..............yyyy........yyyy..............',
        '..............yyyy........yyyy..............',
        '.............yyyyyy......yyyyyy.............',
        '............yyyyyyyy....yyyyyyyy............',
        '............yyyyyyyy....yyyyyyyy............',
        '............yy.yy.yy....yy.yy.yy............',
        '............................................',
      ],
    },
    /* гарпия-ведьма: зелёная кожа, пурпурные крылья, чёрные волосы, красные глаза */
    harpy_hag: { base: 'harpy', tint: { s: 'g', S: 'G', y: 'p', Y: 'P', R: 'z', k: 'r' } },
    /* бехолдер: парящий шар с огромным глазом, стебли с глазками сверху, зубастая пасть (композитор) (48×48) */
    beholder: {
      hd: true, unit: 2,
      rows: [
        '......................wwww......................',
        '...........wwww.......wwkw.......wwww...........',
        '...........wwww.......wwww.......wwww...........',
        '...........wwkw........pp........wwkw...........',
        '...wwww....wwww........pp........wwww....wwww...',
        '...wwww.....pppp.......pp.......pppp.....wwww...',
        '...wwkw......ppp.......pp.......ppp......wwkw...',
        '...wwwwp......ppp......pp......ppp......pwwww...',
        '.....ppppp....pppp.....pp.....pppp....ppppp.....',
        '......ppppp....pppp....pp....pppp....ppppp......',
        '........ppppp...ppp....pp....ppp...ppppp........',
        '.........ppppp..pppp...pp...pppp..ppppp.........',
        '..........pppppp.pppp..pp..pppp.pppppp..........',
        '............ppppp.ppp..pp..ppp.ppppp............',
        '.............pppppppppppppppppppppp.............',
        '...............pppppppppppppppppp...............',
        '................pppppppppppppppp................',
        '..............pppppppppppppppppppp..............',
        '.............AAAApppppppppppppppppp.............',
        '............AAAAAApppppppppppppppppp............',
        '...........AAPPPPPPPPPPPPPPPPPPPPPPp............',
        '...........AAPPPPPPPPPPPPPPPPPPPPPPpp...........',
        '..........ppAPPPPPPPPPPPPPPPPPPPPPPppp..........',
        '..........pppAAAwwwwwwbbbbbbwwwwpppppp..........',
        '..........pppppwwwwwwbbbbbbbbwwwwppppp..........',
        '.........pppppwwwwwwwbbb..bbbwwwwwppppp.........',
        '.........pppppwwwwwwwbb.kk.bbwwwwwppppp.........',
        '.........pppppwwwwwwwbb.kk.bbwwwwwppppp.........',
        '.........pppppwwwwwwwbbb..bbbwwwwwppppp.........',
        '.........ppppppwwwwwwbbbbbbbbwwwwpppppp.........',
        '.........pppppppwwwwwwbbbbbbwwwwppppppp.........',
        '.........pppppppPwwwwwwwwwwwwwwPppppppp.........',
        '.........pppppPPPPPwwwwwwwwwwPPPPPppppp.........',
        '..........ppppPPPPPPPPPPPPPPPPPPPPpppp..........',
        '..........pppPPPPPPPPPPPPPPPPPPPPPPppp..........',
        '..........pppPPPPPPPPPPPPPPPPPPPPPPppp..........',
        '...........ppPPPPPPPPPPPPPPPPPPPPPPpp...........',
        '............pPPiiiiiiiiiiiiiiiiiiiip............',
        '............ppPiiiiiiiiiiiiiiiiiiiip............',
        '.............pPPiiPPiiPPiiPPiiPPiip.............',
        '..............pPiiPPiiPPiiPPiiPPii..............',
        '................pPPPPPPPPPPPPPPp................',
        '.................pppPPPPPPPPppp.................',
        '....................pppppppp....................',
        '................................................',
        '................................................',
        '................................................',
        '................................................',
      ],
    },
    /* злой глаз: красный, жёлтая радужка, два лишних стебля по бокам */
    evil_eye: { base: 'beholder', tint: { p: 'r', P: 'R', b: 'y', A: 'o' }, extra: [[0, 11, 'w'], [1, 11, 'w'], [2, 11, 'w'], [45, 11, 'w'], [46, 11, 'w'], [47, 11, 'w'], [0, 12, 'w'], [1, 12, 'w'], [2, 12, 'w'], [45, 12, 'w'], [46, 12, 'w'], [47, 12, 'w'], [0, 13, 'w'], [1, 13, 'k'], [2, 13, 'w'], [45, 13, 'w'], [46, 13, 'w'], [47, 13, 'k'], [0, 14, 'w'], [1, 14, 'w'], [2, 14, 'w'], [3, 14, 'r'], [44, 14, 'r'], [45, 14, 'w'], [46, 14, 'w'], [47, 14, 'w'], [1, 15, 'r'], [2, 15, 'r'], [3, 15, 'r'], [4, 15, 'r'], [43, 15, 'r'], [44, 15, 'r'], [45, 15, 'r'], [46, 15, 'r'], [2, 16, 'r'], [3, 16, 'r'], [4, 16, 'r'], [5, 16, 'r'], [42, 16, 'r'], [43, 16, 'r'], [44, 16, 'r'], [45, 16, 'r'], [3, 17, 'r'], [4, 17, 'r'], [5, 17, 'r'], [6, 17, 'r'], [41, 17, 'r'], [42, 17, 'r'], [43, 17, 'r'], [44, 17, 'r'], [4, 18, 'r'], [5, 18, 'r'], [6, 18, 'r'], [7, 18, 'r'], [40, 18, 'r'], [41, 18, 'r'], [42, 18, 'r'], [43, 18, 'r'], [5, 19, 'r'], [6, 19, 'r'], [7, 19, 'r'], [8, 19, 'r'], [39, 19, 'r'], [40, 19, 'r'], [41, 19, 'r'], [42, 19, 'r'], [6, 20, 'r'], [7, 20, 'r'], [8, 20, 'r'], [9, 20, 'r'], [38, 20, 'r'], [39, 20, 'r'], [40, 20, 'r'], [41, 20, 'r'], [7, 21, 'r'], [8, 21, 'r'], [9, 21, 'r'], [10, 21, 'r'], [37, 21, 'r'], [38, 21, 'r'], [39, 21, 'r'], [40, 21, 'r'], [8, 22, 'r'], [9, 22, 'r'], [38, 22, 'r'], [39, 22, 'r'], [9, 23, 'r'], [38, 23, 'r']] },
    /* медуза: змеиный хвост кольцом, торс в тёмном платье, волосы-змеи, лук со стрелой (композитор) (48×52) */
    medusa: {
      hd: true, unit: 2,
      rows: [
        '............gg.ggggG..gggg..Ggggg.gg............',
        '...........ggggGggGGG..gg..GGGggGgggg...........',
        '...........ggggGGGGGGG.GG.GGGGGGGgggg...........',
        '............ggGGGGGGGGGGGGGGGGGGGGgg............',
        '...............GGGGGGGGGGGGGGGGGG...............',
        '.................GGGGGGssGGGGGG.................',
        '.................GGGGssssssGGGG.................',
        '........NNggGGGGGGGGssssssssGGGGGGGGgg..........',
        '.......NNggggGGGGGGGssssssssGGGGGGGgggg.........',
        '.......NNggggGGGGG..ssssssss..GGGGGgggg.........',
        '.......NNwgg........ssksssks........gg..........',
        '......NNNw..........ssssssss....................',
        '......NNNw..........ssssssss....................',
        '......NNNw...........ssssss.....................',
        '.....NNN.w.............ss.......................',
        '.....NNN.w......................................',
        '.....NNN.w.........ssssssssss...................',
        '....SlSSss...ssssssssssssssss...................',
        '....Slllsssssssssssssssssssss...................',
        '....SlllNNNNNNNNNNNNNNNNNNNNNNNNN...............',
        '....SlSSsssssssssssssssssssss...................',
        '....NNN..ssssssssssssssssssss...................',
        '....NNN..w.....ssssssssssssss...................',
        '.....NNN.w........yyyyyyyyyyyy.............gg...',
        '.....NNN.w........yyyyyyyyyyyy............gggg..',
        '.....NNN.w........PPPPPPPPPPPP............Gggg..',
        '......NNNw........PPPPPPPPPPPP............GgggG.',
        '......NNNw........PPPPPPPPPPPP............GgggG.',
        '......NNNw........PPPPPPPPPPPP............Ggggg.',
        '.......NNw........PPPPPPPPPPPP............GGggg.',
        '.......NNw........PPPPPPPPPPPP.............GgggG',
        '.......NNw........PPPPPPPPPPPP.............Ggggg',
        '........Nw........PPPPPPPPPPPP.............Ggggg',
        '..................PPPPPPPPPPPP.............Ggggg',
        '...............GggPPPPPPPPPPPP............GGgggg',
        '............ggggggPPPPPPPPPPPP............GggggG',
        '.........GggggggggPPPPPPPPPPPP............GhhggG',
        '........GgggggggggPPPPPPPPPPPP............hggggG',
        '.......GggggggggggggggggGGGG..............hggggG',
        '......GgggggggggggggGGGGGGGG.............hGggggG',
        '.....GggggggggggGGGGGGGGGGG..............hggggGG',
        '....GggggggggGGGGGGGGGGG................hgggggGG',
        '...GggggggggGGGGGGGGG..................ghggggggG',
        '..GgggggggggGGGGG....................GggggggggGG',
        '..Gggggggggggg.....................GggggggggggGG',
        '..Ggggggggggggggg.................ggggggggggGGGG',
        '..GGgggggggghhhhhhhhhhhhhhhhhhhhhhhgggggggGGGGG.',
        '..GGGgggggggggggggggggggggggggggggggggggGGGGGG..',
        '..GGGGGGgggggggggggggggggggggggggggggggGGGGG....',
        '...GGGGGGGgggggggggggggggggggggggggggGGGGGG.....',
        '.....GGGGGGGGgggggggggggggggggggggggGGGGG.......',
        '........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.........',
      ],
    },
    /* королева медуз: синее платье, золотая полоса чешуи, золотая тиара */
    medusa_queen: { base: 'medusa', tint: { P: 'B', h: 'y' }, extra: [[20, 5, 'y'], [21, 5, 'y'], [22, 5, 'y'], [23, 5, 'y'], [24, 5, 'y'], [25, 5, 'y'], [26, 5, 'y'], [27, 5, 'y'], [28, 5, 'y'], [20, 6, 'y'], [21, 6, 'y'], [22, 6, 'y'], [23, 6, 'y'], [24, 6, 'y'], [25, 6, 'y'], [26, 6, 'y'], [27, 6, 'y'], [28, 6, 'y'], [20, 4, 'y'], [21, 4, 'y'], [23, 4, 'y'], [24, 4, 'y'], [25, 4, 'y'], [27, 4, 'y'], [28, 4, 'y'], [20, 7, 'Y'], [21, 7, 'Y'], [22, 7, 'Y'], [23, 7, 'Y'], [24, 7, 'Y'], [25, 7, 'Y'], [26, 7, 'Y'], [27, 7, 'Y'], [28, 7, 'Y']] },
    /* минотавр: тёмная бычья голова с рогами, загорелый торс, красная повязка, двусторонняя секира (52×60) */
    minotaur: {
      hd: true, unit: 2,
      rows: [
        '......ii................ii..........................',
        '.....iii................iii.........................',
        '.....iii................iii......lee.nNneeel........',
        '......iii..............iii......leee.nNneeeel.......',
        '......iiii............iiii.....leeee.nNneeeeel......',
        '.......iiiNNNNNNNNNNNNiii.....leeeee.nNneeeeeel.....',
        '........iNNNNNNNNNNNNNNi......leeeee.nNneeeeeel.....',
        '.........NNNNNNNNNNNNNNN......leeeee.nNneeeeeel.....',
        '.........NNNwwNNNNNNwwNN......leeeee.nNneeeeeel.....',
        '.........NNNkwNNNNNNwkNN.......leeee.nNneeeeel......',
        '.........NNNNNNNNNNNNNNN........leee.nNneeeel.......',
        '..........NNNnnnnnnnnnN..........lee.nNneeel........',
        '..........NNnnnnnnnnnnnN.............nNn............',
        '..........NnnnnnnnnnnnnnN............nNn............',
        '..........NnnnkknnnnkknnN............nNn............',
        '...........NnnnnnnnnnnnN.............nNn............',
        '............NnnnnnnnnnN..............nNn............',
        '.............NNNNNNNNN...............nNn............',
        '........SSSSSSSSSSSSSSSSSSS..........nNn............',
        '........SSSSSSSSSSSSSSSSSSS..........nNn............',
        '......SSSSSSSSSSSSSSSSSSSSSSS........nNn............',
        '......SSSSSSSSSSSSSSSSSSSSSSS........nNn............',
        '.....SSSSSSSSSSSSSSSSSSSSSSSSS.......nNn............',
        '.....SSSSSSSSSSSSSSSSSSSSSSSSS.......nNn............',
        '....SSSSSSSSnnnnnnnnnnSSSSSSSSS......nNn............',
        '....SSSSSSSSnnnnnnnnnnSSSSSSSSS......nNn............',
        '....SSSSSSSnnnnnnnnnnnnSSSSSSSSS.....nNn............',
        '....SSSSSSSnnnnnnnnnnnnSSSSSSSSS.....nNn............',
        '....SSSSS.SSnnnnnnnnnnSSSSSSSSSSS....nNn............',
        '....SSSSS.SSnnnnnnnnnnSSSSSSSSSSS....nNn............',
        '....SSSSS.SSSSnnnnnnSSSSSSSSSSSSSSSnnnnnn...........',
        '....SSSSS.SSSSnnnnnnSSSSSSSSSSSSSSSnnnnnn...........',
        '....SSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........',
        '....SSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........',
        '....SSSSS.SSSSnnnnnnSSSSSSSSSSSSSSSSSSSSS...........',
        '....SSSSS.SSSSnnnnnnSSSSSSSSSSSSSSSSSSSSS...........',
        '....SSSSS.SSSnnnnnnnnSSSSSSSSSSSSSSnnnnnn...........',
        '....SSSSS.SSSnnnnnnnnSSSSSSSSSSSSSSnnnnnn...........',
        '....SSSSS.SSSSnnnnnnSSSSSSSSSSSSS....nNn............',
        '....SSSSS.SSSSnnnnnnSSSSSSSSSSSSS....nNn............',
        '....SSSSS.SSSSSSSSSSSSSSSSSSSSSS.....nNn............',
        '....SSSSS.SSSSSSSSSSSSSSSSSSSSSS.....nNn............',
        '....nnnnn.SSSSSSSSSSSSSSSSSSSSS......nNn............',
        '....nnnnn.yyyyyyyyyyyyyyyyyyyyy......nNn............',
        '.....nnn..rrrrrrrrrrrrrrrrrrrrr......nNn............',
        '..........rrrrrrrrrrrrrrrrrrrrr......nNn............',
        '..........RRRRRRRRRRRRRRRRRRRRR......nNn............',
        '..........RRRRRRRRRRRRRRRRRRRRR......nNn............',
        '..........SSSSSSSSS...SSSSSSSSS.....................',
        '..........SSSSSSSSS...SSSSSSSSS.....................',
        '..........SSSSSSSSS...SSSSSSSSS.....................',
        '..........SSSSSSSSS...SSSSSSSSS.....................',
        '..........SSSSSSSSS...SSSSSSSSS.....................',
        '..........SSSSSSSSS...SSSSSSSSS.....................',
        '..........NNNNNNNNN...NNNNNNNNN.....................',
        '..........NNNNNNNNN...NNNNNNNNN.....................',
        '..........NNNNNNNNN...NNNNNNNNN.....................',
        '..........NNNNNNNNN...NNNNNNNNN.....................',
        '.........DDDDDDDDDD...DDDDDDDDDD....................',
        '.........DDDDDDDDDD...DDDDDDDDDD....................',
      ],
    },
    /* король минотавров: золотая корона, золотая секира, пурпурная повязка */
    minotaur_king: { base: 'minotaur', tint: { e: 'y', l: 'i', r: 'M', R: 'x' }, extra: [[11, 5, 'y'], [12, 5, 'y'], [13, 5, 'y'], [14, 5, 'y'], [15, 5, 'y'], [16, 5, 'y'], [17, 5, 'y'], [18, 5, 'y'], [19, 5, 'y'], [20, 5, 'y'], [21, 5, 'y'], [22, 5, 'y'], [23, 5, 'y'], [11, 6, 'y'], [12, 6, 'y'], [13, 6, 'y'], [14, 6, 'y'], [15, 6, 'y'], [16, 6, 'y'], [17, 6, 'y'], [18, 6, 'y'], [19, 6, 'y'], [20, 6, 'y'], [21, 6, 'y'], [22, 6, 'y'], [23, 6, 'y'], [11, 4, 'y'], [12, 4, 'y'], [16, 4, 'y'], [17, 4, 'y'], [21, 4, 'y'], [22, 4, 'y'], [11, 7, 'Y'], [12, 7, 'Y'], [13, 7, 'Y'], [14, 7, 'Y'], [15, 7, 'Y'], [16, 7, 'Y'], [17, 7, 'Y'], [18, 7, 'Y'], [19, 7, 'Y'], [20, 7, 'Y'], [21, 7, 'Y'], [22, 7, 'Y'], [23, 7, 'Y']] },
    /* мантикора: лев с тёмной гривой, перепончатые крылья, хвост скорпиона с жалом (композитор) (60×58) */
    manticore: {
      hd: true, unit: 2,
      rows: [
        '...........ppp..............................................',
        '..........PpppPPP.......l...................................',
        '........PPPPpppPPPPPP..ll...................................',
        '.......PPPPPpppPPPPPPRlll...................................',
        '......PPPPPPppppPPPPRlllPPP.................................',
        '.....PPPPPPPPpppPPPRRlllPPPPPPPpp...........................',
        '...PPPPPPPPPPpRRpRRRRPllPPPPPPppp...........................',
        '.pppPPPPPPPPPRRRRRRRRPPPPPPPPPppp...........................',
        '.ppppPPPPPPPRRRRRRRRPPPPPPPPPPppp...........................',
        '..ppppPPRRRRRRRRRRRRPPPPPPPPPPppp...........................',
        '...ppppRRRRRRRRRRpRRPPPPPPPPPppp............................',
        '....ppRRRRRRRRRRpppPPPPPPPPPPppp............................',
        '.....pRRRRRRPPPPpppPPPPPPPPPPppp............................',
        '.....RRRRRRPPPPPPpppPPPPPPPPPppp............................',
        '....RRRRRRpPPPPPPpppPPPPPPPPppp......NN.....................',
        '...RRRRRRpppPPPPPPpppPPPPPPPppp.....NNNNNNN.................',
        '..RRRRRR.ppppPPPPPpppPPPPPPPppp.....NNNNNNNNNNN.............',
        '..RRRRRR..pppppPPPPpppPPPPPPppp.....NNNNNNNNNNNNNNNNN.......',
        '...RRRR....pppppPPPpppPPPPPpppP.....NNNNNNNNNNNNNNNNNN.NN...',
        '...RRRR.....pppppPPPpppPPPPpppP......NN.NNNNNNNNNNNNNNNNNN..',
        '..RRRR.......pppppPPpppPPPPppp.........NNNNNNNNNNNNNNNNNNN..',
        '..RRRR.........ppppPppppPPPppp........NNNNNNNNooooooNNNNNN..',
        '.RRRRRR.........ppppPpppPPppp........NNNNNNNooooooooooNNNN..',
        '.RRRRRR..........ppppppppPppp........NNNNNNooooooooooooNN...',
        '..RRRRR...........pppppppPppp.......NNNNNNNooooyyooooooNNN..',
        '...RRRR............pppppppppp.......NNNNNNoooooykoooooooNN..',
        '...RRRR.............pppppppp........NNNNNNooooooooooooooNN..',
        '...RRRRR.............ppppppp........NNNNNNoooooooooOOOOOON..',
        '...RRRRRR.............pppppp........NNNNNNoooooooOOOOOOOOOO.',
        '...RRRRRR..............ppppp........NNNNNNNooooooOOOOOOOOOO.',
        '....RRRRRR..............ppp..........NNNNNNooooooOOOOOOOOOO.',
        '.....RRRRRRR.............ooooooooooooNNNNNNNoooooOOORwwRwwR.',
        '.......RRRRRR........oooooooooooooooooNNNNNNNNoooooORRRRRR..',
        '........RRRRRR....oooooooooooooooooooooNNNNNNNNNNNNNNNRRRR..',
        '........RRRRRR..ooooooooooooooooooooooooNNNNNNNNNNNNNN......',
        '.........RRRRR.ooooooooooooooooooooooooooNNNNNNNNNNNN.......',
        '..........RRRRRoooooooooooooooooooooooooooooNNNNNN..........',
        '...........RRRRoooooooooooooooooooooooooooooooooooo.........',
        '............RRoooooooooooooooooooooooooooooooooooooo........',
        '............oooooooooooooooooooooooooooooooooooooooo........',
        '............oooooooooooooooooooooooooooooooooooooooo........',
        '............oooooooooooooooooooooooooooooooooooooooo........',
        '.............oooooooooOOOOOOOOOOOOOOOOOOOOooooooooo.........',
        '..............ooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOoooo..........',
        '...............ooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoo...........',
        '................oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo............',
        '...........OOOOOOOOoooooooOOOOOOOOOOOOOOOOOOOooooooo........',
        '...........OOOOOOO.oooooooOOOOOOOOOOOOOOOOOO.ooooooo........',
        '...........OOOOOOO.ooooooooooooooooooOOOOOOO.ooooooo........',
        '...........OOOOOOO.ooooooo...........OOOOOOO.ooooooo........',
        '...........OOOOOOO.ooooooo...........OOOOOOO.ooooooo........',
        '...........OOOOOOO.ooooooo...........OOOOOOO.ooooooo........',
        '...........OOOOOOO.ooooooo...........OOOOOOO.ooooooo........',
        '...........OOOOOOO.OOOOOOo...........OOOOOOO.OOOOOOo........',
        '..........OOOOOOOOOOOOOOOO..........OOOOOOOOOOOOOOOO........',
        '..........iiOiiOiiiiOiiOii..........iiOiiOiiiiOiiOii........',
        '..........iiOiiOiiiiOiiOii..........iiOiiOiiiiOiiOii........',
        '..........ii.ii.iiii.ii.ii..........ii.ii.iiii.ii.ii........',
      ],
    },
    /* скорпикора: тёмно-красная шерсть, серые крылья, чёрный хвост, светящийся глаз и жало */
    scorpicore: { base: 'manticore', tint: { o: 'r', O: 'R', N: 'D', P: 'e', p: 'E', R: 'z', y: 'h', l: 'f' } },
    /* красный дракон: два перепончатых крыла, красная чешуя, золотое брюхо, рога, огонь в пасти (композитор) (64×60) */
    red_dragon: {
      hd: true, unit: 2,
      rows: [
        '............Rrrr...................................Rrrr.........',
        '.........RRRRrrrRRRR.......................rr.RRRRRrrrrRii......',
        '......RRRRRRRRrrrRRRRRRR..................rrrRiRRRRrrrRRii......',
        '.rrRRRRRRRRRRRrrrRRRRRRRRRRR.rr...........rrrRiiRRrrrrRRii......',
        '.rrrRRRRRRRRRRrrrrRRRRRRRRRRrrr...........rrrRiiiRrrrRRRiiR.....',
        '..rrrRRRRRRRRRRrrrRRRRRRRRRRrrr..........rrrrRRiiiirRRRiiiiR....',
        '...rrrrRRRRRRRRrrrrRRRRRRRRRrrr..........rrrRRRiiiiiRRRiiiiRR...',
        '....rrrrRRRRRRRRrrrRRRRRRRRRrrr..........rrrRRRRiiiii..iiiiRrrr.',
        '....rrrrrRRRRRRRrrrrRRRRRRRRrrr..........rrrRRRriiiirrriirRrrrr.',
        '.....rrrrrRRRRRRRrrrRRRRRRRRrrr.........rrrRRRRriirrrrrrrrrrrr..',
        '......rrrrrRRRRRRrrrRRRRRRRRrrr.........rrrRRRrrrrrrrrrrrrrrr...',
        '.......rrrrrRRRRRRrrrRRRRRRRrrr.........rrr..rrrrrrrrrrrrrrrr...',
        '........rrrrrRRRRRrrrRRRRRRRrrr........rrr...rrrrrrrrffrrrrrrr..',
        '.........rrrrr.RRRRrrrRRRRRRrrr........rrr..rrrrrrrrrfkrrrrrrr..',
        '..........rrrrr..RRrrrRRRRRRrrr........rrr..rrrrrrrrrrrrrrrrrr..',
        '...........rrrrr..RRrrrRRRRRrrrR.......rrr.rrrrrrrrrrrrrrrffrr..',
        '............rrrrr.RRrrrRRRRRrrrR......rrrRrrrrRrrrrrrrrrRRrffff.',
        '.............rrrrrRRRrrrRRRrrrRR......rrrRrrrRRrrrrrrrrrRRRRr...',
        '..............rrrrrRRrrrRRRrrrRR......rrrrrrrRRrrrrrrrrrRRRRRRR.',
        '...............rrrrrRRrrrRRrrrRR......rrrrrrRRrrrrrrrrrrRRRRR...',
        '................rrrrrRrrrRRrrrRR.....rrrrrrRRrrrrrrrrrr.........',
        '.................rrrrrrrrrRrrrRR.....rrrrrrRrrrrrrrrrr..........',
        '..................rrrrrrrrRrrrRR.....rrrrrRrrrrrrrrrrr..........',
        '...................rrrrrrrrrrrRR....rrrrrrrrrrrrrrrrr...........',
        '....................rrrrrrrrrrR.....rrrrrrrrrrrrrrrr............',
        '.....................rrrrrrrrrR.....rrrrrrrrrrrrrrrr............',
        '......................rrrrrrrr.....rrrrrrr.rrrrrrrr.............',
        '.................RR....RRrrrrRR....RRrrrrRRrrrrrrrr.............',
        '.................RR....RRrrrrRR....RRrrr.RRrrrrrrr..............',
        '.................RR....RR.rrrRR....RRrr..RRrrrrrrr..............',
        '................RRRR..RRRR.rRRRR..RRRR..RRRRrrrrr...............',
        '................RRRR..RRRRrrRRRRrrRRRR..RRRRrrrr................',
        '....................rrrrrrrrrrrrrrrrrrrrrrrrrrrr................',
        '..................rrrrrrrrrrrrrrrrrrrrrrrrrrrrr.................',
        '................rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.................',
        '..............rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..................',
        '.............rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.................',
        '.............rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.................',
        '............rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr................',
        '............rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr................',
        '............rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr................',
        '...........rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr................',
        '..........rrrrrryyyyyyyyyyyyyyyyyyyyyyyyyyyyyyr.................',
        '.........rrrrrrrYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYr.................',
        '........rrrrrrrryyyyyyyyyyyyyyyyyyyyyyyyyyyyyr..................',
        '......rrrrrrrr..YYYYYYYYYYYYYYYYYYYYYYYYYYYYY...................',
        '.....rrrrrrrr....RRRRRRyyyyyyyyyyyyrrrrrryyy....................',
        '....rrrrrrrr.....RRRRRRYYYYYYYYYYYYrrrrrrYYY....................',
        '...rrrrrrrr......RRRRRRyyyyyyyyyyyyrrrrrryy.....................',
        '..rrrrrrr........RRRRRR............rrrrrr.......................',
        '.rrrrrrr.........RRRRRR............rrrrrr.......................',
        '.rrrrrr..........RRRRRR............rrrrrr.......................',
        '.rrrrr..........RRRRRRR...........rrrrrrr.......................',
        '.rrrr...........RRRRRRR...........rrrrrrr.......................',
        '.rrr............RRRRRRR...........rrrrrrr.......................',
        'rrr.............RRRRRRR...........RRRRRRr.......................',
        'Rrr...........RRRRRRRRRR........RRRRRRRRRR......................',
        'RRR...........RiiRiiRiiR........RiiRiiRiiR......................',
        'RRR............iiRiiRii..........iiRiiRii.......................',
        'R..............ii.ii.ii..........ii.ii.ii.......................',
      ],
    },
    /* чёрный дракон: чёрная чешуя, серое брюхо, светлые рога, оранжевые глаза */
    black_dragon: { base: 'red_dragon', tint: { r: 'u', R: 'z', y: 'e', Y: 'E', i: 'l', f: 'o' } },
  });
})();
