/* ============================================================================
   view/sprites_necropolis.js — спрайты существ Некрополиса (14 шт.).
   Формат: см. docs/sprite-guide.md. Имя спрайта = id из js/data/creatures.js.
   Палитра: i/I/L — кость, u/E/z — тёмные латы и саван, x/P — некро-фиолет,
   h/g — зелёное свечение нежити, r/R — кровь и подкладка плаща.
   ========================================================================== */
(function () {
  H3.Sprites.defineMany({

    /* ---- 1 уровень: скелет (20×22) — костяной воин, щит слева, меч поднят ---- */
    skeleton: {
      rows: [
        '.......kkkkk........',
        '......kiiiiik.......',
        '.....kiLiiiiik......',
        '.....kiiuiiuik......',
        '.....kIiiiiiIk......',
        '......kIkIkIk.....k.',
        '.......kIIIk.....kek',
        '.....kkkkIkkkk...kek',
        '...kkIiIiIiIiIkk.kek',
        '.kNnnkIiIkIkIiIkIkek',
        '.kNnnnkIiIiIiIkIIkek',
        '.knynnkIIiIiIIkkIkek',
        '.kNnnnkkIiIiIkk.kyyk',
        '..kNnnk.kIIIk...kIIk',
        '...kkk..kIiIk....kk.',
        '.......kIIkIIk......',
        '.......kIk.kIk......',
        '.......kIk.kIk......',
        '.......kIk.kIk......',
        '.......kIk.kIk......',
        '......kIIk.kIIk.....',
        '......kkkk.kkkk.....',
      ],
    },
    /* скелет-воин: тёмный стальной щит + тёмный шлем + красные глаза */
    skeleton_warrior: {
      base: 'skeleton',
      tint: { n: 'E', N: 'u' },
      extra: [
        [7, 1, 'u'], [8, 1, 'E'], [9, 1, 'E'], [10, 1, 'E'], [11, 1, 'u'],
        [6, 2, 'u'], [7, 2, 'E'], [8, 2, 'E'], [9, 2, 'E'], [10, 2, 'E'], [11, 2, 'E'], [12, 2, 'u'],
        [8, 3, 'r'], [11, 3, 'r'],
      ],
    },

    /* ---- 2 уровень: ходячий мертвец (20×22) — зелёно-серый труп, руки вперёд ---- */
    walking_dead: {
      rows: [
        '......kkkkk.........',
        '.....kHHHHHk........',
        '....kHHjHHHjk.......',
        '....kjHzjjHzk.......',
        '....kjjjjjjjk.......',
        '.....kjGGGjk........',
        '......kjjk..........',
        '....kkkjjkkkk.......',
        '...kNnnkjjknnkkkkkk.',
        '..kNnNnkjjknkHHHHHHk',
        '..kNnnnkjjknkjjjjjjk',
        '..kNnNnkjjknkkkkkkk.',
        '..kNnnNnjjnnk.......',
        '...kNnNnNnNk........',
        '...kNnnnnnnk........',
        '....kNkNkNk.........',
        '....kjk.kjk.........',
        '....kjk.kjk.........',
        '....kGk.kGk.........',
        '....kjk..kjk........',
        '...kjjk..kjjk.......',
        '...kkkk..kkkk.......',
      ],
    },
    /* зомби: темнее, жёлтые глаза, торчащие кости */
    zombie: {
      base: 'walking_dead',
      tint: { H: 'j', j: 'G', G: 'Q', n: 'N', N: 'D' },
      extra: [
        [7, 3, 'y'], [11, 3, 'y'],
        [6, 2, 'i'], [5, 3, 'i'],
        [4, 8, 'i'], [3, 9, 'I'],
        [8, 12, 'i'], [9, 13, 'I'],
        [5, 17, 'i'],
      ],
    },

    /* ---- 3 уровень: привидение (22×22) — парящий саван, без ног ---- */
    wight: {
      rows: [
        '........kkkkk.........',
        '.......kLLlllk........',
        '......kLlllllek.......',
        '......klzzzzzlk.......',
        '......klzhzzhzlk......',
        '......klzzzzzzlk......',
        '.......kllzzzlk.......',
        '......kkkLlllkkk......',
        '.....kLllLlllleek.....',
        '....kLlllLllllleekkkk.',
        '....kllllLllllllllleLk',
        '....kllllLllleekkkllk.',
        '....kllllLllleek..kkk.',
        '....kllllLllleek......',
        '.....kllllllleek......',
        '.....klllllleeek......',
        '.....kkllleeeek.......',
        '......klleekeek.......',
        '......kek.kkkek.......',
        '.......k...k.k........',
        '......................',
        '......................',
      ],
    },
    /* призрак (24×22): тёмный саван, коса в правой руке — редрав */
    wraith: {
      rows: [
        '.................kkkk...',
        '................kllllkk.',
        '.................kkkeeek',
        '........kkkkk.....kNk.kk',
        '.......keeuuuk....kNk...',
        '......keuuuuuuk...kNk...',
        '......kuzzzzzuk...kNk...',
        '......kuzhzzhzuk..kNk...',
        '......kuzzzzzzuk..kNk...',
        '.......kuuzzzuk...kNk...',
        '......kkkeuuukkk..kNk...',
        '.....keuueuuuuuzkkkkNk..',
        '....keuuueuuuuuueekNk...',
        '....kuuuueuuuuzkkkkNk...',
        '....kuuuueuuuuzk..kNk...',
        '....kuuuueuuuuzk..kNk...',
        '.....kuuuuuuuzzk..kNk...',
        '.....kuuuuuzzzzk..kNk...',
        '.....kkuuuzzzzzk..kNk...',
        '......kuzukzuzk...kNk...',
        '......kuk.kkkuk...kkk...',
        '.......k...k.k..........',
      ],
    },

    /* ---- 4 уровень: вампир (22×22) — бледный, чёрный плащ с красной подкладкой ---- */
    vampire: {
      rows: [
        '.......kkkkk..........',
        '......kuuuuuk.........',
        '.....kuuLLLLuk........',
        '.....kuLLLLLLk........',
        '.....kuLzLLzLk........',
        '.....kLLLLLLLk........',
        '......kLLrwLk.........',
        '....kkkkkLLkkkk.......',
        '...kuuuukLLkuuuk......',
        '..kuuuuukEzzkuuuk.....',
        '..kuurRrkEzzzkuukkkk..',
        '..kuurRrkEzzzkkuuLLLk.',
        '..kuurRrkEzzzzkkkkLkk.',
        '..kuurRrkEzzzzk..kk...',
        '..kuurRrkEzzzzk.......',
        '..kuuRRrkEzzzzk.......',
        '..kuuRRrkkzzzzk.......',
        '..kuuRRk.kzzzzk.......',
        '..kuuRk..kzzkzk.......',
        '..kkkk...kkkkkk.......',
        '......................',
        '......................',
      ],
    },
    /* лорд вампиров (24×22): крылья летучей мыши, золотая застёжка — редрав */
    vampire_lord: {
      rows: [
        '.........kkkkk..........',
        '........kuuuuuk.........',
        '..kk...kuuLLLLuk...kk...',
        '.kxPk..kuLLLLLLk..kPxk..',
        '.kxxPk.kuLzLLzLk.kPxxk..',
        'kxxxPPkkLLLLLLLkkPPxxxk.',
        'kxxxxPPkkLLrwLkkPPxxxxk.',
        'kxxxxxPPkkkyykkkPPxxxxxk',
        'kxxxxxPPkuurzzruukPPxxxk',
        'kxxxxxPPkuurzzruukPPxxxk',
        '.kxxxxPPkuurzzruukPPxxk.',
        '.kxxxxPPkuurzzruukPPxxk.',
        '..kxxxPPkuurzzruukPPxk..',
        '..kxxxPPkuurzzruukPPxk..',
        '...kxxPPkuurzzruukPxk...',
        '...kxxPkkuuRzzRuukPxk...',
        '....kxPkkuuRzzRuukkxk...',
        '.....kkkkuuRzzRuukkk....',
        '........kuuRzzRuuk......',
        '........kkkkzzkkkk......',
        '...........kkkk.........',
        '........................',
      ],
    },

    /* ---- 5 уровень: лич (24×26) — скелет в мантии, посох с зелёным шаром ---- */
    lich: {
      rows: [
        '.....................kk.',
        '....................khhk',
        '....................khgk',
        '.......kkkkk.........kk.',
        '......keEEEEk........kNk',
        '.....keEEEEEEk.......kNk',
        '.....kEkiiiikEk......kNk',
        '....kEkiihiihiEk.....kNk',
        '....kEkiiiiiiiEk.....kNk',
        '....kEkkIkIkIkEk.....kNk',
        '....kEEkkIIIkkEk.....kNk',
        '...keEEEkkkkkEEuk....kNk',
        '..keEEEEEEEEEEEEukkkkkNk',
        '..keEEEEEEEEEEEEEEEiikNk',
        '..keEEEEEEEEEEEuukkkkkNk',
        '..keEEEEEEEEEEEuuk...kNk',
        '..keEEEEYYYYEEEuuk...kNk',
        '..keEEEEEEEEEEEuuk...kNk',
        '..kEEEEEEEEEEEuuuk...kNk',
        '..kEEEEEEEEEEuuuuk...kNk',
        '..kEEEEEEEEEuuuuuk...kNk',
        '..kEEEEEEEEuuuuuuk...kNk',
        '..kEEEEEEEuuuuuuuk...kNk',
        '..kEEEEEEuuuuuuuuk...kNk',
        '..kEEEEEuuuuuuuuuk...kNk',
        '..kkkkkkkkkkkkkkkk...kkk',
      ],
    },
    /* могучий лич: фиолетовая мантия, золотая корона на черепе */
    power_lich: {
      base: 'lich',
      tint: { E: 'P', e: 'p', u: 'x', Y: 'y', g: 'a' },
      extra: [
        [8, 4, 'y'], [10, 4, 'y'],
        [7, 5, 'y'], [8, 5, 'Y'], [9, 5, 'y'], [10, 5, 'Y'], [11, 5, 'y'],
      ],
    },

    /* ---- 6 уровень: чёрный рыцарь (28×28) — всадник на скелете-коне ---- */
    black_knight: {
      rows: [
        '..........kkkk..............',
        '.........kEuuuk.............',
        '........kEuuuuuk...k........',
        '........kuzzzzuk..klk.......',
        '........kuuuuuuk..klk.......',
        '.........kEuuEk...kek.......',
        '........kkEuuEkk..kek.......',
        '.......kEEEEEEEEk.kek.......',
        '......kEEuuuuuuEEkkek.......',
        '......kEuuuuuuuuEkkek.......',
        '......kEuuuuuuuuEkkyk.......',
        '......kEuuuuuuuuEEkuk.......',
        '......kEuuuuuuuuuEkkk.kkkkk.',
        '......kEEuuuuuuuuEkkkkiiiiik',
        '...kkkkEEEEEEEEEkiiiIiriiIIk',
        '..kiiIiIkuukIIIkiIiIkkkiIIkk',
        '.kiIiIiIkuukiIiIiIikk.kIIk..',
        '.kiiIiIikuukIiIiIIIk..kkkk..',
        '.kIiIiIikuukIiIiIIk.........',
        '..kIIIIIkkkkIIIIIk..........',
        '..kkIIkkkkkkkkIIkk..........',
        '..kIkkIk....kIkkIk..........',
        '..kIkkIk....kIkkIk..........',
        '..kIkkIk....kIkkIk..........',
        '..kIkkIk...kIk.kIk..........',
        '.kIk.kIk...kIk.kIk..........',
        '.kIk.kIk..kIk..kIk..........',
        'kkkk.kkk..kkk..kkk..........',
      ],
    },
    /* рыцарь смерти: чёрно-фиолетовые латы, красные глаза, пламя на клинке */
    dread_knight: {
      base: 'black_knight',
      tint: { u: 'P', E: 'x', z: 'r' },
      extra: [
        [18, 3, 'F'], [20, 4, 'f'], [18, 5, 'f'], [20, 6, 'F'], [18, 7, 'F'], [20, 8, 'f'],
        [19, 1, 'f'],
        [3, 26, 'F'], [6, 26, 'f'], [12, 26, 'F'], [16, 26, 'f'],
      ],
    },

    /* ---- 7 уровень: костяной дракон (32×29) — скелет с крыльями-мембранами ---- */
    bone_dragon: {
      rows: [
        '......kk........................',
        '.....kuuk.......................',
        '....kuEuuk......................',
        '....kuEuuukk....................',
        '...kuEuuuuuukk.......kkkkkk.....',
        '...kuEuuuuuuuukk....kiiiiiiik...',
        '..kuEuukuuuuuuukk..kiiIiiiiiik..',
        '..kuEuuukuuuuuuukkkiiIrIiiiiiik.',
        '..kuEuuuukuuuuuuukiIiIiiiiiiiiik',
        '.kuEuuuuuukuuuuuuukIiIkkIkIkIkIk',
        '.kuEuuuuuuukuuuuuuukIiIk.kkkkkkk',
        '.kuEuuuuuuuukuuuuuukIiIk.kiIiIik',
        '.kkuuuuuuuuuuuuuuuukIiIkkkkkkkk.',
        '..kkkkkkkkkkkkkkkkkkIiIk........',
        '.......kkkkkkkkkkkkkIiIIk.......',
        '.....kkIiIiIiIiIiIiIiIiIIk......',
        '....kIiIiIiIiIiIiIiIiIiIIIk.....',
        '...kIIiIiIiIiIiIiIiIiIiIIIk.....',
        '..kIIIiIiIiIiIiIiIiIiIIIIk......',
        '.kIIkIIIIIIIIIIIIIIIIIIIkk......',
        'kIIk.kIIkkkkkkkkkkkkkkIIk.......',
        'kIk..kIIk...........kIIk........',
        'kIk..kIkIk.........kIkIk........',
        'kIkk.kIkIk........kIkkIk........',
        '.kkIkkIkkIk.......kIk.kIk.......',
        '..kkkkkkkkkk.....kkIk.kIkk......',
        '.................kkkk.kkkk......',
        '................................',
        '................................',
      ],
    },
    /* призрачный дракон: зелёно-прозрачный, зелёное свечение */
    ghost_dragon: {
      base: 'bone_dragon',
      tint: { i: 'v', I: 'q', u: 'Q', E: 'q', r: 'h' },
      extra: [
        [24, 3, 'h'], [27, 3, 'h'], [31, 6, 'h'], [30, 13, 'h'],
        [4, 14, 'h'], [1, 17, 'h'], [8, 27, 'h'], [23, 27, 'h'],
      ],
    },
  });
})();
