/* ============================================================================
   view/sprites_cove_hd.js — существа Бухты в крупной сетке (unit 2), стиль Б:
   без контурной линии, тона кладёт рисунок. Собирается скриптом dev/proto/cove_hd.py.
   ========================================================================== */
(function () {
  'use strict';
  H3.Sprites.defineMany({
    /* нимфа: морская дева, мятная кожа, бирюзовые волосы, вместо ног гребень волны с пеной (40×46) */
    nymph: {
      hd: true, unit: 2,
      rows: [
        '...............CCCCCCCCC................',
        '.............CCCCCCCCCCCCC..............',
        '............CCCCCCCCCCCCCCC.............',
        '............CCCvvvvvvvvvCCC.............',
        '............CCvvvvvvvvvvvCC.............',
        '............CCvvwkvvvwkvvCC.............',
        '............CCvvwkvvvwkvvCC.............',
        '............CCvvvvvvvvvvvCC.............',
        '............CCCvvvvvvvvvCCC.............',
        '.............CCCvvvvvvvCCCC.............',
        '.............CCCCvvvvvCCCCC.............',
        '..............CCCCvvvCCCCCC.............',
        '...............CCCvvvCCCCCC.............',
        '..........vvvvvvvvvvvvvvvCCCC...........',
        '..........vvvvvvvvvvvvvvvCCCC...........',
        '.........vvvvvvvvvvvvvvvvvCCC...........',
        '........vvvvvvvCCCCCCCvvvvvvvCC.........',
        '........vvvvvvvCCCCCCCvvvvvvvCC.........',
        '.......vvvv.vvvCCCCCCCvvv.vvvvCC........',
        '.......vvvv.vvvCCCCCCCvvv.vvvvCC........',
        '.......vvvv.vvvCCCCCCCvvv.vvvvCC........',
        '.......vvvv.vvvvCCCCCvvvv.vvvv..........',
        '.......vvvv.vvvvvvvvvvvvv.vvvv..........',
        '.......vvvv.vvvvvvvvvvvvv.vvvv..........',
        '.......vvvv.vvvvvvvvvvvvv.vvvv..........',
        '.......vvvv..vvvvvvvvvvv..vvvv..........',
        '.......vvvv..vvvvvvvvvvv..vvvv..........',
        '........vv...vvvvvvvvvvv...vv...........',
        '.............vvvvvvvvvvv................',
        '............CCCvvvvvvvCCC...............',
        '...........CCCCCvvvvvCCCCC..............',
        '..........CCCCCCCCCCCCCCCCC.............',
        '..........CCCCCCCCCCCCCCCCC.............',
        '.........CLLLCCCCCCCCCCCCCCC............',
        '........CLLLLCCCCCCCCCCCLLLCC...........',
        '........CLLLLCCCCCCCCCCCLLLCC...........',
        '.......CCLLLCCCCCCCCCCCCLLLLCC..........',
        '......CCCCCCCCCCCCCCCCCCCLLLCCC.........',
        '......CCCCCCCCCCCCCCCCCCCLLLCCC.........',
        '....LLCCCCCCCCCCCCCCCCCCCCCCCCLL........',
        '...LLLLCCCCCCCCCCCCCCCCCCCCCCLLLL.......',
        '..LLLLLLCCCCCCCCCCCCCCCCCCCCLLLLLL......',
        '..LLLLLLLLCCCCCCCCCCCCCCCCLLLLLLLL......',
        '...LLLLLLLLLLLLLLLLLLLLLLLLLLLLLL.......',
        '....LLLLLLLLLLLLLLLLLLLLLLLLLLLL........',
        '......LLLLLLLLLLLLLLLLLLLLLLLL..........',
      ],
    },
    /* океанида: кожа в голубизну, волосы в глубокую бирюзу, жемчуг в волосах */
    oceanid: { base: 'nymph', tint: { v: 'c', C: 'Q' }, extra: [[14, 1, 'w'], [15, 1, 'w'], [14, 2, 'w'], [18, 0, 'w'], [19, 0, 'w'], [19, 1, 'w'], [24, 2, 'w'], [25, 2, 'w'], [25, 3, 'w']] },
    /* матрос: красная бандана, тельняшка, синие штаны, сабля (40×46) */
    crew_mate: {
      hd: true, unit: 2,
      rows: [
        '..............rrrrrrrrr.................',
        '............rrrrrrrrrrrrr...............',
        '...........rrrrrrrrrrrrrrr..............',
        '...........rrrrrrrrrrrrrrrrr..........lw',
        '...........rrsssssssssssrrrr.........lwl',
        '...........rssssssssssssrr..........lwl.',
        '...........rsssswkssswkssr.........lwl..',
        '...........rsssswkssswkssr.........lwl..',
        '............ssssssssssssss.........lwl..',
        '............ssssssssssssss.........lwl..',
        '.............sssssssssssS..........lwl..',
        '..............ssssssssss...........lwl..',
        '................ssssss.............lwl..',
        '...........llllllssssllllll........lwl..',
        '.........llllllllllllllllllll......lwl..',
        '.........llllllllllllllllllll......lwl..',
        '........bbbbbbbbbbbbbbbbbbbbbb.....lwl..',
        '.......bbbbbbbbbbbbbbbbbbbbbbbb....lwl..',
        '.......bbbbbbbbbbbbbbbbbbbbbbbb....lwl..',
        '......llll.llllllllllllllllll.llll.lwl..',
        '......llll.llllllllllllllllll.llll.lwl..',
        '......llll.llllllllllllllllll.llll.lwl..',
        '......bbbb.bbbbbbbbbbbbbbbbbb.bbbb.lwl..',
        '......bbbb.bbbbbbbbbbbbbbbbbb.bbbb.lwl..',
        '......bbbb.bbbbbbbbbbbbbbbbbb.bbbb.lwl..',
        '......ssss.llllllllllllllllll.ssss.lwl..',
        '......ssss.llllllllllllllllll.ssss.lwl..',
        '......ssss.llllllllllllllllll.ssss.lwl..',
        '......ssss.bbbbbbbbbbbbbbbbbb.ssss.lwl..',
        '......ssss.bbbbbbbbbbbbbbbbbb.ssssyyyyy.',
        '......ssss.bbbbbbbbbbbbbbbbbb.ssssyyyyy.',
        '......SSSS.llllllllllllllllll.SSSSSNN...',
        '......SSSS.llllllllllllllllll.SSSSSNN...',
        '......SSSS.llllllllllllllllll.SSSSSNN...',
        '......SSSS.DDDDDDDDDDDDDDDDDD.SSSSSNN...',
        '...........DDDDDDDyyDDDDDDDD............',
        '...........BBBBBBBBBBBBBBBBBB...........',
        '...........BBBBBBBBBBBBBBBBBB...........',
        '...........BBBBBBBB..BBBBBBBB...........',
        '...........BBBBBBBB..BBBBBBBB...........',
        '...........BBBBBBBB..BBBBBBBB...........',
        '...........BBBBBBBB..BBBBBBBB...........',
        '...........BBBBBBBB..BBBBBBBB...........',
        '..........nnnnnnnnn..nnnnnnnnn..........',
        '..........nnnnnnnnn..nnnnnnnnn..........',
        '..........NNNNNNNNN..NNNNNNNNN..........',
      ],
    },
    /* морской волк: бандана синяя, тельняшка в серую полосу, борода, серьга */
    seaman: { base: 'crew_mate', tint: { r: 'B', b: 'C' }, extra: [[13, 9, 'e'], [14, 9, 'e'], [15, 9, 'e'], [16, 9, 'e'], [17, 9, 'e'], [18, 9, 'e'], [19, 9, 'e'], [20, 9, 'e'], [21, 9, 'e'], [22, 9, 'e'], [23, 9, 'e'], [24, 9, 'e'], [13, 10, 'e'], [14, 10, 'e'], [15, 10, 'e'], [16, 10, 'e'], [17, 10, 'e'], [18, 10, 'e'], [19, 10, 'e'], [20, 10, 'e'], [21, 10, 'e'], [22, 10, 'e'], [23, 10, 'e'], [24, 10, 'e'], [13, 11, 'e'], [14, 11, 'e'], [15, 11, 'e'], [16, 11, 'e'], [17, 11, 'e'], [18, 11, 'e'], [19, 11, 'e'], [20, 11, 'e'], [21, 11, 'e'], [22, 11, 'e'], [23, 11, 'e'], [24, 11, 'e'], [15, 12, 'e'], [16, 12, 'e'], [17, 12, 'e'], [18, 12, 'e'], [19, 12, 'e'], [20, 12, 'e'], [21, 12, 'e'], [22, 12, 'e'], [11, 7, 'y'], [11, 8, 'y'], [10, 8, 'y']] },
    /* пират: треуголка, повязка на глазу, борода, красный камзол, пистолет вперёд, сабля к земле (48×52) */
    pirate: {
      hd: true, unit: 2,
      rows: [
        '..............DDDDDDDDDD........................',
        '............DDDDDDDDDDDDDD......................',
        '...........DDDDDDDDDDDDDDDD.....................',
        '..........DDDDDDDDDDDDDDDDDD....................',
        '.........DDDDDDDDDDDDDDDDDDDD...................',
        '......EEEEEEEEEEEEEEEEEEEEEEEEE.................',
        '.....EEEEEEEEEEEEEEEEEEEEEEEEEEE................',
        '..............ssssssssssss......................',
        '............zzzzzzssssssss......................',
        '.............sszzzsssswkss......................',
        '.............sszzzsssswkss......................',
        '.............ssssssssssssss.....................',
        '.............ssssssssssssss.....................',
        '..............DDDDDDDDDDDD......................',
        '...............DDDDDDDDDD.......................',
        '.................ssssss.........................',
        '............rrrrrrssssrrrrrrr...................',
        '..........rrrrrrrrrrrrrrrrrrrrrr................',
        '..........rrrrrrrrrrrrrrrrrrrrrr................',
        '.........rrrrrrrrrrrrrrrrrrrrrrrr...............',
        '.........rrrrrrrrrrrrrrrrrrrrrrrr...............',
        '........rrrrrrrrrrrrrrrrrrrrrrrrrrrrr...........',
        '........rrrrrrrrrrrrrrrrrrrrrrrrrrrrr...........',
        '.......rrrrr.rrrrrrrrrrrrrrrrrrrrrrrrssss.......',
        '.......rrrrr.rrrrrrrrrrrrrrrrrrrrrrrrssss.......',
        '.......rrrrr.rrrrrrrrrrrrrrrrrrrrrrrrsssseeeeeee',
        '.......rrrrr.rrrrrrrrrrrrrrrrrrrrrrrrsssseeeeeee',
        '.......rrrrr.rrrrrrrrrrrrrrrrrrrrrrrrssssEEEEEEE',
        '.......rrrrr.rrrrrrrrrrrrrrrrrrrrrrrrssssEEEEEEE',
        '.......rrrrr.rrrrrrrrrrrrrrrrrrr.....ssssnnn....',
        '.......rrrrr.rrrrrrrrrrrrrrrrrrr.....ssssnnn....',
        '.......rrrrr.rrrrrrrrrrrrrrrrrrr.........nn.....',
        '.......rrrrr.rrrrrrrrrrrrrrrrrrr.........nn.....',
        '.......rrrrr.rrrrrrrrrrrrrrrrrrr................',
        '.......rrrrr.rrrrrrrrrrrrrrrrrrr................',
        '.......rrrrr.rrrrrrrrrrrrrrrrrrr................',
        '.......rrrrr.rrrrrrrrrrrrrrrrrrr................',
        '.......ssss..yyyyyyyyyyyyyyyyyyy................',
        '.......ssss..yyyyyyyyyyyyyyyyyyy................',
        '.......ssss..YYYYYYYYYYYYYYYYYYY................',
        '.....yyyyyyy.rrrrrrrrrrrrrrrrrrr................',
        '.......lwl...rrrrrrrrrrrrrrrrrrr................',
        '.......lwl...tttttttt..ttttttttt................',
        '.......lwl...tttttttt..ttttttttt................',
        '.......lwl...tttttttt..ttttttttt................',
        '.......lwl...tttttttt..ttttttttt................',
        '.......lwl...DDDDDDDD..DDDDDDDDD................',
        '.......lwl...DDDDDDDD..DDDDDDDDD................',
        '.......lwl...DDDDDDDD..DDDDDDDDD................',
        '.......lwl...DDDDDDDD..DDDDDDDDD................',
        '.......lwl..DDDDDDDDD..DDDDDDDDDD...............',
        '.......lwl..DDDDDDDDD..DDDDDDDDDD...............',
      ],
    },
    /* корсар: камзол в малиновый, штаны серые, красное перо на треуголке */
    corsair: { base: 'pirate', tint: { r: 'M', t: 'e' }, extra: [[25, 0, 'r'], [26, 0, 'r'], [27, 0, 'r'], [28, 0, 'r'], [29, 0, 'r'], [30, 0, 'r'], [31, 0, 'r'], [24, 1, 'r'], [25, 1, 'r'], [26, 1, 'r'], [27, 1, 'r'], [28, 1, 'r'], [29, 1, 'r'], [30, 1, 'r'], [23, 2, 'r'], [24, 2, 'r'], [25, 2, 'r'], [26, 2, 'r'], [27, 2, 'r'], [23, 3, 'r'], [24, 3, 'r']] },
    /* штормовая птица: чайка-буревестник, крылья вверх, тёмные концы крыльев, вилка хвоста (композитор) (52×52) */
    stormbird: {
      hd: true, unit: 2,
      rows: [
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '.......EEEE..............................EEEE.......',
        '..EEEEEEEEEE............................EEEEEEEEEE..',
        'EEEEEEEEEEEEEE........................EEEEEEEEEEEEEE',
        'EEEEEEEEEEEEEE........................EEEEEEEEEEEEEE',
        'EEEEEEEEEEEEEEe......................eEEEEEEEEEEEEEE',
        'EEEEEEEEEEEEEEee....................eeEEEEEEEEEEEEEE',
        'EEEEEEEEEEEEEEeee..................eeeEEEEEEEEEEEEEE',
        'EEEEEEEEEEEEEEeeeee..............eeeeeEEEEEEEEEEEEEE',
        'EEEEEEEEEEEEEEeeeeee............eeeeeeEEEEEEEEEEEEEE',
        'EEEEEEEEEEEEEEeeeeeee..........eeeeeeeEEEEEEEEEEEEEE',
        'EEEEEEEEEEEEEEeeeeeeee........eeeeeeeeEEEEEEEEEEEEEE',
        'EEEEEEEEEEEEEeeeeeeeeee......lllleeeeeeEEEEEEEEEEEEE',
        'EEEEEEEEEEEEeeeeeeeeeeee...lllllllleeeeeEEEEEEEEEEEE',
        '..EEEEEEEEEeeeeeeeeeeeeee.lllllllllleeeeeEEEEEEEEE..',
        '....EEEEEEEeeeeeeeeeeeeee.llllllkkllooeeeEEEEEEE....',
        '.....EEEEEeeeeeeeeeeeeeee.llllllkklloooooeEEEEE.....',
        '.......EEeeeeeeeeeeeeeeee.llllllllllooooooooE.......',
        '........EEEeeeeeeeeeeeeelllllllllllloooooooE........',
        '.......EEEEEeeeeeeeeeelllllllllllllloooeEEEEE.......',
        '.......EEEEEEEeeeeeeelllllllllllllleeeEEEEEEE.......',
        '.......EEEEEEEeeeeeellllllllllllleeeeeEEEEEEE.......',
        '........EEEEEEEEeeeellllllllllllleeeEEEEEEEE........',
        '..........EEEEEEEeeellllllllllllleeEEEEEEE..........',
        '...........EEEEEEEEllllllllllllllEEEEEEEE...........',
        '............EEEEEEEllllllllllllllEEEEEEE............',
        '.............EEEEEEllllllllllllllEEEEEE.............',
        '...............EEEEllllllllllllllEEEE...............',
        '................EEEllllllllllllllEEE................',
        '.................EEllllllllllllllEE.................',
        '..................EEllllllllllllEE..................',
        '....................llllllllllll....................',
        '....................llllllllllll....................',
        '.....................llllllllll.....................',
        '......................llllllloo.....................',
        '.....................eeeeeeeeooo....................',
        '.....................eeeeeeeeoooo...................',
        '....................eeeeeeeeeeoooo..................',
        '....................eeeeeeeeeeeooo..................',
        '...................eeeeeeeeeeeeeoooo................',
        '...................eeeee....eeeeeo..o...............',
        '..................eeeeee....eeeeeo..................',
        '..................eeeeeee..eeeeeeeo.................',
        '....................................................',
        '....................................................',
      ],
    },
    /* айссид: оперение штормовое сине-серое, клюв и лапы огненные, искры на крыльях */
    ayssid: { base: 'stormbird', tint: { l: 'C', e: 'B', E: 'z', o: 'f' }, extra: [[5, 13, 'y'], [6, 14, 'y'], [5, 15, 'y'], [6, 16, 'y'], [7, 17, 'y'], [6, 18, 'y'], [47, 13, 'y'], [46, 14, 'y'], [47, 15, 'y'], [46, 16, 'y'], [45, 17, 'y'], [46, 18, 'y']] },
    /* морская ведьма: тёмно-бирюзовые волосы, фиолетовая мантия с волной по подолу, посох с жемчужиной (56×58) */
    sea_witch: {
      hd: true, unit: 2,
      rows: [
        '...................QQQQQQQQQQ...........................',
        '.................QQQQQQQQQQQQQQ.........................',
        '................QQQQQQQQQQQQQQQQ...............cccccc...',
        '................QQQQssssssssQQQQ..............cccccccc..',
        '...............QQQsssssssssssQQQ.............cccwwwwccc.',
        '...............QQQsssssssssssQQQ.............cccwwwwccc.',
        '...............QQQsswkssswkssQQQ.............cccwwwwccc.',
        '...............QQQsswkssswkssQQQ..............cccccccc..',
        '...............QQQsssssssssssQQQ...............cccccc...',
        '...............QQQsssssssssssQQQ.................NN.....',
        '...............QQQQsssssssssQQQQ.................NN.....',
        '...............QQQQQsssssssQQQQQ.................NN.....',
        '...............QQQQQQsssssQQQQQQ.................NN.....',
        '...............QQQQQ.sssss.QQQQQ.................NN.....',
        '..............QQQQQ.ppppppp.QQQQQ................NN.....',
        '.............QQQQQpppppppppppQQQQQ...............NN.....',
        '............QQQQpppppppppppppppQQQQ..............NN.....',
        '...........QQQQppppppppppppppppppQQQQ............NN.....',
        '...........QQQpppppppppppppppppppppQQQ...........NN.....',
        '...........QQppppppppppppppppppppppppQQ..........NN.....',
        '..........ppppppppppppppppppppppppppppp..........NN.....',
        '..........ppppppppppppppppppppppppppppp..........NN.....',
        '..........pppp.pppppppppppppppppppppppppp........NN.....',
        '..........pppp.pppppppppppppppppppppppppp........NN.....',
        '..........pppp.ppppppppppppppppppppppppppppssss..NN.....',
        '..........pppp.ppppppppppppppppppppppppppppssss..NN.....',
        '..........pppp.ppppppppppppppppppppppppppppssss..NN.....',
        '..........pppp.ppppppppppppppppppppppppppppssss..NN.....',
        '..........pppp.ppppppppppppppppppppppppppppssss..NN.....',
        '..........pppp.ppppppppppppppppppppppppppppssss..NN.....',
        '..........pppp.pppppppppppppppppppppppp....ssss..NN.....',
        '..........pppp.pppppppppppppppppppppppp....ssss..NN.....',
        '..........pppp.pppppppppppppppppppppppp..........NN.....',
        '..........pppp.pppppppppppppppppppppppp..........NN.....',
        '..........pppp.pppppppppppppppppppppppp..........NN.....',
        '..........pppp.pppppppppppppppppppppppp..........NN.....',
        '..........ssss.yyyyyyyyyyyyyyyyyyyyyyyy..........NN.....',
        '..........ssss.YYYYYYYYYYYYYYYYYYYYYYYY..........NN.....',
        '...............pppppppppppppppppppppppp..........NN.....',
        '...............pppppppppppppppppppppppp..........NN.....',
        '..............pppppppppppppppppppppppppp.........NN.....',
        '..............pppppppppppppppppppppppppp.........NN.....',
        '..............pppppppppppppppppppppppppp.........NN.....',
        '..............pppppppppppppppppppppppppp.........NN.....',
        '.............pppppppppppppppppppppppppppp........NN.....',
        '.............pppppppppppppppppppppppppppp........NN.....',
        '.............pppppppppppppppppppppppppppp........NN.....',
        '............pppppppppppppppppppppppppppppp.......NN.....',
        '............ppccppccppccppccppccppccppccpp.......NN.....',
        '...........pppccccccccccccccccccccccccccppp......NN.....',
        '...........pppppccppccppccppccppccppccppppp......NN.....',
        '..........pppppppppppppppppppppppppppppppppp.....NN.....',
        '..........pppppppppppppppppppppppppppppppppp.....NN.....',
        '.........PPpppppppppppppppppppppppppppppppPP.....NN.....',
        '.........PPPPpppppppppppppppppppppppppppPPPP.....NN.....',
        '.........PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.....NN.....',
        '.........PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.....NN.....',
        '.........PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.....NN.....',
      ],
    },
    /* колдунья: мантия в синь, волосы чёрные, жемчужина в сиреневом свете, золотая диадема */
    sorceress: { base: 'sea_witch', tint: { p: 'b', P: 'B', c: 'A', Q: 'z' }, extra: [[19, 2, 'y'], [20, 2, 'y'], [21, 2, 'y'], [22, 2, 'y'], [23, 2, 'y'], [24, 2, 'y'], [25, 2, 'y'], [26, 2, 'y'], [27, 2, 'y'], [28, 2, 'y'], [20, 1, 'y'], [23, 1, 'y'], [24, 1, 'y'], [27, 1, 'y']] },
    /* никс: тритон-воин, мятная кожа, гребень-плавник, чешуйчатые латы, трезубец и щит-раковина (56×60) */
    nix: {
      hd: true, unit: 2,
      rows: [
        '.......................CCC...............ll.............',
        '.....................CCCCCCC.........ll..ll..ll.........',
        '....................CCCCCCCCC........ll..ll..ll.........',
        '...................CCCCCCCCCCC.......ll..ll..ll.........',
        '..................CCvvvvvvvvvCC......ll..ll..ll.........',
        '..................CvvvvvvvvvvvC......llllllllll.........',
        '..................vvvvvvvvvvvvv..........ee.............',
        '..................vvwkvvvvvwkvv..........ee.............',
        '..................vvwkvvvvvwkvv..........ee.............',
        '..................vCCvvvvvvvCCv..........ee.............',
        '..................vCCvvvvvvvCCv..........ee.............',
        '...................vvvvvvvvvvv...........ee.............',
        '....................vvvvvvvvv............ee.............',
        '......................vvvvv..............ee.............',
        '..............qqqqqqqqqvvvvqqqqqqqqq.....ee.............',
        '............qqqqqqqqqqqqqqqqqqqqqqqqq....ee.............',
        '............qqqqqqqqqqqqqqqqqqqqqqqqq....ee.............',
        '...........qqqqqqqqqqqqqqqqqqqqqqqqqqq...ee.............',
        '...........qqqqqqqqqqqqqqqqqqqqqqqqqqq...ee.............',
        '........I.qqqqqqqqqqqqqqqqqqqqqqqqqqqqq..ee.............',
        '........I.qqqqqqqqqqqqqqqqqqqqqqqqqqqqq..ee.............',
        '......IIIIIqqqq.qQQqqQQqqQQqqQQq.qqqqq...ee.............',
        '......IIIIIqqqq.qQQqqQQqqQQqqQQq.qqqqq...ee.............',
        '.....IIiiiIIqqq.QqqQQqqQQqqQQqqQ.qqqqq...ee.............',
        '.....IIiiiIIqqq.QqqQQqqQQqqQQqqQ.qqqqq...ee.............',
        '....IIiiiiiIIqq.qQQqqQQqqQQqqQQq.qqqqq...ee.............',
        '....IIiiiiiIIqq.qQQqqQQqqQQqqQQq.qqqqq...ee.............',
        '...IIiiiiiiiIIq.QqqQQqqQQqqQQqqQ.qqqqq...ee.............',
        '...IIiiiiiiiIIq.QqqQQqqQQqqQQqqQ.qqqqq...ee.............',
        '...IiiiiiiiiiIq.qQQqqQQqqQQqqQQq.qqqqq...ee.............',
        '...IiiiiiiiiiIq.qQQqqQQqqQQqqQQq.qqqqq...ee.............',
        '...IiiiiiiiiiIq.QqqQQqqQQqqQQqqQ.qqqqq...ee.............',
        '...IiiiiiiiiiIq.QqqQQqqQQqqQQqqQ.qqqqq...ee.............',
        '...IiiiCCCiiiIv.qQQqqQQqqQQqqQQq.vvvvvvvvee.............',
        '...IiiiCCCiiiIv.qQQqqQQqqQQqqQQq.vvvvvvvvee.............',
        '..IIiiiCCCiiiII.QqqQQqqQQqqQQqqQ.vvvvvvvvee.............',
        '..IIiiiCCCiiiII.QqqQQqqQQqqQQqqQ.vvvvvvvvee.............',
        '...IiiiCCCiiiIv.qQQqqQQqqQQqqQQq.vvvvvvvvee.............',
        '...IiiiCCCiiiIv.qQQqqQQqqQQqqQQq.vvvvvvvvee.............',
        '...IiiiiiiiiiIv.QqqQQqqQQqqQQqqQ.vvvvvvvvee.............',
        '...IiiiiiiiiiIv.QqqQQqqQQqqQQqqQ.vvvvvvvvee.............',
        '...IiiiiiiiiiIv.qqqqqqqqqqqqqqqq.vvvvv...ee.............',
        '...IiiiiiiiiiIv.qqqqqqqqqqqqqqqq.vvvvv...ee.............',
        '...IIiiiiiiiII..QQQQQQQQQQQQQQQQ.........ee.............',
        '....IIiiiiiII...qqqqqqqqqqqqqqqq.........ee.............',
        '.....IIiiiII....qqqqqqqqqqqqqqqq.........ee.............',
        '.....IIiiiII....qqqqqqqqqqqqqqqq.........ee.............',
        '......IIIII.....qqqqqqq..qqqqqqq.........ee.............',
        '......IIIII.....qqqqqqq..qqqqqqq.........ee.............',
        '................qqqqqqq..qqqqqqq.........ee.............',
        '................qqqqqqq..qqqqqqq.........ee.............',
        '................qqqqqqq..qqqqqqq.........ee.............',
        '................qqqqqqq..qqqqqqq.........ee.............',
        '................qqqqqqq..qqqqqqq.........ee.............',
        '................qqqqqqq..qqqqqqq.........ee.............',
        '................qqqqqqq..qqqqqqq.........ee.............',
        '................qqqqqqq..qqqqqqq.........ee.............',
        '...............vvvvvvvv..vvvvvvvv........ee.............',
        '..............vvvvvvvvv..vvvvvvvvv.......ee.............',
        '.............CCCCCCCCCC..CCCCCCCCCC......ee.............',
      ],
    },
    /* никс-воин: латы чернеют, гребень и плавники оранжевые, трезубец золотой */
    nix_warrior: { base: 'nix', tint: { q: 'u', Q: 'z', e: 'Y', l: 'y', C: 'o' } },
    /* морской змей: тело кольцами, тёмная задняя петля, голова с гребнем и раскрытой пастью (композитор) (64×60) */
    sea_serpent: {
      hd: true, unit: 2,
      rows: [
        '............................................oooooooooo..........',
        '........................................oooooooooooooo..........',
        '........................................oooooooooooooo..........',
        '........................................ooooooooooooo...........',
        '..................................oo....oooooooqooqqqq..........',
        '.................................oooo....oo.qoqqqqqqqqqq........',
        '..............................ooooooo....qqqqqqqqqqqqqqqq.......',
        '............................ooooooooo.qvvvqqqqqqqqqqyyqqqq......',
        '.........................oooooooooooqvvvvqqqqqqqqqqqykqqqqq.....',
        '........................ooooooooo.qvvvvvvqqqqqqqqqqqqqqqqqq.....',
        '........................ooooooooqvvvvvvvqqqqqqqqqqqqqqqqqqq.....',
        '........................oooooovvvvvvvqqqqqqqqqqqqqqqqqqqqqq.....',
        '........................oooqvvvvvvvqqqqqqqqqqqqqqqqqqRwRRw..w...',
        '..........................qvvvvvvqqqqqqqqqqqqqqqqqQQQRRRRR......',
        '..........................vvvvvqqqqqqqqqqqqqqqqqqqQQQQwQQwQQw...',
        '.........................vvvvqqqqqqqqqqqqqq...qqqqqQQQQQQQQQQQ..',
        '........................qvvvqqqqqqqqqqqq...........QQQQQQQ......',
        '........................vvvvqqqqqqqqqq.............QQQ..........',
        '.......................qvvvqqqqqqqqq............................',
        '.......................vvvqqqqqqq...............................',
        '......................vvvvqqqqqqq...............................',
        '.....................qvvvqqqqqqq................................',
        '.....................vvvvqqqqqq.................................',
        '....................qvvvqqqqqqq.................................',
        '....................qvvvqqqqqq..................................',
        '....................qvvvvqqqqq..................................',
        '....................qqvvvvqqqq..................................',
        '....................qqqvvvqqqqq.................................',
        '....................qqqqvvvqqqq.................................',
        '.....................qqqvvvvqqqq................................',
        '......................qqqvvvvqqqqQQQQQQQQQQQQQQQQQQQQ...........',
        '.......................qqqvvvqqqqqQQQQQQQQQQQQQQQQQQQQ..........',
        '.......................qqqqvvqqqqqQQQQQQQQQQQQQQQQQQQQ..........',
        '........................qqqqqqqqqqQQQQQQQQQQQQQQQQQQQQQ.........',
        '.........................qqqqqqqqqQQQQQQQQQQQQQQQQQQQQQQ........',
        '..........................qqqqqqqqQQQQQQQQQQQQQQQQQQQQQQQ.......',
        '..........................qqqqqqqqQQQQQQQQQQQQQQQQQQQQQQQ.......',
        '...........................qqqqqqQQQQQQQQQQQQQQQQQQQQQQQQQ......',
        '................................................QQQQQQQQQQQ.....',
        '................................................QQQQQQQQQQQ.....',
        '.................................................QQQQQQQQQQQ....',
        '..................................................QQQQQQQQQQQ...',
        '..................................................QQQQQQQQQQQ...',
        '.................................................QQQQQQQQQQQQ...',
        '................................................QQQQQQQQQQQQQ...',
        '..............................................QQQQQQQQQQQQQQQ...',
        '............................................QQQQQQQQQQQQQQQQQ...',
        '............qqqqq........................qqqqqQQQQQQQQQQQQQQ....',
        '.........qqvvvvvvvvqqq..............qqqqvvvvvqqqQQQQQQQQQQ......',
        '......qqvvvvvvvvvvvvvvvvvqqq....qqqvvvvvvvvvvqqqQQQQQQQQQ.......',
        '...qqvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvqqqqqQQQQQQ.........',
        'qqvvvvvvvvvqqqqqqqqvvvvvvvvvvvvvvvvvvvvqqqqqqqqqqQQQQ...........',
        'qvvvvvvvqqqqqqqqqqqqqqqqqvvvvvvvvvqqqqqqqqqqqqqqqQQQ............',
        'qvvvvqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQ..............',
        'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq................',
        'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq................',
        'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq..................',
        'qqqqqqqqqqqqq...qqqqqqqqqqqqqqqqqqqqqqqqqq......................',
        'qqqqqqqqqq............qqqqqqqqqqqqqqqq..........................',
        'qqqqqqq....................qqqqqq...............................',
      ],
    },
    /* хаспид: чешуя в малахит, петля чёрная, гребень розовый, ядовитые шипы по спине */
    haspid: { base: 'sea_serpent', tint: { q: 'G', Q: 'z', v: 'H', o: 'm' }, extra: [[7, 48, 'h'], [8, 48, 'h'], [9, 48, 'h'], [8, 47, 'h'], [8, 46, 'h'], [13, 46, 'h'], [14, 46, 'h'], [15, 46, 'h'], [14, 45, 'h'], [14, 44, 'h'], [19, 47, 'h'], [20, 47, 'h'], [21, 47, 'h'], [20, 46, 'h'], [20, 45, 'h'], [25, 48, 'h'], [26, 48, 'h'], [27, 48, 'h'], [26, 47, 'h'], [26, 46, 'h'], [31, 48, 'h'], [32, 48, 'h'], [33, 48, 'h'], [32, 47, 'h'], [32, 46, 'h'], [37, 47, 'h'], [38, 47, 'h'], [39, 47, 'h'], [38, 46, 'h'], [38, 45, 'h']] },
  });
})();
