/* ============================================================================
   view/sprites_icons.js — иконки интерфейса (ресурсы, навыки, заклинания,
   артефакты). Формат см. docs/sprite-guide.md.
     ic_*  12×12  ресурсы / первичные навыки / кнопки боя и меню (фон прозрачный)
     sk_*  16×16  вторичные навыки
     sp_*  16×16  заклинания — рамка цветом школы + символ (helper `framed`)
     art_* 16×16  артефакты
   Подключать после js/view/sprites.js.
   ========================================================================== */
(function () {
  'use strict';

  /* ---------- helper: 16×16 рамка школы магии + 12×12 символ внутри ---------- */
  // col — буква палитры для рамки; sym — 12 строк по 12 символов ('.' = фон 'u').
  function framed(col, sym) {
    const rows = [];
    for (let y = 0; y < 16; y++) {
      let r = '';
      for (let x = 0; x < 16; x++) {
        if (y === 0 || y === 15 || x === 0 || x === 15) r += 'k';
        else if (y === 1 || y === 14 || x === 1 || x === 14) r += col;
        else { const ch = sym[y - 2][x - 2]; r += ch === '.' ? 'u' : ch; }
      }
      rows.push(r);
    }
    return { rows };
  }

  /* ======================= ic_* 12×12 ======================= */
  const IC = {
    /* --- ресурсы --- */
    ic_gold: { rows: [
      '............',
      '...kkkkkk...',
      '..kywyyyyk..',
      '..kyyyyyYk..',
      '..kkkkkkkk..',
      '..kyyyyyyk..',
      '..kYYyyYYk..',
      '..kkkkkkkk..',
      '..kyyyyyyk..',
      '..kYYYYYYk..',
      '...kkkkkk...',
      '............',
    ] },
    ic_wood: { rows: [
      '............',
      '............',
      '....kkkkk...',
      '...kTnnnnk..',
      '...kNnnnNk..',
      '..kkkkkkkkk.',
      '.kTnnnkTnnnk',
      '.kNnnNkNnnNk',
      '.kkkkkkkkkkk',
      '............',
      '............',
      '............',
    ] },
    ic_ore: { rows: [
      '............',
      '............',
      '.....kkk....',
      '....kleek...',
      '...kleeeek..',
      '..kkleeEEk..',
      '.kleekkkkkk.',
      '.kleeekleeek',
      '.keeEEkeeEEk',
      '.kkkkkkkkkkk',
      '............',
      '............',
    ] },
    ic_mercury: { rows: [
      '....kkkk....',
      '....kcck....',
      '.....kk.....',
      '.....kk.....',
      '....kcck....',
      '...kclllck..',
      '..kllwlllik.',
      '..klllllllk.',
      '..kleeeeelk.',
      '...keeeeek..',
      '....kkkkk...',
      '............',
    ] },
    ic_sulfur: { rows: [
      '............',
      '............',
      '............',
      '.....kk.....',
      '....kyyk....',
      '...kyyyYk...',
      '..kyyyyYYk..',
      '.kyyyyYYYYk.',
      '.kyYYYYYYYk.',
      '.kkkkkkkkkk.',
      '............',
      '............',
    ] },
    ic_crystal: { rows: [
      '.....kk.....',
      '....kwmk....',
      '....kwmk....',
      '...kmwmmk...',
      '...kmmmMk...',
      '..kmmmmMk...',
      '..kmmmMMMk..',
      '..kmmMMMMk..',
      '...kMMMMk...',
      '....kkkk....',
      '............',
      '............',
    ] },
    ic_gems: { rows: [
      '............',
      '............',
      '...kkkkkk...',
      '..kwgggggk..',
      '.kgwggggGGk.',
      '.kgggggGGGk.',
      '..kgggGGGk..',
      '...kggGGk...',
      '....kgGk....',
      '.....kk.....',
      '............',
      '............',
    ] },
    /* --- первичные навыки --- */
    ic_att: { rows: [
      '.........kk.',
      '........klwk',
      '.......klek.',
      '......klek..',
      '.....klek...',
      '.kk.klek....',
      '..kkyek.....',
      '...kyyk.....',
      '..kykkyk....',
      '.kNk..kk....',
      'kNk.........',
      'kk..........',
    ] },
    ic_def: { rows: [
      '............',
      '.kkkkkkkkkk.',
      '.kbwbbbbbbk.',
      '.kbbbbybbbk.',
      '.kbbbyyybbk.',
      '.kbbbbybbbk.',
      '..kBbbbbBk..',
      '..kBBbbBBk..',
      '...kBBBBk...',
      '....kBBk....',
      '.....kk.....',
      '............',
    ] },
    ic_pow: { rows: [
      '......k.....',
      '...k.kFk.k..',
      '...kkFfFkk..',
      '..kFFffFFk..',
      '..kFfwffFk..',
      '.kFffwfffFk.',
      '.kFfffffFFk.',
      '.kFFffFFFFk.',
      '..kFFFFFFk..',
      '...kkkkkk...',
      '............',
      '............',
    ] },
    ic_kno: { rows: [
      '............',
      '..kkkkkkkk..',
      '.kRrrrrrrrk.',
      '.kRrryyrrrk.',
      '.kRryyyyrrk.',
      '.kRrrykrrrk.',
      '.kRrrrrrrrk.',
      '.kRrrrrrrrk.',
      '.kkkkkkkkkk.',
      '..kiiiiiik..',
      '..kkkkkkkk..',
      '............',
    ] },
    /* --- прочие --- */
    ic_morale: { rows: [
      '............',
      '............',
      '.kk......kk.',
      '.kykk..kkyk.',
      '..kyykkyyk..',
      '...kyyyyk...',
      '...kyoyyk...',
      '....kyyk....',
      '.....kyk....',
      '.....kk.....',
      '............',
      '............',
    ] },
    ic_luck: { rows: [
      '............',
      '...kk..kk...',
      '..kggkkggk..',
      '..kgGgGgGk..',
      '...kkGgkk...',
      '..kgGgGgGk..',
      '..kggkkgGk..',
      '...kk.kGk...',
      '......kGk...',
      '.....kkk....',
      '............',
      '............',
    ] },
    ic_move: { rows: [
      '............',
      '....kkkk....',
      '....kTnk....',
      '....knnk....',
      '....knnk....',
      '....knnNk...',
      '....knnnNk..',
      '..kknnnnNk..',
      '.kNnnnnNNk..',
      '.kNNNNNNNk..',
      '.kkkkkkkkk..',
      '............',
    ] },
    ic_mana: { rows: [
      '............',
      '.....kk.....',
      '.....kbk....',
      '....kcbk....',
      '....kcbbk...',
      '...kcbbbbk..',
      '...kcbbbbk..',
      '..kcbbbbBk..',
      '..kbbbbBBk..',
      '...kbbBBk...',
      '....kkkk....',
      '............',
    ] },
    ic_xp: { rows: [
      '.....kk.....',
      '.....kyk....',
      '....kyyk....',
      '.kkkkyyykkk.',
      '.kyyyyyyyyk.',
      '..kyyyyyyk..',
      '...kyyyyk...',
      '...kyyyyk...',
      '..kyykkyyk..',
      '..kyk..kyk..',
      '..kk....kk..',
      '............',
    ] },
    ic_day: { rows: [
      '.....k......',
      '..k..k..k...',
      '...k.k.k....',
      '....kkkk....',
      '...kyyyyk...',
      'kkkyywyyykkk',
      '...kyyyyyk..',
      '....kkkk....',
      '...k.k.k....',
      '..k..k..k...',
      '.....k......',
      '............',
    ] },
    ic_hero: { rows: [
      '............',
      '....kkkk....',
      '...keeeek...',
      '..kellleek..',
      '..keeeeeek..',
      '..kkkkkkkk..',
      '..kEk..kEk..',
      '..kEkkkkEk..',
      '..kEEkkEEk..',
      '...kk..kk...',
      '............',
      '............',
    ] },
    ic_town: { rows: [
      '..k.k..k.k..',
      '..kkkkkkkk..',
      '..kllleeek..',
      '..klleeeek..',
      '...keeeek...',
      '...kekkek...',
      '...kekkek...',
      '...keeeek...',
      '..kkeeeekk..',
      '..keeeeeek..',
      '..kkkkkkkk..',
      '............',
    ] },
    ic_sound: { rows: [
      '............',
      '.....kkkk...',
      '.....kwwk...',
      '.....kwkk...',
      '.....kwk....',
      '.....kwk....',
      '.....kwk....',
      '..kkkkwk....',
      '.kllllwk....',
      '.klllkk.....',
      '..kkk.......',
      '............',
    ] },
    ic_save: { rows: [
      '............',
      '..kkkkkkkk..',
      '.kTiiiiiiTk.',
      '..kiiiiiiik.',
      '..kiuuuuiik.',
      '..kiiiiiiik.',
      '..kiuuuiiik.',
      '..kiiiiiiik.',
      '.kTiiiiiiTk.',
      '..kkkkkkkk..',
      '............',
      '............',
    ] },
    ic_end_turn: { rows: [
      '.kkkkkkkkkk.',
      '..kyyyyyyk..',
      '..kYyyyyYk..',
      '...kyyyyk...',
      '....kyyk....',
      '.....kk.....',
      '....klyk....',
      '...kllylk...',
      '..klllylik..',
      '..kyyyyyyk..',
      '.kkkkkkkkkk.',
      '............',
    ] },
    ic_spellbook: { rows: [
      '............',
      '..kkkkkkkk..',
      '.kPpppppppk.',
      '.kPppykpppk.',
      '.kPkyyyyppk.',
      '.kPppyyppPk.',
      '.kPpykkyppk.',
      '.kPpppppppk.',
      '.kkkkkkkkkk.',
      '..kiiiiiik..',
      '..kkkkkkkk..',
      '............',
    ] },
    ic_wait: { rows: [
      '............',
      '....kkkk....',
      '...kllllk...',
      '..kllkkllk..',
      '.klllkklllk.',
      '.klllkkkllk.',
      '.kllllllllk.',
      '.kllllllllk.',
      '..kllllllk..',
      '...kllllk...',
      '....kkkk....',
      '............',
    ] },
    ic_defend: { rows: [
      '............',
      '.kkkkkkkkkk.',
      '.kbwbbybbbbk',
      '.kbbbbybbbk.',
      '.kbbbbybbbk.',
      '.kbbyyyyybk.',
      '..kBbyyybBk.',
      '..kBBbybBk..',
      '...kBBBBk...',
      '....kBBk....',
      '.....kk.....',
      '............',
    ] },
    ic_auto: { rows: [
      '....kk.kk...',
      '...kekkeek..',
      '.kkkeeeeekk.',
      '.keeekkkeeek',
      '..kekleekek.',
      '..kekeeekek.',
      '.keeekkkeeek',
      '.kkkeeeeekk.',
      '...keekkek..',
      '....kk.kk...',
      '............',
      '............',
    ] },
    ic_flee: { rows: [
      '............',
      '.......kk...',
      '......kssk..',
      '.......kk...',
      '..kk..krrk..',
      '..kkkkrrrkk.',
      '.....krrkk..',
      '....krkrk...',
      '...kNk.kNk..',
      '..kNk...kNk.',
      '..kk.....kk.',
      '............',
    ] },
    ic_surrender: { rows: [
      '...kk.......',
      '...kNkkkkk..',
      '...kNkwwwlk.',
      '...kNkwwwwlk',
      '...kNkwwwlk.',
      '...kNkkkkk..',
      '...kNk......',
      '...kNk......',
      '...kNk......',
      '...kNk......',
      '...kkk......',
      '............',
    ] },
    ic_skull: { rows: [
      '............',
      '...kkkkkk...',
      '..kiiiiiik..',
      '.kiiiiiiiik.',
      '.kikkiikkik.',
      '.kikkiikkik.',
      '.kiiiikiiik.',
      '..kiiiiiik..',
      '...kikikik..',
      '...kkkkkk...',
      '............',
      '............',
    ] },
    ic_check: { rows: [
      '............',
      '.........kk.',
      '........kgGk',
      '.......kggk.',
      '......kggk..',
      '.kk..kggk...',
      'kggkkggk....',
      'kGgggGk.....',
      '.kGggk......',
      '..kGk.......',
      '...k........',
      '............',
    ] },
    ic_cross: { rows: [
      '............',
      '.kk......kk.',
      'krrk....krrk',
      'kRrrk..krrRk',
      '.kRrrkkrrRk.',
      '..kRrrrrRk..',
      '..kRrrrrRk..',
      '.kRrrkkrrRk.',
      'kRrrk..krrRk',
      'kRRk....kRRk',
      '.kk......kk.',
      '............',
    ] },
    ic_arrow_r: { rows: [
      '............',
      '............',
      '......kk....',
      '......kyk...',
      '.kkkkkkyyk..',
      '.kyyyyyyyyk.',
      '.kyyyyyyyyYk',
      '.kYYYYYYYYk.',
      '.kkkkkkYYk..',
      '......kYk...',
      '......kk....',
      '............',
    ] },
    ic_flag: { rows: [
      '..kk........',
      '..kNkkkkk...',
      '..kNkrrrrk..',
      '..kNkrrrrrk.',
      '..kNkrrrrrrk',
      '..kNkrrrrrk.',
      '..kNkRRRRk..',
      '..kNkkkkk...',
      '..kNk.......',
      '..kNk.......',
      '..kNk.......',
      '..kkk.......',
    ] },
    ic_shots: { rows: [
      '............',
      '.........kk.',
      '........kwwk',
      '.......kwwek',
      '......keek.k',
      '.....kNNk...',
      '....kNNk....',
      '...kNNk.....',
      '..krrk......',
      '.krrkk......',
      '.kkrk.......',
      '..kk........',
    ] },
    ic_speed: { rows: [
      '............',
      '.......kkk..',
      '.....kkwwwk.',
      '...kkwwwlwk.',
      '..kwwwlwwlk.',
      '.kwwlwwlwlk.',
      '.klwwlwlwlk.',
      '..kkllllllk.',
      '....kkllllk.',
      '......kkllk.',
      '........kkk.',
      '............',
    ] },
    ic_hp: { rows: [
      '............',
      '..kkk..kkk..',
      '.krwrkkrrrk.',
      'krwrrrrrrrRk',
      'krrrrrrrrrRk',
      'krrrrrrrrRRk',
      '.krrrrrrRRk.',
      '..krrrrRRk..',
      '...krrRRk...',
      '....kRRk....',
      '.....kk.....',
      '............',
    ] },
  };

  /* ======================= sk_* 16×16 ======================= */
  const SK = {
    sk_logistics: { rows: [
      '................',
      '....kkkk........',
      '...kwwlwk.......',
      '..kwwlwlwk......',
      '.kwlwlwlwlk.....',
      '..kkllllllk.....',
      '....kkkkTnk.....',
      '.......knnk.....',
      '.......knnk.....',
      '.......knnNk....',
      '.......knnnNk...',
      '....kkknnnnNk...',
      '...kNnnnnnNNk...',
      '...kNNNNNNNNk...',
      '...kkkkkkkkkk...',
      '................',
    ] },
    sk_pathfinding: { rows: [
      '................',
      '.....kkkkkk.....',
      '....kyyyyyyk....',
      '...kyllllllyk...',
      '..kylllkllllyk..',
      '..kyllkrkllyyk..',
      '.kylllkrrkllyk..',
      '.kylkkkrrkkklyk.',
      '.kylllkwwkllyk..',
      '..kyllkwkllyyk..',
      '..kylllkllllyk..',
      '...kyllllllyk...',
      '....kyyyyyyk....',
      '.....kkkkkk.....',
      '................',
      '................',
    ] },
    sk_scouting: { rows: [
      '................',
      '............kkk.',
      '...........kcck.',
      '..........kcckk.',
      '.........knnkk..',
      '........knnnk...',
      '.......kNnnk....',
      '......kNNnk.....',
      '.....kNNnk......',
      '....kkNnk.......',
      '...kyykk........',
      '..kyYyk.........',
      '.kyYyk..........',
      '.kYYk...........',
      '.kkk............',
      '................',
    ] },
    sk_archery: { rows: [
      '..k.............',
      '.kNk............',
      '.kNNk...........',
      '..kNNk..........',
      '...kNNk.........',
      '..k.kNNk.....kk.',
      '..k..kNNk...kwwk',
      '..k...kNNk.kwwek',
      '..kkkkkkkkkeek.k',
      '..k...kNNkeek...',
      '..k..kNNkeek....',
      '..k.kNNk.kk.....',
      '...kNNk.........',
      '..kNNk..........',
      '.kNk............',
      '..k.............',
    ] },
    sk_offense: { rows: [
      '.kk..........kk.',
      'kwlk........klwk',
      'kllek......kellk',
      '.kllek....kellk.',
      '..kllek..kellk..',
      '...kllekkellk...',
      '....klleellk....',
      '.....kleelk.....',
      '.....kleelk.....',
      '....kllekllek...',
      '...kllek..kellk.',
      '..kyyek....keyyk',
      '.kykkk......kkkyk',
      '.kNk..........kNk',
      '.kk............kk',
      '................',
    ] },
    sk_armorer: { rows: [
      '................',
      '..kkkk....kkkk..',
      '.keeeek..keeeek.',
      '.kelleekkeeeeek.',
      '.kellleeeeeeEek.',
      '.keeleeeeeeeEek.',
      '..keeeeeeeeEEk..',
      '..keeeeyeeeEEk..',
      '..keeeyyyeeEEk..',
      '..kEeeeyeeEEEk..',
      '..kEEeeeeeEEEk..',
      '..kEEEeeeEEEEk..',
      '...kEEEEEEEEk...',
      '....kkkkkkkk....',
      '................',
      '................',
    ] },
    sk_wisdom: { rows: [
      '................',
      '................',
      '................',
      '.kkkkkkk.kkkkkk.',
      'kiiiiiiikiiiiiik',
      'kiuuuuiikiuuuuik',
      'kiiiiiiikiiiiiik',
      'kiuuuiiikiuuuiik',
      'kiiiiiiikiiiiiik',
      'kiuuuuiikiiuuuik',
      'kiiiiiiikiiiiiik',
      'kIIIIIIIkIIIIIIk',
      'kkkkkkkkkkkkkkkk',
      '.kRRRRRRRRRRRRk.',
      '..kkkkkkkkkkkk..',
      '................',
    ] },
    sk_air: { rows: [
      '................',
      '......kkkk......',
      '....kkccwwkk....',
      '...kccwkkkcck...',
      '..kcwkk...kcck..',
      '..kckk..kk.kck..',
      '.kcck..kcwk.kck.',
      '.kck..kccwck.kk.',
      '.kck..kckkck..k.',
      '.kcck.kkckck....',
      '..kck...kck.....',
      '..kcck.kck......',
      '...kccckk.......',
      '....kkkk........',
      '................',
      '................',
    ] },
    sk_earth: { rows: [
      '................',
      '................',
      '.......kk.......',
      '......kllk......',
      '.....kltttk.....',
      '....kltnnnnk....',
      '....knnnnNNk....',
      '...knnnkknNNk...',
      '..knnnkddkNNNk..',
      '..knnkddddkNNk..',
      '.knnnkddddkNNNk.',
      '.knnkddddddkNNk.',
      'knnnkddddddkNNNk',
      'kkkkkkkkkkkkkkkk',
      '................',
      '................',
    ] },
    sk_fire: { rows: [
      '.......k........',
      '......kFk...k...',
      '.....kFfk..kFk..',
      '.....kFfFk.kFk..',
      '....kFffFkkFfk..',
      '..k.kFfffFFffFk.',
      '.kFkkFffwffffFk.',
      '.kFfFFfwwwfffFk.',
      '.kFffffwwwyffFk.',
      '..kFfffwwyyfFk..',
      '..kFffffyyyfFk..',
      '...kFfffyyfFk...',
      '....kFFffFFk....',
      '.....kFFFFk.....',
      '......kkkk......',
      '................',
    ] },
    sk_water: { rows: [
      '................',
      '................',
      '................',
      '......kkk.......',
      '.....kcwck......',
      '....kcwkkbk.....',
      '...kcwk..kbk....',
      '..kcwk....kbk...',
      '.kcbk......kbk..',
      'kcbbk..kkkkkbbk.',
      'kBbbkkkcccbbbBBk',
      'kBBbbbbbbbbbBBBk',
      'kkBBBBBBBBBBBBkk',
      '.kkkkkkkkkkkkkk.',
      '................',
      '................',
    ] },
    sk_intelligence: { rows: [
      '................',
      '.....kkkkkk.....',
      '....kmmmmmmk....',
      '...kmmkmmkmmk...',
      '..kmkmmmmmmmmk..',
      '..kmmmkmmkmmmk..',
      '..kmkmmmmmmkmk..',
      '..kmmmkmmkmmmk..',
      '..kMmmmmmmmmMk..',
      '...kMmkmmkmMk...',
      '...kMMmmmmMMk...',
      '....kMMkkMMk....',
      '.....kkkkkk.....',
      '......kppk......',
      '......kkkk......',
      '................',
    ] },
    sk_mysticism: { rows: [
      '................',
      '.....kkkkkk.....',
      '....kaAAaaak....',
      '...kaAAaaaaak...',
      '..kaAaaawaaaak..',
      '..kaaaawwwaaak..',
      '.kaaaawwwwwaaak.',
      '.kaaawwwwwwwaak.',
      '.kaaaaawwwaaaak.',
      '.kPaaaawwwaaaPk.',
      '..kPaaawawaaPk..',
      '..kPPaaaaaaPPk..',
      '...kPPaaaaPPk...',
      '....kPPPPPPk....',
      '.....kkkkkk.....',
      '................',
    ] },
    sk_sorcery: { rows: [
      '..........kkk...',
      '.........kyyyk..',
      '........kyfwyk..',
      '........kyyfyk..',
      '.......kkkyyk...',
      '......kwkkkk....',
      '......kwlk......',
      '.....kwlk.......',
      '.....kwlk.......',
      '....kwlk........',
      '...kkwlk........',
      '..kpplk.........',
      '.kppplk.........',
      '.kPppk..........',
      '.kPPk...........',
      '..kk............',
    ] },
    sk_resistance: { rows: [
      '................',
      '.kkkkkkkkkkkkk..',
      '.kelllllllleek..',
      '.kellllyllleek..',
      '.kelllyyylleek..',
      '.kellyyyyyleek..',
      '.kelllykylleek..',
      '.kelllykylleek..',
      '..keeeykyeeEk...',
      '..keeeyyyeeEk...',
      '...kEeeeeeEk....',
      '....kEeeeEk.....',
      '.....kEEEk......',
      '......kEk.......',
      '.......k........',
      '................',
    ] },
    sk_leadership: { rows: [
      '...kkk..........',
      '..kyyyk.........',
      '...kykkkkkkkkk..',
      '...kNkrrrrrrrrk.',
      '...kNkrrrryrrrk.',
      '...kNkrrryyyrrk.',
      '...kNkrrrryrrrk.',
      '...kNkRrrrrrRk..',
      '...kNkRRRRRRk...',
      '...kNkkkkkkk....',
      '...kNk..........',
      '...kNk..........',
      '...kNk..........',
      '...kNk..........',
      '..kkkkk.........',
      '................',
    ] },
    sk_luck: { rows: [
      '................',
      '....kkk..kkk....',
      '...kyyyk.kyyyk..',
      '...kyYyk.kyYyk..',
      '..kkyyyk.kyyykk.',
      '..kyYYyk.kyYYyk.',
      '..kyYyk...kyYyk.',
      '..kyYyk...kyYyk.',
      '..kyYyyk.kyyYyk.',
      '...kyYyykkyyYk..',
      '...kkyYyyyyYyk..',
      '....kkyYYYYyk...',
      '.....kkkYYkk....',
      '.......kkkk.....',
      '................',
      '................',
    ] },
    sk_necromancy: { rows: [
      '......hhhh......',
      '....hhkkkkhh....',
      '...hkiiiiiikh...',
      '..hkiiiiiiiikh..',
      '.hkiiiiiiiiiikh.',
      '.hkiikkiikkiikh.',
      '.hkikhhkikhhkkh.',
      '.hkikhhkikhhkkh.',
      '.hkiikkiikkiikh.',
      '.hkiiiiikiiiikh.',
      '..hkiiikkkiiikh.',
      '...hkkiiiiikkh..',
      '....hkikikikh...',
      '.....hkkkkkh....',
      '......hhhhh.....',
      '................',
    ] },
    sk_estates: { rows: [
      '.k.k.k.k..k.k...',
      '.kkkkkkk..kkk...',
      '.kllleeek.keek..',
      '.klleeeekkkeek..',
      '..keeeek.keeeek.',
      '..keeeekkkeeeek.',
      '.kkeeeeeeeeeeek.',
      '.keeekkkeeeeeek.',
      '.keeekuukeeeeek.',
      '.keeekuukeekkkkk',
      '.keeekuukeekyyyk',
      '.kkkkkkkkkkkyYyk',
      '............kyyk',
      '............kkkk',
      '................',
      '................',
    ] },
    sk_diplomacy: { rows: [
      '................',
      '................',
      '................',
      '.kkkk......kkkk.',
      'kssssk....ksssSk',
      'kssssskkkksssSSk',
      'ksssssssssssSSk.',
      '.kssssssssssSSk.',
      '.kSssskkkkkssSk.',
      '..kSssssssssSk..',
      '...kSSsssssSk...',
      '....kkSSSSSk....',
      '......kkkkk.....',
      '................',
      '................',
      '................',
    ] },
    sk_learning: { rows: [
      '..............k.',
      '.............kwk',
      '............kwlk',
      '...........kwlk.',
      '..........kwlk..',
      '.kkkkkkk..kwlk..',
      'kiiiiiikkkwlk...',
      'kiuuuiiikwlk....',
      'kiiiiiiiklk.....',
      'kiuuuuiikk......',
      'kiiiiiiik.......',
      'kiuuuiiik.......',
      'kiiiiiiik.......',
      'kIIIIIIIk.......',
      'kkkkkkkkk.......',
      '................',
    ] },
  };

  /* ======================= sp_* 16×16 (framed) ======================= */
  const SP = {
    sp_magic_arrow: framed('p', [
      '..........kk',
      '.........kwk',
      '........kwlk',
      '.......kwlk.',
      '......kwlk..',
      '.....kwlk...',
      '....kwlk....',
      '...kwlk.....',
      '.kkwlk......',
      '.kAAk.......',
      '.kAAAk......',
      '.kkkkk......',
    ]),
    sp_haste: framed('c', [
      '............',
      '.kk.........',
      '.kwkk.......',
      '..kwwkkkkk..',
      '...kwwkTnk..',
      '....kkknnk..',
      '......knnNk.',
      '......knnnNk',
      '...kkknnnnNk',
      '..kNnnnnnNNk',
      '..kNNNNNNNNk',
      '..kkkkkkkkkk',
    ]),
    sp_slow: framed('c', [
      '............',
      '.......k.k..',
      '.......kkk..',
      '...kkk.kgk..',
      '..knnnkkgk..',
      '.knTTnnkgk..',
      '.knTnNnkggk.',
      '.knnnNnkggk.',
      '..kNNNkgggk.',
      '.kkkkkgggGk.',
      '.kGgGGGGGGk.',
      '..kkkkkkkk..',
    ]),
    sp_bless: framed('c', [
      '.....kk.....',
      '..k.kyyk.k..',
      '...kyyyyk...',
      '..kyywwyyk..',
      '.kyywwwwyyk.',
      '.kyywwwwyyk.',
      '..kyywwyyk..',
      '...kyyyyk...',
      '..k.kyyk.k..',
      '.....kk.....',
      '............',
      '............',
    ]),
    sp_curse: framed('n', [
      '...kkkkkk...',
      '..kiiiiiik..',
      '.kiiiiiiiik.',
      '.kikkiikkik.',
      '.kikkiikkik.',
      '.kiiiikiiik.',
      '..kiiiiiik..',
      '...kikikik..',
      '...kkkkkk...',
      '............',
      '............',
      '............',
    ]),
    sp_shield: framed('n', [
      '............',
      '.kkkkkkkkkk.',
      '.kelllllllk.',
      '.kelllyllek.',
      '.kellyyylek.',
      '.kelllyllek.',
      '..kEllllEk..',
      '..kEEeeEEk..',
      '...kEEEEk...',
      '....kEEk....',
      '.....kk.....',
      '............',
    ]),
    sp_stone_skin: framed('n', [
      '............',
      '..kk.k......',
      '.kllkllk.k..',
      '.kelkelkklk.',
      '.kelkelkelk.',
      '.kelllllllk.',
      'kkkellleeek.',
      'kllkelleeek.',
      'kelkeeeeeEk.',
      '.keeeeeEEEk.',
      '..kEEEEEEk..',
      '..kkkkkkkk..',
    ]),
    sp_bloodlust: framed('f', [
      '.....kk.....',
      '.....krk....',
      '....krrk....',
      '....krrrk...',
      '...kMrrrrk..',
      '...kMrrrrk..',
      '..kMrrrrRk..',
      '..kMrrrRRk..',
      '..krrrRRRk..',
      '...krrRRk...',
      '....kkkk....',
      '............',
    ]),
    sp_cure: framed('c', [
      '............',
      '....kkkk....',
      '....kwwk....',
      '....kwwk....',
      '.kkkkwwkkkk.',
      '.kwwwwwwwwk.',
      '.kwwwwwwwwk.',
      '.kkkkwwkkkk.',
      '....kwwk....',
      '....kwwk....',
      '....kkkk....',
      '............',
    ]),
    sp_dispel: framed('c', [
      '............',
      '...kkkkk....',
      '..kAAkkAAk..',
      '.kAk....kAk.',
      '.kAk..k..kk.',
      'kAk.kA.k....',
      'kAk..kA.kAk.',
      '.kk..k..kAk.',
      '.kAk....kAk.',
      '..kAAkkAAk..',
      '...kkkkk....',
      '............',
    ]),
    sp_lightning_bolt: framed('c', [
      '......kkk...',
      '.....kyyk...',
      '....kyyk....',
      '...kyyk.....',
      '..kyykkkk...',
      '..kyyyyyk...',
      '..kkkkyyk...',
      '.....kyk....',
      '....kyk.....',
      '...kyk......',
      '..kyk.......',
      '..kk........',
    ]),
    sp_ice_bolt: framed('b', [
      '..........kk',
      '.........kwk',
      '........kwck',
      '.......kwck.',
      '..k...kwck..',
      '.kck.kwck...',
      '..kckwck....',
      '.kkcwck.k...',
      '.kccck..k...',
      '..kkckkk....',
      '..k.k.......',
      '............',
    ]),
    sp_death_ripple: framed('n', [
      '............',
      '...kkk.kkk..',
      '..kiiikiiik.',
      '..kikikikik.',
      '..kiiikiiik.',
      '...kkk.kkk..',
      '.k........k.',
      '.khk.kk.khk.',
      '..khkhhkhk..',
      '...khhhhk...',
      '....kkkk....',
      '............',
    ]),
    sp_blind: framed('f', [
      '............',
      '............',
      '............',
      '..kkkkkkkk..',
      '.kiiiiiiiik.',
      'kkiiiiiiiikk',
      '.kkkkkkkkkk.',
      '..k.k.k.k...',
      '...k.k.k.k..',
      '............',
      '............',
      '............',
    ]),
    sp_precision: framed('c', [
      '............',
      '...kkkkkk...',
      '..krrrrrrk..',
      '.krkwwwwkrk.',
      '.krwkkkkwrk.',
      '.krwkrrkwrk.',
      '.krwkrrkwrk.',
      '.krwkkkkwrk.',
      '.krkwwwwkrk.',
      '..krrrrrrk..',
      '...kkkkkk...',
      '............',
    ]),
    sp_weakness: framed('b', [
      '.........kk.',
      '........klwk',
      '.......klek.',
      '......klek..',
      '.....kkk....',
      '....k.k.....',
      '...klek.....',
      '..kyyek.....',
      '.kykkyk.....',
      '.kNk.kk.....',
      '.kk.........',
      '............',
    ]),
    sp_disrupting_ray: framed('c', [
      '.......kkkk.',
      'kk....kelllk',
      'kAAkk.keleek',
      'kAAAAk.kelek',
      '.kkAAAAkeeek',
      '...kkAAAAeek',
      '....kkAAAAek',
      '.....kAAkAAk',
      '....kAAk.kk.',
      '...kAk......',
      '..kk........',
      '............',
    ]),
    sp_fortune: framed('c', [
      '............',
      '...kk..kk...',
      '..kggkkggk..',
      '..kgGgGgGk..',
      '...kkGgkk...',
      '..kgGgGgGk..',
      '..kggkkgGk..',
      '...kk.kGk...',
      '......kGk...',
      '.....kkk....',
      '............',
      '............',
    ]),
    sp_fireball: framed('o', [
      '...k..kk....',
      '...kFkFFk.k.',
      '..kFfkffFkFk',
      '..kFffffFfFk',
      '.kFfffwffFFk',
      '.kFffwwffFk.',
      '.kFfffwfffFk',
      '.kFFfffffFFk',
      '..kFFfffFFk.',
      '...kFFFFFk..',
      '....kkkkk...',
      '............',
    ]),
    sp_frost_ring: framed('b', [
      '............',
      '....kkkk....',
      '..kkccwckk..',
      '.kccwkkkcck.',
      '.kcwk...kck.',
      'kcck.....kck',
      'kcck.....kck',
      '.kck....kcck',
      '.kcck..kccwk',
      '..kkcckccwk.',
      '....kkkkk...',
      '............',
    ]),
    sp_destroy_undead: framed('c', [
      '.k...kk...k.',
      '..k.kyyk.k..',
      '.kkkyyyykkk.',
      '.kyyyyyyyyk.',
      '..kykkkkyk..',
      '.kykiiiiky..',
      '.kkiiiiiikk.',
      '..kikkikki..',
      '..kiiikiiik.',
      '...kiiiiik..',
      '....kikik...',
      '....kkkkk...',
    ]),
    sp_animate_dead: framed('n', [
      '............',
      '....k.k.k...',
      '...kikikik..',
      '...kikikik..',
      '..kkiiiiik..',
      '.kikiiiiik..',
      '.kiiiiiiik..',
      '..kiiiiiik..',
      'kkkkiiiikkkk',
      'kdddkkkkdddk',
      'kddddddddddk',
      'kkkkkkkkkkkk',
    ]),
    sp_air_shield: framed('c', [
      '............',
      '.kkkkkkkkkk.',
      '.kclcccccck.',
      'kkcckkkcccc?',
      '.kcckwwkcck.',
      'kkccckkcccc?',
      '..kCccccCk..',
      'kkkCCccCCk..',
      '...kCCCCk...',
      '....kCCk....',
      '.....kk.....',
      '............',
    ]),
    sp_meteor_shower: framed('n', [
      '.k....k.....',
      '.Fk..kFk..k.',
      '..Fk.kOOk.Fk',
      '..kOOkOOk.Fk',
      '.kOnOkkk.kOk',
      '.kOOOk..kOOk',
      '..kkk...kOnk',
      '.....k...kk.',
      '....kFk.....',
      '....kOOk....',
      '...kOnOk....',
      '....kkk.....',
    ]),
    sp_chain_lightning: framed('c', [
      'kkk.........',
      'kyyk........',
      '.kyyk.......',
      '..kyyk.kkk..',
      '...kyykkyyk.',
      '....kyyyyyk.',
      '.....kyykk..',
      '......kyk...',
      '....kkkyyk..',
      '...kyyyyyyk.',
      '...kkkkyyk..',
      '......kkk...',
    ]),
    sp_inferno: framed('o', [
      '.....kk.....',
      '....kFfk....',
      '...kFffFk...',
      '..kFfwffFk..',
      '..kFfwffFk..',
      '.kFffwwffFk.',
      '.kFffwwffFk.',
      '.kFfwwwwfFk.',
      'kFffwwwwffFk',
      'kFfffwwfffFk',
      'kFFffffffFFk',
      'kkkkkkkkkkkk',
    ]),
    sp_resurrection: framed('c', [
      '.....kk.....',
      '....kyyk....',
      '.....kk.....',
      '.kk.kssk.kk.',
      'kwwkksskkwwk',
      'kwlwkwwkwlwk',
      'kwlwwwwwwlwk',
      '.kllwwwwllk.',
      '..kklwwlkk..',
      '....kwwk....',
      '...kwwwwk...',
      '...kkkkkk...',
    ]),
    sp_prayer: framed('c', [
      '.....kk.....',
      '..k.kyyk.k..',
      '...kkyykk...',
      '....kyyk....',
      '.k..kkkk..k.',
      '....ksSk....',
      '...kssSSk...',
      '...kssSSk...',
      '..kssskSSk..',
      '..kssskSSk..',
      '..kkkkkkkk..',
      '............',
    ]),
    sp_town_portal: framed('c', [
      '...kkkkkk...',
      '..kaAAAAak..',
      '.kaAk.kkAak.',
      '.kAk.kkkkAk.',
      'kaAkkeeeekAk',
      'kaAklleeekAk',
      'kaAkeeeeekAk',
      'kaAkekkkekAk',
      '.kAkekkkekk.',
      '.kaAkeeekAk.',
      '..kaAkkkAak.',
      '...kkkkkkk..',
    ]),
  };

  /* ======================= art_* 16×16 ======================= */
  const ART = {
    art_centaur_axe: { rows: [
      '.......kkkk.....',
      '......klleek....',
      '.....kllleeek...',
      '.....klleeeEk...',
      '....kklleeeEk...',
      '...kNkkeeeEEk...',
      '..kNNk.kEEEk....',
      '..kNNk..kkk.....',
      '.kNNk...........',
      '.kNNk...........',
      'kNNk............',
      'kNNk............',
      'kNk.............',
      'kNk.............',
      'kk..............',
      '................',
    ] },
    art_dwarven_shield: { rows: [
      '................',
      '..kkkkkkkkkkkk..',
      '.kyeeeeeeeeeeyk.',
      '.keleelllleelek.',
      '.kelellllllelek.',
      '.keleeliiileelk.',
      '.keeeliiiiileek.',
      '..keelillilleek.',
      '..keeliiiiileek.',
      '..keeelliillek..',
      '...keeeliileek..',
      '....keeeiieek...',
      '.....keeeeek....',
      '......kyyyk.....',
      '.......kkk......',
      '................',
    ] },
    art_unicorn_helm: { rows: [
      '.......kk.......',
      '.......kwk......',
      '.......kwk......',
      '......kwwk......',
      '......kwlk......',
      '.....kkkkkk.....',
      '....kllleeeek...',
      '...klleeeeeeek..',
      '..kleeeeeeeeeek.',
      '..keeeeeeeeeEEk.',
      '..kkkkkkkkkkkkk.',
      '..kEk.......kEk.',
      '..kEk..kkk..kEk.',
      '..kEEkkEEEkkEEk.',
      '...kkkkkkkkkkk..',
      '................',
    ] },
    art_skull_helmet: { rows: [
      '................',
      '.....kkkkkk.....',
      '....kIIIIIIk....',
      '...kIIIIIIIIk...',
      '..kIIIIIIIIIIk..',
      '..kIIkkIIkkIIk..',
      '..kIkrrkIkrrkk..',
      '..kIkrrkIkrrkk..',
      '..kIIkkIkIkkIk..',
      '..kIIIIIkIIIIk..',
      '...kIIIkkkIIk...',
      '...kIkIkIkIkk...',
      '...kkkkkkkkkk...',
      '....kEEEEEEk....',
      '.....kkkkkk.....',
      '................',
    ] },
    art_petrified_breastplate: { rows: [
      '................',
      '..kkkk....kkkk..',
      '.kTTTTk..kTTTTk.',
      '.kTnnTTkkTnnnTk.',
      '.kTnnnTTTTnnnNk.',
      '.kTnnnnnnnnnnNk.',
      '..kTnnnNNnnnNk..',
      '..kTnnNnnNnnNk..',
      '..kTnnnNNnnnNk..',
      '..kNnnNnnNnnNk..',
      '..kNnnnnnnnnNk..',
      '..kNNnnnnnnNNk..',
      '...kNNnnnnNNk...',
      '....kkkkkkkk....',
      '................',
      '................',
    ] },
    art_ring_conjuring: { rows: [
      '................',
      '................',
      '......kkkk......',
      '.....kcbbck.....',
      '.....kbwbbk.....',
      '....kkkkkkkk....',
      '...kyyykkyyyk...',
      '..kyYyk..kyYyk..',
      '..kyYk....kyYk..',
      '..kYYk....kYYk..',
      '..kYYYk..kYYYk..',
      '...kYYYkkYYYk...',
      '....kkYYYYkk....',
      '......kkkk......',
      '................',
      '................',
    ] },
    art_badge_courage: { rows: [
      '................',
      '....kkkkkkkk....',
      '....krrkkrrk....',
      '....krrkkrrk....',
      '....kRrkkrRk....',
      '.....kkkkkk.....',
      '.....kyyyyk.....',
      '....kyyyyyyk....',
      '...kyyywyyyyk...',
      '...kyywwwyyYk...',
      '...kyyywyyYYk...',
      '....kyyyyYYk....',
      '.....kyYYYk.....',
      '......kkkk......',
      '................',
      '................',
    ] },
    art_clover_fortune: { rows: [
      '................',
      '....kkk..kkk....',
      '...kgggkkgggk...',
      '..kghgggggghgk..',
      '..kggGggggGggk..',
      '...kggGkkGggk...',
      '..kkkkGkkGkkkk..',
      '.kgggGgkkgGgggk.',
      '.kghggggggghgGk.',
      '..kgggggkgggGk..',
      '...kkkkkkkGkk...',
      '.........kGk....',
      '........kGk.....',
      '.......kkk......',
      '................',
      '................',
    ] },
    art_blackshard: { rows: [
      '...........kkk..',
      '..........kupk..',
      '.........kuupk..',
      '........kuupk...',
      '.......kuupk....',
      '......kuupk.....',
      '.....kuupk......',
      '....kuupk.......',
      '.kkkuupk........',
      '..kuupk.........',
      '.kuukkk.........',
      'kuukkPk.........',
      'kkkkPPk.........',
      '.kPPk.k.........',
      '.kkk............',
      '................',
    ] },
    art_gnoll_flail: { rows: [
      '.........kkkk...',
      '........kk.kkk..',
      '.......kkekkeek.',
      '.......kkeeeeek.',
      '......kk.keeeek.',
      '.....kk..kkeekk.',
      '....kk....kkkk..',
      '...kk...........',
      '..kkk...........',
      '.kNnk...........',
      '.kNnk...........',
      '.kNnk...........',
      'kNNnk...........',
      'kNNk............',
      'kkk.............',
      '................',
    ] },
    art_gnoll_buckler: { rows: [
      '................',
      '.....kkkkkk.....',
      '....kTTTtttk....',
      '...kTTTtttttk...',
      '..kTTkkkkkkttk..',
      '..kTkeeeeekttk..',
      '.kTkeeleeeekttk.',
      '.kTkeeeeeeekttk.',
      '.kTkeeeeEEekttk.',
      '.kTkeeeEEEekntk.',
      '..kTkeeEEekntk..',
      '..kTTkkkkkknnk..',
      '...kTTnnnnnnk...',
      '....kTTnnnnk....',
      '.....kkkkkk.....',
      '................',
    ] },
    art_magi_crown: { rows: [
      '................',
      '................',
      '...k....k....k..',
      '..kck..kck..kck.',
      '..kbk.kbbk..kbk.',
      '..kbkkkbbkkkkbk.',
      '.kbbbbbbbbbbbbbk',
      '.kbwbbybbybbbbbk',
      '.kbbbybbbbybbBBk',
      '.kbbbbbbbbbbbBBk',
      '.kBbbbbbbbbbBBBk',
      '.kBBBBBBBBBBBBBk',
      '.kkkkkkkkkkkkkkk',
      '................',
      '................',
      '................',
    ] },
    art_rib_cage: { rows: [
      '................',
      '..kkkkk..kkkkk..',
      '.kiiiiikkiiiiik.',
      '.kiikkiiiikkiik.',
      '.kiiiikiiikiiik.',
      '..kkkkkiikkkkk..',
      '..kiiiikiikiiik.',
      '..kkkkkkiikkkkk.',
      '..kiiiikiikiiik.',
      '..kkkkkkiikkkkk.',
      '...kiiikiikiiik.',
      '...kkkkkiikkkk..',
      '....kiiiiiiiik..',
      '.....kkkkkkkk...',
      '................',
      '................',
    ] },
    art_basilisk_scales: { rows: [
      '................',
      '..kkkk....kkkk..',
      '.kgGgGk..kGgGgk.',
      '.kGgGgGkkGgGgGk.',
      '.kgGgGgGgGgGgGk.',
      '.kGgGgGgGgGgGGk.',
      '..kgGgGgGgGgGk..',
      '..kGgGgGgGgGGk..',
      '..kgGgGgGgGgGk..',
      '..kGgGgGgGgGGk..',
      '..kgGgGgGgGGGk..',
      '..kGGgGgGgGGGk..',
      '...kGGGGGGGGk...',
      '....kkkkkkkk....',
      '................',
      '................',
    ] },
    art_ring_vitality: { base: 'art_ring_conjuring', tint: { c: 'm', b: 'r' } },
    art_ring_life: { base: 'art_ring_conjuring', tint: { c: 'h', b: 'g' } },
    art_boots_speed: { rows: [
      '................',
      '................',
      '......kkkk......',
      '.kk...kNnk......',
      '.kwkk.kNnk......',
      '..kwwkkNnk......',
      '...kwwkNnk......',
      '....kkkNnnk.....',
      '......kNnnnk....',
      '......kNnnnnk...',
      '...kkkkNnnnnNk..',
      '..kNnnnnnnnnNNk.',
      '..kNNnnnnnNNNNk.',
      '..kNNNNNNNNNNNk.',
      '..kkkkkkkkkkkkk.',
      '................',
    ] },
    art_equestrian_gloves: { rows: [
      '................',
      '..k.k.k.....k.k.',
      '.kTkTkTk..kTkTkk',
      '.kTTTTTTk.kTTTTk',
      'kkTTTTTTk.kTTTTk',
      'kTkTTTTTk.kTTTTk',
      'kTTTTTTTkkkTTTTk',
      '.kTTTTTTkkTTTTTk',
      '.kTTTTTTkkTTTTTk',
      '..kkkkkkkkkkkkk.',
      '..knnnnnkknnnnk.',
      '..kNNNNNkkNNNNk.',
      '..kkkkkkkkkkkkk.',
      '................',
      '................',
      '................',
    ] },
    art_cape_conjuring: { rows: [
      '................',
      '.....kkkkkk.....',
      '....kyyyyyyk....',
      '...kkkkkkkkkk...',
      '...kbbbbbbbbk...',
      '..kbbbbbbbbbbk..',
      '..kbbbbBbbbbbk..',
      '.kbbbbbBbbbbbBk.',
      '.kbbbbBBBbbbbBk.',
      '.kbbbbbBbbbbBBk.',
      'kbbbbbbbbbbbBBBk',
      'kbbbbbbbbbbBBBBk',
      'kBbbbbbbbbBBBBBk',
      'kBBbbbbbBBBBBBBk',
      'kkkkkkkkkkkkkkkk',
      '................',
    ] },
    art_necklace_swiftness: { rows: [
      '................',
      '....kkkkkkkk....',
      '...kyk....kyk...',
      '..kyk......kyk..',
      '..kyk......kyk..',
      '..kyk......kyk..',
      '...kyk....kyk...',
      '...kyyk..kyyk...',
      '....kkykkykk....',
      '.....kkyykk.....',
      '.kk..kwwwwk.....',
      '.kwkkwwlwwkk....',
      '..kwwwlwlwwwk...',
      '...kklllllllk...',
      '.....kkkkkkk....',
      '................',
    ] },
    art_sword_hellfire: { rows: [
      '...........kkk..',
      '..........kFfk..',
      '.........kFfwk..',
      '........kFfwk...',
      '.......kFfwkk...',
      '......kFfwkFk...',
      '.....kFfwkF.....',
      '....kFfwkF......',
      '.kkkFfwk........',
      '..kyfwkF........',
      '.kyykkk.........',
      'kyykkyk.........',
      'kkkkyyk.........',
      '.kNNk.k.........',
      '.kkk............',
      '................',
    ] },
    art_shield_yawning_dead: { rows: [
      '................',
      '..kkkkkkkkkkkk..',
      '.kuuuuuuuuuuuuk.',
      '.kuuukkkkkkuuuk.',
      '.kuukiiiiiikuuk.',
      '.kukiikiikiikuk.',
      '.kukiiikkiiikuk.',
      '..kkiiikkiiikk..',
      '..kukiiiiiikuk..',
      '..kuukikikikuk..',
      '...kuukkkkkuk...',
      '....kuuuuuuk....',
      '.....kuuuuk.....',
      '......kuuk......',
      '.......kk.......',
      '................',
    ] },
    art_thunder_helmet: { rows: [
      '................',
      '......kkkkk.....',
      '.....kkyyyk.....',
      '.....kykyk......',
      '.....kkkkk......',
      '....kllleeeek...',
      '...klleeeeeeek..',
      '..kleeeeeeeeeek.',
      '..keeeeeeeeeEEk.',
      '..kkkkkkkkkkkkk.',
      '..kEk.......kEk.',
      '..kEk..kkk..kEk.',
      '..kEEkkEEEkkEEk.',
      '...kkkkkkkkkkk..',
      '................',
      '................',
    ] },
    art_armor_wonder: { rows: [
      '....k......k....',
      '..kkkk....kkkk..',
      'k.kAwwk..kwwAk.k',
      '.kAwwwwkkwwwwAk.',
      '.kAwwwwwwwwwwAk.',
      '.kAwwwwwwwwwwAk.',
      '..kAwwwAwwwwAk..',
      '..kAwwAwAwwwAk..',
      'k.kAwwwAwwwAAk.k',
      '..kAAwwwwwwAAk..',
      '..kAAAwwwwAAAk..',
      '..kaAAAwwAAAak..',
      '...kaAAAAAAak...',
      '....kkkkkkkk....',
      '....k......k....',
      '................',
    ] },
    art_ogre_club: { rows: [
      '..........kkkk..',
      '.........kTnnnk.',
      '........kTnnnnnk',
      '........kTnnNnnk',
      '........knkNNnnk',
      '.......knnnNNNk.',
      '.......knnNNNk..',
      '......knnNkkk...',
      '.....knnNk......',
      '....knnNk.......',
      '...knnNk........',
      '..kNnNk.........',
      '.kNNNk..........',
      'kNNNk...........',
      'kNNk............',
      'kkk.............',
    ] },
    art_ogre_targ: { rows: [
      '.......k........',
      '...k..kek..k....',
      '..kk.kkkkk.kk...',
      '..kekkTTTTkkek..',
      '...kTTTTTTTTk...',
      '.kkTTTTTTTTTTkk.',
      'kekTTTTkkkTTTkek',
      'kkkTTTkeeekTTkkk',
      '.kTTTTkeeekTTTk.',
      'kkkTTTTkkkTTTkkk',
      'kekTTTTTTTTTTkek',
      '.kkTTTTTTTTTTkk.',
      '...kTTTTTTTTk...',
      '..kekkkkkkkkkek.',
      '...k..kek..k....',
      '.......k........',
    ] },
    art_cyclops_tunic: { rows: [
      '................',
      '..kkkk....kkkk..',
      '.kttttk..kttttk.',
      '.ktttttkkttttTk.',
      '.kttttttttttttk.',
      '.kttttttttttTTk.',
      '..kttttyyttttk..',
      '..kttttyyttttk..',
      '..kttttttttttk..',
      '..kttttttttTTk..',
      '..kttttttttTTk..',
      '..kttttttttTTk..',
      '..kttttttttTTk..',
      '..kTTTTTTTTTTk..',
      '..kkkkkkkkkkkk..',
      '................',
    ] },
    art_pendant_courage: { rows: [
      '................',
      '.....kkkkkk.....',
      '....kyk..kyk....',
      '...kyk....kyk...',
      '...kyk....kyk...',
      '...kyk....kyk...',
      '....kyk..kyk....',
      '.....kyykyk.....',
      '......kkkk......',
      '.....kyyyyk.....',
      '....kyywyyyk....',
      '....kyyyyyYk....',
      '....kyyyyYYk....',
      '.....kyYYYk.....',
      '......kkkk......',
      '................',
    ] },
    art_cape_velocity: { base: 'art_cape_conjuring', tint: { b: 'r', B: 'R' } },
    art_boots_polarity: { base: 'art_boots_speed', tint: { n: 'p', N: 'P', w: 'A' } },
    art_titan_gladius: { rows: [
      '.............kk.',
      '............kcwk',
      '...........kcbbk',
      '..........kcbbk.',
      '.........kcbbk..',
      '........kcbbk...',
      '.......kcbbk....',
      '......kcbbk.....',
      '.....kcbbk......',
      '.kkkkcbbk.......',
      '..kyybbk........',
      '.kyykkkk........',
      'kyykkyyk........',
      'kkkkyyk.........',
      '.kNNk.k.........',
      '.kkk............',
    ] },
    art_sentinel_shield: { rows: [
      '.kkkkkkkkkkkkkk.',
      'kyyyyyyyyyyyyyyk',
      'kyllllllllllllyk',
      'kylllllwwlllllyk',
      'kyllllwwwwllllyk',
      'kylllwwyywwlllyk',
      'kyllllwyywwlllyk',
      'kylllllwwlllllyk',
      '.kyllllwwlllleY.',
      '.kyeeeeeeeeeeYk.',
      '..kyeeeeeeeeYk..',
      '...kyeeeeeeYk...',
      '....kyeeeeYk....',
      '.....kyeeYk.....',
      '......kyYk......',
      '.......kk.......',
    ] },
    art_helm_enlightenment: { rows: [
      '....k..k..k.....',
      '.....k.k.k......',
      '......kkk.......',
      '.k..kkwwwkk..k..',
      '..kkwwwwwwwkk...',
      '..kwwwlllwwwk...',
      '.kwwllleeellwwk.',
      '.kwlleeeeeellwk.',
      '.kkkkkkkkkkkkkk.',
      '.kEk.........kEk',
      '.kEk..kkkk...kEk',
      '.kEEkkEEEEkkkEEk',
      '..kkkkkkkkkkkkk.',
      '......k.k.......',
      '................',
      '................',
    ] },
    art_titan_cuirass: { rows: [
      '................',
      '..kkkk....kkkk..',
      '.kcbbbk..kbbbBk.',
      '.kcbbbbkkbbbbBk.',
      '.kcbbbbbbbbbbBk.',
      '.kbbbbbbbbbbbBk.',
      '..kbbbykybbbBk..',
      '..kbbbkykbbbBk..',
      '..kbbbykybbbBk..',
      '..kBbbbbbbbbBk..',
      '..kBbbbbbbbBBk..',
      '..kBBbbbbbBBBk..',
      '...kBBBBBBBBk...',
      '....kkkkkkkk....',
      '................',
      '................',
    ] },
    art_necklace_bliss: { rows: [
      '................',
      '....kkkkkkkk....',
      '...kyk....kyk...',
      '..kyk......kyk..',
      '..kyk......kyk..',
      '..kyk......kyk..',
      '...kyk....kyk...',
      '...kyyk..kyyk...',
      '....kkykkykk....',
      '.......kk.......',
      '......kcck......',
      '....kkkcwckkk...',
      '....kccwwwcck...',
      '.....kkcwckk....',
      '......kcck......',
      '.......kk.......',
    ] },
    art_angel_wings: { rows: [
      '................',
      '.kk..........kk.',
      'kwwk........kwwk',
      'kwwwk......kwwwk',
      'kwlwwk....kwwlwk',
      '.kwlwwk..kwwlwk.',
      '.kwlwwwkkwwwlwk.',
      '..kwlwwwwwwlwk..',
      '..kwllwwwwllwk..',
      '...kwllwwllwk...',
      '...kkwllllwkk...',
      '..kwwkkllkkwwk..',
      '.kwlwwkkkkwwlwk.',
      '.kwllwk..kwllwk.',
      '..kkkk....kkkk..',
      '................',
    ] },
  };

  H3.Sprites.defineMany(Object.assign({}, IC, SK, SP, ART));
})();
