/* ============================================================================
   view/sprites_stronghold_hd.js — существа Цитадели в крупной сетке (unit 2), стиль Б:
   без контурной линии, тона кладёт рисунок. Собирается скриптом dev/proto/stronghold_hd.py.
   ========================================================================== */
(function () {
  'use strict';
  H3.Sprites.defineMany({
    /* гоблин: маленький зелёный, большие уши, дубинка, красная повязка (36×44) */
    goblin: {
      hd: true, unit: 2,
      rows: [
        '..............gggggggg..........NN..',
        '.....gg......gggggggggg..gg....NNNN.',
        '....gggg....gggggggggggggggg..NNNNN.',
        '...ggggg...gggggggggggggggggg.NNNNN.',
        '...ggggggggggGGGGggGGGgggggg..NNNNN.',
        '...gggggggggGGwwGGGGwwGG.......NNN..',
        '....ggggggggGGkwGGGGwkGG.......NNN..',
        '.....gggggggggGGGgggGGGg.......NNN..',
        '.......ggggggggggggggggg.......NNN..',
        '.........ggggggGGGGGgg.........NNN..',
        '.........ggggGGRRRGGgg.........NNN..',
        '..........gggGGGGGGGgg.........NNN..',
        '...........gggggggggg..........NNN..',
        '............GGGGGGGG...........NNN..',
        '...........GGGGGGGGGG..........nnn..',
        '...........GGGGGGGGGG..........nnn..',
        '..........GGGGGGGGGGGG.........nnn..',
        '..........GGGGGGGGGGGG.........nnn..',
        '.........GGGGGGGGGGGGGG........nnn..',
        '.........GGGGGGGGGGGGGG........nnn..',
        '........GGGGGGGGGGGGGGGG.......nnn..',
        '........GGGGGGGGGGGGGGGG.......nnn..',
        '.......gggGGGGGGGGGGGGgggg.....nnn..',
        '.......gggGGGGGGGGGGGGgggg.....nnn..',
        '......ggggGGGGGGGGGGGGggggg...nnnn..',
        '......ggggGGGGGGGGGGGGggggg...nnnn..',
        '......ggggGGGGGGGGGGGGggggggnnnnnn..',
        '......ggggGGGGGGGGGGGGggggggnnnnnn..',
        '......ggggGGGGGGGGGGGGgggggggnnnn...',
        '......ggggGGGGGGGGGGGGgggggggnnnn...',
        '......gggg.GGGGGGGGGGG.gggggggg.....',
        '......gggg.rrrrrrrrrrr..gggggg......',
        '.......gg..rRrRrRrRrRr..............',
        '...........RRRRRRRRRRR..............',
        '...........RRRRRRRRRRR..............',
        '...........rrrrrrrrrrr..............',
        '...........gggggg.gggggg............',
        '...........gggggg.gggggg............',
        '...........GGGGGG.GGGGGG............',
        '...........GGGGGG.GGGGGG............',
        '...........gggggg.gggggg............',
        '...........gggggg.gggggg............',
        '..........nnnnnnn.nnnnnnn...........',
        '..........NNNNNNN.NNNNNNN...........',
      ],
    },
    /* хобгоблин: повязка в кожу, красный шлем с гребнем */
    hobgoblin: { base: 'goblin', tint: { r: 'n', R: 'N' }, extra: [[17, 0, 'r'], [18, 0, 'r'], [15, 1, 'r'], [16, 1, 'r'], [17, 1, 'r'], [18, 1, 'r'], [19, 1, 'r'], [20, 1, 'r'], [13, 2, 'r'], [14, 2, 'r'], [15, 2, 'r'], [16, 2, 'r'], [17, 2, 'r'], [18, 2, 'r'], [19, 2, 'r'], [20, 2, 'r'], [21, 2, 'r'], [22, 2, 'r'], [11, 3, 'R'], [12, 3, 'R'], [13, 3, 'R'], [14, 3, 'R'], [15, 3, 'R'], [16, 3, 'R'], [17, 3, 'R'], [18, 3, 'R'], [19, 3, 'R'], [20, 3, 'R'], [21, 3, 'R'], [22, 3, 'R'], [23, 3, 'R'], [24, 3, 'R'], [17, 0, 'R'], [18, 0, 'R']] },
    /* наездник на волке: серый волк в прыжке, гоблин с копьём (композитор) (56×48) */
    wolf_rider: {
      hd: true, unit: 2,
      rows: [
        '........................................................',
        '........................................................',
        '.............................................ll.........',
        '.............................................ll.........',
        '............................................lll.........',
        '...........................................Nllll........',
        '..........................................Nlllll........',
        '.........................................NNlll..........',
        '........................................NNNN............',
        '........................gggg...........NNNN.............',
        '......................gggggggg........NNNN..............',
        '.....................gghhhhgggg......NNNN...............',
        '.....................ghhhhhhggg.....NNNN................',
        '..................g.gghhhhhhgggg.g.NNNN.................',
        '..................gggghhhhhhggggggNNNN..................',
        '...................ggghhhhhhgggggNNNN...................',
        '....................gggwkhhgkwggNNNN....................',
        '....................gggggggggggNNNN.....................',
        '.....................gggggggggNNNN.gg...................',
        '......................ggggggggNNN.ggg...................',
        '........................gggg..NN.gggg...................',
        'llll............................ggggg...................',
        'llll.................GGGGGGGGGGggggg....ee....e.........',
        'llll.................GGGGGGGGGggggg.....eEEeeeeEe.......',
        'llllee............gg.GGGrrrrGGggggg....eeeEEeeeEEe......',
        'eeeeeee..........ggg.GGrrrrrrGGggg....eeeeeeeeeeee......',
        '.eeeeeee........gggggGrrrrrrrrGggeeeeeeeeeeeeeyyeee.....',
        '..eeeeeee......egggggGrrrrrrrrGGeeeeeeeeeeeeeekeeeeee...',
        '...eeeeeeee..eegggggGGGrrrrrrGGGleeeeeeeeeeeeeeeeeeeeee.',
        '.....eeeeeeeeeggDDDDDDDDDDDDDDDDDDDDDDDDDDDDDeeeeeEEEEe.',
        '......eeeeeeeelgDgllGGNNNNNNNNGGlleeeeeeeeeeeeeeeEEEEkE.',
        '.......eeeeeeeelllllllNNNNNNNNllleeeeeeeeeeeeeeeeEEEEEE.',
        '........eeeeeeeelllEEENNNNNNNNEEEEEEEeeeeeeeeeeeeeEEEE..',
        '.........eeeeeeeEEEEEENNNNNNNNEEEEEEEEEEeeeee.ww.ww.ww..',
        '............eeeEEEEEEENNNNNNNNEEEEEEEEEEEeee............',
        '.............eeEEEEEEENNNNNNNNEEEEEEEEEEEee.............',
        '.............EEEEEEEeeeeeeEEEEEEEEEEEEEEeeeeee..........',
        '.............EEEEEEEeeeeeeEEEEEEEEEEEEE.eeeeee..........',
        '.............EEEEEE.eeeeeeeeeeeeeEEEEEE.eeeeee..........',
        '.............EEEEEE..eeeeee......EEEEEE..eeeeee.........',
        '............EEEEEE...eeeeee.....EEEEEE...eeeeee.........',
        '............EEEEEE....eeeee.....EEEEEE....eeeee.........',
        '............EEEEEE....eeeeee....EEEEEE....eeeeee........',
        '...........EEEEEE.....eeeeee...EEEEEE.....eeeeee........',
        '...........EEEEEE......eeeeee..EEEEEE......eeeeee.......',
        '...........EEEEEE......eEEEEE..EEEEEE......eEEEEE.......',
        '..........EEEEEEE......EEEEEEEEEEEEEE......EEEEEEE......',
        '...........EEEEE........EEEEE..EEEEE........EEEEE.......',
      ],
    },
    /* волчий налётчик: чёрный волк, гоблин в красной броне, острие темнее */
    wolf_raider: { base: 'wolf_rider', tint: { e: 'u', E: 'z', l: 'e', G: 'R', r: 'y' } },
    /* орк: зеленокожий, клыки, кожаная броня, метательный топор (48×52) */
    orc: {
      hd: true, unit: 2,
      rows: [
        '..............GGGGGGGGGGGG......................',
        '............GGGGGGGGGGGGGGGG....................',
        '...........GGGGGGGGGGGGGGGGGG...................',
        '...........GGGggggggggggggGGG.....eee...eee.....',
        '...........GGggggggggggggggGG...lllll...eeeee...',
        '...........GGgggGGGggggGGGggG..llllll...eeeeee..',
        '...........GGgggGwwGggggGwwGG..llllllNnNeeeeee..',
        '...........GGgggGwkGggggGkwGG..llllllNnNeeeeee..',
        '...........GGggggggggggggggGG...lllllNnNeeeee...',
        '...........GGggggggGGGGggggGG....eeeeNnNeeee....',
        '............GgggggGGGGGGggG.......eeeNnNeee.....',
        '............GgggggggggggggG..........NnN........',
        '............GggiiGGGGGGiigG..........NnN........',
        '.............GgiiggggggiigG..........NnN........',
        '..............GGgggggggggG...........NnN........',
        '...............GGGGGGGGGG............NnN........',
        '...........nnnnnnnnnnnnnnnnnn........NnN........',
        '...........nnnnnnnnnnnnnnnnnn........NnN........',
        '.........nnnnnnnnnnnnnnnnnnnnnn......NnN........',
        '........nnnnNNNnnnnnnnnnnNNNnnnn.....NnN........',
        '........nnnnNNNnnnnnnnnnnNNNnnnn.....NnN........',
        '.......ggggnNNNNnnnnnnnnNNNNnggggggggNnN........',
        '......gggggnnNNNnnnnnnnnnNNNnngggggggNnN........',
        '......gggggnnNNNnnnnnnnnnNNNnngggggggNnN........',
        '......gggggnnnnnnnnnnnnnnnnnnngggGGGGNnN........',
        '......gggggnnnnnNNNNNNNNnnnnnngggggggNnN........',
        '......gggggnnnnnNNNNNNNNnnnnnngggggggNnN........',
        '......gggggnnnnNNNNNNNNNNnnnnngggggggNnN........',
        '......gggggnnnnNNNNNNNNNNnnnnnggggg..NnN........',
        '......gggggnnnnNNNNNNNNNNnnnnnggggg..NnN........',
        '......GGGGGnnnnnNNNNNNNNnnnnnnGGGGG..NnN........',
        '......GGGGGnnnnnnnnnnnnnnnnnnnGGGGG..NnN........',
        '......GGGGGnnnnnnnnnnnnnnnnnnnGGGGG..NnN........',
        '......GGGGG.nnnnnnnnnnnnnnnnn.GGGGG..NnN........',
        '......ggggg.nnnnnnnnnnnnnnnnn.ggggg.............',
        '......ggggg.nnnnnnnnnnnnnnnnn.ggggg.............',
        '......ggggg.NNNNNNNNNNNNNNNNN.ggggg.............',
        '......ggggg.NNNNNNNNNNNNNNNNN.ggggg.............',
        '.......ggg..nnnnnnnnnnnnnnnnn..ggg..............',
        '............NNNNNNNNNNNNNNNNN...................',
        '............NNNNNNNNNNNNNNNNN...................',
        '............nnnnnnnnnnnnnnnnn...................',
        '............ggggggggg.gggggggg..................',
        '............ggggggggg.gggggggg..................',
        '............ggggggggg.gggggggg..................',
        '............GGGGGGGGG.GGGGGGGG..................',
        '............GGGGGGGGG.GGGGGGGG..................',
        '............GGGGGGGGG.GGGGGGGG..................',
        '............ggggggggg.gggggggg..................',
        '............ggggggggg.gggggggg..................',
        '...........NNNNNNNNNN.NNNNNNNNNN................',
        '...........DDDDDDDDDD.DDDDDDDDDD................',
      ],
    },
    /* вождь орков: броня в красное, рогатый шлем */
    orc_chieftain: { base: 'orc', tint: { n: 'r', N: 'R' }, extra: [[14, 0, 'e'], [15, 0, 'e'], [16, 0, 'e'], [17, 0, 'e'], [18, 0, 'e'], [19, 0, 'e'], [20, 0, 'e'], [21, 0, 'e'], [22, 0, 'e'], [23, 0, 'e'], [24, 0, 'e'], [25, 0, 'e'], [12, 1, 'e'], [13, 1, 'e'], [14, 1, 'e'], [15, 1, 'e'], [16, 1, 'e'], [17, 1, 'e'], [18, 1, 'e'], [19, 1, 'e'], [20, 1, 'e'], [21, 1, 'e'], [22, 1, 'e'], [23, 1, 'e'], [24, 1, 'e'], [25, 1, 'e'], [26, 1, 'e'], [27, 1, 'e'], [11, 2, 'e'], [12, 2, 'e'], [13, 2, 'e'], [14, 2, 'e'], [15, 2, 'e'], [16, 2, 'e'], [17, 2, 'e'], [18, 2, 'e'], [19, 2, 'e'], [20, 2, 'e'], [21, 2, 'e'], [22, 2, 'e'], [23, 2, 'e'], [24, 2, 'e'], [25, 2, 'e'], [26, 2, 'e'], [27, 2, 'e'], [28, 2, 'e'], [10, 0, 'i'], [11, 0, 'i'], [10, 1, 'I'], [11, 1, 'I'], [11, 2, 'I'], [28, 0, 'i'], [29, 0, 'i'], [28, 1, 'I'], [29, 1, 'I'], [28, 2, 'I']] },
    /* огр: толстый жёлто-коричневый великан, живот, повязка из шкуры, дубина (52×56) */
    ogre: {
      hd: true, unit: 2,
      rows: [
        '..............NNNNNNNNNNNN..........................',
        '............NNNNNNNNNNNNNNNN..................DDDDD.',
        '...........NNNNNNNNNNNNNNNNNN................DDDNNDD',
        '...........NNNtttttttttttNNNN...............DDNNNNND',
        '...........NNttttttttttttttNN...............DNNnnNND',
        '...........NNtttTTTttttTTTtNN...............DNNnnNND',
        '...........NNtttTwwTttttTwwTN...............DNNnnNND',
        '...........NNtttTwkTttttTkwTN...............DDNNNNDD',
        '...........NNttttttttttttttNN................DDNNNDD',
        '...........NNtttttttTTTttttNN.................DNNND.',
        '............NtttttttTTTTtttN..................DNNND.',
        '............NttttTTTTTTTTttN..................DNNND.',
        '............NtttiTTTTTTTTitN..................DNNND.',
        '.............NttiitttttiitN...................DNNND.',
        '..............NNttttttttNN....................DNNND.',
        '................NNNNNNNN......................DNNND.',
        '............tttttttttttttttt..................DNNND.',
        '............tttttttttttttttt..................DNNND.',
        '..........tttttttttttttttttttt................DNNND.',
        '.........ttttttttttttttttttttttt..............DNNND.',
        '.........ttttttttttttttttttttttt..............DNNND.',
        '........tttttttttttttttttttttttttt............DNNND.',
        '.......tttttttttttttttttttttttttttt...........DNNND.',
        '.......tttttttttttttttttttttttttttt...........DNNND.',
        '......ttttttTTTTTTTTTTTTTTTTttttttttt.........DNNND.',
        '......tttttTTTTTTTTTTTTTTTTTTtttttttt.........DNNND.',
        '......tttttTTTTTTTTTTTTTTTTTTtttttttt.........DNNND.',
        '......tttttTTTTTTTTTTTTTTTTTTttttttttt........DNNND.',
        '......tttttTTTTTTTTTTTTTTTTTTtttttttttt.......DNNND.',
        '......tttttTTTTTTTTTTTTTTTTTTtttttttttt.......DNNND.',
        '......tttttTTTTTTTTTTTTTTTTTTttttttttttt......NNNNN.',
        '......tttttTTTTTTTTTTTTTTTTTTtttttttttttt.....nnnnn.',
        '......tttttTTTTTTTTTTTTTTTTTTtttttttttttt.....nnnnn.',
        '......TTTTTTTTTTTTTTTTTTTTTTTTtttttttttttttt.nnnnn..',
        '......TTTTTTTTTTTTTTTTTTTTTTTTtttttttttttttttnnnn...',
        '......TTTTTTTTTTTTTTTTTTTTTTTTtttttttttttttttnnnn...',
        '......TTTTT.TTTTTTTTTTTTTTTTTTttttttttttttttnnnn....',
        '......TTTTT.TTTTTTTTTTTTTTTTTTtttttttttttttnnnn.....',
        '......TTTTT.TTTTTTTTTTTTTTTTTTtttttttttttttnnnn.....',
        '......ttttt.TTTTTTTTTTTTTTTTTT..tttttttttt.nnnn.....',
        '......ttttt.TTTTTTTTTTTTTTTTTT....tttttt...nnn......',
        '.......ttt..nnNnnNnnNnnNnnNnnN......................',
        '............nNnnNnnNnnNnnNnnNn......................',
        '............NnnNnnNnnNnnNnnNnn......................',
        '............nNnnNnnNnnNnnNnnNn......................',
        '............NNNNNNNNNNNNNNNNNN......................',
        '............NNNNNNNNNNNNNNNNNN......................',
        '............ttttttttt..tttttttt.....................',
        '............ttttttttt..tttttttt.....................',
        '............ttttttttt..tttttttt.....................',
        '............TTTTTTTTT..TTTTTTTT.....................',
        '............TTTTTTTTT..TTTTTTTT.....................',
        '............ttttttttt..tttttttt.....................',
        '............ttttttttt..tttttttt.....................',
        '...........NNNNNNNNNN..NNNNNNNNNN...................',
        '...........DDDDDDDDDD..DDDDDDDDDD...................',
      ],
    },
    /* огр-маг: синяя кожа, повязка в пурпур, посох со светящимся шаром вместо дубины */
    ogre_mage: { base: 'ogre', tint: { t: 'b', T: 'B', n: 'p', N: 'P' }, extra: [[46, 1, 'c'], [47, 1, 'c'], [48, 1, 'c'], [49, 1, 'c'], [45, 2, 'c'], [46, 2, 'c'], [47, 2, 'c'], [48, 2, 'c'], [49, 2, 'c'], [50, 2, 'c'], [45, 3, 'c'], [46, 3, 'c'], [47, 3, 'c'], [48, 3, 'c'], [49, 3, 'c'], [50, 3, 'c'], [45, 4, 'c'], [46, 4, 'c'], [47, 4, 'c'], [48, 4, 'c'], [49, 4, 'c'], [50, 4, 'c'], [45, 5, 'c'], [46, 5, 'c'], [47, 5, 'c'], [48, 5, 'c'], [49, 5, 'c'], [50, 5, 'c'], [45, 6, 'c'], [46, 6, 'c'], [47, 6, 'c'], [48, 6, 'c'], [49, 6, 'c'], [50, 6, 'c'], [46, 7, 'c'], [47, 7, 'c'], [48, 7, 'c'], [49, 7, 'c'], [47, 3, 'w'], [48, 3, 'w'], [47, 4, 'w']] },
    /* рух: огромная бурая птица, распахнутые крылья, жёлтый клюв, лапы вперёд (композитор) (64×60) */
    roc: {
      hd: true, unit: 2,
      rows: [
        '................NNNN........................NNNN................',
        '........nnnn..nnnnNNNNNNN..............NNNNNNNNnnn..nnnn........',
        '........nnNnnnnnnnnNNNNNnnnn........nnnnNNNNNnnnnnnnnNNn........',
        '....nnnnnnnNNnnnnnnnNnNNnnnnnnnnnnnnnnnnNNnNnnnnnnnNNnnnnnnn....',
        '..NNNnnnnnnnnNNnnnnnnNnNnnnnnnnnnnnnnnnnNnNnnnnnnNNnnnnnnnnNNNN.',
        '..NNNNNNnnnnnnnNNnnnnnNnnnnnnnnnnnnnnnnnnNnnnnnNNnnnnnnnNNNNNN..',
        '..NNNNNNNNNnnnnnnNNnnnnNnnnnnnnnnnnnnnnnNnnnnNNnnnnnnNNNNNNNNN..',
        '..NNNNNNNNNNNNnnnnnNNnnnNNnnnnnnnnnnnnNNnnnNNnnnnnNNNNNNNNNNNN..',
        '..NNNNNNNNNNNnNNNnnnnNNnnnNnnnnnnnnnnNnnnNNnnnnNNNnNNNNNNNNNNN..',
        '.....NNNNNNNNNnnnNNNnnnNNnnNnnnnnnnnNnnNNnnnNNNnnnNNNNNNNNN.....',
        '......NNNNNNNNNNnnnnNNNnnNNnNnnnnnnNnNNnnNNNnnnnNNNNNNNNNN......',
        '........NNNNNNNNNNnnnnnNNNnnnttttnnnnnNNNnnnnnNNNNNNNNNN........',
        '..........NNNNNNNNNnnnnnnnNnttttttnnnNnnnnnnnNNNNNNNNN..........',
        '...........NNNNNNNNNNnnnnnnntkttttnknnnnnnnNNNNNNNNNN...........',
        '............nNNNNNNNNNNnnnnnnttttnnnnnnnnNNNNNNNNNNn............',
        '.............nnNNNNNNNNNnnnnnnnnnnnnnnnnNNNNNNNNNnn.............',
        '..............nnNNNNNNNNNNnnyyyyyyyynnNNNNNNNNNNnn..............',
        '...............nnnNNNNNNNNNnyYYYYYYynNNNNNNNNNnnn...............',
        '.................nnnNNNNNNNnnyYYYYynnNNNNNNNnnn.................',
        '..................nnnNNNNNNNnyYYYYynNNNNNNNnnn..................',
        '...................nnnnNNNNnnnyYYynnnNNNNnnnn...................',
        '.....................nnnnnnnnnyyyynnnnnnnnn.....................',
        '......................nnnnnnnnnyynnnnnnnnn......................',
        '.......................nnnnnnnnyynnnnnnnn.......................',
        '........................nnnnnnttttnnnnnn........................',
        '.........................nnnnttttttnnnn.........................',
        '........................nnnnttttttttnnnn........................',
        '........................nnnnttttttttnnnn........................',
        '........................nnnnttttttttnnnn........................',
        '........................nnnttttttttttnnn........................',
        '........................nnnttttttttttnnn........................',
        '........................nnnttttttttttnnn........................',
        '........................nnnttttttttttnnn........................',
        '........................nnnttttttttttnnn........................',
        '.........................nnttttttttttnn.........................',
        '.........................nnnttttttttnnn.........................',
        '.........................nnnttttttttnnn.........................',
        '..........................nnttttttttnn..........................',
        '..........................nnnttttttnnn..........................',
        '...........................nnnttttnnn...........................',
        '...........................NNNNNNNNNN...........................',
        '.......................yy..NNNNNNNNNN..yy.......................',
        '......................yyy..NnnnnnnnnN.yyy.......................',
        '......................yyy..NnnnnnnnnN.yyy.......................',
        '......................yyy.NNnnnnnnnnNNyyy.......................',
        '......................yyy.NNnnnnnnnnNNyyy.......................',
        '.....................yyy..NNnnnnnnnnNyyy........................',
        '.....................yyy..NNnnnnnnnnNyyy........................',
        '.....................yyy.NNNnnnnnnnnNyyy........................',
        '.....................yyy.NNNnnnnnnnnNyyy........................',
        '.....................YY..NNNnnnnnnnnNYY.........................',
        '.....................YYY.NNNnnnnnnnnNYYY........................',
        '....................Y.YYNNNNnnnnnnnnYNYY........................',
        '....................Y.Y.YNNNnnnnnnnnYNYNY.......................',
        '...................Y..Y.YNNNNNNNNNNYNNYNY.......................',
        '...................Y..Y.NYNNNNNNNNNYNNYN.Y......................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
      ],
    },
    /* птица грома: синее оперение, светлая грудь, молнии из крыльев */
    thunderbird: { base: 'roc', tint: { n: 'b', N: 'B', t: 'c' }, extra: [[10, 10, 'y'], [11, 11, 'y'], [10, 12, 'y'], [11, 13, 'y'], [12, 14, 'y'], [53, 10, 'y'], [52, 11, 'y'], [53, 12, 'y'], [52, 13, 'y'], [51, 14, 'y'], [18, 6, 'y'], [19, 7, 'y'], [18, 8, 'y'], [45, 6, 'y'], [44, 7, 'y'], [45, 8, 'y']] },
    /* циклоп: одноглазый великан, красная повязка, камень в поднятой руке (56×60) */
    cyclops: {
      hd: true, unit: 2,
      rows: [
        '.............................................IIIIIIII...',
        '...........................................IIIIiiiiIII..',
        '..........................................IIiiiiiiiiIII.',
        '..........................................IiiiiiiiiiIII.',
        '..........................................IiiiiiiiiIIII.',
        '..........................................IIiiiiiIIIII..',
        '...........................................IIIIIIIIII...',
        '..............NNNNNNNNNNNN...................ssssss.....',
        '............NNNNNNNNNNNNNNNN................ssssss......',
        '...........NNNNNNNNNNNNNNNNNN..............ssssss.......',
        '...........NNsssssssssssssNNN.............ssssss........',
        '...........NssssssssssssssssN............ssssss.........',
        '...........NsssssssSSSSSssssN...........ssssss..........',
        '...........NssssssSwbbbwSsssN..........ssssss...........',
        '...........NssssssSwbkbwSsssN.........ssssss............',
        '...........NssssssSwbbbwSsssN........SSSSSS.............',
        '...........NsssssssSSSSSssssN.......SSSSSS..............',
        '...........NssssssssssssssssN......SSSSSS...............',
        '...........NsssssSSSSSSSsssSN.....SSSSSS................',
        '............NssssiSiSiSissSN.....SSSSSS.................',
        '............NssssSSSSSSSssSN....SSSSSS..................',
        '.............NsssssssssssSN....SSSSSS...................',
        '..............NNsssssssSNN....SSSSSS....................',
        '................NNNNNNNN.....SSSSSS.....................',
        '.............sssssssssssssssssssss......................',
        '.............sssssssssssssssssssss......................',
        '..........sssssssssssssssssssssssss.....................',
        '.........sssssssssssssssssssssssssss....................',
        '.........sssssssssssssssssssssssssss....................',
        '........ssssssssssssssssssssssssssss....................',
        '.......ssssssSSSSSSSSSSSSSSSssssssss....................',
        '.......ssssssSSSSSSSSSSSSSSSssssssss....................',
        '......sssssssSSSSSSSSSSSSSSSssssssss....................',
        '......ssssss.SSSSSSSSSSSSSSSsssssss.....................',
        '......ssssss.SSSSSSSSSSSSSSSsssssss.....................',
        '......ssssss.SSSSSSSSSSSSSSSsssssss.....................',
        '......ssssss.SSSSSSSSSSSSSSSsssssss.....................',
        '......ssssss.SSSSSSSSSSSSSSSsssssss.....................',
        '......ssssss.SSSSSSSSSSSSSSSsssssss.....................',
        '......ssssss.SSSSSSSSSSSSSSSsssssss.....................',
        '......ssssss.SSSSSSSSSSSSSSSsssssss.....................',
        '......SSSSSS.SSSSSSSSSSSSSSSSSSSSSS.....................',
        '......SSSSSS.SSSSSSSSSSSSSSSSSSSSSS.....................',
        '......SSSSSS.SSSSSSSSSSSSSSSSSSSSSS.....................',
        '......ssssss.SSSSSSSSSSSSSSSSSSSSSS.....................',
        '......ssssss.rrrrrrrrrrrrrrrrrrrrr......................',
        '.......ssss..rRrRrRrRrRrRrRrRrRrRr......................',
        '.............RRRRRRRRRRRRRRRRRRRRR......................',
        '.............rrrrrrrrrrrrrrrrrrrrr......................',
        '.............RRRRRRRRRRRRRRRRRRRRR......................',
        '.............sssssssss...sssssssss......................',
        '.............sssssssss...sssssssss......................',
        '.............sssssssss...sssssssss......................',
        '.............SSSSSSSSS...SSSSSSSSS......................',
        '.............SSSSSSSSS...SSSSSSSSS......................',
        '.............SSSSSSSSS...SSSSSSSSS......................',
        '.............sssssssss...sssssssss......................',
        '.............sssssssss...sssssssss......................',
        '............NNNNNNNNNNN.NNNNNNNNNNN.....................',
        '............DDDDDDDDDDD.DDDDDDDDDDD.....................',
      ],
    },
    /* король циклопов: кожа темнее, повязка в золото, золотая корона */
    cyclops_king: { base: 'cyclops', tint: { s: 'S', S: 'n', r: 'y', R: 'Y' }, extra: [[13, 5, 'y'], [14, 5, 'y'], [15, 5, 'y'], [16, 5, 'y'], [17, 5, 'y'], [18, 5, 'y'], [19, 5, 'y'], [20, 5, 'y'], [21, 5, 'y'], [22, 5, 'y'], [23, 5, 'y'], [24, 5, 'y'], [25, 5, 'y'], [26, 5, 'y'], [13, 6, 'y'], [14, 6, 'y'], [15, 6, 'y'], [16, 6, 'y'], [17, 6, 'y'], [18, 6, 'y'], [19, 6, 'y'], [20, 6, 'y'], [21, 6, 'y'], [22, 6, 'y'], [23, 6, 'y'], [24, 6, 'y'], [25, 6, 'y'], [26, 6, 'y'], [13, 4, 'y'], [14, 4, 'y'], [17, 4, 'y'], [18, 4, 'y'], [21, 4, 'y'], [22, 4, 'y'], [25, 4, 'y'], [26, 4, 'y'], [13, 7, 'Y'], [14, 7, 'Y'], [15, 7, 'Y'], [16, 7, 'Y'], [17, 7, 'Y'], [18, 7, 'Y'], [19, 7, 'Y'], [20, 7, 'Y'], [21, 7, 'Y'], [22, 7, 'Y'], [23, 7, 'Y'], [24, 7, 'Y'], [25, 7, 'Y'], [26, 7, 'Y']] },
    /* чудище: огромный бурый зверь на четырёх лапах, горб, когти, раскрытая пасть (композитор) (64×56) */
    behemoth: {
      hd: true, unit: 2,
      rows: [
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '....................................dddddd......................',
        '................................dddddddddd......................',
        '..........................dddddddddddddddd......................',
        '......................dddddddddddddddddddd..........d...........',
        '................dddddddddddddddddddddddddd..dd.nnnnnddd.........',
        '............dddddddddddddddddddddddddd......ddddnnnndddn........',
        '........ddddddddddddddddddddddddddd........nnddddnnndnnnn.......',
        '........ddddddddddddddddddddddddddddd.....nnnddnnnnnnnnnnn......',
        '........ddddddddddddddddddddddddddddddnn.nnnnnnnnnnnnnnnnnn.....',
        '........dddddddddddddddddddddddddddddddnnnnnnnnnnnyynnnnnnn.....',
        '........ddddddddddddddddddddddddddddddddnnnnnnnnnnknnnnnnnnn....',
        '............ddddddddddddddddddddddddddddnnnnnnnnnnnnnddddddn....',
        '............ddddddddddddddddddddddddddddnnnnnnnnnnndddddddddd...',
        '...........nddddddddddddddddddddddddddddnnnnnnnnnndddddddddddd..',
        '..........nnnddddddddddddddddddddddddddnnnnnnnnnndddddddddddddd.',
        '.........nnnnnddddddddddddddddddddddddnnnnnnnnnnndddddddddddddd.',
        '.......nnnnnnnnddddddddddddddddddddddnnnnnnnnnnnndddddddddddddd.',
        '......nnnnnnnnnnnddddddddddddddddddnnnnnnnnnnnnnnddddddddNNNNNN.',
        '....nnnnnnnnnnnnnnnnnddddddddddnnnnnnnnnnnnnnnnnnnddNwNNwNNwNNN.',
        '...nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnndNNNNNNNNNN..',
        '..nnnnnnnnnnnnnnnnnnnnnNNNNNNNNNNNNNNnnnnnnnnnnnnnnnNNNNNNNNNN..',
        'nnnnnnnnnnnnnnnnnnNNNNNNNNNNNNNNNNNNNNNNNNnnnnnnnnnnNNNNNNNNN...',
        'nnnnnnnnnnnnnnnNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNnnnnnnn..w.NwNNw...',
        'nnnnnnn..nnnnnNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNnnnnn.............',
        '.nnnn....nnnnNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNnnnn.............',
        '.nn.......nnNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNnn..............',
        '...........nNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNn...............',
        '............nNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNn................',
        '.........ddddddddnnnnnnnnNNNNNNNNNNNNddddddddnnnnnnnn...........',
        '.........ddddddddnnnnnnnnNNNNNNNNNNNNddddddddnnnnnnnn...........',
        '.........ddddddddnnnnnnnnNNNNNNNNNNNNddddddddnnnnnnnn...........',
        '.........ddddddddnnnnnnnnNNNNNNNNNNNNddddddddnnnnnnnn...........',
        '.........ddddddddnnnnnnnnnnnnnnnnnnn.ddddddddnnnnnnnn...........',
        '.........ddddddddnnnnnnnn............ddddddddnnnnnnnn...........',
        '.........ddddddddnnnnnnnn............ddddddddnnnnnnnn...........',
        '........ddddddddnnnnnnnnn...........ddddddddnnnnnnnnn...........',
        '........ddddddddnnnnnnnnn...........ddddddddnnnnnnnnn...........',
        '........ddddddddnnnnnnnnn...........ddddddddnnnnnnnnn...........',
        '........ddddddddnnnnnnnnn...........ddddddddnnnnnnnnn...........',
        '........ddddddddddddddddn...........ddddddddddddddddn...........',
        '.......dddddddddddddddddd..........dddddddddddddddddd...........',
        '.......dddddddddddddddddd..........dddddddddddddddddd...........',
        '........iidiidiiiidiidii............iidiidiiiidiidii............',
        '........ii.ii.iiii.ii.ii............ii.ii.iiii.ii.ii............',
        '........ii.ii.iiii.ii.ii............ii.ii.iiii.ii.ii............',
        '........ii.ii.iiii.ii.ii............ii.ii.iiii.ii.ii............',
      ],
    },
    /* древнее чудище: чёрно-серая шерсть, когти светлее и длиннее, глаз алый */
    ancient_behemoth: { base: 'behemoth', tint: { n: 'u', N: 'z', d: 'E', i: 'L', y: 'r' } },
  });
})();
