/* ============================================================================
   view/sprites_inferno.js — спрайты существ фракции Инферно.
   Формат — см. docs/sprite-guide.md. Подключать после js/view/sprites.js.
   Уровни: 1 бес/фамильяр, 2 гог/магог, 3 адская гончая/цербер, 4 демон/рогатый демон,
   5 порождение ада/владыка бездны, 6 ифрит/султан ифритов, 7 дьявол/архидьявол.
   ========================================================================== */
(function () {
  'use strict';
  H3.Sprites.defineMany({

    /* ---------- 1. Бес (20×20): красный чертёнок, рожки, крылья, хвост ---------- */
    imp: {
      rows: [
        '.......k.....k......',
        '.......kk...kk......',
        '......kRkkkkkRk.....',
        '.....korrrrrrrrk....',
        '....korrykrrykrrk...',
        '....krrrrrrrrrrrk...',
        '....kRrrrkkkkkrrk...',
        '.....kRRrrrrrrRk....',
        '.kk...kkkRRRkkk.....',
        'kRRk..kRrrrrrk..kk..',
        'kRRRk.korrrrrrk.kRk.',
        '.kRRRkkRrrrrrrkkRRk.',
        '..kRRRkRrrrrrrkRRk..',
        '...kkkkkRrrrrkkkk...',
        '......kRRrrrrRk.....',
        '.....kkRRkkkRRk.....',
        '....kR.kRk.kRk......',
        '...kRk.kRk.kRk......',
        '..kRRk.kRk.kRk......',
        '...kk..kkk.kkk......',
      ],
    },

    /* Фамильяр: фиолетовый бес с золотым трезубцем */
    familiar: {
      base: 'imp',
      tint: { r: 'p', R: 'P', o: 'A' },
      extra: [
        [17, 5, 'y'], [19, 5, 'y'], [17, 6, 'y'], [18, 6, 'y'], [19, 6, 'y'],
        [18, 7, 'y'], [18, 8, 'y'], [18, 9, 'y'], [18, 10, 'y'], [18, 11, 'y'],
        [18, 12, 'y'], [18, 13, 'y'], [18, 14, 'y'],
      ],
    },

    /* ---------- 2. Гог (24×21): красно-коричневый демон, огненный шар в руке ---------- */
    gog: {
      rows: [
        '......k.......k.........',
        '......kk.....kk.........',
        '.....kOkkkkkkkOk........',
        '....kOOOOOOOOOOk........',
        '...kOOoykOOoykOOk.......',
        '...kOOOOOOOOOOOOk.......',
        '...kNOOOkkkkkOOOk.......',
        '....kNNOOOOOONNk....kk..',
        '.....kkkNNNNkkk....kffFk',
        '....kOOOOOOOOOOk..kfffFk',
        '...kOOkOOOOOOOkOkkFFFFk.',
        '..kOOk.kOOOOOk.kOOOkkk..',
        '..kOk..kOOOOOk..kkkk....',
        '..kk...kNOOOOk..........',
        '.......kNNOOOk..........',
        '.......kNNNNNk..........',
        '......kOOkkkOOk.........',
        '.....kOOk...kOOk........',
        '.....kONk...kONk........',
        '....kNNk.....kNNk.......',
        '....kkkk.....kkkk.......',
      ],
    },

    /* Магог: жёлтые рога, шар больше и ярче */
    magog: {
      base: 'gog',
      extra: [
        [6, 2, 'y'], [14, 2, 'y'], [7, 1, 'y'], [13, 1, 'y'],
        [19, 6, 'k'], [20, 6, 'k'], [21, 6, 'k'], [22, 6, 'k'],
        [19, 7, 'k'], [20, 7, 'f'], [21, 7, 'f'], [22, 7, 'F'], [23, 7, 'k'],
        [18, 8, 'k'], [19, 8, 'f'], [20, 8, 'w'], [21, 8, 'f'],
        [20, 9, 'w'],
      ],
    },

    /* ---------- 3. Адская гончая (24×20): чёрно-красный пёс, огненная грива ---------- */
    hell_hound: {
      rows: [
        '.................kk.....',
        '................kEuk....',
        '.......kkkFkk...kEuuk...',
        '..kk..kEuFfFukkkkEuuuk..',
        '..kFFkEuuFuuuuuuuuuufkk.',
        '.kFfkEuuuuuuuuuuuuuuukuk',
        '.kFkEuuuuuuuuuuuuuuuuuuk',
        '.kkEuzzzzuuuuuuuuuuukkkk',
        '.kEuzzzzzzzuuuuuuuuk.rrk',
        'kEuzzzzzzzzzzzuuuuuukkk.',
        'kuzzzzzzzzzzzzzzzzuuk...',
        'kkzzzzzzzzzzzzzzzzzzk...',
        '.kzzkkkzzzzzzzkkkzzzk...',
        '.kzzk.kzzk..kzzk.kzzk...',
        '.kzk..kzzk..kzzk..kzk...',
        '.kzk..kzk...kzk...kzk...',
        'kzk...kzk...kzk...kzzk..',
        'kzk..kzzk..kzzk...kzzk..',
        'kzzk.kzzk..kzzk...kzzk..',
        'kkkk.kkkk..kkkk...kkkk..',
      ],
    },

    /* Цербер (24×22): три головы — редрав на базе гончей */
    cerberus: {
      rows: [
        '.................kk.....',
        '................kEuk....',
        '.......kkkFkk...kEuuk...',
        '..kk..kEuFfFukkkkEuuuk..',
        '..kFFkEuuFuuuuuuuuuufkk.',
        '.kFfkEuuuuuuuuuuuuuuukuk',
        '.kFkEuuuuuuuuuuuuuuuuuuk',
        '.kkEuzzzzuuuuuuuuuukkkkk',
        '.kEuzzzzzzzuuuuuuukEuukk',
        'kEuzzzzzzzzzzzuuuukuuufk',
        'kuzzzzzzzzzzzzzuuukuuuuk',
        'kkzzzzzzzzzzzzzzuuukuukk',
        '.kzzkkkzzzzzzzzuuuukkrrk',
        '.kzzk.kzzk..kzzzuuuukkkk',
        '.kzk..kzzk..kzzkuuuukEuk',
        '.kzk..kzk...kzk.kuuuuuuk',
        'kzk...kzk...kzk.kuuuuufk',
        'kzk..kzzk..kzzk.kkuuukkk',
        'kzzk.kzzk..kzzk..kuukrrk',
        'kkkk.kkkk..kkkk...kkkkkk',
      ],
    },

    /* ---------- 4. Демон (22×25): мускулистый красный демон с когтями ---------- */
    demon: {
      rows: [
        '......................',
        '......................',
        '.......k......k.......',
        '.......kk....kk.......',
        '......kRkkkkkkRk......',
        '.....korrrrrrrrk......',
        '....korrykrrrykrk.....',
        '....krrrrrrrrrrrk.....',
        '....kRrrrkkkkkrrk.....',
        '.....kRRrwkwkwRk......',
        '......kkRRRRRRkk......',
        '...kkkkorrrrrrrkkkk...',
        '..korrkorrrrrrrkorrk..',
        '.korrrkrrrrrrrrkrrrrk.',
        '.krrrk.kRrrrrrRk.kRrk.',
        '.kRRk..kRrrrrrRk..kRk.',
        '.kwkwk.kRRrrrrRk.kwkwk',
        '.kkkkk.kRRRRRRRk.kkkkk',
        '.......kDDkkkDDk......',
        '......kRRk...kRRk.....',
        '.....kRRk.....kRRk....',
        '.....kRk.......kRk....',
        '.....kRk.......kRk....',
        '....kRRk.......kRRk...',
        '....kkkk.......kkkk...',
      ],
    },

    /* Рогатый демон: большие костяные рога, темнее */
    horned_demon: {
      base: 'demon',
      tint: { o: 'r', r: 'R', R: 'D' },
      extra: [
        [5, 0, 'k'], [6, 0, 'k'], [15, 0, 'k'], [16, 0, 'k'],
        [5, 1, 'k'], [6, 1, 'i'], [7, 1, 'k'], [14, 1, 'k'], [15, 1, 'i'], [16, 1, 'k'],
        [6, 2, 'k'], [7, 2, 'i'], [8, 2, 'k'], [13, 2, 'k'], [14, 2, 'i'], [15, 2, 'k'],
        [7, 3, 'i'], [8, 3, 'k'], [13, 3, 'k'], [14, 3, 'i'],
        [7, 4, 'I'], [14, 4, 'I'],
      ],
    },

    /* ---------- 5. Порождение ада (28×28): крупный демон, крылья, кнут ---------- */
    pit_fiend: {
      rows: [
        '........k..........k........',
        '.......kk..........kk.......',
        '.......kRkkkkkkkkkkRk.......',
        '......korrrrrrrrrrrrk.......',
        '.....korrrrykrrrrykrrk......',
        '.....krrrrrrrrrrrrrrrk......',
        '.....kRrrrrkkkkkkkrrrk......',
        '......kRRrrwkwkwkrrRk.......',
        '.kk....kkkRRRRRRRkkk...kk...',
        'kPPk..korrrrrrrrrrrrk.kPPk..',
        'kPPPkkorrrkOOOOOOkrrrkkPPPk.',
        'kPPPPkrrrkODOOOOOOkrrrkPPPPk',
        'kPPPPkrrkODOOOOOOOOkrrkPPPPk',
        '.kPPPkRrkODDOOOOOOOkrrkPPPkN',
        '.kPPPkRrkOODDDOOOOOkrRkPPPkN',
        '..kPPkRRk.kDDDDDDk.kRRkPPk.N',
        '..kkkkkkk..kkkkkkk..kkkNkk.N',
        '.......kRrrrrrrrrRk.....N..N',
        '.......kDDDkkkkDDDk......NN.',
        '......kRRRk...kRRRk.........',
        '......kRRk.....kRRk.........',
        '.....kRRk.......kRRk........',
        '.....kRrk.......kRrk........',
        '.....kRrk.......kRrk........',
        '.....kRRk.......kRRk........',
        '....kRRk.........kRRk.......',
        '....kkkk.........kkkk.......',
        '............................',
      ],
    },

    /* Владыка бездны: золотые доспехи, трезубец вместо кнута */
    pit_lord: {
      base: 'pit_fiend',
      tint: { O: 'y', D: 'Y', N: '.' },
      extra: [
        [24, 7, 'y'], [26, 7, 'y'], [24, 8, 'y'], [25, 8, 'y'], [26, 8, 'y'],
        [25, 9, 'y'], [25, 10, 'y'], [25, 11, 'y'], [25, 12, 'y'], [25, 13, 'y'],
        [25, 14, 'y'], [25, 15, 'y'], [25, 16, 'y'], [25, 17, 'y'], [25, 18, 'y'],
        [25, 19, 'y'], [25, 20, 'y'],
      ],
    },

    /* ---------- 6. Ифрит (28×28): огненный дух с ятаганом, нижняя часть — пламя ---------- */
    efreet: {
      rows: [
        '..........kkkkk.............',
        '.........kFffFfk............',
        '........kFfkkkkfk...........',
        '........kokoooookk..........',
        '.......kooosykoykok.........',
        '.......koooooooookk.........',
        '.......kOooookkkook.......kk',
        '........kOOooooOOk.......klk',
        '.........kkkOOOkk.......klek',
        '.......kkkooooookkk.....klek',
        '.....kkoookoooooooook..klek.',
        '....koooookooooooookookkek..',
        '...koOOookkOoooooookoookYk..',
        '...kOOOk..kOoooooookkoook...',
        '...kOOk...kOOoooooOk.kkkk...',
        '...kkk....kOOOooOOOk........',
        '...........kOOOOOOk.........',
        '..........kFFFFFFFFk........',
        '.........kFfFFffFFFFk.......',
        '........kFffFFFfFFFFFk......',
        '.......kFFfFFFFFfFFFk.......',
        '.......kFFFFkFFFFFFFk.......',
        '........kFFk.kFFFFFk........',
        '........kFk..kFFfFk.........',
        '.........k....kFFk..........',
        '..............kFk...........',
        '...............k............',
        '............................',
      ],
    },

    /* Султан ифритов: золотая корона, синее пламя */
    efreet_sultan: {
      base: 'efreet',
      tint: { F: 'b', f: 'c' },
      extra: [
        [9, 0, 'k'], [10, 0, 'y'], [11, 0, 'k'], [12, 0, 'y'], [13, 0, 'k'], [14, 0, 'y'], [15, 0, 'k'],
        [10, 1, 'y'], [11, 1, 'y'], [12, 1, 'y'], [13, 1, 'y'], [14, 1, 'y'],
        [10, 2, 'Y'], [11, 2, 'Y'], [12, 2, 'Y'], [13, 2, 'Y'], [14, 2, 'Y'], [15, 2, 'k'],
      ],
    },

    /* ---------- 7. Дьявол (32×32): высокий рогатый с трезубцем и крыльями ---------- */
    devil: {
      rows: [
        '.........k...........k..........',
        '........kk...........kk.........',
        '........kRk.........kRk.........',
        '........kRkkkkkkkkkkkRk.........',
        '.........korrrrrrrrrrk..........',
        '........korrrrykrrrykrk.........',
        '........krrrrrrrrrrrrrk..k.k.k..',
        '........kRrrrrrkkkkkrrk.kykykyk.',
        '.........kRRrrrwkwkwrk..kyyyyyk.',
        '.kk.......kkkRRRRRRkk....kkykk..',
        'kuuk....kkkorrrrrrrrkkk...kyk...',
        'kuuuk..korrrkrrrrrrrkrrk..kyk...',
        'kuuuuk.krrrkrrrrrrrrrkrrk.kyk...',
        'kuuuuukkrrkrrRrrrrrRrkrrkkkyk...',
        '.kuuuuukRrkrrRrrrrrRrrkrrkkyk...',
        '.kuuuuukRrkrrRrrrrrRrrkrrrkyk...',
        '..kuuuukRRkrRRrrrrrRRrkkrrkyk...',
        '..kuuuuk.kkrRRRrrrRRRrk.kRkkyk..',
        '...kuuuk..kRRRrrrrrRRRk..k.kyk..',
        '...kkkkk..kRRRkkkkkRRRk....kyk..',
        '..........kDDDk...kDDDk....kyk..',
        '..........kRRRk...kRRRk....kyk..',
        '.........kRrRk.....kRrRk...kyk..',
        '.........kRrRk.....kRrRk...kyk..',
        '.........kRrk.......kRrk...kyk..',
        '.........kRRk.......kRRk...kyk..',
        '........kRRk.........kRRk..kyk..',
        '........kRRk.........kRRk..kyk..',
        '.......kDDk...........kDDk..k...',
        '.......kkkk...........kkkk......',
        '................................',
        '................................',
      ],
    },

    /* Архидьявол: чёрно-фиолетовый с золотом, огненная аура */
    arch_devil: {
      base: 'devil',
      tint: { r: 'x', R: 'P', o: 'p', D: 'Y', u: 'z' },
      extra: [
        [9, 0, 'f'],
        [21, 0, 'f'],
        [6, 30, 'F'],
        [7, 30, 'f'],
        [8, 30, 'F'],
        [9, 30, 'f'],
        [10, 30, 'F'],
        [11, 30, 'F'],
        [21, 30, 'F'],
        [22, 30, 'f'],
        [23, 30, 'F'],
        [24, 30, 'f'],
        [25, 30, 'F'],
        [7, 31, 'F'],
        [9, 31, 'F'],
        [11, 31, 'F'],
        [22, 31, 'F'],
        [24, 31, 'F'],
        [13, 9, 'y'],
        [14, 9, 'y'],
        [15, 9, 'y'],
        [16, 9, 'y'],
        [17, 9, 'y'],
      ],
    },
  });
})();
