/* ============================================================================
   view/sprites_factory_hd.js — существа Фабрики в крупной сетке (unit 2), стиль Б:
   без контурной линии, тона кладёт рисунок. Собирается скриптом dev/proto/factory_hd.py.
   ========================================================================== */
(function () {
  'use strict';
  H3.Sprites.defineMany({
    /* полурослик: маленький, шляпа с полями, зелёная куртка и жилет, рогатка с камнем в вытянутой руке, босые ноги (36×44) */
    halfling: {
      hd: true, unit: 2,
      rows: [
        '..........HHHHHHHHHH................',
        '.........HHHHHHHHHHHH.........DDDD..',
        '.........HHHHHHHHHHHH.........DeeD..',
        '.........HHHHHHHHHHHH.......DDDeeDDD',
        '.........HHHHHHHHHHHH.......DDDDDDDD',
        '.....HHHHHHHHHHHHHHHHHHHH...nn....nn',
        '....HHHHHHHHHHHHHHHHHHHHHH..nn....nn',
        '.........ssssssssssss........nn..nn.',
        '........ssssssssssssss........nn.nn.',
        '........ssssswkwsswkws........nn.nn.',
        '........ssssswkwsswkws........nnnn..',
        '........ssssssssssssss.........nnn..',
        '........ssssssSSSSssss.........nnn..',
        '.........ssssssssssss..........nnn..',
        '..........ssssssssss...........nnn..',
        '........GGGGGGGGGGGGGGGGGGG....nnn..',
        '......GGGGGGGGGGGGGGGGGGGGGGGGssss..',
        '.....GGGGGGGGIIIIIIIGGGGGGGGGGssss..',
        '.....GGGGGGGGIIIIIIIGGGGGGGGGGssss..',
        '.....GGGGGGGGIIIIIIIGGGGGGGGGGssss..',
        '.....GGGGGGGGIIIIIIIGGGGGGGGGGssss..',
        '.....GGGGGGGGIIIIIIIGGGGGGGGGGssss..',
        '.....GGGGGGGGIIIIIIIGGGGGGG.........',
        '.....GGGGGGGGIIIIIIIGGGGGG..........',
        '.....GGGGGGGGIIIIIIIGGGGGG..........',
        '.....GGGGGGGGIIIIIIIGGGGGG..........',
        '.....GGGGGGGGIIIIIIIGGGGGG..........',
        '.....GGGGGGGGIIIIIIIGGGGGG..........',
        '.....GGGG.GGGIIIIIIIGGGGG...........',
        '.....GGGG.GGGIIIIIIIGGGGG...........',
        '.....ssss.DDDDDyyyDDDDD.............',
        '.....ssss.DDDDDyyyDDDDD.............',
        '..........TTTTTTTTTTTTT.............',
        '..........TTTTTTTTTTTTT.............',
        '..........TTTTTTTTTTTTT.............',
        '..........TTTTTT.TTTTTT.............',
        '..........TTTTTT.TTTTTT.............',
        '..........TTTTTT.TTTTTT.............',
        '..........TTTTTT.TTTTTT.............',
        '..........TTTTTT.TTTTTT.............',
        '..........TTTTTT.TTTTTT.............',
        '.........nnnnnnn.nnnnnnn............',
        '.........nnnnnnn.nnnnnnn............',
        '........nnnnnnnn.nnnnnnnn...........',
      ],
    },
    /* гренадёр: куртка в хаки, шляпа бурая, в рогатке бомба с искрящимся фитилём, гранаты на поясе */
    halfling_grenadier: { base: 'halfling', tint: { G: 'H', H: 'd', e: 'E' }, extra: [[11, 30, 'e'], [12, 30, 'e'], [20, 30, 'e'], [21, 30, 'e'], [11, 31, 'e'], [12, 31, 'e'], [20, 31, 'e'], [21, 31, 'e'], [31, 0, 'f'], [32, 0, 'f'], [31, 1, 'f'], [32, 1, 'f']] },
    /* механик: очки на лбу, синяя рубаха, кожаный фартук с карманом, большой гаечный ключ (40×48) */
    mechanic: {
      hd: true, unit: 2,
      rows: [
        '...............NNNNNNNN........eee..eee.',
        '..............NNNNNNNNNN.......eee..eee.',
        '.............NecccecccceN......eee..eee.',
        '.............NecccecccceN......eeeeeeee.',
        '.............NNeeeeeeeeNN......eeeeeeee.',
        '.............NNNNNNNNNNNN.......eeeeee..',
        '.............Nsssssssssss.........ele...',
        '.............Nsssssssssss.........ele...',
        '.............Nssswkwsswkw.........ele...',
        '.............Nssswkwsswkw.........ele...',
        '..............sssssssssss.........ele...',
        '..............sssssSSSsss.........ele...',
        '...............sssssssss..........ele...',
        '................sssssss...........ele...',
        '............bbbbbbbbbbbbbbbb......ele...',
        '..........bbbbbbbbbbbbbbbbbbbb....ele...',
        '.........bbbbbDDDDDDDDbbbbbbbbbb..ele...',
        '.........bbbbbDDDDDDDDbbbbbbbbbbbsssss..',
        '.........bbbbbDDDDDDDDbbbbbbbbbbbsssss..',
        '.........bbbbbDDDDDDDDbbbbbb.....sssss..',
        '.........bbbb.DDDDDDDDDDDDDbbb..........',
        '.........bbbb.DDDDDDDDDDDDDbbb..........',
        '.........bbbb.DDDDDDDDDDDDDbbb..........',
        '.........bbbb.DDDDDDDDDDDDDbbb..........',
        '.........bbbb.DDDnnnnnnnDDDbbb..........',
        '.........bbbb.DDDnnnnnnnDDDbbb..........',
        '.........bbbb.DDDnnnnnnnDDDbbb..........',
        '.........bbbb.DDDnnnnnnnDDDbbb..........',
        '.........bbbb.DDDnnnnnnnDDDbbb..........',
        '.........bbbb.DDDnnnnnnnDDDbbb..........',
        '.........ssss.DDDDDDDDDDDDDbbb..........',
        '.........ssss.DDDDDDDDDDDDDbbb..........',
        '.........ssss.DDDDDDDDDDDDDbbb..........',
        '.........ssss.DDDDDDDDDDDDDbbb..........',
        '..............DDDDDDDDDDDDDbbb..........',
        '..............DDDDDDDDDDDDDbbb..........',
        '..............DDDDDDDDDDDDDbbb..........',
        '..............DDDDDDDDDDDDDbbb..........',
        '..............DDDDDDDDDDDDD.............',
        '..............DDDDDDDDDDDDD.............',
        '..............eeeeee.eeeeee.............',
        '..............eeeeee.eeeeee.............',
        '..............eeeeee.eeeeee.............',
        '..............eeeeee.eeeeee.............',
        '..............eeeeee.eeeeee.............',
        '.............DDDDDDD.DDDDDDD............',
        '.............DDDDDDD.DDDDDDD............',
        '............DDDDDDDD.DDDDDDDD...........',
      ],
    },
    /* инженер: рубаха в рыжий, ключ и очки из латуни, шестерня на нагруднике */
    engineer: { base: 'mechanic', tint: { b: 'o', n: 'y', e: 'Y' }, extra: [[16, 17, 'y'], [17, 17, 'y'], [18, 17, 'y'], [19, 17, 'y'], [16, 18, 'y'], [17, 18, 'y'], [18, 18, 'y'], [19, 18, 'y'], [17, 16, 'y'], [18, 16, 'y'], [17, 19, 'y'], [18, 19, 'y']] },
    /* броненосец: песочный панцирь пластинами, бурая голова с вытянутой мордой, четыре лапы, хвост (композитор) (52×48) */
    armadillo: {
      hd: true, unit: 2,
      rows: [
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '....................................................',
        '...................NttttttNNt.......................',
        '................ttNNttttttNNtttt....................',
        '.............tttttNNttttttNNttttttN.................',
        '............ttttttNNttttttNNttttttNN................',
        '..........NNttttttNNttttttNNttttttNNtt..............',
        '.........tNNttttttNNttttttNNttttttNNttt.............',
        '........ttNNttttttNNttttttNNttttttNNtttt............',
        '.......tttNNttttttNNttttttNNttttttNNttttt...........',
        '......ttttNNttttttNNttttttNNttttttNNttdttt.d........',
        '......ttttNNttttttNNttttttNNttttttNNttddtt.dd.......',
        '.....tttttNNttttttNNttttttNNttttttNNtttddttddd......',
        '.....tttttNNttttttNNttttttNNttttttNNtttdddddddd.....',
        '....ttttttNNttttttNNttttttNNttttttNNttddddddddd.....',
        '....ttttttNNttttttNNttttttNNttttttNNdddddddddddd....',
        '....ttttttNNttttttNNttttttNNttttttNdddddddddddddd...',
        '....ttttttNNttttttNNttttttNNttttttNdddddddddddddd...',
        '....ttttttNNttttttNNttttttNNttttttddddddddddyydddd..',
        '....ttttttNNttttttNNttttttNNttttttddddddddddykddddd.',
        '....ttttttNNttttttNNttttttNNttttttddddddddddddddddkd',
        '....ttttttNNttttttNNttttttNNttttttddddddddddddddddkd',
        '.....ttddtNNttttttNNttttttNNttttttNddddddddddddddd..',
        '.....tdddtNNttttttNNttttttNNttttttNdddddddddddddd...',
        '......ddddNNttttttNNttttttNNttttttNNdddddddddddd....',
        '.....ddddddNtTTTTTTTTTTTTTTTTTTTTTTNttdddddddd......',
        '....dddddddTTTTTTTTTTTTTTTTTTTTTTTTTTTTTt...........',
        '...ddddddddTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT.........',
        '..dddddddddddddddTdddddddTTTTdddddddTddddddd........',
        '..dddddddTdddddddTdddddddTTTTdddddddTddddddd........',
        '.ddddddd.ddddddddTdddddddTTTTddddddddddddddd........',
        'ddddddd...dddddddddddddddddddddddddddddddddd........',
        'dddddd....dddddddddddddddddddddddddddddddddd........',
        '.dddd.....iidiidddiidiiddddddiidiidd.iidiidd........',
        '..dd......iidiidddiidiiddddddiidiidd.iidiidd........',
        '..........ii.ii...ii.ii......ii.ii...ii.ii..........',
      ],
    },
    /* вожак броненосцев: панцирь в бронзу со светлыми швами, тело темнее, костяные шипы на хребте */
    bellwether_armadillo: { base: 'armadillo', tint: { t: 'O', N: 'i', d: 'D' }, extra: [[14, 15, 'i'], [15, 15, 'i'], [14, 14, 'i'], [15, 14, 'i'], [14, 13, 'i'], [15, 13, 'i'], [15, 12, 'i'], [22, 15, 'i'], [23, 15, 'i'], [22, 14, 'i'], [23, 14, 'i'], [22, 13, 'i'], [23, 13, 'i'], [23, 12, 'i'], [30, 15, 'i'], [31, 15, 'i'], [30, 14, 'i'], [31, 14, 'i'], [30, 13, 'i'], [31, 13, 'i'], [31, 12, 'i']] },
    /* автоматон: паровой робот из латуни, труба с паром, топка на груди, заклёпки, поршневые руки (48×54) */
    automaton: {
      hd: true, unit: 2,
      rows: [
        '.........................lllll..................',
        '........................lllllll.................',
        '.........................lllll..................',
        '..........................uuu...................',
        '..........................uuu...................',
        '..............YYYYYYYYYYYYYYYYYY................',
        '.............YYYYYYYYYYYYYYYYYYYY...............',
        '.............YYyyyyyyyyyyyyyyyyYY...............',
        '.............YYyyyDDDDyyyDDDDyyYY...............',
        '.............YYyyyDccDyyyDccDyyYY...............',
        '.............YYyyyDccDyyyDccDyyYY...............',
        '.............YYyyyDDDDyyyDDDDyyYY...............',
        '.............YYyyyyyyyyyyyyyyyyYY...............',
        '.............YYyyyyEEEEEEEEyyyyYY...............',
        '.............YYyyyyyyyyyyyyyyyyYY...............',
        '..............YYYYYYYYYYYYYYYYYY................',
        '...................uuuuuu.......................',
        '...................uuuuuu.......................',
        '........YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY..........',
        '......YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY........',
        '.....uuuuuYYyyyyyyyyyyyyyyyyyyyyYYuuuuu.........',
        '.....uuuuuYYyyyyyyyyyyyyyyyyyyyyYYuuuuu.........',
        '.....uuuuuYYyyyyyyyyyyyyyyyyyyyyYYuuuuu.........',
        '.....uuuuuYYyyNNyyyyyyyyyyyyNNyyYYuuuuu.........',
        '.....uuuuuYYyyNNyyyyyyyyyyyyNNyyYYuuuuu.........',
        '.....uuuuuYYyyNNyyyyyyyyyyyyNNyyYYuuuuu.........',
        '.....uuuuuYYyyyyyyyOOOOOOyyyyyyyYYuuuuu.........',
        '.....uuuuuYYyyyyyyyOOOOOOyyyyyyyYYuuuuu.........',
        '.....uuuuuYYyyyyyyOOffffOOyyyyyyYYuuuuu.........',
        '.....uuuuuYYyyyyyyOffFFffOyyyyyyYYuuuuu.........',
        '.....uuuuuYYyyyyyyOffFFffOyyyyyyYYuuuuu.........',
        '.....uuuuuYYyyyyyyOffFFffOyyyyyyYYuuuuu.........',
        '.....uuuuuYYyyyyyyOOffffOOyyyyyyYYuuuuu.........',
        '.....uuuuuYYyyyyyyOOffffOOyyyyyyYYuuuuu.........',
        '.....uuuuuYYyyyyyyyOOOOOOyyyyyyyYYuuuuu.........',
        '.....uuuuuYYyyNNyyyyyyyyyyyyNNyyYYuuuuu.........',
        '.....uuuuuYYyyNNyyyyyyyyyyyyNNyyYYuuuuu.........',
        '.....uuuuuYYyyNNyyyyyyyyyyyyNNyyYYuuuuu.........',
        '...YYYYYY.YYyyyyyyyyyyyyyyyyyyyyYY.YYYYYY.......',
        '...YYYYYY.YYyyyyyyyyyyyyyyyyyyyyYY.YYYYYY.......',
        '...YYYYYY.YYyyyyyyyyyyyyyyyyyyyyYY.YYYYYY.......',
        '...YYYYYY.YYYYYYYYYYYYYYYYYYYYYYYY.YYYYYY.......',
        '..........YYYYYYYYYYYYYYYYYYYYYYYY..............',
        '.............uuuuuuuu....uuuuuuuu...............',
        '.............uuuuuuuu....uuuuuuuu...............',
        '.............YYYYYYYY....YYYYYYYY...............',
        '.............YYYYYYYY....YYYYYYYY...............',
        '.............uuuuuuuu....uuuuuuuu...............',
        '.............uuuuuuuu....uuuuuuuu...............',
        '.............uuuuuuuu....uuuuuuuu...............',
        '.............uuuuuuuu....uuuuuuuu...............',
        '...........YYYYYYYYYY..YYYYYYYYYY...............',
        '...........YYYYYYYYYY..YYYYYYYYYY...............',
        '...........YYYYYYYYYY..YYYYYYYYYY...............',
      ],
    },
    /* автоматон-страж: сталь темнеет, глаза и топка горят алым */
    sentinel_automaton: { base: 'automaton', tint: { Y: 'E', y: 'e', u: 'z', O: 'D', f: 'r', F: 'f', c: 'r' } },
    /* песчаный червь: кольчатое тело поднимается из песка, пасть-воронка кверху с рядами зубов (композитор) (60×60) */
    sandworm: {
      hd: true, unit: 2,
      rows: [
        '............................................................',
        '............................MMiiiiiiiiiiiiiiiiiiiiiiii......',
        '............................MMiiiiiiiiiiiiiiiiiiiiiiii......',
        '.............................MMiiMRiiRRiiRRiiRRiiMMii.......',
        '.............................MMiiMMiiMMiiMMiiMMiiMMii.......',
        '..............................MMMMMMMMMMMMMMMMMMMMMM........',
        '..............................MMMMMMMMMMMMMMMMMMMMMM........',
        '...............................MMMMMMMMMMMMMMMMMMMM.........',
        '..............................dMMiiiiiiiiiiiiiiiiMMd........',
        '..............................ddMMiiMMiiMMiiMMiiMMdd........',
        '.............................ddtMMiiMMiiMMiiMMiiMMtdd.......',
        '.............................ddttMMMMMMMMMMMMMMMMttdd.......',
        '.............................ddttMMMMMMMMMMMMMMMMttdd.......',
        '.............................ddttttttttttttttttttttdd.......',
        '..............................ddttttttttttttttttttdd........',
        '..............................dddttttttttttttttttddd........',
        '..............................ddddttttttttttttttddd.........',
        '..............................dddddddttttttttddddd..........',
        '..............................ddttdddddddddddddddd..........',
        '..............................ddtttttddddddddtttdd..........',
        '.............................ddddttttttttttttttddd..........',
        '............................ddddddttttttttttttddd...........',
        '............................ddttdddttttttttttddd............',
        '............................ddtttddddttttttddddd............',
        '............................ddttttdddddddddddddd............',
        '............................ddtttttttddddddtttdd............',
        '............................dddttttttttttttttddd............',
        '...........................ddddttttttttttttttdd.............',
        '...........................ddtddttttttttttttdd..............',
        '...........................ddtddddttttttttdddd..............',
        '...........................ddtttddddddddddddd...............',
        '...........................ddttttdddddddddddd...............',
        '...........................ddttttttttttttttdd...............',
        '..........................dddttttttttttttttdd...............',
        '.........................dddddttttttttttttddd...............',
        '........................dddtdddttttttttttddd................',
        '........................ddtttddddttttttdddd.................',
        '........................ddttttdddddddddddd..................',
        '........................ddttttttdddddddddd..................',
        '.......................dddttttttttttttttdd..................',
        '......................dddddttttttttttttddd..................',
        '......................ddtdddttttttttttddd...................',
        '.....................ddtttdddttttttttddd....................',
        '.....................ddttttddddttttdddd.....................',
        '...................ddddtttttdddddddddd......................',
        '..................dddddttttttttdddddd.......................',
        '..................ddttddttttttttttdd........................',
        '...............ddddtttdddttttttttddd........................',
        '..............dddddttttddddttttdddd.........................',
        '.............dddtddtttttdddddddddd..........................',
        '.........dddddtttddttttttttdddd.............................',
        '........ddddddttttddttttttttdd..............................',
        '...dddddddttddttttddddttttdddd..............................',
        '..dddddddtttddtttttddddddddddT..............................',
        '..ddtttddttttdddttttdddddddTTTTTTTTT........................',
        '.TddtttdddttttddddddddTTTTTTTTTTTTTTTTT.....................',
        'TTdddddddddddddddddddTTTTTTTTTTTTTTTTTTT....................',
        'TTTddddddddddddTTTTTTTTTTTTTTTTTTTTTTTTT....................',
        '.TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT.....................',
        '....TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT........................',
      ],
    },
    /* олгой-хорхой: тело рыжеет, кольца в тёмно-красный, пасть алая */
    olgoi_khorkhoi: { base: 'sandworm', tint: { t: 'o', d: 'R', M: 'r', R: 'D', T: 'O' } },
    /* стрелок: широкополая шляпа, усы, красный платок, светлый плащ-пыльник, длинное ружьё (56×58) */
    gunslinger: {
      hd: true, unit: 2,
      rows: [
        '..................DDDDDDDDDD............................',
        '.................DDDDDDDDDDDD...........................',
        '.................DDDDDDDDDDDD...........................',
        '.................DDDDDDDDDDDD...........................',
        '.................DDYYYYYYYYDD...........................',
        '..........DDDDDDDDDDDDDDDDDDDDDDDDDD....................',
        '.........DDDDDDDDDDDDDDDDDDDDDDDDDDDD...................',
        '..................ssssssssssss..........................',
        '.................ssssssssssssss.........................',
        '.................ssssswkwsswkws.........................',
        '.................ssssswkwsswkws.........................',
        '.................ssssssssssssss.........................',
        '.................ssssssNNNNNsss.........................',
        '..................ssssssssssss..........................',
        '...................ssssssssss...........................',
        '..................rrrrrrrrrrrr..........................',
        '..............TTTTrrrrrrrrrrrrTTTT......................',
        '............TTTTTTTTTTTTTTTTTTTTTTTT....................',
        '............TTTTTTTTTTTTTTTTTTTTTTTT....................',
        '...........TTTTTTTTTTTTTTTTTTTTTTTTTT...................',
        '..........TTTTTTTTTTTTTTTTTTTTTTTTTTTT..................',
        '..........TTTTTTTTTTTTTTTTTTTTTTTTTTTT..................',
        '..........TTTTTTTTTTTTTTTTTTTTTTTTTTTT..................',
        '..........TTTTTTTTTTTTTTTTTTTTTTTTTTTT..................',
        '..........TTTTTTTTTTTTNNNNsssssNlllllEEEEEEEEEEEEEEEEEEE',
        '..........TTTTTTTTTTTTNNNNsssssNllllllllllllllllllllllll',
        '..........TTTTTTTTTTTTNNNNsssssNlllllEEEEEEEEEEEEEEEEEEE',
        '..........TTTTTTTTTTTTNNNNsssssNlllllTTTTsssss..........',
        '..........TTTTTTTTTTTTNNNNNNNNTTTTTTTTTTTsssss..........',
        '..........TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTsssss..........',
        '..........TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTsssss..........',
        '..........TTTTTTTTTTTTTTTTTTTTTTTTTTTT..................',
        '..........TTTTTTTTTTTTTTTTTTTTTTTTTTTT..................',
        '..........TTTTNNNNNNNNNyyNNNNNNNNNTTTT..................',
        '..........TTTTNNNNNNNNNyyNNNNNNNNNTTTT..................',
        '..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................',
        '..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................',
        '..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................',
        '..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................',
        '..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................',
        '..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................',
        '..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................',
        '..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................',
        '..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................',
        '..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................',
        '..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................',
        '..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................',
        '..........TTTTTTTTTTTTuuuuTTTTTTTTTTTT..................',
        '............uuuuuuuuuuuu..uuuuuuuuuuuu..................',
        '............uuuuuuuuuuuu..uuuuuuuuuuuu..................',
        '............uuuuuuuuuuuu..uuuuuuuuuuuu..................',
        '............uuuuuuuuuuuu..uuuuuuuuuuuu..................',
        '............uuuuuuuuuuuu..uuuuuuuuuuuu..................',
        '............uuuuuuuuuuuu..uuuuuuuuuuuu..................',
        '............nnnnnnnnnnnn..nnnnnnnnnnnn..................',
        '............nnnnnnnnnnnn..nnnnnnnnnnnn..................',
        '...........nnnnnnnnnnnnn..nnnnnnnnnnnnn.................',
        '...........NNNNNNNNNNNNN..NNNNNNNNNNNNN.................',
      ],
    },
    /* охотник за головами: плащ бордовый, платок золотой, оптика на стволе, патронташ через грудь */
    bounty_hunter: { base: 'gunslinger', tint: { T: 'R', r: 'Y', N: 'n', u: 'e' }, extra: [[40, 23, 'E'], [41, 23, 'E'], [42, 23, 'E'], [43, 23, 'E'], [44, 23, 'E'], [45, 23, 'E'], [46, 23, 'E'], [40, 22, 'c'], [41, 22, 'c'], [42, 22, 'c'], [43, 22, 'c'], [44, 22, 'c'], [45, 22, 'c'], [46, 22, 'c'], [40, 21, 'E'], [41, 21, 'E'], [42, 21, 'E'], [43, 21, 'E'], [44, 21, 'E'], [45, 21, 'E'], [46, 21, 'E'], [12, 19, 'y'], [13, 19, 'y'], [14, 20, 'y'], [15, 20, 'y'], [16, 21, 'y'], [17, 21, 'y'], [18, 22, 'y'], [19, 22, 'y'], [20, 23, 'y'], [21, 23, 'y']] },
    /* коатль: пернатый змей, золотые крылья, зелёное тело со светлым брюхом, гребень, раскрытая пасть (композитор) (64×60) */
    couatl: {
      hd: true, unit: 2,
      rows: [
        '.......................................yyyyyyyyy................',
        '.....................................yyyyyyyyyyy................',
        '....................................yyyyyyyyyggggg..............',
        '....................................yyyyyyyygggggggg............',
        '....................................yyyyyyggggggggggg...........',
        '....................................yyyygggggggggggggg..........',
        '.....................................gggggggggggwwggggg...ggg...',
        '.....................................gggggggggggwkggggggggggg...',
        '.....yY..............................gggggggggggggggggggggggg...',
        '.....yyY.............................ggggggggggggggRwwRRwwR.....',
        '....yyyYY...........................gggggggggggggggRwwRRwwR.....',
        '....yyyyYYY.........................gggggggggggggggRwwRRww......',
        '...yyyyyyYYY.......................ggggggggggggggggggRRRRR......',
        '...yyyyyyYYYY.....................gggggggggggggggg.ggggRRR......',
        'y.yYyyyyyyYYYY....................gggggggggg.......ggggggg......',
        'yyyyYYyyyyyYYYY..................ggggggggggg.......ggggggggg....',
        'yyyyyyYYyyyyYYYY.................ggggghhggg.....................',
        'yyyyyyyyYYyyyYYYYY...............gggghhhhg......................',
        'yyyyyyyyyyYyyyYYYYY..............gggghhhhg......................',
        'yyyyyyyyyyyYYyyYYYYY............ggggghhhhg......................',
        'yyyyyyyyyyyyyYYYYYYYY...........gggghhhhgg...................YYY',
        '.yyyyyyyyyyyyyyYYYYYYY..........gggghhhhg..................YYYy.',
        '.yyyyyyyyyyyyyyyyYYYYYYY........gggghhhhg................YYYYyy.',
        '..yyyyyyyyyyyyyyyyYYYYYYY.......gggghhhhg..............YYYYYYyy.',
        '...yyyyyyyYYYyyyyyyYYYYYYY......ggghhhhgg............YYYYYYYyyy.',
        '...yyyyyyyyyyYYYyyyyYYYYYYY.....ggghhhhggg.........YYYYYYYYyyyy.',
        '....yyyyyyyyyyyyYYYyyYYYYYYY....ggghhhhggg......YYYYYYYYYYYYYYY.',
        '.....yyyyyyyyyyyyyyYYYYYYYYYYY...ggghhhhggg...YYYYYYYYYYYYyyyyyy',
        '......yyyyyyyyyyyyyyyyYYYYYYYYY..ggghhhhggg.YYYYYYYYYYyyyyyyyyyy',
        '.......yyyyyyyyyyyyyyyyyYYYYYYYY..ggghhhhgggYYYYYYYYyyyyyyyyyyyy',
        '.......yyyyyyyyyyyyyyyyyyYYYYYYYY.ggghhhhgggYYYYYYyyyyyyyyyyyyyy',
        '........yyyyy.yyyyyyyyyyyYYYYYYYYY.ggghhhhggYYYYYyyyyyyyyyyyyyyy',
        '.........yyyy...yyyyyyyyyyYYYYYYYYYggghhhhggYYYyyyyyyyyyyyyyyyyy',
        '.........yyyy.....yyyyyyyyyYYYYYYy.gggghhhhgYyyYYYYYYYYYyyyyyyy.',
        '....................yyyyyyyyYYYYy..gggghhhhgyyyyyyyyyyyyYyyyyy..',
        '.....................yyyyyyyyYYyy.ggggghhhhgyyyyyyyyyyyyyyyy....',
        '.......................yyyyyyyyy..gggghhhhggyyyyyyyyyyyyyyyy....',
        '.........................yyyyyyy..gggghhhhgyyyyyyyyyyyyyyyy.....',
        '...........................yyyy...gggghhhhgyyyyyyyyyyyyyyy......',
        '.............................yy..ggggghhhhgyyyyy...yyyyyy.......',
        '................................ggggghhhhggyy......yyyy.........',
        '...............................gggggghhhhg.........yyyy.........',
        '...............................ggggghhhhhg..........yy..........',
        '..............................ggggghhhhhg.......................',
        '.............................gggggghhhhh........................',
        '...........................ggggggghhhhh.........................',
        '..........................ggggggghhhhhg.........................',
        '........................gggggggghhhhhg..........................',
        '......................gggggggggghhhhh...........................',
        '.....................ggggggggghhhhhh............................',
        '..................gggggggggghhhhhhhg............................',
        '...............gggggggggggghhhhhhhg.............................',
        '...........gggggggggggggghhhhhhhh...............................',
        '.........gggggggggggggghhhhhhhhg................................',
        '........ggggggggggggghhhhhhhhg..................................',
        '..gggggggggggggggghhhhhhhhhh....................................',
        '.ggggggggggggghhhhhhhhhhhhg.....................................',
        '.ggggggggggghhhhhhhhhhhhg.......................................',
        '.gggggggggghhhhhhhhhhhg.........................................',
        '.gggggggggghhhhhhhg.............................................',
      ],
    },
    /* багровый коатль: тело в багрянец, брюхо розовое, крылья огненные */
    crimson_couatl: { base: 'couatl', tint: { g: 'M', h: 'm', y: 'f', Y: 'O', R: 'z' } },
  });
})();
