/* ============================================================================
   view/sprites_necropolis_hd.js — существа Некрополиса в крупной сетке (unit 2), стиль Б:
   без контурной линии, тона кладёт рисунок. Собирается скриптом dev/proto/necro_hd.py.
   ========================================================================== */
(function () {
  'use strict';
  H3.Sprites.defineMany({
    /* скелет: череп с глазницами, рёбра, ржавый меч, круглый щит (40×48) */
    skeleton: {
      hd: true, unit: 2,
      rows: [
        '..............iiiiiiiii.................',
        '............iiiiiiiiiiiii...............',
        '...........iiiiiiiiiiiiiii......O.......',
        '...........iiIIIIIIIIIIIii......O.......',
        '...........iiIzzzIIIzzzIii.....ONO......',
        '...........iiIzzzIIIzzzIii.....ONO......',
        '...........iiIIIIIIIIIIIii.....ONO......',
        '............iIIIIzzIIIIIi......ONO......',
        '............iiIIIIIIIIIii......ONO......',
        '.............IiIiIiIiIiI.......ONO......',
        '..............IIIIIIIII........ONO......',
        '................III............ONO......',
        '.........iii....III....iii.....ONO......',
        '.........iii....III....iii.....ONO......',
        '...DDDDDiIIi..iiIIIii..iIIi....ONO......',
        '..DNNNNNDIIi.iiiiiiiii.iIIi....ONO......',
        '..DNNNNNDIIi.iiiiiiiii.iIIi....ONO......',
        '.DNNNNNNNDIi.iIzzzzzIi.iIIi....ONO......',
        '.DNNNNNNNDIi.iiiiiiiii.iIIi....ONO......',
        '.DNNNNNNNDIi.iiiiiiiii.iIIi....ONO......',
        '.DNNNeNNNDIi.iIzzzzzIi.iIIi....ONO......',
        '.DNNeeeNNDIi.iiiiiiiii.iIIi....ONO......',
        '.DNNeeeNNDIi.iiiiiiiii.iIIi....ONO......',
        '.DNNNeNNNDIi.iIzzzzzIi.iIIi....ONO......',
        '.DNNNNNNNDIi.iiiiiiiii.iIIi....ONO......',
        '.DNNNNNNNDIi.iiiiiiiii.iIIi....ONO......',
        '.DNNNNNNNDIi..iIzzzIi..iIIi....ONO......',
        '..DNNNNNDIIi...iiiii...iIIi....ONO......',
        '..DNNNNNDIIi...iiiii...iIIi....ONO......',
        '...DDDDDiIIi....III....iIIi....ONO......',
        '.........ii...iiIIIii...ii..DDDDDDDDD...',
        '..............iIIIIIi..........NNN......',
        '..............iiiiiii..........NNN......',
        '..............III.III..........NNN......',
        '..............III.III..........NNN......',
        '..............III.III..........NNN......',
        '..............iIi.iIi..........NNN......',
        '..............iIi.iIi..........NNN......',
        '..............iIi.iIi...................',
        '..............iIi.iIi...................',
        '..............iIi.iIi...................',
        '..............III.III...................',
        '..............III.III...................',
        '..............III.III...................',
        '..............iIi.iIi...................',
        '..............iIi.iIi...................',
        '.............iiii.iiii..................',
        '.............IIII.IIII..................',
      ],
    },
    /* скелет-воин: шлем и клинок из стали, красный щит */
    skeleton_warrior: { base: 'skeleton', tint: { O: 'l', N: 'R' }, extra: [[19, 0, 'e'], [20, 0, 'e'], [18, 1, 'e'], [21, 1, 'e'], [17, 2, 'e'], [22, 2, 'e']] },
    /* ходячий мертвец: сгорбленный, руки вперёд, рваная одежда, кость наружу (40×48) */
    walking_dead: {
      hd: true, unit: 2,
      rows: [
        '..............GGGGGGGGG.................',
        '............GGhhhhhhhhhGG...............',
        '...........GhhhhhhhhhhhhhG..............',
        '...........GhhhGGhhhhGGhhG..............',
        '...........GhhhGzhhhhGzhhG..............',
        '...........GhhhhhhhhhhhhhG..............',
        '...........GhhhhGGGGGhhhhG..............',
        '............GhhhhhhhhhhhG...............',
        '.............GGGhhhhhGGG................',
        '................GhhhG...................',
        '............HHHHHhhhHHHHH...............',
        '............HHHHHhhhHHHHH...............',
        '..........HHHHHHHhhhHHHHHHH.............',
        '..........HHHHHHHhhhHHHHHHH.............',
        '.........iIHHDDHHHHHHHHDDHHH............',
        '.........iIHHDDHHHHHHHHDDHHH............',
        '........HiIHDDDHHHHHHHHDDDHHHHhhhhhh....',
        '........HiIHDDDHHHHHHHHDDDHHHHhhhhhh....',
        '........HiIHDDHHHHHHHHHHDDHHHhhhhhhhh...',
        '........HHHHDDHHHHHHHHHHDDHHHhhhhhhhh...',
        '........HHHHHHHHHHDDDHHHHHHHHhhhGhhhh...',
        '........HHHHHHHHHHDDDHHHHHHHHhhhGhhhh...',
        '........HHHHHHHHHDDDDDHHHHHHHHhhhhhhh...',
        '........HHHHHHHHHDDDDDHHHHHHHHhhhhhhh...',
        '........HHHHHHHHHDDDDDHHHHHHHHhhhGGGh...',
        '........HHHHHHHHHDDDDDHHHHHHHHhhhGGGh...',
        '........HHHHHHHHHHDDDHHHHHHHHHGGG.......',
        '........HHHHHHHHHHDDDHHHHHHHHHGGG.......',
        '........HHHHHHHHHHHHHHHHHHHHHH..........',
        '........HHHHHHHHHHHHHHHHHHHHHH..........',
        '........HHHHDDHHHHHHHHHHHDDHHH..........',
        '........HHHHDDHHHHHHHHHHHDDHHH..........',
        '........HHHHDDDHHHHHHHHHDDDHHH..........',
        '.........HHHDDHHHHHHHHHHDDHHH...........',
        '..........HHHHHHHHHHHHHHHHHH............',
        '...........NNNNNNNNNNNNNNNN.............',
        '...........NNNNNNNNNNNNNNNN.............',
        '...........NnnnnnnnNNnnnnnN.............',
        '...........NnnnnnnnN.NnnnnN.............',
        '...........NnnDDnnnN.NnnnnN.............',
        '...........NnnDDDnnN.NnDDnN.............',
        '...........NnnnDDnnN.NnDDnN.............',
        '...........NnnnnnnnN.NnnnnN.............',
        '...........NnnnnnnnN.NnnnnN.............',
        '...........NNnnnnnNN.NNnnNN.............',
        '...........NNNNNNNNN.NNNNNN.............',
        '..........DDDDDDDDDD.DDDDDDD............',
        '..........DDDDDDDDDD.DDDDDDD............',
      ],
    },
    /* зомби: кожа сереет, одежда в бурый, больше кости */
    zombie: { base: 'walking_dead', tint: { h: 'v', G: 'q', z: 'D', u: 'N' }, extra: [[9, 15, 'i'], [9, 16, 'i'], [9, 17, 'i']] },
    /* привидение: саван с рваным низом, тьма под капюшоном, светящиеся глаза (композитор) (44×48) */
    wight: {
      hd: true, unit: 2,
      rows: [
        '............................................',
        '............................................',
        '............................................',
        '............................................',
        '...................llllll...................',
        '.................llllllllll.................',
        '................llllllllllll................',
        '...............llllllllllllll...............',
        '..............llllllllllllllll..............',
        '..............llllllllllllllll..............',
        '..............llllllzzzzllllll..............',
        '.............lllllzzzzzzzzlllll.............',
        '.............llllzzzzzzzzzzllll.............',
        '.............llllzzzzzzzzzzllll.............',
        '.............lllzzzzzzzzzzzzlll.............',
        '.............lllzzzAAzzzzAAzlll.............',
        '.............lllzzzzzzzzzzzzlll.............',
        '..............llzzzzzzzzzzzzll..............',
        '..............lllzzzzzzzzzzlll..............',
        '..............lllzzzzzzzzzzlll.........LLLL.',
        '...............lllzzzzzzzzlll..........LLLL.',
        '................llllzzzzllll...........LLLL.',
        '...........llllllllllllllllllllll......LLLL.',
        '...........lllllllllLLLLlllllllll.llllllll..',
        '..........llllllllLLLLLLLLllllllllllllllll..',
        '......lllllllllllLLLLLLLLLLlllllllllllllll..',
        '...lllllllllllllLLLLLLLLLLLLlllllllllllll...',
        '...lllllllllllllLLLLLLLLLLLLlllllllllllll...',
        '...llllllllllllLLLLLLLLLLLLLLllllllllllll...',
        '...llllllllllllLLLLLLLLLLLLLLllllllllllll...',
        '..lllllllllllllLLLLLLLLLLLLLLlllllll........',
        '..lllll..llllllLLLLLLLLLLLLLLllllll.........',
        '..ll.....llllllLLLLLLLLLLLLLLllllll.........',
        '.........llllllLLLLLLLLLLLLLLllllll.........',
        '.........lllllllLLLLLLLLLLLLlllllll.........',
        '.........lllllllLLLLLLLLLLLLlllllll.........',
        '........lllllllllLLLLLLLLLLlllllllll........',
        '........llllllllllLLLLLLLLllllllllll........',
        '........llllllllllllLLLLllllllllllll........',
        '........llllllllllllllllllllllllllll........',
        '.........llllllllllllllllllllllllllllll.....',
        '.........llllllllllllllllllllllllllllll.....',
        '..........llll..llll..llll..llll..llll......',
        '..........llll..llll..llll..llll..llll......',
        '...........ll....ll....ll....ll....ll.......',
        '...........ll....ll....ll....ll....ll.......',
        '............................................',
        '............................................',
      ],
    },
    /* призрак: саван темнеет, глаза в ядовитый свет */
    wraith: { base: 'wight', tint: { l: 'u', L: 'l', A: 'h' } },
    /* вампир: чёрный плащ с алой подкладкой, бледное лицо, поднятая рука (40×48) */
    vampire: {
      hd: true, unit: 2,
      rows: [
        '..............zzzzzzzzz.................',
        '............zzzzzzzzzzzzz...............',
        '...........zzzzzzzzzzzzzzz..............',
        '...........zzzLLLLLLLLLzzz..............',
        '...........zzLLLLLLLLLLLzz..............',
        '...........zzLLLkLLLkLLLzz..............',
        '...........zzLLLLLLLLLLLzz..............',
        '...........zzlLLLLLLLLLlzz..............',
        '............zlLLrrrrrLLlz...............',
        '............zllLLLLLLLllz........l......',
        '.............zllllllllllz........L......',
        '........RRR...zzlllllzz...RRR...LLL.....',
        '.......RRRRR.zzzzzzzzzzz.RRRRRLLLLLL....',
        '.......RRRRR.zzzzzzzzzzz.RRRRRLLLLLL....',
        '.......RRRRRzzzzzzzzzzzzzRRRRR.LLl......',
        '.......RRRRzzzzzzzzzzzzzzzRRRR.LLl......',
        '.......RRRzzzzzzzzzzzzzzzzzRRR.LLl......',
        '.......RRRzzzzzzzzzzzzzzzzzRRR.LLl......',
        '......RRRRzzzzzzzzzzzzzzzzzRRRRLLl......',
        '......RRRRzzzzzzzzzzzzzzzzzRRRRLLl......',
        '......RRRRzzzzzzzzzzzzzzzzzRRRRLLl......',
        '......RRRRzzzzzzzzzzzzzzzzzRRRRLLl......',
        '......RRRRzzzzzzzzzzzzzzzzzRRRRLLl......',
        '......RRRRzzzzzzzzzzzzzzzzzRRRRLLl......',
        '......RRRRzzzzzzzzzzzzzzzzzRRRRLLl......',
        '......RRRRzzzzzzzzzzzzzzzzzRRRRLLl......',
        '......RRRRzzzzzzzzzzzzzzzzzRRRR.........',
        '......RRRRzzzzzzzzzzzzzzzzzRRRR.........',
        '......rRRRzzzzzzzzzzzzzzzzzRRRr.........',
        '......rRRRzzzzzzzzzzzzzzzzzRRRr.........',
        '......rRRRzzzzzzzzzzzzzzzzzRRRr.........',
        '......rRRRRzzzzzzzzzzzzzzzRRRRr.........',
        '......rrRRRRzzzzzzzzzzzzzRRRRrr.........',
        '......rrRRRRzzzzzzzzzzzzzRRRRrr.........',
        '......rrrRRRRRzzzzzzzzzRRRRRrrr.........',
        '.......rrrrRRRRRzzzzzRRRRRrrrr..........',
        '........rrrrrrRRRzzzRRRrrrrrr...........',
        '..........rrrrrrrzzzrrrrrrr.............',
        '..............zzzzzzzzz.................',
        '..............zzz...zzz.................',
        '..............zzz...zzz.................',
        '..............zzz...zzz.................',
        '..............zzz...zzz.................',
        '..............zzz...zzz.................',
        '..............zzz...zzz.................',
        '..............zzz...zzz.................',
        '.............zzzz...zzzz................',
        '.............zzzz...zzzz................',
      ],
    },
    /* лорд вампиров: подкладка в пурпур, седые виски, золотая застёжка */
    vampire_lord: { base: 'vampire', tint: { r: 'p', R: 'P' }, extra: [[13, 4, 'l'], [13, 5, 'l'], [24, 4, 'l'], [24, 5, 'l'], [19, 12, 'y'], [20, 12, 'y']] },
    /* лич: череп в капюшоне, пурпурная мантия с магическим знаком, посох с черепом (44×48) */
    lich: {
      hd: true, unit: 2,
      rows: [
        '.................PPPPPPPPP..........hhh.....',
        '...............PPPPPPPPPPPPP.......hhhhh....',
        '..............PPPPPPPPPPPPPPP.......iii.....',
        '..............PPPPxxxxxxxPPPP......iiiii....',
        '..............PPPxiiiiiiixPPP.....iiiiiii...',
        '..............PPPxiiiiiiixPPP.....iizizii...',
        '..............PPPxihhiihhixPP......iiiii....',
        '..............PPPxiiiiiiixPPP.......iii.....',
        '..............PPPxIiIiIiIxPPP.......DND.....',
        '..............PPPPxIIIIIxPPPP.......DND.....',
        '...............PPPPxxxxxPPPP........DND.....',
        '................PPPPPPPPPPP.........DND.....',
        '.............PPPPPxxxxxxxPPPPP......DND.....',
        '.............PPPPPxxxxxxxPPPPP......DND.....',
        '............PPPxxxxxxxxxxxxxPPP.....DND.....',
        '............PPPxxxxxxxxxxxxxPPP.....DND.....',
        '...........PPxxxxxxxxxxxxxxxxxPP....DND.....',
        '...........PPxxxxxxxxxxxxxxxxxPP....DND.....',
        '...........PxxxxxxxxxxxxxxxxxxxP....DND.....',
        '...........PxxxxxxxxxxxxxxxxxxxP....DND.....',
        '...........PxxxPxxxxxxxxxxxPxxxP....DND.....',
        '...........PxxxPxxxxxxxxxxxPxxxP....DND.....',
        '...........PxxxPxxxxaaaxxxxPxxIIIIIIDND.....',
        '...........PxxxPxxxxaaaxxxxPxxIIIIIIDND.....',
        '...........PxxxPxxxaAAAaxxxPxxiiiiiiDND.....',
        '...........PxxxPxxxaAAAaxxxPxxiiiiiiDND.....',
        '...........PxxxPxxxxaaaxxxxPxxiiiiiiDND.....',
        '...........PxxxPxxxxaaaxxxxPxxiiiiiiDND.....',
        '...........PxxxPxxxxxxxxxxxPxxIIIIIIDND.....',
        '...........PxxxPxxxxxxxxxxxPxxIIIIIIDND.....',
        '...........PxxxPPxxxxxxxxxPPxxxP....DND.....',
        '...........PxxxPPxxxxxxxxxPPxxxP....DND.....',
        '...........PxxxxPPPPPPPPPPPxxxxP....DND.....',
        '...........PxxxxxxxxxxxxxxxxxxxP....DND.....',
        '...........PxxxxxxxxxxxxxxxxxxxP....DND.....',
        '...........PxxxxxxxxxxxxxxxxxxxP....DND.....',
        '...........PxxxxxxxxxxxxxxxxxxxP....DND.....',
        '...........PxxxxxxxxxxxxxxxxxxxP....DND.....',
        '...........PxxxxxxxxxxxxxxxxxxxP....DND.....',
        '...........PxxxxxxxxxxxxxxxxxxxP....DND.....',
        '...........PxxxxxxxxxxxxxxxxxxxP....DND.....',
        '...........PxxxxxxxxxxxxxxxxxxxP....DND.....',
        '...........PxxxxxxxxxxxxxxxxxxxP....DND.....',
        '...........PxxxxxxxxxxxxxxxxxxxP....DND.....',
        '...........PxxxxxxxxxxxxxxxxxxxP....DND.....',
        '...........PPxxxxxxxxxxxxxxxxxPP....DND.....',
        '...........PPPxxxxxxxxxxxxxxxPPP....DND.....',
        '...........PPPPPPPPPPPPPPPPPPPPP....DND.....',
      ],
    },
    /* могучий лич: мантия чернеет, знак и свет посоха ярче */
    power_lich: { base: 'lich', tint: { x: 'P', P: 'z', a: 'A', h: 'A' } },
    /* чёрный рыцарь: чёрный конь с алыми глазами, чёрные латы, меч, щит с черепом (композитор) (64×56) */
    black_knight: {
      hd: true, unit: 2,
      rows: [
        '...........................RRRRRRRR.............................',
        '...........................RRRRRRRR.............................',
        '...........................RRRR.RR...........ee.................',
        '............................RR..............eee.................',
        '...........................................eell.................',
        '............................EEEEEE........eele......zzz.........',
        '...........................EEeeEEEE.......eel......zzzzzz.......',
        '...........................EeeeeEEE......eele....zzzzzzzz.......',
        '...........................EeeeeEEE.....eele....zzzzzzzzz.......',
        '...........................ErrrrrrE.....eel...zzzzzzzzzzzz......',
        '...........................ErrrrrrE....eel...zzzzzzzzzz..z......',
        '...........................EEEEEEEE...eele...zzzzzzzz...zzzz....',
        '...........................eEEEEEEE..eeel....zzzzzzz..zzzzzzzz..',
        '..........................EeeeeEEEEE.eel.....zzzzzz..zzzzzrzzzz.',
        '..........................eeeeeeEEEEeele......zzzzzzzzzzzzzDDDD.',
        '.........................EeeeeeeEEEeeel........zzzzzzzzzzzzDDDD.',
        '.........................EeeeeeuuYYYYYYY......zzzzzzzzzzzzzDDDD.',
        '.........................EeeeeuuuYYYYYYY......zzzzzzzzzzzzzDDDD.',
        '.........................EeeeuuuuuuEE.........zzzzzzzzzzzzzz....',
        '.........................EeeeuuuuuuEE........zzzzzzzzzzzzz......',
        '............zzz........EEEEeeuuuuuuEE.........zzzzzzzzzzzz......',
        '........zzzzzzz........EEEEeeuuuuuuE..........zzzzzzzzzzzz......',
        '......zzzzzzzzz........EEEEEeeuuuuEE..........zzzzzzzzzzzzz.....',
        '......zzzzzzzzz.......EEEEEEEEEuuEE.......zzzzzzzzzzzzzzzz......',
        '......zzziiiizz.......EEEEEEEEEEEE.......zzzzzzzzzzzzzzzzz......',
        '......zzziiiizzz......EEEEEE.EEEE.......zzzzzzzzzzzzzzzzzz......',
        '......zzziiiizzz......EEEEEERRRRRR.....zzzzzzzzzzzzzzzzzz.......',
        '......zzziiiizzz.....EEEEEERRRRRRRRRR.zzzzzzzzzzzzzzzzzzz.......',
        '.......zzzzzzzzz....zEEEEEExxxxxxxRRRRzzzzzzzzzzzzzzzz..........',
        '.......zzzzzzzzz..zzzEEEEEExxxxxxxxxxRRzzzzzzzzzzzzzzz..........',
        '.......zzzzzzzz.zzzzEEEEEEExxxxxxxxxxxRzzzzzzzzzzzzzzz..........',
        '.......zzzzzz.DDDDDDEEEEEExxxxxxxxxxxxuzzzzzzzzzzzzzzz..........',
        '.......zzzzDDDDDDDDuEEEEEExxxxxxxxxxxuuuuzzzzzzzzzzzzz..........',
        '.......zzDDDDDDDDDuEEEEEEExxxxxxxxuuuuuuuuzzzzzzzzzzz...........',
        '.........DDDDDDDDDuEEEEEEuuuuuuuuuuuuuuuuuzzzzzzzzzz............',
        '........DDDDDDDDDDDEEEEEEuuuuuuuuuuuuuuuuzzzzzzzzzz.............',
        '........DDDDDDDDDDDEEEEEEuuuuuuuuuuuuuuzzzzzzzzzzz..............',
        '.......DDDDDDDDDDDEEEEEEEuuuuuuuuuuuzzzzzzzzzzzz................',
        '......DDDDDDDDDDDDEEEEEEDDDzzzzzzzzzzzzzzzzzzzz.................',
        '......DDDDDDDDDDDDuuuuEEDDDzzzzzzzzzzzzzzzzzzzz.................',
        '.....DDDDDDDDDDDDuuuuuuEDDDzzzzzzzzzzzzzzzzzzz..................',
        '....DDDDD..DDDDDDuuuuuuDDDzzzzzzzzzzzzzzzzzz....................',
        '....DDDD....DDDDDDuuuuDDDDDzzzzzzzzzzzzzzz.zzzzzz...............',
        '...DDDDD.....DDDDDDDDDDDDDDzzzzzzzzzzzzzz..zzzzzz...............',
        '...DDDD......DDDDDDDDDDDDDDzzzzzzzzzzzzzz..zzzzzz...............',
        '..DDDDD......DDDDDD..DDDDDD........zzzzzz..zzzzzz...............',
        '..DDDD.......DDDDDD..DDDDDD........zzzzzz..zzzzzz...............',
        '...DD........DDDDDD..DDDDDD........zzzzzz..zzzzzz...............',
        '.............DDDDDD..DDDDDD........zzzzzz..zzzzzz...............',
        '.............DDDDDD..DDDDDD........zzzzzz..zzzzzz...............',
        '.............DDDDDD..DDDDDD........zzzzzz..zzzzzz...............',
        '.............DDDDDD..DDDDDD........zzzzzz..zzzzzz...............',
        '............uuuuuuu.uuuuuuu.......uuuuuuu.uuuuuuu...............',
        '............uuuuuuu.uuuuuuu.......uuuuuuu.uuuuuuu...............',
        '............uuuuuuu.uuuuuuu.......uuuuuuu.uuuuuuu...............',
        '................................................................',
      ],
    },
    /* рыцарь смерти: латы в пурпур, попона алая, плюмаж пурпурный */
    dread_knight: { base: 'black_knight', tint: { E: 'P', e: 'p', R: 'r', x: 'R' } },
    /* костяной дракон: череп с рогами, крылья-спицы с обрывками перепонки, рёбра, хвост (композитор) (64×62) */
    bone_dragon: {
      hd: true, unit: 2,
      rows: [
        '...........................II...................................',
        '...............II.....PPPPPii............................II.....',
        '.............PPPiPPPPPPPPPPiI.................I..........II.....',
        '.....II.PPPPPPPPiPPPPPPPPPPiI.................II.........II.....',
        '.....IiPPPPPxxxPPiPPPPPPPPPiI..................II........II.....',
        '.....IIiPxxxxxxPPiPPPPPPPPPiI...................III.....IIII....',
        '......IPixxxxxxPPiPPPPPPPPPiI...................IIII....IIII....',
        '.......IixxxxxxxPPiPPPPPPPPiI....................IIII...IIII....',
        '........IixxxxxxPPiPPPPPPPPiI....................IIIiiiiii......',
        '........IIixxxxxPPiPPPPPPPPiI.....................iiiiiiiiii....',
        '.........IIixxxxxPPiPPPPPPPiI....................iiiiiiiiiiii...',
        '..........IixxxxxPPiPPPPPPIiI....................iiiiiiiiiiii...',
        '...........IixxxxxPiPPPPPPIiI...................iiiiiihhiiiiii..',
        '...........IIixxxxPPiPPPPPIiI...................iiiiiihiiiiiii..',
        '............IIixxxPPiPPPPPIiI...................iiiiiiiiiiiiii..',
        '.............IixxxxPiPPPPPIiI...................iiiiiiiiiiIIii..',
        '..............IixxxPPiPPPPiI.....................iiiiiiiiiIIIII.',
        '..............IIixxPPiPPPIiI.....................iiiiiiiiiIIIII.',
        '...............IIixxPiPPPIiI.....................IiiiiiiiiIII...',
        '................IixxPPiPPIiI....................IiiiiiiiiiI.....',
        '.................IixPPiPPIiI...................IIiiiI...........',
        '..................IixPiPPIiI...................IiiiiI...........',
        '..................IIiPPiPIiI..................IIiiiI............',
        '...................IixPiPIiI..................IiiiI.............',
        '....................IiPiPIiI.................IiiiiI.............',
        '.....................xiPiIiI................IIiiiI..............',
        '......................xiiPiI................IiiiII..............',
        '......................IiiPiI...............IiiiiI...............',
        '.......................IiiiI...............IiiiI................',
        '........................Iii...............IiiiII................',
        '.........................IIIIIIIIII......IiiiiI.................',
        '......................IIIIIIIIIIIIIIII...IiiiII.................',
        '...................iiIIiizziizziizziiIIiIiiiiI..................',
        '..................IiIIzizzzizzzizzzizzIiIiiiI...................',
        '.................IIizzzizzzizzzizzzizzziIiiII...................',
        '...............iiiiiiiiiiiiiiiiiiiiiiiiiIIIIi...................',
        '...............iiiiiiiiiiiiiiiiiiiiiiiiiiiiii...................',
        '................IIzizzzizzzizzzizzzizzzizzII....................',
        '...............IIIzizzzizzzizzzizzzizzzizzII....................',
        '..............IIIIzizzzizzzizzzizzzizzzizzII....................',
        '.............IIIIIIizzzizzzizzzizzzizzzizII.....................',
        '............IIIIIIIizzzizzzizzzizzzizzziIII.....................',
        '...........IIIII..IiIIzizzzizzzizzzizzIiII......................',
        '..........IIIII....iIIIiIzzizzzizzziIIIi........................',
        '.........IIIII.....IIIIIIIIiIIIiIIIIIIII........................',
        '........IIIII......IIIII.IIIIIIIIIIIIIII........................',
        '.......IIIII.......IIIII...........IIIII........................',
        '......IIIII........IIIII...........IIIII........................',
        '.....IIIII.........IIIII...........IIIII........................',
        '....IIIII..........IIIII...........IIIII........................',
        '...IIIII..........IIIIII..........IIIIII........................',
        '..IIIII...........IIIIII..........IIIIII........................',
        '..IIII............IIIIII..........IIIIII........................',
        '..III.............IIIIII..........IIIIII........................',
        '..III.............IIIIII..........IIIIII........................',
        '.III............iiiiiiiiii......iiiiiiiiii......................',
        '.III............iiiiiiiiii......iiiiiiiiii......................',
        '.III............iiiiiiiiii......iiiiiiiiii......................',
        '.II.............................................................',
        '................................................................',
        '................................................................',
        '................................................................',
      ],
    },
    /* призрачный дракон: кость в мятный свет, перепонка в бирюзу */
    ghost_dragon: { base: 'bone_dragon', tint: { i: 'v', I: 'q', P: 'Q', x: 'q', h: 'A' } },
  });
})();
