"""PDF коммерческого предложения. Разметка как в КП компании: разделы, НДС 5%, оплата 60/40."""
from __future__ import annotations

from datetime import date
from pathlib import Path

from fpdf import FPDF
from fpdf.fonts import FontFace

from .pricing import PRICES, Line, Params, Totals, duration_days

GOLD = (138, 106, 47)
COMPANY = ["Aureum Construction", "Business Bay, The Citadel Tower, Office 203",
           "Dubai, United Arab Emirates", "+971 58 584 3691 | info@aureumgroup.ae"]


def _latin(s: str) -> str:
    """Встроенные шрифты PDF знают только Latin-1: заменяем остальное."""
    return s.replace("−", "-").replace("–", "-").replace("—", "-").encode("latin-1", "replace").decode("latin-1")


def _n(v: float) -> str:
    s = f"{v:,.2f}".rstrip("0").rstrip(".")
    return s.replace(",", " ")


def render_pdf(p: Params, lines: list[Line], t: Totals, out: Path, discount_pct: float = 0) -> Path:
    pdf = FPDF(format="A4")
    pdf.set_margins(15, 15, 15)
    pdf.set_auto_page_break(True, 18)
    pdf.add_page()

    pdf.set_font("Times", "", 26)
    pdf.set_text_color(*GOLD)
    pdf.set_char_spacing(4)
    pdf.cell(90, 12, "AUREUM")
    pdf.set_char_spacing(0)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(60, 60, 56)
    y0 = pdf.get_y()
    for i, row in enumerate(COMPANY):
        pdf.set_xy(105, y0 + i * 4)
        pdf.cell(90, 4, row, align="R")
    pdf.set_xy(15, y0 + 12)
    pdf.set_font("Helvetica", "", 7)
    pdf.set_char_spacing(3)
    pdf.cell(90, 4, "CONSTRUCTION")
    pdf.set_char_spacing(0)
    pdf.set_draw_color(169, 133, 63)
    pdf.set_line_width(0.6)
    pdf.line(15, y0 + 19, 195, y0 + 19)

    pdf.set_xy(15, y0 + 24)
    pdf.set_text_color(29, 31, 28)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, _latin(f"Offer: {p.offer or '-'}"), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Date: {date.today():%d.%m.%Y}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 9.5)
    pdf.multi_cell(0, 5, "Aureum Construction invites you to get familiar with the quotation for roof repair "
                         "and waterproofing works as follows:", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    pdf.set_font("Times", "B", 11)
    pdf.cell(0, 7, "COST ESTIMATE", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)

    sect = FontFace(emphasis="BOLD", fill_color=(237, 237, 232))
    sub = FontFace(emphasis="BOLD", fill_color=(243, 242, 238))
    tot = FontFace(emphasis="BOLD", fill_color=(233, 230, 220))
    grand = FontFace(emphasis="BOLD", fill_color=(220, 212, 191))
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_draw_color(207, 207, 201)
    pdf.set_line_width(0.2)
    with pdf.table(col_widths=(7, 88, 17, 14, 25, 29), line_height=4.6,
                   text_align=("CENTER", "LEFT", "RIGHT", "CENTER", "RIGHT", "RIGHT"),
                   headings_style=FontFace(emphasis="BOLD", fill_color=(227, 225, 216))) as table:
        table.row(["#", "Description", "Qty", "Unit", "Price, AED", "Cost, AED"])
        for si, s in enumerate(p.sections):
            r = table.row()
            r.cell(_latin(f"{si + 1}. Roof repair and waterproofing works ({s.name.lower()})"),
                   colspan=6, align="C", style=sect)
            for i, l in enumerate([l for l in lines if l.section == si], 1):
                table.row([str(i), PRICES[l.code]["en"], _n(l.qty), PRICES[l.code]["unit"], _n(l.price), _n(l.cost)])
            r = table.row()
            r.cell("Subtotal", colspan=5, align="R", style=sub)
            r.cell(_n(t.by_section[si]), style=sub)

        def total_row(label: str, value: str, style: FontFace) -> None:
            r = table.row()
            r.cell(label, colspan=5, align="R", style=style)
            r.cell(value, style=style)

        if len(p.sections) > 1 or t.discount:
            total_row("Total", _n(t.subtotal), tot)
        if t.discount:
            total_row(f"Discount ({_n(discount_pct)}%)", "-" + _n(t.discount), tot)
        total_row("VAT (5%)", _n(t.vat), tot)
        total_row("Grand total, AED", _n(t.grand), grand)

    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 9.5)
    pdf.cell(0, 5, "Payment schedule:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9.5)
    pdf.cell(0, 5, "60% - within 2 days of signing the contract", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, "40% - after completion of 100% of works", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 9.5)
    pdf.cell(0, 5, f"Duration: {duration_days(p)} working days", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, f"Warranty: {p.warranty} years", new_x="LMARGIN", new_y="NEXT")
    pdf.set_auto_page_break(False)
    pdf.set_y(-14)
    pdf.set_font("Helvetica", "", 7)
    pdf.set_text_color(140, 140, 132)
    pdf.cell(0, 4, "Draft generated by Aureum Quote prototype")

    out.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(out))
    return out
